### ISSUE TITLE
Installation on pivCCU failed

### ISSUE THREAD

**Issue by thkl** [thkl/hap-homematic#1]
see https://github.com/thkl/homebridge-homematic/issues/576#issuecomment-607339148

**Comment by v0r73x** [comment]
installation successful with Release 0.2 on pivccu 
but in the opened plugin window I see no content. 
From debugger i gathered some Warnings and 1 Error. Do you need more details out of the debug as well? 
![image](https://user-images.githubusercontent.com/48632087/78248932-cd615280-74ed-11ea-8456-998878f1ec5b.png)

**Comment by v0r73x** [comment]
and this is filtered to css:

![image](https://user-images.githubusercontent.com/48632087/78249128-203b0a00-74ee-11ea-98d0-dec38836a67c.png)

**Comment by v0r73x** [comment]
one additional update - i see a new acessory possible to to add on home (on iphone) so soething is definitly working :) i dont add it because i cannot setup from plugin webgui and dont want to run in issues if i add it know.

**Comment by thkl** [comment]
Yes there are no errors ? There should be some /api/ network requests after loading the page ...

**Comment by v0r73x** [comment]
only the exception with Object what i pasted in 1st screenshot

**Comment by v0r73x** [comment]
![image](https://user-images.githubusercontent.com/48632087/78251617-e66c0280-74f1-11ea-868b-40a761d13be4.png)

**Comment by v0r73x** [comment]
if i cleanup log and refresh the page i get the following 👍 
![image](https://user-images.githubusercontent.com/48632087/78251861-3c40aa80-74f2-11ea-8a19-d34340eb9b99.png)

**Comment by thkl** [comment]
There is no Fav icon yes the other error is Firefox related.  I’ve tested the stuff in chrome and safari

**Comment by v0r73x** [comment]
ok so I use now chrome - before i used firefox  - and now - tadaa it is displaying text :) so the issue is solved here

**Comment by thkl** [comment]
Ok seems like i have to get Firefox for testing :)

**Comment by roe1974** [comment]
@thkl ...... yes please, i am using firefox too ;-)

**Comment by thkl** [comment]
note to myself: avoid using firefox under all circumstances .. js debugging is a bag of pain there
