### ISSUE TITLE
Dimmer Anzeige in HomeKit nicht ad-hoc (mit Homematic IP Dimmer-Steckdose)

### ISSUE THREAD

**Issue by StefanS200** [thkl/hap-homematic#101]
Hallo Team,
Einbindung mit HAP Homematic klappt sehr gut. Bei Aktor „Homematic IP Dimmer-Steckdose“ beobachte ich folgenden Schönheitsfehler beim Dimmen in Home App: Dimmt man mit dem Balken in der Home App, dann wird die Prozentanzeige der Helligkeit in der App fortlaufend (beim Bewegen des Fingers) aktualisiert, das Licht wird aber erst beim Loslassen des Balkens angepasst. Und auch da geht nach Loslassen des Balkens in der Home App der Prozentbalken kurz auf den zuvor aktuell eingestellten Helligkeitswert, ehe er dann auf den den neuen Helligkeitswert Sprint. Dann wird das Licht erst angepasst. 

Nur ein Schönheitsfehler, war bei Rematic Add on aber nicht. 

Danke Euch

**Comment by thkl** [comment]
Hi, 

ja, es ist Absicht, das das Level erst gesetzt wird, wenn sich 500ms keine Änderung ergeben hat. HomeKit liefert mir leider jeden Wert als Event wenn man mit dem Finger den Slider schiebt.
Von 0 auf 50% würde ich an der Stelle 50 Werteänderungen an die CCU senden. Und die CCU an den Aktor. Ich denke, das findet weder die CCU cool, noch der DutyCycle.

Das "Springen" kommt daher, das die CCU beim Ändern von Dimmern auch Zwischenwerte sendet. Wenn ich der CCU sage: dimme auf 50% (von 0) dann geht es 5% ... und der nächste Event sind dann 50% ... Der Balken ist also auf dem Sollwert, bekommt dann den Wert des Anfangs Events (also 5%) und dann noch mal 50% wenn das Dimmen beendet ist.



Ich gebe zu, ich finde das Verhalten auch nicht hübsch, aber ich habe derzeit keine schlaue Idee wie ich das verhindern kann. Ich muss aber auf die Events aus der CCU hören und den Slider setzen, sonst würde HomeKit den Wert des Dimmers nicht anpassen, wenn dieser von Außen (zb Direktverknüpfung) geändert wird.

**Comment by comtel2000** [comment]
Ich teste das mal mit IP. In dem Zusammenhang habe ich noch einen weiteren unschönen Effekt.
Wenn via Homekit von 0 auf bsplw. 10% gedimmt wird, geht der Aktor (HmIP-BSD) immer erst auf 100% und danach auf 10%. Ist das bei HM auch, oder nur bei HmIP?

**Comment by comtel2000** [comment]
Ich schätze, das die 2 characteristics Light ON/OFF + Helligkeit 0-100% parallel arbeiten und bei Dimmern eigentlich nur Helligkeit Events ausgewertet werden müssen?

**Comment by comtel2000** [comment]
ich habe mal den` this.lightBulbService.getCharacteristic(Characteristic.On)` in HomeMaticDimmerAccessory deaktiviert und mit HmIP bzw. HmIP-BSD läuft das Dimmen
 0% auf <100% deutlich besser. Logischer Weise auch mit weniger Rega updates.

**Comment by roe1974** [comment]
> Ich teste das mal mit IP. In dem Zusammenhang habe ich noch einen weiteren unschönen Effekt.
> 
> Wenn via Homekit von 0 auf bsplw. 10% gedimmt wird, geht der Aktor (HmIP-BSD) immer erst auf 100% und danach auf 10%. Ist das bei HM auch, oder nur bei HmIP?

ja ist bei HM auch so ....

**Comment by comtel2000** [comment]
Ich würde das Verhalten des Dimmers an die HUE Logik anpassen (wenn die CCU hier mitspielt):

IST: Helligkeit 0% / AUS
NEU: Schalte EIN-> Helligkeit 10% / EIN  (10% nur via EVE App, Home App setzt beim Einschalten wahrscheinlich parallel auch die 100% Helligkeit)

IST: Helligkeit 0% / EIN (geht vermutlich nur via EVE App)
NEU: Schalte AUS-> Helligkeit 0% / AUS

IST: Helligkeit 80% / AUS (Helligkeit intern gespeichert, CCU setzt beim Ausschalten die Helligkeit auf 0%)
NEU: Schalte EIN-> Helligkeit 80% / EIN

IST: Helligkeit 100% / EIN
NEU: Schalte AUS -> Helligkeit 100% / AUS

IST: Helligkeit 0<>100% / AUS
NEU: Dimme auf 50% -> Helligkeit 50% / EIN

IST: Helligkeit 0<>100% / EIN
NEU: Dimme auf 50% -> Helligkeit 50% / EIN

IST: Helligkeit 0<>100% / EIN
NEU: Dimme auf 0% -> Helligkeit 0% / AUS (EVE schaltet nicht automatisch AUS bei 0% Dimmen)

**Comment by thkl** [comment]
OK ich hab mir mal die Reihenfolge angeschaut, die HomeKit sendet wenn ich eine ausgeschaltete Lampe hoch dimme. Und ja es wird zu erst Characteristic.On auf true gesetzt. Damit wird aktuell das letzte bekannte Level (oder wenn es das nicht gibt 100%) an die CCU gesendet. Das ist vergleichbar mit dem Verhalten des WebUI der CCU. Wenn man dort auf EIN drückt wird auch das OldLevel gesetzt. Nach dem Characteristic.On kommt der erste Wert des Levelsliders ... in dem Falle 0 ... und folgende.

Daher kommt das Verhalten das die Lampe erst voll an geht und dann zurück auf die eingestellte Helligkeit.

Ich habe jetzt den gleichen Timer der den Slider "entprellt" dafür benutzt den On Befehl um 250ms zu verzögern. Da der Timer beim Betätigen des Sliders immer wieder gelöscht und neu gesetzt wird, wird das senden des LastLevels quasi ignoriert und durch den ersten Sliderbefehl überschrieben. Damit ist das Einschaltverhalten 100% -> gewünschte % dann weg.

**Comment by thkl** [comment]
ne oder ;o) https://github.com/thkl/hap-homematic/pull/103

**Comment by comtel2000** [comment]
Hatte da eine sehr ähnliche Idee.. :)

**Comment by thkl** [comment]
mir ist eben aber in Eve aufgefallen: Wenn man in der Detailansicht des Gerätes ist, also wo nur noch On/Off und der Slider sind .. und dann den Slider nach rechts schiebt dann geht On/Off sofort auf On aber dann bleibt dort ein Activity Spinner am drehen .. der ist nicht da wenn man in der Übersicht den Dimmer betätigt.

Diese Spinner sind nur der Indikator wenn HomeKit auf eine Antwort wartet aber ich beantworte sogar noch vor dem setzen des Timers den callback .. *hmm*

**Comment by comtel2000** [comment]
Ja, gleiches Problem hier. Eve springt beim Dimmen und an/aus sehr viel hin und her. Der Spinner verschwindet beim Dimmen nicht, oder teilweise erst sehr spät. Je schneller der Callback kommt, desto mehr events schickt Eve wahrscheinlich..

**Comment by thkl** [comment]
das Springen des Sliders habe ich im PR erklärt da haste zu viel rausgenommen ;)

**Comment by comtel2000** [comment]
Sieht so aus, das mit Ramp Time der Eve Spinner bei Ein/Aus jetzt auch ok ist. Ohne Ramp Time springt Ein/Aus kurz hin und her wenn der Slider bewegt wird. Dann dreht auch der Ein/Aus Spinner endlos weiter.
