### ISSUE TITLE
Funk-Fenster-Drehgriffkontakt HM-Sec-RHS Status

### ISSUE THREAD

**Issue by theo-69** [thkl/hap-homematic#102]
Ich Wechsel gerade schrittweise von RedMatic und mir ist beim integrieren des Funk-Fenster-Drehgriffkontakt HM-Sec-RHS aufgefallen das bei RedMatic der Griff bei gekippt 25% geöffnet anzeigt bei dir hier steht nur geöffnet. kannst du das anpassen?
![IMG_4760](https://user-images.githubusercontent.com/28484958/83777903-431ea180-a68a-11ea-9ae6-3987777daf4b.png)

**Comment by thkl** [comment]
Der Drehgriff mappt in einen normalen Kontakt und der kennt nur auf oder zu .. 
Man könnte dem aber auch wie den normalen Kontakt noch in die Window class mit aufnehmen und dann auf 25% setzen, ja das geht

**Comment by thkl** [comment]
so wirds ;) siehe #112 ich ändere noch die 15 in 25%
