### ISSUE TITLE
HMIP-eTRV wird immer als Favoriten angezeigt.

### ISSUE THREAD

**Issue by Sheldor81** [thkl/hap-homematic#104]
Ich habe bei einem Heizkörperthermostat den Boost Modus über "HAP" eingebunden. 
Genau dieser taucht immer als Favorit auf und lässt sich auch. nur über den Mac aus diesen entfernen.
Doch er taucht trotzdem nach einiger Zeit dann wieder in den Favoriten auf.

**Comment by thkl** [comment]
Ich kann die Favoriten nicht beeinflussen. Ich liefere nur die HomeKit Geräte. Bei einem HM-TC-IT-WM-W-EU hab ich das getestet da geht das.

**Comment by Sheldor81** [comment]
Wenn ich den BoostModus ausschalte funktioniert es und er verschwindet aus den Favoriten.

<img width="256" alt="Bildschirmfoto 2020-06-05 um 17 12 47" src="https://user-images.githubusercontent.com/37243683/83893168-e71e5080-a74f-11ea-8d5b-ca84bfd13869.png">

**Comment by thkl** [comment]
schon klar, ich hab es hier auch mit Boost Schalter probiert.

**Comment by Sheldor81** [comment]
Wenn ich ihn aus den Favoriten entfernen taucht er nach einem Neustart des HAP, direkt wieder unter diesen auf.
Das passiert wenn ich den Boot Modus nicht mit einbinde nicht.

**Comment by timwegenerDE** [comment]
Das ist bei mir auch so. Das scheint aber ein HomeKit Problem zu sein.

Workaround (klappt bei jedem zweiten bis dritten Versuch):
- Geräte Einstellungen öffnen
- Favorit abwählen
- „Geräte“ wählen (Hier findet sich das Thermostat selbst und der Boost Mode)
- Lange auf das Thermostat drücken und einmal durch die Einstellungen scrollen.
- „X“
- Lange auf den Boost Mode und ebenfalls einmal durch die Einstellungen scrollen
- „X“
- „Zurück“
- „X“
- Ggf. wiederholen
