### ISSUE TITLE
programming a thermostat from eve should be possible

### ISSUE THREAD

**Issue by thkl** [thkl/hap-homematic#106]
see last comments from #85

**Comment by thkl** [comment]
Funktionsweise: Es kann in den Einstellungen eines der 3 festen Programme des Thermostats gewählt werden. Die Eve Einstellungen werden dann in dieses Programm im Thermostat gespeichert.

*EINSCHRÄNKUNGEN*

Eve kennt nur Low Temp und Hight Temp .. also quasi wann heizt es nicht , wann heizt es ...

Daher kann ich nicht das Programm aus dem Thermostat lesen und in Eve darstellen. Daher ist das ein OneWay. Eve und HAP merken sich die letzten settings. Wenn diese allerdings in der CCU oder mit anderen Programmen geändert werden, geht das nicht zurück zu eve.


Mit obigem Commit funktioniert das derzeit mit einem HM-TC-IT-WM-W-EU.
Da das Programm im Master Dataset liegt (quasi eine Gerätekonfig ist) wird es erst aus der CCU an das Gerät übertragen, wenn das Gerät das nächste Mal mit der CCU redet)

Für hmIP muss ich erst mal rausfinden wie dort die Programme gespeichert werden.

/cc : @mike4president

**Comment by roe1974** [comment]
wenn man eve nicht nutzt ist der verhalten wie vorher oder ? ... oder wird irgendwas an den werten in der ccu trotzdem geändert ?

**Comment by thkl** [comment]
Eve:

![image](https://user-images.githubusercontent.com/884355/83915250-2b6f1800-a773-11ea-853b-40d342d3ec6b.png)



wird zu : 
![image](https://user-images.githubusercontent.com/884355/83915149-f793f280-a772-11ea-8a73-81f05c3ea4e1.png)

**Comment by thkl** [comment]
> wenn man eve nicht nutzt ist der verhalten wie vorher oder ? ... oder wird irgendwas an den werten in der ccu trotzdem geändert ?

das ist ein eigener Service (HomeMaticProgrammableThermostatAccessory) wenn Du den normalen HomeMaticThermostatAccessory nutzt siehst du das alles eh nicht. Und da die Characteristics nur in Eve bekannt sind wirst du auch nie ein setValue dafür aus Apples Home auslösen.

**Comment by roe1974** [comment]
ah perfekt :)

**Comment by thkl** [comment]
> ah perfekt :)


..ooOOO(seine Version schreibt natürlich ab Januar 2021 heimlich das Programm im Bad um, das es morgens dann kuschelige 12 Grad hat) .... oops laut gedacht ...

**Comment by roe1974** [comment]
😜😜😜😜

**Comment by mike4president** [comment]
https://github.com/thkl/hap-homematic/issues/106#issuecomment-639739869

Brav ;-) Kann ich für die IP Thermostate irgendwie unterstützen (mit glänzendem Halbwissen und irgendwelchen Logfiles?)
