### ISSUE TITLE
Thermostat Heizung Gruppe Problem

### ISSUE THREAD

**Issue by theo-69** [thkl/hap-homematic#107]
Die Thermostat Ventile spinnen noch.
1. Wenn ich auf AUS stelle bleiben die Thermostate auf Automatik, das bedeutet sie schalten dann nach voreingestellten Zeiten ein. Aber aus sollte aus sein. Also Modus Manuell 4,5 Grad.
2. Wechsel ich auf Heizung sollte ja der Manuell Modus aktiviert werden, funktioniert leider auch nicht, es ändert sich nur die Temperatur bleibt aber bei automatisch bzw. springt wieder zurück.

Habe gestern von RedMatic gewechselt und dort hatte es funktioniert.

**Comment by theo-69** [comment]
Ach ja zusätzlich gibt mir RedMatic die Option einen Luftfeuchtigkeitssensor anzuzeigen. Das wäre auch noch eine Option, eventuell auch Temperatur als separater Sensor.

**Comment by mike4president** [comment]
> Ach ja zusätzlich gibt mir RedMatic die Option einen Luftfeuchtigkeitssensor anzuzeigen. Das wäre auch noch eine Option, eventuell auch Temperatur als separater Sensor.

Bei der Heizgruppe geht das doch??

**Comment by theo-69** [comment]
> Bei der Heizgruppe geht das doch schon??

Bei mir nicht 🤔

**Comment by mike4president** [comment]
so angelegt? 

<img width="1125" alt="Bildschirmfoto 2020-06-06 um 13 14 59" src="https://user-images.githubusercontent.com/65063329/83942862-c4e00d80-a7f7-11ea-9f8c-5317c6e895d5.png">

**Comment by mike4president** [comment]
ich hab die IP Thermostate

**Comment by mike4president** [comment]
![2FCE2804-A82E-46FB-B1CD-BEA231BBFE8B](https://user-images.githubusercontent.com/65063329/83942927-4e8fdb00-a7f8-11ea-836e-d76d67fe0985.png)

**Comment by mike4president** [comment]
ich hab übrigens kanal 1 der Heizgruppe in Homekit hinterlegt... weiß nicht, ob das relevant ist

**Comment by theo-69** [comment]
hab das normale und dort keine Luftfeuchtigkeit.

**Comment by mike4president** [comment]
Hattest du die Heizgruppe oder nur das Thermostat hinterlegt? Das IP Thermostat kann die Luftfeuchtigkeit nicht messen

**Comment by theo-69** [comment]
Die Gruppe, aber der Wert kommt eigentlich vom Raumthermostat.

**Comment by theo-69** [comment]
Aber das Hauptproblem ist ja der erste Beitrag!

**Comment by thkl** [comment]
Welche Geräte sind in der Gruppe ?

**Comment by thkl** [comment]
Btw: Nicht verwirren lassen vom HeatingMode es gibt da 2 Modi:

*target (also was soll das thermostat machen) und
*current (was macht das thermostat gerade)

Diese Einstellung:

![IMG_00B1A9D4B236-1](https://user-images.githubusercontent.com/884355/83946162-4f803700-a80f-11ea-9ea1-7b535a3f267e.jpeg)

ist durchaus valide: Das Thermostat soll im AutoModus heizen (im WebUI steht es auch auf Auto) heizt aber gerade nicht weil die Aktuelle Temperatur über der Solltemperatur liegt.

**Comment by thkl** [comment]
> Ach ja zusätzlich gibt mir RedMatic die Option einen Luftfeuchtigkeitssensor anzuzeigen. Das wäre auch noch eine Option, eventuell auch Temperatur als separater Sensor.

Ähm die Gruppe hat aber keine Feuchtigkeit:

![image](https://user-images.githubusercontent.com/884355/83946285-17c5bf00-a810-11ea-972a-82c993f4b336.png)

**Comment by theo-69** [comment]
> Btw: Nicht verwirren lassen vom HeatingMode es gibt da 2 Modi:
> 
> *target (also was soll das thermostat machen) und
> *current (was macht das thermostat gerade)
> 
> Diese Einstellung:
> 
> ![IMG_00B1A9D4B236-1](https://user-images.githubusercontent.com/884355/83946162-4f803700-a80f-11ea-9ea1-7b535a3f267e.jpeg)
> 
> ist durchaus valide: Das Thermostat soll im AutoModus heizen (im WebUI steht es auch auf Auto) heizt aber gerade nicht weil die Aktuelle Temperatur über der Solltemperatur liegt.
> 
> Auch das ist valide:
> 
> ![IMG_2821A9F6579B-1](https://user-images.githubusercontent.com/884355/83946229-c0275380-a80f-11ea-99ec-0b085b838a37.jpeg)
> 
> hier sieht man was ich meine: Es soll manuell geheizt werden, aber das Soll ist unterhalb des Ist , deswegen wird gerade nicht geheizt.

Schon klar, aber er setz bei Aus auf 4,5 Grad Automatik und nicht 4,5 Grad Manuell, somit startet passend zur eingestellten Zeit das Thermostat und stellt sich trotz off auf z.B. 22 Grad Tag.

**Comment by theo-69** [comment]
> > Ach ja zusätzlich gibt mir RedMatic die Option einen Luftfeuchtigkeitssensor anzuzeigen. Das wäre auch noch eine Option, eventuell auch Temperatur als separater Sensor.
> 
> Ähm die Gruppe hat aber keine Feuchtigkeit:
> 
> ![image](https://user-images.githubusercontent.com/884355/83946285-17c5bf00-a810-11ea-972a-82c993f4b336.png)

komisch, dann holt er sich das wohl vom Raumthermostat.

<img width="447" alt="screenshot_125" src="https://user-images.githubusercontent.com/28484958/83948672-033cf300-a81f-11ea-9e61-c1fb3b5c8aae.png">

**Comment by thkl** [comment]
> Schon klar, aber er setz bei Aus auf 4,5 Grad Automatik und nicht 4,5 Grad Manuell, somit startet passend zur eingestellten Zeit das Thermostat und stellt sich trotz off auf z.B. 22 Grad Tag.

ok, muss ich mal sehen ich hab leider keine IP Thermostate. Das macht das Testen etwas schwierig.

Allerdings schalte ich das Thermostat bei Off vorher auf Manuell:

https://github.com/thkl/hap-homematic/blob/35eb9baeb5f9f083d0771450c752b3fc7d70cafa/lib/services/HomeMaticRadiatorThermostatAccessory.js#L64-L68

**Comment by thkl** [comment]
> komisch, dann holt er sich das wohl vom Raumthermostat.

Exzellente Idee

**Comment by theo-69** [comment]
meines sind auch keine IP Thermostate sondern HM-CC-RT-DN und das HM-TC-IT-WM-W-EU als Gruppe.

**Comment by thkl** [comment]
Dann sollte das mit der nächsten Version drin sein. siehe (https://github.com/thkl/hap-homematic/commit/03e71db73018f2ef082b785c44551285623765c9)

**Comment by theo-69** [comment]
> Dann sollte das mit der nächsten Version drin sein. siehe ([03e71db](https://github.com/thkl/hap-homematic/commit/03e71db73018f2ef082b785c44551285623765c9))

okay auch das Problem mit auto/manuell? Irgendwie läuft es derzeit nicht flüssig, es springt auf 10 Grad und bleibt bei Automatik wenn ich auf Heizen manuell Wechsel. und eben auf Automatik wenn ich auf aus gehe.

**Comment by theo-69** [comment]
nach Update auf 0.44 noch wildere Probleme in der Gruppe. Wenn ich auf Heizung gehe springt er zurück auf aus dann wieder Heizung und so weiter. Dann bleibt er bei aus hängen. Benehmen kenne ich so nicht, bei RedMatic klappt es sogar in Echzeit und er übernimmt wenn man auf Automatik wechselt auch die eingestellte Temperatur bei HAP nimmt er irgendeine Temperatur oft 10 Grad

**Comment by thkl** [comment]
Ok, das kann ich nachvollziehen:

Off = 4,5 Grad er merkt sich das als letzte SollTemp .. wenn man auf Heizen geht wird Manu Mode eingestellt und die letzte gemerkte SollTemp (was 4,5 Grad sind und dazu führt das er das als OFF interpretiert)

Frage: Welche Temperatur solls denn sein wenn keine gemerkte Temperatur da ist ? 20° ?

**Comment by theo-69** [comment]
Bei Automatik sollte er die Temperatur der für die Zeit voreingestellten Temperatur sein. (muss er sich vom Raumthermostat bzw. der Gruppe holen)
Bei Aus eben 4,5 Grad.
Bei Heizung 20 oder 21, vielleicht als Option bei der Erstellung eingeben? Mann könnte dann pro Raum eine andere nehmen. (Schlafzimmer 19, Wohnzimmer 21, Bad 23 oder so)

**Comment by thkl** [comment]
naja das ist nur für den Fall eines HAP Neustarts interessant. Ansonsten nehme ich die zuletzt eingestellt manuelle Temperatur ...

**Comment by theo-69** [comment]
Okay dann 20 ;-)

**Comment by thkl** [comment]
so der mode Selector springt dann auch nicht mehr hin und her ...

**Comment by theo-69** [comment]
kommt dann beim nächsten Update? Und Luftfeuchtigkeit auch? Ginge auch ein separater Temperatur Sensor?

**Comment by theo-69** [comment]
> luftfeuchtigkeit müsste jetzt schon gehen ... ich frage das Gerät ob es HUMIDITY kennt und wenn ja, wird die Luftfeuchtigeit angezeigt

Bei mir nicht :-(

<img width="1127" alt="screenshot_126" src="https://user-images.githubusercontent.com/28484958/83974020-7cede300-a8ea-11ea-8dd9-0bc82c52ef6c.png">
<img width="1123" alt="screenshot_127" src="https://user-images.githubusercontent.com/28484958/83974022-7f503d00-a8ea-11ea-9418-6a2945cddcca.png">

**Comment by thkl** [comment]
ne automatisch, da gibts keinen Schalter für ... ich frage das Gerät ob es auf Kanal 1 HUMIDITY Datenpunkt hat und dann wird die Luftfeuchte mit angezeigt

**Comment by theo-69** [comment]
Ah okay, gefunden. Ist aber leider nicht separat anzeigbar. Das geht z.B. bei RedMatic

**Comment by florianbeck** [comment]
> luftfeuchtigkeit müsste jetzt schon gehen ... ich frage das Gerät ob es HUMIDITY kennt und wenn ja, wird die Luftfeuchtigeit angezeigt

Das funktioniert soweit gut. Bei Gruppen, in denen kein Wandthermostat enthalten ist, wird bei mir aber 20% Luftfeuchtigkeit angezeigt. Der Wert ist in mehreren Gruppen (ohne WTH) gleich und ändert sich nie.

**Comment by florianbeck** [comment]
Ich habe eben noch etwas geforscht. Die 20% kommen von der Homematic selbst. Auch eine komplett leere Heizungsgruppe hat im Datapoint "ACTUAL_HUMIDITY" den Wert "20.0".

**Comment by florianbeck** [comment]
Tritt das beschriebene Verhalten (20% Luftfeuchtigkeit in Gruppen ohne Wandthermostat) so bei jemand anderem auch auf oder liegt das evtl. an meiner RaspberryMatic Installation (Firmware 3.53.30.20200919)?

**Comment by Jimlouke** [comment]
Habe vor einer Woche begonnen hap-homematic einzurichten. Firmware und Plugin sind auf dem neusten Stand. Habe allerdings ebenfalls die ganz am Anfang in diesem Issue beschriebene Problematik. Jeweils die Thermostate (ip) als eine Gruppe in Raspberry-Matic angelegt und dann als Gerät auf HAP importiert. Wenn ich nun in der Home App einen Thermostat bedienen möchte und die UI öffne, springt der aktuelle Zustand des Thermostates ständig hin und her. Von "aus" auf "automatisch" dann auf "manuell", völlig willkürlich bis er dann irgendwann bei einem Zustand stehen bleibt. Meist auf aus, aber manchmal auch auf einem der anderen. Ich habe die Displays des Raumthermostates und jenes des Heizkörperthermostates beobachtet, diese zeigen in den entsprechenden Momenten das gleiche Verhalten. Also wird synchronisiert ich weiss nur nicht wer in dem Moment die Führung hat, Homekit oder die Thermostate. Dieses Verhalten tritt allerdings nur auf wenn es eine Gruppe ist, wenn der Thermostat als einzelnes Gerät angelegt ist, funktioniert die Eingabe und die Rückmeldung des Status einwandfrei und praktisch ohne Verzögerung. Nur gibt dann der entsprechende Thermostat die Werte leider nicht an die in der Gruppe verknüpften Heizkörperthermostate weiter, daher ist die Handhabung auf diese Weise leider nicht möglich. Hat es jemand bereits hingekriegt mit den Gruppen und HAP?

**Comment by timwegenerDE** [comment]
Bei mir springt es auch hin und her. Allerdings nur in der Gruppe, in der auch ein Wand-Thermostat ist. Gruppen bestehend aus Fenstersensor + (einem) Heizungs-Thermostat gehen. Kann das jemand bestätigen, dass es am Wand-Thermostat (hier hmip-rf) liegen könnte?
![A29450AD-8FC3-4EE0-B90B-C629A5845497](https://user-images.githubusercontent.com/56134910/95672065-f3069d00-0b9d-11eb-808f-c7265ea3e4de.gif)

**Comment by thkl** [comment]
OK das ist das gleiche wie in #190 
Das Thermostat hat versucht den aktuellen Zustand für Aus/Heizen/Automatisch aus den Soll Ist Temperaturen zu ermitteln. 
Das habe ich jetzt mal geändert. Der Zustand wird jetzt aus dem Thermostat genommen. (damit sollte es nicht mehr springen)


Außerdem ist es scheinbar ein Problem wenn das Thermostat in einer Gruppe in der CCU hängt. Wird dann der Heizungsmodus (Manu/Auto) am Thermostat verstellt springt die Gruppe beim Setzen auf Manuell kurz auf 4.5 Grad SollTemp was HomeKit als Event bekommt. Und natürlich denkt oh OFF ... 
Auch das habe ich geändert.

Ich schau mir das jetzt mal ein paar Tage an, und dann schieb ich eine neue Version raus.

**Comment by devin987** [comment]
> OK das ist das gleiche wie in #190
> Das Thermostat hat versucht den aktuellen Zustand für Aus/Heizen/Automatisch aus den Soll Ist Temperaturen zu ermitteln.
> Das habe ich jetzt mal geändert. Der Zustand wird jetzt aus dem Thermostat genommen. (damit sollte es nicht mehr springen)
> 
> Außerdem ist es scheinbar ein Problem wenn das Thermostat in einer Gruppe in der CCU hängt. Wird dann der Heizungsmodus (Manu/Auto) am Thermostat verstellt springt die Gruppe beim Setzen auf Manuell kurz auf 4.5 Grad SollTemp was HomeKit als Event bekommt. Und natürlich denkt oh OFF ...
> Auch das habe ich geändert. Es werden nur noch Mode Änderungen geschickt wenn wirklich der Schalter betätigt wurde. (Bisher wurde der Mode auch noch mal gesendet wenn die Temperatur geändert wurde)
> 
> Ich schau mir das jetzt mal ein paar Tage an, und dann schieb ich eine neue Version raus.
> 
> Wer möchte das geänderte File ist hier : https://github.com/thkl/hap-homematic/blob/master/lib/services/HomeMaticThermostatAccessory.js
> 
> Es liegt auf der CCU in /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/

Wann wird den die neue Version veröffentlicht?

**Comment by blackbasket** [comment]
@theo-69 besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)

**Comment by bassmeister777** [comment]
> ![2FCE2804-A82E-46FB-B1CD-BEA231BBFE8B](https://user-images.githubusercontent.com/65063329/83942927-4e8fdb00-a7f8-11ea-836e-d76d67fe0985.png)

Vorab vielen Dank für das tolle AdOn!!!

Wir habt ihr diese Ansicht eingerichtet? Ich finde da keine Möglichkeit...

**Comment by blackbasket** [comment]
Ich vermute, dass das die EVE-App ist
