### ISSUE TITLE
EveApp Werteverlauf Wandthermostat

### ISSUE THREAD

**Issue by rost2802** [thkl/hap-homematic#108]
HmIP-WTH-2 schreibt in den Verlauf Feuchtigkeit 0%. Selten ist auch mal ein richtiger wert dabei. In der Geräteübersicht ist der aktuelle Wert aber vorhanden.

![CDD12C48-E878-4EDA-8653-80C522CBE408](https://user-images.githubusercontent.com/59236127/83942873-d9240a80-a7f7-11ea-8a29-a230918ad0ec.png)
![4B24735C-8EB9-43C1-A3A7-BAB1B7578FE3](https://user-images.githubusercontent.com/59236127/83942875-dd502800-a7f7-11ea-93ac-959a9e908f71.png)

**Comment by mike4president** [comment]
Komisch, das Problem konnte ich nicht nicht feststellen... muss sich Thomas wohl ansehen 

![89E1A4B6-63A5-4587-8C66-0BB510805B05](https://user-images.githubusercontent.com/65063329/83942954-8c8cff00-a7f8-11ea-9aa6-01b81965f233.png)
![43311100-048A-4090-A838-2E63BE8AB73B](https://user-images.githubusercontent.com/65063329/83942955-90b91c80-a7f8-11ea-95f2-275a28446621.png)

**Comment by mike4president** [comment]
Hast du es als Heizgruppe hinterlegt?

**Comment by rost2802** [comment]
Bei der Temperatur genau das selbe...

**Comment by rost2802** [comment]
> Hast du es als Heizgruppe hinterlegt?

Hab beides ausprobiert... selbes Ergebnis.

**Comment by rost2802** [comment]
Hier noch die Bilder zu der Temperatur:

![C48B7527-7955-4633-8B31-0C42AC6A9E48](https://user-images.githubusercontent.com/59236127/83943015-f3121d00-a7f8-11ea-85c1-0b28d7977579.png)
![B2634C40-88C1-425C-AD01-ED953AF1A0F2](https://user-images.githubusercontent.com/59236127/83943019-f7d6d100-a7f8-11ea-9d04-83b2691eaa85.png)

**Comment by mike4president** [comment]
Welchen Kanal der Gruppe hast du in HomeKit hinterlegt? Ich hab Kanal 1 genommen

**Comment by rost2802** [comment]
> Welchen Kanal der Gruppe hast du in HomeKit hinterlegt? Ich hab Kanal 1 genommen

Auch Kanal 1

**Comment by mike4president** [comment]
hmmmm.... dann muss Thomas ran ;-)

**Comment by thkl** [comment]
> HmIP-WTH-2 schreibt in den Verlauf Feuchtigkeit 0%. Selten ist auch mal ein richtiger wert dabei. In der Geräteübersicht ist der aktuelle Wert aber vorhanden.

Welcher Service wird da benutzt ? HomeMaticRadiatorThermostatAccessory ? Damit ich weiss wo ich suchen muss.

**Comment by rost2802** [comment]
> > HmIP-WTH-2 schreibt in den Verlauf Feuchtigkeit 0%. Selten ist auch mal ein richtiger wert dabei. In der Geräteübersicht ist der aktuelle Wert aber vorhanden.
> 
> 
> 
> Welcher Service wird da benutzt ? HomeMaticRadiatorThermostatAccessory ? Damit ich weiss wo ich suchen muss.
> 
> 
Ja genau den nutze ich

**Comment by thkl** [comment]
Was mich wundert, sind die wenigen Einträge. Ich habe pro Stunde ca 10 Einträge. Ähnlich wie im Screenshot von @mike4president  ... aber bei Dir ist zb zwischen 9 und 10 nur ein Eintrag. Das heisst das Thermostat hat nur einmal einen neuen Wert zur CCU gesendet.

**Comment by rost2802** [comment]
hmm... Hilft da irgendein Log? Servicemeldungen hab ich auch nicht wegen Funkstörungen oder so.

**Comment by rost2802** [comment]
Da ist zwischen 13 und 14 Uhr mehr passiert... nur ohne Wert 🤔

![BFFFADD3-E614-4A79-95AD-5B9FDBAF887F](https://user-images.githubusercontent.com/59236127/83947053-f1eee900-a814-11ea-8194-f4aed20ee53e.png)

**Comment by thkl** [comment]
vielleicht ma ne Stunde lang das Debug Log laufen lassen .. aber das ist dann echt viel Text ;)

**Comment by rost2802** [comment]
Na ich lass mal laufen...

**Comment by rost2802** [comment]
Temperatur kam auch einmal an um 13:17Uhr sonst wie in dem letzten Screenshot.

**Comment by thkl** [comment]
Hast Du den Boost Schalter in der Config hinzugefügt. Ich habe gerade gesehen ich füge in dem Fall ungültige Daten zur History wenn ein BOOST_MODE Event kommt.

**Comment by rost2802** [comment]
Ja Boost ist mit drin... wurde aber nur zu Testzwecken gedrückt.

**Comment by rost2802** [comment]
Hier das Log:

[hap-homematic-log-2.txt](https://github.com/thkl/hap-homematic/files/4740567/hap-homematic-log-2.txt)

**Comment by rost2802** [comment]
Die Uhrzeit 17:53 war einmal bei 68%... bin dann aus der App raus und in die Apple Home App rein, danach wieder zurück zu Eve und dann waren die 17:53 Werte wieder auf 0% 

![BBA63450-54B5-4688-A006-5047C720DC3C](https://user-images.githubusercontent.com/59236127/83948872-b22dfe80-a820-11ea-8a67-0fe1a1831ccb.png)

**Comment by thkl** [comment]
ok ich vermute mal es liegt daran das ich in die History auch  die BOOST Mode Events schreibe obwohl die nichts da zu suchen haben. Das erzeugt die Löcher mit 0% Humidity. Die Events passieren zum selben Zeitpunkt wie die Einträge in Deinem Bild.
Ich kick das mal raus.

**Comment by thkl** [comment]
Workaround : Boost Schalter einstweilen rausnehmen.

**Comment by rost2802** [comment]
> Workaround : Boost Schalter einstweilen rausnehmen.

Das Probier ich direkt mal aus... muss ich das Gerät komplett neu anlegen oder reicht bearbeiten?

**Comment by thkl** [comment]
bearbeiten reicht ...

**Comment by rost2802** [comment]
Die nullen sind jetzt weg ohne Boost 👍 aber die Werte kommen weiterhin sehr selten... erst wenn ich die Apple Home App öffne werden die Werte in Eve Verlauf erneuert.

**Comment by thkl** [comment]
Naja es gibt keinen regelmässigen pull der Werte ich nehme die Events, die die CCU schickt entgegen .. In deinem Log oben sind in einer Stunde 11 Werteänderungen eingegangen. Also so viele Eintragungen sollten auch im Graphen ungefähr sein.

**Comment by rost2802** [comment]
Heute nochmal beobachtet da es etwas kälter ist... erst wenn der Aktor von der Heizungsgruppe eingeschaltet ist kommen regelmäßig Werte. Sobald die Solltemperatur erreicht ist schaltet Aktor wieder aus und es kommen keine Werte mehr.

Auf dem Bild sieht man das ganz gut (soll ist 20grad):

![IMG_3202](https://user-images.githubusercontent.com/59236127/83978974-6906a900-a90b-11ea-825f-31b6fe70cc51.jpeg)

**Comment by thkl** [comment]
https://de.elv.com/homematic-ip-wandthermostat-hmip-wth-2-mit-luftfeuchtigkeitssensor-wth-2-fuer-smart-home-hausautomation-143159

2. FAQ  es wird nur bei einem Delta von 0.4 Grad aktualisiert ...

**Comment by rost2802** [comment]
> Was mich wundert, sind die wenigen Einträge. Ich habe pro Stunde ca 10 Einträge. Ähnlich wie im Screenshot von @mike4president ... aber bei Dir ist zb zwischen 9 und 10 nur ein Eintrag. Das heisst das Thermostat hat nur einmal einen neuen Wert zur CCU gesendet.

Deswegen dachte ich es wäre ein Fehler aber mit der Erkenntnis aus dem FAQ passt wieder alles. Dann hat sich bei @mike4president die Temp schneller verändert und deswegen auch die Feuchtigkeit. Vielen Dank für die Info dann sind hier alle Probleme beseitigt 👍
