### ISSUE TITLE
.45 Probleme bei Installation

### ISSUE THREAD

**Issue by rost2802** [thkl/hap-homematic#109]
Nach Update war die HAP-Seite nicht mehr erreichbar... nach Neustart der CCU wieder erreichbar nur waren alle Geräte gelöscht. Das Autobackup hat mich gerettet 😉 nach Einspielen lief es wieder.

**Comment by rost2802** [comment]
...leider nur für kurze Zeit. Wieder nicht erreichbar. Irgendwas stimmt nicht... sobald ich was schalte stürzt HAP ab.

**Comment by rost2802** [comment]
Scheint nur an den HmIP-BROLL zu liegen. Alles andere lässt sich Schalten.

[hap-homematic-log-9.txt](https://github.com/thkl/hap-homematic/files/4742150/hap-homematic-log-9.txt)

Mehr bekomm ich aus dem Log nicht raus.

**Comment by thkl** [comment]
Könnte ich mal die config.json und ccu.json als mail haben ?

**Comment by rost2802** [comment]
Mail ist raus

**Comment by rost2802** [comment]
Hab im HAP-Homematic Ordner noch eine Crash Datei gefunden (in TXT umbenannt):

[1591536515698.txt](https://github.com/thkl/hap-homematic/files/4742472/1591536515698.txt)

**Comment by thkl** [comment]
Ja hab den Fehler gefunden. Für die BROLL hatte ich noch keinen Test. Den konnte ich aber mit Deinen Daten bauen und dabei ist es aufgefallen.

Update kommt gleich

**Comment by thkl** [comment]
So .46 sollte das Problem lösen. Die .45 crasht erst beim Bedienen der BROLL also vorher updaten

**Comment by rost2802** [comment]
Jawoll funktioniert jetzt 👍

**Comment by thkl** [comment]
Prima
