### ISSUE TITLE
Fehlende Funktion: Der HM Jalousie Aktor HM-LC-Ja1PBU-FM wir nicht unterstüzt....

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#11]
Hallo Thomas

Wie oben beschrieben taucht der HM-LC-Ja1PBU-FM nicht in der Liste der Geräte auf.
Die Details zum Aktor findest Du in der EQ-3 Doku auf Seite 211.

lg Richard

**Comment by thkl** [comment]
Das Ding hat ja Slats ... es gibt ein eigenes HomeKit Gerät für Slats .. aber die haben wiederum keine Behanghöhe .. (hmm)

**Comment by roe1974** [comment]
mach normale blinds draus .... wie in der 219er ... das reicht :-)
hauptsache es steht "geöffnet" und nicht "öffnen" :-)
Die Slats regelt doch eh kein Mensch mit Homekit  *gggg*

**Comment by thkl** [comment]
Ah das WindowCovering hat noch horizontale Neigung zwischen -90 und 90  das könnte ich auf die 0..100 umrechnen

**Comment by roe1974** [comment]
na wen das geht ;-)

**Comment by thkl** [comment]
ok ich werfe das erst mal in die normalen Blinds und dann schauen wir mal .. 

STOP button fehlt da ja auch noch

**Comment by roe1974** [comment]
ok :-) ... STOP Button ? ... den gabs in der 219er auch nicht ... nur den regler

**Comment by roe1974** [comment]
👍

**Comment by roe1974** [comment]
Jalousie geht …. gleiches Problem wie Winmatic … steht "öffnen" statt "geöffnet" …. :(

**Comment by thkl** [comment]
Ist ein loklisierung Problem rdar://7678460 bei Apple aufgemacht ... ob der gefixt wird ... keine Ahnung
