### ISSUE TITLE
Variable Trigger lässt sich nicht updaten

### ISSUE THREAD

**Issue by franzel61** [thkl/hap-homematic#110]
Hallo,

ich habe einen Typo beim Trigger in den Variablen:
A.) Ich habe es korrigiert  "Enter" ... keine Änderung
B.) Ich habe es korrigiert  "Enter" plus Triogger aktualisieren .... keine Änderung
C.) Trigger über die Auswahl gewählt .... keine Änderung

Ich denke ich muss eine Taste klicken .... aber welche um den Update duchzuführen

Wer weiss WO???

**Comment by franzel61** [comment]
version 45 im Einsatz

**Comment by thkl** [comment]
isn bug im webui

**Comment by franzel61** [comment]
danke für die schnelle Antwort... gibst ein workaround?

**Comment by thkl** [comment]
Dieses File https://github.com/thkl/hap-homematic/blob/master/lib/configurationsrv/html/js/ui.js muss auf der CCU nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/configurationsrv/html/js kopiert werden und die dort vorhandene ui.js ersetzt werden

**Comment by franzel61** [comment]
Danke für die schnelle Hilfe ..... ein cools tool
