### ISSUE TITLE
CCU3 stürzt mit Updaterelease ab

### ISSUE THREAD

**Issue by blackbasket** [thkl/hap-homematic#111]
Meine CCU3 landet immer genau dann bei praktisch 100% DC und braucht einen Reboot, wenn das Plugin ein Update gefunden hat. Das Verhalten habe ich jetzt zum mind. 3. Mal in Folge beobachtet.

Ist zwar ein schöner Hinweis auf ein Plugin-Update, aber ;)

**Comment by thkl** [comment]
What ? Und sobald das Update eingespielt wurde, ist das Problem mit der Last weg ?

**Comment by blackbasket** [comment]
Leider nein. Ich installiere das Update, dann erreiche ich das Plugin gar nicht mehr. Danach starte ich das Plugin über CLI neu und kann es wieder erreichen. Dann wird es aber auf der CCU nicht besser (habe ich heute nochmal länger beobachtet) und ich muss die neu starten.

**Comment by thkl** [comment]
aber nach dem Neustart ist wieder alles ok, bis zum nächsten mal ein Update gefunden wurde ?

Das wundert mich arg. Die Versionsprüfung funktioniert so, das sobald ein WebBrowser angemeldet ist (WebSockets) fragt das Plugin aller 10 Minuten in der npmjs Registry die Versionsnummer der aktuellen Version ab und liefert die und auch die eigene als JSON in den Browser .. und der erkennt neue Version weil die Nummern unterschiedlich sind und zeigt den Button an.  

Das heisst: solange a) keine WebUI Config Oberfläche geöffnet ist wird keine Versionsnummerabfrage bei npmjs gemacht und b) der check läuft auch wenn es keine neue Version gibt aller 10 Minuten solange wenigstens ein WebBrowser die UI anzeigt.

sieht man mit `top` auf der console wer da amok läuft.

Ich hab das mal auf einem Testsystem (pivccu3) ausprobiert:

```
Mem: 859492K used, 88812K free, 33084K shrd, 82536K buff, 466940K cached
CPU:   0% usr   0% sys   0% nic  99% idle   0% io   0% irq   0% sirq
Load average: 0.15 0.03 0.01 2/228 21027
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
18888     1 root     S     143m  16%   0% node /usr/local/addons/hap-homematic/node_modules/hap-homematic//index.js
  453     1 root     S     248m  27%   0% java -Xmx128m -Dos.arch=arm -Dlog4j.configuration=file:///etc/config/log4j.xml -Dfile.encoding=ISO-8859-1 -Dgnu.io.rxtx.SerialPorts=/dev/mmd_hmip -jar /opt/HMServer/HMIPServer
  368   340 root     S     8016   1%   0% /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -D
18191  1004 root     S     4652   0%   0% sshd: root@pts/0
21027 18193 root     R     3244   0%   0% top
18899 18888 root     S     131m  14%   0% hap-homematic-config
  586     1 root     S    28320   3%   0% /bin/ReGaHss.community -f /etc/rega.conf -l 2
  440     1 root     S    18988   2%   0% /bin/rfd -f /etc/config/rfd.conf -l 5
  413     1 root     S<   11972   1%   0% /bin/multimacd -f /etc/multimacd.conf -l 5
  369   340 root     S     8136   1%   0% /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -D
  367   340 root     S     7836   1%   0% /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -D
  365   340 root     S     7800   1%   0% /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -D
  308     1 root     S     7192   1%   0% /usr/sbin/ntpd -g 0.de.pool.ntp.org 1.de.pool.ntp.org 2.de.pool.ntp.org 3.de.pool.ntp.org
  340   339 root     S     6584   1%   0% /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -D
 1004     1 root     S     4652   0%   0% /usr/sbin/sshd
  119     1 root     S     4392   0%   0% /bin/hss_led -l 6
  331     1 root     S     4088   0%   0% /bin/eq3configd
  580     1 root     S     4068   0%   0% /bin/eq3-uds-services
  345     1 root     S     3908   0%   0% /bin/ssdpd
  838     1 root     S     3244   0%   0% /usr/sbin/crond -f -l 9
18193 18191 root     S     3244   0%   0% -sh
    1     0 root     S     3116   0%   0% init
  183     1 root     S     3116   0%   0% /sbin/syslogd -n -m 0
  185     1 root     S     3116   0%   0% /sbin/klogd -n
  205     1 root     S     3116   0%   0% /sbin/udhcpc -b -t 100 -T 3 -S -x hostname:ccu3-webui -i eth0 -F ccu3-webui -V eQ3-CCU3 -s /bin/dhcp.script -p /var/run/udhcpc_eth0.pid
  151     1 dbus     S     2892   0%   0% dbus-daemon --system
  293     1 root     S     1824   0%   0% /usr/sbin/ifplugd -i eth0 -fI -u0 -d10
  339     1 root     S     1580   0%   0% /usr/sbin/lighttpd-angel -f /etc/lighttpd/lighttpd.conf -D
```

Da langweilt sich alles ....

**Comment by thkl** [comment]
ich habe 0.0.47 gepusht .. schauen wir mal ;)

**Comment by blackbasket** [comment]
Bisher ist noch alles gut :) Ich melde mich gerade aber auch ganz bewusst nicht an der WebUI an, da ich bei den Problemen immer einen doppelten Versionssprung (0.42 -> 0.44; 0.44 -> 0.46) hatte. Ich warte einfach mal ein paar Tage und gucke, was passiert ;)

**Comment by thkl** [comment]
das mit den Versionen lag daran, das ich immer kurz nach dem Release irgendeinen kritischen Bug beseitigt hatte ;)

**Comment by blackbasket** [comment]
ja, sowas dachte ich mir bereits ;) aber es klingt für mich nicht so, dass du in Betracht ziehst, dass mein Problem davon kam... daher einfach mal warten... ich glaube zwar nicht an Zufälle, aber es mag ja trotzdem so sein ;)

**Comment by thkl** [comment]
Ich habe mit der letzten Version in 2 verschiedenen virtuellen CCUs das mit dem Update mal simuliert und konnte das bisher nicht nachstellen. Daher bin ich etwas ratlos, wo das Problem liegen könnte.

**Comment by blackbasket** [comment]
Ich halte es ja eig selbst für Schwachsinn, aber nur so war es bisher reproduzierbar :/ hast du 0.0.48 schon gepusht? -> #114 

Es fängt nämlich langsam an, wenn auch noch human und ohne Auswirkungen...

![880551D0-F144-4D1F-9815-6AF9996B8C0D](https://user-images.githubusercontent.com/64146687/84566895-20b91200-ad75-11ea-8689-a6b795422cc2.jpeg)

**Comment by thkl** [comment]
nein .47 ist aktuell

**Comment by blackbasket** [comment]
Ok... CPU langweilt sich auch noch...

**Comment by thkl** [comment]
Ich habe in Verbindung mit dem DC Service auch mehrfach das HAP Produktivsystem neu gestartet aber der DC der CCU ist nie über 7% gestiegen ...  trotzdem werde ich da mal weiter ein Auge drauf werfen.

**Comment by blackbasket** [comment]
Der DC ist aktuell von 54 auf 33 gefallen... top ist auch nicht besonders auffällig... hab es mal ein bisschen mitgeloggt...

[putty.log](https://github.com/thkl/hap-homematic/files/4774518/putty.log)

**Comment by thkl** [comment]
schaut "normal" aus. Natürlich bin ich, neben dem HMIPServer, sehr Speicherlastig. Aber so ist das nun mal bei Systemen mit Runtime ...

**Comment by blackbasket** [comment]
Guten Morgen :)

Da haben wir den Schuldigen... Leider habe ich nur noch keine Ahnung, warum und was genau es für ein Prozess ist...

`Mem: 615116K used, 379016K free, 3336K shrd, 9856K buff, 230716K cached
CPU:  25% usr   0% sys   0% nic  74% idle   0% io   0% irq   0% sirq
Load average: 1.00 1.00 1.00 2/215 30761
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
  719     1 root     S     255m  26%  25% java -Xmx128m -Dos.arch=arm -Dlog4j.co
  922     1 root     S     171m  18%   0% node /usr/local/addons/hap-homematic/n
  667     1 root     S     7480   1%   0% /usr/sbin/snmpd -Lsd -Lf /dev/null -c
  216     1 root     S     4024   0%   0% /sbin/udevd -d
  322     1 root     S     1720   0%   0% /usr/sbin/rngd
28879     2 root     IW       0   0%   0% [kworker/2:2]
30606     2 root     IW       0   0%   0% [kworker/0:2]
30551     2 root     IW       0   0%   0% [kworker/0:0]
  962   922 root     S    87024   9%   0% hap-homematic-config
  846     1 root     S    39788   4%   0% /bin/ReGaHss.community -f /etc/rega.co
  704     1 root     S    24204   2%   0% /bin/rfd -f /etc/config/rfd.conf -l 5
  678     1 root     S<   11972   1%   0% /bin/multimacd -f /etc/multimacd.conf
  616   591 root     S     8008   1%   0% /usr/sbin/lighttpd -f /etc/lighttpd/li
  617   591 root     S     7968   1%   0% /usr/sbin/lighttpd -f /etc/lighttpd/li
  615   591 root     S     7824   1%   0% /usr/sbin/lighttpd -f /etc/lighttpd/li
  614   591 root     S     7756   1%   0% /usr/sbin/lighttpd -f /etc/lighttpd/li
  559     1 root     S     7192   1%   0% /usr/sbin/ntpd -g fs01.blaesing.local
  591   589 root     S     6588   1%   0% /usr/sbin/lighttpd -f /etc/lighttpd/li
  315     1 root     S     5652   1%   0% /usr/sbin/irqbalance
  898     1 root     S     5572   1%   0% /opt/mh/openvpn --daemon --config /usr`

**Comment by thkl** [comment]
Das Java Ding ? Das ist doch der HmIp / Virtual Groups Server

**Comment by blackbasket** [comment]
Ok, danke :)

also, folgendes sehe ich... CPU load ist seit 08:18 gestiegen (vgl. PRTG)...
![cpu](https://user-images.githubusercontent.com/64146687/84587444-b14c2c80-ae1f-11ea-943e-19209189821f.png)

und das im hmserver.log...
`Jun 14 08:08:51 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-3] SYSTEM: Eventlistener Handler utilization: 0/50 used 
Jun 14 08:13:52 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-3] SYSTEM: 0 Accesspoints in Queue 
Jun 14 08:13:52 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-3] SYSTEM: Permanent-/Burstlistener Handler utilization: 0/50 used 
Jun 14 08:13:52 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-3] SYSTEM: Eventlistener Handler utilization: 0/50 used 
Jun 14 08:13:53 de.eq3.cbcs.lib.remotecommadapter.device.service.AccessPointWatchdog INFO  [vert.x-eventloop-thread-0] SYSTEM: Access Point Watchdog running periodic connection check... 
Jun 14 08:14:00 org.apache.http.impl.client.DefaultHttpClient INFO  [HmIP-RF_java_WorkerPool-0] I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:39292: Connection reset 
Jun 14 08:14:01 org.apache.http.impl.client.DefaultHttpClient INFO  [HmIP-RF_java_WorkerPool-0] Retrying request to {}->http://127.0.0.1:39292 
Jun 14 08:14:59 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] (un)registerCallback on VirtualDeviceHandlerRega called from url: http://192.168.179.24:9875 
Jun 14 08:14:59 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] Removed InterfaceId: null 
Jun 14 08:14:59 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] (un)registerCallback on VirtualDeviceHandlerRega called from url: http://192.168.179.24:9875 
Jun 14 08:14:59 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] Added InterfaceId: HAP_VirtualDevices. 
Jun 14 08:14:59 de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker INFO  [vert.x-worker-thread-11] Execute BackendCommand: de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand 
Jun 14 08:15:01 de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand INFO  [vert.x-worker-thread-11] updateDevicesForClient -> 7 device addresses will be added 
Jun 14 08:15:02 de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand INFO  [vert.x-worker-thread-11] set ready config of INT0000001 
Jun 14 08:15:10 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] (un)registerCallback on VirtualDeviceHandlerRega called from url: http://192.168.179.24:9875 
Jun 14 08:15:10 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] Removed InterfaceId: null 
Jun 14 08:15:10 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] (un)registerCallback on VirtualDeviceHandlerRega called from url: http://192.168.179.24:9875 
Jun 14 08:15:10 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] Added InterfaceId: HAP_VirtualDevices. 
Jun 14 08:15:10 de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker INFO  [vert.x-worker-thread-12] Execute BackendCommand: de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand 
Jun 14 08:15:13 de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand INFO  [vert.x-worker-thread-12] updateDevicesForClient -> 7 device addresses will be added 
Jun 14 08:15:19 de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand INFO  [vert.x-worker-thread-12] set ready config of INT0000001 
Jun 14 08:18:52 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-3] SYSTEM: 0 Accesspoints in Queue 
Jun 14 08:18:52 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-3] SYSTEM: Permanent-/Burstlistener Handler utilization: 0/50 used 
Jun 14 08:18:52 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-3] SYSTEM: Eventlistener Handler utilization: 0/50 used 
Jun 14 08:20:00 org.apache.http.impl.client.DefaultHttpClient INFO  [HmIP-RF_java_WorkerPool-1] I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:39292: Broken pipe (Write failed) 
Jun 14 08:20:00 org.apache.http.impl.client.DefaultHttpClient INFO  [HmIP-RF_java_WorkerPool-1] Retrying request to {}->http://127.0.0.1:39292 
Jun 14 08:20:30 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] (un)registerCallback on VirtualDeviceHandlerRega called from url: http://192.168.179.24:9875 
Jun 14 08:20:31 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] Removed InterfaceId: null 
Jun 14 08:20:32 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] (un)registerCallback on VirtualDeviceHandlerRega called from url: http://192.168.179.24:9875 
Jun 14 08:20:32 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] Added InterfaceId: HAP_VirtualDevices. 
Jun 14 08:20:32 de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker INFO  [vert.x-worker-thread-13] Execute BackendCommand: de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand 
Jun 14 08:20:47 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] (un)registerCallback on VirtualDeviceHandlerRega called from url: http://192.168.179.24:9875 
Jun 14 08:20:47 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] Removed InterfaceId: null 
Jun 14 08:20:47 org.apache.http.impl.client.DefaultHttpClient INFO  [HAP_HmIP-RF._WorkerPool-0] I/O exception (java.net.SocketException) caught when processing request to {}->http://192.168.179.24:9875: Broken pipe (Write failed) 
Jun 14 08:20:47 org.apache.http.impl.client.DefaultHttpClient INFO  [HAP_HmIP-RF._WorkerPool-0] Retrying request to {}->http://192.168.179.24:9875 
Jun 14 08:20:48 de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand INFO  [vert.x-worker-thread-13] updateDevicesForClient -> 7 device addresses will be added 
Jun 14 08:20:48 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] (un)registerCallback on VirtualDeviceHandlerRega called from url: http://192.168.179.24:9875 
Jun 14 08:20:48 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] Added InterfaceId: HAP_VirtualDevices. 
Jun 14 08:20:58 de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand INFO  [vert.x-worker-thread-13] set ready config of INT0000001 
Jun 14 08:21:02 de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker INFO  [vert.x-worker-thread-13] Execute BackendCommand: de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand 
Jun 14 08:21:21 org.apache.http.impl.client.DefaultHttpClient INFO  [HAP_HmIP-RF._WorkerPool-0] I/O exception (java.net.SocketException) caught when processing request to {}->http://192.168.179.24:9875: Broken pipe (Write failed) 
Jun 14 08:21:23 org.apache.http.impl.client.DefaultHttpClient INFO  [HAP_HmIP-RF._WorkerPool-0] Retrying request to {}->http://192.168.179.24:9875 
Jun 14 08:21:25 org.apache.http.impl.client.DefaultHttpClient INFO  [HmIP-RF_java_WorkerPool-1] I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:39292: Broken pipe (Write failed) 
Jun 14 08:21:25 org.apache.http.impl.client.DefaultHttpClient INFO  [HmIP-RF_java_WorkerPool-1] Retrying request to {}->http://127.0.0.1:39292 
Jun 14 08:23:55 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-3] SYSTEM: 0 Accesspoints in Queue 
Jun 14 08:23:58 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-3] SYSTEM: Permanent-/Burstlistener Handler utilization: 0/50 used 
Jun 14 08:23:59 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-3] SYSTEM: Eventlistener Handler utilization: 0/50 used 
Jun 14 08:24:08 de.eq3.cbcs.lib.remotecommadapter.device.service.AccessPointWatchdog INFO  [vert.x-eventloop-thread-0] SYSTEM: Access Point Watchdog running periodic connection check... 
Jun 14 08:25:05 de.eq3.cbcs.lib.nrjavaserialdevice.internal.SerialFrameDecoder ERROR [Thread-6] Last frame was not complete. Aborting decoding of that frame. 
Jun 14 08:29:13 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-3] SYSTEM: 0 Accesspoints in Queue 
Jun 14 08:29:55 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-3] SYSTEM: Permanent-/Burstlistener Handler utilization: 0/50 used 
Jun 14 08:29:16 de.eq3.cbcs.lib.nrjavaserialdevice.internal.SerialFrameDecoder ERROR [Thread-6] Last frame was not complete. Aborting decoding of that frame. 
Jun 14 08:31:54 de.eq3.cbcs.lib.nrjavaserialdevice.internal.SerialFrameDecoder ERROR [Thread-6] Last frame was not complete. Aborting decoding of that frame. 
Jun 14 08:34:05 de.eq3.cbcs.lib.remotecommadapter.device.service.AccessPointWatchdog INFO  [vert.x-eventloop-thread-0] SYSTEM: Access Point Watchdog running periodic connection check... 
Jun 14 08:41:03 de.eq3.cbcs.lib.nrjavaserialdevice.internal.SerialFrameDecoder ERROR [Thread-6] Last frame was not complete. Aborting decoding of that frame. 
Jun 14 08:42:23 de.eq3.cbcs.lib.nrjavaserialdevice.internal.SerialFrameDecoder ERROR [Thread-6] Last frame was not complete. Aborting decoding of that frame. `

**Comment by thkl** [comment]
Laut log weint der IP Server das er keine Verbindung mehr zu HAP aufbauen kann wenn er einen Event abliefern möchte. Aber auch sein eigener Rega Server scheint nicht mehr erreichbar ... 

Ich habe gesehen, ich melde die Schnittstelle allerdings nicht ab, bevor ich das Update mache. Was sein kann, das während des Updates der IP Server seine Nachrichten nicht los wird.  Ich werde da mal was ändern, das vor dem Update die Schnittstellen beendet werden. Hinterher wird der hap Prozess eh neu gestartet. 

Allerdings passiert das alles erst beim Klick auf Updaten. 

Und es ist kein Grund warum der IP Server so zickt.  Wenn RFD (der HM Schnittstellenprozess) seinen Kram nicht los wird hört er nach 10 Versuchen auf damit.

**Comment by blackbasket** [comment]
hmm, ok... also, das Update habe ich jetzt auch bewusst noch nicht gemacht... ich habe gerade den hmserver neu gestartet... jetzt sieht alles wieder gut aus...

**Comment by blackbasket** [comment]
aber so traue ich mich ja gar nicht in Urlaub zu fahren ;)

**Comment by thkl** [comment]
ach ? der load ging so hoch ohne Update .. na dann bin ich ja gänzlich unschuldig ... 
Selbst wenn der Event Empfänger auf der anderen Seite nicht mehr reagiert dann sollte der Schnittstellenprozess nicht alles lahm legen. Kann ja sein, das zb Rega oder in dem Falle HAP einfach crasht.

**Comment by blackbasket** [comment]
Ja, war ja immer so... siehe oben... ich habe jetzt gerade das Update gemacht, nachdem ich dem HMserver neu gestartet habe... jetzt ist das Update das erste Mal problemlos durchgelaufen ;)

**Comment by thkl** [comment]
Hmm alles wild ;) ... ich implementiere das mit dem Abmelden mal bevor ich update ... dann läuft der HMIP nicht ins Leere und weint das log voll.

**Comment by blackbasket** [comment]
Thx :) ich halt wirklich alles strange... aber die DC Probleme habe ich „leider“ erst, seitdem ich das Plugin verwende... sonst muss ich das Plugin mal testweise ein paar Wochen runterwerfen und auf Siri verzichten... ich nutze das Plugin lediglich zur internen Sprachsteuerung...

**Comment by thkl** [comment]
ich versuche schon nett zur CCU zu sein und frage alle Daten von Rega ab und nicht direkt von der Schnittstelle um keinen unnützen Funkverkehr zu generieren.

**Comment by blackbasket** [comment]
Glaub ich dir :)

**Comment by ChrWi** [comment]
ich hatte beim Update auf die .47 das Problem, dass das UI nicht mehr zurückkam. Hab mir kurzerhand damit beholfen, dass ich das Addon deinstalliert und reinstalliert habe - anschließend Datensicherung zurückgespielt.

**Comment by blackbasket** [comment]
Das hatte ich heute mal nicht...

normal reicht dann aber: /etc/config/rc.d/hap-homematic restart

Wenn ich das unterwegs gerade richtig im Kopf habe ;)

**Comment by thkl** [comment]
richtig

**Comment by blackbasket** [comment]
Hallo Thomas,

ich habe das Plug-in letzte Woche Dienstag entfernt und seitdem keinerlei Probleme mehr. Nun habe ich meine Backups der letzten Monate mal etwas genauer analysiert, da diese mit der Installation des Plug-ins deutlich größer geworden sind (nicht verwunderlich), aber nach der Deinstallation nicht mehr auf die alte Größe zurück gegangen sind.

Ich habe in usr_local.tar.gz ->  /usr/local/etc/config/addons nach der Deinstallation weiterhin einen Ordner hap-homekit und unter /usr/local/addons einen Ordner npm.

Vielleicht kam mein Problem ja von einem der Updates, die nicht sauber funktioniert haben. Kann ich diese Ordner bedenkenlos von der CCU löschen? Oder erwarten mich dann Probleme?

Unter Zusatzsoftware taucht das Plug-in nicht mehr auf.

LG,
Marcel

**Comment by thkl** [comment]
Die Ordner können weg. 
Eine neue Version des Updaters legt das npm Verzeichnis ins /temp das heißt beim nächsten reboot ist das wieder weg. 

Leider kann die CCu3 nicht wie die RM Ordner vom Backup ausschließen.  Sonst würden die Programmfiles für hap nicht im Backup landen. 
Aber ich bin auf den Ordner addons angewiesen. Da dort die Zusatzsw. rein gehört.

**Comment by blackbasket** [comment]
So, die CCU ist seit der Deinstallation stabil durchgelaufen... ich installiere jetzt einmal das Plug-in neu ;)

**Comment by blackbasket** [comment]
sieht bisher eher mies aus :( habe alles neu konfiguriert und nur die relevanten Geräte für Siri-Steuerung hinzugefügt...

![image](https://user-images.githubusercontent.com/64146687/87510440-e395b780-c673-11ea-8ca8-0c15df4c8d48.png)

**Comment by thkl** [comment]
Kann ich mal das Config Verzeichnis als Archiv haben ?

**Comment by blackbasket** [comment]
/usr/local/etc/config/hap-homematic ist leer, /usr/local/etc/config/addons/hap-homematic kann ich dir gerne als Mail zusenden...

**Comment by thkl** [comment]
Jo letzteres config/addons/hap-homematic

**Comment by thkl** [comment]
also ich kann erst ma nichts ungewöhnliches finden

**Comment by blackbasket** [comment]
Ich denke, ich habe den "Fehler" gefunden :) Da ich das Plugin nur zur inhouse-Siri-Steuerung verwende, hatte ich keine Steuerzentrale definiert... Seitdem das AppleTV als Steuerzentrale aktiviert ist, sieht es deutlich besser aus... Den Zusammenhang hatte ich nicht erwartet -.-

![image](https://user-images.githubusercontent.com/64146687/87787788-81d47980-c83c-11ea-891e-d02b3516f474.png)

**Comment by thkl** [comment]
Oh ok. Ich frage explizit die Werte von Geräten bei Rega ab wenn ich von HomeKit ein get für die jeweilige Characteristic bekomme. Das passiert wenn man zb in der HomeApp einen Pull2Refresh macht. Ansonsten liefere ich die Werte an HomeKit welche ich von den jeweiligen Schnittstellen per Event bekomme. 

Es könnte jetzt also sein, das irgend ein HomeKit Controller bei Dir also permanent nachgefragt hat was dann den hohen DC erzeugt.

**Comment by blackbasket** [comment]
Ich werde es nochmal 2 Wochen beobachten und dann berichten... aber jetzt bin ich guter Dinge ;)

**Comment by blackbasket** [comment]
sieht weiterhin alles gut aus, daher mache ich hier jetzt mal einen Deckel drauf :)
