### ISSUE TITLE
Fenster: 50% bei gekippt

### ISSUE THREAD

**Issue by dkrizic** [thkl/hap-homematic#112]
Könntest Du das wieder so implementieren, dass bei einem gekippten Fenster 50% angezeigt wird statt "Offen". Das ist sehr hilfreich.

**Comment by theo-69** [comment]
Siehe https://github.com/thkl/hap-homematic/issues/102

**Comment by thkl** [comment]
Ich schau mal ob ich das Fenster ReadOnly bauen kann.

**Comment by thkl** [comment]
![IMG_3700](https://user-images.githubusercontent.com/884355/84043136-38c01880-a9a6-11ea-9836-11944e08de3d.PNG)
![IMG_DCE9307E4C41-1](https://user-images.githubusercontent.com/884355/84043162-3cec3600-a9a6-11ea-80e9-293140c30d60.jpeg)

**Comment by theo-69** [comment]
👍

**Comment by thkl** [comment]
so 25% bei gekippt. Ich musste allerdings TargetPosition wieder auf beschreibbar stellen. Apples Home App fällt sonst in ein "No Response" wenn man das Icon antippt. Das ist bissel blöd. Eve hat richtigerweise das Bediencontrol ausgeblendet. Naja ...

**Comment by roe1974** [comment]
Bitte im Standard bleiben :-P :-P :-P

**Comment by theo-69** [comment]
> so 25% bei gekippt. Ich musste allerdings TargetPosition wieder auf beschreibbar stellen. Apples Home App fällt sonst in ein "No Response" wenn man das Icon antippt. Das ist bissel blöd. Eve hat richtigerweise das Bediencontrol ausgeblendet. Naja ...

böser Apfel, böser

**Comment by thkl** [comment]
> Bitte im Standard bleiben :-P :-P :-P

![image](https://user-images.githubusercontent.com/884355/84049956-5f358200-a9ad-11ea-8c4e-fa92731bf833.png)

**Comment by thkl** [comment]
kann das hier weg ?

**Comment by dkrizic** [comment]
ja
