### ISSUE TITLE
Manuelles Backup und Autobackup bei HAP Update teilweise nicht möglich

### ISSUE THREAD

**Issue by comtel2000** [thkl/hap-homematic#113]
Das manuelle Backup aus HAP mit SID auth. schlägt teilweise fehl (Kein File Download) und nach timeout ist HAP wieder bedienbar. Ich habe CCU Authentication testweise deaktiviert und nach HAP Neustart ging das Backup 1-2 mal, danach das gleiche Problem. Danach geht das Backup erst wieder nach HAP Neustart.
Aufgefallen ist mir das erst, weil das HAP Update jetzt anscheinend ein Autobackup macht und entsprechend auch nicht mehr funktioniert mit (SID auth.). Vor 0.0.44 hatte ich das Problem nicht, aber auch nie ein HAP Backup gestartet.
Ich würde evtl. Autobackup auch als Optionsfeld mit in den Update Dialog nehmen.
Wie kann ich auf SSH (Raspimatic) loggen, was beim Backup fehl schlägt?

**Comment by thkl** [comment]
Moin,

Schau mal ob im Config Verzeichnis .crash Dateien liegen.  Die werden angelegt wenn der Prozess auf eine Fehler läuft.

**Comment by comtel2000** [comment]
leider keine .crash files da
Ohne "CCU Authentication" habe ich keine Probleme. Erst wenn ich "CCU Authentication" aktiviere, schlägt das Backup fehl.

**Comment by thkl** [comment]
Hmm ich hab das mal ausprobiert. Bei mir klappt das.
Du kannst mal folgendes tun wenn motiviert ;) 
* ```ssh auf die ccu``` 
* service beenden ```/etc/config/rc.d/hap-homematic stop```
* debug starten ```node /usr/local/addons/hap-homematic/node_modules/hap-homematic/index.js -D```

und wenn das Ganze gestartet ist über das WebUI ein Backup erzeugen und schauen ob in der Console irgend ein Error geworfen wird ...

Ein ReStart über das WebUI startet den Service wieder (oder ```/etc/config/rc.d/hap-homematic start```)

**Comment by comtel2000** [comment]
ok, das Backup funktioniert immer, wenn hap-homematic via CLI `node /usr/local/addons/hap-homematic/node_modules/hap-homematic/index.js -D` gestartet wird.
Wenn ich dann aber via WebUI ein HAP Restart auslöse, geht das Backup danach nicht mehr.
"CCU Authentication" ist doch nicht relevant, macht also keinen Unterschied.

Hier die Log für `/etc/config/rc.d/hap-homematic`
```
root@homematic-charly:~# /etc/config/rc.d/hap-homematic stop
root@homematic-charly:~# /etc/config/rc.d/hap-homematic
root@homematic-charly:~# [Mon Jun 08 2020 21:33:14 GMT+0200 (CEST)] [HAP Server] [CCU] no channel found for 2e60d92c-79d3-4fb1-be24-e9c0b2XXXXcc:0
[Mon Jun 08 2020 21:33:17 GMT+0200 (CEST)] [HAP Server] [Generic] no key voltage found in undefined
[Mon Jun 08 2020 21:33:17 GMT+0200 (CEST)] [HAP Server] [Generic] no key roChannel found in undefined
[Mon Jun 08 2020 21:33:17 GMT+0200 (CEST)] [HAP Server] [Generic] no key roChannel found in undefined
[Mon Jun 08 2020 21:33:27 GMT+0200 (CEST)] [HAP ConfigServer] File not found /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/configurationsrv/html/assets/en.json
```

Wenn ich mit DEBUG via WebUI starte ist das idR. der letzte Eintrag:
```
[Mon Jun 08 2020 20:49:59 GMT+0200 (CEST)] debug - [HAP Server] ** Fakegato-storage write FS file: /usr/local/etc/config/addons/hap-homematic/homematic-charly_DitecSteuerungTemp_0_persist.json "firstEntry":1378,"lastEntry":5410,"usedMemory":4032,"refTime":610143384,"initia
```
"DitecSteuerungTemp" ist eine SystemVariable. Gibt es da bei Fakegato ein Problem?
Aber warum geht's, wenn via SSH direkt von 'root' gestartet wird.. Bin raus :(

**Comment by thkl** [comment]
gibts evtl in ```/var/log/messages``` irgendwas auffälliges ? 

Die Fakegato-storage Meldungen sind ok da wird nur geloggt das ein Update in das jeweilige History File geschrieben wird.

File Not Found en.json ist auch ok, weil alle Meldungen in englisch im Code stehen und nur optional nach Deutsch übersetzt werden. 

Und die Warnings wegen den fehlenden Channels kann man auch irgnorieren ...

**Comment by roe1974** [comment]
hab ich dir auch schon geschrieben dass backup nicht mehr funktioniert .... ist seit .44 so

**Comment by comtel2000** [comment]
in messages ist auch nix:

```
Jun  8 20:59:08 homematic-charly user.info homematic: stopped hap-homematic
Jun  8 20:59:18 homematic-charly user.info homematic: started (restart) hap-homematic
Jun  8 21:01:55 homematic-charly user.info homematic: stopped hap-homematic
Jun  8 21:14:48 homematic-charly user.info homematic: stopped hap-homematic
Jun  8 21:14:58 homematic-charly user.info homematic: started (restart) hap-homematic
Jun  8 21:19:51 homematic-charly user.info homematic: stopped hap-homematic
Jun  8 21:20:01 homematic-charly user.info homematic: started (restart) hap-homematic
Jun  8 21:33:03 homematic-charly user.info homematic: stopped hap-homematic
```
Ich hatte auch mal die serial als Identifier in Fakegato im Verdacht. Die virtuellen HVL Geräte haben da ja idR. keine eindeutigen Namen. Aber warum geht's via SSH node ..

**Comment by thkl** [comment]
also bei mir geht das auch via service .. 
Das Backup wird durch einen Call ```http://ccu:9874/api/?method=backup&sid=....``` erzeugt.
Wobei sid die Session ID ist wenn CCU Authentication verwendet wird.

Geht da das Backup ? Dann wüsste ich schon mal in welche Richtung ich suchen muss.

**Comment by roe1974** [comment]
ich habe ccu auth deaktiviert, https aktiviert ...

**Comment by comtel2000** [comment]
als service gestartet habe ich alles ohne Erfolg probiert:
```
http://ccu:9874/api/?method=backup
http://ccu:9874/api/?method=backup&sid=null
http://ccu:9874/api/?method=backup&sid=[aktuell_gültige_sid]
```

Ich schalte jetzt mal Fakegato aus. CCU Auth ist schon länger aus und spielt denke ich keine Rolle

**Comment by comtel2000** [comment]
@roe1974 ist bei dir HVL installiert?

**Comment by roe1974** [comment]
@comtel2000 ....   nein

**Comment by thkl** [comment]
Also alle Calls liefern kein Backup ? ... Ok dann liegt es auf der Serverseite nicht auf Seiten des Clients ...  

Das Backup macht nichts anderes als 

1. nachschauen ob ein altes Backup in /tmp/hap_homematic_backup.tar.gz liegt
2. wenn ja das löschen
3. ein tar -C /etc/config/addons/hap-homematic/ -czvf  /tmp/hap_homematic_backup.tar.gz --exclude="hap-autobackup_*.*"

4. das  /tmp/hap_homematic_backup.tar.gz zurückliefern.


@comtel2000 was du mal testen könntest:  /tmp/hap_homematic_backup.tar.gz löschen backup auslösen und schaun ob  /tmp/hap_homematic_backup.tar.gz wieder da ist

**Comment by comtel2000** [comment]
ja,  /tmp/hap_homematic_backup.tar.gz wird wieder neu erstellt. Der Client bekommt aber keine Rückmeldung

**Comment by thkl** [comment]
Ok, dann weiss ich in welche Richtung ich suchen muss ...  ich rufe zwar den tar Befehl mit execsync auf, aber ich habe das Gefühl, das das Backup file (noch) nicht da ist / oder nicht lesbar ist , wenn der Befehl fertig ist und der Server das File versenden möchte.

**Comment by roe1974** [comment]
> ja,  /tmp/hap_homematic_backup.tar.gz wird wieder neu erstellt. Der Client bekommt aber keine Rückmeldung

selbe verhalten hier ....

**Comment by comtel2000** [comment]
Hatte gerade einen CCU Neustart gemacht. (mit System Setting: Nur Eve History Disabled = ON) Danach geht das Backup. Auch nach Restart HAP service via WebUI -> Backup funktioniert. Danach habe ich Eve History Disabled = OFF gesetzt. Automatischer HAP Restart -> Backup geht nicht mehr.
Egal wie oft ich dann das Backup auslöse. Da geht nichts mehr bis evtl. ein HAP restart hilft

**Comment by thkl** [comment]
ich könnte mal die eve history files aus dem Backup ausschließen.

**Comment by roe1974** [comment]
ah... die eve history wollt ich eh noch disabeln .... muss ich danach ccu rebooten oder reicht hap ? ... welche files muss ich löschen damit die history weg ist ?

**Comment by thkl** [comment]
hap rebooten reicht lsöchen *.persist.json in /etc/config/addons/hap-homematic/

**Comment by thkl** [comment]
es liegt nicht an Eve; ich habe aber gerade das gleiche Verhalten .. ich schau mir das morgen weiter an ...

**Comment by comtel2000** [comment]
Probiere ich aus.
Mit `node /usr/local/addons/hap-homematic/node_modules/hap-homematic/index.js -D` aus der Console läuft das Backup bei mir komischer weise immer, egal ob mit CCU Auth. Eve history, etc.

Aber der Auto Restart nach Änderung einer System Einstellung löst fast immer das Backup Problem bei mir aus

**Comment by comtel2000** [comment]
ohne *.persist.json ist das /tmp/hap_homematic_backup.tar.gz nur noch 19kb, bringt aber leider keinen Unterschied

**Comment by thkl** [comment]
schaut so aus als ob execsync das problem ist .. ich hab das jetzt mal auf asyncron und promises umgebaut .. siehe commit hier oben .. @comtel2000 das könntest du mal testen. Denn bis eben ging das Backup bei mir auch nicht mehr; jetzt schon

**Comment by comtel2000** [comment]
👍 bei mir bisher keine Probleme mehr

**Comment by thkl** [comment]
Nice !

**Comment by comtel2000** [comment]
Das Auto-Backup vor dem HAP Update konnte ich noch nicht testen.
Mal sehen wie viele auch das Problem beim Update auf .47 bekommen ;)

**Comment by comtel2000** [comment]
fixed 🙏
