### ISSUE TITLE
HM-Sen-DB-PCB (KEY) -> Motion Detektor

### ISSUE THREAD

**Issue by dkrizic** [thkl/hap-homematic#115]
Ich habe hier einen HM-Sen-DB-PCB (Türklingelsensor). Den kann ich aktuell als DoorBell anlegen, aber wie wir wissen funktioniert das so nicht. Kannst Du mal hinzufügen, dass er als Motion Sensor dargestellt wird?

**Comment by theo-69** [comment]
Könntest du über CuxD selber machen. Virtuellen Bewegungsmelder anlegen und verknüpfen, zur not via Script.

**Comment by thkl** [comment]
Ähm bei mir geht der DoorBell Sensor.  Ich hab diesen Klingelsensor auch und immer wenn jemand klingelt schickt mir HomeKit einen Push das die Bell rankt 😂

**Comment by thkl** [comment]
Ach, das Ding wird in Eve nicht angezeigt. Es ist nur unter Devices selber zu finden. Und Home behauptet es wird nicht unterstützt. Trotzdem sendet Home mit Pushes.

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/84037997-a0269a00-a99f-11ea-9acb-3a720719bea7.jpeg)

**Comment by dkrizic** [comment]
Ok, auf die Idee das zu testen kam ich nicht.... Ich habe es jetzt getestet und gemerkt, dass das Gerät wohl tot ist, ich muss mal die Batterien tauschen. Aber wenn diese Push-Notification kommt, dann bin ich glücklich.
