### ISSUE TITLE
Variablen mit mehr Services

### ISSUE THREAD

**Issue by theo-69** [thkl/hap-homematic#116]
Ist es Möglich im Bereich Variablen mehr Services unter zubringen. z.B. Luftfeuchtigkeit, Bewegungsmelder, Belegtmelder, Feuchtigkeitssensor etc.

**Comment by thkl** [comment]
Also quasi das eine Numerische Variable nicht nur ein Dimmer sein kann sondern auch ein Feuchtigkeitssensor oder eine Boolesche Variable auch ein Motion Detector ?

**Comment by theo-69** [comment]
Genau oder auch ein Belegt Sensor (OccupiedSensor) Und zurück zum Duty Cycle geht das auch bei der CCU3?

**Comment by thkl** [comment]
ok, keine so dumme Idee 👍

**Comment by mike4president** [comment]
> Genau oder auch ein Belegt Sensor (OccupiedSensor) Und zurück zum Duty Cycle geht das auch bei der CCU3?

https://github.com/thkl/hap-homematic/issues/114#issuecomment-640607824

**Comment by mike4president** [comment]
Also ich hab auch eine CCU3, hab den Raspberry Pi rausgeschmissen und durch ein Tinkerboard S ersetzt. Außerdem habe ich gleich Raspberrymatic draufgespielt und da geht es...

**Comment by mike4president** [comment]
> ok, keine so dumme Idee 👍

Thomas, Frage off topic: wie viele Sensoren sind eigentlich in einem HomeKit Gerät möglich? Ich frage nur, weil z.B. beim Hue Bewegungssensor 3 Sensoren in einer Kachel abgebildet werden, die man auch einzeln darstellen kann. Ich glaube ich habe sogar schon vier gesehen. Was geben die Homekit Spezifikationen da her? Ich hätte manchmal gerne mehr Sensoren  verschiedener Geräte zugunsten der Übersichtlichkeit in einer Kachel... Sprich Wassersensor, Bewegung, Luftfeuchtigkeit und Temperatur... oder meinetwegen auch nur Gefahrenmelder wie Bewegung Feuer und Wasser... Mich interessiert das nur grundsätzlich... Wir sprachen ja bereits darüber, wie die Umsetzung in HAP erfolgt.

**Comment by thkl** [comment]
Ich hatte nach 22 Stück keine Lust mehr noch welche dazuzufügen. 


![image](https://user-images.githubusercontent.com/884355/84051702-ce13da80-a9af-11ea-95bc-62ba3b68eddf.png)

**Comment by mike4president** [comment]
ich meinte eigentlich das hier... 

<img width="284" alt="Bildschirmfoto 2020-06-08 um 19 03 28" src="https://user-images.githubusercontent.com/65063329/84059614-33b99400-a9bb-11ea-83b1-fa0fc79e261c.png">

**Comment by mike4president** [comment]
wie viele Sensoren sind da pro Gerät eigentlich möglich... ? ist nur interessehalber...

**Comment by thkl** [comment]
jaja ich auch ... wie gesagt bei 22 hab ich aufgehört welche hinzuzufügen

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/84062154-48982680-a9bf-11ea-804a-b4734de2a624.png)

![IMG_3704](https://user-images.githubusercontent.com/884355/84064563-1a1c4a80-a9c3-11ea-976c-2686524ee447.jpg)
![IMG_3705](https://user-images.githubusercontent.com/884355/84064567-1c7ea480-a9c3-11ea-829d-d05ea6c24db9.jpg)
![IMG_3706](https://user-images.githubusercontent.com/884355/84064568-1d173b00-a9c3-11ea-8fbf-ffcea1ac3977.jpg)

**Comment by thkl** [comment]
![IMG_4C495C677CDA-1](https://user-images.githubusercontent.com/884355/84066606-77fe6180-a9c6-11ea-9ee4-0756f7673760.jpeg)



Wichtig für die Nutzung: Eve merkt sich über einen längeren Zeitraum die Art der History für ein Objekt. Das heisst, wenn die Variable mit dem Namen Test-A erst für einen Motion Sensor benutzt, dann gelöscht und auf einen Contact Sensor umgebaut wurde, kann es sein, das die History nicht richtig funktioniert, weil Eve immer noch alte History Daten gespeichert hat.

Das passiert aber nur beim Wechsel des Loggin Types; in dem Falle nur beim Wechseln von Contact auf etwas anderes und zurück. Motion/Occupancy/Leak gehen untereinander.
