### ISSUE TITLE
Variablen mit Geräte verbinden

### ISSUE THREAD

**Issue by rost2802** [thkl/hap-homematic#118]
Hallo, wäre eine optionale Verbindung von Variablen mit Geräten eine Idee? Also das man beim erstellen eine Variable (z.B. Batterie Level) auswählen kann zu welchem Gerät das gehört. So könnte man auch die Co2 Sensoren zuordnen und das erstellen neuer Geräte wird nicht zu überladen.

**Comment by thkl** [comment]
Das wird nicht ganz so funktionieren. 

Aktuell basiert die Struktur des ganzen System auf Accessories, welche eine spezielle Funktion haben.(Tür/Fenster/Kontakt/Thermometer etc). Jedem Accessory ist ein HomeMatik Gerät zugeordnet. Wenn auf den überwachten Schnittstellen jetzt ein Event zur Änderung eines Datenpunktes ausgelöst wird, weiß der Server genau welches Accessory das betrifft und wie die Datenpunktänderung nach HomeKit übersetzt werden muss.

Ich könnte zwar optional Variablen zu Accessories hinzufügen, müsste aber bei der Programmierung schon wissen, was diese für einen HomeKit Aktor/Sensor darstellen sollen.

Also ja im gewissen Rahmen (wie auch mit dem CO2 Sensor am Thermometer) kann ich das schon machen, aber einen so ultraflexiblen Baukasten wird es nicht geben. 

Das würde auch irgendwie die Idee des Projektes, eine einfache möglichst konfigurationsarme Bereitstellung von HomeKit für die CCU, sprengen.

**Comment by rost2802** [comment]
> 
> Edit: Evtl kommst Du ja mit #116 schon weiter.

Genau das hat mich auf die Idee Gebracht... das Ziel war ja die Vereinfachung weil man dann das Co2 zB wieder raus nehmen könnte aus der Geräteerstellung und erst wenn man es wünscht/braucht in die Variablen geht und es denn da hinzufügt.

**Comment by thkl** [comment]
Naja, evtl. könnte ich das so lösen, das ich nur diese Option anbiete, wenn zb einem Kanal des Gerätes, welches ausgewählt wurde, die Variable in der CCU hinzugefügt wurde. Das verlagert diese Konfiguration dann in die CCU ... 

Aber wenn ich es in den Variablen hinzufüge wird ein neues HomeKit Gerät auf Basis dieser Variable angelegt. Ich könnte zwar jetzt eine Option dort einbauen, wo drin steht "Kein eigenes Gerät sondern als CO2 Sensor ins Thermometer" aber dann habe ich die Einstellungen nur vom Thermometer in die Variablen verlegt.

**Comment by rost2802** [comment]
> Naja, evtl. könnte ich das so lösen, das ich nur diese Option anbiete, wenn zb einem Kanal des Gerätes, welches ausgewählt wurde, die Variable in der CCU hinzugefügt wurde. Das verlagert diese Konfiguration dann in die CCU ...

Klingt auch nicht schlecht... was wäre denn einfacher/sauberer/besser zu Programmieren?

> Aber wenn ich es in den Variablen hinzufüge wird ein neues HomeKit Gerät auf Basis dieser Variable angelegt. Ich könnte zwar jetzt eine Option dort einbauen, wo drin steht "Kein eigenes Gerät sondern als CO2 Sensor ins Thermometer" aber dann habe ich die Einstellungen nur vom Thermometer in die Variablen verlegt.

Bei einer Option ist das noch simpel aber wenn dann mehr (wünsche ;-) dabei kommen ist das in den Variablen evtl. übersichtlicher. Da existiert ja schon ein HomematicBatVariableAccessory zB.

**Comment by thkl** [comment]
> Klingt auch nicht schlecht... was wäre denn einfacher/sauberer/besser zu Programmieren?

ist viel Aufwändiger ;)

**Comment by thkl** [comment]
So, die Variablenfelder bekommen optionale Select Helper:

![Bildschirmfoto 2020-06-09 um 22 01 48](https://user-images.githubusercontent.com/884355/84194320-24127c00-aa9d-11ea-929d-7c7fea5974f1.png)


![Bildschirmfoto 2020-06-09 um 22 01 57](https://user-images.githubusercontent.com/884355/84194341-2a085d00-aa9d-11ea-8e84-64d458e685d9.png)
