### ISSUE TITLE
HomeKit Dimmer not working

### ISSUE THREAD

**Issue by aschuster-muc** [thkl/hap-homematic#119]
CCU3 (RasperryMatic + hap 0.0.11)

I have set up a HomeMaticDimmerAccessory (HmIP-BDT  Dimmaktor). I can successfully switch the light on and off in Homekit but it does not accept a dimm value. When for example set to 50% or any other value it does not change the light intensity but always goes back to 100%.

**Comment by thkl** [comment]
The idea is to save the current level at events from LEVEL and only publish it to HomeKit when WORKING is false.  I will try this soon as get the ip dimmer

**Comment by roe1974** [comment]
same behavior here with HM Dimmer (HM-LC-Dim1TPBU-FM and HM-LC-Dim1T-FM) ....

**Comment by comtel2000** [comment]
just checked if one of these CCU settings „ Eventverzögerung, Zufallsanteil“ make a difference...
but doesn't looks like

**Comment by thkl** [comment]
> same behavior here with HM Dimmer (HM-LC-Dim1TPBU-FM and HM-LC-Dim1T-FM) ....

For me it works well on a HM-LC-Dim1PWM-CV and also with HVL devices which are mapped to HUE bulbs.

**Comment by roe1974** [comment]
it works in eve but not in apple home .... but i am not using eve :-/ :-P

**Comment by thkl** [comment]
So the Problem is not hap. So I can went to bed 🛌 again 😂

**Comment by comtel2000** [comment]
Events for set Dimmer Level from 0 to 52% by Home App (HmIP-BDT) and Ramp time 500

Log from debugging version:
https://github.com/comtel2000/hap-homematic/blob/comtel2000-dimmer-patch/lib/services/HomeMaticDimmerAccessory.js


```
..
[Thu Jun 11 2020 14:00:07 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP get LVL 0.000000
[Thu Jun 11 2020 14:00:07 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] CCU event 0
[Thu Jun 11 2020 14:00:07 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] CCU set ON false
[Thu Jun 11 2020 14:00:07 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] CCU set LVL 0
[Thu Jun 11 2020 14:00:07 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP get LVL 0.000000
[Thu Jun 11 2020 14:00:11 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP try set LVL 0.16
[Thu Jun 11 2020 14:00:11 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP try set ON true
[Thu Jun 11 2020 14:00:11 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP try set LVL 0.32
[Thu Jun 11 2020 14:00:11 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP try set ON true
[Thu Jun 11 2020 14:00:12 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP try set LVL 0.43
[Thu Jun 11 2020 14:00:12 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP try set ON true
[Thu Jun 11 2020 14:00:12 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP try set LVL 0.48
[Thu Jun 11 2020 14:00:12 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP try set ON true
[Thu Jun 11 2020 14:00:12 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP try set LVL 0.51
[Thu Jun 11 2020 14:00:12 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP try set ON true
[Thu Jun 11 2020 14:00:13 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP try set LVL 0.52
[Thu Jun 11 2020 14:00:13 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP try set ON true
[Thu Jun 11 2020 14:00:13 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] HAP set LVL 1
[Thu Jun 11 2020 14:00:13 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] CCU event 0.1
[Thu Jun 11 2020 14:00:13 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] CCU event skipped
[Thu Jun 11 2020 14:00:13 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] CCU set working true
[Thu Jun 11 2020 14:00:15 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] CCU event 1
[Thu Jun 11 2020 14:00:15 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] CCU event skipped
[Thu Jun 11 2020 14:00:15 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] CCU set working false
[Thu Jun 11 2020 14:00:15 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] CCU finally get LVL
[Thu Jun 11 2020 14:00:15 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] CCU event 1
[Thu Jun 11 2020 14:00:15 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] CCU set ON true
[Thu Jun 11 2020 14:00:15 GMT+0200 (CEST)] info - [HAP Server] [Dimmer] CCU set LVL 100
```

**Comment by comtel2000** [comment]
btw. how can I add a device name or id to the log entry? I uses multiple dimmers..

**Comment by thkl** [comment]
Add a %s in text and  this._serial to your log arguments. I‘ve done this already in Thermostat cause i‘v ran into the same problem while debugging.

**Comment by comtel2000** [comment]
Home App is call a "switch ON" after each LVL update? self.oldLevel should be updated outside of the timeout call

**Comment by comtel2000** [comment]
With this patch the slider of the Home App sometimes still jumps, but the final result of the dimmer level is ok. 
..tested with AppleTV latest version and a iOS 13.5 + iOS 12.4 device

**Comment by roe1974** [comment]
with .47 dimmer works perfect 👍

**Comment by thkl** [comment]
@aschuster-muc :

How is this working for your HmIP dimming devices ?
