### ISSUE TITLE
Fehler: "HomeMaticSwitchAccessory" Subtyp Outlet/Switch vertauscht

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#12]
Hallo Thomas

Beim "HomeMaticSwitchAccessory" ist der Subtyp vertauscht.
Bei "Outlet" bekommt man einen switch in HK
Bei "Switch" bekommt man ein outlet in HK

Und könnte man noch den Typ "Fan" hinzufügen ?

lg Richard

**Comment by thkl** [comment]
Tatsache :o)

![image](https://user-images.githubusercontent.com/884355/80386130-3d71b700-88a7-11ea-98aa-78a4228fac17.png)

**Comment by roe1974** [comment]
hihi :-)

**Comment by thkl** [comment]
sollte auch in .28 drin sein

**Comment by roe1974** [comment]
passt jetzt 👍
