### ISSUE TITLE
Homematic HM-ES-PMSw1-Pl-DN-R1

### ISSUE THREAD

**Issue by Donni1966** [thkl/hap-homematic#120]
[HM-ES-PMSw1-Pl-DN-R1.txt](https://github.com/thkl/hap-homematic/files/4761197/HM-ES-PMSw1-Pl-DN-R1.txt)
Hi, hab zwei der Schalter und die geht - funktionell jedenfalls, nur entsteht immer noch ein zweites Gerät nach der Aktivierung

Siehe Bild. 
![Screenshot 2020-06-10 22 55 32](https://user-images.githubusercontent.com/61660957/84317706-8cc92980-ab6d-11ea-8d22-75ca8a3d4854.png)

Mach ich was falsch? 
Ich kann auch den Verbrauch nicht finden oder sehen - in EVE

Off topic: Das hier ist ein großartiges Projekt und ich bin so froh, dass die HK Anbindung nun in der Rasipatic ist. Ich hab dir heute spontan mal was "gesponsert" auf Paypal.

**Comment by thkl** [comment]
Jap dann sollte es gehen.

**Comment by Donni1966** [comment]
So weit so gut . Ich habe nur einen Schalter und eine Steckdose in meinem Homekit.  Bei Eve werden nun Messwerte angezeigt. Allerdings bleibt eine Grafik leer - die von Strom. 

Ich frag mal ganz unverblümt - warum müssen das zwei Geräte sein? Ich kann die auch nicht gruppieren und bei beiden auch "schlafen" als ein und aus ... 

Mir würde im Homekit ein Schalter( Steckdose) reichen, wenn man da eh keine Messwerte sehen kann. 

Ist das eine Sache vom Homekit? Muss das so sein? 
![IMG_3842](https://user-images.githubusercontent.com/61660957/84380788-41079600-abe8-11ea-8b3c-efbdc01e482e.png)
![IMG_3841](https://user-images.githubusercontent.com/61660957/84380790-4238c300-abe8-11ea-8a05-111718db1112.png)
![IMG_3840](https://user-images.githubusercontent.com/61660957/84380793-4369f000-abe8-11ea-8dec-257187637fe5.png)

**Comment by thkl** [comment]
Man kann immer nur eine Historyfunktionn für ein Gerät nutzen. Das ist in dem Falle die Eve Power Funktion.  Leider macht die App sobald eine History verfügbar ist überall Diagramme hin. 


2 Geräte weil sonst Apple Home das Gerät dar nicht erkennt.

**Comment by Donni1966** [comment]
> 2 Geräte weil sonst Apple Home das Gerät dar nicht erkennt.
Verstehe ... danke für die Antwort. Die kannst du aber nicht zusammen in ein Device packen?

**Comment by thkl** [comment]
Sie sind in einem Accessory. Aber halt der Powermanagement Service und der Switch. 

Wenn dich die ganzen Messwerte nicht interessieren kannst du auch nur den Schaltkanal als Switch konfigurieren.

**Comment by Donni1966** [comment]
"Sie sind in einem ACC?" Also ich habe zwei Objekte in Eve und Homekit. Wenn ich den Plug steuere geht auch der Schlater, aber nicht umgekehrt und wenn ich lokal steuere (knöpf drück) dann geht der Schlater aus, aber der PLUG nicht. irgendwie seltsam. 

Aber gut ... Frage ist beantwortet
