### ISSUE TITLE
HmIP-BWTH: Leere Batterie (0%) - haben aber keine

### ISSUE THREAD

**Issue by dkrizic** [thkl/hap-homematic#122]
Bei meinen HmIP-BWTH wird eine Leere Batterie angezeigt, obwohl sie keine haben. Der Rest funktioniert ganz normal:

![image](https://user-images.githubusercontent.com/1181349/84389855-fa6d6800-abf6-11ea-8b6c-879015633425.png)

**Comment by thkl** [comment]
Ok ich schaue ob ich OPERATING_VOLTAGE als Datenpunkt finde und mache daran das Vorhandensein von Batterien fest ... ne blöde Idee wie sich rausstellt 🤦🏻‍♀️

**Comment by theo-69** [comment]
Auch ne Frage zur Batterie Anzeige. Habe z.B. einen virtuellen Bewegungsmelder (also natürlich ohne Batterie :-)) trotzdem wird dort immer Batterie angezeigt zwar 100% aber EVE hat mir schon mal LOW Batterie angezeigt.

**Comment by theo-69** [comment]
Und mir ist noch aufgefallen das bei den Fensterkontakten keine Batterie angezeigt wird 🤔

**Comment by mike4president** [comment]
> Und mir ist noch aufgefallen das bei den Fensterkontakten keine Batterie angezeigt wird 🤔

Welche Fenstersensoren hast du denn? Bei den optischen IP Dingern wird der Batteriestatus angezeigt

**Comment by theo-69** [comment]
> > Und mir ist noch aufgefallen das bei den Fensterkontakten keine Batterie angezeigt wird 🤔
> 
> Welche Fenstersensoren hast du denn? Bei den optischen IP Dingern wird der Batteriestatus angezeigt

Die optischen aber ohne IP HM-Sec-Sco

**Comment by dkrizic** [comment]
Bei den folgenden Geräten wäre eine Batterieanzeige sinnvoll:

HM-Sec-Key-S (KeyMatic)

```
<device name="Diele Türschloss" ise_id="8616" unreach="false" sticky_unreach="false" config_pending="false">
<channel name="Diele Türschloss:0" ise_id="8617" index="0" visible="" operate="">
<datapoint name="BidCos-RF.NEQ0683203:0.UNREACH" type="UNREACH" ise_id="8637" value="false" valuetype="2" valueunit="" timestamp="1591874487" operations="5"/>
<datapoint name="BidCos-RF.NEQ0683203:0.STICKY_UNREACH" type="STICKY_UNREACH" ise_id="8633" value="false" valuetype="2" valueunit="" timestamp="1591874487" operations="7"/>
<datapoint name="BidCos-RF.NEQ0683203:0.CONFIG_PENDING" type="CONFIG_PENDING" ise_id="8619" value="false" valuetype="2" valueunit="" timestamp="1591874487" operations="5"/>
<datapoint name="BidCos-RF.NEQ0683203:0.LOWBAT" type="LOWBAT" ise_id="8627" value="false" valuetype="2" valueunit="" timestamp="1591874487" operations="5"/>
<datapoint name="BidCos-RF.NEQ0683203:0.DUTYCYCLE" type="DUTYCYCLE" ise_id="8623" value="false" valuetype="2" valueunit="" timestamp="1591874487" operations="5"/>
<datapoint name="BidCos-RF.NEQ0683203:0.RSSI_DEVICE" type="RSSI_DEVICE" ise_id="8631" value="1" valuetype="8" valueunit="" timestamp="1591874487" operations="5"/>
<datapoint name="BidCos-RF.NEQ0683203:0.RSSI_PEER" type="RSSI_PEER" ise_id="8632" value="57" valuetype="8" valueunit="" timestamp="1591874487" operations="5"/>
</channel>
<channel name="Diele Türschloss" ise_id="8641" index="1" visible="true" operate="true">
<datapoint name="BidCos-RF.NEQ0683203:1.STATE" type="STATE" ise_id="8654" value="true" valuetype="2" valueunit="" timestamp="1591946799" operations="7"/>
<datapoint name="BidCos-RF.NEQ0683203:1.OPEN" type="OPEN" ise_id="8652" value="" valuetype="2" valueunit="" timestamp="0" operations="2"/>
<datapoint name="BidCos-RF.NEQ0683203:1.RELOCK_DELAY" type="RELOCK_DELAY" ise_id="8653" value="" valuetype="4" valueunit="s" timestamp="0" operations="2"/>
```
<datapoint name="BidCos-RF.NEQ0683203:1.STATE_UNCERTAIN" type="STATE_UNCERTAIN" ise_id="8655" value="false" valuetype="2" valueunit="" timestamp="1591946799" operations="5"/>
<datapoint name="BidCos-RF.NEQ0683203:1.ERROR" type="ERROR" ise_id="8643" value="0" valuetype="16" valueunit="" timestamp="1591946799" operations="5"/>
</channel>
</device>
```

HM-Sec-SC (HomeMatic Magnetkontakt)

```
<device name="Diele Haustür" ise_id="2371" unreach="false" sticky_unreach="false" config_pending="false">
<channel name="Diele Haustür:0" ise_id="2372" index="0" visible="" operate="">
<datapoint name="BidCos-RF.LEQ0034888:0.UNREACH" type="UNREACH" ise_id="2388" value="false" valuetype="2" valueunit="" timestamp="1591874487" operations="5"/>
<datapoint name="BidCos-RF.LEQ0034888:0.STICKY_UNREACH" type="STICKY_UNREACH" ise_id="2384" value="false" valuetype="2" valueunit="" timestamp="1591874487" operations="7"/>
<datapoint name="BidCos-RF.LEQ0034888:0.CONFIG_PENDING" type="CONFIG_PENDING" ise_id="2374" value="false" valuetype="2" valueunit="" timestamp="1591874487" operations="5"/>
<datapoint name="BidCos-RF.LEQ0034888:0.LOWBAT" type="LOWBAT" ise_id="2378" value="false" valuetype="2" valueunit="" timestamp="1591874487" operations="5"/>
<datapoint name="BidCos-RF.LEQ0034888:0.RSSI_DEVICE" type="RSSI_DEVICE" ise_id="2382" value="1" valuetype="8" valueunit="" timestamp="1591874487" operations="5"/>
<datapoint name="BidCos-RF.LEQ0034888:0.RSSI_PEER" type="RSSI_PEER" ise_id="2383" value="1" valuetype="8" valueunit="" timestamp="1591874487" operations="5"/>
</channel>
<channel name="Diele Haustür" ise_id="2392" index="1" visible="true" operate="true">
<datapoint name="BidCos-RF.LEQ0034888:1.STATE" type="STATE" ise_id="2417" value="false" valuetype="2" valueunit="" timestamp="1591947483" operations="5"/>
<datapoint name="BidCos-RF.LEQ0034888:1.ERROR" type="ERROR" ise_id="2393" value="0" valuetype="16" valueunit="" timestamp="1591874207" operations="5"/>
<datapoint name="BidCos-RF.LEQ0034888:1.LOWBAT" type="LOWBAT" ise_id="2416" value="false" valuetype="2" valueunit="" timestamp="1591947482" operations="5"/>
</channel>
</device>
```

**Comment by mike4president** [comment]
https://www.eq-3.de/downloads/download/broschueren/homematic_ip/94470_HmIP_Produktkatalog_Januar_2019.pdf

**Comment by mike4president** [comment]
Da sind alle IP Geräte Batterie drinnen

**Comment by thkl** [comment]
das sollte in Zukunft nicht mehr so sein. Ich prüfe jetzt, ob das Gerät einen LOWBAT (HM) oder LOW_BAT (HmIP) auf Channel 0 hat. Wenn ja dann hat es auch eine Batterie.

**Comment by theo-69** [comment]
Die optischen Fensterkontakte HM-Sec-Sco und auch die Rauchmelder zeigen keine Batterie an.

**Comment by thkl** [comment]
Die Kontakte (wenn sie als Door oder Window) benutzt werden bekommen im nächsten Release eine Batterie ( siehe https://github.com/thkl/hap-homematic/commit/4a1e202a721687f7745ad49d476f37a052b9e8d1 )

Für die Rauchmelder füge ich sie auch noch hinzu.
