### ISSUE TITLE
Nach Hinzufügen neuer Geräte werden diese nicht "Grün" in der Instanzenübersicht

### ISSUE THREAD

**Issue by Buildex1101** [thkl/hap-homematic#124]
Installation und erste Einrichtung von hap-homematic auf dem RaspberryMatic haben gut funktioniert. Räume angelegt und Geräte hinzugefügt - alles soweit ok. Leider wurden bei der ersten Einrichtung nicht alle Geräte gefunden/angelegt. Also habe ich diese in der Web-Oberfläche über den Punkt "Geräte -> Neu". Diese werden mir nun auch angezeigt, allerdings sind diese Instanzen nicht "Grün" hinterlegt und werden im HomeKit auch nicht angezeigt. Die Konfiguration der Geräte ist analog zu bestehenden Geräte, die in der Ersteinrichtung gefunden und eingerichtet wurden und alle "Grün" sind und dementsprechend auch im HomeKit angezeigt werden. Gerätetyp: HM-Sec-SCo (Tür/Fensterkontakt). Restart der HAP-Instanz und des RaspberryMatic hat nicht geholfen. Was nun?

**Comment by JensBonse** [comment]
Schau mal in HomeMatic, ob die Ports für die HAP Instanzen offen sind.

**Comment by Buildex1101** [comment]
Vielen Dank für den Hinweis. Allerdings lag es nicht an den Ports - die waren offen. Aber beim Überprüfen der HAP-Instanzen auf die Ports ist mir aufgefallen, dass man unter "HomeKit-Instanzen" -> "Einstellungen" die "Veröffentlichungseinstellungen" für die Räume, die bislang ohne Geräte waren, noch anwählen muss. Jetzt funktioniert es, wie es soll :-)

**Comment by thkl** [comment]
Links Menü Instanzen und dort in den Veröffentlichungseinstellungen die Häkchen setzten dann bekommen die Instanzen die Geräte verpasst und die landen dann in HomeKit.
