### ISSUE TITLE
Jalousie HM bei .47 ... status bei schließen

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#125]
Hi Thomas

Mit .47 habe ich jetzt mit dem HM Jalousie Aktor
ein „kleines“ anzeigen Problem ....
Wenn die Jalousie offen ist und ich schließe sie springt die Anzeige auf „schließen“ dann aber gleich auf „öffnen=geöffnet“ ... wenn sie dann zu ist springt die Anzeige auf „geschlossen“
Umgekehrt funktioniert alles normal ... also beim öffnen steht solange „wird geöffnet“ bis sie offen ist ...
lg Richard

**Comment by thkl** [comment]
Hallo Richard, 
könntest Du bitte mal das DebugLog einschalten, die Jalousie schließend und anschließend nach Events BidCos-RF.Serial:1.DIRECTION Ausschau halten. Diese werden von der CCU erzeugt und geben an, in welche Richtung die Jalousie läuft. Das sende ich als PositionState zu HomeKit.

**Comment by roe1974** [comment]
Habe dir das log per Mail geschickt .... der Fehler passiert aber wie soeben festgestellt nicht jedesmal :-/

**Comment by thkl** [comment]
ich konnte das bei meiner Tradfri Version der Blinds nachvollziehen .. mit obiger Änderung funktioniert das dann

**Comment by roe1974** [comment]
sieht gut aus !! :-) 👍
