### ISSUE TITLE
Geräte werden nicht erkannt - HmIP-BROLL

### ISSUE THREAD

**Issue by MINIdodo89** [thkl/hap-homematic#126]
Hallo,

leider muss ich vorweg gestehen, dass ich noch recht neu im Umfeld Homematic und HAP-Homematic bin. Daher hoffe ich, mein Problem ist kein totaler Anfängerfehler. 
Ich habe meine HmIP-Broll Aktoren aber in einer RaspberryMatic übertragen können und diese auch dem Wohnzimmer zuweisen können. 
Leider werden die Kanäle aber nicht in der HAP-HomeMatic zur Verfügung gestellt. Hier sind alle Räume mit einer (0) versehen. Ich habe schon einen Neustart beider Systeme vorgenommen, aber leider keinen Erfolg gehabt. Ich habe hier den Raum aber übertragen können und es wurde mir auch eine Bridge eröffnet, aber es stehen keine Geräte zur Zuweisung zur Verfügung. 
Ports sind entsprechend auch freigegeben.
Über eine Hilfe würde ich mich sehr freuen.

**Comment by thkl** [comment]
Das klingt wie der Wizzard. Bitte einmal versuchen den Wizzard abzubrechen, im WebUI unter Internes die Funktion CCU Cache aktualisieren, und dann in der Geräteliste über die Funktion "Neu" den Broll suchen. Dort müsste er zu finden sein und sich einrichten lassen.

BTW: Der Wizzard kommt solange von alleine bis mindestens ein Gerät eingerichtet wurde.

**Comment by MINIdodo89** [comment]
Danke für deine schnelle Hilfe. Hat bei mir funktioniert und die Rolladen lassen sich wie gewünscht per Homekit steuern.

**Comment by thkl** [comment]
Perfekt 😎

**Comment by Salamovka** [comment]
Hallo,
ich bin neu hier und bin noch relativ unbeholfen mit dem Umgang mit HAP-Homematic, ich hoffe Sie sehen mir die folgende Frage nach...
Ich habe nach dem Anlernen eines HMIP-Broll ein ähnliches Phänomen beobachtet, das Gerät war einfach nicht im WebUI von HAP-Homematic auffindbar. Nachdem ich diese issue im Netz gefunden habe, wollte ich ebenfalls den CCU Cache aktualiseren, aber einen Button dafür konnte ich in der WebUI unter Internes leider nicht finden...
