### ISSUE TITLE
Nachkommastellen bzw. richtige Einheit bei der Anzeige des Energieverbrauchs

### ISSUE THREAD

**Issue by ChrWi** [thkl/hap-homematic#127]
0.0.47 ermöglich die Anzeige eines Energieverbrauchs basierend auf einer HM Variablen.

Eve rechnet in kWh - zeigt in der History auch Wh an. Hier kommt es bei mir zur Abweichung:

Bei 153Wh sollte der aktuelle Wert doch 0,15kWh haben und nicht 0,00kWh?

![IMG_1133](https://user-images.githubusercontent.com/52505025/84598955-c1d7c380-ae6e-11ea-9569-dfbca026a64e.png)
![IMG_1134](https://user-images.githubusercontent.com/52505025/84598963-cdc38580-ae6e-11ea-9ac4-4a84562287a6.png)

**Comment by thkl** [comment]
Welcher Wert steht in der Variable und welche Einheit hat dieser ?

**Comment by ChrWi** [comment]
(momentaner) Solarertrag und Stromverbrauch wird in Watt aus dem Datenlogger geliefert (siehe auch [diese Liste](https://github.com/thkl/homebridge-homematic/files/4272166/daten.pdf) und  in der CCU Variable so verarbeitet. 
<img width="629" alt="Bildschirmfoto 2020-06-14 um 19 57 27" src="https://user-images.githubusercontent.com/52505025/84600408-48919e00-ae79-11ea-8ad5-ce0e264b4278.png">

**Comment by thkl** [comment]
ok dann muss in den Geräteeinstellungen im WebUI der Faktor auf 1000 gestellt werden.
Denn Eve erwartet kWH für die Consumtion Characteristic. Die Diagramme rechnen selber in Eve ...

Aber wenn das W sind ist es ja eine Momentanleistung. Da fehlt ja die Zeitkomponente. Also müsste der Service dann noch zusätzlich Power statt Consumption anbieten.

**Comment by ChrWi** [comment]
Es sollte doch Faktor 1/1000 sein, oder? Habe mir den Tagesertrag als Variable konfiguriert. 21,102kWh = 21102Wh. Mit Faktor 1000 liefert mir Eve traumhafte 21.102.000,00kWh.

Du hast absolut recht - für Momentanleistungen benötigt der Service Power, nicht Consumption.

**Comment by thkl** [comment]
ähm ja ;) 0.0001 aber ich mache ein parseInt damit geht das kaputt .. ich korrigiere das mal

**Comment by ChrWi** [comment]
Hallo Thomas, in der 0.0.48 ist der Fix des Faktors noch nicht enthalten? Oder muss ich ggf. die Konfiguration anpassen?

**Comment by thkl** [comment]
alles was bis gestern hier in der codebase war ist eingeflossen. In Deinem Fall müsste der Faktor 0.001 sein oder ?

**Comment by ChrWi** [comment]
Ich stelle gerade fest, dass Config-Änderungen in meinen Variablen nicht gespeichert werden. Beim Versuch, die Variablen neu anzulegen, bekomme ich diese in der Auswahlliste nicht angezeigt?
Wenn ich das config.json manuell auf 0.001 setze, werden die Variablen korrekt gesetzt (wobei der Subtype hier noch fehlt).
Muss mal schauen, warum die UI Konfiguration nicht funktioniert.

**Comment by ChrWi** [comment]
Hallo Thomas,
ich habe gerade die .49 installiert. 
Den Subtype kann ich nun einstellen. Ansonsten fallen zwei Sachen auf:
- der Faktor wird nach Konfiguration im WebUI immer auf 1 "aufgerundet", obwohl im config.json 0.001 steht.
- in der Eve App steht die Momentanleistung unter der Variable in Watt - bei konfiguriertem 0.001 als Faktor steht dann nun allerdings 1W anstelle 1385W bzw. 1,385kW. Auf der rechten Seiten und auf der Landingpage steht "0.00kWh".
![IMG_1436](https://user-images.githubusercontent.com/52505025/89735477-0c3a8280-da63-11ea-969e-e0152c06ed2c.jpeg)
