### ISSUE TITLE
Neues Gerät: HmIP-FALMOT-C12 (Fußboden-Heizungssteuerung)

### ISSUE THREAD

**Issue by joehun** [thkl/hap-homematic#128]
Hallo,
anbei die Daten zur Integration der Heizungssteuerung "HmIP-FALMOT-C12". Hierbei interessieren mich insbesondere die Öffnungsstatus der Ventile (in Prozent?).

[HmIP-FALMOT-C12 (1).json.txt](https://github.com/thkl/hap-homematic/files/4778407/HmIP-FALMOT-C12.1.json.txt)

Mit freundlichen Grüßen,
Jörg Hundgeburth
P.S.: Beste Software für die CCU3!

**Comment by thkl** [comment]
Ich schau mir das Gerät mal an. Aber es gibt aktuell keine offizielle Characteristic für die Ventilposition. Ich kann die selber erzeugen, aber Apples Home App wird die nicht anzeigen. Mit Elgatos Eve sollte es aber funktionieren.

**Comment by thkl** [comment]
Nachtrag: Ich habe mir mal die Doku zu dem Aktor angeschaut. Der hat 12 Kanäle und dort sind die einzig interessanten Parameter das Valve Level ?. Habe ich da was übersehen ?

**Comment by joehun** [comment]
Ich denke, dass ist richtig. Die beschreiben, wie weit das Ventil geöffnet ist.

**Comment by thkl** [comment]
Ok, hier müsste ich eine neues Gerät für HomeKit anlegen. Da die Apple Home App weder eine Characteristic für Ventilöffnung noch einen entsprechenden Service dafür kennt, wird das nur in Elgato Eve funktionieren.
