### ISSUE TITLE
Neues Gerät: HmIP-FCI6 Kontaktinterface 6-Kanal

### ISSUE THREAD

**Issue by joehun** [thkl/hap-homematic#129]
Hallo,

anbei die Datei zu dem Gerät HmIP-FCI6 6-fach Kontakteingänge.

[HmIP-FCI6.json.txt](https://github.com/thkl/hap-homematic/files/4778501/HmIP-FCI6.json.txt)

Mit freundlichen Grüßen,
Jörg Hundgeburth.

**Comment by thkl** [comment]
Dieser Sensor hat PRESS_SHORT und PRESS_LONG (würde also wie ein Key Device funktionieren) aber auch STATE (also wie ein Contact) funktionieren. Kann man das einstellen ? Oder sind die Datenpunkte immer da ?

**Comment by joehun** [comment]
Die einzelnen Eingänge lassen sich einstellen:

• Inaktiv
• Taster
    - kurzer
    - langer Tastendruck
• Schalter
• Tür-/Fensterkontakt

Ich benutze zwei davon um den Füllstand (min/max) meines Gartenteiches zu signalisieren und ein Magnetventil zur Füllung anzusteuern. Dafür sind die Kanäle als Schalter definiert.

**Comment by thkl** [comment]
ok hier kann ich den ChannelTyp MULTI_MODE_INPUT_TRANSMITTER in die Liste vorhandener Services aufnehmen das wären für 
STATE =  Contact / Door / Window 
KEY = PushTheButton / Key ...

**Comment by joehun** [comment]
Hi,

man kann bei diesem Device nur den Status in der Funktion „Contact/Door/Window“ sehen. Schaltbar ist das Device in keiner Funktion. Von daher macht eigentlich nur die Funktion „Contact/Door/Window“ Sinn. 



Hier benutze ich 1, 2 um einen Schaltaktor via Direktverknüpfung anzusteuern und 3, 4 um den jeweiligen Zustand der Schwimmer zu sehen.
1, 3 und 2, 4 sind elektrisch zusammen geschlossen.

**Comment by thkl** [comment]
naja und mit Umprogrammierung können KEY Events ausgelöst werden .. das ist analog den keinen Universal Eingangsbausteinen aus HM Zeiten.
