### ISSUE TITLE
Problem mit Heizungsgruppe

### ISSUE THREAD

**Issue by theo-69** [thkl/hap-homematic#130]
Ich habe immer noch ein Problem mit den Heizungsgruppen.

Wenn ich z.B. von aus auf Automatik oder Heizen Wechsel springt es direkt zurück auf aus. Nutze das Homematic Heizkörperthermostat HM-CC-RT-DN in Verbindung mit dem Raumthermostat HM-TC-IT-WM-W-EU.

**Comment by thkl** [comment]
kann ich im ersten Test so nachvollziehen. Schau ich mir an

**Comment by theo-69** [comment]
schon was gefunden :-)

**Comment by theo-69** [comment]
wann kommt das Update 😢

**Comment by thkl** [comment]
wenn es fertig ist

**Comment by theo-69** [comment]
kurzes Feedback, funktioniert soweit. Nur wenn das dazugehörige Fenster auf ist und man dann auf Automatik geht springt es immer noch zurück auf Aus. Wenn das Fenster zu ist geht es 🤔

**Comment by thkl** [comment]
ja ;) weil dann ein Event für die Target Temperature kommt. Und da die < als die aktuelle Raumtemperatur ist zeigt das Thermostat Aus an .. es heizt ja auch nicht ;)

**Comment by theo-69** [comment]
Ne stimmt nicht, normalerweise kann man auf Automatik wechseln und dann wird die abgesenkte Temperatur angezeigt für geöffnetes Fenster angezeigt. (Bei mir dann 12 Grad) Funktioniert auch bei dir wenn ich zwischendurch Fenster auf zu mache, dann bleibt es bei Automatik. Ein zurückspringen auf Aus ist also ein Fehler. Sonst könnte ich ja nur auf Automatik umstellen wenn das Fenster geschlossen ist. Wäre ja Quatsch.

**Comment by thkl** [comment]
Nein, Du hast schon Recht. Das Thermostat schaltet ja auch nicht auf Aus . Sondern nur die Anzeige in HomeKit sagt Aus wenn die Soll Temp < als die Ist Temp ist.  Das ist aber schon immer so.
In Home schaut das bissel doof aus in Eve ist das besser sichtbar:

![image](https://user-images.githubusercontent.com/884355/87961513-1564af00-cab6-11ea-9055-4a1815876b45.png)

Der Soll Mode ist Auto .. der Ist Mode ist aber Off (weil Target < Current)

**Comment by theo-69** [comment]
Seltsam, denn bei RedMatic schaltet die Anzeige auf Auto und zeigt dann die abgesengte Solltemperatur an. 🤔 Bei hap sehe ich unter EVE bei Modus nur EIN und AUS.

Thermostat bei Redmatic:

![IMG_4885](https://user-images.githubusercontent.com/28484958/88034880-97e68080-cb41-11ea-94a4-aee29fa06c46.PNG)
 unter HAP:

![IMG_4884](https://user-images.githubusercontent.com/28484958/88034901-a0d75200-cb41-11ea-8320-d9c28e272c93.PNG)

**Comment by theo-69** [comment]
irgend eine Idee?
