### ISSUE TITLE
HmIP-BSM

### ISSUE THREAD

**Issue by ChrWi** [thkl/hap-homematic#131]
Version 0.0.47 erkennt vom HmIP-BSM (Schaltaktor mit Leistungsmessung) die Kanäle 1 und 2, jedoch nicht den Aktor (Kanal 4) und Leistungsmessung (Kanal 7). Von der Konfiguration ansonsten sehr ähnlich zum HmIP-PSM, der bereits unterstützt wird.

**Device related data**

[HmIP-BSM.txt](https://github.com/thkl/hap-homematic/files/4810260/HmIP-BSM.txt)

**Comment by thkl** [comment]
Der Kanal 7 ENERGIE_METER_TRANSMITTER müsste erkannt werden. Dieser muss ausgewählt werden. Kanal 4 wird bei Nutzung des HomeMaticIPPowerMeterSwitchAccessory automatisch hinzugefügt

**Comment by ChrWi** [comment]
Jetzt geht es. Gestern nicht. Das Issue kann geschlossen werden.

**Comment by thkl** [comment]
ok
