### ISSUE TITLE
Web UI nicht erreichbar

### ISSUE THREAD

**Issue by Grisu118** [thkl/hap-homematic#132]
Ich hab das Plugin heute installiert, ich komme danach aber nicht auf das WebUI

hmhapinstall.log
```
[Installer]Start installer
[Installer]Program Dir is /usr/local/addons/hap-homematic
[Installer]installing HAP-Homematic ...
[Installer]creating HomeKit Button ...
```

hap-homematic.log
```
[Thu Jun 25 2020 21:15:56 GMT+0200 (CEST)] info - [HAP Server] ---- launching ----
[Thu Jun 25 2020 21:15:56 GMT+0200 (CEST)] info - [HAP Server] Welcome to HAP Homematic. Use your HomeMatic devices in HomeKit
[Thu Jun 25 2020 21:15:56 GMT+0200 (CEST)] info - [HAP Server] (c) 2020 by @thkl - https://github.com/thkl/hap-homematic
[Thu Jun 25 2020 21:15:56 GMT+0200 (CEST)] info - [HAP Server] [Server] Using config from /usr/local/etc/config/addons/hap-homematic/persist
[Thu Jun 25 2020 21:15:56 GMT+0200 (CEST)] info - [HAP Server] Spawning configuration service with PID 1316
[Thu Jun 25 2020 21:15:56 GMT+0200 (CEST)] info - [HAP Server] [Server] current restart count is  1
[Thu Jun 25 2020 21:15:56 GMT+0200 (CEST)] info - [HAP Server] [CCU] check Rega is alive
[Thu Jun 25 2020 21:15:56 GMT+0200 (CEST)] info - [HAP Server] [Server] Rega is alive going ahead
[Thu Jun 25 2020 21:15:56 GMT+0200 (CEST)] info - [HAP Server] [CCU] loading object database for devices from /usr/local/etc/config/addons/hap-homematic/devices.json
[Thu Jun 25 2020 21:15:56 GMT+0200 (CEST)] error - [HAP Server] [CCU] databse not found get a new one
[Thu Jun 25 2020 21:15:56 GMT+0200 (CEST)] info - [HAP Server] [CCU] device database loaded 84 devices found
[Thu Jun 25 2020 21:15:56 GMT+0200 (CEST)] info - [HAP Server] [CCU] loading object database for variables from /usr/local/etc/config/addons/hap-homematic/variables.json
[Thu Jun 25 2020 21:15:56 GMT+0200 (CEST)] error - [HAP Server] [CCU] databse not found get a new one
```

Ich sehe das die `devices.json` angelegt wurde, die `variables.json` fehlt. 

Firewall ist komplett offen
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8182 -j DROP
-A INPUT -p tcp -m tcp --dport 8183 -j DROP
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9874 -j ACCEPT
-A INPUT -p udp -m udp --dport 9874 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9875 -j ACCEPT
-A INPUT -p udp -m udp --dport 9875 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9876 -j ACCEPT
-A INPUT -p udp -m udp --dport 9876 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 9877 -j ACCEPT
-A INPUT -p udp -m udp --dport 9877 -j ACCEPT
....
```

**Comment by thkl** [comment]
http://ccuip:9874/ geht nicht ?

**Comment by Grisu118** [comment]
Nein, sehe auch nicht das jemand auf den Port hört wenn ich `netstat -ltup` ausführe

**Comment by Grisu118** [comment]
Wenn ich `/usr/local/etc/config/rc.d/hap-homematic restart` ausführe um hap-homematic neuzustarten. Sehe ich folgende Meldung in meinem terminal

```
[Thu Jun 25 2020 22:48:08 GMT+0200 (CEST)] [HAP Server] [CCU] databse not found get a new one
(node:11604) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token B in JSON at position 1246
    at JSON.parse (<anonymous>)
    at /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/HomeMaticCCU.js:316:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/configurationsrv/index.js:73
    this.useAuth = config.useCCCAuthentication || false
                          ^

TypeError: Cannot read property 'useCCCAuthentication' of undefined
    at new ConfigurationService (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/configurationsrv/index.js:73:27)
    at Object.<anonymous> (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/configurationsrv/index.js:1702:11)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by thkl** [comment]
Kann ich mal die .json Files aus /etc/config/addons/hap-homematic haben.

**Comment by Grisu118** [comment]
Ich hab das Problem gefunden, das JSON das beim laden der Variablen geladen wurde war ungültig.
Siehe nicht escapte " in dpInfo.
```
{
            "id": 10136,
            "name": "Batteriezustand",
            "dpInfo": "Resultat des Programms "Batterietest"",
            "unerasable": "false",
            "valuetype": 20,
            "subtype": 11,
            "minvalue": "",
            "maxvalue": "",
            "unit": ""
        },
```

Nach bearbeiten dieser Beschreibung gehts.

**Comment by asudeck** [comment]
Moin, also ich habe (sehr wahrscheinlich) das gleiche Problem. Version 0.0.11 als Zusatzsoftware installiert, Ports in der Firewall freigegeben und nach einem Klick auf den Homebridge-Button ist Ende. Die Seite ist nicht erreichbar. Auch wenn ich die Ports komplett freigebe passiert nichts. Im Ordner /etc/config/addons/hap-homematic ist bei mir nur die devices.json zu finden. Auch nach einer Neu-Installation ist das Problem nicht behoben? Ich weiss gerade nicht weiter...

**Comment by thkl** [comment]
Ok.  
Ich schau mir das an. Die Dateien werden aber nach dem Launch wieder neu geladen und überschrieben.

**Comment by asudeck** [comment]
Super, vielen Dank! Jetzt funktioniert es... 👍

**Comment by JarvisHome** [comment]
ich vermute ich hab gerade ein ähnliches Problem:
- Respberrymatic (Version 3.53.30)
- hap-homematic installiert
- button erscheint / komme nicht auf die GUI (Firewall ist es nicht)
- im Folder /etc/config/addons/hap-homematic liegt lediglich eine json Datei (devices.json) -> sieht aber konsistent aus
- Log sagt als letztes:

[Sat Oct 17 2020 09:45:15 GMT+0200 (CEST)] info - [HAP Server] [CCU] loading object database for variables from /usr/local/etc/config/addons/hap-homematic/variables.json

[Sat Oct 17 2020 09:45:15 GMT+0200 (CEST)] error - [HAP Server] [CCU] databse not found get a new one

sprich: er scheint an der viriables.json zu scheiterm,...

würde mich über Hilfe sehr freuen :-)

**Comment by thkl** [comment]
Sonst nix im Log ?

**Comment by JarvisHome** [comment]
glaub nichts relevantes - ganzes log:

[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] ---- launching ----
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] Welcome to HAP Homematic. Use your HomeMatic devices in HomeKit
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] (c) 2020 by @thkl - https://github.com/thkl/hap-homematic
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [Server] settings loading ...
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [Server] config loading completed; start building servicetable
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [Server] service loading completed; publishing services
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [Server] settings loading is done ; continuing init
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [Server] Using config from /usr/local/etc/config/addons/hap-homematic/persist
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] Spawning configuration service with PID 5224
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [Server] current restart count is  5
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [Server] current restart count is  >= 5 disable monitoring
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [Server] Checking rega connection
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [CCU] check Rega is alive
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [Server] Rega is alive going ahead
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [Server] continueInitialization
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [CCU] loading object database for devices from /usr/local/etc/config/addons/hap-homematic/devices.json
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [CCU] object database loaded 263 objects found
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [CCU] device database loaded 263 devices found
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] info - [HAP Server] [CCU] loading object database for variables from /usr/local/etc/config/addons/hap-homematic/variables.json
[Sat Oct 17 2020 09:59:51 GMT+0200 (CEST)] error - [HAP Server] [CCU] databse not found get a new one
~

**Comment by thkl** [comment]
Wir hatten hier irgendwo den Gall das Variablen nicht richtig gelesen wurden, weil sie Sonderzeichen oder sowas enthielten. Ggf ist das auch der Fall.

**Comment by JarvisHome** [comment]
ja, daran dachte ich auch - hatte ich grad schon oberflächlich in der GUI geprüft und nichts gesehen. 

Jedoch kommen beim Direktabruf der Systemvariblen via Skript die folgenden Variablen mit (die in der GUI ja umgeschrieben werden):
${sysVarRainToday}
${sysVarRainYesterday}

Vielleicht sind die das Problem?

**Comment by thkl** [comment]
Ich werde die Namen mal encodieren. Da gibt's im Rega eine Funktion für.

**Comment by thkl** [comment]
die ${ sind im JSON kein Problem solange sie in "" stehen .. aber wenn eine Variable ein " im Namen hat wird es kniffelig ;)

**Comment by JarvisHome** [comment]
ich sehe bei mir jetzt nichts mit Anführungszeichen. Hast du mir einen Tipp was ich weiter teste kann um den Fehler einzugrenzen?

**Comment by thkl** [comment]
Liefert das hier ein Result ? 

´´´
string varid;boolean df = true;Write('{"variables":[');foreach(varid, dom.GetObject(ID_SYSTEM_VARIABLES).EnumIDs()){object ovar = dom.GetObject(varid);if(df) {df = false;} else { Write(',');}Write('{')Write('"id": ' # varid # ',');Write('"name": "');WriteXML(ovar.Name());Write('",');Write('"dpInfo": "');WriteXML(ovar.DPInfo());Write('",');Write('"unerasable": "' # ovar.Unerasable() # '",');Write('"valuetype": ' # ovar.ValueType() # ',');Write('"subtype": ' # ovar.ValueSubType() # ',');Write('"minvalue": "' # ovar.ValueMin() # '",');Write('"maxvalue": "' # ovar.ValueMax() # '",');Write('"unit": "');WriteXML(ovar.ValueUnit());Write('"');Write('}');} Write(']}');
´´´


Im "Script testen" auf dem CCU UI sollte das ein valides JSON mit den Variablen erzeugen

**Comment by JarvisHome** [comment]
das hat geholfen - hab's gefunden :-)
scheint ein (unsichtbares) Sonderzeichen beim Copy & Paste in der Beschreibung einer Systemvariable rein gerutscht zu sein.

Das war der JSON Fehler:
Control character '\u0009' is not allowed in string literals

Hab die Beschreibung dieses Systemvariable angepasst - jetzt geht es

Vielen Dank für die schnelle Hilfe!

**Comment by thkl** [comment]
Das erzeugte JSON war also fehlerhaft ? hmpf ich hatte gehofft WriteXML löst das Problem. Dann muss ich da noch mal nacharbeiten.

**Comment by JarvisHome** [comment]
Naja, die JSON war zwar fehlerhaft - aber durch das Unicode Sonderzeichen für "Tab" (was unterm Strich ja mein Fehler war). Klar, wenn es abgefangen wird - umso besser :-)

**Comment by ax46-git** [comment]
Ich weiss, das dieser Thread schon älter ist, aber jetzt ich habe ein Problem mit dem Plugin.
Ich habe eine CCU3 mit dem aktuelle OpenCCU-Image (3.85.7) geflasht und einige Geräte angelernt.
Anschließend habe ich das HAP-Plugin (Version 0.0.14) ohne Probleme installiert.. Im weiteren Verlauf konnte ich noch 2 Geräte (Schalter) im Plugin verknüpfen und beim dritten Gerät ist das Plugin abgestürzt und macht nichts mehr.
I
ch komme weder auf die UI des Plugins noch sonst was.

Ein Neustart-Versuch des Plugins wird mit einem Fehler dokumentiert. Das hierauf ausgelesene "addon-uninstall-error.log" wirft folgendes aus:
start-stop-daemon: warning: killing process 6949: No such process
kill: you need to specify whom to kill
~

Weiterhin sind im Ordner /etc/config/addons/hap-homemmatic   vier. .crash Dateien. Der Inhalt ist folgender:
Error log : Sun Nov 30 2025 16:05:46 GMT+0100 (Central European Standard Time)

Error: TimeOut
    at ClientRequest.<anonymous> (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/HomeMaticRegaRequest.js:88:16)
    at ClientRequest.emit (node:events:518:28)
    at Socket.emitRequestTimeout (node:_http_client:863:9)
    at Object.onceWrapper (node:events:632:28)
    at Socket.emit (node:events:530:35)
    at Socket._onTimeout (node:net:609:8)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
~
~

Wäre extrem dankbar, wenn mir jemand weiterhelfen könnte.

Vielen Dank und einen schönen Sonntag
Axel
