### ISSUE TITLE
HomeMaticThermometerAccessory - kein Temperatur-Log-Eintrag, wenn Luftfeuchtigkeit ignoriert wird

### ISSUE THREAD

**Issue by jaroschek** [thkl/hap-homematic#133]
In der Datei HomeMaticThermometerAccessory.js sind die Zeilen 71 und 72 ein Copy&Paste-Fehler aus den Zeilen 98 und 99. In den Bedingungen in Zeile 71 und 72 wird auf self.ignoreTemp geprüft. Hier müsste aber auf self.ignoreHum geprüft werden und in Zeile 72 sollte die Prüfung sich auf die humidity auswirken. Durch den Fehler in der Bedingung wird kein Temperatur-Log-Eintrag erzeugt, wenn der Sensor keine Luftfeuchtigkeit liefern kann (z.B. HM-WDS30-T-O).

**Comment by jaroschek** [comment]
Sorry für die falschen Service-Namen. Bin da beim Review etwas durcheinander gekommen, weil ich auch noch eine Idee für den Garagentor-Service habe. Das werde ich aber zunächst selbst in einem Fork ausprobieren und ggf. als Merge-Request bereitstellen.

Hier beim HomeMaticThermometerAccessory wäre noch die Teile 72 zu verändern, um hier den Wert für humidity in Abhängigkeit von self.ignoreHum entweder mit 0 oder mit self.currentHumidity zu befüllen. Das müsste quasi die umgekehrte Variante zu Zeile 99 werden.

**Comment by thkl** [comment]
Oh ja, danke für die Info. Das hatte ich übersehen ...

**Comment by jaroschek** [comment]
Die mit den Code-Änderungen werden die Log-Einträge für die reinen Temperatur-Sensoren (z.B. HM-WDS30-T-O) jetzt erzeugt. Vielen Dank für den schnellen Bugfix!
