### ISSUE TITLE
Ich verweise mal auf ein closed

### ISSUE THREAD

**Issue by AdlerCentauri** [thkl/hap-homematic#134]
Es wäre wirklich sehr nice @thkl 

https://github.com/thkl/hap-homematic/issues/40

Von mir aus auch sehr gerne sozusagen als In-App mit einer Spende. Es haben ja mehrere Interesse.

**Comment by theo-69** [comment]
Bitte nicht die HAP zu weit aufblähen!!! Ich brauche es nicht und möchte auch nicht das eine PlugInn unnötig aufgebläht wird!!!

**Comment by thkl** [comment]
Ich hatte das doch schon in dem geschlossenen Issue erklärt.  Das Projekt hier dreht sich um die HomeKit Anbindung der CCU  + Geräte.  Eine Integration der Logitech Harmony steht nicht zur Debatte.  Das ist einfach out of scope.

**Comment by dkrizic** [comment]
@AdlerCentauri Es gibt doch https://github.com/nicoduj/homebridge-harmony, das funktioniert super.

**Comment by AdlerCentauri** [comment]
Ach so, @theo-69 und weil Du es nicht brauchst, brauchen es andere auch nicht, alles klar! 😂

**Comment by mike4president** [comment]
☮️
