### ISSUE TITLE
Interface null führt zu Cash von HAP-Homematic

### ISSUE THREAD

**Issue by Meeppoo** [thkl/hap-homematic#135]
Hi zusammen,

evtl. kann mir einer helfen oder mich in die richtige Richtung schubsen. :upside_down_face:

HAP-Homematic cashed immer mit folgendem Fehler:
>(node:27480) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/HomeMaticCCU.js:695:33
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:27480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To terminate
the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict`
> -(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`

Im Log der Homematic steht folgendes dazu:
>Jul  3 08:19:01 homematic-raspi local0.info ReGaHss: Info: ScriptRuntimeError: Stack trace: [-1]   0 0x0000 [0]  56 0x0038 [1]   0 0x0000 [2]  58 0x003a [3]   0 0x0000 [4]  59 0x003b  [ExecError():iseESPexec.cpp:12797]
Jul  3 08:19:01 homematic-raspi local0.err ReGaHss: ERROR: ScriptRuntimeError: string sifId;boolean df = true;Write('{"interfaces":[');foreach(sifId, root.Interfaces().EnumIDs()){object oIf = dom.GetObject(sifId);if(df) {df = false;} else { Write(',');}Write('{')Write('"id": ' # sifId # ',');Write('"name": "' # oIf.Name() # '",');Write('"type": "' # oIf.Type() # '",');Write('"typename": "' # oIf.TypeName() # '",');Write('"info": "' # oIf.InterfaceInfo() # '",');Write('"url": "' # oIf.InterfaceUrl() # 
>-'"');Write('}');} Write(']}'); [ExecError():iseESPexec.cpp:12798]`

Nachdem ich mich mit dem Code an der betroffenen Stelle auseinandergesetzt habe, konnte ich feststellen, dass ich ein Interface null habe. Zumindest wird dieses angezeigt, wenn ich das Script etwas umgestalte und händisch ausführe.

![image](https://user-images.githubusercontent.com/46077083/86456690-c16e7200-bd22-11ea-9599-b47082be55ef.png)

Daher ist auch klar warum HAP-Homematic cashed, da es an der betroffenen Stelle versucht ein JSON zu erstellen. Dieses schlägt natürlich fehl, bei einem Interface null ohne Type usw.

Ich konnte das mit einem Workaround (valid JSON hardcoded in HomeMaticCCU.js) umgehen. :zany_face: Der Rest funktioniert ohne Probleme, also fetchen von Räumen, Devices etc.

Nun zu der Frage hatte jemand das schon mal? Oder weiß wie ich das Interface null wieder loswerde? :thinking:
Bin bei Homematic nicht so 100% in der Materie, was das Backend angeht.

Problematisch wird mein Workaround bei Updates und es ist einfach, nicht schön mit einem Workaround etwas zu lösen, was funktionieren sollte. Sollte so etwas schon öfter vorgekommen sein, trage ich gerne etwas dazu bei, dass der Fehler anderen erspart bleibt. Sofern das gewünscht ist.

Sollte ich auf einer ganz falschen Spur sein, bin ich über jede Hilfe dankbar. :relaxed:

**Comment by thkl** [comment]
Kannst du mal bitte das geänderte Script zum fetch der Interfaces hier probieren ... 

```
string sifId;boolean df = true;Write('{"interfaces":[');foreach(sifId, root.Interfaces().EnumIDs()){object oIf = dom.GetObject(sifId);if (oIf) {if(df) {df = false;} else { Write(',');}Write('{')Write('"id": ' # sifId # ',');Write('"name": "' # oIf.Name() # '",');Write('"type": "' # oIf.Type() # '",');Write('"typename": "' # oIf.TypeName() # '",');Write('"info": "' # oIf.InterfaceInfo() # '",');Write('"url": "' # oIf.InterfaceUrl() # '"');Write('}');}} Write(']}');
```

Das checkt erst ob die gelieferte ID auch wirklich existiert.
Es müsste ein JSON mit den Interfacedaten zurückkommen.

**Comment by Meeppoo** [comment]
Jap funktioniert. Gibt nur die existierenden Interfaces zurück. Soll ich ein Pull Request dafür machen oder machst es schnell selbst? Danke für die schnelle Antwort.

**Comment by isi07** [comment]
Das hat auch mein Problem gelöst. Hat jemand eine Idee, wie man so ein null Interface wieder loswird?
