### ISSUE TITLE
Alle Einstellungen verloren

### ISSUE THREAD

**Issue by joehun** [thkl/hap-homematic#136]
Die HAP Installation hat alle Einstellungen verloren. Neue Instanzen sind nicht mehr anlegst, neue Geräte können nicht hinzugefügt werden. Logfile kann nicht runtergeladen werden. Debug Modus ändert nichts, Neustart CCU ändert nichts, Neustart HAP ändert nichts.

System Ccu3: 3.51.6

HomeKit Version 0.0.11
HAP Version 0.0.47
Cux Deamon 2.4.4
Neo Server 2.5.4
Hue Addon 3.0.12

**Comment by thkl** [comment]
Klingt nach einer kaputten config.json
Das File liegt unter /usr/local/etc/config/addons/hap-homematic 

Ggf kann das mal in jsonlint.com geworfen werden um zu testen wo der Fehler ist. 

Oder mal hier anhängen.

**Comment by thkl** [comment]
hat sich das hier erledigt ?

**Comment by joehun** [comment]
Nein, habe es nur noch nicht untersuchen können.

**Comment by joehun** [comment]
Ich habe mir mehrere json-files angeschaut, alle waren syntaktisch in Ordnung.

**Comment by thkl** [comment]
Kann ich mal ein geziptes Archiv des Config Folders haben.  Mail Adresse steht in jedem Sourcefile

**Comment by joehun** [comment]
Danke Thomas,

die Änderung des fehlerhaften Eintrages in der "variables.json" hat geholfen.

Vielen Dank für die super Unterstützung.

**Comment by thkl** [comment]
Ähm der Fehler ist in der config.json .. die variables.json wird automatisch aus der CCU erzeugt.
