### ISSUE TITLE
Variablen werden nicht aktualisiert

### ISSUE THREAD

**Issue by HomematicHamburg** [thkl/hap-homematic#137]
Bei mir werden trotz Trigger die Variablen nicht aktualisiert. Habe HAP extra installiert, da auch über Homebridge keine Aktualisierung funktioniert.

Einsatzgebiet:
Der Zustand einer Variable soll abgegriffen werden, um in Homekit meine Homekit-fähigen-Jalousien über eine Automatition zu steuern (Taster oben (Homematic) = Variable Jalousieoben "an" (Homematic) -> Jalousie 100% (Dritthersteller)).

Kann jemand helfen?

**Comment by thkl** [comment]
Wird die virtuelle Taste in der CCU denn beim Ändern ausgelöst ?

**Comment by HomematicHamburg** [comment]
Programmiert ist es. Die Variable wird geändert, das Update kommt in Homekit nicht an.
Sofern du die virtuelle Taste meinst, ich habe dies versucht über einen Favoriten zu kontrollieren (richtiger Weg?). Wird leider nicht gedrückt, sofern ich das richtig einschätze.

**Comment by thkl** [comment]
Das kann man auf der HomeMatic WebUI sehen in den Geräten gibt es ja die 50er virtuelle Fernbedienung. Da sind alle Tasten aufgelistet. Die, die als Trigger für die Variablenänderung benutzt wird muss beim Ändern der Variable auslösen. Sonst bekommt HAP das nicht mit. Und fragt die Variablen nicht neu ab.

![image](https://user-images.githubusercontent.com/884355/87052729-65fc2280-c201-11ea-84d0-36dc51a134cc.png)

**Comment by HomematicHamburg** [comment]
Taster wird gedrückt, da die Uhrzeit bei Statusänderung aktualisiert wird allerdings kommt die Statusänderung nicht in Homekit an

**Comment by thkl** [comment]
Dann mal den Debug Modus über das WebUI von HAP einschalten und die Taste einmal auslösen.
Dann müsste im Log sowas hier stehen (entsprechend angepasst an die eigenen Einstellungen)

```
[Fri Jul 10 2020 22:17:10 GMT+0200 (CEST)] [HAP Server] [RPC] event for BidCos-RF.BidCoS-RF:49.PRESS_SHORT with value true
[Fri Jul 10 2020 22:17:10 GMT+0200 (CEST)] [HAP Server] [Rega] RegaScript object o = dom.GetObject(ID_SYSTEM_VARIABLES).Get('EZTemp');if (o){Write(o.State());}
````


BidCos-RF.BidCoS-RF:49.PRESS_SHORT ist die Virtuelle Taste (Key 49)
und in dem Falle wird EZTemp aktualisiert.

Wenn das nicht so auftaucht bitte mal checken ob die richtige Taste in den Variablen als Trigger gewählt wurde.

**Comment by HomematicHamburg** [comment]
Im Log erscheint der von dir angefügte Code nicht exakt - siehe anbei.
Ich habe in HAP auch nicht einen Temperatursensor, sondern eine Variable definiert, da ich den An/Aus-Status brauche. Das ist korrekt?

Vielleicht mache ich ja auch einen Fehler in der Programmierung.

Ich muss doch die Variable mittels eines physischen Schalters ändern und nicht die virtuelle Taste als Trigger, oder? Der Trigger wird nämlich auch betätigt, wenn ich den physischen Schalter drücke.

`[Mon` Jul 13 2020 09:00:01 GMT+0200 (CEST)] debug - [HAP Server] [CCU] updateCCUVarTrigger get datapoint and channel ids BidCos-RF.BidCoS-RF:40.PRESS_SHORT
[Mon Jul 13 2020 09:00:01 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript object x = dom.GetObject('BidCos-RF.BidCoS-RF:40.PRESS_SHORT');Write('{"DpId":' # x.ID() # ',');Write('"ChId":' # x.Channel() # '}');
[Mon Jul 13 2020 09:00:01 GMT+0200 (CEST)] debug - [HAP Server] [Rega] result is {"DpId":1174,"ChId":1171}
[Mon Jul 13 2020 09:00:01 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript object oPTmp = dom.GetObject( ID_PROGRAMS );object program = dom.GetObject("_hap_autotrigger_");if (program) { dom.DeleteObject(program);}program = dom.CreateObject(OT_PROGRAM);program.PrgInfo("This program will autotrigger the variable updater for hap-homematic.");program.Name("_hap_autotrigger_");boolean bF1 = oPTmp.Add(program.ID());object rule = program.Rule();object destn = rule.RuleDestination();object n_condition;if (rule.RuleConditions().Count()>0) {n_condition = rule.RuleConditions(0);} else {n_condition = rule.RuleAddCondition();}n_condition.CndOperatorType(2);object s_cond;object dest = destn.DestAddSingle();dest.DestinationParam(ivtObjectId);dest.DestinationChannel(1171);dest.DestinationDP(1174);dest.DestinationValueType(ivtBinary);dest.DestinationValue(1);s_cond = n_condition.CndAddSingle();s_cond.OperatorType(2);s_cond.ConditionType(9);s_cond.ConditionType2(13);s_cond.LeftValType(19);s_cond.ConditionChannel(65535);s_cond.LeftVal(57559);s_cond.RightVal1("");program.Active(true);dom.RTUpdate(0);
[Mon Jul 13 2020 09:00:01 GMT+0200 (CEST)] debug - [HAP Server] [Rega] result is 
[Mon Jul 13 2020 09:00:02 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript string sifId;boolean df = true;Write('{"interfaces":[');foreach(sifId, root.Interfaces().EnumIDs()){object oIf = dom.GetObject(sifId);if(df) {df = false;} else { Write(',');}Write('{')Write('"id": ' # sifId # ',');Write('"name": "' # oIf.Name() # '",');Write('"type": "' # oIf.Type() # '",');Write('"typename": "' # oIf.TypeName() # '",');Write('"info": "' # oIf.InterfaceInfo() # '",');Write('"url": "' # oIf.InterfaceUrl() # '"');Write('}');} Write(']}');
[Mon Jul 13 2020 09:00:02 GMT+0200 (CEST)] debug - [HAP Server] [Rega] result is {"interfaces":[{"id": 1009,"name": "BidCos-RF","type": "458753","typename": "INTERFACE","info": "BidCos-RF","url": "xmlrpc_bin://127.0.0.1:32001"},{"id": 1010,"name": "VirtualDevices","type": "458753","typename": "INTERFACE","info": "Virtual Devices","url": "xmlrpc://127.0.0.1:39292/groups"},{"id": 1011,"name": "HmIP-RF","type": "458753","typename": "INTERFACE","info": "HmIP-RF","url": "xmlrpc://127.0.0.1:32010"}]}

**Comment by HomematicHamburg** [comment]
Im Log erscheint der von dir angefügte Code nicht exakt - siehe anbei.
Ich habe in HAP auch nicht einen Temperatursensor, sondern eine Variable definiert, da ich den An/Aus-Status brauche. Das ist korrekt?

Vielleicht mache ich ja auch einen Fehler in der Programmierung.

Ich muss doch die Variable mittels eines physischen Schalters ändern und nicht die virtuelle Taste als Trigger, oder? Der Trigger wird nämlich auch betätigt, wenn ich den physischen Schalter drücke.

`[Mon` Jul 13 2020 09:00:01 GMT+0200 (CEST)] debug - [HAP Server] [CCU] updateCCUVarTrigger get datapoint and channel ids BidCos-RF.BidCoS-RF:40.PRESS_SHORT
[Mon Jul 13 2020 09:00:01 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript object x = dom.GetObject('BidCos-RF.BidCoS-RF:40.PRESS_SHORT');Write('{"DpId":' # x.ID() # ',');Write('"ChId":' # x.Channel() # '}');
[Mon Jul 13 2020 09:00:01 GMT+0200 (CEST)] debug - [HAP Server] [Rega] result is {"DpId":1174,"ChId":1171}
[Mon Jul 13 2020 09:00:01 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript object oPTmp = dom.GetObject( ID_PROGRAMS );object program = dom.GetObject("_hap_autotrigger_");if (program) { dom.DeleteObject(program);}program = dom.CreateObject(OT_PROGRAM);program.PrgInfo("This program will autotrigger the variable updater for hap-homematic.");program.Name("_hap_autotrigger_");boolean bF1 = oPTmp.Add(program.ID());object rule = program.Rule();object destn = rule.RuleDestination();object n_condition;if (rule.RuleConditions().Count()>0) {n_condition = rule.RuleConditions(0);} else {n_condition = rule.RuleAddCondition();}n_condition.CndOperatorType(2);object s_cond;object dest = destn.DestAddSingle();dest.DestinationParam(ivtObjectId);dest.DestinationChannel(1171);dest.DestinationDP(1174);dest.DestinationValueType(ivtBinary);dest.DestinationValue(1);s_cond = n_condition.CndAddSingle();s_cond.OperatorType(2);s_cond.ConditionType(9);s_cond.ConditionType2(13);s_cond.LeftValType(19);s_cond.ConditionChannel(65535);s_cond.LeftVal(57559);s_cond.RightVal1("");program.Active(true);dom.RTUpdate(0);
[Mon Jul 13 2020 09:00:01 GMT+0200 (CEST)] debug - [HAP Server] [Rega] result is 
[Mon Jul 13 2020 09:00:02 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript string sifId;boolean df = true;Write('{"interfaces":[');foreach(sifId, root.Interfaces().EnumIDs()){object oIf = dom.GetObject(sifId);if(df) {df = false;} else { Write(',');}Write('{')Write('"id": ' # sifId # ',');Write('"name": "' # oIf.Name() # '",');Write('"type": "' # oIf.Type() # '",');Write('"typename": "' # oIf.TypeName() # '",');Write('"info": "' # oIf.InterfaceInfo() # '",');Write('"url": "' # oIf.InterfaceUrl() # '"');Write('}');} Write(']}');
[Mon Jul 13 2020 09:00:02 GMT+0200 (CEST)] debug - [HAP Server] [Rega] result is {"interfaces":[{"id": 1009,"name": "BidCos-RF","type": "458753","typename": "INTERFACE","info": "BidCos-RF","url": "xmlrpc_bin://127.0.0.1:32001"},{"id": 1010,"name": "VirtualDevices","type": "458753","typename": "INTERFACE","info": "Virtual Devices","url": "xmlrpc://127.0.0.1:39292/groups"},{"id": 1011,"name": "HmIP-RF","type": "458753","typename": "INTERFACE","info": "HmIP-RF","url": "xmlrpc://127.0.0.1:32010"}]}``

**Comment by thkl** [comment]
Also es sollte eine virtuelle Taste sein. Laut log wurde ja auch die Virtuelle Taste 40 ausgewählt und das Programm dazu auf der CCU erstellt.  Jetzt sollte beim ändern  der eingebundenen Variable das Programm "hap-autotrigger" auslösen und die Virtuelle Taste 40 gedrückt werden.  Passiert das ?

**Comment by HomematicHamburg** [comment]
Die Taste wird laut Spalte "letzte Änderung" gedrückt. Allerdings kommt die Änderung in Homekit nicht an. 
Im Programm ändere ich die Variable. Das ist korrekt oder muss ich den Schalter drücken oder beides?

**Comment by thkl** [comment]
Das HIlfsprogramm sorgt dafür, das beim Ändern einer Variable die Virtuelle Taste gedrückt wird.
Ich bau mal mehr logging ein für diese Funktion.

**Comment by HomematicHamburg** [comment]
Hab zur Sicherheit den Trigger auch nochmal bei der Homebridge rausgenommen. Auch kein Effekt. Mache ich was falsch oder vergesse was? Muss doch eigentlich nur in HAP bei Variablen meine Variable auswählen, den Raum in Homekit einbinden (Variable erscheint auch!) und den Trigger definieren. Läuft der Trigger gerade ins Leere? Wie kann ich den dahinterliegenden Skript sehen in der Oberfläche?

**Comment by roe1974** [comment]
Du musst in der CCU ein Programm anlegen (oder ein bestehendes verwenden) indem bei jeder Änderung dieser Variable die virtuelle Taste (die, die du als Trigger in HAP definiert hast) einfach gefrückt wird. Hast Du das so umgesetzt ?

**Comment by HomematicHamburg** [comment]
Das habe ich durch HAP im Bereich Variablen machen lassen. Also ja

**Comment by HomematicHamburg** [comment]
Die Taste wird auch gedrückt, was im Statusbereich der Homematic sehe. Nur aktualisiert Homekit den Status nach wie vor nicht

**Comment by roe1974** [comment]
nicht durch HAP .... in der CCU !! ... dort muss bei Veränderung der Variable (nehmen wir an eine boolean Variable, die von true auf false gestezt wird) die virtuelle Taste (die, die du in HAP als Trigger definiert hast) gedrückt werden. Ich Habe dafür ein Programm wo alle relevanten Variablen (die ich in HAP/HK darstelle) enthalten sind ....

**Comment by roe1974** [comment]
...also WENN variabel1 auf "true" ODER variable1 auf "false" ODER variable2 auf "true" ODER variable2 auf "false" ...... DANN taste xyz PRESS SHORT

**Comment by roe1974** [comment]
PSS: aber dieses Hilfsprogramm wird ja inzwischen automatisch angelegt ...oder ?

**Comment by HomematicHamburg** [comment]
Genau. Das Hilfsprogamm wird automatisch angelegt.

Warum auch immer funktioniert es jetzt. Habe das Problem gefunden, welches mich zum nächsten Problem bringt:

Es funktioniert nur, wenn ich Homekit einmal schließe und öffne. Lasse ich Homekit offen, wird der Status nicht aktualisiert.

Mein Szenario: Mit einem Homematic Wandschalter möchte ich einen Status ändern. Homekit (also das Apple TV) soll diese Änderung sofort erkennen und die Jalousien (Dritthersteller, welcher mit Homekit verbunden ist) schließen. Bei Änderung der Variable klappt das jetzt auch alles. Nur muss Homekit geöffnet sein, was aktuell keinen Sinn macht.

**Comment by roe1974** [comment]
verstehe ich nicht ganz....
homekit wandschalter = eine hardware (schalter) der homekit zertifiziert ist ... oder ist das die variable ?
die jalousie ist auch in homekit eingebunden ? ... über HAP oder homerbridge ?

**Comment by HomematicHamburg** [comment]
der wandschalter ist von homematic. in der ccu3 lege ich fest, dass der wandschalter die variable ändert. bei variablenänderung in homekit wird die jalousie bewegt. dies erfolgt aber nur, wenn ich die homekit app öffne/schließe. ich hätte es gerne, dass es (logischerweise) ohne die app funktioniert

**Comment by roe1974** [comment]
ok, dh die jalousie ist nicht in der ccu, richtig ?

**Comment by HomematicHamburg** [comment]
Gut ding will Weile haben: ich habs :-)

Man muss es nicht über eine Variable lösen. Großer Denkfehler von mir...man kann in HAP ja Geräte als in meinem Fall Schalter einbinden. Super Lösung. Ein riesen Lob an die Entwickler!!!!!!

**Comment by roe1974** [comment]
genau :-) :-P

**Comment by thkl** [comment]
Geht das jetzt ?

**Comment by HomematicHamburg** [comment]
funktioniert :-)
