### ISSUE TITLE
Erlaube Mehrfachzuweisungen von HM Geräten

### ISSUE THREAD

**Issue by MephistoJB** [thkl/hap-homematic#138]
Derzeit lässt sich ein HM Gerät nur einer HAP Instanz zuordnen. Das macht es schwierig, wenn man mehrere Arbeitsumgebungen hat, die auf HAP zugreifen wollen, weil eine HAP Instanz (vermutlich aufgrund der Protokolls) immer nur mit einem "Haus" verknüpfbar ist.

Das könnte recht einfach gelöst werden denke ich, wenn es möglich wäre ein HM Gerät mehreren HAP Instanzen zuweisen zu können.

**Comment by thkl** [comment]
Soll dann das HM Gerät in eine eigene Instanz für ein zweites "Zuhause" gesetzt werden ?

**Comment by MephistoJB** [comment]
Grundsätzlich schon. Besser wäre aber jedes HM Gerät in beliebig vielen HAP Instanzen "verwerten" zu können.

**Comment by thkl** [comment]
Ok, das geht prinzipiell allerdings ist der Aufwand das umzusetzen sehr hoch. Ich muss dafür das komplette Eventhandling umbauen.

**Comment by MephistoJB** [comment]
Oh ok, hatte angenommen, das wäre ne Kleinigkeit. Wenn ich irgendwie unterstützen kann sag Bescheid. Bin zwar nicht der Mega Progger, aber ein bisschen was geht schon.

**Comment by thkl** [comment]
ne Kleinigkeit is hier nix

**Comment by JensBonse** [comment]
Wäre es da nicht eher ratsam HomeBridge zu benutzen, bevor hier dieser Sonderfall in HAP umgesetzt werden müsste?
Mit einer eigenen HomeBridge kann man auch noch andere Geräte in mehrere Homes bringen.

**Comment by thkl** [comment]
Naja Homebridge = eigener Pi dafür ...(bzw eigene Virtualisierung) und dort ist das Eventhandling genauso ...

**Comment by thkl** [comment]
Also ich hab mal bissel rum probiert. Es lässt sich einbauen. Aber wenn, dann in allen Instanzen mit den gleichen Einstellungen.

**Comment by MephistoJB** [comment]
Spricht aus meiner Sicht nix dagegen. Würde meinem Anwendungsfall sogar entsprechen.

**Comment by thkl** [comment]
So, 
In der Liste schaut das dann so aus:

![Bildschirmfoto 2020-07-12 um 17 10 08](https://user-images.githubusercontent.com/884355/87250020-ab6b5a80-c462-11ea-8697-967da9043aaf.png)

+1 heisst das das Gerät in einer 2. Instanz vorhanden ist.


Settings:

![Bildschirmfoto 2020-07-12 um 17 09 11](https://user-images.githubusercontent.com/884355/87250032-bc1bd080-c462-11ea-8f63-ee40cfc74e1c.png)

**Comment by MephistoJB** [comment]
Genial, das ging ja mal echt schnell. Ist gut umgesetzt.

**Comment by MephistoJB** [comment]
Machst du dafür eigentlich ein neues Release oder kann ich / soll ich einfach die Dateien austauschen?

**Comment by thkl** [comment]
Es müssen mehrere Dateien getauscht werden. Nicht nur aus dem letzten Commit. 

Da sich einiges gesammelt hat würde ich diese Woche mal wieder ein Release bauen.  Ich müsste aber noch einen Installationstest machen.

**Comment by MephistoJB** [comment]
Kurze Frage. Ich habe gesehen dass du den changelog angepasst hast. Ist es erforderlich dass du nochmal ein installer Paket zusammenstellst oder kann ich irgendwie anders updaten?

**Comment by thkl** [comment]
Update geht über die WebOberfläche. Der Installer bleibt der alte.
