### ISSUE TITLE
HMIP-WGC als Garagentor in Homekit

### ISSUE THREAD

**Issue by MattN82** [thkl/hap-homematic#139]
Hallo,

das hat jetzt nicht die Wahnsinns-Prio. :-) Ich hab grad nen HMIP-WGC Garagentortaster verbaut.
hap-homematic erkennt das Gerät und ich kann es als "Switch" konfigurieren.
(Funktioniert....mit nicht unerheblicher Verzögerung, aber es funktioniert)

Aus IOBroker weiß ich, dass es die Kategorie "Garagentor" (bzw. Garage door opener) gibt....ein Blick in die belegbaren Funktionen sieht jedoch nicht danach aus, als ob man Taster da irgendwie einbinden könnte.
Iobroker bietet mir an: LockCurrentState, LockTargetState, Name, CurrentDoorState, ObstructionDetected und TargetDoorState.

Testbelegung ergab: Egal wohin man den Taster packt: Keine Reaktion. (Macht ja auch irgendwo Sinn, wenn man sich die Art der Funktionen anschaut.

Meine Frage wäre: Kann man HomeKit mittels hap-homematic das Ding irgendwie als Garage verkaufen?

Danke und Gruß!

**Comment by thkl** [comment]
Das geht schon :
https://github.com/thkl/hap-homematic/issues/98

**Comment by MattN82** [comment]
Sorry, dass ich das nicht selbst gefunden hab und:
Danke!

**Comment by thkl** [comment]
macht ja nix
