### ISSUE TITLE
Kosmetik: Typo Fehler im log .... "serivce" statt "service"

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#14]
Hallo Thomas

Hier ein Beispiel ;-)

"200 (CEST)] info - [HAP Server] [Server] **serivce** used for Ventilator Badezimmer is HomeMaticSwitchAccessory"

lg Richard

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/80404272-3f487400-88c1-11ea-8f98-04440d1c4684.png)

**Comment by roe1974** [comment]
:-P :-P :-P
