### ISSUE TITLE
Absturz nach Löschen von HVL

### ISSUE THREAD

**Issue by isi07** [thkl/hap-homematic#140]
Hallo
meine HAP Installation ist leider komplett abgeschmiert.
Auch nach mehrmaligem Neuinstallieren, bekomme ich es nicht wieder zum Laufen.

Ich habe HVL (Homematic Virtual Interface) deinstalliert.
https://github.com/thkl/Homematic-Virtual-Interface
Nach dieser Anleitung:

> How to remove the stuff:
> There is currently no automated process so you have to do it step by step. 1st make sure the hvl is still running (ccu is not able to remove objects without response from interface) 2nd remove all your virtual devices from your ccu's device list 3rd remove the changes in in /etc/config_templates/InterfacesList.xml 4rd run this to remove the interface from regadom at your ccu's webinterface (Programs/Test Script): dom.DeleteObject(dom.GetObject('HVL')); 5th reboot your ccu

Jetzt geht nichts mehr.
Ich vermute, es ist irgendetwas von diesem Interface übrig geblieben.
HAP hängt sich beim Starten, beim Einlesen von Interfaces auf.
Hier der letzte Eintrag in
/var/log/hap-homematic.log

> [Mon Jul 13 2020 19:58:37 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript string sifId;boolean df = true;Write('{"interfaces":[');foreach(sifId, root.Interfaces().EnumIDs()){object oIf = dom.GetObject(sifId);if(df) {df = false;} else { Write(',');}Write('{')Write('"id": ' # sifId # ',');Write('"name": "' # oIf.Name() # '",');Write('"type": "' # oIf.Type() # '",');Write('"typename": "' # oIf.TypeName() # '",');Write('"info": "' # oIf.InterfaceInfo() # '",');Write('"url": "' # oIf.InterfaceUrl() # '"');Write('}');} Write(']}');

> [Mon Jul 13 2020 19:58:37 GMT+0200 (CEST)] debug - [HAP Server] [Rega] result is {"interfaces":[{"id": 1009,"name": "BidCos-RF","type": "458753","typename": "INTERFACE","info": "BidCos-RF","url": "xmlrpc_bin://127.0.0.1:32001"},{"id": 1010,"name": "VirtualDevices","type": "458753","typename": "INTERFACE","info": "Virtual Devices","url": "xmlrpc://127.0.0.1:39292/groups"},{"id": 1011,"name": "HmIP-RF","type": "458753","typename": "INTERFACE","info": "HmIP-RF","url": "xmlrpc://127.0.0.1:32010"},{"id": 1503,"name": "CUxD","type": "458753","typename": "INTERFACE","info": "CUxD","url": "xmlrpc_bin://127.0.0.1:8701"},{"id": 1504,"name": "

Kann jemand helfen, wie es wieder zum Laufen bekomme?
Die Webseite ist zwar erreichbar, aber man kann keine Kofiguration anlegen. Auch eine vorherige Sicherung einspielen bringt keinen Erfolg.

Vielen Dank
Christian

**Comment by thkl** [comment]
ich denke mal das problem ist vergleichbar mit dem hier #135 das wäre die Lösung: https://github.com/thkl/hap-homematic/commit/8da601deec677a4d51895a663b4ae561bc04e7c0#diff-18c2197f5a8240571ff5b2966df6b4dd

**Comment by isi07** [comment]
Danke!!!
Das war das Problem. Lösung hat funktioniert.

**Comment by thkl** [comment]
ok ist dann 4all im nächsten release gefixt
