### ISSUE TITLE
Poweropti -> CCU Sytemvariable -> HAP homematic -> Eve App

### ISSUE THREAD

**Issue by mike4president** [thkl/hap-homematic#141]
Hallo Thomas,

ich habe ein recht ungewöhnliches Anliegen. ich bin seit heute Besitzer eines Poweropti. 

https://poweropti.powerfox.energy
https://www.youtube.com/watch?v=80rKCotSLA0

Mein Stromzähler war Gott sei Dank kompatibel. 

Der Poweropti bietet eine API Schnittstelle, um die Daten in die CCU übertragen zu können. Die Anbindung wurde aber bisher noch von niemanden umgesetzt und das übersteigt meine Fähigkeiten.

[powerfox-Kunden-API.pdf](https://github.com/thkl/hap-homematic/files/4926593/powerfox-Kunden-API.pdf)

Was ich jetzt klasse fände, wenn man die Verbrauchsdaten über fagegato in die Eve-App bekommen könnte. Mein Gedanke war, dass man dafür doch eine Anbindung an die CCU per Systemvariable oder so schaffen könnte und danach die Systemvariable als Gerät in Homekit mit den entsprechenden Fakegato-Daten. 

Wäre das machbar?

Gruß

Mike

**Comment by thkl** [comment]
Es gibt einen Service der eine Variable als Grundlage für einen Leistungsmesser (Verbrauchsdaten) benutzt.

**Comment by mike4president** [comment]
Okay, scheitert für mich aber leider daran, dass ich es nicht schaffen werden die API in der CCU umzusetzen. Ist aber nicht weiter wild. Eine letzte Frage noch: Nachdem mich die CCU nun bereits mehrfach im Stich gelassen hat (ohne sichtbaren Grund Verbindung zum LAN verloren - im Urlaub schlecht - und verbindet sich auch nicht wieder neu), bin ich erstmal wieder beim AccessPoint. besteht die Möglichkeit, dass dein Addon auch irgendwann für den Homematic IP AccessPoint verfügbar wird? 

Home Assistant beispielsweise nutzt die homematicip-rest-api um das zu ermöglichen.

https://github.com/coreGreenberet/homematicip-rest-api

Man kommt aber mit Home Assistant nicht auf so elegante Ergebnisse wie mit deiner Lösung, insbesondere was auch Fakegato angeht. Besteht da eine Chance? Grüße

**Comment by thkl** [comment]
Soweit ich das weiss, kann man auf dem AccessPoint nichts laufen lassen.

**Comment by roe1974** [comment]
Würde mal das Problem in deinem Netz suchen ... hatte bis jetzt mit noch keiner Raspberrymatic Version ein Problem .... schon gar nicht so eines wie du beschreibst ....sehr seltsam ....

**Comment by mike4president** [comment]
Der fängt nach paar Tagen immer wieder an fröhlich blau vor sich hinzublicken und ich komme erste wieder auf die CCU, wenn ich den Stecker gezogen habe. Das hatte ich in der gleichen Netzwerkumgebung mit dem Access Point nie. Hat er im Urlaub paarmal gemacht. Echt doof wenn man dann unterwegs ist. Habe schon gegoogelt, aber finde nicht die richtige Lösung. Ich muss auch zugeben, dass ich von der CCU selber sehr enttäuscht bin. Es macht zwar Spaß, wenn man den Bogen raus hat, aber die Lernkurve ist für Anfänger schon recht steil. 

Mit einem modernen intuitiveren WebUI könnte man das vielen Nutzern einfacher machen. HAP ist doch auch einfach zu bedienen. Ich verstehe nicht, warum eq3 das nicht auf die Reihe bekommt. Irgendwie ist fast alles in der CCU kompliziert gestaltet. Ich hab aber die Hoffnung nicht zu 100 Prozent aufgegeben, dass sie da irgendwann noch nachbessern. 

@Thomas: ich hatte gehofft, dass man HAP irgendwie ich zusätzlich auf einen Raspberry ziehen könnte und dann über die Cloudanbindung an die IP Cloud auch den AccessPoint anbinden könnte.

Aber ich kann verstehen, wenn das nicht so dein Ziel für dieses Projekt ist. Die Zielgruppe ist aber sicher da, da viele auf den Access Point setzen und um die CCU einen Bogen machen.

**Comment by thkl** [comment]
Das geht schon, aber ich werde das so nicht bauen ;) Das setzt Zeit und entsprechende Testhardware voraus.

Zum Thema WebUI der CCU; Das muss nur mal jemand machen. Aber da sind wir wieder bei a) Zeit und b) der Hardware, denn dafür brauchst du wirklich jedes HM(IP) Gerät, was EQ3 für CCUs anbietet.

**Comment by mike4president** [comment]
Ok, danke für die Rückmeldung.

Das mit dem WebUI würde ich dich eher von eQ3 erwarten , die ihr Einkommen damit bestreiten und nicht von fleißigen ehrenamtlichen Entwicklern, die damit fast kein Geld verdienen.
