### ISSUE TITLE
Config Freeze

### ISSUE THREAD

**Issue by stefanfejfar** [thkl/hap-homematic#142]
Beim Anlegen von Instanzen friert die Applikation ein.
Nach einem Addon-Neustart über die CCU alle bereits hingefügten Geräte und Instanzen noch vorhanden.
Neue Instanzen können weiterhin erstellt werden, die Geräteliste bleibt beim Neuanlegen allerdings leer.
Gleiches gilt für Variablen, Programme und besondere Geräte - hier ist keine nachträgliche Änderung oder Ergänzung mehr möglich.
In der Home-App können bereits deployte Geräte auch verwendet werden, der Status aktualisiert sich allerdings nicht.
Neustart des Dienstes oder CCU bringen leider keine Besserung.
Beim Durchforsten des Logs ist mir nichts konkretes aufgefallen :-(
Help needed!

Vielen Dank! Stefan

> 4 Kerne ARMv7 Processor rev 1 (v7l)
1136.42 MB freier Speicher

>CCU Laufzeit 2 Stunden
HAP Laufzeit 11 Minuten

>Version 0.0.48

**Comment by ChrWi** [comment]
@thkl „ Gleiches gilt für Variablen, Programme und besondere Geräte - hier ist keine nachträgliche Änderung oder Ergänzung mehr möglich.“ deckt sich mit dem Verhalten bei mir.
Manuelle Änderung der config.json geht aber.

**Comment by thkl** [comment]
Gehen die Config Dialoge noch auf oder passiert da nichts ?

Gibt's in der Browser Console irgendwelche Fehlermeldungen ?

**Comment by ChrWi** [comment]
Bei mir sieht‘s so aus: Ausgegraute Suche, keine Listendarstellung. Browser Console muss ich später nachsehen


[iOS]

**Comment by xz-wq** [comment]
Ich habe genau das gleiche Problem nach dem Update

**Comment by thkl** [comment]
Wie gesagt, mal bitte in der Browserconsole nach Fehlermeldungen schauen.

**Comment by thkl** [comment]
Was evtl. auch hilft  Cache leeren, es haben sich einige Sachen in den client Javascripts geändert. 
Ggf müsste ich dem Webserver mal beibringen immer zu behaupten die Files wären neu.

**Comment by stefanfejfar** [comment]
> Bei mir sieht‘s so aus: Ausgegraute Suche, keine Listendarstellung. Browser Console muss ich später nachsehen [iOS]

Das entspricht exakt auch meinem Fehlerbild.
Die Option CCU Cache leeren hatte ich probiert, ebenso den Browser Cache mittels Graceful Reload geleert - kein Erfolg.

**Comment by thkl** [comment]
Und was sagt die Browserconsole ? Da müssten irgendwelche Errors aufschlagen.

**Comment by ChrWi** [comment]
Einziger Fehler ist "[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (style.css.map, line 0)"

**Comment by stefanfejfar** [comment]
> Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für http://xx.xx.xx.xx:9874/css/style.css.map konnte nicht geladen werden: HTTP Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by thkl** [comment]
hmm das ist echt nicht viel und der Fehler ist auch völlig egal.

**Comment by stefanfejfar** [comment]
> hmm das ist echt nicht viel und der Fehler ist auch völlig egal.

Kann ich dir sonst irgendwelche Logs zur Verfügung stellen, die bei der Fehlersuche helfen?

**Comment by thkl** [comment]
Ein Archiv des Config Verzeichnisses (/etc/config/addons/hap-homematic) per Mail wäre gut. Dann könnte ich das mal im Simulator ausprobieren.

**Comment by xz-wq** [comment]
@thkl Ich habe dir eine Mail mit meiner config + screenshot von der Konsole geschickt.

**Comment by thkl** [comment]
Ja, ich sehe zwar wo das Problem ist, aber mit der Kopie der Config tritt das bei mir nicht auf ...

**Comment by xz-wq** [comment]
Ich habe mal zum Test auf meine CCU3 jetzt Rasberrymatic installiert und die config reingeladen, habe aber weiterhin das gleiche Problem. Soll ich am besten die das Plugin neu installieren und alles neu konfigurieren?

**Comment by thkl** [comment]
ok auf einer simulierten CCU3 kann ich das nachvollziehen. Mit den Änderungen aus dem Commit https://github.com/thkl/hap-homematic/commit/354b1e7b2abbcce0cbd7311b283fa7527c4ca4fc tritt das nicht mehr auf.

**Comment by xz-wq** [comment]
Ah perfekt, ich teste es mal Morgen bei mir.

**Comment by xz-wq** [comment]
Okay, bei mir funktionierts jetzt ebenfalls. Danke!

**Comment by thkl** [comment]
Sehr schön.

**Comment by stefanfejfar** [comment]
Wie kann ich es bei mir testen? Den Commit manuell in die bearbeitete Datei legen und den Service neustarten?

**Comment by xz-wq** [comment]
Ich hab die Server.js runtergeladen und mit meiner überschrieben. Danach musst nur noch das Plugin neu starten dann sollte es gehen.

**Comment by marle77** [comment]
Moin zusammen, unter welchem Pfad finde ich die Server.js? Danke und Grüße.

**Comment by thkl** [comment]
Prima dann klick ich die Woche noch eine neues Release

**Comment by dkrizic** [comment]
Ich konnte bei mir keine Garage hinzufügen, auch nach dem Update 0.0.48 nicht. Was letztendlich geholfen hat, war es die config.json aufzuräumen:

- Alle special Devices löschen
- Alle Referenzen auf Spezial Devices entfernen, wobei hier einige doppelte drin waren.

Danach Neustart und ich konnte meine Garage hinzufügen und die funktioniert absolut problemlos!

**Comment by thkl** [comment]
Ja, durch den Fehler beim Laden der Garage wurden die bei jedem Speicherversuch neu referenziert.
Das ist noch ein Problem im Config Server, was aber nur durch den Ladefehler auftreten konnte.
Aber ich mach da mal noch eine Sicherheitsabfrage rein.
