### ISSUE TITLE
Garage: "Mandatory fields are missing"

### ISSUE THREAD

**Issue by dkrizic** [thkl/hap-homematic#143]
Ich kann keine (neue) Garage anlegen, es kommt stets die Meldung "Mandatory fields are missing":

![image](https://user-images.githubusercontent.com/1181349/87886921-0a137400-ca21-11ea-97d4-e302e91063a7.png)

auch wenn ich alle Felder ausfülle.

**Comment by thkl** [comment]
Wurden die Datenpunkte per Select Button ermittelt ? Wenn ja mal den letzten Buchstaben von State löschen und wieder hinschreiben.  Ich hab da so ne Vermutung ....

**Comment by dkrizic** [comment]
Ja, die Datenpunkte habe ich ausgewählt, der Teil klappt übrigens super. Ich habe alle Werte nochmal mit sich selbst überschreiben bzw. das letzte Zeichen überschrieben, aber weiterhin das gleiche Problem.

**Comment by thkl** [comment]
Ok ich schau nachher mal woran das liegen könnte. Eigentlich sind nur die markierten Feld Pflichtfelder

**Comment by thkl** [comment]
Ok Problem war/ist das beim Speichern des Datenpunktes aus dem Selector Dialog kein Change Event ausgelöst wurde, was zum speichern des Eintrages in den Settings führt

Workaround bis zum Release:
Im Beispiel oben bei STATE das E löschen ; Feld verlassen, E wieder rein ; Feld wieder verlassen 
Dann wird es richtig gespeichert. 

(oder manuell die eine Zeile in ui.js ändern )

**Comment by dkrizic** [comment]
Ok, der Workaround funktioniert, aber die Garage wird nicht angelegt, die Liste bleibt leer.
