### ISSUE TITLE
Variable aktualisieren

### ISSUE THREAD

**Issue by d-lindner** [thkl/hap-homematic#144]
Habe eine Systemvariable vom Typ Logikwert in der CCU, welche als "HomeMaticVariableAccessory" an die Home-App weitergegeben wird. Beim betätigen des "Schalters" in der Home-App aktualisiert dieser den Wert in der CCU sowie auch seinen status in der Home-App.

Ändere ich die Variable der CCU allerdings mit einen anderen Gerät (in meinen Fall Taster), so aktualisiert sich der Wert der Variablen zwar in der CCU, diese Aktualisierung wir allerdings nicht weiter an die Home-App geschickt, so dass ein falscher Status zustande kommt.

Beim Beenden der Home-App über den Taskmanager und ein erneutes öffnen behebt den Fehler und zeigt den Status richtig an.

4 Kerne ARMv7 Processor rev 4 (v7l)
629.31 MB freier Speicher
CCU Laufzeit 20 Tage
HAP Laufzeit 14 Stunden
Version 0.0.48

Grüße Daniel.
P.s. Ein super gemachtes Plugin, großes Lob meinerseits.

**Comment by thkl** [comment]
Hast Du für die Variablenänderung den Trigger eingestellt ? Mal hier in den Issues nach Variable und Trigger suchen.  Das hatten wir schon öfters.

**Comment by d-lindner** [comment]
Danke für die schnelle Antwort, jetzt läuft es wie gewünscht :-)
