### ISSUE TITLE
devices are not addable anymore on Raspberrymatic

### ISSUE THREAD

**Issue by marle77** [thkl/hap-homematic#145]
Hello, I use the newest version 0.0.48. I can't add devices, variables, programs anymore. They are not displayed if I use new button. I deinstalled and installed again. Evrything works short time, after a period of time same issue. regards, Markus

**Comment by ChrWi** [comment]
Sounds like #142 
Can you share errors in browser log?

**Comment by thkl** [comment]
should work again in .49
Update is possible via the hap-homematic wbui.
