### ISSUE TITLE
GarageDoorAccessory - Adresse des Schließen Sensors zeigt keine Datenpunkte an

### ISSUE THREAD

**Issue by xz-wq** [thkl/hap-homematic#146]
Guten Tag,

ich habe diverse Homematic IP Wired Aktoren und wollte jetzt mein Garagentor ebenfalls ins Homekit hinzufügen, leider werden bei mir keine Datenpunkte angezeigt.

![image](https://user-images.githubusercontent.com/60407231/88478783-509a2e80-cf4b-11ea-90dc-ef3fed9c6fbd.png)

Hängt das ggf. damit zusammen, das Homematic IP Wired Geräte nicht unterstützt werden? 

Außerdem wird bei diesen Sensor true/false zurückgegeben, in der Anleitung zum homebridge-homematic/Garagentor möchte homebridge 0/1.

https://github.com/thkl/homebridge-homematic/wiki/Garagentor

![image](https://user-images.githubusercontent.com/60407231/88478798-6871b280-cf4b-11ea-8b46-14e442ab3286.png)

![image](https://user-images.githubusercontent.com/60407231/88478809-73c4de00-cf4b-11ea-87b4-447bfa0d5305.png)

![image](https://user-images.githubusercontent.com/60407231/88478811-76273800-cf4b-11ea-8844-1273513a13c9.png)

**Comment by hillinator** [comment]
Ich habe den Datenpunkt einfach direkt eingetragen, ohne über die Auswahlliste zu gehen. Sollte auch funktionieren. Ich gehe davon aus, dass der Filter für die Auswahl noch im Code erweitert werden müsste.

**Comment by thkl** [comment]
Welche Geräte sind das denn, die da fehlen ? Derzeit werden als Sensoren Geräte angezeigt deren Channels in diese Liste passen:

['CONTACT', 'SHUTTER_CONTACT', 'TILT_SENSOR', 'ACCELERATION_TRANSCEIVER', 'SHUTTER_CONTACT_TRANSCEIVER']

und als Aktoren:

 ['SWITCH', 'SWITCH_VIRTUAL_RECEIVER']

Diese Listen lassen sich natürlich erweitern.

**Comment by xz-wq** [comment]
Wo kann ich die Bezeichnung sehen?

**Comment by thkl** [comment]
Im Zweifel in der EQ3 Doku zu den Geräten wenn man nach den Typenbezeichnungen sucht.

**Comment by hillinator** [comment]
Ich habe einen HmIP-FCI1 im Einsatz. Dieser hat einen Magnetkontakt angeschlossen für das Gartentor.
Das sollte dann MULTI_MODE_INPUT_TRANSMITTER sein

**Comment by hillinator** [comment]
Wenn ich das richtig sehe wäre HMIPW_DRI32 der gleiche Channel type.

**Comment by thkl** [comment]
ok wenn das jemand probieren möchte, siehe obiger commit

**Comment by hillinator** [comment]
ja könnte ich gerne testen. wie bekommen ich am schnellsten die neue json ausgetauscht?

**Comment by hillinator** [comment]
OK cool. der channel type wird jetzt auch erkannt. habe das hotfix mal manuell nachgezogen und getestet. wäre ja mal bald zeit für n neues release!?

**Comment by hillinator** [comment]
Mir ist noch aufgefallen, dass bei Auswahl des Datenpunktes der Wert direkt geschrieben wird. Bedeutet also, dass auch wenn ich den Dialog abbreche oder einfach nur schließe, die Daten überschrieben werden. Wäre Super wenn erst beim submit die Daten in die config geschrieben werden ;)

**Comment by thkl** [comment]
ja, das ist mir auch aufgefallen. Die Werte werden aber nur in dem SettingsCache im Browser gespeichert und nicht zum Backend geschickt. Ich müsste bei allen Edit Dialogen die Settings des devices speichern und beim Abbruch die wieder zurückschreiben.
