### ISSUE TITLE
Leistungsanzeige HM-ES-PMSw1-DR in Home App

### ISSUE THREAD

**Issue by boersenman** [thkl/hap-homematic#147]
Ich bekomme über das Homematic Gerät HM-ES-PMSw1-DR keine Leistungsdaten in der Apple Home App angezeigt.
Der aktuelle Wert in Watt und die Tagesleistung in kWh wäre für mich interessant.
Ist dies nicht vorgesehen oder mache ich etwas falsch?
--

**Comment by thkl** [comment]
Das funktioniert nur in Eve.  Apple Home kennt keine Energieverbrauchsgeräte.
