### ISSUE TITLE
Werte aus Variable in der Home App anzeigen

### ISSUE THREAD

**Issue by boersenman** [thkl/hap-homematic#148]
Ich habe zwei Werte die jeweils in eine Variable vom Typ Zahl (kWh) und Logikwert (Manuell/Automatik) geschrieben werden.
Wie bekomme ich die Werte in der Home App dargestellt.
Alle was ich versucht habe schlägt fehl. Ist das Anzeigen von Variablen-Inhalten nicht vorgesehen oder mache ich etwas falsch?

**Comment by thkl** [comment]
Die Energieanzeige geht über einen Variablenservice.  Funktionieren wird das aber nur in Eve, das Apples Home keine dieser Geräte kennt.
