### ISSUE TITLE
Homematic Funksender

### ISSUE THREAD

**Issue by Blacerrr** [thkl/hap-homematic#149]
Servus thkl,

sämtliche Homematic Funksender (wie z.B. der HM-PB-2-FM) werden in Homematic und dadurch auch in Homekit über HAP Homematic leider als mehrere einzelne Geräte angezeigt 

(![Homematic Ansicht](https://user-images.githubusercontent.com/13471958/88488159-c2926800-cf8b-11ea-9791-b11fa7dda604.png) ... man denke an die 6-fach Taster... oh Gott...). 

Für Homekit wäre es optisch viel schöner, wenn man wie bei den Hue oder Xiaomi/Aqara Fernbedienungen mehrere Tasten pro Homekit Gerät haben könnte 

(![Beispiel Hue Fernbedienung](https://user-images.githubusercontent.com/13471958/88488336-e1452e80-cf8c-11ea-8a65-0305564453e7.png)). 

Leider besteht im Home (Stand iOS 14 Beta 3) nicht die Möglichkeiten Taster, so wie es mit Lampen möglich ist, zu gruppieren.

Wäre das realisierbar?

Viele Grüße 

Blacer

**Comment by thkl** [comment]
Jap, das ist genau die Art und Weise wie HAP-Homematic arbeitet. Es werden in den meissten Fällen (außer bei Geräten wo es absolut keinen Sinn macht [Wetterstation zb]) die Kanäle einzeln betrachtet. Das heisst ein 2 Fach Switch Aktor wird in Homekit zu zwei einzelnen Geräten. 

Dummerweise passiert das natürlich für die Taster auch.

Aber Du hast schon Recht, im Prinzip wäre es nett, wenn man Taster zusammenfassen könnte. Bisher war das ja mit Gruppierungen in Home möglich. Wenn das jetzt nicht mehr geht, könnte ich ein Special Device bauen, was X Tasten erzeugen kann und wo man sich dann die jeweiligen Channels zusammenstellen kann.

**Comment by Blacerrr** [comment]
Gruppieren klappt leider nur bei Schaltern nicht. Sowohl in iOS 13 und in der iOS 14 Beta nicht. Ich bin mir auch nicht sicher, ob die sowas überhaupt auf dem Schirm haben werden. 

So ein universales special device wäre die Rettung. Dann wäre es sogar möglich, falls vorhanden, mehrere Funksender in einem Zimmer zu gruppieren und es noch schöner darzustellen.

**Comment by thkl** [comment]
Die Taster kann man doch von HomeKit aus eh nicht betätigen oder ? Das sind doch nur "Empfänger" für Events die dann Regeln auslösen.

**Comment by Blacerrr** [comment]
Genau, korrekt. Man wählt nur die zu steuernden Geräte oder Szenen aus.

**Comment by thkl** [comment]
ok, dann macht es wirklich Sinn, alle Taster einer Instanz in ein Gerät zusammenzusetzen.
Ich schau mal, wie ich das am geschicktesten abbilden kann.

**Comment by thkl** [comment]
Preview:

![image](https://user-images.githubusercontent.com/884355/90061171-0e604380-dce6-11ea-876f-7690bc5b7e62.png)

![IMG_4303](https://user-images.githubusercontent.com/884355/90061223-220baa00-dce6-11ea-9e5e-456500ef1e4e.PNG)


Es fehlt noch die Settingslogik zum hinzufügen einer neuen Channelzeile + Löschen einer alten ...

**Comment by Blacerrr** [comment]
Sehr geil! Noch besser als ich es mir vorgestellt hatte.
