### ISSUE TITLE
Fehler: Der Wassersensor HM-Sec-WDS-2 funktoniert nicht

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#15]
Hallo Thomas

Wenn ich den Wassersensor HM-Sec-WDS-2 einer Bridge hinzufüge, wird er zwar in HK angezeigt, aber alle Geräte der Bridge (inkl. Wassersensor) sind dann nichr mehr erreichbar.

lg Richard

**Comment by thkl** [comment]
ok meine unit test dafür läuft durch, daher müsstest du mal bitte schauen ob Du in Deinem config Ordner ein crashlog hast .. die  werden angelegt wenn das Plugin stirbt ... endet auf .crash und ist eine Textdatei ... sonst mal in /var/log/hap-homematic.log schauen ob da was steht 1

**Comment by roe1974** [comment]
hmmmmm ... kein crash file ... nix auffäliges im log.....
aber alle geräte im raum sind "nicht erreichbar" sobald ich den wassermelder hinzufüge.....
der steht in der CCU auf protokolliert ... macht das was aus ?

log auszug:

[Mon Apr 27 2020 17:42:31 GMT+0200 (CEST)] info - [HAP Server] [Server] serivce used for Wassermelder WC is HomeMaticLeakSensorAccessory
[Mon Apr 27 2020 17:42:31 GMT+0200 (CEST)] info - [HAP Server] [Server] add Wassermelder WC to bridge instance 27f47922-f44c-4e57-994f-d04404b9488b

komisch .....
nehme ich ihn raus ... gehen die anderen wieder ....

**Comment by roe1974** [comment]
hast du den "live" bei dir oder nachgebaut ?

**Comment by thkl** [comment]
Ok, ich glaube, ich hab es gefunden. Ich ergänze einige Geräte automatisch um eine Fault Characteristics das kennt aber das HM Gerät nicht. Wenn ich die rausnehme gehts ...

**Comment by thkl** [comment]
> hast du den "live" bei dir oder nachgebaut ?

Simuliert  ;)

**Comment by roe1974** [comment]
👍

**Comment by roe1974** [comment]
wassersensor ist nicht erreichbar … aber dafür gehen die anderen geräte im raum normal
kommt immer "aktualisiere" ... "keine antowrt"
ahhhhhh .... jetzt sin dale weg im raum

**Comment by roe1974** [comment]
funktioniert !
