### ISSUE TITLE
HmIP-SMI55 Taster ohne Funktion

### ISSUE THREAD

**Issue by timwegenerDE** [thkl/hap-homematic#150]
Hallo,

ich habe die Tasten des Bewegungsmelders HmIP-SMI55 nach HomeKit veröffentlichen wollen. Das funktioniert auch, nur kommt der Tastendruck (weder auf Kanal 1 noch 2) nicht in HomeKit an. Mache ich was falsch?

![D3284539-01A9-4396-B93F-6C68F9F6A0EB](https://user-images.githubusercontent.com/56134910/89545093-32fa7e00-d803-11ea-9208-5da7d7dba6f3.jpeg)

**Comment by thkl** [comment]
KeyAccesories erzeugen einen sog. ProgrammableSwitchEvent. Das ist ein Trigger in HomeKit für den dann bei Short und/oder Longpress eine Scene ausgeführt werden kann. 
(double press wird aus homeMatic nicht unterstützt daher funktioniert das nicht)


Diese Szene muss einmalig zugewiesen sein.  In Eve schaut das zb so aus:

![image](https://user-images.githubusercontent.com/884355/89680481-53096a80-d8f3-11ea-9840-ffe99d1bcaa9.png)

Bei Tastendruck wird dann die Szene durch HomeKit ausgeführt. 


Und das funktioniert bei mir zb bestens.

**Comment by timwegenerDE** [comment]
Hi,

da ich weder den SMI55 noch den hmip BSL als Schalter zum Laufen bekomme, liegt es vllt. doch an mir. Keine Aktion die ich hinterlege (Kurz, Lang, Doppelt) wird ausgelöst. Aktion testen hingegen funktioniert. Kanal 1 und 2 sind doch korrekt oder?
![3DC0BC17-830A-469B-ADCD-1655DFE36E61](https://user-images.githubusercontent.com/56134910/89706466-3eb28580-d966-11ea-8eda-8beb06422047.jpeg)
![5F6C1987-BB2D-4760-9410-F64F68184743](https://user-images.githubusercontent.com/56134910/89706470-43773980-d966-11ea-84d8-edc52a5a2ed7.jpeg)

**Comment by thkl** [comment]
in Deinem Log steht aber kein PRESS_SHORT Event. Es werden zwar alle möglichen Events auf Channel 0 (das ist der für Statusinfos) gesendet, aber auf den Tastenchannels passiert nichts.

Als Beispiel hier : BidCos-RF.MEQ0669321:1

Der Service wird initialisiert:
```
[Tue Aug 11 2020 21:26:44 GMT+0200 (CEST)] [HAP Server] [Server] service used for Taster Test Up is HomeMaticKeyAccessory
[Tue Aug 11 2020 21:26:44 GMT+0200 (CEST)] [HAP Server] [HomeMaticKeyAccessory] MEQ0669321 publishing services for Taster Test Up 
[Tue Aug 11 2020 21:26:44 GMT+0200 (CEST)] [HAP Server] [HomeMaticKeyAccessory] MEQ0669321 add Service
```

Das Log beim Start zeigt dann das der Service den PRESS_SHORT Event registriert:

```
[Tue Aug 11 2020 21:26:44 GMT+0200 (CEST)] [HAP Server] [HomeMaticKeyAccessory] MEQ0669321 buildAddress PRESS_SHORT
[Tue Aug 11 2020 21:26:44 GMT+0200 (CEST)] [HAP Server] [HomeMaticKeyAccessory] MEQ0669321 seems to be a single datapoint
[Tue Aug 11 2020 21:26:44 GMT+0200 (CEST)] [HAP Server] [CCU] register address BidCos-RF.MEQ0669321:1.PRESS_SHORT for events
```

Das Log müsste dann ungefähr so aussehen bei Tastendruck:


```
[Tue Aug 11 2020 21:30:07 GMT+0200 (CEST)] [HAP Server] [RPC] event for BidCos-RF.MEQ0669321:1.PRESS_SHORT with value true
[Tue Aug 11 2020 21:30:07 GMT+0200 (CEST)] [HAP Server] [CCU] event BidCos-RF.MEQ0669321:1.PRESS_SHORT will be handled by 1 registered callback
```

**Comment by timwegenerDE** [comment]
Das heisst entweder habe ich einen Bug gefunden oder wir haben ein Layer 8 Problem weil ich nicht richtig auf den Knopf gedrückt habe? :)

**Comment by thkl** [comment]
Das weiss ich noch nicht :o) Kannst Du mal bitte im WebInterface unter Internes / Hilfe  das Devicefile für diesen HMIP BSL erzeugen und hier anhängen. Dann kann ich das zumindest mal trocken testen.

**Comment by timwegenerDE** [comment]
Den BSL hab ich aktuell wieder rausgeschmissen; Hier aber die Config vom SMI55. 

[HmIP-SMI55.json.txt](https://github.com/thkl/hap-homematic/files/5059184/HmIP-SMI55.json.txt)

Ich reiche die nächsten Tage auch gerne noch die andere Config nach.

**Comment by thkl** [comment]
Hmmm also ich hab das mal durch den Trockentest laufen lassen, das funktioniert alles.
Könntest Du mal bitte hap im debugmode starten und wirklich schauen ob die oben (https://github.com/thkl/hap-homematic/issues/150#issuecomment-672219164) aufgelisteten Events auftauchen

**Comment by thkl** [comment]
Ok, dann hier weiter:

Folgender Workaround:
=================

Taster haben bei der CCU eine kleine Eigenheit. Der Taster muss für die Events an der CCU "als Direkt Link Partner angelernt werden". Ansonsten bekommt die CCU den Key Event nicht mit. Das kann man ganz einfach durch ein Dummy Programm in der CCU machen. Also einfach den Taster als Auslöser für ein Programm nutzen. Das Programm selber muss nichts machen, aber so wird der  KEY Event zuverlässig auf die Schnittstelle gesendet.

**Comment by dkrizic** [comment]
Ich klinke mich mal hier ein. Ich habe das gleiche Problem mit einem ähnlichen Gerät. Die Config sieht so aus:

```
{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HM-PB-2-WM55",
      "address": "8467757571ABCD",
      "type": "HM-PB-2-WM55",
      "channels": [
        {
          "id": 1001,
          "name": "8467757571ABCD:1",
          "intf": 0,
          "address": "8467757571ABCD:1",
          "type": "KEY",
          "access": 255
        },
        {
          "id": 1002,
          "name": "8467757571ABCD:2",
          "intf": 0,
          "address": "8467757571ABCD:2",
          "type": "KEY",
          "access": 255
        }
      ]
    }
  ]
}
```

**Comment by dkrizic** [comment]
> Ok, dann hier weiter:
> 
> # Folgender Workaround:
> Taster haben bei der CCU eine kleine Eigenheit. Der Taster muss für die Events an der CCU "als Direkt Link Partner angelernt werden". Ansonsten bekommt die CCU den Key Event nicht mit. Das kann man ganz einfach durch ein Dummy Programm in der CCU machen. Also einfach den Taster als Auslöser für ein Programm nutzen. Das Programm selber muss nichts machen, aber so wird der KEY Event zuverlässig auf die Schnittstelle gesendet.
> 
> Das Problem ist mir bei der HVL Javascript Engine aufgefallen. Aber es gibt eine Möglichkeit das auch ohne "Dummyprogramm" zu machen, dazu muss ich aber noch in HAP nacharbeiten.

Das habe ich auch gerade herausgefunden: Ich setze eine boolsche Variable auf true/false mit zwei Programmen. Als ich die Programme erstellt habe wurden Config-Parameter an den Schalter gesendet. Ab jetzt blinkt er auch orange/grün, wenn ich ihn betätige. Ohne die Programme nur Orange. Jetzt funktioniert bei mir alles! Danke sehr.

**Comment by thkl** [comment]
Ja, das Problem ist mir wieder aufgefallen hier. Alle von mir verwendeten Taster in HK leben schon in diesem Dummy Programm. Das braucht es nicht wirklich, es gibt ein reportUsage Command für die Schnittstelle. Das Programm selber löst beim Speichern ein reportUsage für die auslösenden Datenpunkte aus. Das bau ich einfach für HAP nach und dann spart man sich den Dummy

**Comment by pinogrigio** [comment]
Hallo,

ich habe diesen Thread gefunden, da er zu meinem aktuellen Problem am besten passt. Ich habe mehrere Homematic Taster über HAP in HomeKit veröffentlicht. Wenn ich über einen Tastendruck ein anderes HomeKit-Gerät einschalten möchte, dann funktioniert es nicht (mit allen Homematic-Tastern im Haus). 

Ich habe auf der CCU eine Systemvariable angelegt, die geändert wird, wenn ein Taster betätigt wird und alle ButtonPress-Events werden von der CCU auch wahrgenommen. Lediglich der Eventtrigger in HomeKit wird nicht angestoßen und ich kann mir nicht erklären wieso. 

Der oben beschriebene Workarround scheint bei meinem Problem nicht zu helfen. 

<img width="1123" alt="Bildschirmfoto 2021-05-15 um 09 33 30" src="https://user-images.githubusercontent.com/84119880/118352246-ab475a00-b560-11eb-8882-d44f9912f5fd.png">

Das HAP-Log zeigt den Event an

<img width="524" alt="Bildschirmfoto 2021-05-15 um 09 34 28" src="https://user-images.githubusercontent.com/84119880/118352265-c4e8a180-b560-11eb-8d37-3baea879fdb8.png">

Der Trigger in HomeKit ist folgendermaßen hinterlegt

**Comment by thkl** [comment]
Ok der Event kommt augenscheinlich bei Hap an. 

Das ist ein HMIp Taster ?

**Comment by pinogrigio** [comment]
Ja, ein HmIP-BSL.

**Comment by thkl** [comment]
Ok schau ich mal nach

**Comment by pinogrigio** [comment]
Ich konnte das Problem endlich finden - der Fehler lag bei HomeKit und nicht bei HAP! Sorry und Danke!!

**Comment by thkl** [comment]
Oh gut .. ich hab noch eine kleine Änderung an HAP gemacht da ggf wiederkehrende Events sonst in Zukunft nicht funktionieren würden.

**Comment by WeisserWolf611** [comment]
Ich muss das hier leider noch einmal herauskamen -.-
Ich nutze in der CCU3 eine Schlüsselfernbedienung HmIP-KRCK. Hier läuft aktuell ein Dummytaster, welches durch alle 4 Tasten sowohl kurz als auch lang ausgelöst wird. Dieses dient lediglich der Übermittlung der Tastendrücke an den ioBroker.
Eine Direktverknüpfung gibt es nicht.

Ich habe nun über HAP die Taste 1 mit dem Service "HomeMaticPushTheButtonAccessory" in Homekit integriert. Diese wird auch angezeigt, aber leider löst ein Druck auf dem iPhone keine Aktion aus. Verstehe ich den Sinn des Services nicht?
Ist er nicht dafür gedacht den Taster zu "spiegeln"? Funktioniert bei anderen Usern hier auch, sogar ohne Dummytaster-Programm.
Danke schonmal im Voraus.
