### ISSUE TITLE
Garagentor - Variable als Sensor möglich?

### ISSUE THREAD

**Issue by isi07** [thkl/hap-homematic#151]
Hallo
ich kann bei meinem Hoftor den Torzustand an der Steuerung abgreifen.
Das habe ich über einen HmIP-FCI6 realisiert.
Ich greife zwei Punkte ab, die kombiniert den Zustand des Tore ergeben
                                    Kanal 1          Kanal 2
Tor offen                     true               true
Tor geschlossen          false              false
Tor öffnend                 false              true
Tor schliessend           true               false

Damit habe ich aber keinen eindeutigen Offen oder Geschlossen Sensor.
Ich könnte die Zustände in einer oder auch zwei Binärvariablen auswerten, und diese dann als Offen und Geschlossen Sensoren verwenden.
Allerdings weiß ich nicht, wie oder ob überhaupt eine Variable als Datenpunkt für das Garagentor als Sensor angegeben werden kann.

Kann mir dazu jemand einen Tip geben?
Müsste eine solche Variable dann in dem Variablen-Trigger für die normalen Variablen mit aufgenommen werden?

Vielen Dank
Christian

**Comment by thkl** [comment]
Das ist angedacht, in der Beschreibung schon angegeben, aber leider noch nicht eingebaut.

**Comment by berndbarker** [comment]
Hey, 
erstmal vielen Dank für all die Arbeit, die Du investiert hast! 

Ich wäre auch sehr interessiert an der Möglichkeit eine Variable als Datenpunkt anstelle eines Sensors zu nutzen.
Würde mich freuen, wenn Du das noch implementieren würdest.

Danke !!!

**Comment by blackbasket** [comment]
@isi07 besteht das Anliegen noch? Sonst bitte das Ticket schließen. Danke :)

**Comment by isi07** [comment]
Wird nicht mehr benötigt. Mach hier zu. Danke.
