### ISSUE TITLE
CuxD-Gerät (XiaoMi Aqara Tür- und Fensterkontakt) als Kontaktsensor in HomeKit

### ISSUE THREAD

**Issue by Milo-PRT** [thkl/hap-homematic#152]
Moin, habe mir einen XiaoMi Aqara Tür- und Fensterkontakt via CuxD (als Universal-Wrapper-Device 90) eingebunden und funktioniert so weit (als Überwachung der Gefrierschranktüre). Beim Einbinden dieses Devices in HomeKit ist leider nur die HomeMaticSwitchAccessory, die HomeMaticProgammableSwitchAccessory und die HomeMaticValveAccessory auswählbar. Besteht die Möglichkeit, hier auch noch den Punkt HomeMaticContactSensorAccessory auswählbar zu machen? Somit könnte dann in HomeKit auch das korrekte Symbol und die anderen netten Funktionen genutzt werden.
Beste Grüsse

**Comment by thkl** [comment]
Bitte mal das Device File erzeugen. Das geht über das WebUI vom hap und dort über Interne/Hilfe.
Es wird ein anonymisiertes File mit den Datenpunkten des Gerätes erzeugt. Das bitte dann mal hier anhängen, dann kann ich mir das anschauen.

**Comment by Milo-PRT** [comment]
et Voila.... bei der Datei die Endung txt - konnte sie sonst nicht hochladen.
[_device.json.txt](https://github.com/thkl/hap-homematic/files/5060761/_device.json.txt)
Gruss

**Comment by thkl** [comment]
Hmm wenn die Datei nur 2 Byte hat {} als Inhalt dann wurde die Seriennummer nicht gefunden.

**Comment by Milo-PRT** [comment]
nach einigen Versuchen hats geklappt.
beste Grüsse
[HM-Sec-SC.json.txt](https://github.com/thkl/hap-homematic/files/5072685/HM-Sec-SC.json.txt)

**Comment by thkl** [comment]
Das File sagt Channel 1 ist ein Switch (daher die in deinem Posting oben angegebenen Switch Dienste).
Channel 2 und 3 sind ein Typ WRAPPER ??? Hier muss ich mir also mal auf dem Testsystem CuxD installieren und schauen was der WRAPPER so macht ...

**Comment by thkl** [comment]
OK die Doku sagt WRAPPER ist ein Universales Device .... und der Datenpunkt kann festgelegt werden. Ich denke mal das ist dann STATE für einen Türsensor.

Dann ist das mit der Änderung einer Codezeile in HomeMaticContactSensorAccessory machbar siehe commit

**Comment by Milo-PRT** [comment]
danke für die Info - hab das ganze Packet nochmals installiert, Restart gemacht und kontrolliert Obst geht. Leider nein...

Hab dir mal einen Screenshot angefügt, ggf. hilft dir dies weiter.
Danke und Gruss
![HM-CuxD-Wrapper](https://user-images.githubusercontent.com/63641604/90263719-569b7500-de50-11ea-9dfa-d8bad65766c2.png)

**Comment by thkl** [comment]
nooooo ! Im Release ist das natürlich noch nicht drin. Entweder du änderst das File manuell oder wartest auf das nächste Update
