### ISSUE TITLE
Gerät welches eine URL aufrufen kann, möglich?

### ISSUE THREAD

**Issue by LevelOne2k** [thkl/hap-homematic#153]
Hallo @thkl wäre es möglich, ein Gerät zu erstellen, welches eine URL aufrufen kann? Z.B. als Stecker-Gerät, in HAP bei der Konfiguration dieses Gerätes gibt man dann die aufzurufende URL ein, wenn man dann in der Home App das Gerät einschaltet, wird die URL aufgerufen. Hierbei handelt es sich nicht um eine übliche “Web-URL” sondern um eine URL die etwas steuert, z.B. den Sat-Receiver einschaltet oder das Programm umschaltet.

**Comment by thkl** [comment]
Könnte man das nicht über ein CCU Programm lösen ? Programme können ja von HomeKit ausgelöst werden.

**Comment by LevelOne2k** [comment]
Ja, aber funktioniert irgendwie unzuverlässig und so wäre es auch abhängig von der CCU und direkt in HAP nicht. Würde es auch allgemein besser und einfacher finden wenn es in HAL möglich ist, wäre super con dir.

**Comment by thkl** [comment]
Ja aber Hap ist doch auch von der CCU abhängig.  Läuft ja schließlich drauf 😁. 

Naja ich behalte das mal im Hinterkopf.  Obwohl damit das ursprüngliche Konzept ausfranst.

**Comment by LevelOne2k** [comment]
Stimmt hast recht, aber es wäre trotzdem einfacher hand zu haben. Würde mich freuen!

**Comment by dkrizic** [comment]
Es gibt Homebridge und hunderte von Plugins, die genau das können. Such Dir da was schönes aus.

**Comment by LevelOne2k** [comment]
Und was hat das mit HAP zutun? Genau nix!
