### ISSUE TITLE
i386 Support?

### ISSUE THREAD

**Issue by sotatech** [thkl/hap-homematic#154]
I'm moving my RaspberryMatic installation to Proxmox on an Intel NUC and I don't see any mention of support for this platform. Will it work or do you have any plans to support this?

Thanks!

**Comment by thkl** [comment]
one of my test systems is a raspberrymatic running on MacOS Virtual Box .. so i should work ;)

**Comment by sotatech** [comment]
Thanks Thomas, I'll try it out and report back.

Pat

**Comment by sotatech** [comment]
Ooops, I forgot to report that it works fine. Thanks!
