### ISSUE TITLE
Was bedeutet diese Meldung bei aktualisieren von HAP?

### ISSUE THREAD

**Issue by LevelOne2k** [thkl/hap-homematic#155]
![732CCCAA-3466-4E0D-8F4C-F2BAA2D22D04](https://user-images.githubusercontent.com/25386824/90312018-5b6c3180-df01-11ea-95b2-a261051a7fdb.jpeg)

**Comment by thkl** [comment]
Im Normalfall wird hier der letze Beitrag des Changelogs eingeblendet.
Das ist ein Fehler beim parsen des Logs. Für die aktuelle Version ist das folgender EIntrag:

Changelog for 0.0.49:
=====================

* fixed a bug that some installations are not able to add new devices
* fixed a bug für special devices are not added anymore
