### ISSUE TITLE
Garagentor HM-LC-Sw1-Pl-CT-R1

### ISSUE THREAD

**Issue by Luftloch80** [thkl/hap-homematic#156]
Servus. Ich bin umgestiegen vom Homematic Plugin auf dieses.  
Läuft alles super außer mein Garagentor. 
Immer wenn ich es öffne oder schließe leuchtet die Lampe am HM-LC-Sw1-Pl-CT-R1 rot und das Gerät blockiert. 
Vorher hat es problemlos funktioniert. 
Hat jemand eine Lösung?
Danke

**Comment by thkl** [comment]
Wie muss dieses Gerät angesteuert werden, damit es funktioniert ? Also ein Impuls oder Ein/Aus für Auf / Zu

**Comment by Luftloch80** [comment]
Bekommt so weit ich weiß nur einen Impuls. Es gibt nur eine Taste am Gerät die schaltet. 400ms Impuls laut Anleitung

**Comment by thkl** [comment]
ok dann mal die Message für den Open Actor auf das hier ändern:

```
{"on": true, "onTime":1}
```

**Comment by Luftloch80** [comment]
Danke läuft jetzt.

**Comment by ChrWi** [comment]
@thkl was bedeutet das "onTime:1"? ist das die Verweildauer im Zustand ein? Rein Interessehalber gefragt, da ich mein Garagentor auch mit dem HM-LC-Sw1-Pl-CT-R1 schalte, aber den Open Actor (bis zuvor im Homebridge-homematic) auf {"on": true, "off": false} stehen habe. Die Garage läuft mit hap-homematic wie ein Uhrwerk.

**Comment by thkl** [comment]
Ja onTime ist die Zeit wie lange der Aktor eingeschaltet bleiben soll.
Es gibt einen 2. Parameter der den Aktor auch noch mal zurücksetzt (das ist die Öffnen / Schließen Zeit)
Der HmIP-WCG kann aber zb damit nicht umgehen und dort hat sich die onTime (das ist die Einschaltzeit wie man sie auch direkt in HM - Programmen angeben kann) als besser herrausgestellt.

Aber wenn es beim Ursprungsposter jetzt geht, fein.

**Comment by Luftloch80** [comment]
Kann man beim Status des Sensors schließen auch 
1 und 0 nehmen?
Habe einen HM-Sec-SC-2 der nicht true und false sendet

**Comment by thkl** [comment]
Ja einfach das json in dem Feld anpassen.
