### ISSUE TITLE
HM-PB-2-WM55 als HomeMaticKeyAccessory: Keine Reaktion

### ISSUE THREAD

**Issue by dkrizic** [thkl/hap-homematic#157]
Ich habe einen HM-PB-2-WM55

![image](https://user-images.githubusercontent.com/1181349/90320832-99d71000-df44-11ea-8928-e6b64a23fd2c.png)

(Batteriebetrieben, Wippschalter, normalerweise werden HomeMatic-Geräte damit direkt gekoppelt)

Den habe ich als HomeMaticKeyAccessory eingebunden:

![image](https://user-images.githubusercontent.com/1181349/90320858-d0ad2600-df44-11ea-9fe0-9324bd81589f.png)

und er erscheint auch:

![image](https://user-images.githubusercontent.com/1181349/90320866-dc98e800-df44-11ea-91c6-b8621c96b256.png)

Allergings passiert nichts, wenn ich ihn physisch auslöse.

Hintergrund: Ich würde ihn gerne dazu nutzen ein andere HomeKit-Gerät zu schalten.

**Comment by thkl** [comment]
Die Geräte funktionieren von HomeMatic zu HomeKit .. es werden die Short oder Long Press Events vom Schalter zu HomeKit gesendet. Diesen Events kann dann eine HomeKit Action zugeordnet werden.

**Comment by timwegenerDE** [comment]
Besteht hier ggf. ein Zusammenhang? #150

**Comment by thkl** [comment]
Nachtrag: Wenn die Richtung andersrum sein soll, also aus HomeKit der Button in HomeMatic betätigt werden soll muss HomeMaticPushTheButtonAccessory als Service verwendet werden. Dann wird ein Switch erzeugt, der beim Betätigen in HomeKit den Key Event in HomeMatic auslöst und dann wieder zurückgeschalten wird.

Das liegt, da dran, das es eigentlich keine Buttons in HomeKit gibt....

**Comment by dkrizic** [comment]
> Besteht hier ggf. ein Zusammenhang? #150

Ja, scheint das gleiche Problem zu sein. Ich schau mal, was ich im Log finde.

**Comment by dkrizic** [comment]
Ich mach den mal hier zu, weil es ein duplicate zu #150 ist.
