### ISSUE TITLE
[HomeMaticSPGarageDoorAccessory] Two Sensor Mode

### ISSUE THREAD

**Issue by hillinator** [thkl/hap-homematic#158]
Hi, wenn ein optionaler Sensor für den Status Offen hinterlegt und wieder entfernt wurde, erscheint folgende Fehlermeldung:

[HAP Server] [SPGDS] Two sensor mode. Fetching value for Close Sensor HmIP-RF.0000********:1.STATE -> 0
[HAP Server] [HomeMaticSPGarageDoorAccessory] 785de944-faf3-408a-9bd8-657dccef3e53 buildAddress 
[HAP Server] [Generic] unable create HM Address from undefined Input 

Ich gehe davon aus, dass beim entfernen der Wert in der Config vielleicht nicht korrekt entfernt wird und deswegen noch davon ausgegangen wird, dass es zwei Sensoren gibt. Das würde zumindest erklären, warum er die nicht mehr vorhandene Adresse nicht mehr finden kann.

Kann ich das manuell in der config überprüfen, bzw. bereinigen?

**Comment by thkl** [comment]
Hi, 

ja das kann man in der config entfernen.
Die Config hat einen Key 785de944-faf3-408a-9bd8-657dccef3e53 (das ist die zufällige ID Deines Tordevices).
Dort gibt es einen Eintrag "address_sensor_close":"",  die Zeile wirf raus. Dann ist das für ihn wieder ein Ein/Sensor Tor.
Achtung: die config.json muss in sich wieder ein gültiges JSON Format ausweisen. Ggf vor dem Speichern bei jsonlint.com testen.

Ich prüfe nur auf "Eintrag nicht vorhanden", ich werde das mal noch auf "" erweitern.

**Comment by hillinator** [comment]
ich habe den address_sensor_open raus geworfen. Der address_sensor_close ist da required.
Vielen Dank ;)
