### ISSUE TITLE
Inkorrekte Thermostaten-Solltemperaturspanne in HomeKit

### ISSUE THREAD

**Issue by Mattis-Schulte** [thkl/hap-homematic#159]
Moin, mir ist aufgefallen, dass man in HomeKit die Solltemperatur der Thermostate zwischen 10 und 38 °C einstellen kann, die Solltemperaturspanne der Homematic Thermostate liegt aber normalerweise bei, 5 bis 30 °C. Daher kann man in HomeKit die Thermostate nicht auf unter 10 °C einstellen und somit wird auch fehlerhaft 10 °C angezeigt, falls die Solltemperatur der Thermostate auf unter 10 °C eingestellt wurde. Wenn man in HomeKit die Temperatur auf über 30 °C einstellt, schalten die Thermostate auf die höchst mögliche Temperatur. An sich ist das ganz zwar kein großes Problem, wollte trotzdem aber mal fragen, ob es möglich wäre, die korrekte Temperaturspanne in HomeKit anzuzeigen. Hoffe, ich habe das Ganze halbwegs verständlich formuliert.

**Comment by thkl** [comment]
HomeKit selber gibt für TargetTemperature die Spanne zwischen 10 und 38° vor.

Man könnte das ändern. Soweit ich weiß sind die Temperaturbereiche zwischen den HM / HMIP  Thermostaten jedoch unterschiedlich, deswegen habe ich das bisher nicht angefasst und bei HomeKit Vorgabe belassen.

**Comment by Mattis-Schulte** [comment]
Also so weit ich weiß, geht der Temperaturbereich bei HM Thermostaten von 4,5 bis 30,5 °C und bei HMIP von 5 bis 30 °C. Allerdings kann der Benutzer diesen Bereich sowohl bei HM und HMIP verändern, indem er die minimale / maximale Soll-Temperatur in den Einstellungen festlegt. Somit ist es möglich, die Temperaturspanne unsinnigerweise von 14,5 bis 15 °C einzuschränken. Aber Werksstandard ist 4,5 bis 30,5 bzw. 5 bis 30 °C.

**Comment by thkl** [comment]
Na das wird ja immer bunter. Dann müsste ich ja, um es wirklich richtig zu machen, diese Einstellungen auslesen und das HomeKit Device entsprechend dieser Settings konfigurieren. /o\

**Comment by thkl** [comment]
> Na das wird ja immer bunter. Dann müsste ich ja, um es wirklich richtig zu machen, diese Einstellungen auslesen ...

Ok, das soll nicht heissen, das das nicht geht:

```
[Tue Aug 18 2020 21:28:12 GMT+0200 (CEST)] [HAP Server] [HomeMaticThermostatAccessory] XXX Fetching setTemp boundaries from device
[Tue Aug 18 2020 21:28:12 GMT+0200 (CEST)] [HAP Server] [CCU] sendInterfaceCommand BidCos-RF getParamset
...
[Tue Aug 18 2020 21:28:20 GMT+0200 (CEST)] [HAP Server] [HomeMaticThermostatAccessory] XXX min 4.5 | max 30.5 will be used in homekit for this device
```

dumdiedum
