### ISSUE TITLE
Kosmetik: "Next" & "Previous" Button bei neuen Gerät anlegen

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#16]
Hallo Thomas

Wenn man ein neues Gerät anlegt, werden zwischen "previous" und "next" die seiten 1-8 als button angezeigt. Wenn man auf "8" steht und auf "next" klickt, würde ich erwarten dass nicht nur der Zahlenbereich unten "weiterrutscht" (also man sieht dann "9") ... sodern auch gleich oben die Seite "9" angezeigt wird" 

lg Richard

**Comment by thkl** [comment]
bleibt so

**Comment by roe1974** [comment]
:-P
