### ISSUE TITLE
HmIP-BROLL: Öffnen statt Offen

### ISSUE THREAD

**Issue by ChrWi** [thkl/hap-homematic#160]
Hallo Thomas,
Meine frisch installieren BROLL‘s zeigen mir im AppleHome ein „Öffnen“ anstatt „Offen“. (In Eve 100% - ok)
![FA2492B0-649B-4685-AAF5-52F84DFEE3A4](https://user-images.githubusercontent.com/52505025/91165785-9294cc80-e6d1-11ea-95a6-94b31192b57e.jpeg)
![125491DE-330C-48F1-B555-59D3D8FED063](https://user-images.githubusercontent.com/52505025/91165787-93c5f980-e6d1-11ea-8c50-a3a5b5f53529.jpeg)
Ist das ein Typo bei Dir oder liegt das am Apple Home?

**Comment by thkl** [comment]
Das hatten wir doch schon mal bei HM(not IP) Rollos ... 
Ich liefere generell keine Texte oder so .. sondern nur den Ist Zustand in % (0-100) und den Soll Zustand (0-100) .. HomeKit selber erzeugt dann die Icons/Texte

Aber HM und HMIP Rollos sind unterschiedliche Klassen ich schau mal ob die IP Klasse was anders macht.

**Comment by artspe** [comment]
Ja, das hatten wir schon mal. Ist ein Bug in der iOS 13 Home App. Ab iOS 14 werden die Zustände korrekt mit "Geöffnet" angezeigt.

**Comment by ChrWi** [comment]
Kann noch kein iOS14 nutzen, aber danke für den Hinweis @artspe
