### ISSUE TITLE
Seit dem Update auf 0.0.50 kann man bei Besondere Geräte nicht mehr auf Neu klicken.

### ISSUE THREAD

**Issue by LevelOne2k** [thkl/hap-homematic#162]
Hallo @thkl ich habe eben das Update auf 0.0.50 gemacht. Seitdem kann ich bei "Besondere Geräte" nicht mehr auf "Neu" klicken, es öffnet sich kein Dialog.

<img width="1415" alt="Bildschirmfoto 2020-09-04 um 21 42 03" src="https://user-images.githubusercontent.com/25386824/92279430-90174b80-eef7-11ea-8f32-643c0883c5c0.png">

**Comment by thkl** [comment]
Gibt es auf der Browserconsole irgendwelche Fehlermeldungen ?

**Comment by LevelOne2k** [comment]
Wo finde ich die?

**Comment by thkl** [comment]
Zb im Chrome Rechtsklick und dann "Untersuchen" aus dem Menü wählen.

**Comment by LevelOne2k** [comment]
Das vielleicht?
<img width="725" alt="Bildschirmfoto 2020-09-04 um 22 42 18" src="https://user-images.githubusercontent.com/25386824/92283302-e8524b80-eeff-11ea-9112-beada237fbcc.png">

**Comment by thkl** [comment]
OK offensichtlich liefert der Server die Liste der verfügbaren Sonderklassen nicht.
Dazu bräuchte ich mal das DebugLog um zu verstehen was schief läuft. Ich kann das auf 2 Testsystemen hier erst mal nicht nachvollziehen.


- auf der HAP Weboberfläche Internes / HAP Neustart
- DebugModus im Neustartfenster aktivieren
- kurz warten bis HAP neu gestartet ist
- Browser Reload
- Besondere Geräte / Neu anklicken
- dann über Internes / Log herunterladen das Logfile sichern
- über Internes Debug wieder ausschalten

Das Logfile entweder hier anhängen oder mir per Mail zukommen lassen.

**Comment by LevelOne2k** [comment]
Mail ist raus

**Comment by thkl** [comment]
da fehlt ein großer Teil des launches … 
das Logfile endet mit dem Laden von CCU Daten. Die ganzen Devices richtung HomeKit sind noch nicht mal initialisiert.
Evtl zu früh das ganze geladen.


ggf crasht das Ding ja wenn, dann liegen die crashlogs auf der ccu unter /usr/local/etc/config/addons/hap-homematic/  (das ist das config verzeichnis)
die heissen irgendwas.crash

**Comment by LevelOne2k** [comment]
Der findet auch irgendwie keine Geräte aus dem Raum Wohnzimmer. Der Port ist aber frei

<img width="506" alt="Bildschirmfoto 2020-09-05 um 11 21 18" src="https://user-images.githubusercontent.com/25386824/92302209-985c9e80-ef6a-11ea-80a9-c76b0f1f730d.png">

<img width="1417" alt="Bildschirmfoto 2020-09-05 um 11 21 05" src="https://user-images.githubusercontent.com/25386824/92302212-9abef880-ef6a-11ea-9133-477c2e7a35c1.png">

**Comment by thkl** [comment]
HomeKit Geräte funktionieren aber ? Schaut so aus, als ob die Weboberfläche keine / oder unvollständige Daten vom Serverdaemon bekommt.  Kann ich mal ein aktuelles Backup haben ? Was für eine CCU Variante (welche FW) läuft da ?

**Comment by LevelOne2k** [comment]
RM 3.51.6.20200621

Backup von HAP? Wenn ja, kommt per Mail dann

**Comment by thkl** [comment]
nö

eher damit : 
```
[Sat Sep 05 2020 11:07:01 GMT+0200 (CEST)] warn - [HAP Server] [Server] no channels to map in configuration found
```

**Comment by LevelOne2k** [comment]
Und nu?

**Comment by thkl** [comment]
travis hat ein kleines timingproblem .. jetzt ist er grün ...

Ich brauch eine Kopie des Config Verzeichnisses. Wichtig sind diese Files:

```
config.json
devices.json
evdps.json
programs.json
rooms.json
variables.json
```

**Comment by LevelOne2k** [comment]
Ist per Mail raus

**Comment by thkl** [comment]
In Deiner Config sind keine Geräte die zu HomeKit gehen .... warum kann ich erstmal nicht sagen. Vor dem Update wird ein Backup der Config angelegt. Dieses liegt im config Pfad und heisst autobackup_version blabla ... da kannst du mal die config.json rauskopieren und in den Config  Pfad werfen. anschließend HAP rebooten und schauen ob es dann geht ..

**Comment by LevelOne2k** [comment]
Da werden auch keine Geräte drin sein. Wollte HAP erst jetzt mit der 0.0.50 aktiv nutzen und habe erst (eben) in der 0.0.50 eine Instanz (Wohnzimmer) zu HAP hinzugefügt.

**Comment by thkl** [comment]
Achso, ok .. ich schau mal warum aus dieser Config keine Special Devices funktionieren

**Comment by LevelOne2k** [comment]
Naja, es werden ja auch keine normalen Geräte aus dem Raum Wohnzimmer geladen. Tote Hose bei mir ^^

**Comment by thkl** [comment]
Es werden zwar alle Serviceklassen geladen aber es fehlt ein Eintrag im Log, der alle Services die es daraus dann gibt auflistet. Daher weiß dann auch der Configuration Server nicht was er anlegen soll und es werden keine Geräte angezeigt.

Auf meiner VM RM funktioniert das aber mit Deiner config.

**Comment by thkl** [comment]
Aber wenn Du eh noch nichts eingetragen hasts, dann kill doch das AddOn von der CCU und installier es mal neu.
Es scheint so das der HAP-Daemon mit dem Laden der Serviceklassen nicht fertig wird. Warum kann ich aktuell nicht ermitteln.

**Comment by LevelOne2k** [comment]
Okay, mache ich.

Müssen die Ports freigegeben werden? Eine Instanz wird ja automatisch angelegt mit dem Port 9877 und als ich die Instanz Wohnzimmer angelegt habe, wurde für diese Instanz der Port 9878 angelegt.

**Comment by thkl** [comment]
es werden die Ports benötigt, die in der Instanzliste stehen

**Comment by LevelOne2k** [comment]
Habs deinstalliert und neu installiert, nun funktioniert alles. Auch kann ich bei den besonderen Geräten auf "Neu" klicken und der Dialog öffnet sich. Danke!

**Comment by thkl** [comment]
ich habe noch mal was am timing des classloaders geändert. Sollte in nächster Version stabiler sein

**Comment by LevelOne2k** [comment]
@thkl Gerade habe ich von 0.0.50 auf 0.0.51 geupdatet, und nun kann ich bei besondere Geräte wieder nicht auf "Neu" klicken, genau wie es beim Update von 0.0.49 auf 0.0.50 war.

**Comment by thkl** [comment]
ok das problem liegt in der ClassList .. blöd nur das ich das an mehreren TestSystemen nicht nachvollziehen kann .. auf was für einer Hardware läuft das Ganze denn ?

**Comment by LevelOne2k** [comment]
Raspi3

**Comment by thkl** [comment]
siehe https://github.com/thkl/hap-homematic/issues/165#issuecomment-688429961
