### ISSUE TITLE
Frage zur HAP Bedienung / Konfiguration

### ISSUE THREAD

**Issue by LevelOne2k** [thkl/hap-homematic#163]
Hallo @thkl !

Ich habe eine neue Instanz hinzugefügt und diese "WohnzimmerHAP" genannt. Dann habe ich den Raum Wohnzimmer ausgewählt und mir wurden alle Geräte im Raum Wohnzimmer angezeigt, zum test habe ich erstmal nur ein Gerät ausgewählt.

Die Instanz konnte ich in der Home App hinzufügen, per Code, QR-Code gibt es keinen, oder? Die Instanz wurde hinzugefügt und ich musste das Gerät trotzdem einem Raum hinzufügen. Ich hatte es so verstanden, dass durch die Instanz auch direkt ein Raum in HomeKit hinzugefügt wird, in meinem fall "WohnzimmerHAP" dem ist aber nicht so, es gibt keinen Raum "WohnzimmerHAP". 

Wenn ich nun eine weitere Instanz hinzufüge z.B. für den Raum Büro, kann man dann nicht die Geräte aus dem Raum Büro erst auswählen bevor die Instanz erstellt wird? Ich habe die Instanz "HomeMatic BüroHAP" dann in der Home App hinzugefügt, aber dort sind keine Geräte drin.

**Comment by thkl** [comment]
Die Instanzen müssen zuerst leer ohne ein Gerät in Homekit hinzugefügt werden. Dann werden sie HomeKit Räumen zugeordnet. Wird dann über HAP einer Instanz ein Gerät hinzugefügt, dann setzt HomeKit es in den gleichen Raum wie die Bridgeinstanz selber. Wird die BridgeInstanz initial mit den Geräten veröffentlicht muss jedes Gerät manuell zugeordnet werden.

Der Wizzard ist da recht eindeutig in der Beschreibung. Das Wiki https://github.com/thkl/hap-homematic/wiki/Instanzen auch.

**Comment by LevelOne2k** [comment]
Entweder bin ich grad komplett zu blöd, oder ich weiss auch nicht. Ich lege erst eine Instanz mit beliebigem Namen an, oder mit Namen wo es schon einen Raum für gibt z.B. Wohnzimmer? Diese Instanz für ich dann in HomeKit hinzu, weise der Instanz einen Raum zu z.B. Wohnzimmer, und erst dann gehe ich in HAP zu "Geräte" --> "Neu" suche das entsprechende Gerät, klicke auf Auswählen und im nächsten Schritt weise ich dem Gerät einen Namen und die Instanz hinzu? Ist das so korrekt?
