### ISSUE TITLE
HTTP Device funktioniert bei mir mit folgender URL nicht

### ISSUE THREAD

**Issue by LevelOne2k** [thkl/hap-homematic#164]
Hallo @thkl !

Ich kann mit folgender URL z.B. im Browser meinen Receiver einschalten:
http://root:passwort@192.168.178.18:9541/web/remotecontrol?command=116

Ich habe unter besondere Geräte ein "HomeMaticSPHTTPAccessory" angelegt und die oben genannte URL eingetragen. Wenn ich das Gerät nun in der Home App einschalte, passiert leider nichts, eigentlich sollte sich dann der Receiver einschalten.

**Comment by thkl** [comment]
ja, authentication und parameter wurden bisher nicht unterstützt

**Comment by LevelOne2k** [comment]
Kann ich die geänderte Datei schon einfügen damit es schon klappt?

**Comment by thkl** [comment]
ja

**Comment by LevelOne2k** [comment]
Und wie? ^^

**Comment by thkl** [comment]
das neue File HomeMaticSPHTTPAccessory.js muss nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services kopiert und das alte dort überschrieben werden. HAP Neustart fertig

**Comment by LevelOne2k** [comment]
Kannst Du das evtl. schon als Update zur verfügung stellen? Wenn ich es ändere, crasht irgendwie alles.
