### ISSUE TITLE
Seit dem Update auf 0.0.50 kann ich keine neuen Geräte mehr hinzufügen

### ISSUE THREAD

**Issue by timwegenerDE** [thkl/hap-homematic#165]
Seit dem Update auf 0.0.50 kann ich keine neuen Geräte mehr hinzufügen. Die Liste der verfügbaren Geräte bleibt leer.

<img width="1224" alt="Bildschirmfoto 2020-09-06 um 16 15 40" src="https://user-images.githubusercontent.com/56134910/92327785-80654780-f05c-11ea-85cd-6a79a1fee8fc.png">

Vorhandene Geräte funktionieren einwandfrei.

Klingt ähnlich zu: #162 
Allerdings kann ich das Plugin nicht noch mal rausschmeißen, da ich hier bereits eine Vielzahl an Geräten drin habe.

**Comment by thkl** [comment]
ja, das könnte ein Timingproblem beim erstellen der Services sein.Das habe ich versucht im neuen Code schon zu umgehen. npm kommt später

**Comment by timwegenerDE** [comment]
0.0.51 bringt etwas Besserung: Die Geräte werden wieder angezeigt. Beim Klick auf "Auswählen" passiert jedoch nichts mehr.

<img width="1200" alt="Bildschirmfoto 2020-09-06 um 21 11 58" src="https://user-images.githubusercontent.com/56134910/92333472-0b0e6c80-f086-11ea-86a6-28523e387587.png">

Zeitversetzt kommt der hinzu:

<img width="1208" alt="Bildschirmfoto 2020-09-06 um 21 13 55" src="https://user-images.githubusercontent.com/56134910/92333483-1a8db580-f086-11ea-9fd9-b44cc2f58587.png">

**Comment by thkl** [comment]
hmm kannst Du mal schauen, ob der Server im Log einen Fehler wirft. Schaut so aus, als ob der API Call für channelAddress einen 500er Fehler zurückliefert

**Comment by timwegenerDE** [comment]
Kein Error im Log. Auch vom Gerät selbst (ID) keine Spur. In dem ganzen minifizierten Kram kann ich leider auch nicht debuggen; Da bin ich zu wenig JavaScript-Pro für :-P

**Comment by thkl** [comment]
Sind special Devices konfiguriert ?

**Comment by timwegenerDE** [comment]
Ja, ein Garagentor.

**Comment by thkl** [comment]
Ok ich Versuch das morgen mal nachzubauen. Sehr wild.

**Comment by timwegenerDE** [comment]
Kein Stress. Kann auch sonst TeamViewer o.ä. anbieten, um das Nachbauen zu sparen.

BTW: Cooles Add-On, cooler Typ! 👍

**Comment by thkl** [comment]
Also das Problem ist das Gleiche, wie vorher. Die Serviceliste kann nicht erstellt werden. 
An der Erstellung dieser Liste habe ich seit .50 was gemacht um einige neue Funktionen zu bewerkstelligen.
Daher müsste man das Ganze wirklich mal im Debugmodus starten um zu sehen, was ggf schief läuft.

**Comment by timwegenerDE** [comment]
Leider nein.
Das Bearbeiten von Geräten geht übrigens auch nicht mehr; Der Dialog erscheint nicht.

**Comment by thkl** [comment]
Das ist alles die gleiche Funktion. Baut alles auf einer Serviceliste auf die augenscheinlich nicht da ist.

**Comment by thkl** [comment]
> Wie kann ich denn mal Zugriff auf meine Umgebung geben?
das wäre vielleicht gar nicht mal so eine schlechte idee

**Comment by timwegenerDE** [comment]
Wo find ich die Adresse? :)

**Comment by thkl** [comment]
in jedem Source file ganz oben ;o) https://github.com/thkl/hap-homematic/blob/master/lib/Server.js

**Comment by thkl** [comment]
so, vielen Dank fürs Debugging an @timwegenerDE  das ist ein Timing Problem und in  0.0.53  erstmal gelöst

**Comment by arndtk** [comment]
Guten Tag,

meine Frage passt vielleicht nicht ganz rein, aber wo kann ich die 0.0.50 herunter laden? Ich sehe nur die 0.0.11 als latest?

Danke und Grüße,
Arndt

**Comment by dkrizic** [comment]
Hallo @arndtk, einfach die 0.0.11 installieren und dann Update auf die aktuelle Version machen.

**Comment by thkl** [comment]
Das auf der GitHub Seite stehende tar.gz ist nur der Installer. 
Dieser installiert immer die aktuelle Version. 

Sollte schon eine Version auf der CCU vorhanden sein, gibt es auf der WebOberfläche des Addons einen Update Button.

**Comment by arndtk** [comment]
<img width="511" alt="Bildschirmfoto 2020-09-22 um 13 52 59" src="https://user-images.githubusercontent.com/11616282/93878870-0d560500-fcdb-11ea-9311-3923aba5286f.png">

Vielen Dank!! Also ist das so korrekt?

**Comment by thkl** [comment]
Ja und mit dem Klick auf "einstellen" kommt man ja aufs WebUi da sollte Version 0.53 oben rechts stehen. 

Das kleine CCU Addon ist wirklich nur für die Installation und den Start des HomeKit Dienstes zuständig.  Daher ändert sich dessen Version nicht so oft mit.

**Comment by arndtk** [comment]
Wunderbar und nochmals danke!
