### ISSUE TITLE
Alarmanlagen Problem

### ISSUE THREAD

**Issue by theo-69** [thkl/hap-homematic#166]
Seit dem letzen Update habe ich folgendes Problem:

Wenn ich die Alarmanlage in HomeKit einschalte erscheint im Icon Aktivieren... aber es passiert nix. Erst wenn ich die APP schließe und öffne wird die Alarmanlage eingeschaltet. Das selbe dann mit Deaktivieren 🤔

**Comment by theo-69** [comment]
any Ideas?

**Comment by thkl** [comment]
nein ich hab das mal mit einer HM-SEC-SIR-WM ausprobiert da funktioniert es

**Comment by Mattis-Schulte** [comment]
Habe das selbe Probleme mit meiner Alarmanlage über eine Systemvariable, sonst funktioniert es aber gut

**Comment by thkl** [comment]
Kurze Frage hierzu : Wird der Schaltvorgang selber ausgeführt und stimmt nur die Anzeige in HomeKit nicht ?

**Comment by Mattis-Schulte** [comment]
Es stimmt nur die Anzeige in HomeKit nicht

**Comment by theo-69** [comment]
bei mir auch mit Systemvariablen

**Comment by lukasriegel** [comment]
gleiches Problem bei mir auch - Alarmanlage über SV. Es stimmt nur die Anzeige in HomeKit nicht.

**Comment by Mattis-Schulte** [comment]
Die letzte Version hat das Problem behoben, also denke ich mal, dass dies hier geschlossen werden könnte.
