### ISSUE TITLE
Konfigurationsdaten Fenstersensoren nach update auf 0.0.51

### ISSUE THREAD

**Issue by MattN82** [thkl/hap-homematic#169]
Ich hab jetzt so garkeine Ahnung ob das überhaupt eine "Issue"-Charakter hat, aber es kommt mir seltsam vor:

Seit ich auf 0.0.51 geupdated habe (Wonach die Home-App übrigens bei den ersten 2-3 Starts wie in Zeitlupe reagiert hat, falls das relevant/interessant ist), "sammeln" sich in den Servicemeldungen meiner Raspberrmatic 

"Konfigurationsdaten stehen zur Übertragung an"

bei meinen Fenstersensoren (HMIP-SWDO-I), die sich durch klick auf bestätigen nicht wegklicken lassen.

Alle 3 Minuten meldet sich der nächste. Hatte ich so noch nie. Erschiene mir wir ein Riesenzufall, dass eine andere Ursache das exakt nach dem Update ausgelöst haben könnte.

Deswegen, zur Sicherheit, Issue aufgemacht :-)

EDIT: Jetzt fängt die RPM an, sie "wegzuarbeiten". Ok, vielleicht doch kein Issue. Ich lass es aber mal stehen, falls in irgendeiner Weise doch mit dem update verknüpft

**Comment by thkl** [comment]
Ich schreibe, außer beim programmierbarem Thermostat, nichts an die Geräte der CCU. Daher halt ich das nicht für einen Issue ... aber ich lass das mal offen

**Comment by MattN82** [comment]
Was auch Immer es war, es ist weg. Wird wohl doch ein Zufall gewesen sein. Ich denke das hier kann weg nach closed oder gelöscht werden :-)

**Comment by thkl** [comment]
Na dann 🤓
