### ISSUE TITLE
Kosmetik: Bei "internals" fehlt ein icon .... schwierig zu klicken bei kleiner "Seitenleiste"

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#17]
Hallo Thomas

Bei "internals" fehlt ein icon. Wenn man die Seitenleiste minimiert, sieht man bei den oberen Punkten nur mehr die icons, bei "internals" nur mehr einen Teil von dem Wort ... ausserdem "verrutscht" der Punkt "internals"

![Unbenannt](https://user-images.githubusercontent.com/30420568/80366468-9a5e7480-8889-11ea-9607-ac577caa0f6d.JPG)

lg Richard

**Comment by thkl** [comment]
demnächst:

![image](https://user-images.githubusercontent.com/884355/80404099-f7c1e800-88c0-11ea-9f33-7f82b093f1f6.png)

**Comment by roe1974** [comment]
ahhhhhhhh 👍
