### ISSUE TITLE
Lokale Einbindung von showdown.js

### ISSUE THREAD

**Issue by timwegenerDE** [thkl/hap-homematic#170]
Momentan ist showdown.js über cloudflare (https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.1/showdown.js) eingebunden. Alleine schon aus Datenschutz- und Zuverlässigkeits-Gründen schlage ich eine lokale Einbindung vor.

**Comment by thkl** [comment]
ja ok kann man machen
