### ISSUE TITLE
Special Device GarageDoor - Eventsperren bis Tor ganz auf/zu

### ISSUE THREAD

**Issue by timwegenerDE** [thkl/hap-homematic#171]
Hallo Thomas,
mein Garagentor hat nur einen einzigen Taster für Auf/Zu. 
Immer wenn der Taster geschlossen wird, werden diese Befehle abwechselnd ausgeführt. Wenn der Taster jedoch schließt während das Tor in Fahrt ist, stoppt es.

Wenn das Tor also gerade öffnet und ich es dann per HomeKit (vermeintlich) wieder schließe, bleibt es stehen.
Kann im ungünstigsten Fall dazu führen, dass ich das Tor versehentlich nicht schließe.
Hierzu bräuchte es ein "Timeout" / eine "Bediensperre" für die Dauer der Fahrt.

Danke im Voraus!

**Comment by thkl** [comment]
Kann man machen. Ich möchte nur bemerken, das dann natürlich die Möglichkeit entfällt, das Tor im Notfall zu stoppen.
Wenn HAP dann einfach x Sekunden einen Befehl ignoriert. Aber ok. Die sichere Variante wäre ein Sensor für Tor ist komplett Offen und einer für Tor ist geschlossen.

**Comment by hillinator** [comment]
Ich würde es garnicht schlecht finden, wenn das Tor stehen bleibt. Der Status müsste dann nur von z.B. „Öffnen“ in „Offen“ wechseln und wenn man nochmal betätigt dann auf „schließen“. Wenn das Tor wirklich „geschlossen“ ist, zeigt ja der Sensor.

**Comment by thkl** [comment]
Naja wenn, dann wird das ein optionaler Parameter in der Öffnen / Schließen Aktor Message. 

Der Zustand des Tores ist nur mit 2 Sensoren (offen / geschlossen) zuverlässig darstellbar. Sonst wird halt aus bisherigen Aktionen geraten.

**Comment by timwegenerDE** [comment]
Aber auch mit einem zweiten Sensor würde das Problem doch noch bestehen oder? Das Tor stoppt ja dann trotzdem nur wenn es während der Fahrt einen erneutes Taster-Schließen bekommt.

Aber deine Bedenken, Thomas, bezgl. das Tor kann nicht gestoppt werden sind nicht von der Hand zu weisen. 

Mal mit zwei Sensoren dahin gesponnen:

Wenn (!TorSensorGeöffnet && !TorSensorGeschlossen)
{
SchalterSchließen; // Stoppt das Tor
2Sek. warten;
Schalter schließen; // Lässt das Tor in entg. Richtung fahren
}

Und anstatt dem GeöffnetSensor eine „Fahrtdauer“:

Fahrtdauer=20s;
Wenn (!TorSensorGeschlossen && AktuelleFahrtDauer < Fahrtdauer)
{
SchalterSchließen; // Stoppt das Tor
2Sek. warten;
Schalter schließen; // Lässt das Tor in entg. Richtung fahren
}

Aber so ganz trivial ist das ja dann schon nicht mehr...

**Comment by thkl** [comment]
Ja. Der zweite Sensor stellt nur sicher, das die korrekte Torposition dargestellt wird. Und nicht der geratene Wert aus den Aktionen.

**Comment by hillinator** [comment]
Kann man nicht mit einer internen variable arbeiten? 
HM_GD_STATUS = Öffnen
Wenn das Tor angehalten wurde, bzw. erneut die taste betätigt wird, wird der Wert invertiert
HM_GD_STATUS = Schließen

if (GM_GD_STATUS == "Öffnen")
{GM_GD_STATUS = "Schließen"
}
else 
{GM_GD_STATUS = "Öffnen"
}

Damit hätte man bei einem initialen geschlossenem Tor (Sichergestellt durch den Sensor) immer den aktuellen Status.

**Comment by thkl** [comment]
Naja das ist ja auch nur der Sollzustand.  Der Antrieb hat ja nur einen Impulseingang der bei jedem Impuls die Fahrtrichtung wechselt.

**Comment by Jemeins** [comment]
Moin,
ich möchte das Thema noch mal aufgreifen.
Optimal wäre es denke ich wenn mit 2 Sensoren und einer Zeit gearbeitet wird.

-Während der fahrt erneute Ansteuerung -> Tor stoppt -> HomeKit anzeige "Tor geöffnet"
-Tor erreicht vom Fahrtbefehl an länger als die eingestellte Zeit keine Endlage -> Blockade entdeckt 

Denn so hätte man gleich die Blockademeldung in HomeKit für das Tor realisiert.

Mit freundlichen Grüßen
