### ISSUE TITLE
Thermostate mit Unterputz Schalter gekoppelt

### ISSUE THREAD

**Issue by theo-69** [thkl/hap-homematic#172]
Hallo ich habe ein Wandthermostat mit einem Unterputzschalter als direkte Verbindung verknüpft. Ändere ich die Temperatur am Thermostat schaltet der Schalter sofort. Ändere ich die Temperatur via HomeKit dauert es ca. 5min. Was mache ich falsch oder wie kann ich das Problem beheben?

**Comment by thkl** [comment]
Was passiert wenn die Temperatur über die CCU WebOberfläche geändert wird ?

**Comment by theo-69** [comment]
Okay liegt an CCU3, hat einer ne Idee wie was Problem lösen kann?
Hier die Info von ELV "Die aktuelle Statusinformation... Aktor EIN/AUS...erfolgt im Zeitraster von ca. 2,5 min.
Dieser Zyklus ist unabhängig von der zyklischen Statusmeldung des HmIP-STHD. Eine Verkürzung ist deshalb nicht möglich."
