### ISSUE TITLE
Leere GUI bei gesperrter Internetverbindung

### ISSUE THREAD

**Issue by MattN82** [thkl/hap-homematic#173]
In den letzten Tagen habe ich ein wenig mit der Option rumgebastelt, mein System komplett offline...also ohne Internetverbindung zu betreiben.

Dabei ist mir grad was aufgefallen: Sperre ich der Raspberrymatic die Internetverbindung (via Gerätesperre in der Fritzbox), ist die gesamte GUI von hap-homematic leer. Also leer im Sinne von: Kein Text, keine Geräte...nichts. Egal auf welchen Reiter ich klicke...Geräte, Instanzen....alles leer.

Der Dienst läuft aber einwandfrei. 

Sobald ich die Sperre wieder rauswerfe, zack, Text/Inhalt wieder da. Ist das bekannt?

**Comment by thkl** [comment]
Ja, das ist das hier : https://github.com/thkl/hap-homematic/issues/170

**Comment by thkl** [comment]
Oh sorry ich habe gesehen, es geht um das Inet der CCU. Das Problem ist wenn der Update Check fehl schlägt.
Ich hab das korrigiert.

**Comment by MattN82** [comment]
Danke. Schnellste support response time ever! :-)
