### ISSUE TITLE
Instanzen und Geräte weg

### ISSUE THREAD

**Issue by Schorsinator** [thkl/hap-homematic#174]
Hallo zusammen,

ich habe auf meiner CCU3 hap-homematic in der Version 0.0.53 installiert.
Nach der Einrichtung war ich auch total begeistert, alles hat super funktioniert.
Nach 2 Tagen wurden mir jedoch sämtliche Geräte im Homekit als nicht erreichbar angezeigt!? Ein Blick in die
hap-homematic-Oberfläche hat gezeigt, dass keine Instanzen und Geräte mehr vorhanden sind. Diese konnte ich auch leider nicht wieder hinzufügen. Ich hatte als erstes ein geändertes CUXD-Gerät in verdacht...Also hap-homematic noch einmal neu installiert und eingerichtet. Wieder hat alles einwandfrei funktioniert. Nun nach 2 Tagen sind leider wieder alle Geräte und Instanzen weg. An den CUXD-Geräten habe ich diesmal nichts geändert, ich habe nur 2 weitere Homematic-Rauchmelder installiert.
Kann es vielleicht mit meiner NODE-RED-Instanz zusammenhängen? Die hap-homematic-Log-Datei lässt sich bei mir leider nicht öffnen.

Kennt vielleicht jemand das Problem?

Vielen Dank im Voraus.

**Comment by thkl** [comment]
Unter /usr/local/etc/config/addons/hap-homematic liegt das config File (config.json)

Wenn da nichts mehr drin steht ist es ein hap-homematic Problem. 

Ggf liegen in diesem Ordner auch .crash Files die erzeugt werden wenn der hap-homematic Dämon crasht. 


Das Log liegt unter /var/log/hap-homematic.log
