### ISSUE TITLE
Time to release new version 0.0051?

### ISSUE THREAD

**Issue by Glibbertt** [thkl/hap-homematic#175]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Device related data**
If you want to add a new device or add a feature to a new device, please login to your hap-homematic WebUI; Select Internal/Help and create the device description file as described in the dialog you will get. Please attach the file to your request.

**Comment by thkl** [comment]
its done when its done
