### ISSUE TITLE
SPMultiChannelKeyAccessory – Reihenfolge und Tastenbeschriftung

### ISSUE THREAD

**Issue by florianbeck** [thkl/hap-homematic#176]
In der Apple-Home-App wird die Reihenfolge der Taster nicht eingehalten und die Beschriftung nicht übernommen. In der Eve-App wird alles richtig dargestellt inkl. Tastenbeschriftung. 

Als Beispiel habe ich den ersten Taster mit der Szene "Gemütlich" verknüpft. In Eve korrekt EZ_6T:1. Bei Apple ist das aber Taste 3.

Details siehe Screenshots.

![IMG_3931](https://user-images.githubusercontent.com/15218751/93532693-cf0abf80-f941-11ea-8cee-978782b09708.PNG)
![IMG_3930](https://user-images.githubusercontent.com/15218751/93532701-d336dd00-f941-11ea-8f01-90f6ae12968d.PNG)
<img width="1128" alt="Bildschirmfoto 2020-09-18 um 00 00 29" src="https://user-images.githubusercontent.com/15218751/93532890-2872ee80-f942-11ea-8771-068316f01d6f.png">

**Comment by thkl** [comment]
Tja. Aber das ist wohl eher ein Problem mit der Home App

**Comment by florianbeck** [comment]
Das habe ich befürchtet ;)
