### ISSUE TITLE
Raspberrymatic 3.53.30.20200919  kein Installation möglich

### ISSUE THREAD

**Issue by docrossi** [thkl/hap-homematic#177]
Raspberrymatic 3.53.30.20200919  kein Installation möglich

**Comment by thkl** [comment]
Das heißt konkret was ?

**Comment by docrossi** [comment]
<img width="1943" alt="Bildschirmfoto 2020-09-20 um 11 43 58" src="https://user-images.githubusercontent.com/64773359/93708522-389fef00-fb37-11ea-89bb-2d6e57ca426c.png">

**Comment by thkl** [comment]
Schaut aus wie ein kaputtes Addon. Das hier ist das richtige : 

https://github.com/thkl/hap-homematic/raw/master/addon_installer/hap-homematic-0.0.11.tar.gz

**Comment by docrossi** [comment]
funktioniert !

**Comment by thkl** [comment]
Perfekt, das tar.gz für das Addon war aus dem Release verschwunden. Ich habe es noch mal neu angehangen.
