### ISSUE TITLE
Tip: Use HMIP-BSM for controlling a HomeKit lamp

### ISSUE THREAD

**Issue by dkrizic** [thkl/hap-homematic#178]
In my daughters room I have a HMIP-BSM (Light switch) and now she wanted a lamp that can change the color. The bulb is a VOCOLinc L3 bulb that can be fully controlled via HomeKit via Wifi and prefers to receive constant power. I wanted the BSM to deliver constant power but wanted to use it for controlling this lamp.

The BSM has the following setup:

![image](https://user-images.githubusercontent.com/1181349/93857204-8a24b700-fcba-11ea-8af4-fae1cadeccf8.png)

- Channel 1: Sensor for light off
- Channel 2: Sensor for light on
- Channel 3: Actor for the light

Channel 1,2 and 3 are coupled by default. They need to be decoupled. The actor is configured to be permanently on. Channel 1 and 2 are exposed as HomeMaticKeyAccessory:

![image](https://user-images.githubusercontent.com/1181349/93856999-2ef2c480-fcba-11ea-96c9-ee70868694ab.png)

They appear as programmable switches:

![image](https://user-images.githubusercontent.com/1181349/93857046-43cf5800-fcba-11ea-98cd-d35d15970f84.png)

They now can be coupled with the actual HomeKit lamp. Upon light on you can configure the level (0-100%) and the color. The result is, that the switch behaves like expected and the lamp receives permanent color.

**Comment by ChrWi** [comment]
@thkl kann man diesen guten Beitrag ins Wiki verschieben?

**Comment by thkl** [comment]
Muss ich kopieren aber ja. Vielen Dank schon mal an @dkrizic für das hilfreiche Beispiel.

**Comment by ChrWi** [comment]
@thkl Ich habe den Beitrag im [Wiki](https://github.com/thkl/hap-homematic/wiki/Devices#programmable-switch) dokumentiert und dabei die img dieses Beitrags übernommen. Bitte bei Bedarf verschieben!
<img width="240" alt="BSM-1" src="https://user-images.githubusercontent.com/52505025/135508540-36dcf2f4-217f-4ca3-b75c-b1f2e8b9a315.png">
<img width="510" alt="BSM-2" src="https://user-images.githubusercontent.com/52505025/135508547-c431a409-19f5-4041-a580-c767110509d8.png">
<img width="507" alt="BSM-3" src="https://user-images.githubusercontent.com/52505025/135508552-fae7fffc-3be7-45b8-b8a3-9de872d93899.png">
