### ISSUE TITLE
Hilfe bei Garagentor-Config

### ISSUE THREAD

**Issue by arndtk** [thkl/hap-homematic#179]
Hallo zusammen,

sorry für die wahrscheinlich nervige Frage, aber nach dem Wechsel von der CCU2 auf die 3 und nun auch mit HAP, funktioniert alles soweit sehr gut! Vielen Dank für diese super Erweiterung!

Leider bekomme ich die Sache mit dem Garagentor nicht geregelt. :-( Ich weiß einfach nicht, welche Werte ich wo eintragen muss. Nachfolgend meine beiden Aktoren, welche ich bis dato genutzt habe.

**Neigungssensor für den Auf/Zu-Zustand**

<img width="1063" alt="Bildschirmfoto 2020-09-22 um 20 58 28" src="https://user-images.githubusercontent.com/11616282/93925708-cede3b80-fd16-11ea-84cb-05b9195fe0e1.png">

**Schalter mit potentialfreiem Ausgang, der den Garagentorantrieb "triggert".**

<img width="874" alt="Bildschirmfoto 2020-09-22 um 20 57 27" src="https://user-images.githubusercontent.com/11616282/93925729-d69de000-fd16-11ea-8444-3eadad5ce2b2.png">

Welche Werte muss ich hier eintragen?

<img width="1115" alt="Bildschirmfoto 2020-09-22 um 20 59 04" src="https://user-images.githubusercontent.com/11616282/93925758-e1587500-fd16-11ea-80fc-dd672e9bf1a5.png">

Vielleicht könnte mir hier jemand auf die Sprünge helfen, das wäre super!! 

Grüße
Arndt

**Comment by thkl** [comment]
1. den neigungssensor bei Adresse des Schließen Sensors auswählen und zwar dort den Kanel 1 und STATE Datenpunkt
2. fraglich ist jetzt was der meldet wenn das Tor geschlossen ist ... true oder false ... (Feld Status des Schließen Sensors) das einfach mal ausprobieren. Entweder der Zustand in HomeKit stimmt oder ist genau verkehrtrum

3. Den Funkschaltaktor bei Adresse des Öffnen Aktors auswählen und zwar Kanal 1 (das sollte der Schaltkanal sein) und auch den State Datenpunkt

Wenn der Aktor nur den Antrieb triggert wäre folgendes in der Nachricht Öffnen Aktor : {"on":1,"onTime":1}
Dann wird der Aktor geschalten und geht nach 1sek wieder aus

Rest der Felder bleiben so wie sie sind

Müsste so funktionieren ...

**Comment by arndtk** [comment]
Vielen Dank für Deine Rückmeldung, dass hatte ich im Vorfeld (so ähnlich) bereits versucht.

Jedoch komme ich nach dem Punkt DATA POINT nicht weiter bzw. kann nirgendwo etwas eintragen und es wird auch nicht angezeigt zum Auswählen. :-(

![1](https://user-images.githubusercontent.com/11616282/93976214-f2d26900-fd78-11ea-8724-19717661a5b3.jpg)

**Comment by arndtk** [comment]
Ob Du mir vielleicht nochmal helfen könntest? Oder mir sagen, wo ich diese Datenpunkte einsehen kann?

Danke und Gruß
Arndt

**Comment by thkl** [comment]
Der Datenpunkt für den Sensor heisst BidCos-RF.MEQ0475367:1.STATE der Aktor BidCos-RF.MEQ143772:1.STATE

Generell setzen sich die DPs wie folgt zusammen:  Schnittstelle.Seriennummer:Kanal.DatenpunktName

Bei welchem Gerät bleibt der Datenpunk Auswahldialog denn in deinem Obigen Screen stehen ?

**Comment by arndtk** [comment]
Hallo, wunderbar, es klappt nun! Es fehlte zwar eine 8 in der Adresse vom Aktor, aber das war mir zum Glück selbst aufgefallen!  ;-)

Bei beiden Geräten komme ich nach Datenpunkt nicht weiter:
HM-LC-Sw1-Pl-CT-R1
HM-Sec-TiS

Benötigst Du weitere Angaben?

**Comment by xz-wq** [comment]
Also bei mir werden leider auch keine Datenpunkte angezeigt.

![image](https://user-images.githubusercontent.com/60407231/94182576-8010dd00-fea1-11ea-8384-8d9f56142363.png)

![image](https://user-images.githubusercontent.com/60407231/94182532-70919400-fea1-11ea-9454-f5e740635b66.png)

**Comment by timwegenerDE** [comment]
Dito. Channel auswählen geht; Datenpunkte fehlen.

**Comment by thkl** [comment]
ja, das ist hier https://github.com/thkl/hap-homematic/commit/9014d2342594438a64c1cea5ad6b172ea68d550c schon gefixt aber noch nicht im Release

**Comment by timwegenerDE** [comment]
Hi Thomas,
Wann darf man denn mit dem neuen Release rechnen? :)

**Comment by thkl** [comment]
Jetzt ;)
