### ISSUE TITLE
ccu rasperrymatic

### ISSUE THREAD

**Issue by fighterzg6** [thkl/hap-homematic#18]
funktioniert das hap-homematic plugin auch wenn ich die ccu 3 zu einer raspberrymatic mache????

**Comment by roe1974** [comment]
Also ich verwende das plug-in auf einer RM ... wenn das die Frage ist .....

**Comment by fighterzg6** [comment]
naja wollte meine ccm zu einer raspberry matic machen, und dachte ich frag th erstmal, zwecks nodejs Versionen usw

**Comment by roe1974** [comment]
gibt es auf der RM Seite ein eigenes Image beim erstmaligen umstieg.....

https://github.com/jens-maus/RaspberryMatic/releases/download/3.51.6.20200420/RaspberryMatic-3.51.6.20200420-ccu3.tgz

![Unbenannt](https://user-images.githubusercontent.com/30420568/80372353-b5ce7d00-8893-11ea-97f6-33aaa547edce.JPG)

lg Richard

**Comment by thkl** [comment]
Ja die RM hat sogar eine neuere Node Version. 
Ggf vorher einmal die Config sichern. Der ganze Kram wird bei der CCU 3 ins Backup der CCU mit übernommen es sollte also out of the Box wieder gehen, da es die gleiche Architektur ist.

**Comment by fighterzg6** [comment]
ok, danke, dann morgen der Umzug!

**Comment by thkl** [comment]
Du kannst natürlich auf "nummer sicher" gehen. Den Config Ordner sichern. Das Addon auf der CCU3 löschen .. dann Backup der CCU machen .. umziehen .. Addon wieder installieren ... RM startet neu und installiert dabei alles wieder ... und dann config Ordner zurück kopieren ...

Aber vor dem Addon Remove den Ordner sichern, denn beim Löschen des Addons von der CCU entferne ich auch den Config Ordner ...

**Comment by roe1974** [comment]
meinst du den ordner ?

/usr/local/etc/config/addons/hap-homematic

Weil dieser ist nämlich leer:

/usr/local/etc/config/hap-homematic

lg Richard

**Comment by thkl** [comment]
die Daten liegen alle in /usr/local/etc/config/addons/hap-homematic

es gibt noch /usr/local/etc/addons/www/hap-homemartic -> da liegt das inde.html File, welches aus der Systemteuerung aufgerufen wird und die Weiterleitung macht

und /usr/local/addons/hap-homematic -> hier liegt der ganze Programmzauber

das Logfile liegt unter /var/log/hap-homematic.log

Ich mach mal noch eine Funktion ins UI, welche den Datenordner gezipt downloaded.
Aber der wird auch beim backup der CCU mit gesichert.

**Comment by roe1974** [comment]
ok, was aber ist das leere:
/usr/local/etc/config/hap-homematic
;-)
lg Richard

**Comment by thkl** [comment]
den Ordner lege ich im Addon an .. ich weiss nicht mehr warum ;)

**Comment by roe1974** [comment]
alles klar :-P :-)

**Comment by thkl** [comment]
ich mach das mal hier zu
