### ISSUE TITLE
Unterstützung HM-Sen-Wa-Od

### ISSUE THREAD

**Issue by zivi78** [thkl/hap-homematic#180]
Ich bin begeistert von diesem Plugin Ich würde mir wünschen den Füllstandssensor auch benutzen zu können. Sehen Sie eine Chance?

Ich kann mir vorstellen dass HomeKit hier zu keine Darstellungsmöglichkeit hat. Könnte mir aber auch vorstellen, dass der Füllstand prozentual wie das duty Seikel dargestellt werden könnte.￼￼

**Comment by thkl** [comment]
Bitte mal auf der WebUi des Addons unter Internes / Hilfe das Template File für das Gerät erzeugen und hier anhängen. Wie das geht steht in der Hilfefunktionen.

**Comment by zivi78** [comment]
Hier das Template File des Gerätes

{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HM-Sen-Wa-Od",
      "address": "3951871708ABCD",
      "type": "HM-Sen-Wa-Od",
      "channels": [
        {
          "id": 1001,
          "name": "3951871708ABCD:1",
          "intf": 0,
          "address": "3951871708ABCD:1",
          "type": "CAPACITIVE_FILLING_LEVEL_SENSOR",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by zivi78** [comment]
Habe gesehen, dass hier bereits was entwickelt wurde. Mega! Ist dies schon im Plugin enthalten? Benutze Version 0.0.53. muss ich Updaten?

**Comment by thkl** [comment]
Nein solange das WebUI nichts vermeldet, gibt es keine neue Version.

**Comment by zivi78** [comment]
Hallo Thomas. Ich habe das Gerät nun verbinden können.

Allerdings zeigt er nur 0% an. Laut CCU sollten aber 57% angezeigt werden.

![image](https://user-images.githubusercontent.com/56314723/95715271-dafc4f80-0c69-11eb-86c0-7386471c2014.png)

**Comment by zivi78** [comment]
Kannst du bitte kurz Rückmeldung geben, warum 0% angegeben wird anstatt der Prozentzahl, die in der CCU am Gerät vorhanden ist.

**Comment by thkl** [comment]
Das kann ich noch nicht sagen. Ich muss da noch mal die Doku zu dem Ding fragen. Ggf liefert die CCU 0-1 und HK möchte 0-100 und es fehlt eine Umrechnung.

**Comment by zivi78** [comment]
Ich habe bei Blog.Bubis.de diesen Code gefunden. Vielleicht kannst du ja damit was anfangen?

";
$mysqluser="";
$mysqlpwd="";
$connection=mysql_connect($mysqlhost, $mysqluser, $mysqlpwd) or die ("Verbindungsversuch fehlgeschlagen");
$mysqldb="";
mysql_select_db($mysqldb,$connection) or die("Konnte die Datenbank nicht waehlen.");
$sql = "INSERT INTO zisterne (timestamp,fuellstand) VALUES (CURRENT_TIMESTAMP,$zustand[1])";
$query = mysql_query($sql) or die("Anfrage 1 nicht erfolgreich");
?&gt;

**Comment by zivi78** [comment]
Hallo Thomas!

Könntest du bitte dieses Thema nochmals wegen der 0% Anzeige anschauen. Ich muss Frau von dem App überzeugen und solange immer 0% angezeigt wird, setzt sie dies nicht ein.

Vielen Dank. Bald ist diese jetzt voll, dann kann ich dir Rückmeldung geben ob dann 1 angezeigt wird.

**Comment by thkl** [comment]
Ok da brauch ich bissel Input wegen den Daten die aus der CCU kommen. Ich denk mir mal was aus

**Comment by thkl** [comment]
Kannst Du mal bitte folgendes im Script Testen  Screen auf dem CCU UI ausführen (der Script Testen ist in den Programmen)

```
object o = dom.GetObject('BidCos-RF.12345:1.LEVEL');
if (o) { 
  Write(o.State()); 
} else {
  Write('not found');
}
```

wobei 12345 die Seriennummer des Sensors ist  (das :1 muss bleiben das ist der Channel 1)

Und das Ergebnis hier rein kippen + dem was das WebUI gerade als Füllstand in % angibt

**Comment by zivi78** [comment]
Mit folgendem Code habe ich den Wert auslesen können. Auch in der richtigen Größe.

![image](https://user-images.githubusercontent.com/56314723/97799617-7fe9c700-1c2f-11eb-8d8f-de4d4de40089.jpeg)

![image](https://user-images.githubusercontent.com/56314723/97799622-837d4e00-1c2f-11eb-80f6-fe1c899f356b.jpeg)

Hoffe das du damit den richtigen Wert in das PlugIn bekommst und die Prozentzahl angezeigt wird. 

Viel Erfolg!

**Comment by thkl** [comment]
na da haben wir es doch schon .. der Datenpunkt heisst FILLING_LEVEL und nicht LEVEL wie ich angenommen hatte

**Comment by zivi78** [comment]
Prima. Freue mich dann auf das nächste Update in dem dies dann erscheint

**Comment by zivi78** [comment]
Und die Funktion .Value() anstatt .State() nutzen.

**Comment by thkl** [comment]
Ja, der CCU Manager nutzt Value zur Abfrage der Werte ; um nicht jedes mal einen Event auf der Funkschnittstelle zu triggern und den DC hochzutreiben,

**Comment by zivi78** [comment]
0.0.56 installiert. Wert wird in der homeApp dargestellt. Vielen Dank nochmals für deine perfekte Arbeit.
