### ISSUE TITLE
HAP funktioniert nach Update von RaspberryMatic nicht mehr (bzw. danach ist ein Fehler aufgefallen)

### ISSUE THREAD

**Issue by LevelOne2k** [thkl/hap-homematic#181]
Hallo @thkl ,

ich habe auf die aktuelle RaspberryMatic Version geupdatet bzw. habe die SD-Karte mit der aktuellen Version neu geflasht und dann mein zuvor erstelltes Backup wieder eingespielt.

Ich wollte HAP über die Systemerweiterungen öffnen, ging nicht „Seite kann nicht geöffnet werden, da Safari keine Verbindung zum Server aufbauen kann“. Also dachte ich mir, ich muss HAP erneut installieren, sozusagen drüber bügeln so wie es bei vielen anderen Addons nach einem einspielen eines Backups auch der Fall ist, dies habe ich dann auch getan und HAP lief wieder wie vorher. Dann habe ich gestern ein neues Gerät (HmIP-SWD ) bekommen und an der CCU angemeldet und dann wollte ich dieses auch in HAP einbinden, es wurde in HAP jedoch nicht gefunden also wollte ich HAP neu starten, seitem funktioniert HAP wieder nicht mehr, es kommt wieder die Meldung „Seite kann nicht geöffnet werden, da Safari keine Verbindung zum Server aufbauen kann“ Dann habe ich HAP wieder erneut „drüber gebügelt“ aber die CCU hat danach keinen reboot gemacht (ich habe lange gewartet) dann habe ich den reboot der CCU selber ausgeführt, und danach funktionierte HAP wieder.

Dann habe ich versucht HAP über internes wieder neu zu starten, aber das klappt wohl nicht. Die Ansicht rödelt immer weiter
![09A1151F-8077-432D-86E1-959620A4877F](https://user-images.githubusercontent.com/25386824/94132780-115f5f80-fe60-11ea-939f-4a9682f61756.jpeg)
Dann schließe ich die Meldung oben rechts über das x aber HAP läuft dann auch nicht mehr, es kommt wieder die Meldung „Seite kann nicht geöffnet werden, da Safari keine Verbindung zum Server aufbauen kann“ erst wenn ich die CCU dann neu starte, funktioniert HAP wieder.

PS: Das ist das neue Gerät

![D48D2A58-F684-4F0E-A815-17C7BF9A9066](https://user-images.githubusercontent.com/25386824/94134011-bc244d80-fe61-11ea-8b9f-950077692544.jpeg)

```{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HmIP-SWD",
      "address": "5704833150ABCD",
      "type": "HmIP-SWD",
      "channels": [
        {
          "id": 1001,
          "name": "5704833150ABCD:0",
          "intf": 0,
          "address": "5704833150ABCD:0",
          "type": "MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "5704833150ABCD:1",
          "intf": 0,
          "address": "5704833150ABCD:1",
          "type": "WATER_DETECTION_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1003,
          "name": "5704833150ABCD:2",
          "intf": 0,
          "address": "5704833150ABCD:2",
          "type": "ALARM_COND_SWITCH_TRANSMITTER",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by timwegenerDE** [comment]
Ich habe (leider) auch auf RaspberryMatic 3.53.30.20200919 geupdatet. Das Update hat sich leider mittendrin verabschiedet und mir schon mal meine ganze Config zerschossen; Also neu aufgesetzt. Bereits ohne Geräte in Homematic habe ich das Problem, dass sich HAP-Homematic nach dem Neustart des Add-Ons verabschiedet. Erst nach mehrmaligem Neustart des Add-Ons und oder nach einem Neustart der CCU3 kommt HAP-Homematic wieder. Hier war mir noch aufgefallen, dass bei den Special Devices das Hinzufügen des Garagentors nicht möglich war, da ich entweder keinen Channel auswählen kann oder keinen Datapoint angezeigt bekomme...

Ich bin total ratlos; Denke ich muss erstmal downgraden, bevor ich jetzt für Tage mein Garagentor nicht mehr aufbekomme.

**Comment by timwegenerDE** [comment]
Downgrade hat sich dann erledigt, nachdem mein Backup scheinbar korrupt ist. Bin dann jetzt wieder auf 3.53.30.20200919. Aber auch nach Neuinstallation bleibt HAP-Homematic in einem seltsamen Zustand. Manchmal komme ich auf die Web-Oberfläche, spätestens nach einem Neustart des Add-Ons nicht mehr (Seite nicht erreichbar). Die Meldung beim Neustarten sieht auch komisch aus.
<img width="801" alt="Bildschirmfoto 2020-09-26 um 11 48 54" src="https://user-images.githubusercontent.com/56134910/94337940-8496dc00-ffee-11ea-8562-f8a02390286a.png">

Zeitweise hatte ich heute auch das Gefühl das HAP die CCU runterzieht und die Oberfläche nicht mehr bedienbar ist.

**Comment by thkl** [comment]
Das klingt alles ziemlich wild. Was sagt denn /var/log/hap-homematic.log

Der Daemon schreibt sich zwar in das Monitoring der CCU und wird von dessen Watchdog neu gestartet wenn er crasht. Aber sollte das innerhalb von 10 Minuten mehr als 5x passieren, dann wird das Monitoring ausgeschalten.

**Comment by timwegenerDE** [comment]
Hin Thomas,

Log ist langweilig. Er sagt noch freundlich "bye" und dann passiert nichts mehr.

`Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] ---- launching ----
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] Welcome to HAP Homematic. Use your HomeMatic devices in HomeKit
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] (c) 2020 by @thkl - https://github.com/thkl/hap-homematic
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [Server] settings loading ...
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [Server] config loading completed; start building servicetable
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [Server] service loading completed; publishing services
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [Server] settings loading is done ; continuing init
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [Server] Using config from /usr/local/etc/config/addons/hap-homematic/persist
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] Spawning configuration service with PID X
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [Server] current restart count is  1
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [Server] Checking rega connection
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] check Rega is alive
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [Server] Rega is alive going ahead
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [Server] continueInitialization
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] loading object database for devices from /usr/local/etc/config/addons/hap-homematic/devices.json
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] object database loaded 50 objects found
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] device database loaded 50 devices found
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] loading object database for variables from /usr/local/etc/config/addons/hap-homematic/variables.json
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] object database loaded 11 objects found
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] variable database loaded 11 variables found
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] loading object database for programs from /usr/local/etc/config/addons/hap-homematic/programs.json
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] object database loaded 4 objects found
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] program database loaded 4 programs found
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] loading object database for rooms from /usr/local/etc/config/addons/hap-homematic/rooms.json
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] object database loaded 11 objects found
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] room database loaded 11 rooms found
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [CCU] disable Monitoring
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] warn - [HAP Server] [Server] no channels to map in configuration found
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [Server] powering up bridge : HomeMatic default with id X , userid X and pinCode  XXX-XX-XXX
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_default PinCode is XXX-XX-XXX
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [Server] 49 compatible devices found
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_default (X) is running on port 9877.
[Mon Sep 28 2020 18:40:26 GMT+0200 (CEST)] info - [HAP Server] [RPC] server for all interfaces is listening on port 9875.
[Mon Sep 28 2020 18:46:19 GMT+0200 (CEST)] info - [HAP Server] [Server] shutting down all homekit instances
[Mon Sep 28 2020 18:46:19 GMT+0200 (CEST)] info - [HAP Server] [Server] shutting down Homekit bridge HomeMatic default
[Mon Sep 28 2020 18:46:19 GMT+0200 (CEST)] info - [HAP Server] [Server] bye
`

Das starten mit node `/usr/local/addons/hap-homematic/node_modules/hap-homematic/index.js` und auch mit `/etc/config/rc.d/hap-homematic start` funktioniert dagegen tadellos.

Lediglich eine gelbe Message bei mir:
[Server] no channels to map in configuration found

**Comment by timwegenerDE** [comment]
Den hätte ich noch:

**Comment by thkl** [comment]
die warnung ist nicht wichtig ;) aber ich habe das Problem gefunden. Ich habe den rc.d launcher aktualisiert und angepasst

https://github.com/thkl/hap-homematic/blob/master/addon_installer/rc.d/hap-homematic

der kommt nach /etc/config/rc.de ... bitte mal testen

**Comment by timwegenerDE** [comment]
Wie mach ich das am besten? Bin mit dem vi so gar nicht fit...

**Comment by thkl** [comment]
File https://github.com/thkl/hap-homematic/raw/master/addon_installer/rc.d/hap-homematic runterladen und per FTP drüber kopieren

**Comment by thkl** [comment]
ich hab ein neues RM Addon zusammengebaut . Das enthält den neuen Launcher https://github.com/thkl/hap-homematic/releases/download/0.0.12/hap-homematic-0.0.12.tar.gz

**Comment by timwegenerDE** [comment]
Funktioniert wunderbar!

Danke Thomas!

**Comment by thkl** [comment]
\o/

**Comment by LevelOne2k** [comment]
Danke für die Arbeit an euch beiden. Konnte leider nicht früher reagieren. @thkl hast du auch das von Mormonen gepostete Gerät gesehen?
