### ISSUE TITLE
Device not supported yet?

### ISSUE THREAD

**Issue by PhilipKyleBoone** [thkl/hap-homematic#182]
This is a really awesome plug-in! Thanks for developing it!

I have two Eltakos (HM Device ID: HM-LC-Sw1-DR). They dont show up in the device list, so I guess they aren't supported yet. Any idea when tehy might be?

Thanks

**Comment by thkl** [comment]
May u please go to the WebUi Internals / Help m ... paste the Serial Number of your device and attache the downloaded template here. So I am able to look into your issue.
