### ISSUE TITLE
Nach Installation erscheint kein HomeKit Button

### ISSUE THREAD

**Issue by Schazo** [thkl/hap-homematic#183]
Habe das Plugin wie in der Anleitung beschrieben auf meiner CCU3 installiert.

Allerdings erscheint nach der Installation kein HomeKit Button. Bei Zusatzsoftware sehe ich aber, dass das Plugin installiert worden ist. Wenn ich auf Einstellen gehe, werde ich umgeleitet, aber die Seite lädt nicht.

Kann mir da jemand helfen?

**Comment by dkrizic** [comment]
Check mal die Firewall-Einstellungen. Die entsprechenden Ports müssen offen sein, testweise kann man auch die Firewall komplett aufmachen.

**Comment by Schazo** [comment]
Hab schon die Ports geöffnet, bzw danach mal alle freigegeben und das Plug-In komplett neu installiert. Allerdings exakt das gleiche Verhalten wie vorher.. :(

**Comment by thkl** [comment]
Dann geht irgend was bei der Installation schief.  Der Installer schreibt ein log nach /var/log ... das ist aber eine RamDisk und nach einem Reboot der CCU wieder weg. Deswegen folgende Vorgehensweise:

Addon installieren. 
CCU muss rebooten
2min warten (beim Neustart versucht der Installer das npm File nachzuladen)
in /var/log nach dem logfile schauen. 


Achja die CCU braucht zumindest für den Reboot nach dem AddOn Einspielen einmal kurz Inet um das npm Paket zu laden.

**Comment by Schazo** [comment]
Dann ist vermutlich das fehlende Internet das Problem :) wir sind grade erst eingezogen und bekommen erst am Donnerstag Internet..

**Comment by thkl** [comment]
Ja das AddOn ist nur der Installer. Es legt die Pfade in /usr/local/addons an und führt ein npm install hap-homematic aus.
