### ISSUE TITLE
HM-CC-TC not supported fully?

### ISSUE THREAD

**Issue by townlema** [thkl/hap-homematic#185]
Wonderful piece of software!  I have a problem with the above Thermostat where only channel 1 is recognised as a WEATHER channel so yes I can see the Humidity and Temp in Homekit but cannot be used as a thermostat.  Device file looks like the following so is there anything I can do to get this working?

Seems like we need a new channel service based on this one:
https://github.com/thkl/homebridge-homematic/blob/master/ChannelServices/HomeMaticHomeKitThermostatService.js

Device Section for Thermostat:
      "id": 1461,                         
      "name": "HM-CC-TC IEQ0106500",      
      "address": "IEQ0106500",            
      "type": "HM-CC-TC",                 
      "channels": [                       
        {                                 
          "id": 1481,                     
          "name": "HM-CC-TC IEQ0106500:1",
          "intf": 1010,                   
          "address": "IEQ0106500:1",      
          "type": "WEATHER",                 
          "access": 255                      
        },                                   
        {                                    
          "id": 1484,                        
          "name": "HM-CC-TC IEQ0106500:2",   
          "intf": 1010,                      
          "address": "IEQ0106500:2",         
          "type": "CLIMATECONTROL_REGULATOR",
          "access": 255                      
        },                                   
        {                                    
          "id": 1489,                        
          "name": "HM-CC-TC IEQ0106500:3",   
          "intf": 1010,                      
          "address": "IEQ0106500:3",         
          "type": "WINDOW_SWITCH_RECEIVER",  
          "access": 255                      
        }                                    
      ]                                      
    },

**Comment by thkl** [comment]
ok, i've added the device to the thermostat service. it will be available for the next version

**Comment by townlema** [comment]
I did a quick test and it looks good.  Many thanks for the quick turnaround.

**Comment by thkl** [comment]
i cannot believe that anybody is still using these old thermostats but here we are 😎
