### ISSUE TITLE
Mobiler Zugriff 

### ISSUE THREAD

**Issue by Arne1989** [thkl/hap-homematic#186]
Hallo, ist es möglich das Ganze über das mobile netz zu erreichen? 

Im wlan klappt bereits alles. 

Danke im Voraus für eine Hilfestellung

**Comment by thkl** [comment]
HomeKit selber ist via Mobil erreichbar wenn mindestens ein AppleTV HomePod oder IPad im eignen WLAN läuft. Dann läuft die HoemKit Bedienung über iCloud. 


Die WebOberfläche von HapHomematic Dämon könnte man über gängige VPN Lösungen mobil erreichbar machen. Das ist aber beides hier out of Scope.

**Comment by samhomatic** [comment]
Zur Information: 
habe mittels Synology eine VPN-Lösung(OpenVPN)  aufgebaut welche auch funktioniert (getestet mit PocketControl und anderen Systemen) , jedoch dürfte HomeKit das ignorieren und unbedingt ein WLAN benötigen.

**Comment by JensBonse** [comment]
HomeKit benötigt kein WLAN. Das iPAD benötigt WLAN um mit dem Heimnetz verbunden zu sein, um dann als Bridge zu Apple zu fungieren.
Am besten sind meiner Erfahrung nach Apple TVs die per LAN Kabel mit dem Netzwerk verbunden sind.
