### ISSUE TITLE
Anzeige der Relativen Luftfeuchtigkeit von Wandthermostaten

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#188]
Hallo,

Anzeige der Relativen Luftfeuchtigkeit der Wandthermostate.
Damit diese als Trigger verwendet werden können für z.B. eine Lüftungsempfehlung.
(>70%RLF = Die Feuchtigkeit im Badezimmer ist hoch, bitte Lüften.)

Gerne können sie  auch als zusätzliches Gerät angezeigt werden.

Ich habe 2 verschiedene meiner Wandthermostate angehangen (es gibt noch mehr Versionen)
[HmIP-WTH-2.txt](https://github.com/thkl/hap-homematic/files/5314648/HmIP-WTH-2.txt)
[HmIP-eTRV-B.txt](https://github.com/thkl/hap-homematic/files/5314649/HmIP-eTRV-B.txt)

Vielen Dank schonmal im voraus.
Gruß meistermolli

**Comment by gerd2005** [comment]
Hallo,

das ist auch gerade meine Frage... Wie kann ich mir die Luftfeuchtigkeit in HomeKit anzeigen lassen?
Ich habe die HmIP-BWTH.

Vielen Dank.

**Comment by meistermolli** [comment]
Hi,
wenn du auf das Gerät / Einstellungen gehst, dann wird die Luftfeutchtigkeit angezeigt.
Diesen Wert hätte ich gerne als eigenes "Gerät" in der Home app angezeigt. Damit man Sie dauerhaft sieht und als "Trigger" verwenden kann. ;-)

**Comment by thkl** [comment]
Es gibt in HomeKit Feuchtigkeitssensoren .. da könnte ich einen für WEATHER Channels bauen

**Comment by thkl** [comment]
man kann in Eve das aber doch auch für ein Thermostat einstellen:

![IMG_BBBDDDB0D065-1](https://user-images.githubusercontent.com/884355/96633111-f1b13f00-1318-11eb-8e38-8c8690939578.jpeg)

**Comment by meistermolli** [comment]
Hm .. ich glaube ich muss mir auch mal die EVE app anschauen. Benutze grade alles über Homekit, da ich die verschiedenen Apps nicht mehr nutzen möchte. Und habe schon mehrfach von der Eve App gelesen.

Kann ich es dann auch in Homekit szenen einbinden?

**Comment by thkl** [comment]
Eve ist ein HomeKit Controller , wie die Apple Home App auch, also alles was in HomeKit eingebunden ist geht auch mit Eve zu managen.  

HomeKit = Datenbank+Framework für SmartHome Geräte

HomeKitController = Client App :)


Du kannst die Geräte mit beliebigen HomeKit Controllern bedienen. Die Zustände syncen auf alle Apps.  Die einen können mehr die anderen weniger 😎

**Comment by meistermolli** [comment]
Ja .. meine Frau freut sich, wenn ich wieder mit einer neuen app gelaufen komme ;-).
Würde die feuchtigkeit nach wie vor gern im HomeKit sehen und mit ihr arbeiten. Schaue mir die Eve app aber mal an.
An die Home App und Bedienung habe ich Sie gewöhnt und die nutzt Sie zum gluck jetzt auch.
Merci

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/96744948-dbad8800-13c5-11eb-8bcd-f81c7e9977fb.jpeg)

**Comment by gerd2005** [comment]
> Hi,
> wenn du auf das Gerät / Einstellungen gehst, dann wird die Luftfeutchtigkeit angezeigt.
> Diesen Wert hätte ich gerne als eigenes "Gerät" in der Home app angezeigt. Damit man Sie dauerhaft sieht und als "Trigger" verwenden kann. ;-)

Meinst du diese Einstellungen? Hier wird mir keine Luftfeuchtigkeit angezeigt....
![34EAA645-BC4E-4D25-A5BE-54603B37878E](https://user-images.githubusercontent.com/72799068/96837080-24a52100-1446-11eb-84f4-5a4251a0e395.jpeg)

**Comment by meistermolli** [comment]
Was ist das für ein Thermostat? Die können ja nicht alle die RLF anzeigen!
Schicke gleich mal ein bild von meinem. Bin grade alles neu am einrichten.

**Comment by gerd2005** [comment]
Hallo,

ja doch, die können das. Ich habe die HmIP-BWTH. Wie gesagt, wenn ich Siri nach der LF frage kommt auch eine Antwort.

**Comment by gerd2005** [comment]
Bitte auch für den HmIP-STHD Umsetzen, falls noch nicht geschehen. Danke :-)

**Comment by meistermolli** [comment]
Also in dem BWTH / WTH steht es so drin wie in dem Bild.
Achtung: bei mit angezeigten Boost Modus sind 2 Geräte gruppiert. Daher muss man noch eine ebene tiefer gehen. 
Ein Grund mehr für mich, dass ich die rlf mit im Raum als gerät ablesen kann (auch im Status)

Kann ich mir davon nicht auch eine Variable setzen? Und mit dieser dann einen Grenzwert definieren?

Gruß meistermolli 

![CD6C24A5-F688-450A-8099-85BBBD461A44](https://user-images.githubusercontent.com/55836556/97041098-44843400-156f-11eb-9439-3e8d7733cac4.png)

**Comment by meistermolli** [comment]
Hi @thkl , 
habe mir gerade die Humidity Sensoren angeschaut die du in der neuen Version 0.0.55 eingepflegt hast.

Ich kann ein Homematic Gerät aber nur einmal in HAP Homematic hinzufügen (hier steht dann in der Auswahl: schon vorhanden), also entweder als Thermostat oder als Humidity sensor.

- Kann man das Gerät auch doppelt anlegen?
1x WTH als Thermostat
1x den selben WTH als Feuchtigkeitssensor

Wenn ich eine Variable in Hap Homematic anlege mit dem Wert der Relativen Luftfeuchtigkeit, dann wird diese schonmal klein oben im Status des Raumes angezeigt.
Mit dieser Variablen kann man aber in einer Szene nicht arbeiten, da sie nicht in der HomeKit Geräteliste auftauchen.
Das geht nur wenn ich es als Humidity Gerät in HAP Homematic angelegt habe.

Gruß meistermolli

**Comment by thkl** [comment]
Ich hab es glaube ich schon irgendwo anders hier geschrieben; jeder Kanal eines CCU Gerätes kann genau auf ein HomeKit Gerät gemappt werden.

**Comment by meistermolli** [comment]
mist ... ok ... irgendwas kriege ich da sicher hin ;-) Danke dir!!!

**Comment by gerd2005** [comment]
@thkl du schreibst, dass jeder Kanal eines CCU Geräts nur auf ein HomeKitGerät gemappt werden kann. Wie macht denn NodeRed das? Ich experimentiere mit dem PlugIn aktuell etwas herum (wobei ich deins wesentlich benutzerfreundlicher finde). 
Jedenfalls lassen sich hier bspw. Für meine Thermostate mehrere HomeKit-Geräte anlegen.
![D3D68AE1-8EF0-4DB3-A2B5-927946A3E656](https://user-images.githubusercontent.com/72799068/97802954-22fa0b00-1c47-11eb-8b9e-f03e2a60e126.png)

**Comment by meistermolli** [comment]
Habe in der Homematic CCU Variablen angelegt mit der RLF des entsprechenden Raumes. Diese Variable habe ich dem Raum in Homekit über HAP Homematic hinzugefügt. So wird die RLF oben im Status für den Raum angezeigt.

In der EVE App Zeigt das Gerät direkt auch die Kanäle für die RLF an. Die Homekit App kann dies "Leider" einfach nicht.

Vielleicht gibt es hierzu ja irgendwann mal ein Apple Update dazu.

zudem hat thkl ja eine neue Geräteklasse angelegt, mit der man "nur" die RLF der Thermostate abgreifen und als Gerät in Homekit anzeigen kann.

Merci für die Hilfe.

**Comment by han-gru** [comment]
Auch wenn hier schon geschlossen wurde muss ich nochmal einhaken. Ich bekomme es einfach nicht hin, das die aktuelle relative Luftfeuchtigkeit von der ccu an hap übermittelt wird. Wenn ich eine systemvariable in der ccu anlege, kann ich das wth als Kanal hinzufügen. Die systemvariable kann ich dann in hap auswählen, allerdings kommt in Apple home App nur 0% an. Was mach ich falsch?

**Comment by meistermolli** [comment]
Hi,

Ich habe den Variablentyp Zahl und den Kanal :1 vom WTH-2 gewählt. 

In HAP dann so angelegt:
![D5594723-79C5-45A3-BC96-86564A2EFC3E](https://user-images.githubusercontent.com/55836556/103474679-9b478e80-4da6-11eb-88ce-0062d14f15ea.jpeg)

und dann muss auf der HAP - Variablen Seite noch der hier vergeben werden. Hier habe ich einen freien Virtuellen Taster aus der CCU Ausgewählt.

![Uploading 467BF855-83FE-4F47-B014-246D7132D1A4.png…]()

Gruß

**Comment by han-gru** [comment]
Vielen Dank für deine Anleitung. Leider hab ich es auf diese Weise nicht hinbekommen. 
Ich habe allerdings gestern Abend nochmal ein bisschen probiert und im hap ist mir aufgefallen, dass ich in den Geräten sowohl das wth als auch einen separaten Temperatur-Regler aufgeführt habe. Somit habe ich nun das wth zur Anzeige der Luftfeuchtigkeit eingerichtet und den Temperatur-Regler zur Einstellung der Temperatur. Diese Zegt mir auch die aktuelle Raumtemperatur an. Zustandekommt dir sicherlich, da ich mit heizungsgruppen in der ccu arbeite.
