### ISSUE TITLE
HmIP-SWO-B Wettersensor nicht erreichbar ... neue RM/neue HAP

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#189]
Hallo zusammen
Ich habe seit der neuen RM und der aktuellen HAP das Problem unter iOS 14, dass meine Wetterstation und Apple Home herumzickt ... sie ist nicht erreichbar und zieht mir auch den ganzen Raum auf nicht erreichbar ... wenn ich alle Geräte durchklicke geht alles bis auf die Helligkeit des Wettersensors ... noch wer das Problem ?
lg Richard

**Comment by roe1974** [comment]
Hier das devicefile...
[HmIP-SWO-B.json.txt](https://github.com/thkl/hap-homematic/files/5321303/HmIP-SWO-B.json.txt)

**Comment by mano87** [comment]
Kann ich bestätigen. Der Wettersensor (HmIP-SWO-PR) lässt sich im HAP freigeben und kommt auch unter iOS 14 an, jedoch ohne Funktion mit dem Hinweis "Gerät wird nicht unterstützt"

**Comment by luismoeller** [comment]
Des Weiteren bleibt die Temperatur wenn der Wettersensor als HomeMaticThermometerAccessory eingebunden ist immer bei 0,0 während die Luftfeuchtigkeit funktioniert. Würde mich sehr über eine Lösung freuen.

**Comment by mano87** [comment]
Es hat sich durchaus etwas getan. Auch ich konnte meinen HmIP-SWO-PR nun als HomeMaticThermometerAccessory einbinden. Allerdings wird auch bei mir nur die Luftfeuchtigkeit einwandfrei übertragen. Die Temperatur liegt bei mir auch bei 0,0 Grad :-)

Das wäre echt traumhaft, wenn das bald klappt ...

**Comment by luismoeller** [comment]
Ich habe einen Workaround gebastelt. Hierfür habe ich ein kleines Skript geschrieben, das bei Änderung der Temperatur/der Luftfeuchtigkeit die beiden Werte in zwei Systemvariablen speichert. Diese Variablen habe ich dann jeweils in HAP Homematic als Temperatur- und Luftfeuchtigkeitssensor eingebunden. Funktioniert einwandfrei.

**Comment by mano87** [comment]
Vielleicht kann @thkl etwas dazu sagen :-)

**Comment by roe1974** [comment]
sollte mit 0.0.58 eigentlich gehen ....
![image](https://user-images.githubusercontent.com/30420568/105612699-e1987800-5dbd-11eb-8387-656ceeab3782.png)

**Comment by luismoeller** [comment]
Bei mir geht die Wetterstation jetzt ohne Probleme. Top. Danke.

**Comment by mano87** [comment]
![D26A3248-3FD4-4877-887D-2BD24709A4E0](https://user-images.githubusercontent.com/25568300/105627199-97eb7400-5e35-11eb-88b9-648fe7381f74.jpeg)

Auch nach dem Update ist bei mir keine Änderung zu sehen... woran kann das liegen?

**Comment by DanJoeHa** [comment]
Hi,

kann das Phänomen von @mano87 (leider) bestätigen:

![04F42753-4F03-4514-9788-469452C41381](https://user-images.githubusercontent.com/5477947/107850724-c9d47280-6e04-11eb-918e-1ba9b8ff89d2.jpeg)
 
Raspberrymatic 3.55.5.20201226
HomeKit Homematic 0.0.14
HmIP-SWO-PL 1.0.18

**Comment by DanJoeHa** [comment]
Konnte das Problem aufgrund https://github.com/thkl/hap-homematic/discussions/385 lösen. Evtl. auch für dich interessant @mano87

**Comment by mano87** [comment]
@DanJoeHa Danke, damit sieht es jetzt wirklich besser aus :-)

Service = HomematicWeatherStationAccessory und in den Einstellungen "Apple Home-App kompatibel" aktivieren.

Hierdurch habe ich nun auch die Helligkeit in Lux. Wobei hier noch "Lampe" steht ;-) Damit könnte dieses Ticket vermutlich auch zu...

**Comment by ChrWi** [comment]
Mit Bezug auf #385 und #331 schließe ich das Issue
