### ISSUE TITLE
Fehler: "Name in Homekit" ... Name darf nicht doppelt sein....obwohl anderer Raum

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#19]
Hallo Thomas

Ich HK kann ja ein Name eines Gerätes öfter vorkommen. Siri/HK unterscheidet das dann nach dem Raum. zB "LIcht" gibt es im Wonhzimmer, Balkon etc.
Wenn man in deinem Plug-In den "Name in Homekit" öftermals gleich vergibt, kommt es zu problemen.
Die Geräte werden nicht hinzugefügt.

lg Richard

**Comment by thkl** [comment]
![IMG_3418](https://user-images.githubusercontent.com/884355/80405381-d3670b00-88c2-11ea-8f11-1e9e5d21698b.jpg)
![IMG_3417](https://user-images.githubusercontent.com/884355/80405394-d7932880-88c2-11ea-976f-7db53401ccce.jpg)


Hmm geht doch ? Sogar als 2 verschiedene Geräte

**Comment by roe1974** [comment]
Ok ... teste ich nochmal ....

**Comment by roe1974** [comment]
Ok ... kann ich nicht mehr nachvollziehen .... denke zu "wild" herumgeklickt :-P
Ich mach mal zu hier
lg Richard
