### ISSUE TITLE
Lauffähige Kombination aus HMIP-SAM und HMIP-WGC als Garagentoröffner ?

### ISSUE THREAD

**Issue by Icke-NOH** [thkl/hap-homematic#191]
Moinsen,

lese schon einige Tage hier mit und musste mich nun doch mal anmelden um meine Frage loszuwerden.
Hat es jemand geschafft aus einem HMIP-WGC und HMIP-SAM einen funktionierenden Garagentoröffner in HomeKit mit HAP zu erstellen? Wäre für die Konfiguration dankbar. weil maximal AUF habe ich hinbekommen, allerdings meldet der SAM auch immer auf, hab den noch nie in zustand ZU versetzen können (in der CCU zeigt er schon an ob wagerecht oder geneigt) und sobald man noch zusätzlich in der config etwas einstellt zeigt HomeKit an wird geöffnet und hängt sich weg..Hardwareseitig nutze ich eine CCU3 mit dem neuesten Rasperrymatic Release.

![Bildschirmfoto 2020-10-03 um 05 23 07](https://user-images.githubusercontent.com/72289306/94982239-4e4ee480-0539-11eb-8c9b-0aaea7183926.png)
![Bildschirmfoto 2020-10-03 um 05 26 55](https://user-images.githubusercontent.com/72289306/94982241-5018a800-0539-11eb-9b94-0c3c399c0918.png)
![Bildschirmfoto 2020-10-03 um 05 27 26](https://user-images.githubusercontent.com/72289306/94982242-50b13e80-0539-11eb-8f99-f87b68454ed2.png)
![Bildschirmfoto 2020-10-03 um 05 28 18](https://user-images.githubusercontent.com/72289306/94982243-5149d500-0539-11eb-908c-90631c2023e9.png)
![Bildschirmfoto 2020-10-03 um 05 46 19](https://user-images.githubusercontent.com/72289306/94982562-cdddb300-053b-11eb-9edb-4957c67e0dd9.png)

**Comment by thkl** [comment]
Es funktioniert nicht, wenn der eine Sensor in beiden Zeilen (für Öffnen und Schließen) eingetragen ist.  Wirf ihn bei "Adresse des offen Sensors" wieder raus. 

Das Tor wird dann im "Ein Sensor Mode" betrieben. Es gilt als Offen wenn der Sensor den Wert hat, der im Status Feld steht. Und als Geschlossen wenn der Wert ein anderer ist.  



Und das gleiche für den Aktor. Er kann beim Schließen Aktor wieder raus. Dann wird zum Öffnen und Schließen der gleiche Aktor angesteuert.

**Comment by Icke-NOH** [comment]
Habs nun umgestellt...aber der sensor sagt immer Garage ist auf. Und Garage wird auch nur geöffnet...nicht geschlossen, hab gemerkt das man den Schalter per Hand drückt er den erst freigibt, weil ich mit der normalen Fernbedienung das Tor auch nicht mehr zu bekommen habe...aber die anzeige ist immer falsch...nie geschlossen.
![Bildschirmfoto 2020-10-03 um 10 01 23](https://user-images.githubusercontent.com/72289306/94986608-5f5f1c00-0560-11eb-9e33-034690ea35d8.png)
![Bildschirmfoto 2020-10-03 um 10 03 17](https://user-images.githubusercontent.com/72289306/94986610-60904900-0560-11eb-800b-6a9f28c6b4b9.png)
![Bildschirmfoto 2020-10-03 um 10 03 30](https://user-images.githubusercontent.com/72289306/94986611-60904900-0560-11eb-9021-ccdb4df2bcff.png)
![Bildschirmfoto 2020-10-03 um 10 03 40](https://user-images.githubusercontent.com/72289306/94986612-60904900-0560-11eb-8187-d60d203eb34a.png)
![Bildschirmfoto 2020-10-03 um 10 04 01](https://user-images.githubusercontent.com/72289306/94986613-6128df80-0560-11eb-803d-a97fcfb2d753.png)

**Comment by Icke-NOH** [comment]
hab das problem auch mit der funkfernbedinung, da hatte ich so nen Programm für gemacht, was derzeit aus ist.

![Bildschirmfoto 2020-10-03 um 10 09 25](https://user-images.githubusercontent.com/72289306/94986645-a51be480-0560-11eb-9d55-36566382d962.png)

**Comment by thkl** [comment]
Beim HmIP-SAM muss aber der MOTION Datenpunkt als Sensor benutzt werden. In Deinem Fall ist der Eintrag 
HmIP-RF.000F1BE98BE313:1.MOTION

**Comment by Icke-NOH** [comment]
DAS WARS :) Dankeeeeee

**Comment by sailor79** [comment]
> DAS WARS :) Dankeeeeee

Hallo Icke-NOH,
Könntest Du bitte Bilder der nun funktionieren Kombination (Gerät bearbeiten, Status etc.) hier posten, ich würde das gerne ins Wiki mit aufnehmen. Habe selber aber die entsprechende Hardware nicht. Danke

**Comment by Icke-NOH** [comment]
Moin, klar:

Also ich hab die 4 entsprechenden Einträge mal zusammengeknipst, damit funktioniert es. kann sein das ich noch einen Fehler drin hab, wegen dem WGC zurücksetzen, aber das habe ich ja mit dem 1sek aus Programm gelöst. bei einer anderen Idee würde ich es auch gerne ausprobieren.

Falls noch was gebraucht wird einfach melden.

<img width="1130" alt="Bildschirmfoto 2020-10-04 um 17 12 23" src="https://user-images.githubusercontent.com/72289306/95019418-83585580-0665-11eb-9f92-c4014ae5b5f4.png">
<img width="1412" alt="Bildschirmfoto 2020-10-04 um 17 13 32" src="https://user-images.githubusercontent.com/72289306/95019419-85221900-0665-11eb-81d8-215277b961ca.png">
<img width="1421" alt="Bildschirmfoto 2020-10-04 um 17 14 02" src="https://user-images.githubusercontent.com/72289306/95019420-85baaf80-0665-11eb-9d82-ccb19f7860be.png">
<img width="1406" alt="Bildschirmfoto 2020-10-04 um 17 14 25" src="https://user-images.githubusercontent.com/72289306/95019422-85baaf80-0665-11eb-8ff7-4e31497999d8.png">

**Comment by Icke-NOH** [comment]
Hab ich erledigt. Mal ne andere Frage. Wenn ich meinen Wäschetrockner über schaltmessdose abfrage wann er fertig ist bekomme ich über Telegram eine Nachricht das fertig. Wie muss ich den in HAP einbinden damit er da über HomeKit sich meldet ?! 

Mit freundlichen Grüßen 

Von meinem iPhone gesendet

**Comment by thkl** [comment]
Ich befürchte das wird nicht so einfach. Der "ist fertig" Status wird sicher über die Strommessung entschieden.
Da aber außer Türen und Fenstern (oder auch Kontakten) nichts eine eine Notification erzeugt wird das nichts.

Was man machen könnte: Ein virtuelle Taste wird in der CCU durch die Strommessung < x mA getriggert. Und diese müsste mit einem virtuellen Kontakt verknüpft werden, der halt kurz zu geht wenn ein Tastendruck erkannt wird. (letztere Funtionsweise müsste ich als Service aber erst bauen)

**Comment by Icke-NOH** [comment]
Ja wäre eine feine Sache. Ich meine es gibt einige die Waschmaschine und Trockner so auslesen. Kann man dich denn in deinem Project auch über eine Spende weiter motivieren ? 

Mit freundlichen Grüßen 
Lutz 

Von meinem iPhone gesendet

**Comment by thkl** [comment]
Ich habe ne noch bessere Idee. Es gibt bereits einen fertigen Türklingel Service. Dem muss ich nur sagen, das er auch auf virtuelle Tasten reagieren soll. Das ist ein kleiner Eintrag. Die Türklingel löst auch eine Notification aus. Und die kommt nur einmal. Die muss man dann halt nur Trockner nennen.

**Comment by Icke-NOH** [comment]
Ja coole Sache. Wenn ich testen Kann/soll einfach Bescheid geben. Muss aber dazu sagen das ich mit virtuellen noch nie was gemacht habe. 

Ps. Gib mal Kaffeekasse Paypal Adresse bitte. 

Von meinem iPhone gesendet

**Comment by thkl** [comment]
>  Gib mal Kaffeekasse Paypal Adresse bitte. 

Auf der Hauptseite hier gibt es einen Sponsor Button, der ist mit PP verlinkt

**Comment by Icke-NOH** [comment]
Sie haben Post 

Von meinem iPhone gesendet

**Comment by thkl** [comment]
🙏

**Comment by Icke-NOH** [comment]
Nabend, ist das nun drin? und wie trigger ich das dann an? derzeit lös ich die Meldung über Telegram wenn der Stromwert erreicht ist.

![Bildschirmfoto 2020-10-11 um 16 52 13](https://user-images.githubusercontent.com/72289306/95681816-2703b180-0be2-11eb-86ba-e76a991ef814.png)

**Comment by sailor79** [comment]
@Icke-NOK, danke für die Bilder. Habe sie hier erstmal roh ins WIKI übernommen -> [https://github.com/thkl/hap-homematic/wiki/special-devices#garage-door-opener-with-hmip-sam-und-hmip-wgc](url).
