### ISSUE TITLE
Impuls für Licht

### ISSUE THREAD

**Issue by 00raphael** [thkl/hap-homematic#193]
Hallo zusammen!

Ich habe eine Frage, die sehr ähnlich zum Garagentoröffner ist - ich habe eine Leuchte für die ich einen Impuls (ca. 1 Sek) zum ein- oder ausschalten geben muss. 

Ich habe die Leuchte mit dem HMIP-PCBS angeschlossen und in HomeMatic funktioniert das auch wunderbar (Einschaltdauer 1 Sekunde). Wie kann ich dies aber nun in HomeKit bekommen?

Danke für die Hilfe und einen schönen Sonntag Abend!
Raphael

**Comment by thkl** [comment]
Entweder über den Umweg eines Programmes oder warten bis ich einen "Einschaltdauer" Parameter in Switche eingebaut habe 😎. 

Problem bei der Sache ist dann aber, das der Zustand der Lampe und des eigentlichen Lichtes nicht mehr passen. Auch wenn es leichter wird es in HomeKit dann ja ausgeschalten angezeigt.

**Comment by 00raphael** [comment]
Hi Thomas, das stimmt! Ein neuer Aspekt an der Sache ;-)
Gibt es Deiner Ansicht nach einen Workaround, damit der Zustand einer Lampe richtig angezeigt wird? Wahrscheinlich könnte das nur funktionieren wenn man irgendwie messen kann, ob Strom fließt...

**Comment by timwegenerDE** [comment]
Ich habe mit einem Schalt-Messaktor das Treppenhaus-Licht (Stromstoß-Schaltung) smart bekommen. Geht aber nur, da der BSM auch messen kann.

https://technikkram.net/blog/2019/07/19/homematic-stromstossschaltung-stromstossrelais-treppenhauslicht-smart-machen/

Die Schalt-Messaktoren sind m.W. aber alle nur für 230V ausgelegt.

**Comment by thkl** [comment]
Also generell könnte ich allen Switch und Dimmern eine Einschaltzeit verpassen. 

Des Weiteren wäre für Schaltaktoren mit Strommessung ein neuer Service möglich, der den "ein" Zustand in HomeKit abhängig von einer konfigurierbaren Mindestlast macht.  Und in Zusammenhang mit der Einschaltzeit würde das Treppenlicht so funktionieren.

**Comment by thkl** [comment]
Ok Dimmer und Switche haben ab dem nächsten Release eine konfigurierbare Einschaltzeit (ON_TIME).
Dabei wird, sollte diese > 0 Sekunden sein, der Wert vor dem Setzen des Ein (bzw. Helligkeitswertes) an das Gerät gesendet.
Das Gerät schaltet sich nach dieser Zeit automatisch wieder aus. Das wird vom Gerät selber gemanagt.

Wichtig für Dimmer: Die ON_TIME wird nur gesetzt, wenn das Licht initial eingeschaltet wird. Also von 0 auf X gedimmt wird. Wird während des Ablaufes der ON_TIME die Helligkeit geändert, dann wird die Zeit nicht noch mal gesetzt, das heisst, die Lampe bleibt an.

**Comment by comtel2000** [comment]
@00raphael HMIP-PCBS & HMIP-PCBS2 können als Stromstoß/Impuls Aktoren (Einschaltdauer 1 sec.) leicht via Direkt-Verknüpfung mit Virtuellen Tastern realisiert werden. Die Virtuelle Taste dann einfach in HAP hinzufügen..
Da PCBS keine Leistungsmessung hat, wäre die Idee mit Leistungs- oder Helligkeitsmessung da vermutlich nur via "Special Device"
mit verschiedenen Kanälen möglich. Oder einfach einen BSM kaufen ;)

**Comment by sailor79** [comment]
Functionality added to wiki
