### ISSUE TITLE
AppleTV Geräte zeigen in Favoriten nur Szenen an; keine einzelne Geräte

### ISSUE THREAD

**Issue by edwolf60** [thkl/hap-homematic#196]
Ich habe iPhone/Ipad und MacOS Geräte, auf denen die Anzeige stimmt und synchronisiert ist.
Auf meinen AppleTV Geräten zeigt es nur die Szenen aus den Favoriten an. 
Sämtliche Geräte (auch das HAP-addon sind auf dem neuesten Softwarestand und neu gestartet.

**Comment by thkl** [comment]
Ja, das ist so. Auf dem ATV werden nur Szenen und keine einzelnen Geräte angezeigt:

https://support.apple.com/de-de/guide/tv/atvb5f549664/14.0/tvos/14.0

**Comment by sailor79** [comment]
added to wiki
