### ISSUE TITLE
HM-Sec-SCo als HomeMaticWindowAccessory

### ISSUE THREAD

**Issue by rbartholomay** [thkl/hap-homematic#197]
Hallo!

Ich bei mir meine HM-Sec-SCo als HomeMaticWindowAccessory (war auch der Vorschlag) konfiguriert. Es geht alles aber HomeKit meint das es ein Fenster mit Motorsteuerung ist.
Bekommt man das irgendwie ohne Motor hin, oder kennt HomeKit kein „einfaches“ Fenster.

BTW: Super Plugin!!!

Gruß, René

**Comment by thkl** [comment]
Nein, HomeKit kennt aktuell nur diese Motorfenster oder halt Kontakte.
Man kann aber in der Home App in den Settings des Kontaktes dann festlegen, wie dieser dargestellt werden soll. Dort gibt es dann auch Fenster und Türen.

**Comment by rbartholomay** [comment]
Geändert und geht. Danke!!!
