### ISSUE TITLE
Alle Geräte werden trotz Instanzen in Standardraum gemappt und Umbenannt.

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#199]
Hallo,

Heute Morgen waren alle Geräte in einem neuen Standardraum gemappt.
0.0.12
0.0.54
Auf aktueller Raspberrymatic 3.53.30.20200919
IPhone Xs als Zugriff über IPad Steuerzentrale

Zudem sind die Geräte in Homekit umbenannt.
- Aus Badezimmer Fenster wurde nur Fenster. Es war aber im Standardraum aufgelistet.
(Normal wird das Badezimmer nur weg gelassen, wenn sich das Gerät im Raum Badezimmer befindet.)
Der ursprüngliche Standardraum enthält keine Geräte.

In der Oberfläche von HAP Homematic steht bei der Instanz Default - Keine Geräte.
Bei der Instanz Badezimmer stehen aber die Geräte noch drin.
Schaue ich dann in den Geräteeinstellungen im Homekit unter Bridge - Hier hat sich der Raum der Bridge verändert (hinzugefügt wurde Sie zu Badezimmer) Hier steht nun, dass die Bridge Homeatic Badezimmer sich im Standardraum befindet. Ändere ich den Raum wieder auf Badezimmer wird der Vorgang nicht ausgeführt.
![Unbenannt](https://user-images.githubusercontent.com/55836556/95303686-cd1e8700-0883-11eb-9fac-d00d923cac4b.JPG)

Nach Löschen vom Cache und Neustart der CCU / HAP Homematic und Homekit App keine Änderung.

Andere Homekit Geräte (HUE) funktionieren tadellos.

Gruß meistermolli

![image2](https://user-images.githubusercontent.com/55836556/95301358-ca6e6280-0880-11eb-8532-8d53ad4e9acf.png)
![image1](https://user-images.githubusercontent.com/55836556/95301367-ccd0bc80-0880-11eb-89df-a9865c9ec8ec.jpeg)
![image0](https://user-images.githubusercontent.com/55836556/95301372-ce9a8000-0880-11eb-9776-ea46d23bb182.png)

EDIT: Log kann ich erst heute Abend erzeugen ich vermute der Fehler liegt in der Home App, dass hier die Räume der Bridges auf Standardraum gesetzt wurden.

**Comment by thkl** [comment]
Hast du vor dem Veröffentlichen der Geräte die Instanzen (als sie noch leer waren) in HomeKit den gewünschten Räumen zugeordnet ?

Die Bridgeinstanz selber bringt keine Info mit in welchem Raum sie ist. Deswegen kann man die am Anfang leer veröffentlichen und in HomeKit in einen Raum setzten. 

Alle anschließend in diese Instanz veröffentlichten Geräte landen in dem selben Raum wie die Bridgeinstanz.

**Comment by meistermolli** [comment]
Genau:
1. Instanzen erstellt
2. Zu Homekit hinzugefügt und Raum "Badezimmer" zugeordnet. (oder halt dem entsprecheden Raum)
3. Geräte gemappt. (hat jetzt auch 3 Tage funktioniert)
Geräte wurden im jeweiligen Raum angezeigt.

Heute Morgen dann alle in einem neu angelegten Standardraum in der Home App.
HAP-Homematic zeigt in der Oberfläche noch alles Korrekt an.

Gruß meistermolli

**Comment by thkl** [comment]
Das klingt aber echt wild, Ich habe ja durch die Entwicklung schon eine Menge hin und her geschoben. Aber sobald eine Bridge Instanz in einem Raum ist kommen neue Geräte immer mit in diesen Raum.

Die Angabe des Raumes auf der Config Oberfläche hat nichts mit dem Raum in HomeKit zu tun. Ich kann einer Bridge Instanz keinen Raum mitgeben. Das muss auf Client Seite passieren.

Wenn Du mutig bist kannst Du folgendes versuchen:

Alle Hap-HomeMatic Instanzen aus Home löschen (Achtung ggf erstelle Automationen gehen dabei drauf)
Datei /usr/local/etc/config/addons/hap-homematic/config.json auf der CCU editieren:

Das ist ein JSON und es existiert (meist gleich am Anfang) ein Key "instances" Darin enthalten sind die Instanzen:

```
  "12345-abcd-1234-1234-foobar123": {
   "name": "Flur",
   "user": "12:34:56:78:90:aa",
   "pincode": "1234-00-000",
   "roomId": 2651,
   "publishDevices": true
  }
```

(Name; UUID, PINS können variieren ;) )

Wenn Du jetzt 

`
   "publishDevices": true
` 
auf 
` 
  "publishDevices": false
`
stellst , das speicherst und anschließed HAP neu startest werden die Instanzen wieder ohne Geräte an Home geschickt.
Dann kannst Du die wieder Räumen zuordnen und hinterher wieder die Häkchen für Geräte publizieren auf dem WebUI machen.


Das ist deswegen so kompliziert gemacht, weil ein depublizieren von Geräten eben die Automationen löscht und da möchte ich vermeiden, das das ausversehen passiert.

**Comment by meistermolli** [comment]
Hi, danke. 
Ich hatte zum Glück noch keine Automationen drin. Da ich alles neu aufgebaut hatte. 
Auf dem iPad war es auch so. Alle Bridges / Instanzen haben den Raum gewechselt auf Standard Raum. Ich lege das alles nochmal neu auf und schaue es mir an. 
Merci

**Comment by kampfschlonz** [comment]
Den Effekt hatte ich nach einem Homepod Update auch gehabt. Habe dann auf AppleTV umgestellt, bisher ohne Probleme.

**Comment by meistermolli** [comment]
Da ich noch nichts weiter geändert habe mangels Zeit hier noch etwas kurioses:
Der Mac zeigt alles korrekt an.
iPad und iPhone werfen alles in den Standard Raum. 

Ich setze mal alles von vorne neu auf inkl neu Installation und dann mal sehen.

![28F8BE80-437D-4605-8FCC-9A3E52EF084A](https://user-images.githubusercontent.com/55836556/95472840-c8d99300-0983-11eb-904b-487ed33e894f.jpeg)
![97F5FC0B-098C-467E-8C81-04A972742808](https://user-images.githubusercontent.com/55836556/95472846-caa35680-0983-11eb-944a-cee82121bf16.png)

**Comment by gerd2005** [comment]
Das ist schön, dass jemand vom gleichen Verhalten betroffen ist wie ich. Bei mir werden auch neue Geräte immer in einen neuen Standardraum gelegt.

**Comment by meistermolli** [comment]
Das ist ja nochmal was anderes denke ich .

**Comment by gerd2005** [comment]
Findest du? Ich denke, dass dieses Issue aus der gleichen Ecke kommt.
![4E294375-9798-4F86-ABAA-028CB5121C7E](https://user-images.githubusercontent.com/72799068/95856769-dcf20b80-0d5a-11eb-94c9-fdc400337e89.png)
![E32ABEF7-E5F9-4470-9E86-4E174CA2B1C9](https://user-images.githubusercontent.com/72799068/95856786-e2e7ec80-0d5a-11eb-9ffc-7d99e5f103bc.jpeg)

**Comment by thkl** [comment]
> ![97F5FC0B-098C-467E-8C81-04A972742808](https://user-images.githubusercontent.com/55836556/95472846-caa35680-0983-11eb-944a-cee82121bf16.png)


Also ich habe jetzt mal ein Testsystem aufgesetzt (IOS14.0.1) RM 3.53.30.20200919 HAP-Homematic Version 0.0.54

* Zuerst die default Instanz (noch ohne Geräte und ohne das Veröffentlichungshäkchen in den Settings) in Homekit aufgenommen (Home APP)
* Diese Bridge dann direkt im Setup Assistenten von Home einem neuen leeren Testraum zugeordnet (Ich habe jetzt kein separates neues leeres Home erzeugt)
* ein Gerät über das WebUI dieser Instanz hinzugefügt und anschließend das "Veröffentlichungshäkchen" gesetzt.
* 10sek später taucht das Gerät in genau diesem Testraum auf ...

*works for me*

**Comment by thkl** [comment]
Ok das ist dann aber eher ein HomeKit Problem, was ich hier nicht beeinflussen kann.

**Comment by gerd2005** [comment]
Mhh komisch, wobei ich mir das aber nicht wirklich vorstellen kann, dass HomeKit da unterschiedlich agiert. Naja... 

Mein Setting besteht aus zwei iPhones, zwei iPads und ein Apple TV (Zentrale). Hier wird alles synchron angezeigt. Einen Mac habe ich nicht mehr.

Dann würde ich sagen, dass wir das mal beobachten :-)

**Comment by meistermolli** [comment]
So, heute endlich dazu gekommen.

Alle Instanzen neu angelegt und HomeKit hinzugefügt und den Räumen zugewiesen.
Anschließend alle Geräte neu zugeordnet und auf HomeKit übertragen. (Was ein gedönz für so viele Geräte die Favoriten und Benachrichtigungen abzuwählen. - gibt es da einen schnelleren Weg den ich nicht kenne?)
Funktioniert wieder und die Bridges sind auch den einzelnen Räumen zugeordnet.

Erkenntnis aus anderen Bereichen: ich hatte mit zwei HomeKit Secure Video Kameras Probleme.
Die kamen davon, dass unser zu Hause unter Familien.ID läuft und ich Einstellungen mit meiner Me.ID gemacht habe und nicht direkt mit der Familien.ID. Vielleicht hat das ja hier auch zu diesen Problemen geführt? Ich beobachte das jetzt mal. Habe auch schön von allem Screenshots gemacht.

Was ich jetzt schon sagen kann: Bisher wurden schon einmal die Wandthermostate wieder als Favorit gesetzt, obwohl ich sie abgewählt hatte. (das habe ich schon in einem anderen issue gelesen)

Gruß und schönes Wochenende 
meistermolli

**Comment by meistermolli** [comment]
@thkl HI,

also ich habe ein Wandthermostat, dass immer wieder als Favorit angezeigt wird nach Neustart des iPads. (ggf. HomeKit fehler?)

Zudem wurde bisher eine Bridge aus Raum Schlafzimmer in Standardraum verschoben, samt Geräten.
Was kann ich hier machen um nachzuvollziehen was hier passiert?
Die Bridges waren definitiv alle den Räumen zugeordnet. Erst dann habe ich die Geräte auf die Bridges verteilt.
Also jetzt die Bridges wieder gelöscht, neue erstellt, zugeordnet und in den Raum gelegt. Geräte gelöscht und neu angelegt und wieder neu zugeordnet. (hier kann es natürlich auch ein HomeKit Fehler sein).

Bin grade eh genervt von der Apple Software, Mac entsperren über Watch geht nicht, HomeKit Secure video macht viele Mukken (aufnähme bei Bewegung vom Baum obwohl dies abgeschaltet ist, aufnahmelängen viel zu kurz, Benachrichtigungen obwohl abgewählt).

Läuft grade alles andere als Rund das ganze.

Gruß

**Comment by thkl** [comment]
Das klingt alles nicht nett, aber ich kann das nicht so wirklich beeinflussen.
Ich liefere eine Bridge mit x Accessories an HomeKit. Dabei kommen keinerlei Rauminformationen oder Informationen über Favoriten Statusmessages etc mit.

Diese Infos werden alleine durch den HomeKit Controller (also die HomeApp oder Eve oder was auch immer benutzt wird) vergeben.


Es gibt einen einzigen Fall, wo auf Seiten des HomeKit Devices (also in dem Falle hap-homematic) etwas durcheinander kommen kann. Und zwar an der Stelle, wenn eine Bridge ohne vorher schon einmal bekannte Geräte im HomeKit auftaucht.
Dann wirft HomeKit gern mal die zu diesem Gerät erstellen Automationen weg. Um das zu verhindern, kann man auch den Haken in den Bridge Settings in hap-homematic bei "Geräte veröffentlichen" nicht wieder entfernen wenn er einmal gesetzt wurde.

**Comment by meistermolli** [comment]
Hi Merci, ok wollte nur noch mitteilen wie das hier weiter geht.
Dann liegt es ja wie auch von mir geschrieben nicht an deinem Plugin, kann aber bei anderen Usern auch zu Fehlern führen. 

Sollen wir den hier dann schließen? Für mich in Ordnung.

Gruß meistermolli

**Comment by JensBonse** [comment]
Bei mir waren letztlich auch auf einmal einige Geräte vom richtigen Raum in den Standard Raum verschoben worden.
Ich denke es lag daran, dass ich in der Philips Hue App eine Meldung bekommen habe, das dir Räume nicht Synchron wären und Synchronisiert werden sollten. Nachdem ich da blöderweise auf OK geklickt habe, waren die Geräte im Standard Raum.
Ich denke das es kein HAP Problem sein kann, da Thomas ja keine Raumdaten durchreichen kann. Und somit alles auf HomeKit Ebene gemanaged wird. Vermute das da meine Philips APP dann was blödes gemacht hat...

**Comment by meistermolli** [comment]
Hallo, ich habe das jetzt eine ganze weile beobachtet und denke auch, dass die HUE app hier der Übeltäter des Problems ist.
Wenn man ein Gerät oder Raum in der Home App umbenennt nicht auf die Synchronisieren Funktion in der Hue App tippen. Sondern statt dessen in der Hue App Manuell den Raum / Leuchte / Gruppe etc umbenennen! So verschwindet das Ausrufezeichen in der Hue App und es kommt zu keinen Problemen mit der Raumverteilung meht!

Hier liegt der Fehler denke ich im Homekit in Verbindung mit der HUE app.

Gruß meistermolli
