### ISSUE TITLE
readiness test on  rock64 (pivccu3) 

### ISSUE THREAD

**Issue by v0r73x** [thkl/hap-homematic#2]
sorry to disturb you once more @thkl 

this is my rooms with devices in it 
![image](https://user-images.githubusercontent.com/48632087/78264796-ea088500-7503-11ea-8895-bf9607241a1c.png)

when i want to create the instances the room names are different and shows no usable devices 
![image](https://user-images.githubusercontent.com/48632087/78265068-410e5a00-7504-11ea-9023-189ca42a0e6d.png)

is that because of pivccu is different to raspberrymatic and could not parse the rooms ?

**Comment by thkl** [comment]
No that’s because of that the ccu uses generic names in the database which will be translated in the Ui. 

U may create instances without adding devices first. U are able to assign them later and the system will switch the device to the correct instance.

**Comment by v0r73x** [comment]
again strange thing going on ... i pressed one time to publish instances and now the names are updated ?!? anyway  see now number of devices now ... 
![image](https://user-images.githubusercontent.com/48632087/78266212-c2b2b780-7505-11ea-83c7-83a0a2e341d0.png)

**Comment by thkl** [comment]
Oh wow,

Seem like I have to add lots of logging to catch all the strange behavior on user side 😀

**Comment by v0r73x** [comment]
ok now i added one device - done the room mapping and - it works :) 
I have my sonoff switch running - now i try to change the service .. keep you updated :) 
and I share a beer for you :) thx thkl :)

**Comment by thkl** [comment]
when you add more devices to the same instance , homekit will put the new devices in the same room as the ones you've first added. So one of the big issues with homebrige, that u will lost your device to room mapping if something goes wrong, is gone for ever ;)

**Comment by v0r73x** [comment]
moin moin again ;) 

I started now the migration to hap-homematic. 
But again - I have some issue which I never faced in the last years with homekit/homebridge/homematic... 
I have some devices which I can control after setup over hap-homematic - for example the modified cuxd shutter where i have connected an HM-LC-Sw4-PCB and 3 channels vor pressing my Becker Centronics RF Remote :) that works great after importing the instance which have mapped this aktor. 

but for example a device HM-LC-Sw1-FM (bulp for kinderzimmer) or an HM-LC-Sw4-Ba-PCB is viewed in home App but pressing will not dio anything - it will not trigger the aktor....

**Comment by v0r73x** [comment]
in general : can you let me know me the advantages of using the plugin instead of the homebridge-homematic plugin ? I know for me the sprinkler support is important but to be honest I am not that familiar why its better to have several instances instead of 1 - as the german say: ich seh' den wald vor lauter Bäumen nicht ) ;) 
btw: if you have neopixels i have a very good python script which offers a http webserver and you can controll the neopixel with 1 gpio pin from raspberry - also with the homeapp choosing the colors ;)

**Comment by v0r73x** [comment]
oh nooo ...the valves are dissapear again ... same as I have on the plugin - its working some seconds (10-20se.) and then the both devices disappear automatically out of the homekit app ... ;(

**Comment by thkl** [comment]
Ok I will Check this

**Comment by v0r73x** [comment]
Hi Thomas,
i checked in actual Eve App as well - same behavior as in Home App. Devices there ... but after waiting some seconds they dissapear in Eve ... totally stange...
btw: i tried to switch a light in Eve as well HM-LC-Sw1-FM (bulp for kinderzimmer) - its change to active and 1 sec. after back to inactive - and nothing was triggered in homematic - i checked the timestamps there.

**Comment by thkl** [comment]
Strange all these actors are working fine here. 

May you try to add another home and add the instances. Maybe that’s a glitch in the HomeKit database

**Comment by thkl** [comment]
Ok i've found the root cause of that behavior: I've recently added a check for read only settings of channels. If the accessory has not definition for this check the result is random. So sometimes it works .. sometimes not ;-/ the new npm package 0.0.16 will  fix this

**Comment by v0r73x** [comment]
ok i will try and give you feedback tomorrow latest .... many thanks and stay healthy :)

**Comment by v0r73x** [comment]
ok i updated to 0.0.16 and it seems that pressing the button is now working - i tested with the HM-LC-Sw1-FM (bulb for kinderzimmer) and its triggering now the actor - so that is working.

But i have still the behavior that the valves are disappering after some seconds - if i modify them as switch they stay in home app. 
I also tried to define the valves as generic - to see if that makes any difference but unfortunatly not ;(

**Comment by thkl** [comment]
i've tried this with a HM-LC-Sw1-Fm and a HM-LC-Sw2-FM ..and it works fine with HomeMaticValveAccessory ...

**Comment by v0r73x** [comment]
ok i tried it with HM-LC-Sw4-Ba-PCB and it disappear. but its only the problem with the valve service - it looks that crashes the hap instance or sth. similar. can i debug that somewhere ?

**Comment by v0r73x** [comment]
related that pivccu runs in a container our setuop should be the same.. i still have no clue how to identify the issue or to deeper debug the hap service logs

**Comment by thkl** [comment]
> ok i tried it with HM-LC-Sw4-Ba-PCB and it disappear. but its only the problem with the valve service - it looks that crashes the hap instance or sth. similar. can i debug that somewhere ?

u can run the hap service in debug mode
login (or attach) to the ccu
stop the service :  /etc/config/rc.d/hap-homematic stop
run this in debug: node /usr/local/addons/hap-homematic/index.js -D

this will produce lots of output ;) but a crash is visible

**Comment by v0r73x** [comment]
Hi Thomas, 

again thanks for your feedback:

I tried to start the debug but i havent.got the index.js in that part ... 
![image](https://user-images.githubusercontent.com/48632087/78387435-9f5c3b00-75df-11ea-852b-be0a8a697048.png)

**Comment by v0r73x** [comment]
du you know what that means? 
![image](https://user-images.githubusercontent.com/48632087/78389086-6d000d00-75e2-11ea-821e-67b9ca16c663.png)

i checked in log the initialization of the device - all looks good
![image](https://user-images.githubusercontent.com/48632087/78389242-b5b7c600-75e2-11ea-8edc-159678ea4194.png)

when I start the debug I see the device initialized correctly then i start the valve to run - the valve stay running but the icon disappear in home app ?!? 
nothing is changing in the log - i tried after the valve disappear to switch sth other to see if that comes into debug and yes it came... 
i will let the debug run to see if something will be coming in the next hours in the log because after that "crash" no valve is in the log recognized anymore - i hope you understand what i mean

**Comment by thkl** [comment]
the warning is not critical .. there is no definition for the channel where the system will check the read only mode so the current channel will be used. (This is only relevant for Powermeter with Switch -> u have to add channel 3 (powermeter) and channel 1 (switch) will be checked)
 .... blabla bla ..


currently there are no errors .. so i am afraid, the problem is homekit not the HAP Service ...
have u tried to add a new home in your app and add the hap instances there ?

**Comment by thkl** [comment]
and yes u are right .. the npm version is installd in node_modues/hap-homematic .. the path above is my test system ... ;) .. i will add a debug switch into the webUI later

**Comment by v0r73x** [comment]
> currently there are no errors .. so i am afraid, the problem is homekit not the HAP Service ...
> have u tried to add a new home in your app and add the hap instances there ?
yes i created new home in homeapp and add the hap-instance with the mapped valve in it

**Comment by v0r73x** [comment]
what i found some minutes later is that the valve was switched of and the timestamp match with the homematic web gui when the aktor was switched off) - and that is what i found in the log 
![image](https://user-images.githubusercontent.com/48632087/78391418-9de24100-75e6-11ea-9321-9254973eca67.png)

**Comment by v0r73x** [comment]
so hap service seems to work but why it switched off after 10 min?  It wasn't possible for me to configure the switch

**Comment by thkl** [comment]
default valve time is 0 seconds, which means no time; the valve should stay on 
u can set the duration time in apples home by sliding upwards in the device detail screen....

and no, do not logout of icloud this will end up in chaos ;o)

**Comment by thkl** [comment]
/etc/config/addons/hap-homematic/ is the path for all the configuration files. there is one file for each device which contains persistent settings (.pstore) ... in your case u should check ccuname_oeq1211481_4_pstore ... the only setting should be "duration":.... with the last value which was set thru homekit Characteristic.SetDuration

**Comment by v0r73x** [comment]
Hi Thomas,

i had some tryouts with complete new home config from scratch - still same result :(
by the way I get it work to set a timer over the homeapp - and yes its written into the .pstore file
![image](https://user-images.githubusercontent.com/48632087/78795919-e5d1e100-79b5-11ea-8e57-7e7994876ed0.png)

In debug still nothing new - i mentioned some elgato faketimer exception could it be that the icon disappears in the homeapp related to this? 
Im just guessing because i have still no idea what causes this issue.

**Comment by v0r73x** [comment]
thats all what the debug gave me:

![image](https://user-images.githubusercontent.com/48632087/78797299-ccca2f80-79b7-11ea-97ee-331f59a670c4.png)

and in middle of setting the timer duration in homeapp for the new choosen devices as irrigator - the icon and timersettings menü disapper in home app 

(in log you see i playing a little bit with the timer) and then...broken - no valve anymore

**Comment by thkl** [comment]
this looks all good .. there is no error .. anyway a very strange behaviour at your side ... 
btw: version 0.0.18 has now a switch to enable debug logging via webUI

**Comment by v0r73x** [comment]
hmm Thomas - what kind of setup you use or prefer: rasbianmatic, original ccu3, pivccu etc.?

**Comment by thkl** [comment]
i am using:

an raspberrymatic (Rpi 3)  as production system
an raspberrymatic (VirtualBox) as development system
an pivccu3 (Rpi 3) as integration and test system

choose your fighter ;o)

**Comment by v0r73x** [comment]
ok after a complete new setup with Homekit (new installed rock64 with pivccu3- complete from scratch) I added 2 channels of an HM-LC-Sw4-Ba-PCB and set them to valve - now they stay constant! I guess there was a problem with the new linux header after updating the rock64 with apt update && upgrade. Looks that something goes wrong with the GPIO header - after reset of the pivccu the reset of CCU3 duty cycle was not reset to zero as well... 

There is only one open topic left - can you make it possible that CuxD switches could be used as valve as well? 

I though you told in the Gartenbewässerungs issue that there is no Eventlistener on  the CuxD.
At the moment I have a program running when the HM-LC-Sw4-Ba-PCB is triggered that the CuxD device will be on or of ... so that i can use the vave timer on homeapp - its just a workaround and dirty - I hope there is a possibility to run the CuxD switches as well as valves.
looking forward to hear from you -

**Comment by thkl** [comment]
i am not sure, CuxD is an virtual interface and sends events as well to rega. But it uses, the last time i checked,  binrpc. BinRPC is deprecated and i do not have implement it. U may test this as well. The system will automatic fetch the used interfaces from your ccu and will connect to that interface if there is an device it should use. So just add an CuxD Switch or so, and check the debug log.

The latest version has an option at the webui to restart the service with debug enabled so u do not have to use a terminal anymore ;)

**Comment by v0r73x** [comment]
Hi Thomas - yes - i saw the new internal area on webgui and already use it :) very helpful to have it ;) 

CuxD switches in general working - but if i define them as valve - my initial problem is back - valve devices disappear in home app ;(

**Comment by thkl** [comment]
WTF ..

look like i have to install cuxd on the test pivccu and dig into that ...

**Comment by v0r73x** [comment]
if i can support somehow somewhere - let me know

**Comment by thkl** [comment]
looks like cuxd is still using xmlrpc_bin :( and its a terrible ui/ux ¯\_(ツ)_/¯

**Comment by v0r73x** [comment]
just another question: when i use homebridge-hap is there a way to anounce the devices into alexa? 
i used in the past the homebridge plugin called alexa but this plugin runs on a homebridge and will not discover devices i have in homematic-hap...

**Comment by thkl** [comment]
To use Alexa u have to offer a cloud based middleware. This costs money so no .... Siri and Alexa will not get married ;)

**Comment by thkl** [comment]
Version 0.0.19 has now CUxD event support ...

**Comment by v0r73x** [comment]
stop ... moment ... incredible c+_+D

**Comment by thkl** [comment]
wwwwhat ?

**Comment by v0r73x** [comment]
i tested 0.19 and my initial problem is away - the valves are still persist - no disappear anymore you ǝןqɐʇ ɐ ǝʞıן ǝɯ dıןɟ   ;) It's the best Easter present I can get - many thanks and I you want I'll invite you to some beer

**Comment by thkl** [comment]
oh sounds great \o/ ...

**Comment by v0r73x** [comment]
timer working great ... icon stay visible all the time - Status information are updated (I had sometimes issues with a cuxd shutter that not was updated to actual state) but all this is solved now :) 
You made my day (after making a bicycle tour today)

**Comment by v0r73x** [comment]
just one question - again (≧︿≦) 
is it possible to integrate the garagedoor function into homematic-hap? I want to use a sysvar where i define the closing time - i have no contact sensor on it and calculate with sys var. the closing time (to trigger open...openings,closing, closed). As actor I have an HM-LC-Sw1-PCB - it will be nice to go away from Http-GarageDoor plugin on homebridge

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/79051667-ad3e3b80-7c31-11ea-92df-5cb6261d05cf.png)


work im progress

**Comment by v0r73x** [comment]
ok - you impress me again - thats exact what i need XD as you know I am your beta tester ^^ XD let me know when there is something where I can help you - Im just only a sec network admin but with basic skills in node & python. I am member from ccc

**Comment by thkl** [comment]
i am not sure how to implement the current status of the door without a sensor on it ?

**Comment by v0r73x** [comment]
hahah - same same but different - i was just thinking to write that ^ ^

So - i use vars in homematic where the status is emulating if the door was triggered to close or open. You are right I only can trust what the homeapp says - if someone use the ir remote of the garagedoor its displaying wrong value - but in my family I am the only one who drives - so i use with bike my helmed and ask siri to open the garagedoor - and in the car i made some geomap - when i passes the point (gps coordinates) then the door will open automatically - closure is the same

**Comment by thkl** [comment]
Ok strange. The easiest way is to glue a optical window sensor on to the door, but i think i am able to fix this also in software :-)

**Comment by v0r73x** [comment]
that will be nice because my garagedoor is outside and the problem I have is  regading waterproof and - if someone want the can steal it from outside I had the situation already that someone steal my "lichtschranke"
I modified a little bit this how to and that was working very good for me 

https://github.com/mach1009/homebridge-http-garagedoor/wiki/How-to-setup-a-garage-door-opener-in-Homekit-with-Homematic-CCU2-or-RaspberryMatic

**Comment by v0r73x** [comment]
regarding my alexa issue i'll try this one :+1: https://github.com/bwssytems/ha-bridge

hey siri without a homepod is like talking to your wife - you have to repead it several times  by using an power plugged ipad - because of the missing array mic

**Comment by v0r73x** [comment]
after some weeks the valve service still works ༼ つ ◕_◕ ༽つ
I only get faced with some cosmetic issues - if i try to activate sometimes the valves I have to press long on the icon in home app and swipe the swith up/down. Timer are working great but if i ask siri to put on the valves she said everytime  "Bewässerung ist ausgestellt" or simmilar... it makes no matter if the actual status is on or off. did you face with same issues? 

btw: i saw you integrated the special device GaragedoorService :) I saw the required fields and I have no clue if I can already use it without the sensor - with sw based status - is there a possibility ? 

happy "Tag der Arbeit" ,

cheers, Robert

**Comment by v0r73x** [comment]
I also mentioned, that the motion sensors nut update the LUX - I want to try to use this value to activate lights by motion only if the brightness is bad... is that related to my device setup in homematic regarding the status updates? I tried to reduce my dutycycle and could be that i make some misconfig on the HomematicIP motion sensors HmIP-SMI.

and last thing on pvccu3 on rock64: if I update to new release in your WebGui - after pressing Yolo XD - the WebGui freezes and i have to relaod the page - I already tried to wait 5min but it makes no difference.
also, the cores of the rock64 are marked as unknown- could be nice to have the right one if possible
![image](https://user-images.githubusercontent.com/48632087/80843146-d3894280-8c03-11ea-8660-d5566255a225.png)

my proc/cpuinfo
![image](https://user-images.githubusercontent.com/48632087/80843311-4397c880-8c04-11ea-9e58-93a64859de3c.png)

**Comment by thkl** [comment]
I am not able to control Siri’s reaction on requests. That’s all done by the phone. If the Home App shows status A and Siri responds with status B, that looks like a HomeKit/Siri issue. 

Currently it’s not possible to use variables instead of real devices for the garage door service. I will keep this in mind for later versions. 

Short question about your motion sensor issue:   If any device sends an datapoint update to the ccu, the hap-homematic plugin also receives an event and will update the corresponding HomeKit device. May you please check the values at your ccu webui vs. HomeKit to make sure these values are the same as in HomeKit.  


Ah and I use node‘s process information 1:1 to display the CPU informations .. so I’m afraid that’s an node issue 😁

**Comment by thkl** [comment]
Ah and i know about the reboot issue.  I have to come up with a better solution to detect when the server is back from rebooting.
