### ISSUE TITLE
Fehler: Winmatic zeigt im Zustand offen "öffnen" statt "geöffnet

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#20]
Hallo Thomas

Wie oben beschrieben, zeit die Winmatic in HK wenn Sie offen ist (war auch leider so bei der 219er) "öffnen" statt "geöffnet :(

lg Richard

**Comment by thkl** [comment]
siehe https://github.com/thkl/hap-homematic/issues/11#issuecomment-620106665

**Comment by roe1974** [comment]
ja .... :-) 👍
