### ISSUE TITLE
Abfrage des Status der Gerät dauert sehr lang

### ISSUE THREAD

**Issue by NullcheckerHipw** [thkl/hap-homematic#201]
Hallo zusammen, ich habe das Problem dass die Abfrage des Status in der Apple Home App sehr lange dauert. Dh ich öffne die Apple Home App, es werden direkt jede Menge Geräte angezeigt die angeblich nicht antworten. Nach ca 5-10 sek verschwinden die dann und es kommen neue hinzu. Nach etwa 20-30 Sekunden sind dann alle Geräte vorhanden und sind ohne Fehler. 
Meine gesamte Elektrik läuft bei mir über HmipW und es sind aktuell knappe 40 Geräte eingebunden. 
Ich hoffe ihr versteht was ich meine und könnt mir weiterhelfen. 
![2CD4C3B3-6BDA-47E3-8297-96653C5CB07F](https://user-images.githubusercontent.com/72544933/95495123-3cd56480-099f-11eb-86ac-dc74716506b4.jpeg)

**Comment by NullcheckerHipw** [comment]
Kann mir keiner helfen?

**Comment by dkrizic** [comment]
Ich habe es gelesen. Ich habe diese Probleme nicht. Wie ist Dein Netz aufgebaut? Sind WLAN und LAN verschiedene Netze. Werden Bonjour-Pakete zwischen beiden Netzen weiter gegeben? Ich verwende ein Tool namens iNet Network Scanner um zu schauen, wie die HomeKit-Geräte sich im Netz präsentieren:

![image](https://user-images.githubusercontent.com/1181349/95676087-e5f8a680-0bbb-11eb-93e1-928939370c61.png)

Diese IP-Adressen und Ports müssen natürlich vom WLAN aus erreichbar sein.

**Comment by NullcheckerHipw** [comment]
Ich habe einen Speedport Hybrid Router der nur für LAN da ist. Am Speedport hab ich noch einen Orbi hängen. Der Orbi ist als Accesspoint konfiguriert und erzeug das WLAN. Die CCU3 hängt aber auch am Orbi. 
Ich hab mir Inet als IPhone App runtergeladen. Die Bonjour Dienste kann ich mit der Freeware Version aber leider nicht sehen.

**Comment by dkrizic** [comment]
Haben LAN (als das Netz direkt am Orbi) und das WLAN verschiedene IP-Adressbereiche, bzw. anders gefragt: Arbeitet Orbi (ich kenne das Teil nicht direkt) im Bridge-Mode oder im Router-Mode?

**Comment by NullcheckerHipw** [comment]
Also im Orbi hab ich die Wahl zwischen Router Modus und AP-Modus. Der Orbi ist im AP Modus. Beide Geräte haben den gleichen IP Adressenbereich. Der Speedport und der Orbi haben ip 192.168.2.1 & 2 und wlan ips fangen bei 100 an also 192.168.2.1xx.

**Comment by NullcheckerHipw** [comment]
Was ich noch dazu sagen muss, ich benutze noch die Smarthome App „@Home“. Mit der App hab ich diese Probleme nicht.

**Comment by NullcheckerHipw** [comment]
Hat noch irgendwer eine Idee woran es liegen könnte?

**Comment by khwerhahn** [comment]
Bei mir tritt ein ähnliches Problem auf. Nach einer Weile findet HomeKit die Homematic Devices nicht mehr, die allerdings vorher einwandfrei funktioniert haben.  

Ich bin mir sehr sicher, dass sich der Port der Bridge verändert hat durch einen Reboot (ging ja vorher). Habe alle Ports, die im Log stehen und die eigene IP Adresse der CCU in die Firewall Settings eingetragen und jetzt funktioniert alles wieder. @NullcheckerHipw

**Comment by NullcheckerHipw** [comment]
> Bei mir tritt ein ähnliches Problem auf. Nach einer Weile findet HomeKit die Homematic Devices nicht mehr, die allerdings vorher einwandfrei funktioniert haben.
> 
> Ich bin mir sehr sicher, dass sich der Port der Bridge verändert hat durch einen Reboot (ging ja vorher). Habe alle Ports, die im Log stehen und die eigene IP Adresse der CCU in die Firewall Settings eingetragen und jetzt funktioniert alles wieder. @NullcheckerHipw

Die Ports sind alle eingetragen und die Geräte funktionieren auch. Dann auf einmal werden bei teilweise allen Geräten angezeigt, dass diese nicht antworten. Wartet man eine Minute dann sind die Geräte alle wieder da und fehlerfrei. Ich weiß echt nicht mehr was das noch sein könnte. Mir ist allerdings aufgefallen das auch in der Konfigurationsseite die Ports der Instanzen rot angezeigt werden obwohl alles läuft. Im nächsten Moment passt es aber dann auch wieder.

**Comment by NullcheckerHipw** [comment]
Hab das jetzt komplett gelöscht und durch Redmatic ersetzt. Fall erledigt.
