### ISSUE TITLE
Dimmer Werte synchronisieren 

### ISSUE THREAD

**Issue by dl-84** [thkl/hap-homematic#202]
Hallo,

ich habe folgendes Problem.

In meiner HomeMatic habe ich via CUxD Ikea Tradfri Spots eingebunden, bei welchen ich mit einem 6-Fach Taster die Dimmwerte über ein Programm steuere.

Die Einbindung in HAP unter Geräte war ohne Probleme möglich, auch die Steuerung klappt super.

Wenn ich die Spots via HomeKit steuere so bekommt die Homematic den aktuellen Dimmwert mit.
Steuere ich die Spots allerdings über die Homematic, so bekommt HomeKit den aktuellen Dimmwert leider nicht mit.

Wie kann ich das umgehen?

Danke und Grüße 
Daniel

**Comment by dl-84** [comment]
Könnte man das ganze umgehen wenn ich es über eine Systemvariable steuere?

HAP -> verändert Systemvariable und die CCU reagiert drauf und steuert die Lampe
+
Homematic Taster verändert Systemvariable, die CCU reagiert drauf steuert die Lampe und HAP bekommt den veränderten Wert mit.

Oder gibts sonst eine Lösung oder Erfahrungen?

**Comment by dl-84** [comment]
Also über eine Variable funktioniert das ganze jetzt wunderbar. Eine Kleinigkeit ist mir aber doch noch aufgefallen.

Wenn die Lampe aus ist und ich schalte sie über HomeKit an, so wird ein Dimmwert von 100% eingestellt und auch im HomeKit Icon so angezeigt.

Tippe ich jetzt nur einmal auf das HomeKit Icon zum ausschalten, so wird der Dimmwert auf 0% gesetzt, die Lampe ist aus aber das HomeKit Icon zeigt an immer noch einen eingeschaltete Lampe mit 0% an.

**Comment by dl-84** [comment]
> Ich vermute mal die CuxD Schnittstelle sendet keinen Event wenn der Spot verändert wird. Damit bekommt der hap-homematic Daemon das natürlich nicht mit. Und damit werden auch keine Werte in HomeKit verändert.

Lässt sich so ein Event manuell via HTTP Request auslösen?

Ich steuere meine Lampen ja auch direkt via HTTP-Befehl, kann ich dann auch einen an "hap-homematic Daemon" senden das er der die Werte neu laden und aktualisieren soll?

Wenn das klappen würde wäre das genau die Lösung die die Ikea Tradfri leuchten.

**Comment by thkl** [comment]
Sie oben https://github.com/thkl/hap-homematic/issues/202#issuecomment-707842387 Wenn die Variable geändert wurde kann diese durch das Triggern eines virtuellen Keys neu geladen werden.

**Comment by dl-84** [comment]
> Sie oben [#202 (comment)](https://github.com/thkl/hap-homematic/issues/202#issuecomment-707842387) Wenn die Variable geändert wurde kann diese durch das Triggern eines virtuellen Keys neu geladen werden.

Des klappt ja bis auf den Schönheitsfehler auch wunderbar, ich meinte aber den Weg wenn die Lampe direkt als Gerät von der Homematic in die HAP einbinde.

Die Lampen steuere ich via Programm mit Script und schicke HTTP-Befehle zum Dimmen weg. 
Der "hap-homematic Daemon" bekommt allerdings nicht mit das sich was geändert hat und ändert den Dimmwert in HomeKit nicht.

Gibt es hierfür einen Refresh Befehl? 
Die CCU der Homematic kennt den aktuellen Dimmerwert immer, er wird nur nicht weitergereicht von daher dachte ich, 
das ich die Aktualisierungen eines Gerätes manuell antriggern könnte.

**Comment by thkl** [comment]
Ja, so wie ich das verstanden habe, wird der Dimmwert über eine Variable gesteuert, das heisst in dem Prozess mit den HTTP Calls wird die Variable auch geändert ? Oder wo steht die aktuelle Helligkeit der Lampe in der CCU ?

**Comment by dl-84** [comment]
Der Weg über die Variable funktioniert bis auf den Schönheitsfehler das beim ausschalten nur ein 0% Dimmwert eigestellt wird und die Lampe in HomeKit an "An" dargestellt wird.
Aufgrund dessen bin ich am Testen ob es anderweitig auch klappen könnte und habe mir folgenden Weg überlegt:

- Einbindung in meine Tradfri CUxD Lampen in HomeKit via HAP als "Gerät".
- Steuerung in HomeKit Problemlos möglich, der HomeKit Status wird auch an die CCU übermittelt.
- Steuerung der die CCU mit Programm in dem ich Direkt den Dimmwert auf das CUxD Gerät setze.
- Funktion ist gegeben, nur HomeKit sprich HAP bekommt von der Änderung nichts mit.
- Wird HomeKit geschlossen und wieder geöffnet stimmt der Status.

Von daher meine Frage, ob ich die Status Aktualisierung die beim erneuten öffnen der HomeKit App geschieht auch manuell antriggern kann?

**Comment by thkl** [comment]
Ahhhh den Schönheitsfehler hab ich ganz überlesen. Das ist mit obigem Commit gefixt und in nächster Version drin.
