### ISSUE TITLE
Seit update auf RPM 20200919 & 0.0.54 Sysvar-Probleme und Neustart-Freezes

### ISSUE THREAD

**Issue by MattN82** [thkl/hap-homematic#204]
Wie schon im Titel geschrieben:

Seit diesen Updates läuft hap-homematic zwar. Ein Neustart des Services lässt sorgt dafür, dass es beim "Neustartversuch" bleibt. Schließen der Seite und erneutes Öffnen: Nicht erreichbar. Erst ein Neustart der CCU/RPM sorgt dafür, dass das Webinterface wieder erreichbar ist.

Normalerweise starte ich das nichts groß manuell neu...es ist mir nur aufgefallen weil (anderes Problem): Seit den Updates neuangelegte Systemvariablen (in der CCU) lassen sich zwar in hap-homematic auswählen und tauchen in HomeKit auf. Ein Schalten des Switches in Homekit schaltet aber NICHT mehr die Systemvariable. Einfach...kein Effekt, obwohl alle Werte identisch sind mit den VOR den Updates angelegten Systemvariablen.

Falls das relevant ist (weil ich diese ganze v11,v14,etc.-Geschichte nur am Rande mitbekommen hab): Bei mir läuft immer noch die ursprünglich installierte V11....halt hochgepatched bis zur aktuellen 0.0.54

**Comment by MattN82** [comment]
Ich hab mal ein paar Systemvariablen-Schaltungsvorgänge vorgenommen und die entsprechenden Stellen aus Debug-Log rausgezogen (falls das was bringt):

- [HAP Server] [Variable] set false
[Tue Oct 13 2020 15:42:34 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject(ID_SYSTEM_VARIABLES).Get('Lichtautomatik Raum 1);if (o){Write(o.State(false));}
[Tue Oct 13 2020 15:42:34 GMT+0200 (CEST)] debug - [HAP Server] [Rega] result is true
[Tue Oct 13 2020 15:42:34 GMT+0200 (CEST)] debug - [HAP Server] [Variable] set Result true
[Tue Oct 13 2020 15:42:37 GMT+0200 (CEST)] debug - [HAP Server] [Variable] set true
[Tue Oct 13 2020 15:42:37 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject(ID_SYSTEM_VARIABLES).Get('Lichtautomatik Raum 1');if (o){Write(o.State(true));}
[Tue Oct 13 2020 15:42:37 GMT+0200 (CEST)] debug - [HAP Server] [Rega] result is true
[Tue Oct 13 2020 15:42:37 GMT+0200 (CEST)] debug - [HAP Server] [Variable] set Result true
[Tue Oct 13 2020 15:42:39 GMT+0200 (CEST)] debug - [HAP Server] [Variable] set false
[Tue Oct 13 2020 15:42:39 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject(ID_SYSTEM_VARIABLES).Get('Lichtautomatik Raum 2');if (o){Write(o.State(false));}
[Tue Oct 13 2020 15:42:39 GMT+0200 (CEST)] debug - [HAP Server] [Rega] result is 
[Tue Oct 13 2020 15:42:39 GMT+0200 (CEST)] debug - [HAP Server] [Variable] set Result 
[Tue Oct 13 2020 15:42:40 GMT+0200 (CEST)] debug - [HAP Server] [Variable] set true
[Tue Oct 13 2020 15:42:40 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject(ID_SYSTEM_VARIABLES).Get('Lichtautomatik Raum 2');if (o){Write(o.State(true));}
[Tue Oct 13 2020 15:42:40 GMT+0200 (CEST)] debug - [HAP Server] [Rega] result is 
[Tue Oct 13 2020 15:42:40 GMT+0200 (CEST)] debug - [HAP Server] [Variable] set Result 
[Tue Oct 13 2020 15:42:41 GMT+0200 (CEST)] debug - [HAP Server] [RPC] event for HmIP-RF.CENTRAL:0.PONG with value hm-rpc.1
[Tue Oct 13 2020 15:42:42 GMT+0200 (CEST)] debug - [HAP Server] [Variable] set false
[Tue Oct 13 2020 15:42:42 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject(ID_SYSTEM_VARIABLES).Get('Lichtautomatik Raum 3');if (o){Write(o.State(false));}
[Tue Oct 13 2020 15:42:42 GMT+0200 (CEST)] debug - [HAP Server] [Rega] result is 
[Tue Oct 13 2020 15:42:42 GMT+0200 (CEST)] debug - [HAP Server] [Variable] set Result 
[Tue Oct 13 2020 15:42:44 GMT+0200 (CEST)] debug - [HAP Server] [Variable] set true
[Tue Oct 13 2020 15:42:44 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject(ID_SYSTEM_VARIABLES).Get('Lichtautomatik Raum 3');if (o){Write(o.State(true));}
[Tue Oct 13 2020 15:42:44 GMT+0200 (CEST)] debug - [HAP Server] [Rega] result is 
[Tue Oct 13 2020 15:42:44 GMT+0200 (CEST)] debug - [HAP Server] [Variable] set Result 



Kann es sein. (Laienverständnis), dass hap-homematic keine Rückmeldung von der CCU bekommt, was der tatsächliche Status ist? Das bei "Rega result is" ist das einzige was mir jetzt spontan an Unterschied aufgefallen wäre

**Comment by thkl** [comment]
Das alte V11 Addon (das ist auch für den Start des hap-daemon nötig) funktioniert in der aktuellen RM Version nicht mehr richtig. Deswegen würde ich empfehlen das Addon auf die aktuelle Version zu aktualisieren. Damit funktioniert der Restart auf  RM 3.53.30.20200919 zumindest wieder richtig.

Die Variablenfrage habe ich nicht verstanden ? Was ist da das Problem ?

**Comment by MattN82** [comment]
Zum Restart-Problem:
Alles klar. Aktualisieren heisst: Über Einstellungen - Systemsteuerung - Zusatzsoftware die aktuelle Version "drüberinstallieren"?

Zum Variablenproblem:
Sorry...hatte vorhin zwischen Tür und Angel geschrieben. Ich verwende in meiner CCU/RPM mehrere Logikwert-Systemvariablen (0 und 1 bzw aktiv/inaktiv). Deren Zustand nehme ich als Programmtrigger, um entweder global (ganzes Haus) oder selektiv (einzelne Räume) die Ansteuerung der Lichter/deren Dimmwerte in Abhängigkeit von der Tageszeit automatisch laufen zu lassen.

Die Logik funktioniert hierbei so, dass für die Lichtautomatik im Bad z.b. sowohl "Lichtautomatik global" als auch "Lichtautomatik Bad" aktiv sein müssen. Deaktiviere ich letzteres, rennt die Lichtautomatik im Rest des Hauses weiter.

Diese Systemvariablen flansche ich mittels deines "Variablen"-Reiters als Schalter an HomeKit dran, damit ich per Sprache und Switch einzelne Bereiche ein oder ausschalten kann.

Das hat alles wunderbar funktioniert....bis zu den Updates. Heute hab ich nen neuen Bewegungsmelder von ELV bekommen, um einen bisher nicht automatisierten Raum mit einer Lichtautomatik auszustatten. Alles gemacht wie immer:
Variable angelegt, Logikwert, aktiv/inaktiv. Nach Restart der CCU (sonst findet hap-homematic die neue Variable nicht...und "service restart" führt ja zum crash) kann ich dann in hap-homematic die Variable auch auswählen, kann nen "Schalter" draus machen und er taucht in HomeKit auf.

Aber er toggled eben NICHT den Wert der dazugehörigen Systemvariable in der CCU/RPM. Am Schalter in HomeKit sieht man kein Problem. Er lässt sich an und ausschalten. Aber in der CCU passiert halt nix.
Alle anderen Sysvariablen (die von vor den Updates) funktionieren einwandfrei.

**Comment by thkl** [comment]
ok.Also bei Lichtautomatik Raum 2 funktioniert es; bei Lichtautomatik Raum 3 nicht ?

**Comment by MattN82** [comment]
Fast :-) Bei Raum 1 funktioniert es (das ist ein "alter" Raum vor den Updates). 
Bei Raum 2 und 3 nicht.
Wobei Raum 2 und 3 ein und derselbe Raum sind, wo ich nur zum Testen 2 verschiedene Variablen unterschiedlicher Benennung ausprobiert hab (Raum 1,2,3 sind nur Platzhalternamen...um auszuschließen dass bei der realen Benennung das Problem liegt).

**Comment by thkl** [comment]
Kannst Du dann mal bitte zum Test die Lichtautomatik Raum 3 ohne Leerzeichen schreiben .. nur so ne Idee ;)

**Comment by thkl** [comment]
Oder vielleicht das Script mal auf der CCU im Script Tester ausprobieren (Der ist dort wo man Programme baut)

```
object o = dom.GetObject(ID_SYSTEM_VARIABLES).Get('Lichtautomatik Raum 3');if (o){Write(o.State(true));}else{Write('VarNotFound');}
```

Wenn die Variable im DOM nicht gefunden wird kommt VarNotFound in die Ausgabe

**Comment by MattN82** [comment]
Und...sorry wenn ich da nochmal nachhake aber könntest du mir grad zu meiner "drüberinstallier"-Frage mit der nächsten Antwort nen schnellen Daumen hoch oder runter geben? :-)

Zu den Leerzeichen: Hab ich getan...Raum 3 IST die Variante "Raum 2 ohne Leerzeichen"...womit "Raum 3" und "Raum 1" (der funktioniert!), Formatierungstechnisch identisch sind. Das kanns also eigentlich nicht sein.

In "Klarnamen" :-D

Raum 1 = Lichtautomatik Bad
Raum 2 = Lichtautomatik Küche oben (könnte das Leerzeichen ein Problem sein)
Raum 3 = Lichtautomatik Küche (geht auch nicht).

Zum Skript: Moment...ich probiers

**Comment by thkl** [comment]
Ja das Addon kann einfach drüber gebügelt werden. Das erzeugt auch keinen Neustart wenn der Daemon gefunden wird ..

**Comment by MattN82** [comment]
Gell? Das scheint echt der einzige Unterschied zu sein. 

Zwischenbilanz: Das Service-Restart-Problem ist vom Tisch. ab 0.0.14 drüberinstalliert. Geht.
Das Variablenproblem ist unverändert. Ich schmeiß die Variablen jetzt nochmal aus der CCU und hap raus und leg sie nach einem sauberen CCU reboot nochmal frisch an.

Ich poste dann das Ergebnis.

**Comment by thkl** [comment]
Mal einen kürzeren Namen probieren "LAKO" zb für "Licht Automatik Küche oben" vielleicht ;) nur so als Test *g* Der Aktor kann ja in HomeKit einen eigenen Namen bekommen  der ist sowieso zu für Siri ;o)

**Comment by MattN82** [comment]
Ich...denke ich habs. Es ist der Umlaut. "Kueche" hat das Problem gelöst. 

Also nochmal zum Mitschreiben und Staunen :-D : "Küche" = böse..."Kueche" geht einwandfrei.

**Comment by MattN82** [comment]
Es scheint als wären bei mir mal wieder ein paar Punkte zusammengekommen, wo dein Plugin mal wieder so garnix dafürkonnte :-)

Ich...glaube wir können hier dichtmachen. Danke Thomas für den wie immer relativistisch-schnellen Support :-D

**Comment by thkl** [comment]
Hmm Umlaute sind schwer ;) Da kann viel schief gehen ...
