### ISSUE TITLE
Anzahl der „Verbundenen Geräte“ stimmt nicht mit den tatsächlichen Geräten überein

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#205]
Hallo,

Ich habe meine CCU3 neu aufgesetzt und habe dadurch auch das PlugIn  neu konfiguriert. Vorher stimmten die Angaben überein. Nun ist es so, dass mir im HAP-Dashboard gerade einmal 4 verbundene Geräte angezeigt werden, obwohl ich 22 Geräte habe.
![9FA8B4C5-F4D1-45F0-BCBE-97FF83AD921C](https://user-images.githubusercontent.com/72799068/95882344-e2ab1980-0d79-11eb-8711-842376644a81.png)
![BB2A50AF-53D8-40F9-9EBC-ACFB53BE3F97](https://user-images.githubusercontent.com/72799068/95882355-e76fcd80-0d79-11eb-8ee7-d6482adf1299.jpeg)

Danke und lieben Gruß

**Comment by thkl** [comment]
In der CCU wurde das Backup zurückgespielt .. oder wurde alles von 0 auf neu aufgesetzt ?
Weil das schaut mir schon sehr komisch aus, zumal die Geräte ja in HomeKit da sind ...

**Comment by gerd2005** [comment]
Nein, kein Backup. Alles von Anfang.

**Comment by thkl** [comment]
Nach einem Restart des HAP Daemons über die WebOberfläche bleiben die verschwunden ?

**Comment by gerd2005** [comment]
Ich habe die CCU schon mehrmals neu gestartet, HAP über „Zusatzsoftware“ mehrmals neugestartet und auch deinen Weg bin ich schon mehrmals gegangen. Letzteres habe ich gerade erneut gemacht, leider ohne Erfolg. Es kann auch nur ein Darstellungsproblem sein. Wenn man ein Gerät löscht, rutscht ein anderes hinterher. Es sind in der Tabelle also mehr Geräte vorhanden, als angezeigt werden. Was eigentlich auch klar ist, weil HomeKit wunderbar funktioniert. Alle Gerät reagieren wie gewünscht.

**Comment by thkl** [comment]
Hmm die Tabelle hat eine maxRecords Einstellung von 10. Und wenn die überschritten wird, dann wir unten ein Pager eingeblendet.  

Sehr komisch.

**Comment by gerd2005** [comment]
Ich versuche hier mal noch ein Verhalten zu beschreiben was ich heute entdeckt habe, was vielleicht bei der Fehlersuche hilft.

So sieht aktuell mein Büro aus:
![C9D74EB5-F8D9-4179-BCEE-A06DA6304AFB](https://user-images.githubusercontent.com/72799068/97414296-18b4d580-1904-11eb-9ffe-e5f3f3aa5356.jpeg)

So sieht es im PlugIn aus. Mein Büro taucht hier nicht auf. Auch ist unten kein Pager eingeblendet:
![A1C0B8FB-40FF-4C5E-A321-4EBFE5A825BB](https://user-images.githubusercontent.com/72799068/97414550-66c9d900-1904-11eb-923c-3456289718bf.png)

Wenn ich nun bspw. mein Thermostat suche taucht es in der Suche auf und ich könnte es hinzufügen, obwohl es schon vorhanden ist:
![9771C840-3D9C-4FE6-B1E3-75D7162343D2](https://user-images.githubusercontent.com/72799068/97414679-94168700-1904-11eb-9503-8d5d97441b4d.png)

Nun füge ich den Kanal 1 ein weiteres mal hinzu und nenne das Gerät „Thermostat 2“:
![E149EDD1-0CF6-4107-A0C2-580937DE6922](https://user-images.githubusercontent.com/72799068/97414755-b01a2880-1904-11eb-8ca8-b432b321a874.png)

Nun erscheint das „Thermostat 2“ auf einmal in der Liste auf:
![EACFC0B3-01F3-4383-88F4-7CA2FE46E2BF](https://user-images.githubusercontent.com/72799068/97414999-f7a0b480-1904-11eb-89c0-012f68adc68a.png)

... und mein HomeKit sieht nun so aus. Das „Thermostat“ ist verschwunden, dafür wird nun „Thermostat 2“ angezeigt.
![2A932045-0237-40A7-8D13-58785D98DA40](https://user-images.githubusercontent.com/72799068/97415475-94635200-1905-11eb-90c9-00b35fa6357d.jpeg)

**Comment by gerd2005** [comment]
Kann es sein, dass alle Geräte nicht mitgezählt werden, die über den Assistenten nach der Installation hinzugefügt worden sind?

**Comment by thkl** [comment]
Nein eigentlich ist das Wurst on Assistent oder Nicht.

**Comment by gerd2005** [comment]
Ich habe das PlugIn einmal komplett deinstalliert und wieder neu installiert, sowie in HomeKit das Zuhause gelöscht. Anschließend habe ich alle Instanzen angelegt und in HomeKit hinzugefügt. Danach habe ich nach und nach die Geräte hinzufügen wollen. Die ersten beiden Geräte werden nun auch in HomeKit angezeigt, und auch die Anzahl „Verbundene Geräte“ ist korrekt mit 2. Das dritte Gerät wurde auch in HomeKit hinzugefügt, dieses erscheint aber nicht in dem PlugIn.

**Comment by gerd2005** [comment]
Ich hab den Fehler glaube ich. Anscheinend kann jeder Gerätename nur einmal verwendet werden.

In jedem Raum habe ich im Grunde ein Thermostat und ein Rollo. Ich habe diese Geräte auch nur so benannt und NICHT bspw. „Thermostat Büro“.
Anders gesagt: Im Raum „Büro“ ist 1 x „Thermostat und 1 x „Rollo“
Wenn ich nun im Raum „Badezimmer“ das „Thermostat“ hinzufüge, klappt das nicht. Benenne ich das Gerät jedoch „Thermostat 2“, klappt es.

Kannst du nachvollziehen wie ich das meine?

**Comment by thkl** [comment]
Oh ok. Pro Instanz darf immer nur einmal der gleiche Name auftreten weil daraus die ID berechnet wird. 

Ich teste mal warum das übergreifend nicht geht.

**Comment by gerd2005** [comment]
Pro Instanz ist das ja logisch. Im Wohnzimmer bspw. Habe ich zwei Rollos. Die habe ich Rollo 1 und Rollo 2 benannt.

Ok, also ich habe jetzt alle Geräte manuell ohne Assistenten hinzugefügt. Es bleiben bei mir 8 Geräte in den „verbundenden Geräte“. Warum 8? Weil das genau die Geräte sind, die unterschiedliche Namen (Name in HomeKit) haben.
![BE71D2BA-5D26-4833-8574-E4B834DC6612](https://user-images.githubusercontent.com/72799068/97982590-54541180-1dd4-11eb-8989-f439d8b8f2ed.jpeg)

**Comment by thkl** [comment]
Ok, das Problem ist wirklich der gleiche Name.

Aus dem Namen wird die UUID abgeleitet (das macht das hap-nodejs Modul) . Da ich diese ID aber als Index für den Speicher des Gerätes nehme, egal in welcher Instanz es lebt, wird Gerät 2 in der Liste beim Hinzufügen Gerät 1 überschreiben.

Das hat keinen Einfluss auf HomeKit, denn dort leben die Geräte ja in verschiedenen Instanzen, aber eben auf die WebUI.

Ich nehme jetzt als Index, die BridgeID und die ID des Gerätes. Dann sollte es gehen.

**Comment by gerd2005** [comment]
Hervorragend! Das hört sich aber so an, als ob alle Geräte neu hinzugefügt werden müssten, oder? Oder zeigt er bei mir dann nach dem Update direkt alle Geräte an?

**Comment by thkl** [comment]
Sie sind einfach wieder da :) Man muss nichts neu einbinden.
