### ISSUE TITLE
Behanghöhe von Rollos realisieren

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#206]
Hallo,

wie kann ich es realisieren, dass ich Siri „Öffne das Rollo im Wohnzimmer um 50%“ sagen kann. Muss ich dafür die entsprechenden Laufzeiten in der CCU3 angeben, oder mache ich das irgendwo in dem PlugIn?

Leider habe ich dazu keine Informationen gefunden.

**Comment by thkl** [comment]
"Hey Siri, setze Rollo xxx auf 50%" sollte funktionieren.  Ich liefere dann einen Level 0.5 an die CCU. 

Ich benutze das selber mit TRÅDFRI Rollos die an der CCU hängen.

**Comment by gerd2005** [comment]
Die IKEA Dinger sind doch von Haus aus mit HomeKit kompatibel, oder? Ich rede von „richtigen“ Außenrollos. Diese steuere ich mit HMIP-FROLL. Ich habe es gerade noch einmal ausprobiert, es funktioniert aber nicht. Siri bestätigt mir zwar „Rollo wird auf 50%“ gestellt, das Rollo fährt aber bis zur Endstellung durch.

**Comment by timwegenerDE** [comment]
Zumindest bei den BROLL funktioniert das nur nach Kalibrierungsfahrt in der CCU also Hinterlegung der Fahtzeit.

**Comment by thkl** [comment]
> Die IKEA Dinger sind doch von Haus aus mit HomeKit kompatibel, oder?

Ja aber ich will ja das die CCU die automatisch steuert. 

Funktioniert denn die Einstellung der Behanghöhe via CCU Weboberfläche? Also wenn man das dort auf 50% stellt.

**Comment by gerd2005** [comment]
> > Die IKEA Dinger sind doch von Haus aus mit HomeKit kompatibel, oder?
> 
> Ja aber ich will ja das die CCU die automatisch steuert.

Ah ok... ich wäre vermutlich hingegangen und hätte die direkt ins HomeKit gebracht mit einer Automation. Gibt es einen Vorteil bei deinem Weg?

> Funktioniert denn die Einstellung der Behanghöhe via CCU Weboberfläche? Also wenn man das dort auf 50% stellt.
Nein, das funktioniert nicht, weil ich die Laufzeiten noch nicht eingetragen habe. Das war ja im Grunde meine Eingangsfrage. „Wo und wie muss ich das genau einstellen?“ CCU, oder HAP-PlugIn.

**Comment by thkl** [comment]
> Ah ok... ich wäre vermutlich hingegangen und hätte die direkt ins HomeKit gebracht mit einer Automation. Gibt es einen Vorteil bei deinem Weg?

Ja aber ich habe Hue und TRÅDFRI über ein eigenes Zigbee Gateway laufen. Damit ich nicht 1000 Kästchen und Zeugs habe.  
Die CCU selbst verwaltet auch nur die Geräte. Die Automationen Läufen über eine eigene JavaScript Engine.

> Nein, das funktioniert nicht, weil ich die Laufzeiten noch nicht eingetragen habe. Das war ja im Grunde meine Eingangsfrage. „Wo und wie muss ich das genau einstellen?“ CCU, oder HAP-PlugIn.


In der CCU. Wie oben schon beschrieben, das CCU Gerät hat eine Level Einstellung.  Diese beliefere ich aus HomeKit.  Wie diese jetzt am Aktor umgesetzt wird, hängt an der CCU.

**Comment by gerd2005** [comment]
Ich habe nun die Laufzeiten in die CCU eingetragen ... und siehe da ... es funktioniert einwandfrei. Danke für die Unterstützung.
