### ISSUE TITLE
Schaltaktor als Türöffner = Türsummer

### ISSUE THREAD

**Issue by neyStyle** [thkl/hap-homematic#207]
Hey,

ich habe einen Schaltaktor um meine Türen im Haus zu öffnen.
Leider werden diese in Homekit ja als Lichtschalter angezeigt,
kann ich dies umstellen um nicht zu sagen:
"Hey Siri, schalte die Haustür ein"
sondern
"Hey Siri, öffne die Haustür"

Schaltaktor: https://www.amazon.de/Homematic-104225-HomeMatic-Funk-Schaltaktor-Wandmontage/dp/B005JRW96C/ref=sr_1_3?dchild=1&keywords=homematic+4fach+schaltaktor&qid=1602685864&sr=8-3

lg und ansonsten Top Zusatzsoftware

**Comment by thkl** [comment]
für den Anfang geht auch "Siri aktiviere die Haustür" ;)

Geplant ist eine Implementierung der VideoDoorBell .. da würde sowas gehen.

**Comment by thkl** [comment]
Ich habe gerade nachgeschaut , es gibt in HomeKit einen DoorLock Mechanismus .. den kann ich dafür verwenden.
Also ja kann man machen

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/96036473-cfc14380-0e64-11eb-81be-732b8cc67935.png)

Dumdiedum ....

**Comment by neyStyle** [comment]
Sehr geil, solche Menschen liebe ich. Bekommen ein Problem mitgeteilt und lösen es direkt.
Nicht auf die lange Bank schieben sondern eben machen.
Top, das auch meine Arbeitsweise. 

Thumbs up

**Comment by meistermolli** [comment]
Bitte dierekt auch für den Homematic PCBS ;-) der öffnet meinen E-Öffner an der Tür, zumindest bis das update von dir kommt und die Keymatic das kann. Anschließend kann ich dann die Tagesfallen Funktion mit dem E-Öffner steuern.

Zu den Geräten die als Haustür gesteuert werden - die gehen dann nur bei Entspertem iPhone oder Apple Watch? Korrekt?
Nicht dass jemand am offenen Fenster rein ruft :-P ...

**Comment by neyStyle** [comment]
> Zu den Geräten die als Haustür gesteuert werden - die gehen dann nur bei Entspertem iPhone oder Apple Watch? Korrekt?
> Nicht dass jemand am offenen Fenster rein ruft :-P ...

Dürfte eh nicht gehen, da Siri nur auf deine Stimme triggert, das ist anders als bei Alexa

**Comment by thkl** [comment]
Das dürfte nur mit einem entsperrten iPhone in der Nähe gehen

**Comment by neyStyle** [comment]
Eben getest, 

SPITZE - WO kann ich Donaten

**Comment by meistermolli** [comment]
@neyStyle Dann hast du jetzt den Schaltaktor als schloss angezeigt? Kannst du kurz sceenshots Posten wie du das Gerät angelegt hast und wie es nun aussieht?

Danke dir .

**Comment by neyStyle** [comment]
Hey,

na klar.


Mit freundlichen Inselgrüßen
Heiko Papenfuß

neyStyle
http://www.neystyle.de
Mail: info@neystyle.de
Tel:  +49 151 58767143
