### ISSUE TITLE
Pushmitteilungen in Homekit?

### ISSUE THREAD

**Issue by itylux** [thkl/hap-homematic#208]
Hi, 

an dieser Stelle nochmal Danke für dieses tolle Plugin!
Wir haben da eine grundsätzliche Frage: Ist es in irgendeiner Form möglich individuelle Pushmitteilungen an Homekit zu senden? Bzw. wird es überhaupt in einer Form möglich sein?
Bspw. Wenn die Alarmanlage ausgelöst wird.

Vergleichbar mit den Pushmitteilungen aus Pocket Control/ Pushover / Telegram etc. 

Danke schonmal vorab!

**Comment by thkl** [comment]
HomeKit selber schickt Pushmitteilungen über Statusänderungen ausgewählter Geräte. Das kann man in den jeweiligen Gerätesettings des gewünschten Gerätes in der Apple Home App einstellen. 

Dort kann auch bei geteilten Homes eingestellt werden, wer die Nachricht bekommt.  

Das funktioniert in der Regel für Kontakte, Alarmsirenen und einige andere Sachen.

**Comment by itylux** [comment]
Vielleicht war ich nicht präzise genug.
Wenn wir die Alarmanlage aktivieren (derzeit noch über Pocketkontrol) bekommen wir jeweils eine Mitteilung.
"Hüllschutz aktiviert" "Vollschutz aktiviert" etc.

Wenn Fenster oder Türen noch offen stehen sollten: "Vollschutz NICHT aktiviert. Bitte alle Türen und Fenster schließen"
Das alles prüfen wir über Variablen in der CCU. 

Wir haben keine Möglichkeit gefunden beim auslösen des Alarms eine von uns eingestellte Pushmitteilung anzeigen zu lassen. 
Diese Möglichkeit suchen wir gerade. 

Danke Dir

**Comment by thkl** [comment]
Nein, das geht nicht. Man kann keine selbst definierten Push Meldungen schicken. Das kann HomeKit nicht.  

Das müsste über einen 3rd party Push Provider gemacht werden.

**Comment by itylux** [comment]
hm.. schade. Hoffen wir das Apple da vielleicht in Zukunft eine Schnittstelle bereitstellt. Danke!

**Comment by thkl** [comment]
Ich glaube das wird eher nicht passieren

**Comment by gerd2005** [comment]
Hallo,

so richtig verstehe ich das nicht, warum
das nicht möglich sein soll. 
Kann man keine Automation anlegen wie:
WENN „Die letzte Person verlässt Privat“ und Fensterkontakt = geöffnet DANN Push-Benachrichtigen 

Das muss doch in den Automationen realisierbar sein .... das ist doch absoluter Standard...

**Comment by gerd2005** [comment]
Ja ok... es fehlt die Möglichkeit eine „UND-Bedingung“ zu hinterlegen, oder?
![2AF710ED-0E23-405E-AD8C-EE243E6D0704](https://user-images.githubusercontent.com/72799068/96315847-b0661a00-100e-11eb-8cbc-6fefd165b2c1.jpeg)

**Comment by timwegenerDE** [comment]
Hi @gerd2005,

du kannst noch ein „Wenn“ in das andere ziehen. Das ersetzt das „Und“:

![8CEFB855-845D-4F46-A873-AAC543D0AC58](https://user-images.githubusercontent.com/56134910/96329593-d27f8c80-104e-11eb-8d61-98d8d234857f.jpeg)

Ich glaube aber du wirst mit deinem Kurzbefehl so nicht glücklich werden. Selbst wenn du es hinbekommen würdest, kommt ja die Pushnachricht erst wenn du schon um die Häuserecke bist. Du müsstest immer zurück.

Als Idee:
Ich habe im Hausflur einen Bewegungsmelder. Wenn der etwas entdeckt schaltet der eine Lampe (eigentlich den hmip-bsl) ein, wenn noch Fenster offen sind. 

![23B8113F-F357-469D-8663-FCF4D01C43CB](https://user-images.githubusercontent.com/56134910/96329655-82ed9080-104f-11eb-8231-2b64ec45625c.jpeg)

**Comment by thkl** [comment]
Mal auf den Push zurückzukehren: über das Vehikel des Siri Shortcuts würde das gehen wenn man noch einen externen Pushprovider benutzt. Zb: https://www.pushcut.io/homekit
