### ISSUE TITLE
Willkommen - Auswahl wird nicht zwischengespeichert

### ISSUE THREAD

**Issue by mano87** [thkl/hap-homematic#209]
Hallo,
bei einer größeren Anzahl an Geräten und Räumen werden diese auf entsprechende Seiten im Willkommenswizard verteilt. Leider werden die über die Checkbox ausgewählten Items beim Seitenwechsel nicht beibehalten. Das sollte gerade bei einer Mehrfachauswahl möglich sein.

**Comment by thkl** [comment]
ähnlich https://github.com/thkl/hap-homematic/issues/203
