### ISSUE TITLE
Fehler: Der Neigungssensor "HM-Sec-TiS" wird als Bewegungsmelder angezeigt.

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#21]
Hallo THomas

Der Neigungssensor wird leider "Bewegungsmelder" statt "Kontaktsensor" (wie in der 219er) angezeigt .... kannst Du das bitte ergänzen ? Der Kontaktservice steht nicht zur Auswahl :-)

lg Richard

**Comment by thkl** [comment]
Der Neigungssensor hat nur einen Motion Datenpunkt ... deswegen ist er zu den Bewegungsmeldern gewandert ...

**Comment by roe1974** [comment]
👍

**Comment by roe1974** [comment]
funktioniert ! 👍
