### ISSUE TITLE
QR-Code für Instanzen

### ISSUE THREAD

**Issue by mano87** [thkl/hap-homematic#210]
Hallo,
als FeatureRequest würde ich hiermit in der Übersichtsseite/Tabelle der Instanzen/Räume eine Möglichkeit zum Aufruf des jeweiligen HomeKit QR-Codes vorschlagen. "HomeKit-Konfigurationscode anzeigen"

**Comment by thkl** [comment]
Ja, das geht, aber nur für Instanzen, die mit einer zukünftigen Version angelegt werden.
Hintergrund: Derzeit benutze ich Kleinbuchstaben im username der Bridge. Die Methode über den SetupURL Code setzt aber Großbuchstaben voraus. Ich kann natürlich jetzt nicht alle Usernamen pauschal umbauen, denn dann würde Home nicht mehr auf die vorhandenen Instanzen connection können.

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/96298726-3c6a4880-0ff3-11eb-93ae-1b57668133cf.png)

**Comment by mano87** [comment]
Das hört sich doch aber gut an :-)

**Comment by sailor79** [comment]
added to wiki
