### ISSUE TITLE
Hue-Lampen für HomeKit bereitstellen

### ISSUE THREAD

**Issue by fmaack** [thkl/hap-homematic#211]
Moin,

ich habe ein Setup, bei dem ich einige Lightify-Lampen/Steckdosen an meiner Hue-Bridge angemeldet habe. Die wiederum ist mit der ccu verbunden. Ich kann problemlos über homematic-Skripte etc. diese Geräte steuern.

Leider werden die Geräte nicht für die Nutzung per HomeKit angeboten. Gibt es hier einen technischen Grund für oder können diese virtuellen Geräte ergänzt werden?

Hue lässt sich zwar selbst in HomeKit integrieren, das funktioniert aber nur mit Original Philips-Lampen.

Vielen Dank!

**Comment by thkl** [comment]
Tauchen die Lampen als Geräte in der CCU auf ?

**Comment by fmaack** [comment]
guten morgen!
ja, tuen sie.
<img width="1171" alt="Bildschirmfoto 2020-10-17 um 08 09 01" src="https://user-images.githubusercontent.com/11184006/96329739-1d4dd400-1050-11eb-921b-9776b09b85e4.png">

**Comment by thkl** [comment]
Dann bitte mal über das WebUi / Hilfe das Devicefile für eines der Lampen erstellen und hier anhängen.  Wie das geht steht dort.

**Comment by fmaack** [comment]
Ich habe einmal die Konfig-Datei für die GU10-Spots (Osram Lightify PAR16 LED Reflektorlampe Tunable White, Dimmbar) und für die Zwischenschaltsteckdose (Osram Plug) erzeugt: 

Ich kann hier keine json-Datei anhängen, daher der Inhalt.

{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "VIR-LG-ONOFF",
      "address": "1079891751ABCD",
      "type": "VIR-LG-ONOFF",
      "channels": [
        {
          "id": 1001,
          "name": "1079891751ABCD:0",
          "intf": 0,
          "address": "1079891751ABCD:0",
          "type": "VIP-MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "1079891751ABCD:1",
          "intf": 0,
          "address": "1079891751ABCD:1",
          "type": "VIR-LG-ONOFF-CH",
          "access": 255
        }
      ]
    }
  ]
}

{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "VIR-LG-WHITE-DIM",
      "address": "2002605106ABCD",
      "type": "VIR-LG-WHITE-DIM",
      "channels": [
        {
          "id": 1001,
          "name": "2002605106ABCD:0",
          "intf": 0,
          "address": "2002605106ABCD:0",
          "type": "VIP-MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "2002605106ABCD:1",
          "intf": 0,
          "address": "2002605106ABCD:1",
          "type": "VIR-LG-WHITE-DIM-CH",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by act2000** [comment]
[VIR-HUE-Tradfi.zip](https://github.com/thkl/hap-homematic/files/5395125/VIR-HUE-Tradfi.zip)

Hallo,
ich möchte ebenfalls einige Geräte/Lampen an HAP anbinden und sehe diese nicht im Webinterface. 
Anbei die Files für eine Tradfi Lampe sowie eine Hue Go, beide über die Hue Bridge an die Homematic angebunden.

Ich habe auch/noch eine Osram Bridge an der Homematic, die Geräte sind ebenfalls in der Homematic sichtbar und bedienbar aber in Hap nicht verknüpfbar.

Wenn weitere Infos benötigt werden bitte melden.

Danke für dieses Projekt.

Gruss
Andreas

**Comment by thkl** [comment]
Die Hue Bridge ist doch aber direkt schon HomeKit fähig oder ?

**Comment by act2000** [comment]
Ja, die Hue Lampen schon aber Tradfi oder Osram an der Hue Bridge nicht. Tradfi mit der systemeigenen Bridge wohl auch aber ich würde gerne alles auf die Hue Bridge bringen, Tradfi Bridge müsste ich noch kaufen und Osram wird je demnächst das Zeitliche segnen.
Gruß
#AS

**Comment by thkl** [comment]
> [VIR-HUE-Tradfi.zip](https://github.com/thkl/hap-homematic/files/5395125/VIR-HUE-Tradfi.zip)
Zu diesen Geräten gibt es leider keine Doku bei eq3 weil das nur virtuelle Geräte sind.


VIR-LG-DIM ist nur dimmbar ? oder kann die auch noch was andere
VIR-LG-RGBW-DIM müsste den normalen Hue Lampen entsprechen also analog den EQ3 RGB Aktoren funktionieren ?

**Comment by thkl** [comment]
Ok hier brauch ich ein bissel Hilfe von @act2000  und @fmaack 

für die Geräte VIR-LG-DIM VIR-LG-RGBW-DIM und VIR-LG-WHITE-DIM finde ich nichts an Doku wie Datenpunkte etc aussehen. Deswegen hier ein kleines Script was über die CCU Programme/Verknüpfungen - Script testen einmal ausgeführt werden muss. 

Bitte vorher devName gegen den Gerätenamen des VIR-* Gerätes der CCU ersetzen.
Was das Script macht, es ermittelt alle Kanäle und Datenpunkte der Kanäle mit deren Eigenschaften des angegebenen Gerätes.

ich bräuchte Ergebnis das pro Gerätetyp einmal hier angehangen.

```
string devName = "XXXXX";
object oDevice = dom.GetObject(devName);
string sChnId;string sDpId;
Write("{\"id\": " # oDevice.ID() # ", \"address\": \"" # oDevice.Address() # "\", \"name\": \"" # oDevice.Name() # "\",");var inf = dom.GetObject(oDevice.Interface());if (inf) {Write("\"ifid\": " # oDevice.Interface() # ", \"ifname\": \"" # inf.Name() # "\",");}Write("\"type\": \"" # oDevice.HssType() # "\",  \"visible\": " # oDevice.Visible().ToString() # ",  \"ready\": " # oDevice.ReadyConfig().ToString() # ",");Write("\"channels\":[");boolean cFirst = true;foreach(sChnId, oDevice.Channels()) {object oChannel = dom.GetObject(sChnId);if (cFirst) {cFirst = false;} else {WriteLine(",");}Write("{\"id\": " # sChnId # ", \"address\": \"" # oChannel.Address() # "\", \"name\":\"" # oChannel.Name() # "\",");Write("\"type\": \"" # oChannel.HssType() # "\", \"aes\": " # oChannel.ChnAESActive().ToString() # ", \"dir\":" # oChannel.ChnDirection() # ",");Write("\"archive\": " # oChannel.ChnArchive().ToString() # ", \"visible\": " # oChannel.Visible().ToString() # ", \"rights\":\"" # oChannel.UserAccessRights(iulOtherThanAdmin).ToString() # "\",");boolean dpFirst = true;Write("\"dp\":[");if (oChannel.ChnDirection()==2) {object oDP = oChannel.DPByHssDP('WORKING');if (oDP) {dpFirst = false;Write("{\"id\": " # sDpId # ", \"name\": \"" # oDP.Name().StrValueByIndex(".", 2) # "\", \"address\":\"" # oDP.Name() # "\",");Write("\"type\": \"" # oDP.TypeName() # "\", \"operations\": " # oDP.Operations() # ",");Write("\"vtype\": " # oDP.ValueType() # ", \"vstype\": " # oDP.ValueSubType() # "}");}}foreach(sDpId, oChannel.DPs().EnumUsedIDs()) {object oDP = dom.GetObject(sDpId);if (dpFirst) {dpFirst = false;} else {WriteLine(",");}Write("{\"id\": " # sDpId # ", \"name\": \"" # oDP.Name().StrValueByIndex(".", 2) # "\", \"address\":\"" # oDP.Name() # "\",");Write("\"type\": \"" # oDP.TypeName() # "\", \"operations\": " # oDP.Operations() # ",");if (oDP.ValueUnit() != "") {Write("\"vunit\":\"");WriteURL(oDP.ValueUnit());Write("\",");}Write("\"vtype\": " # oDP.ValueType() # ", \"vstype\": " # oDP.ValueSubType() # "}");}Write("]}");}Write("]}");
```

**Comment by act2000** [comment]
Versuche ich heute Abend auszulesen, Tradfi ist nur eine Dimmbare sonst nix weiter.
Gruß
Andreas

**Comment by fmaack** [comment]
Hi,
hier die ausgaben für VIR-LG-WHITE-DIM (das ist der GU10-Spot, der dimmbar ist und der Weißton kann eingestellt werden - jedoch keine Farben) sowie den Zwischenstecker, der kann nur ON/OFF:

`{"id": 2632, "address": "HU-Terrasse Wa", "name": "VIR-LG-WHITE-DIM HU-Terrasse Wa","ifid": 1008, "ifname": "VirtualDevices","type": "VIR-LG-WHITE-DIM",  "visible": true,  "ready": true,"channels":[{"id": 2633, "address": "HU-Terrasse Wa:0", "name":"VIR-LG-WHITE-DIM HU-Terrasse Wa:0","type": "VIP-MAINTENANCE", "aes": false, "dir":0,"archive": false, "visible": true, "rights":"255","dp":[]},
{"id": 2634, "address": "HU-Terrasse Wa:1", "name":"Terrasse.Wand2","type": "VIR-LG-WHITE-DIM-CH", "aes": false, "dir":0,"archive": false, "visible": true, "rights":"255","dp":[{"id": 2635, "name": "LEVEL", "address":"VirtualDevices.HU-Terrasse Wa:1.LEVEL","type": "HSSDP", "operations": 3,"vunit":"100%25","vtype": 4, "vstype": 0},
{"id": 2636, "name": "WHITE", "address":"VirtualDevices.HU-Terrasse Wa:1.WHITE","type": "HSSDP", "operations": 3,"vunit":"100%25","vtype": 4, "vstype": 0}]}]}`

`{"id": 4374, "address": "HU-On/Off pl06", "name": "VIR-LG-ONOFF HU-On/Off pl06","ifid": 1008, "ifname": "VirtualDevices","type": "VIR-LG-ONOFF",  "visible": true,  "ready": true,"channels":[{"id": 4375, "address": "HU-On/Off pl06:0", "name":"VIR-LG-ONOFF HU-On/Off pl06:0","type": "VIP-MAINTENANCE", "aes": false, "dir":0,"archive": false, "visible": true, "rights":"255","dp":[]},
{"id": 4376, "address": "HU-On/Off pl06:1", "name":"VIR-LG-ONOFF HU-On/Off pl06:1","type": "VIR-LG-ONOFF-CH", "aes": false, "dir":0,"archive": false, "visible": true, "rights":"255","dp":[{"id": 4377, "name": "LEVEL", "address":"VirtualDevices.HU-On/Off pl06:1.LEVEL","type": "HSSDP", "operations": 3,"vunit":"100%25","vtype": 4, "vstype": 0}]}]}`

**Comment by act2000** [comment]
[HUE_Osram.zip](https://github.com/thkl/hap-homematic/files/5396830/HUE_Osram.zip)

Hallo,
anbei die Infos zu den Lampen/Steckdosen die ich nutze, Hue Original E27, nur dimmbar; Hue Ligthstrip, RGBW & Dimmbar, Hue Go V2, RGBW & Dimmbar, Tradfri E14, nur dimmbar; Osram Gardenpole, RGB & dimmbar; Osram Steckdosen, nur ein/aus, keine Messung und eine Gruppe aus drei Osram Steckdosen.

Danke für den Support.

Gruss
#as

**Comment by fmaack** [comment]
meine lightify-lampen die an die hue-bridge angelernt sind lassen sich jetzt mit 0.0.55 erfolgreich steuern. vielen dank!
