### ISSUE TITLE
Absturz beim anlegen von Instanzen / Zuweisen von Geräten

### ISSUE THREAD

**Issue by JarvisHome** [thkl/hap-homematic#213]
Habe ab und zu das Problem dass beim Anlegen von neuen Instanzen und zuweosen von Aktoren der hap-homeamtic plötzlich abstürzt nicht mehr reagiert (auch die Oberfläche ist dann weg). 

Nach einem Neustart geht wieder alles.
Das Problem tritt (leider) sporadisch auf. 

Ich hab folgendes in der Syslog gefunden:

```
Oct 18 12:28:35 homematic user.err rfd: XmlRpcClient error calling newDevices({"HAP_BidCos-RF.",{[ADDRESS:"BidCoS-RF",CHILDREN:{"BidCoS-RF:0","BidCoS-RF:1","BidCoS-RF:2","BidCoS-RF:3","BidCoS-RF:4","BidCoS-RF:5","BidCoS-RF:6","BidCoS-RF:7","BidCoS-RF:8","BidCoS-RF:9","BidCoS-RF:10","BidCoS-RF:11","BidCoS-RF:12","BidCoS-RF:13","BidCoS-RF:14","BidCoS-RF:15","BidCoS-RF:16","BidCoS-RF:17","BidCoS-RF:18","BidCoS-RF:19","BidCoS-RF:20","BidCoS-RF:21","BidCoS-RF:22","BidCoS-RF:23","BidCoS-RF:24","BidCoS-RF:25","B
dCoS-RF:26","BidCoS-RF:27","BidCoS-RF:28","BidCoS-RF:29","BidCoS-RF:30","BidCoS-RF:31","BidCoS-RF:32","BidCoS-RF:33","BidCoS-RF:34","BidCoS-RF:35","BidCoS-RF:36","BidCoS-RF:37","BidCoS-RF:38","BidCoS-RF:39","BidCoS-RF:40","BidCoS-RF:41","BidCoS-RF:42","BidCoS-RF:43","BidCoS-RF:44","BidCoS-RF:45","BidCoS-RF:46","BidCoS-RF:47","BidCoS-RF:48","BidCoS-RF:49","BidCoS-RF:50"},FIRMWARE:"3.53.30.20200919",FLAGS:9,INTERFACE:"PEQ1102842",PARAMSETS:{"MASTER"},PARENT:"",RF_ADDRESS:2171046,ROAMING:1,RX_MODE:1,TYPE:"HM
RCV-50",UPDATABL
Oct 18 12:28:35 homematic user.err rfd: XmlRpc transport error
```

und in der hap-homematic.log:

```
[Sun Oct 18 2020 12:28:30 GMT+0200 (CEST)] error - [HAP Server] [RPC] Modul is not running ignore call
[Sun Oct 18 2020 12:28:30 GMT+0200 (CEST)] error - [HAP Server] [RPC] Modul is not running ignore call
```

und in der Kernel-Log steht:
```
<6>[23772.602042] TCP: request_sock_TCP: Possible SYN flooding on port 8183. Sending cookies.  Check SNMP counters.
```

Wobei ich beim Kernel Log leider kein Datum / Uhrzeit sehe - bin mir nicht sicher ob der Fehler zum gleichen Problem gehört.

Bei mir sind recht viele Gräte und Instanzen angelegt:
22 laufende HAP Instanzen
146 verbundene Geräte

Das Problem trat erst ab einer gewissen Menge auf und kommt jetzt immer wieder vor (nur bei Änderungen, nicht im "Standard" Betrieb).

Das Problem ist zwar nicht akut (da ich mir recht einfach über einen Neustart behelfen kann) - es wäre aber evtl. sinnvoll die Ursache des Absturzes zu beheben.

**Comment by thkl** [comment]
Während eines Reloads werden die RPC Listener für die CCU Schnittstellen kurz beendet und dann wieder gestartet.
Dabei wird zuerst der komplette RPC Manager auf den Zustand gestoppt gesetzt und anschließend ein deInit auf jedem verbunden Interface zur CCU gesendet. Letzteres sorgt dafür das die CCU keine Änderungen/Events mehr an HAP sendet.

Wenn während diesem Vorgang eine Event auftritt wird der vom RPC Manager ignoriert, weil dieser ja schon auf den Zustand gestoppt gesetzt wurde. (Das ist die Meldung [RPC] Modul is not running ignore call)

Anschließend werden alle Geräte wieder geladen und die Verbindung zur CCU wird wieder aufgebaut.

Dieser Ab und Wiederaufbau ist nötig, da ich nur Events von Interfaces abonniere, von denen Geräte nach HomeKit gehen sollen. Also wenn man bspw. keine HMIP Geräte hat, warum sollte ich dann Änderungen auf dem HMIP Interface abonnieren. Und da sich beim Reload ja diese Einstellungen ändern könnten passiert der Ab und Aufbau.

Die Frage ist jetzt ob der ganze Daemon crasht. Wenn das passiert schreibe ich vor dem Crash ein Log nach /usr/local/etc/config/addons/hap-homematic

**Comment by JarvisHome** [comment]
jup, es gibt ein crash log:

```
Error log : Sun Oct 18 2020 12:28:35 GMT+0200 (CEST)

TypeError: Cannot read property 'reconnecting' of undefined
    at Server.<anonymous> (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/HomeMaticRPC.js:202:28)
    at Server.emit (events.js:315:20)
    at /usr/local/addons/hap-homematic/node_modules/homematic-xmlrpc/lib/server.js:42:14
    at Deserializer.callback (/usr/local/addons/hap-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:65:7)
    at Deserializer.onDone (/usr/local/addons/hap-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:92:12)
    at SAXStream.emit (events.js:315:20)
    at SAXParser.SAXStream._parser.onend (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:171:8)
    at emit (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:325:33)
    at end (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:363:3)
    at SAXParser.end (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:137:24)

```

**Comment by thkl** [comment]
BTW: Welche RM Version und welche Addon Version läuft bei Dir ?

**Comment by JarvisHome** [comment]
Sorry: 
- Raspberry Matic: 3.53.30.20200919 (aktuellste)
- hap-homematic: 0.0.54

**Comment by thkl** [comment]
ich meine das CCU Addon das ist zwar "nur" der Installer aber auch für den restart Prozess verantwortlich . Da hat sich mit der letzten RM Version eine Änderung ergeben

**Comment by thkl** [comment]
> jup, es gibt ein crash log:

Ah ok ... das fange ich mal besser ab

**Comment by JarvisHome** [comment]
Installer ist 0.0.14

**Comment by thkl** [comment]
ok. Naja ich habe zumindest den Bug der zu obigen Crash führt beseitigt. Mal schauen

**Comment by roe1974** [comment]
wird das ein neuer installer oder eine neue version .... ?

**Comment by thkl** [comment]
neue Version.
