### ISSUE TITLE
Neues Gerät: HM-LC-Sw4-PCB

### ISSUE THREAD

**Issue by JarvisHome** [thkl/hap-homematic#214]
wird bisher noch nicht unterstützt / gefunden:
[HM-LC-Sw4-PCB.zip](https://github.com/thkl/hap-homematic/files/5397628/HM-LC-Sw4-PCB.zip)

PS: super Addon - endlich einfaches Homekit - Vielen Dank dafür :-)

**Comment by thkl** [comment]
Das Ding halt laut dem File 4 Switch Kanäle. Das wird von allen Switchklassen unterstützt. Wenn es neu hinzugefügt wurde, dann bitte mal über "Internes - CCU Cache aktualisieren" dem Daemon neue Geräte beibringen.

**Comment by JarvisHome** [comment]
Das war's - sorry & danke :-)

**Comment by thkl** [comment]
Ich mache den Cache Refresh auch wenn ich von der Schnittstelle die newDevices Meldung bekomme. Das ist der Fall wenn das Gerät angelernt wurde. Dann hat es aber noch den HM-.....Seriennummer Namen, den ich dann bekomme. Wenn man es im Posteingang umbenennt, bekomme ich jedoch keine Info vom Rega und so ist das Gerät in HAP zwar da aber halt noch unter dem alten Namen und noch in keinem Raum. Daher der manuelle Refresh. 

Ich habe noch keine Idee wie das verbessert werden kann, da Rega selber keine Events kennt.

**Comment by sailor79** [comment]
added to wiki
