### ISSUE TITLE
Anzeige Klimawerte des HM-TC-IT-WM-W-EU Thermostaten

### ISSUE THREAD

**Issue by Elbe122** [thkl/hap-homematic#215]
Hallo Thomas,

die Klimadaten des Thermostaten kann ich nicht als "Gerät" in der Version 0.0.54 hinzufügen, wie es beim alten Thermostat HM-CC-TC möglich ist. Es wäre prima, wenn Du die Anzeige von Temperatur und Luftfeuchtigkeit auch für den neueren Thermostaten noch aktivieren könntest.

Auf jeden Fall ein großes Danke für diese Initiative!!!

Grüße
   Carsten

**Comment by thkl** [comment]
Das Gerät sollte doch als Thermostat hinzufügbar sein. Channel 1 ist vom Typ THERMALCONTROL_TRANSMIT .. und der wird durch die Serviceklasse HomeMaticThermostatAccessory unterstützt

**Comment by Elbe122** [comment]
Ja, das ist korrekt. Es wird dann die Thermostatsteuerung in der Home App angeboten. Allerdings liegt mein Interesse an den Messwerten des Thermostaten (Temperatur, Luftfeuchtigkeit) als HomeMaticThermometerAccessory, um diese in der Home App anzuzeigen.

**Comment by thkl** [comment]
Achso also das Thermostat soll quasi als Thermometer only verwendet werden... hmm kann ich machen

**Comment by Elbe122** [comment]
Funktioniert perfekt - vielen Dank!

**Comment by kurtwithslc** [comment]
Sorry, aber ich bekomme nur die Temperatur angezeigt (oder alternativ nur die Luftfeuchtigkeit).
Wie kann ich beide Werte anzeigen lassen?

**Comment by thkl** [comment]
Es werden doch beide angezeigt :

![image](https://user-images.githubusercontent.com/884355/101331495-5e09e280-3874-11eb-98c6-23a6127a1d6b.jpeg)

**Comment by kurtwithslc** [comment]
Ok, habs hinbekommen.
Ich muss bei der Gerätezuordnung "HomematicThermometerAccessory" einstellen.
Ist für mich verwirrend, da ich gedanklich mit Thermometer nur die Temperatur verbinde
und nicht Temperatur und Luftfeuchte.
