### ISSUE TITLE
Leider läuft bei mir die Installation auf der CCU3 (Raspberrymatic nicht...

### ISSUE THREAD

**Issue by hsetz** [thkl/hap-homematic#216]
Habe schon alle varianten versucht, mehere ports geöfnet (9874; 9875; 9876; bis ...9890 leider ohne erfolg.

9890;

![grafik](https://user-images.githubusercontent.com/60353625/96373851-68123d80-116f-11eb-9e51-9c3c8c4ce64a.png)

![grafik](https://user-images.githubusercontent.com/60353625/96373867-7fe9c180-116f-11eb-9862-da46fdeb2e7f.png)

![grafik](https://user-images.githubusercontent.com/60353625/96373893-98f27280-116f-11eb-924c-d709b344e421.png)

können Sie mir weiterhelfen...

Mit freundlichen Grüssen

Setz Hans-Ruedi

**Comment by thkl** [comment]
Wurde in der Systemsteuerung ein HomeKit Button hinzugefügt:

![image](https://user-images.githubusercontent.com/884355/96374670-41a2d100-1174-11eb-99a0-e0219f8039de.png)

**Comment by Klonass** [comment]
Ich habe das gleiche Problem. Und der Homekit Button wird nicht angezeigt. Ich habe auch versucht eine älter Version zu installieren, dies ergab jedoch den gleichen Fehler

**Comment by thkl** [comment]
Wenn der Homekit Button nicht da ist läuft im Installer was schief.

Die CCU selber kann aber auf das Internet zugreifen ?

**Comment by Klonass** [comment]
Ja, sie zeigt Updates etc. an und entsprechende Firewall Regeln (welche es dem Raspi verbieten würden) sind im Netzwerk nicht festgelegt.

**Comment by thkl** [comment]
Nach dem Start der CCU sollte das Log vom Installer hier liegen:

/var/log/hmhapinstall.log

Was steht da drin ?

**Comment by Ritschi75** [comment]
Bei mir ja dasselbe Problem.
Im Log steht folgendes:
[Installer]Check existency of the daemon
[Installer]daemon exists lets light this candle
Installiert habe ich die Version 0.0.14
System:
Thinkerboard
3.53.34.20201121

Gruss
Ritschi

**Comment by c0d35io** [comment]
👋🏻

im Log ist nach mehren Installationsversuchen mehrfach `[Installer]Looks like the daemon is not here so start installer` zu sehen. Die [hier abgefragte](https://github.com/thkl/hap-homematic/blob/68a181059829a1868fb8a80e629c4000441ed47b/addon_installer/etc/postinstall.sh#L12) index.js ist auf dem Dateisystem vorhanden. Beobachtet bei einer CCU3 mit Raspberrymatic. Wo kann man hier ansetzen, bin noch neu in der Raspberrymatic-Welt

**Comment by Camel2k** [comment]
Noch einmal das Thema aufgegriffen, hab auch das Problem das der HomeKit Button nicht angezeigt wird.

Installer]Start installer
[Installer]Program Dir is /usr/local/addons/hap-homematic
[Installer]installing HAP-Homematic ...
[Installer]creating HomeKit Button ...

**Comment by ChrWi** [comment]
Das ist doch identisch mit #345?
