### ISSUE TITLE
Unterschiedliche Versionsangaben

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#218]
Hallo,

kann mir jemand erklären, warum für das PlugIn verschiedene Versionen in der CCU und dem PlugIn angezeigt werden? 
Danke.

![140F2B94-28F1-4D85-A1DA-A08D46BD5867](https://user-images.githubusercontent.com/72799068/96547649-c264e880-12ac-11eb-9dcd-d2d3f9fab7b6.jpeg)
![C958A9E3-DF19-4342-8BBA-425D71E851BF](https://user-images.githubusercontent.com/72799068/96547658-c5f86f80-12ac-11eb-85bf-8c755add059f.jpeg)

**Comment by blackbasket** [comment]
Hallo Gerd,

in der CCU wird dir die Version des Installers (aktuell 0.0.14) angezeigt. Im Plugin selbst wird dir die Version des Plugins (aktuell 0.0.54) angezeigt.

LG

**Comment by thkl** [comment]
So ist es. Das Addon auf der CCU ist nur für den initialen Download des NPM Archives und dessen Installation da. Es startet weiterhin beim Start der CCU den HAP Daemon. Daher muss es nicht so oft aktualisiert werden wie der eigentliche HAP Daemon.

Ich hatte auch schon mal drüber nachgedacht, beide Versionen zu vereinheitlichen, mal sehen.
