### ISSUE TITLE
HmIP-Heizung Boostmode

### ISSUE THREAD

**Issue by blackbasket** [thkl/hap-homematic#219]
Hallo Thomas,

gibt es eigentlich die Möglichkeit, den Boost-Mode (vgl #7 ) über HomeKit zu verwenden? Oder bietet Apple die Funktion gar nicht an?

LG,
Marcel

**Comment by gerd2005** [comment]
Hallo, wenn ich deine Frage richtig verstehe, solltest du als erstes schauen, ob der Boost-Mode in deiner CCU aktiv ist. Ich könnte mir vorstellen, dass wenn der Wert auf „0“ steht das nicht funktioniert.
![A67FAEAC-7ACE-4D4C-9180-D6C4B7878365](https://user-images.githubusercontent.com/72799068/96836153-dba09d00-1444-11eb-9a2c-cd1a6473b111.png)

Dann gehst du in das PlugIn und aktivierst den Haken hier:
![C2F336A9-B705-4223-806D-81D0BD70AAEC](https://user-images.githubusercontent.com/72799068/96836283-0854b480-1445-11eb-951e-f5ffe88efa94.png)

Anschließend würde ich die CCU einmal neustarten. 
Dann solltest du den Boost-Mode in Homekit angezeigt bekommen.
![22D073A0-4BA4-4C36-ADDB-A44914260FDF](https://user-images.githubusercontent.com/72799068/96836346-23bfbf80-1445-11eb-88c8-2c7512d9f16e.jpeg)
![26D64D38-1702-44EA-9BC3-78E06F7B35C8](https://user-images.githubusercontent.com/72799068/96836351-25898300-1445-11eb-8a77-3e6575b84a90.jpeg)
![C98D2540-D1DB-45AD-A189-5B076C87FF4C](https://user-images.githubusercontent.com/72799068/96836355-26221980-1445-11eb-8a46-91f8913a9c6a.jpeg)



 du als erstes im PlugIn den Boostmode aktivieren.

**Comment by blackbasket** [comment]
Hallo Gerd,

danke. Klassisches Layer 8-Problem ;) Der Haken im Plugin hat gefehlt.

LG,
Marcel
