### ISSUE TITLE
Kosmetik: Keine Sortierung der Geräte bei der Übersicht.

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#22]
Hallo Thomas

Da ich nicht geneu erkenne wonach die Geräte in der Überishct sortiert werden, wäre eine sortiermöglichkeit recht cool :-)

lg Richard

**Comment by thkl** [comment]
1 Sortierung ist die Instanz (also der Raum)
Aber ich bringe dem Datagrid mal sortierungen nach Spalten bei.

**Comment by roe1974** [comment]
bin ich blind ... aber wo wird da nach raum sortiert ? ;-) :-P
![Unbenannt](https://user-images.githubusercontent.com/30420568/80385473-5fb70500-88a6-11ea-8396-057a94091e48.JPG)

lg Richard

**Comment by thkl** [comment]
OB DU NICHT DEN WIZZARD BENUTZT HAST DER DAS GANZE SORTIERT ANLEGT HABE ICH GEFRAGT ...

(ja Sortierungen kommen) bis dahin einfach oben die Suche benutzen

**Comment by roe1974** [comment]
okeeeee ... mea culpa..... ich bin schuld :-P

**Comment by thkl** [comment]
fixed with 0.0.32

**Comment by roe1974** [comment]
👍
