### ISSUE TITLE
Unterstützung der Alarmsirene HmIP-ASIR-B1

### ISSUE THREAD

**Issue by mpaul79** [thkl/hap-homematic#220]
Hallo,

habe erfolglos versucht die Alarmsirene HmIP-ASIR (Silvercrest) einzubinden. Ist es möglich, dass der Gerätetyp noch nicht unterstützt wird?  

[HmIP-ASIR-B1.json.zip](https://github.com/thkl/hap-homematic/files/5435946/HmIP-ASIR-B1.json.zip)

Vielen Dank für deine Unterstützung!
Gruß

Marco

**Comment by thkl** [comment]
Wir hatten das hier schon mal. Was soll Homekit denn machen ? Die Sirene tröten lassen ?

**Comment by mpaul79** [comment]
Hallo! Ja, aus meiner Sicht wäre es sinnvoll, wenn man über Homekit das optische und das akutische Signal (sofern möglich separat) ansteuern könnte. Dadurch wäre es mir dann möglich, das Gerät meine Alarmanlage zu integrieren.

**Comment by thkl** [comment]
Es gibt bei dem Ding nur einen Key Kanal (Channel 1) Trötet die los wenn man diese Taste in der CCU Drückt ?

**Comment by mpaul79** [comment]
An dem Gerät gibt es nur eine mechanische Taste, die Anlerntaste. Über die HomeMatic Web UI kann ich den akustischen und den optischen Alarm allerdings separat voneinander testen.

Meldungen dazu aus dem Systemprotokoll:

HmIP-ASIR-B1 000AD99396C420:3 | Optisches Signal aktiviert, Akustisches Signal deaktiviert

HmIP-ASIR-B1 000AD99396C420:3 | Optisches Signal aktiviert, Akustisches Signal aktiviert

HmIP-ASIR-B1 000AD99396C420:3 | Optisches Signal deaktiviert, Akustisches Signal aktiviert

Infos bzgl. der Kanäle aus den Geräteeinstellungen:

Name | Typenbezeichnung | Bezeichnung | Seriennummer | Interface/Kategorie | Übertragungsmodus

HmIP-ASIR-B1 000AD99396C420:1 Verknüpfungspartner Sabotagekontakt | HmIP-ASIR-B1 | Homematic IP Alarmsirene | 000AD99396C420:1 | Sender | Gesichert 

HmIP-ASIR-B1 000AD99396C420:2 Verknüpfungspartner für Sensor mit Sicherheitskanal | HmIP-ASIR-B1 | Homematic IP Alarmsirene | 000AD99396C420:2 | nicht verknüpfbar | Gesichert 

HmIP-ASIR-B1 000AD99396C420:3 Alarmkanal | HmIP-ASIR-B1 | Homematic IP Alarmsirene | 000AD99396C420:3 | Empfänger | Gesichert

**Comment by blackbasket** [comment]
@mpaul79 besteht das Anliegen noch? Sonst bitte das Ticket schließen. Danke :)

**Comment by mpaul79** [comment]
Das Anliegen besteht zwar noch, werde den Punkt aber dann trotzdem schließen. 😊
