### ISSUE TITLE
Benachrichtigung bei einer bestimmten Luftfeuchtigkeit

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#222]
Hallo,

ich habe einen HMIP-STHD. Über HomeKit hätte ich gerne eine Benachrichtigung, wenn die Luftfeuchtigkeit über 70% steigt. Wie kann ich das mit Bordmitteln realisieren? 

Bei meinen Fensterkontakten kann ich bspw. im Gerät selber „Status und Mitteilung“ auswählen und sagen, dass eine Benachrichtigung bei „offen“ oder „geschlossen“ generiert werden soll. Software Ähnliches hätte ich beim Thermostat nun auch erwartet.

Danke und lieben Gruß

**Comment by thkl** [comment]
Es gibt in der nächsten Version einen expliziten Feuchtigkeitssensor .. den kann man dann ggf in eine Automation in Homekit einbinden. Jedoch lassen sich in Homekit keine frei definierten Push Meldungen realisieren.

**Comment by gerd2005** [comment]
Hallo,

seid mir nicht böse... aber irgendwie verstehe ich das mit den Push Mitteilungen immer noch nicht.
Warum ist es möglich bei einem Fensterkontakt über „Status & Mitteilungen“ zu sagen: Schicke eine Push Mitteilung, wenn das Fenster geöffnet oder geschlossen wird“, ... und bei einem Feuchtigkeitsmesser geht das nicht. Selbst über Kurzbefehle gehts nicht. Bzw. Ich bekomme es nicht hin. Mir ist schon klar, dass das ein HomeKit-Thema ist. Aber wie dämlich sind die denn da bei Apple, dass die so eine (Standard)-Funktion nicht unterstützen?!

PS: Danke für das Update. Das mit dem Anzeigen des Feuchtigkeitssensors funktioniert wunderbar.

**Comment by thkl** [comment]
Tja Apple hat das nicht vorgesehen. 

Es gibt einen Leak Sensor der pusht. 

Man *) könnte jetzt natürlich folgendes machen: Feuchtigkeitssensor > x% entspricht einem Leak und dann würde der pushen 

*)
Also ich müsste nen Device Service bauen der das so umsetzt.

**Comment by gerd2005** [comment]
Mhh nicht nachvollziehbar von Apple finde ich. Aber Hauptsache in iOS 14.1 einen neuen Reiter „Entdecken“ in die Home-App einbauen. Unfassbar... Naja...

Noch eine Frage zum Thema Thermostat und Luftfeuchtigkeitssensor:
Wenn ich in deinem PlugIn mir ein Thermostat schnappe und den neuen Service „Humidity“ auswähle, wird mir in HomeKit die Luftfeuchtigkeit angezeigt... So wie es sein soll... Leider verschwindet im gleichen Zug die Funktionalität des Thermostats. Ist das richtig so? Entweder - Oder? Oder geht auch beides?

**Comment by thkl** [comment]
Ja, derzeit ist die komplette interne Struktur so angelegt, das es nur einen Service pro DeviceKanal geben kann.   

Das zu ändern geht nicht so einfach.

**Comment by gerd2005** [comment]
Ah ok... Schade. Alles klar, danke!

**Comment by meistermolli** [comment]
jetzt hier auch gelesen ... merci
