### ISSUE TITLE
CCU Programm Starten

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#223]
Hallo,
wenn ich ein Programm in HAP Homematic hinzufüge und der Instanz zuordne kann ich es zwar in HomeKit sehen aber kann es leider nicht aus der Home app Starten. (Schieberegler belegt sich aber das Programm startet nicht)
Muss hier der Schieberegler lang gehalten werden oder benötigt das Programm in der CCU/In den HomeKit Einstellungen einen speziellen Startbefehl/Haken irgendwo?

Ich helfe mir hier aktuell mit einem "Besonderen Gerät" - Multi channel push button um das Programm zu starten.
Das funktioniert auch gut. Nur Blockiert es mir ja Virtuelle Taster. (allein schon für unseren Wasserhahn knapp 10 Stück).

Wahrscheinlich stelle ich mich nur doof an?

Danke und Gruß
meistermolli

**Comment by thkl** [comment]
Das ist ein Bug der in der nächsten Version raus ist

https://github.com/thkl/hap-homematic/commit/61e3f42c6b9f6f6267e337b430db314886b05da0

**Comment by meistermolli** [comment]
Perfekt danke... Hast du schon eine Ahnung wann du das Update ca. online bringst?
Merci

**Comment by thkl** [comment]
Ja

**Comment by Peyto79** [comment]
Es scheint als ließen sich Programme noch nicht starten. Ich habe eins neu hinzugefügt, es erscheint auch in der Home-App, aber wenn ich es antippe passiert noch nichts. Ich habe die 0.0.55 installiert.

**Comment by thkl** [comment]
Der Switch wird 500ms nach dem Aktivieren des Programms wieder ausgeschalten. Aber es wird auf der CCU aktiviert. Zumindest in meinen Tests

**Comment by meistermolli** [comment]
@thkl Hi, klappt leider bei mir auch nicht. Habe das auch nochmal neu hinzu gefügt. Der Push Button Service zum selben Programm startet es aber. Ist die 500 ms vielleicht zu kurz?
