### ISSUE TITLE
Version 0.0.55: anderer Bug bei zB: HM-CC-RT-DN .... "aus" wird als 4,5° gezeigt

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#224]
Hallo Thomas

Seit der 0.0.55 wird bei Thermostaten die auf "aus" sind in der CCU in Homekit "Heizung:4.5°" angezeigt....
Da stand in der 0.0.54 noch "aus" in Homekit :-)
Schaltet man in HK dann auf "aus" springt es zurück auf "Heizung:4.5°" ;-)

lg Richard

**Comment by gerd2005** [comment]
Nach dem Update zeigte HK ein ähnliches Verhalten bei mir. Nachdem ich dann aber noch das neue Update für die CCU installiert habe, hat alles wieder funktioniert. Ich würde vermuten, dass ein Neustart der CCU Abhilfe schafft.

**Comment by roe1974** [comment]
ich habe die aktuelle RM bereits vorher installiert .... denke nicht dass ein reboot hier den bug behebt .... was sagst Du Thomas ?

**Comment by daseichi** [comment]
Bei mir das gleiche Probleme: schaltet man eine Heizung in Home aus, springt sie nach wenigen Sekunden wieder auf 4,5°

Kann man eigentlich auf die 0.0.54 downgraden?

**Comment by steckenpferd** [comment]
Nur als Info an alle - das ist kein echter Bug - die CCU speichert OFF intern mit dem Wert 4,5. 
Also liest das Addon (oder auch manche App) den richtigen Wert 4,5 aus, besser wäre aber das der Wert 4,5 im Addon umgewandelt wird für Thermostete in der Darstellung auf den Wert OFF.
Ist zwar ärgerlich in der Darstellung aber 4,5 ist kein echter Fehler.

**Comment by daseichi** [comment]
> Nur als Info an alle - das ist kein echter Bug - die CCU speichert OFF intern bei Thermostaten mit dem Wert 4,5.
> Also liest das Addon (oder auch manche App) den richtigen Wert 4,5 aus, besser wäre aber das der Wert 4,5 im Addon umgewandelt wird für Thermostete in der Darstellung auf den Wert OFF.
> Ist zwar ärgerlich in der Darstellung aber 4,5 ist kein echter Fehler.

In Version 0.0.54 gab es dieses Verhalten aber nicht - irgendwas muss sich geändert haben. ¯\_(ツ)_/¯

**Comment by roe1974** [comment]
> 
> 
> Bei mir das gleiche Probleme: schaltet man eine Heizung in Home aus, springt sie nach wenigen Sekunden wieder auf 4,5°
> 
> Kann man eigentlich auf die 0.0.54 downgraden?

ja .... per ssh auf der CCU/RM:

/etc/config/rc.d/hap-homematic stop
npm install hap-homematic@0.0.54

**Comment by daseichi** [comment]
> /etc/config/rc.d/hap-homematic stop
> npm install hap-homematic@0.0.54

das hatte ich schon probiert, schlägt leider fehl:

```
Unhandled rejection Error: EROFS: read-only file system, mkdir '/root/.npm'ff9e

┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```
Wollte aber auch nicht weiter _wild_ rumprobieren...

**Comment by thkl** [comment]
Nooo so wird das nix 
Das npm cache liegt auf einer RO Partition un muss beim Install umgebogen werden. das geht mit dem --cache Switch also 

npm --cache /tmp/  ....

**Comment by daseichi** [comment]
Sieht so aus als wäre dieser "Bug" mit Version 0.0.57 behoben - zumindest kann ich diese Verhalten bei mir nicht mehr beobachten. Danke! 👍

**Comment by ChrWi** [comment]
@daseichi dann mache ich das Issue zu
