### ISSUE TITLE
HAP mit TinkerBoard - multiple Anmeldungen an FritzBox

### ISSUE THREAD

**Issue by steho051** [thkl/hap-homematic#225]
Nach Installation von HAP-Homematic erscheinen nach einiger Zeit multiple Einträge/Neuanmeldungen der Raspberrymatic/HAP-IP Adresse in der FritzBox, siehe Screenshot.

Die Homebridge funktioniert ansonsten wie erwartet - keine erkennbaren Fehlermeldungen.

Sobald die Anmeldung in Dauerschleife läuft sind weder Homebridge noch WebUI der Raspberrymatic erreichbar, es hilft dann nur ein Kaltstart.

- TinkerBoard ist i.O., wurde getauscht, 
- TB ist via Netgear Switch an FB angeschlossen, auch direkter Anschluss an FB gleicher Fehler
- unterschiedliche Ports an FB getestet, gleiches Problem
- gleiche Installation auf RPI 3B+ funktioniert fehlerfrei, daher Vermutung Zusammenhang HAP-TinkerBoard?

Danke!

**Comment by thkl** [comment]
Das TB macht also permanent einen DHCP renew ?

Ich kann mir nicht vorstellen, das das an der RM und noch weniger an Hap liegt.

**Comment by steho051** [comment]
Ob das ein DHCP "Renew" ist, kann ich nicht sagen, das TB/RM hat eigentlich eine in der RM fest zugewiesene IP und damit startet das System auch. Die IP liegt in einem geschützten Bereich, wo die FB keine IPs vergeben darf (<.100).

<img width="851" alt="Bildschirmfoto 2020-10-28 um 06 33 15" src="https://user-images.githubusercontent.com/73586729/97433517-ee701180-191d-11eb-8fcd-e681214f7146.png">

so sieht das in der FB aus...

Sobald das mit den multiplen (identischen) IPs losgeht, kommt man auch nicht mehr auf die RM oder HAP, das gesamt LAN wird hakelig und (wenn überhaupt) werden Programme auf der RM nur sehr verzögert ausgeführt -  vorher läuft es einwandfrei.

Wie gesagt, ein aktuelles Backup auf einen RPI 3+ gespielt, Funkmodul umgesteckt, alles in Ordnung. Daraufhin hatte ich ein neues TB bestellt, da ich an einen Defekt glaubte, frische RM draufgespielt, Backup eingespielt, nach ca. 12h ging der Spuk wieder los.

Jetzt ist HAP deinstalliert und momentan läuft es auf dem TB "unauffällig".

Wenn ich irgendetwas protokollieren soll/kann, gerne - aber bitte mit Hinweis wie und was. 

Danke für die Hilfe und auch Danke für das tolle Projekt!

**Comment by thkl** [comment]
Hm von meiner Seite aus laufen keinerlei lowlevel Netzwerksachen. 

Das HapNodeJs Framework macht pro Instanz einen HTTP Server auf und ich noch einen für die CCU Events und das WebUi. 

Einzige Sache ist ggf das Bonjour Protokoll was die HomeKit Bridges im Netzwerk bekannt macht. Das ist bringt aber HapNodeJs mit.

**Comment by sailor79** [comment]
Ich habe genau das gleiche Problem seit letzter Woche nach dem Rasperryupdate.  Im Forum läuft es auf zufällig zeitliche Korrelation hinaus. Mit HAP-Homematic lief es aber vorher schon korrekt. Nach Rücksprache mit dem AVM-Support der FRITZ!Box soll man keine feste IPs  in den Geräten vergeben, sondern erst eine per DHCP vergeben lassen und dann den Haken setzen, dem Gerät immer die gleiche Adresse zu reservieren. Gleichzeitig hat AVM auch konstatiert, dass sie keine zuverlässige Funktion gewährleisten, wenn man den Adressbereich von .20-.200 auf was anderes verschiebt. Meine persönliche Meinung ist, dass es mit den Repeatern zusammenhängt. Vielleicht machst du auch mal ein Ticket da auf, dann wären wir schon drei. Bin als Einzelfall abgefertigt worden ohne zufriedene Lösung mit Verweis aufs Handbuch, was aber die Emailantwort nicht widerspiegelt.  Meine und eine andere Ticketnummer auf die du auch verweisen kannst: AVM Ticket-ID 3805137, 3722749

**Comment by thkl** [comment]
Hmm klingt wild. Ich habe generell bei mir feste IPs via DHCP eingestellt. Und auch auf diversen Testplattformen keine Probleme. Allerdings kein ThinkerBoard wo ich das nachstellen könnte.

**Comment by steho051** [comment]
@sailor79 

Jetzt dämmert mir was:
Ich habe in der Woche der "HAP-Installation" einen zusätzlichen AVM 2400er gekauft und (versucht) in mein Netzwerk einzubinden.
Der Repeater hat einen LAN-Anschluss und - gemäß (Kurz-)Anleitung - ich hatte ihn mit dem Netzwerk verbunden und versucht zu konfigurieren.
Das ging aber nicht, da sich der Repeater über DHCP stumpf und stur die .2 am Ende "geholt" hatte, welche aber schon durch einen 1750er AVM Repeater in Benutzung war. Werksreset und einbinden per WLAN klappte, eine Vergabe einer festen IP-Adresse auch, bis zu dem kläglichen Versuch in dann per LAN-Kabel einzubinden: wieder die .2...

Der freundliche AVM-Support schickte mir eine Anleitung, wie man den Repeater per LAN einbinden könne - ironischerweise widersprach das dort Beschriebene der beiliegenden, gedruckten Anleitung: Erst per WLAN einbinden, dann drauf einloggen und dann dort in den Tiefen der Menüs das Teil als LAN-Brücke einrichten und ggf. IP-Adresse einstellen und Neustarten. 
Danach funktionierte es.
1-2 Tage später kam dann ein Update von AVM für den Repeater mit dem "Feature", dass der Repeater "erkennt" ob er per LAN-Kabel angeschlossen ist.

Gefühlt war die Anleitung der (Werksfimware) Firmware ihrer Zeit voraus...

Ich werde das Teil mal vom Netz nehmen und es nochmal mit TinkerBoard und HAP probieren, Backup hab ich ja noch liegen. Schaffe ich aber wohl erst morgen...

Ein Kollege von mir hatte übrigens ein ähnliches Phänomen nach dem AVM-Firmware-Update und einem danach stattgefunden Stromausfall. Da hatte er auch ein Gerät, welches zig mal unter den Netzwerkgeräten erschien, bei ihm war der Spuk aber nach ein, zwei Tagen vorbei und er hat sich da nicht weiter drum gekümmert...

Beruhigt mich aber ein wenig, dass ich nicht völlig verblödet bin und das auch bei anderen aufgetreten ist. ;-)

**Comment by steho051** [comment]
@sailor79 

Ich habe gestern ein Ticket beim AVM Support eröffnet und werde denen im Laufe der nächsten Tage die angeforderten "Daten" schicken. 

Um die Sache etwas besser eingrenzen zu können, habe ich gestern den AVM 2400 aus meinem Netz entfernt und werde heute auf dem TinkerBoard/Raspberrymatic HAP-Homebridge neu installieren - ich meine nämlich, dass es ohne den 2400er erst problemlos funktioniert hat.

Weiterhin - aber da war ich noch nicht zu gekommen - erhielt ich die letzten Wochen jeden Tag mehrere Push-Nachrichten über neuangemeldete Netzwerkgeräte, obwohl diese im Netzwerk definitiv bekannt sind/waren.

Beispiel Handy/Smartwatch beim nach Hause kommen = neu angemeldetes Gerät. Ich dachte erst, dass ich da evtl. bei den Benachrichtigungen irgendwo ein Häkchen zuviel gesetzt hatte, aber seit Abziehen des 2400ers ist auch da (vorerst) Ruhe...

Ich halte euch hier auf dem Laufenden, brauche aber etwas Zeit und die Mail an AVM ausführlich und mit entsprechenden Screenshots, etc. zu verfassen = Zeit.... (die ich leider nie habe)

**Comment by sailor79** [comment]
@steho051 
Danke für Deine Rückmeldung. Ich bleibe auch an dem Thema ran, wo bei das mit dem Support gerade etwas träge verläuft. Im Zweifel werde ich alle AVM Geräte ausmustern, wenn das so weiter geht. Mal sehen.

**Comment by steho051** [comment]
So, HAP wurde gestern neu installiert und dann Backup eingespielt - bisher läuft es...

Ich habe zudem meine Netzwerkinfrastruktur überprüft, sprich Kabelverbindungen von FB zu Switches zu Repeatern - sind i.O., weiterhin habe ich den 2400er mal direkt an die FB angeschlossen und die Einstellungen kontrolliert, alles i.O., jetzt wieder an vorgesehenem Standort angeschlossen.

Im Gespräch mit dem Techniker von AVM erwähnte der, dass es Sinn machen könnte, den Netzwerkbereich zu erweitern, weil es sonst schon mal "eng" werden könnte mit den IP-Adressen und in dem Zusammenhang meinte er, dass sich z.B. Apple Geräte immer wieder mit anderer "Adresse" anmelden würden/könnten.

--> Seit iOS 14 gibt es bei EINSTELLUNGEN - WLAN - i bei verbundenem WLAN drücken, die Option, sich bei jedem Verbinden mit einem (auch bekannten!) Netzwerk eine neue MAC-Adresse zu verwenden -->>> Daher die unzähligen Push-Nachrichten meiner FB bezüglich Tablet, Telefon & Co... 
Habe ich eben mal für mein Heimnetzwerk deaktiviert (man kann es für JEDES Netzwerk individuell einstellen) und da ist auch Ruhe eingekehrt.

Keine Ahnung, ob es jetzt so bleibt, ich beobachte und Berichte...

Schönes Wochenende!

**Comment by steho051** [comment]
Kurzes Update: 

Seitens AVM wurde ein Firmware-Update für den Repeater 2400 (7.21) veröffentlicht, der u.a. folgenden Bug beheben soll:

**Behoben** Bei einem per LAN mit der FRITZ!Box verbundenen Repeater wurde u. U. nach einem Neustart zeitweise eine ungültige IP-Adresse vergeben

bisher läuft die Installation jetzt fehlerfrei, AVM habe ich so detailliert wie möglich den zuvor beschriebenen Fehler geschildert.

@sailor79 - viellicht kannst du das ja auch mal testen mit dem FW-Update und ob es dann geht.

Ich fand es ja schon befremdlich genug, dass man den Repeater nicht wie in der Anleitung dokumentier (per LAN) in Betrieb nehmen konnte, sondern es anhand eines Support-Dokumentes machen musste...

**Comment by sailor79** [comment]
@steho051 Ich habe die Woche alle AVM Repeater rausgeschmissen und durch Unifi APs ersetzt. Der Support da war unterirdisch und jetzt hab ich die Notbremse gezogen. Bisher keine neuen Vorkommnisse bei mir, aber ich bin auch noch auf der September Version von Raspi. Mal sehen, ich habe das Gefühl das Thema wird von mehreren Dingen beeinflusst.

**Comment by twister9916** [comment]
Hallo, ich habe genau das gleiche Problem. Fritz Box 6351 Cable mit Software 7.21 neuste Raspberrymatic über LAN angeschlossen. Raspberrymatic läuft auf einem Tinkerbord S. Switch und W-Lan Accesspoitns von Unifi. Nach ca. 48h beginnt der Spuk und die Raspberrymatic wecheselt sebständig und ständig die MAC Adressen. Ist sonst nicht mehr erreichbar und es hilft nur noch Kaltstart.

**Comment by steho051** [comment]
@twister9916 

Bisher ist das Phänomen bei mir nicht wieder aufgetreten mit den entsprechenden Updates von AVM. 
Für mich ist allerdings auch nicht zu 100% nachvollziehbar, ob das Problem durch den AVM 2400 oder die HAP-Homebridge Installation hervorgerufen wurde, da das relativ zeitgleich erfolgte.
Was ich aber mit Sicherheit sagen kann, dass die Installation des 2400 ein Krampf war und direkt dabei IP-Konfikte auftraten und nichts mehr ging im Netz, was AVM ja als Bugfix auch einräumt.

Der von thkl hier bereitgestellten Software und deren Entwicklung gebührt wirklich Respekt - toll das Leute so etwas machen und teilen, aber ich überlege für mich, ob ich nicht wieder zu einer getrennten Lösung übergehe, sprich CCU/Raspberrymatic und die HomeBridge auf einen separaten Pi4 (hab eh einen für io-Broker, bietet sich an), nur müsste ich da wohl wieder mehrere Instanzen laufen lassen - oder gibt es die 99 Geräte Limitierung nicht mehr?

**Comment by sailor79** [comment]
Ich hatte leider nicht die 2400, sondern drei andere Modelle, u.a. den 1160, die alle samt kein Update bekommen haben von AVM. Um Hap-Homematic auszuschließen, könntest Du eine Sicherung machen innerhalb Hap-Homematic und das Addon von der CCu vorübergehend  deinstallieren und mal 2-3 Tage schauen was passiert. Für mich ist der gemeinsame Nenner hier eher die Kombi Tinkerboard und Fritz und/oder Rasperrymatic und Fritz.

**Comment by sailor79** [comment]
@twister9916 Hallo, hast Du das mal getestet bzw. konntest Du HAP-ausschließen? Ich habe auch noch einen Foreneintrag gefunden, in welcher tatsächlich das Tinkerboard mit RM ärger gemacht hat. Also das ist alles sehr ominös...

**Comment by twister9916** [comment]
Hallo, ja habe ich getestet. Ohne HAP treten die Probleme nicht auf. Ich habe zwar noch einen RasPi 4 hier rum liegen aber so schnell kann ich den als Alternative nicht testen. Die Fritz Umgebung scheidet für mich aus. Es ist bei mir nachvollziehbar dass das Thema von der Raspberrymatic angestoßen wird. Erst wenn die anfängt mehrfach die MAC Adressen zu ändern in sogar recht kurzen Abständen, strauchelt irgendwann auch mal der Router. Bei mir habe ich jetzt einen MAC Filter eingeschaltet. Also nur bekannte MAC Adressen dürfen ins Netz. Dann bekommt man von der Fritz Box sofort ne Mail wenn die Raspberrymatic anfängt zu spinnen.

**Comment by steho051** [comment]
Hallo zusammen!

...und täglich grüßt das Murmeltier :-(
Der Spuk ging dann Freitag Nacht wieder los, die MAC Adresse der RaspberryMatic änderte sich im 2 Minuten-Takt, was in etwas wie folgt aussah: 
XX:XX:3F:XX:XX:XX-->XX:XX:0C:XX:XX:XX-->XX:XX:54:XX:XX:XX...... IP blieb natürlich immer gleich.

In den Tagen zuvor lief das System völlig unauffällig, allerdings unter folgenden Bedingungen:
- HAP Homematic war installiert, ca. 14 Instanzen waren eingerichtet, ABER:
- nur 3 in HomeKit "hinzugefügt" (drei Räume zum testen, ob es an HAP liegt...)
--> keine Probleme, alles gut, daher:

Freitag auch die restlichen Instanzen in HomeKit eingerichtet.
--> keine Auffälligkeiten, bis ich gegen 22:10Uhr von der Arbeit kam und das Garagentor über meine AIO / NEO App öffnete.
- unmittelbar danach ging der Spaß wieder los - alle 2 Minuten neue MAC-Adresse
- da ich des nächtens jetzt keine Lust auf Fehlersuche hatte, habe ich einfach das Netzwerkkabel von der Zentrale abgezogen und bin genervt ins Bett.

Nächster Morgen:
Einige Jalousien waren hochgefahren, andere nicht, sprich die CCU lief noch, aber irgendwie nicht richtig.

Da das Problem unmittelbar nach der Bedienung (NICHT über HomeKit!) eines Gerätes im Raum/Instanz Garage entstand, habe ich in HomeKit diesen Raum entfernt, dann die RaspberryMatic neu gestartet und auch in HAP die Instanz Garage gelöscht -->bisher läuft es.

Könnte einer der Betroffenen mal schauen, ob in seiner HomeMatic-Installation vielleicht  auch das 

GERÄT HmIP-MIO16-PCB VERWENDUNG FINDET???

Ich nutze diese Multi-I/O Platine zur Auswertung des Torzustandes und auch zur Ansteuerung. Dazu sind die Eingänge teils als "Türkontakt" und teils als "Taster" konfiguriert.

Diese Platine macht mir aber seit dem ersten Tag nicht so richtig Freude, es kam immer wieder dazu, dass sich das Gerät "aufgehangen" hat und es nicht mehr reagierte. Auch werden Statusmitteilungen der "Tür-Kontakte" nicht immer zuverlässig übertragen. Ich habe sogar schon ein HmIP-Gateway in der Garage installiert, um mögliche Reichweitenprobleme auszuschließen - wobei meine anderen Geräte dort nie Probleme gemacht haben.

@thkl: hast du da eventuell (negative) Erfahrungen mit dem Gerät? wird es vielleicht nicht (richtig) unterstützt, bzw. in dieser Konfiguration? Warum das zu einem Mac-Adressen-Shift führen könnte ist mir allerdings schleierhaft...

**Comment by thkl** [comment]
Sorry, ich kann dazu absolut nichts beitragen. 

Ich selber benutze feste IPs über DHCP das heißt, die Fritzbox vergibt die IPs anhand der Mac. 

Das funktioniert seit immer.

**Comment by twister9916** [comment]
Hallo zusammen, 

auch ich nutze die spezielle Funktion „besondere Geräte“ für die Garagentorfunktion in HAP 

Zur Bedienung ist bei mir ein HmIP-WGC verbaut und die Lage des Tor läuft über ein
HmIP-SAM

Liebe Grüße

**Comment by steho051** [comment]
@thkl Danke für die Info - so mache ich es eigentlich auch und es funktioniert(e) auch immer...

Ich schreibe mal den Jens Maus an, bzw. poste das auch da mal bei den Issues - ich kann mir halt den Zusammenhang zwischen alternierender MAC-Adresse und HAP bzw. RaspberryMatic einfach nicht erklären. 

Ich hab demnächst ein paar Tage off, da werde ich mal ein System aufsetzten mit nur der Instanz Garage und den darin enthaltenen Devices - wenn es dann wieder auftreten sollte könnte man es vielleicht besser eingrenzen oder gezielter suchen.

Bis dato hatte ich die Sonderfunktion "Garagentor" in HAP noch gar nicht konfiguriert, bzw. es so eingerichtet - also daran kann/sollte es nicht liegen.

**Comment by thkl** [comment]
Ich mache keinerlei lowlevel Netzwerksachen. Ich wüsste auch nicht, warum es zu diesem Effekt kommen sollte.

**Comment by twister9916** [comment]
Hallo zusammen, 

Ich würde das Tinker Board gerne ausschließen als Fehlerquelle für obiges Thema. Daher habe ich eine raspberrymatic in der virtuellen Maschine auf einem Synology NAS installiert. Aber kann ich da dieses AD On hier überhaupt installieren ? Oder brauche ich dafür eine x86er Version ?

Habe ich vorher irgnedwie nicht richtig überlegt.

**Comment by thkl** [comment]
Ich habe das Ganze als Test immer auf einer RaspberryMatic in Einer VirtualBox auf dem Mac laufen. 

Daher sollte es funktionieren.

**Comment by sailor79** [comment]
Hi @twister9916. 
Gestern Abend war es wieder soweit, Doppelte IP am gleichen Gerät mit leicht veränderter Mac Adresse nur an dritter Stelle. Meine aktuelle Konfiguration: Tinkerbord S, RM September Version, KEINE(!!) Addons außer CuxD und XML-API, KEINE Fritz!box.  Auch wenn im Forum manche mit dem Tinkerboard verheiratet zu sein scheinen und anderslautende Erfahrungen wenig toleriert werden, muss es damit direkt oder indirekt zu tun haben. Gestern ist die CCU3 von ELV angekommen, werde nach vielen Jahren wohl zurückwechseln für mein Produktivsystem.

**Comment by steho051** [comment]
@sailor79
Hallo Marc!

Danke für das Feedback - ich bin mittlerweile auch eher am überlegen, ob ich nicht wieder auf Raspi umsteigen sollte... Hatte das TB wegen der eMMC genommen und hielt dies für "sicherer". Andererseits kann man auch einfach prophylaktisch nach 12 Monaten eine frische SD-Karte in den Raspi stecken, dann sollte die Gefahr des Ausfalls minimiert sein.

Komisch ist nur, dass der Fehler erst nach gut 18 Monaten erstmalig auftrat - und ich habe zwei Boards hier liegen und bei beiden passiert exakt das gleiche wir bei dir: dritte Stelle der MAC fängt an sich zu ändern...

Schönes Wochenende allerseits!

**Comment by thkl** [comment]
Da würde ich aber lieber einen Raspberry4 mit SSD nehmen (wenn die RM das irgendwann mal schafft)

Zumindest sind andere Projekte von mir auf dieser Hardware grandios schnell.

**Comment by steho051** [comment]
Ja, wenn dann RP4.

Hatte mir schon einen besorgt, aber der hat jetzt einen defekten 3er ersetzt, wo ioBroker und ne weitere Homebridge drauf läuft. Mal schauen, wann mir ein günstiges Angebot mit 4GB RAM über den Weg läuft. 

Alternativ wäre eine "virtuelle" Lösung auch ein Weg, aber da muss ich mich erstmal rantasten - es fehlt die Zeit...

**Comment by steho051** [comment]
So, heute habe ich mich mal an das Update der RaspberryMatic Version 3.53.34.20201121 von Jens gemacht... 

Katastrophe...
Erster Start nach Installation: HAP-Homematic lief nicht
Neustart, alles "normal", HAP läuft
1h nach Installation: MAC Adressen ändern sich wieder...
Neustart
wieder etwa ne Stunde vergangen: MAC Adressen ändern sich erneut...

Jetzt ändern sich übrigens die Blöcke 3 UND 4....

Ich hab die Nase nun endgültig voll vom TinkerBoard - ist jetzt die Frage ob Raspberry 4 oder gleich Intel NUC, ich weiß es nicht...

Wie sieht's bei den Leidensgenossen aus?

**Comment by roe1974** [comment]
Hier wirst Du mehrere Meinungen finden .... virtuell soll ja inzwischen echt gut laufen.
Ich kann nur sagen bei mir werkelt inzwischen seit einem 3/4 Jahr ein PI4 ohne Probleme .. und das extrem flott.
Ich bin ein Fan von dedizierten Raspi's ... die sind im Fehlerfall in "0 komma nix" getauscht :-)
lg Richard

**Comment by dkrizic** [comment]
Bei mir laufen die ganzen Smart-Home Dinger auf einem Kubernetes Cluster aus 3 amd64 und 5 Raspis. Ich betreibe für jedes Plugin eine eigene Hombridge-Instanz aber auch andere Dinger wie z.B. HA-Bridge. Wenn ein Raspi ausfällt startet der Service auf einem der anderen automatisch.

![ED771A86-CA2A-4E82-BCA9-F2284EF36CBD_1_105_c](https://user-images.githubusercontent.com/1181349/99973803-766ffc80-2da0-11eb-9047-5f9a0c48474d.jpeg)

**Comment by thkl** [comment]
Also soviel nur wenn ein Backup auf ein leeres System gespielt wird, dauert es ein paar Minuten bis der Hap launcher wieder alle Pakete geladen und installiert hat. Auch wenn der HomeKit Button schon in der Systemsteuerung ist.  

Aber das mit den IP Adressen scheint ja "häufig" aufzutreten.

**Comment by steho051** [comment]
Hallo Richard!


Diesen Weg bin ich bisher auch gegangen - alles auf separate Pis und einer liegt als Reserve und entsprechende Backups auf SD-Karte immer griffbereit. 
Einzig beim Tinker ging das nicht (war auch bisher nicht nötig LOL), da hatte ich einen Pi3 als "Not-CCU" daneben hängen, aber meine Frustration ist mittlerweile groß genug...  

Also her mit 2 neuen 4ern...

**Comment by thkl** [comment]
@dkrizic klingt nice gibt's da ne Idiotenanleitung für Leute wie mich, die mit Virtualisierung nix an Hut haben.

**Comment by roe1974** [comment]
@dkrizic ..... sieht sehr cool aus !!!!!!

**Comment by steho051** [comment]
@thkl
Meintest du das mit "den paar Minuten" auch  nach einem RaspberryMatic Update?
Also ich hab das Update laufen lassen und hab ca. ne halbe Stunde später raufgeschaut, da ging nix (auch mein typisches durchklackern der Jalousieaktoren blieb aus, das ist immer verdächtig...)



 @dkrizic 

Dem schließe ich mich an... Platz und Hutschiene sind vorhanden...

**Comment by dkrizic** [comment]
@thkl: Du erinnerst Dich, als ich Dich gefragt habe warum homebridge-homematic damals die History mit dem Hostname gespeichert hat? Es hat mich gestört, weil die Software immer wieder auf einem anderen Node läuft.

Ich habe beruflich mit Kubernetes zu tun und bin auch CKA (Certified Kubernetes Administrator). Aber kurz zum Einstieg:

- Man braucht arm64 und möglichst viel Speicher und CPU, daher Raspberry Pi 4 mit 4GB
- Es läuft Ubuntu 64bit auf den Dingern, Raspbian ist nur 32bit
- Im Prinzip installiert man Docker und Kubernetes (kubelet und kubeadm) auf jedem Raspi (https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/) und lässt auf dem ersten "kubeadm init" laufen und auf allen anderen dann einen "kubeadm join". In diesem Fall spielt der erste Node den Master, die anderen sind Worker.
- Für einen ernsthaften Cluster braucht man mindestens 3 Master (ungerade Anzahl) und davor einen richtigen Load Balancer (in meinem Fall eine pfSense)
- Kubernetes braucht dringend eine Speicherlösung, die in der Lage ist Speicherplatz an jeden der Nodes zu mounten. Für den Anfang reicht ein externer NFS-Server (z.B. Synology), ist aber sehr langsam. Bei mir läuft Ceph (http://rook.io) auf den drei amd64 master nodes welcher die lokalen SSD gespiegelt im Cluster zur Verfügung stellt.

Immer noch Interesse?

**Comment by thkl** [comment]
Holly macaroni... Ähm nein das ist mir zu kompliziert. Da fahre ich als Testsystem lieber ne leere VM mit RM hoch

**Comment by roe1974** [comment]
na bumm ... das klingt nach einer Studienarbeit ;-) ... aber TOP !

**Comment by thkl** [comment]
Ach was, das ist nix anderes als ein glorifiziertes PXE mit Management dahinter. *scrn*

Nein, Tschuldigung das klingt alles sehr kompliziert und für meine Anwendungsfälle viel zu overengineert. 🧢 ab wer da durchsieht.

**Comment by sailor79** [comment]
@steho051: Also ich gehe nach vielen Jahren zurück auf eine CCU3, weiterhin erstmal ohne Addons bis sich die ganzen Thema beruhigt haben. Offensichtlich gibt es gerade viele Änderungen vieler Hersteller (z.B: iOS MAC Randomization etc.). Hadere nur noch ob ich das System komplett neu aufsetzte (mit Werksreset der Teile) oder per Restore. Ansonsten würde ich auch den RPI4 nehmen in Kombination mit dem Metallgehäuse und der externen Doppelantenne von Eugen (stall.biz).
@dkrizic: Absolut beeindruckend, will auch haben. Leider übersteigt das meine Gehinrkapazität. Selbst wenn ich es hinkriegen würde, wüsste ich in einem halben Jahr nicht mehr, das Ding zu bedienen. Aber geniale Sache :-)

**Comment by thkl** [comment]
Also ich bin mit der RM4 Lösung recht zufrieden. Keinerlei Ausfälle seit ich vor 1/2 Jahr von einem R3 geswitcht bin. 

Und ja die Containerlösung von @dkrizic ist sicher der "Heilige Grahl der Stabilität und Verfügbarkeit" aber auch mein Kopf ist literally explodiert beim Leser des Getting Started Guide 🤯

**Comment by twister9916** [comment]
...so Schluss mit dem Spuk. Selbst tägliches Neustarten der Raspberrymatic um 03:30 hat nicht geholfen. Nach spätestens zwei bis drei  Tagen war wieder Stecker ziehen angesagt und manchmal trat das Problem dann 5 Minuten später wieder auf und ich musste dem Tinker Board S nochmal einfach den Stecker ziehen. Jetzt habe ich umgestellt auf eine virtuelle Maschine auf meinem Synology NAS. Bis jetzt funktioniert alles einwandfrei. Für mich spricht immer mehr dafür, dass es an der Hardware liegt, sprich Tinker Board. Leider habe ich nun an meinem NAS keinen USB Port mehr frei und muss eine Lösung suchen für das tägliche Backup der Raspberrymatic das bisher auf einem USB Stick am Tinker Board S lief. Schade.

**Comment by roe1974** [comment]
wieso nicht backup auf der NAS auf einem NFS mount ;)
