### ISSUE TITLE
Überwachungskameras in Homekit

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#226]
Hallo,

ich habe mehrere IP-Überwachungskameras die einen RTSP-Stream zur Verfügung stellen können. Kennt jemand eine Möglichkeit diesen Stream über die CCU in HomeKit einzubinden?

Danke und lieben Gruß

**Comment by dkrizic** [comment]
https://github.com/Sunoo/homebridge-camera-ffmpeg#readme

**Comment by thkl** [comment]
Es gibt ein "Special Device" Video Doorbell. Dieses kann Kamera Streams nutzen. Es muss als eigenes Gerät HomeKit Gerät eingebunden werden und es muss ffmpeg auf der Raspberrymatic installiert werden.

**Comment by gerd2005** [comment]
Ich habe eine normale CCU3, und kein Raspberrymatic. Ich habe gerade versucht das mit NodeRed bzw. Redmatic hinzubekommen. Die Kamera erscheint zwar in HomeKit, es taucht jedoch kein Bild auf. Vermutlich, weil meine Kamereas „nur“ H.265 und nicht H.264 unterstützen. Gibt es weitere Ideen von dir/euch?

**Comment by thkl** [comment]
Alle HomeKit Kameras basieren auf dem Prinzip, das da ein ffmpeg läuft, der den Stream der Kamera auf ein HomeKit kompatibles Format konvertiert. Ob es aber ein ffmpeg Binary gibt, welches auf der CCU3 läuft weiß ich nicht.

**Comment by gerd2005** [comment]
Aha ok. So gut kenne ich mich dann doch noch nicht aus. 
Wenn man ffmpeg auf einem Raspberrymatic installieren kann, geht das doch auf einer CCU3 als Zusatzsoftware sicherlich auch, oder?

**Comment by ykhnhfr** [comment]
> Aha ok. So gut kenne ich mich dann doch noch nicht aus.
> Wenn man ffmpeg auf einem Raspberrymatic installieren kann, geht das doch auf einer CCU3 als Zusatzsoftware sicherlich auch, oder?

Das kommt eben, wie @thkl gesagt hatte dann, wenn es ein ffmpeg binary gibt, welches auf deiner originalen CCU3 läuft.
Ob das der Fall ist, ist die Frage.

**Comment by gerd2005** [comment]
Sorry für meine Unwissenheit... So ganz blicke ich das Thema „ffmpeg Binary“ noch nicht. Habt ihr ein Tutorial o.ä. welches mir weiterhelfen kann? Also eine Anleitung, wie man soetwas auf der CCU installieren kann?

**Comment by sailor79** [comment]
@gerd2005 An Deiner Stelle würde ich mal in das homematic-forum.de schauen, da hat es das Thema bestimmt schon mehrfach gegeben. Eine Suche dort ergibt 37 Treffer, z.B. https://homematic-forum.de/forum/viewtopic.php?f=77&t=47866&hilit=Ffmpeg

Mit HAP-Homematic hat das nicht direkt zu tun. Ich persönlich nutze iobroker, habe dort ffmpeg installiert und streame über einen Rtsp-stream an HomeKit mit dem yahka Addon. 

Gruß 
Marc

**Comment by gerd2005** [comment]
Hallo Marc,

danke für den Hinweis. 
Stimmt, Homekit ist es ja am Ende egal von wo die Daten herkommen. HomeKit sammelt im Grunde ja nur unterschiedliche  Geräte in einer App. 

Ich habe erste Gehversuche mit NodeRed unternommen. Dort geht anscheinend soetwas auch. Für den ioBroker benötige ich vermutlich noch einen Raspberry o.ä., wovon ich erst einmal kein Freund bin, da das zusätzliche Hardware usw. bedeutet.

**Comment by ChrWi** [comment]
Da kein direkter Bezug zu HAP-homematic, sondern allgemein (-> Homematic-forum) schließe ich das Issue hier
