### ISSUE TITLE
is there a possibility to edit the PIN-Code?

### ISSUE THREAD

**Issue by v0r73x** [thkl/hap-homematic#227]
Hi Thomas,

is there a way to modify the PIN Code for the instances to have co-existence of homebridge instances? 
I would have the devices which I have set in hap-homematic also discovered in the homebridge GUI. Is that possible? 

thx and regards,

Robert

**Comment by thkl** [comment]
No, the pin codes are randomly generated.
And you are not able to control HomeKit Instances via HomeBridge GUI. HomeBridge GUI does a little trick to control the devices by talking the the homebridge kernel and not to HomeKit itself.
