### ISSUE TITLE
Unterstützung HM-LC-DW-WM

### ISSUE THREAD

**Issue by fapla1** [thkl/hap-homematic#228]
Danke erstmal für den einfachen und schönen Weg einer HomeKit integration! Ich würde mich über eine Unterstützung des Dual White-LED controllers freuen.

Danke und Grüße!

[HM-LC-DW-WM.txt](https://github.com/thkl/hap-homematic/files/5454958/HM-LC-DW-WM.txt)

**Comment by thkl** [comment]
weiter in https://github.com/thkl/hap-homematic/issues/270
