### ISSUE TITLE
CCU Programm Startet nicht in 0.0.55

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#229]
@thkl Hi, klappt leider bei mir auch nicht. Habe das auch nochmal neu hinzu gefügt. Der Push Button Service zum selben Programm startet es aber. Ist die 500 ms vielleicht zu kurz?

_Originally posted by @meistermolli in https://github.com/thkl/hap-homematic/issues/223#issuecomment-718212611_

**Comment by thkl** [comment]
Was ggf Aufschluß bringt:

Auf dem CCU WebUI unter Programme gibts eine Funktion Script testen.
Dort mal das hier testen:

```
object o = dom.GetObject(ID_PROGRAMS).Get('XXX');if (o){Write(o.ProgramExecute());} else {Write('program not found by rega');}
```

XXX gegen den Namen des gewünschten Programmes ersetzen.
Das müsste das Programm starten. Das ist auch das was hap macht

**Comment by Peyto79** [comment]
Kann es sein, dass in der Code-Zeile die letzten beiden Zeichen vertauscht sind?

**Comment by thkl** [comment]
Wie schaut das Script aus wenn es funktioniert ?

**Comment by Peyto79** [comment]
Hinten einfach nur Semikolon und geschweifte Klammer in der Reihenfolge vertauschen.

object o = dom.GetObject(ID_PROGRAMS).Get('XXX');if (o){Write(o.ProgramExecute());} else {Write('program not found by rega')**};**

**Comment by thkl** [comment]
Nooooo das ; schließt das Write Command ab

**Comment by Peyto79** [comment]
Ja eben, aber in deiner Code Zeile ist es vertauscht. :-)

**Comment by Peyto79** [comment]
Aber es funktioniert wenn ich es vertausche. Oder fehlt etwa ein weiteres Semikolon?
Ich bin leider kein Script Profi. Aber es läuft wenn ich ich das Semikolon an letzte Stelle setze.

**Comment by meistermolli** [comment]
Hi @thkl - Also bei mir:

Programm Name: Programm Haustüre Öffnen
Wenn: Virtueller Taster Tastendruck Kurz,
Dann: Keymatic - Öffnen

Skript Testen: Funktioniert - TRUE - Falle der Keymatic wird zurück gezogen.
object o = dom.GetObject(ID_PROGRAMS).Get('Programm Haustüre Öffnen');if (o){Write(o.ProgramExecute());} else {Write('program not found by rega');}

Virtueller Taster im HomeKit als Trigger:
der Virtuelle Taster über HAP Homematic hinzugefügt. Auch dieser Taster Funktioniert in der Home App und öffnet die Keymatic.


**Das Programm über HAP Hinzufügen funktioniert - Programm Sichtbar im HomeKit.
Das Programm ausführen aus HomeKit Home App leider nicht möglich. Keine Reaktion**

Gruß meistermolli

**Comment by thkl** [comment]
Ok ich werde nochmal nen Blick werfen. Ich benutze diese Funktion mehrfach täglich.

**Comment by meistermolli** [comment]
Merci, aus der Eve app startet es auch nicht. Muss hier ggf. noch irgendwo eine Freigabe erteilt werden?

**Comment by thkl** [comment]
nein das ist alles das gleiche

**Comment by meistermolli** [comment]
Hi, hast du schon eine Idee woran es liegen könnte?

**Comment by meistermolli** [comment]
versuche das nun in 0.0.57 erneut und verweise sonst auf dieses Issue.

**Comment by meistermolli** [comment]
Issue Update:
habe einen Einfluss auf die Bedienbarkeit des Homematic Programs in Homekit gefunden.


Festlegung der "Wenn" Bedingung im CCU Programm.

Das Program habe ich in mehreren Versuchen so angelegt:
1. Wenn
  ein Taster gedrückt wird
   oder
      ein Virtueller Taster gedrückt wird (in Homekit angelegt, da die Programme von mir nicht starten konnten)
..............
weiterer versuch:
2. Wenn
  ein Taster gedrückt wird
   oder
      ein Virtueller Taster (in Homekit angelegt, da die Programme von mir nicht starten konnten)
   oder
      leer
..............
Die beiden Schalten in Homekit nicht, wenn ich es als Program über HAP Homematic einbinde.
Siehe weiter oben im Issue, alle anderen Bedingungen und Bedienung über den Programm Button in der Webui funktionieren.

Skript Testen: Funktioniert - TRUE 
object o = dom.GetObject(ID_PROGRAMS).Get('Programm Haustüre Öffnen');if (o){Write(o.ProgramExecute());} else {Write('program not found by rega');}


3. Wenn Leeres Feld

Ein Program ohne Wenn Bedingung und nur mit Sonst bedingungen kann bei mir in Homekit gestartet werden.


Ist das generell so und bei mir ein Verständnisproblem?
Dann kopiere ich mir einfach die Entsprechenden Programme und lösche meine Trigger da raus.
Schöner wäre aber, wenn ich das bestehende Program mit den anderen Triggern auch in Homekit auslösen könnte.

--- Kann jemand im Wiki die entsprechende Info hinzufügen?

Gruß meistermolli
