### ISSUE TITLE
HomeKit zeigt „Keine Antwort“ für alle von dieser App kommenden Geräte

### ISSUE THREAD

**Issue by sailor79** [thkl/hap-homematic#230]
Hallo Thomas,

in Apple HomeKit haben alle HAP-HM Geräte keine Verbindung mehr (andere schon).
Was habe ich bei mir geändert? 1. Update auf 0.55 und 2. Änderung der IP-Adresse der CCU und damit auch des Service. Hat letzteres Einfluss auf die Bridge-Verbindung?
PS Neustart aller betreffenden Geräte im Haus hatte keinen Einfluss.
Danke und Gruß 
Marc

**Comment by thkl** [comment]
Die IP Adressen der HAP Devices werden zwar per mDNS im Netzwerk verbreitet aber ich weiss jetzt nicht ob HomeKit das automatisch umwurstet. Du kannst ja mal zum Test eine Instanz aus Homekit rausnehmen und wieder neu hinzufügen.

**Comment by sailor79** [comment]
Ja, leider wahr. Dann gehts, was natürlich nicht Sinn der Sache ist. Ich informiere mich mal, wie Apple das handhabt.

**Comment by sailor79** [comment]
Also Apple hat da mal wieder ne offene Flanke, es gibt aber eine 3rd party App, die zumindest die ganzen Automationen etc. sichern und zurückspielen kann. 
Nach einem Wechsel der IP einer Bridge oder der SSID z.B. Anbieterwechsel hört by Bonjour der Spaß auf. Ansonsten dreht sich wieder alles um herstellerübereifendes mDNS/ IGMP snooping usw. Das Thema wird langsam zum generellen Problem, jedenfalls bei mir...
