### ISSUE TITLE
Siri gibt falschen bzw. kein Feedback

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#231]
Hallo,

ich habe für unser Garagentor das hier gekauft...
https://www.tor7.de/hoermann-homematic-ip-gateway-inkl-hcp-adapter

... und soeben angeschlossen und eingerichtet. Das Homematic-Gerät funktioniert am Ende wie ein Rolladenaktor mit den Zuständen Auf, Zu und Stopp. Wenn ich nun Siri sage: „Öffne das Garagentor“, passiert genau das. Soweit so gut... Allerdings gibt sie mir als Feedback, dass das Gerät nicht reagiert. Ich habe die Garage auch einmal komplett entfernt und alles noch einmal neu eingerichtet, CCU neu gestartet und und und... Allerdings ohne Erfolg. Hat jemand eine Idee woran das liegen könnte?

![39121075-C8CE-46BE-8D38-3426C718222E](https://user-images.githubusercontent.com/72799068/97723575-3c2a7c80-1acc-11eb-9a11-46987ff1e0b4.png)
![591F49FD-5316-4149-AF13-1AE7BAEF16DB](https://user-images.githubusercontent.com/72799068/97723595-42205d80-1acc-11eb-9f08-5e325447b020.png)

**Comment by gerd2005** [comment]
Ich habe den Fehler denke ich gefunden. Das ist wieder diese Geschichte mit dem Standardraum. Warum auch immer, wurde das Garagentor zwei mal hinzugefügt. Einmal in den Raum „Garage“ und ein weiteres mal in den Raum „Standardraum“. Wie ich jetzt allerdings den Standardraum entfernt bekomme... keine Ahnung....

![A3B8C47F-310E-45C9-90BE-59AE99048D76](https://user-images.githubusercontent.com/72799068/97732291-9e887a80-1ad6-11eb-8fc2-f9b984b4f60a.png)
![ED56343A-90A1-4D25-9097-4D667A48C032](https://user-images.githubusercontent.com/72799068/97732316-a811e280-1ad6-11eb-88f1-00fc9938fd09.png)
![3FC9DF0D-D34C-4110-8077-749C19507DD4](https://user-images.githubusercontent.com/72799068/97732318-a811e280-1ad6-11eb-8a0c-4938e527c0cf.png)

**Comment by gerd2005** [comment]
Ich habe die Bridge im Standardraum gelöscht. Das Problem besteht aber weiterhin, dass Siri ein falsches Feedback gibt. Sehr seltsam...

**Comment by blackbasket** [comment]
Hallo Gerd,

hast du iOS 14.1 installiert? Ich bekomme seit der Installation gestern auch teilweise seltsame Rückmeldungen, aber es funktioniert alles.

LG,
Marcel

**Comment by gerd2005** [comment]
@thkl wäre es evtl. möglich, dass du dir das Problem einmal anschaust? Ich glaube ehrlich gesagt nicht, dass es an iOS14 liegt.

**Comment by gerd2005** [comment]
Dieses Issue kann denke ich geschlossen werden. Siri gibt nun einkorrektes Feedback beim Öffnen und Schließen des Tores wieder.
![AD0662ED-1EBD-4CEA-A490-080C8921FAA9](https://user-images.githubusercontent.com/72799068/103364703-c5573300-4abe-11eb-82f1-60fb344e020f.jpeg)
![F3ABF868-F8CD-49B9-94DB-D18DFBBCE6E8](https://user-images.githubusercontent.com/72799068/103364706-c720f680-4abe-11eb-9dc9-4cf75ecb182c.jpeg)
![BE4E24D8-E04A-416A-9FA3-AB37686135DD](https://user-images.githubusercontent.com/72799068/103364710-c7b98d00-4abe-11eb-9eb5-487eefdf7a51.jpeg)
![F310644C-828E-425B-A263-097D63A62491](https://user-images.githubusercontent.com/72799068/103364714-c8522380-4abe-11eb-8dbb-28825601f80e.jpeg)

Beim Schließen des Tores aktiviert sich allerdings die „Lüftung“. Auch wenn das Tor schon längst geschlossen ist, dreht sich der Ventilator fröhlich weiter. Das Verhalten muss ich noch einmal genau beobachten und eröffne dann ein neues Issue. Zudem habe ich den Eindruck, dass beim Aktivieren der Lüftung das gesamte PlugIn abstürzt. Alle Geräte erhalten dann auf einmal den Status „Gerät antwortet nicht“. Aber auch das muss ich noch einmal genau nachstellen und dokumentieren.

Danke, lieben Gruß und einen guten Rutsch.
