### ISSUE TITLE
Dimmer Werte synchronisieren 2 (siehe #202)

### ISSUE THREAD

**Issue by dl-84** [thkl/hap-homematic#232]
Hallo Thomas,

leider habe ich keine andere Kontaktmöglichkeit gefunden als einen neuen Issue zu öffnen.
Das Problem das ich in #202 beschreiben habe besteht leider weiterhin.

Vielleicht hättest du ja mal Zeit und Lust, dann könnten wir uns das mal in einer Remote Sitzung bei mir ansehen.

Viele liebe Grüße.
Daniel

**Comment by thkl** [comment]
Wie ist denn der Stand der Dinge ? Der letzte Eintrag in dem anderen Issue war, das bei 0 der Dimmer nicht im Zustand aus war.

**Comment by dl-84** [comment]
Das ist leider immer noch aktuell. 
Bei 0 erscheint nicht Aus sondern ein Dimmwert von 0% und die Lampe meldet das sie an ist obwohl dies nicht der Fall ist.

**Comment by thkl** [comment]
Welcher Service wird da benutzt ?

**Comment by dl-84** [comment]
Ich nutze den HomeMaticVariableAccessory Service
