### ISSUE TITLE
HMIP-PSM Strommessung vom Wäschetrockner/Waschmaschine als Pushnachricht ausgeben?

### ISSUE THREAD

**Issue by Icke-NOH** [thkl/hap-homematic#233]
Hallo, wie bekomme ich meine Wäschetrockner Fertig Meldung mit 

[https://github.com/thkl/hap-homematic/commit/1c5b0dd0409ffc36c0551b28c360eb29ce631925](url)

verknüpft? Kleiner Denkanstoss wäre nett :) 
<img width="1082" alt="Bildschirmfoto 2020-10-31 um 12 12 41" src="https://user-images.githubusercontent.com/72289306/97777875-51a6b180-1b73-11eb-85ce-872d77c94354.png">

**Comment by thkl** [comment]
Das geht nicht so direkt, weil HomeKit keine selbst definierten Push Meldungen zulässt.
Was geht ist eine Virtuelle Taste mit einer HomeKit DoorBell zu verknüpfen und die virtuelle Taste durch die CCU bei Trockner Fertig zu drücken. Dann klingelt es halt an der Tür im Keller ...
