### ISSUE TITLE
Merkwürdiges Verhalten Automationen mit HmIP-eTRV-B

### ISSUE THREAD

**Issue by han-gru** [thkl/hap-homematic#234]
Zunächst einmal vielen Dank für deine Arbeit!

Ich habe jedoch das Problem, dass die über die Home-App eingestellten Automationen nicht korrekt ausgeführt werden. 

[Hier ein Video dazu.](https://gofile.io/d/uYk7Zb) 

Erklärung: Eigentlich sollen um 21 Uhr alle Heizungen auf 19 °C reguliert werden. Einige der Heizkörper waren bereits vor 21 Uhr auf 19 °C gestellt, hier geht es mir nur um die beiden Heizungen im Wohnzimmer (Heizung Wohnzimmer und Heizung Couch Wohnzimmer). Heizung Wohnzimmer ist korrekt reguliert, Heizung Couch Wohnzimmer steht bei 22 °C und erst nach antippen der Kachel springt die Temperatur in der App und auch am Thermostat um. Es ist also nicht nur eine falsche Darstellung in der App, die Senkung der Temperatur wird auch nicht an das Thermostat weitergereicht. 

Probleme treten bei mir mit allen Thermostaten auf, die in Automationen eingebunden sind. 

Kennt noch jemand das Problem?

Ich benutze die aktuellste Version (.55).

**Comment by gerd2005** [comment]
Hallo,

die Automationen funktionieren bei mir in HomeKit auch nicht zuverlässig. Aus diesem Grund verwaltete ich alle Automationen in der CCU selber.

**Comment by thkl** [comment]
Das Problem liegt daran das 2 Events ankommen. Einmal das Setzen der Temperatur und einmal das Setzen des Modus (Auto/Heizen) etc. Diese sind nicht immer in der gleichen Reihenfolge. Damit bei der manuellen Bedienung die Anzeigen nicht hin und her springen (das passiert weil ein Setzen des Modus einen Event mit der Rückgabe der aktuellen Temperatur aus der Schnittstelle zur Folge hat), werden alle Events ignoriert die in der Zeit eintreffen, bis der Befehl von der CCU ausgeführt wurde. HomeKit schickt aber den Temp Befehl unmittelbar danach, so das er "verloren" geht.

Ich kenne das Problem, habe aber irgendwie noch keine gute Idee das zu lösen

**Comment by han-gru** [comment]
Vielen Dank erst mal für die Antworten.

Leider habe ich nicht nur zeitbasierte Automationen, sondern auch Personenbezogene (Stichwort Geofencing), teilweise auch Zeit+Person. Die zeitbasierten kann ich sicherlich problemlos auf die ccu auslagern, die personenbezogenen jedoch nicht (außer vielleicht mit mediola), zumindest habe ich noch keine Möglichkeit gefunden, die ccu erkennen zu lassen, dass meine Frau oder ich zu Hause sind. Gibt’s da vielleicht was?

**Comment by thkl** [comment]
Du könntest je eine Personenbezogene Automation nutzen um eine Variable für die Anwesenheit der jeweiligen Personen im Haus zu setzen (man kann Variablen über HAP setzen) und dann in der CCU diese nutzen um zu ermitteln ob 1 oder mehrere Personen da sind ...

**Comment by han-gru** [comment]
Klingt interessant 😅 bisher reichen meine Kenntnisse da noch nicht, aber da kann man sich sicherlich einlesen. Ich danke dir für die Info. Hier kann dann wieder zu 😊

**Comment by gerd2005** [comment]
Schau mal hier. Ich glaube das hilft dir. 

https://youtu.be/f9XsboS1ZGE

**Comment by han-gru** [comment]
Danke Gerd, das hat mir sehr geholfen. Programme laufen nun direkt über die ccu, über hap habe ich die Variablen für die Anwesenheitserkennung zu Home hinzugefügt. Heute lief das „Zu Hause ankommen“ noch nicht, da habe ich aber glaube ich den Fehler im Programm gefunden und entsprechend eine Änderung vorgenommen. Mal schauen ob es morgen klappt. 👍
