### ISSUE TITLE
Rolladenaktor gibt Behangwerte an CCU3, aber nicht an Apple Home zurück

### ISSUE THREAD

**Issue by ykhnhfr** [thkl/hap-homematic#235]
Mir ist aufgefallen, dass wenn man die Höhe des Behangs per Schalter abändert, kann die CCU3 den Wert zwar korrekt anzeigen und erkennt die Höhe, in der Home App von Apple gibt es aber nur den Status offen oder geschlossen, keinen Prozentwert des Behangs, den ich sehen würde, wenn ich die Höhe per App verändere. 

Siehe Beispiel auf meinen Fotos:

Bei den 40% wurde die Behanghöhe per Home App eingestellt. Dies spiegelt die CCU3 dann auch wieder.
Danach habe ich die Behanghöhe per Schalter auf 31% eingestellt, jetzt zeigt die App den Rolladen als geschlossen an, weil der Behang mehr in Richtung 0% gestellt wurde. Hätte ich den Behang "geöffnet, weiter in Richtung 100% Höhe, so hätte die App mir den Rolladen als geöffnet angezeigt, obwohl dieser ja immer einen Status dazwischen hat. 

Hier in der Home App, 40% darüber eingestellt. 
![40_App](https://user-images.githubusercontent.com/63097862/97802742-f1cd0b00-1c45-11eb-83b6-3be24f8c8dff.jpg)

Wert wird in die CCU3 übermittelt.
<img width="548" alt="40_App" src="https://user-images.githubusercontent.com/63097862/97802745-f85b8280-1c45-11eb-9c07-9ca547f3fd96.png">
 
Änderung per Schalter, die Home App zeigt den Rolladen als geschlossen an.
![31_Schalter](https://user-images.githubusercontent.com/63097862/97802739-ee398400-1c45-11eb-8cf4-b66082a46e7f.jpg)

Wert wird aber korrekt in die CCU3 übermittelt, ggf. aber nicht ausgelesen um das in der Home App anzuzeigen.
<img width="537" alt="31_Schalter" src="https://user-images.githubusercontent.com/63097862/97802744-f72a5580-1c45-11eb-9609-5448696f33b0.png">

Vielleicht geht das ganze ja auch gar nicht. Wäre aber cool, wenn das implementiert würde.
LG

**Comment by thkl** [comment]
Passiert das auch, wenn die Höhe per WebUI in der CCU geändert wird ?

**Comment by ykhnhfr** [comment]
Ja, auch dann passiert das.

Am 01.11.2020 um 13:49 schrieb Thomas Kluge <notifications@github.com>:

﻿

Passiert das auch, wenn die Höhe per WebUI in der CCU geändert wird ?

**Comment by ChrWi** [comment]
@ykhnhfr hast du die letzte Firmware auf dem Aktor? Bei meinen Geräten (Broll) hatte ich mit dem Auslieferzustand derartige Probleme

**Comment by ykhnhfr** [comment]
@ChrWi Also die 1.8.16 habe ich. Müsste die letzte sein.

**Comment by ChrWi** [comment]
Ok, die habe ich auch. Bei mir funktioniert alles - ich habe aber CCU3 (3.53.30, mit der HAP 0.0.54) auf einem Raspberry laufen.

**Comment by thkl** [comment]
Die .55 hat eine kleine Änderung beim Rollo. Dort wird aller 30 Minuten der aktuelle Zustand von Rollo abgefragt. Das sollte aber auf dieses Problem weniger Einfluss haben. Theoretisch müsste es sogar besser werden.  Stimmt nach 30 Minuten der Zustand ?

**Comment by ykhnhfr** [comment]
Ich habe das überprüft. Zustand stimmt auch nach 30 Minuten nicht. Ggf. ist noch etwas falsch konfiguriert oder muss ich dafür nichts besonderes einstellen?

**Comment by ChrWi** [comment]
Gelöst in #426
