### ISSUE TITLE
Nach Neustart der CCU3 und Update auf Version 0.0.55 alle Geräte weg

### ISSUE THREAD

**Issue by mano87** [thkl/hap-homematic#237]
Seit einem Neustart der CCU3 und dem zuvor durchgeführten Update auf Version 0.0.55 sind nun alle Geräte im HomeKit verschwunden.

Was kann ich tun?

**Comment by Ritschi75** [comment]
Ebenfalls bei mir nach Installation der 0.0.55 keine Geräte mehr vorhanden.
Auch eine Neuinstallation brachte nichts.
Kann der Bug nachvollzogen werden?

**Comment by thkl** [comment]
Welche CCU Version und auf welcher Hardware ?

**Comment by Ritschi75** [comment]
> Welche CCU Version und auf welcher Hardware ?

Version: 3.53.30.20201024
Hardware: Thinkerboard

**Comment by sailor79** [comment]
Welche IP-Adresse hatte Deine CCU vor dem Neustart, und welche danach?

**Comment by mano87** [comment]
Also ich nutze die CCU3 mit Firmware 3.53.34. Die IP-Adresse ist fest hinterlegt und ändert sich in meinem Fall nicht.

**Comment by Ritschi75** [comment]
Auch ich habe eine fixe IP vergeben.

**Comment by sailor79** [comment]
Ich frage deshalb, weil meine ebenfalls fest hinterlegt war, aber sich am Tinkerboard die .Mac-Adresse geändert hat (warum noch unklar), und dadurch die Fritz!box zwangsweise eine neue IP vergeben hat.

**Comment by jakob-martens** [comment]
Habe das gleiche Problem. Kann es evtl. mit https://github.com/thkl/hap-homematic/issues/205 zusammenhängen? Ich frage, weil das Problem bei mir aufgetreten ist, kurz nachdem ich versucht habe gleichnamige Geräte hinzuzufügen.

**Comment by thkl** [comment]
Gleichnamige Geräte führen nur dazu, das ein Gerät von Beiden nicht mehr in der Config Oberfläche angezeigt wird.
Sind die Geräte noch in HomeKit vorhanden ?

**Comment by jakob-martens** [comment]
OK, dann ist das ein anderes Problem. Bei mir war es so, dass in HomeKit die Geräte noch da waren, jedoch keine Verbindung mehr hatten. Auf der Weboberfläche war alles weg und ich konnte auch keine neuen Geräte mehr anlegen, hat nichts funktioniert. Ich habe dann das Addon deinstalliert und neu installiert, danach ging wieder alles. In den von dir genannten Ordnern gibt es keine Logfiles mehr von gestern.

**Comment by thkl** [comment]
Hmm Schade, dann lässt sich in dem Falle leider nicht mehr ermitteln wo der Bug ist.

Generell hilft es mir bei der Fehlersuche, wenn das LogFile und die config.json aus dem addons/hap-homematic/ vor einem Reinstall gesichert werden. Das Logfile überlebt iÜ einen CCU Reboot nicht, denn /var/log liegt auf einer RAM Disc.

**Comment by Ritschi75** [comment]
> Hmm Schade, dann lässt sich in dem Falle leider nicht mehr ermitteln wo der Bug ist.
> 
> Generell hilft es mir bei der Fehlersuche, wenn das LogFile und die config.json aus dem addons/hap-homematic/ vor einem Reinstall gesichert werden. Das Logfile überlebt iÜ einen CCU Reboot nicht, denn /var/log liegt auf einer RAM Disc.



> Hmm Schade, dann lässt sich in dem Falle leider nicht mehr ermitteln wo der Bug ist.
> 
> Generell hilft es mir bei der Fehlersuche, wenn das LogFile und die config.json aus dem addons/hap-homematic/ vor einem Reinstall gesichert werden. Das Logfile überlebt iÜ einen CCU Reboot nicht, denn /var/log liegt auf einer RAM Disc.

Wo kann ich die log Datei zur Verfügung stellen? Kenne mich hier nicht so aus.

**Comment by thkl** [comment]
die kann hier angehangen werden einfach per drag&drop in das Textfeld reinziehen

**Comment by FabianLR** [comment]
Ihr schreibt hier von Version 0.0.55, ich finde nur Verein 0.0.14........ das verwundert mich, bin ich blind? Nein bin ich nicht, aber neu hier 😬

**Comment by thkl** [comment]
https://github.com/thkl/hap-homematic/wiki/prerequisites#what-is-the-difference-between-the-version-numbers-from-ccu-addon-and-number-at-the-webui-

**Comment by ChrWi** [comment]
@jakob-martens das Thema ist fast 1 Jahr alt und mittlerweile gibt es 0.0.63
Ist das Thema noch aktuell?
