### ISSUE TITLE
FR  HomeMaticVarBasedElectricConsumptionAccessory - Consumption Multiplikator < 1 ermöglichen

### ISSUE THREAD

**Issue by artspe** [thkl/hap-homematic#239]
Ist es möglich kleinere Werte als 1 als Multiplikatoren für das Variablen Accessory zu ermöglichen. Usecase: Ich nutze Modbus um einige Variablen mit Verbrauchswerten meines Wechselrichters auszulesen und muss diese mit 0,001 für die Umrechnung in kWh multiplizieren.

**Comment by thkl** [comment]
hmm der Faktor ist ein Float also 0.001 sollte zb. durch 1000 teilen

**Comment by blackbasket** [comment]
@artspe besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)
