### ISSUE TITLE
Zeitverzögerung  für garagentor sensor

### ISSUE THREAD

**Issue by fighterzg6** [thkl/hap-homematic#24]
bei der homebridge kann ich eine zeit für den Kontaktsensor angeben (sensor_requery_time) weil das tor bissel zeit braucht bis es zu ist! könnte man das hier auch machen?

und wofür sind diese punkte
Delay open actor,Delay close actor????

**Comment by thkl** [comment]
sensor_requery_time mach ich .

Die Delays werden benutzt um den Schalt-Aktor wieder auszuschalten. Nehmen wir an Du hast einen Switch der aber nur einen Impuls an die Torsteuerung geben muss. Dann schaltet dieses Delay den Aktor nach x (default 5) Sekunden wieder aus.
