### ISSUE TITLE
Valves schalten nicht (mehr)

### ISSUE THREAD

**Issue by arndtk** [thkl/hap-homematic#242]
Hallo zusammen, 

im Zuge der Entleerung meiner Bewässerungsanlage fiel mir heute auf, dass sich die Ventile nicht mehr schalten lassen. In der Homekit App werden die Symbole korrekt dargestellt, klicke ich drauf, passiert allerdings nichts.

Schalte ich das Ventil über HM-App klappt alles und der Status wird auch korrekt in der Homekit APP angezeigt, nur ist leider keine Bedienung von dort aus mehr möglich.

Ich nutze die aktuellste HAP Version.

Hat dieses Problem vielleicht noch jemand?

Viele Grüße
Arndt

**Comment by thkl** [comment]
Welches HM Gerät und welcher Service wird benutzt ?

**Comment by arndtk** [comment]
Hallo, entschuldige bitte, aber es geht wieder, warum auch immer. Ich hatte es wirklich mehrfach probiert, ohne Erfolg. 

Nun gut, so ist es ja umso besser. :-)
