### ISSUE TITLE
Automatischen Neustart Definierten

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#244]
Hallo,

bei meinem rumgefummel kommt es schonmal vor, dass HAP neugestartet werden muss.
Das habe ich aber schonmal vergessen und meine Frau konnte dann morgens die Geräte nicht bedienen.

Kann man einen automatischen Neustart deffinieren auf z.B. nachts um 02:00 oder frei wählbar?

Danke und Gruß 
meistermolli

**Comment by thkl** [comment]
Per cron Job geht das. Das Command ist "/etc/config/rc.d/hap-homematic restart"

Allerdings macht der hap Dämon von alleine einen quasi Restart wenn seine Config geändert wird.
