### ISSUE TITLE
HmIP-BDT Dimmbereich

### ISSUE THREAD

**Issue by Jemeins** [thkl/hap-homematic#245]
Moin,
da das Dimmen von LED´s immer wieder zu Problemen führt, wäre es schön wenn man den Dimmbereich seitens HomeKit anpassen könnte.

Ich stelle mir das so vor, dass man eine minimal und maximal Grenze definieren kann.
Dimmer Grenze minimal: 20
Dimmer Grenze maximal: 80

Der HomeKit regelbereich sollte trotzdem 0 bis 100% umfassen.

**Comment by thkl** [comment]
Kann man das nicht in den Geräteeinstellungen in der CCU schon machen ?

**Comment by Jemeins** [comment]
Bei dem HmIP-BDT wohl leider nicht, habe auch schon ein Telefonat mit eQ-3 diesbezüglich geführt.

**Comment by thkl** [comment]
Also soll quasi der CCU Dimmerbereich weiter proportional zum HomeKit laufen Beispiel:
min = 20 ; max = 80
HomeKit = 0 -> CCU = 0
HomeKit = 20 -> CCU = 32
HomeKit = 50 -> CCU = 50
HomeKit = 70 -> CCU = 62
HomeKit = 100 -> CCU = 80

**Comment by Jemeins** [comment]
Genau!

**Comment by thkl** [comment]
Nope HK = 1 - CCU =  20.6 ;) aber ja ;)

**Comment by Jemeins** [comment]
Müsste 1% HK nicht der minimal Einstellung also 20% CCU entsprechen?
Jedenfalls wäre ich sehr dankbar für eine Integration! :)

**Comment by thkl** [comment]
Und 0,1% ? 
Egal es ist fertig. Siehe Commit oben.

**Comment by Jemeins** [comment]
Vielen Dank! Das ging ja schnell :) 
Ich probiere es so bald wie möglich.
Ich war immer der Meinung das HomeKit nur mit Ganzzahlen arbeitet

**Comment by Jemeins** [comment]
Die Funktion ist dann mit im nächsten Update enthalten?
Oder wie kann ich die so bald wie möglich testen?

**Comment by thkl** [comment]
ist in .56

**Comment by Jemeins** [comment]
Ich hatte jetzt die Gelegenheit das Feature zu testen.
Dabei ist mir aufgefallen das die Anzeige in HomeKit nicht ganz korrekt ist.

-Ich schalte den Dimmer an dem Taster ein
-Dimme am Taster maximal weit runter
-HomeKit zeigt die Lampe als ausgeschaltet an

Meine Einstellungen:
HAP-HomeMatic: 
min:10
max:50

Direktverknüpfung:
Pegel im Zustand "ein": 50%
Pegelbegrenzung beim Hochdimmen: 50%
Pegelbegrenzung beim Herunterdimmen: 10%
