### ISSUE TITLE
Instanzen werden nicht veröffentlicht

### ISSUE THREAD

**Issue by Snake-Doc81** [thkl/hap-homematic#246]
Hallo zusammen,

ich habe meine CCU3 frisch auf RaspberryMatic gebracht und dann frisch HAP installiert.
Ich bekomme allerdings nur 9 von 12 Instanzen veröffentlicht. Eine davon ist die "Default"-Instanz.

Auch eine saubere Neuinstallation hat den selben Effekt. Wenn ich die Instanzen zum Aktivieren anklicke und auf Fertigstellen klicke, passiert rein gar nichts.
Die entsprechenden Ports sind in der Firewall freigeschaltet.

Kann mir jemand helfen?

Danke
![Instanzen](https://user-images.githubusercontent.com/74423059/99098345-2becc400-25d9-11eb-80ea-64b38491c5f1.JPG)

**Comment by han-gru** [comment]
Geht es darum, dass du die HomeKit-Codes für die Instanzen zum hinzufügen in Apple Home erhältst oder um die Veröffentlichung deiner bereits den Instanzen hinzugefügten Geräte?

**Comment by han-gru** [comment]
Oder anders gefragt: Hast du den nicht aktivierbaren Instanzen schon Geräte zugeordnet?

**Comment by Snake-Doc81** [comment]
Okay, dummer Anfänger-Fehler.
Der Assistent hatte die Geräte, welche sich hinter den "Instanzen" hätten befinden sollen, nicht zugeordnet bzw. aktiviert.
Nachdem ich jetzt die passenden Geräte hinzugefügt und der Instanz zugeordnet habe, funktioniert auch alles!

Danke für die schnelle Hilfe!
