### ISSUE TITLE
GarageDoor Fehler

### ISSUE THREAD

**Issue by harun-28** [thkl/hap-homematic#247]
Hallo, folgendes Szenario:

HM-LC-Sw1-Pl-CT-R1 als Aktor für die Garage mit zwei Fensterkontakten. 
In der CCU3 und Hap Homematic konfiguriert erscheint der Button in der Homeapp, jedoch zeigt er immer nur „Garage wird geöffnet“

Zudem wenn ich die Homeapp schließe und wieder öffne bekomme ich an allen Geräten den Status erneut mitgeteilt. 

Anbei mal alle Screenshots von den Konfigurationen. 

![01FC233A-4D99-42D0-B4F3-FC8A0DEE8AF3](https://user-images.githubusercontent.com/74476450/99160267-b7537b80-26e5-11eb-883e-4da961cd3375.jpeg)
![8DBFCB43-B52C-4EEE-A54B-CFCB36540EED](https://user-images.githubusercontent.com/74476450/99160270-b9b5d580-26e5-11eb-8555-11f5bfb7d59a.jpeg)
![E50558BA-8B51-4A79-993F-90FE571CC8DF](https://user-images.githubusercontent.com/74476450/99160272-bae70280-26e5-11eb-83ec-ded729c6c35a.jpeg)
![B906B1CF-06CE-472F-8A91-99EBD90EF675](https://user-images.githubusercontent.com/74476450/99160273-bae70280-26e5-11eb-8234-5b78cb8d8e81.jpeg)

**Comment by ciddi89** [comment]
Hallo, 

hab heute zwei SWDO Sensoren und ein PCBS Aktor installiert und hab das selbe problem. Gibt es schon eine Lösung? Meine Config sieht so aus:

![image](https://user-images.githubusercontent.com/66088020/107678367-988c6300-6c9b-11eb-8d8f-fba8214235b2.jpeg)

![image](https://user-images.githubusercontent.com/66088020/107678339-8f9b9180-6c9b-11eb-87b4-c1ee99bcc530.jpeg)

Danke schonmal. LG

**Comment by harun-28** [comment]
Leider nein
Bei mir hilft es jedesmal den cache zu löschen in hap oder aber die home app zu beenden und neustarten.

Am 11.02.2021 um 19:02 schrieb ciddi89 <notifications@github.com>:

﻿

Hallo,

hab heute zwei SWDO Sensoren und ein PCBS Aktor installiert und hab das selbe problem. Gibt es schon eine Lösung? Meine Config sieht so aus:

[image]<https://user-images.githubusercontent.com/66088020/107678367-988c6300-6c9b-11eb-8d8f-fba8214235b2.jpeg>

[image]<https://user-images.githubusercontent.com/66088020/107678339-8f9b9180-6c9b-11eb-87b4-c1ee99bcc530.jpeg>

Danke schonmal. LG

**Comment by ciddi89** [comment]
> Leider nein

Danke für die Rückmeldung. Hmm okay. Mit einem Sensor läuft es erstmal aber sobald ich den zweiten mit rein nehme dann kommt der Fehler das er immer den falschen Status zeigt. Werde es morgen nochmal probieren und sonst teste ich es mal mit Yahka auf ioBroker.

**Comment by ChrWi** [comment]
Ich mache hier zu, da #397 aktueller
