### ISSUE TITLE
HmIP-SRH bitte auch als Türkontakt

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#250]
Der Fenstergriffsensor (HmIP-SRH) kann entgegen seinem Namen auch an Türen verbaut werden. Kommt häufig bei Balkon- bzw. Terreassentüren vor, welche geschlossen, geöffnet oder gekippt werden können. Hier wäre es schön, wenn ein entsprechender Service hinzugefügt werden könnte, so dass die Visualisierung dann auch stimmt.

**Comment by thkl** [comment]
Könnte ich hier mal bitte das Devicefile angehangen bekommen. (siehe https://github.com/thkl/hap-homematic/wiki/internals#support ) Da fehlen mir einige Daten.

**Comment by detLAN** [comment]
Anbei die gewünschte Datei 
[HmIP-SRH.json.txt](https://github.com/thkl/hap-homematic/files/5578033/HmIP-SRH.json.txt)

**Comment by thkl** [comment]
hmm der Sensor bringt den Kanaltype ROTARY_HANDLE_TRANSCEIVER mit und der wird durch HomeMaticRotarySensorAccessory unterstützt. Das sollte also schon funktionieren ?

**Comment by detLAN** [comment]
Wieder mein Fehler, habe HomeMaticRotaryWindowAccessory genommen. Mit HomeMaticRotarySensorAccessory ist es jetzt wie beim HmIP-SWDO - Perfekt.
Vielen Dank für Deine Mühe. Ich mach dann hier zu.
