### ISSUE TITLE
HMIP-SWDO bitte auch als Türkontakt ohne Antrieb

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#251]
Der Fenster- und Türkontakt (HMIP-SWDO) wird in der Eve App als Türantrieb dargestellt, aktuell wird dieser als Türkontakt genutzt. Bei der Nutzung als Fensterkontakt gibt es dieses Verhalten nicht.  Hier wäre es schön, wenn dem Service für diesen Kontaktschalter die Antriebsfunktionalität entfernt wird - ein Kontaktschalter ist kein Antrieb.

**Comment by thkl** [comment]
Für den HmIP-SWDO (also der SHUTTER_CONTACT Kanal) sollte doch auch der normale HomeMaticContactSensorAccessory auswählbar sein ?

**Comment by detLAN** [comment]
Wenn ich HomeMaticContactSensorAccessory  nehme, dann erscheint das Gerät, sondern wird lediglich unter Sensoren geführt. Bedeutet ich kann nicht alle Geräte in der Übersicht auf einmal sehen. Oder ist dies vielleicht von Apple so gewollt?

**Comment by thkl** [comment]
Ich glaube, das liegt an der Home App.  In Eve zb sind die Geräte einzeln geführt. Ggf kann man das irgendwo einstellen. Aber so genau kenne ich die Home App auch nicht.

**Comment by detLAN** [comment]
Okay, vielen Dank. Ich mach dann hier zu.
