### ISSUE TITLE
Bridge wird nicht mehr gefunden nach Löschen

### ISSUE THREAD

**Issue by chriskroees** [thkl/hap-homematic#253]
Bridge wurde zu HomeKit hinzugefügt und wieder gelöscht. Nach dem Löschen wird diese nicht zur erneuten Verbindung angezeigt.

Sind irgendwelche Probleme in diesem Zusammenhang bekannt? Es sind alle Ports auf raspberrymatic freigegeben und auch neue Instanzen werden nicht gefunden. Das Add-On wurde aus der CCU gelöscht und neu installiert. Dies brachte keine Besserung.

Bin über jede Idee dankbar.

**Comment by thkl** [comment]
bitte mal in /etc/config/addons/hap-homematic den persist Ordner löschen, den hap daemon via WebUI neu starten und schauen, ob HomeKit die Instanzen wieder findet. Wichtig sollten mehrere Instanzen verbunden sein, gehen damit alle Verknüpfungen zu HomeKit flöten.
