### ISSUE TITLE
Frage zum Thermostat: HM-CC-TC

### ISSUE THREAD

**Issue by hbednarek** [thkl/hap-homematic#254]
Hallo,
Wenn ich das Thermostat HM-CC-TC in das Programm eintrage erhalte ich: **Dieser Service erstellt einen Temperatur Sensor in HomeKit**. Bei HomeKit findet sich aber der Sensor im Bereich **Neue Automation** nicht wieder. Die Temperatur ist nur im jeweiligen Zimmer als Info zu sehen. Mache ich da etwas falsch? Gibt es einen anderen Weg um die Temperatur zur Steuerung zu verwenden? Ist das etwas was noch nicht implementiert ist?

Hermann Bednarek

**Comment by thkl** [comment]
Bitte nicht den Channel 1 (WEATHER) auswählen. Dieser Kanal ist nur lesend.
Wenn Channel 2 (CLIMATECONTROL_REGULATOR) ausgewählt wird, kann man dann HomeMaticThermostatAccessory nutzen. Hier kann die Temperatur eingestellt werden.

**Comment by hbednarek** [comment]
Vielen Dank, das scheint schon einmal die "halbe Miete“ zu sein. Jetzt wird der Thermostat in der Home-Kit App als Gerät dargestellt. Mit Drehregler usw. 
Leider kann ich aber bei meinem Schaltaktor keine Automation damit verknüpfen, weil der Thermostat dort weiterhin nicht angezeigt wird. Gibt es da eine Idee?
