### ISSUE TITLE
Neue RaspberryMatic 3.53.34.20201121 Version Umstellung auf 64Bit - HAP kompatibel?

### ISSUE THREAD

**Issue by AdlerCentauri** [thkl/hap-homematic#255]
Moin @thkl , @jens-maus hat eine neue Version von RaspberryMatic veröffnelticht "[3.53.34.20201121](https://github.com/jens-maus/RaspberryMatic/releases/tag/3.53.34.20201121)" Die Version ist auf 64bit umgestellt worden. Ist das Hap Addon damit kompatibel?

"IMPORTANT NOTICE:
Please note that this is a MAJOR release which incorporates changes on hardware support level. So please make sure to read the ChangeLog (see Operating system changes) before updating and that you understand the implications of the incorporated switch to a 64bit OS, especially if you are using a RaspberryPi2 as your current hardware platform for RaspberryMatic."

Es heißt zwar
"While a 32bit binary compatibility layer had been integrated alongside the 64bit support and the standard list of third-party CCU Addon have been tested for compatibility, some third-party software or CCU Addon might run into issues with the new 64bit environment or should be ported/recompiled as a full 64bit application."

Aber es wird auch darauf hingeweisen, dass die Addons 64 kompatibel gemacht werden sollten. Wie verhält sich das mit HAP?

**Comment by roe1974** [comment]
habe update (nachdem thomas es vorher probiert hat 😜) der RM vor ca 1h gemacht ... HAP läuft wieder ganz normal
lg richard

**Comment by meistermolli** [comment]
Danke für die Info ;-)
