### ISSUE TITLE
"HmIP-DRBLI4" zeigt alle Rolläden als geschlossen, sind aber offen

### ISSUE THREAD

**Issue by kallejones** [thkl/hap-homematic#256]
Ich habe alle Geräte erfolgreich mit den verschiedenen Instanzen im Homekit angelegt, leider werden alle Rolläden als geschlossen makiert und lassen sich nicht steuern.
Steuerung per WebUI und Taster klappt, nur leider nicht im Homekit.

Vielen Dank für die Hilfe

[HmIP-DRBLI4.txt](https://github.com/thkl/hap-homematic/files/5585427/HmIP-DRBLI4.txt)

**Comment by deilmann** [comment]
Hallo,
Ich habe das selbe Problem gibt es eine Lösung ?
Gruß Thomas

**Comment by thkl** [comment]
Ah ich sehe gerade in HomeMaticBlindIPAccessory unterstütze ich zwar den Channel BLIND_VIRTUAL_RECEIVER aber lege ihn für das Gerät auf Channel 4 fest. Bei dem HmIP-DRBLI4 gibts aber auf C4 diesen Typen nicht.

Das müsste mit der Änderung aus obigem Commit funktionieren.

Zum Testen könnte man das File hier https://github.com/thkl/hap-homematic/blob/master/lib/services/HomeMaticBlindIPAccessory.js downloaden und nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services kopieren .. Hap neu starten und schauen ob es geht

**Comment by deilmann** [comment]
Super hat geklappt funktioniert tadellos 👍🏻😉

**Comment by thkl** [comment]
Dann mach ich den hier mal zu .. offiziell wandert das dann in die nächste Version
