### ISSUE TITLE
Virtueller Schalter gibt kein Feedback

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#257]
Hallo zusammen,

ich habe in meiner CCU3 einen virtuellen Schalter angelegt und diesen mittels Direkt-Verknüpfung an die integrierte Beleuchtung unseres Garagentorantriebs gehangen. Das ganze sieht so aus:
![B7D5BC2F-F2EF-4F8C-95F6-1427B24C6313](https://user-images.githubusercontent.com/72799068/100093229-8696e300-2e57-11eb-83d8-4fc18f7e6c1a.png)

Dann habe ich in HAP mir diesen virtuellen Schalter geschnappt und meiner Home-App hinzugefügt.
![40ED72A8-6CFB-4D61-A993-40A4CEEDB102](https://user-images.githubusercontent.com/72799068/100093415-c8278e00-2e57-11eb-93cf-9d141017657b.png)
![6DAAD2E1-D8CE-4790-B776-22024DE22075](https://user-images.githubusercontent.com/72799068/100093435-cd84d880-2e57-11eb-8119-6cea0773b5e5.png)

Das schöne ist: Wenn ich in HomeKit den Schalter betätige, wird das Licht an, bzw. Ausgeschaltet. Auch Siri klappt wunderbar. Allerdings wird in HomeKit nicht der aktuelle Status überführt.

Als Beispiel:
1. Licht ist aus
2. Schalter zum Einschalten wird gedrückt
3. Licht geht an
4. In der Home-App springt der Schalter kurz auf ein, um dann wieder auf aus
5. In der CCU wird der Status korrekt angezeigt

Im Grunde ist es so, dass wenn ich den Schalter auslöse, einfach nur das Gegenteil mit dem Licht passiert. Ist es an, wird es ausgeschaltet und umgekehrt. Die Anzeige in der Home-App ist aber immer „aus“.

Weiss jemand Rat?

Vielen Dank und viele Grüße.

**Comment by roe1974** [comment]
Die virtuellen Taster (nicht Schalter) - egal ob HM oder HMiP - sind doch Taster (also SHORT_ON bzw. LONG_ON) ... d.h. der springt ja, wie für einen Taster üblich, gleich wieder auf "OFF" .... der müsste auch in der CCU gleich wieder auf "OFF" sein ... oder ?

lg Richard

**Comment by gerd2005** [comment]
Nein, der Status bleibt hier.

![777F8985-EAE7-4FCC-A06D-1D311CD83139](https://user-images.githubusercontent.com/72799068/100097837-6833e600-2e5d-11eb-9204-feac7edba6d0.png)
![3F6E58B3-92B9-4623-B06F-BE0FA72BC27A](https://user-images.githubusercontent.com/72799068/100097847-6bc76d00-2e5d-11eb-85a9-051b43e16057.png)

**Comment by JensBonse** [comment]
Du solltest das Licht Garage in HomeKit einbinden damit du den Status hast.
Der Virtuelle Schalter ist ja nur ein Toggle und geht sofort wieder aus.
Der Virtuelle Schalter hat in der CCU gar keinen Status an oder aus.

**Comment by gerd2005** [comment]
Achso... Klar, logisch. Jetzt ist der Groschen gefallen. Aber dann sind wir wieder bei dem Problem, dass das PlugIn leider nur einen Kanal je Gerät zu lässt.

**Comment by JensBonse** [comment]
Dann Nimm eine Boolean Variable und spiegel auf die den Zustand des Lichts.

**Comment by gerd2005** [comment]
Mhh ok... An der Stelle bin ich wieder raus. Boolean-Variable muss ich später googeln und schauen wie das funktioniert.

**Comment by JensBonse** [comment]
Eine Variable in HM anlegen mit dem Typ Logik (Wahr / Falsch).
In der Wiki dann nach Variable Update Trigger schauen.

**Comment by JensBonse** [comment]
Oder @thkl baut den Service für den HmIP-MOD-HO so um, dass automatisch auch ein Licht mit in HomeKit angelegt wird.

**Comment by gerd2005** [comment]
thkl hat bzgl. Mal soetwas hier geschrieben: > Ich hab es glaube ich schon irgendwo anders hier geschrieben; jeder Kanal eines CCU Gerätes kann genau auf ein HomeKit Gerät gemappt werden.<

Da das Garagentor (auf & zu) mit HAP bereits verbunden ist, ist das Licht somit raus.

**Comment by JensBonse** [comment]
Das stimmt, dass es er nur einmal Mappen kann. Aber bei dem einem Mal könnte er daraus zwei HomeKit Geräte erzeugen denke ich.
Er müsste also beim Garagentor um einen Switch Service erweitern. Dann wäre alles in einem Gerät.
Wie bei den Thermostaten z.B. wo Temperatur und Luftfeuchtigkeit unterschiedliche Datenpunkte sind.

Zumindest habe ich es so verstanden. Habe zu meinem Bedauern, seinen Code nie wirklich analysiert.

**Comment by gerd2005** [comment]
Ja das wäre natürlich prima.
@thkl Könntest du bei dem Gerät HmIP-MOD-HO noch bitte den Kanal 2 für das Licht als zweites Gerät hinzufügen, so, wie es @JensBonse beschrieben hat? Wäre super, wenn das gehen würde.
Herzlichen Dank!

**Comment by thkl** [comment]
Kurz, damit ich das verstehe... HmIP-MOD-HO hat noch einen Datenpunk für ein Garagenlicht ?

**Comment by gerd2005** [comment]
Ja, genau. Wirst du aus diesem Screenshot schlau? Oder benötigst du noch weitere Infos?
![5FBAF245-736E-4FBC-8DFC-1BEA3664B7C2](https://user-images.githubusercontent.com/72799068/100116301-ddaab100-2e73-11eb-8d64-41620f79eacc.png)

Hier das Gerät auf der Homematic Seite:
https://www.homematic-ip.com/produkte/detail/homematic-ip-modul-fuer-hoermann-antriebe.html

**Comment by thkl** [comment]
Ok ich hab in der Doku nach geschaut .. es gibt einen Kanal 3 SIMPLE_SWITCH_RECEIVER .. den kann ich einfach einem normalen Schalter zuordnen .. dann kann man sich den in HomeKit als Licht mit allen Spässchen die das Licht zu kann einbinden. Das ist kein Akt

**Comment by gerd2005** [comment]
Mega! Danke

**Comment by thkl** [comment]
Das ist dann natürlich ein 2. Gerät .. aber das kann ja dann in den Raum "Garage" oder so , das Siri dann "Schalte das Licht in der Garage ein" kapieren dürfte ...
