### ISSUE TITLE
Keine veröffentlichten Geräte

### ISSUE THREAD

**Issue by mludi** [thkl/hap-homematic#258]
Hi,
erst mal vielen vielen Dank, das ist richtig klasse!

Zum Problem: ich konnte 3 Instanzen ohne Probleme hinzufügen, das Wohnzimmer zickt irgendwie etwas rum. Sind alle gleich konfiguriert in Raspberrymatic.

Ich musste die Instanz Wohnzimmer manuell hinzufügen, ebenso die Geräte.

Anbei mal 2 Screenshots wie es aktuell aussieht. Leider sind so auch keine Geräte veröffentlich und ich in der Home App natürlich nicht :-)

Danke!

<img width="1111" alt="Bildschirmfoto 2020-11-24 um 15 32 47" src="https://user-images.githubusercontent.com/2865361/100108592-3aee3480-2e6b-11eb-888f-7e1f3bca4b06.png">
<img width="607" alt="Bildschirmfoto 2020-11-24 um 15 39 10" src="https://user-images.githubusercontent.com/2865361/100108599-3c1f6180-2e6b-11eb-82d9-32820060efb8.png">

**Comment by sailor79** [comment]
Hi @mludi,

hast Du auch den Haken zur Veröffentlichung einmalig für den Raum gesetzt?
siehe auch [hier](https://github.com/thkl/hap-homematic/wiki/devices#publishing-settings)

**Comment by mludi** [comment]
Ursprünglich schon. Scheinbar hab ich dann vergessen ihn wieder zu setzen, nachdem es Probleme gab. Jetzt tut es jedenfalls. Vielen Dank!
