### ISSUE TITLE
Bewegungsmelder HmIP-SMI, HmIP-SMI55 und HmIP-SMO

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#259]
Bei den Homematic IP Bewegungsmelder gibt es die Funktion "Unterdrückung der Bewegungserkennung" auf Kanal 2 (HmIP-SMI55 und HmIP-SMO) bzw. Kanal 4 (HmIP-SMI55).
Schön wäre, wenn es eine Möglichkeit geben würde, mit der man die Bewegungserkennung ein- bzw. ausschalten könnte. Nützlich wenn z.B. der Hund im Flur allein zu Hause ist.

[HmIP-SMI.json.txt](https://github.com/thkl/hap-homematic/files/5591845/HmIP-SMI.json.txt)
[HmIP-SMI55.json.txt](https://github.com/thkl/hap-homematic/files/5591849/HmIP-SMI55.json.txt)
[HmIP-SMO.json.txt](https://github.com/thkl/hap-homematic/files/5591847/HmIP-SMO.json.txt)

**Comment by thkl** [comment]
sowas hier ? 

![Bildschirmfoto 2020-11-24 um 21 11 06](https://user-images.githubusercontent.com/884355/100146195-d1394f00-2e99-11eb-8571-00cc03f0a959.png)

Leider ist das Problem, die Home App kennt diese Switch Erweiterung nicht im Bewegungsmelder und damit wird sie nicht dargestellt. Elgato Eve kann das  ...

**Comment by detLAN** [comment]
Ich finde die Home App eigentlich gar nicht so schlecht, zumal es diese auch auf dem Mac gibt. Würde mich freuen, wenn Du die Geräte "Home Kompatibel" machst.

**Comment by thkl** [comment]
Man könnte diese Option an die globale Einstellung der Eve History Koppeln.  Man entscheidet sich ja quasi dauerhaft für eine Client App. Ich würde diese Option dann umbenennen auf "Apple Home kompatibel" (mit passender Erläuterungen was das heißt) und daran halten sich dann alle Geräte. 

Dann muss man das nicht überall einzeln aktivieren. 

🤔

**Comment by detLAN** [comment]
Die Idee ist super. Es gibt auch noch weitere Geräte, wie z.B. die Wetterstation, wo man sich entscheiden muss, welche App man nutzen möchte. Eine globale Einstellung würde dies durchaus vereinfachen.

**Comment by detLAN** [comment]
Wo finde ich die globale Einstellung?

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/103356684-b7e77c00-4ab1-11eb-8e88-fdbbeaefa355.png)

![image](https://user-images.githubusercontent.com/884355/103356705-c897f200-4ab1-11eb-8a6e-8775a02cbd41.png)


ggf einmal einen kompletten Browserreload damit all das gecachte überschrieben wird

**Comment by detLAN** [comment]
Aktiviere ich die Home App Kompatibilität, braucht es eine weile, bis sich die Aussenanlage aktualisiert hat:
![Bild1](https://user-images.githubusercontent.com/64675966/103357951-b66b8300-4ab4-11eb-801e-4b8b43ea563f.jpg)

Danach geben dann nur noch HmIP-SWO-PR, HmIP-STHO und HmIP-SLO keine Antwort.
![Bild2](https://user-images.githubusercontent.com/64675966/103357989-cf743400-4ab4-11eb-8f20-69bbd953f672.jpg)

Die Kachel für den Bewegungsmelder Schalter wird als Ausgeschaltet dargestellt, obwohl dieser Eingeschaltet ist. Auch lässt die Kachel sich nicht direkt schalten sondern erfordert das öffnen des Dialogs.

**Comment by detLAN** [comment]
Jetzt habe ich  Home App Kompatibilität erst einmal wieder deaktiviert. Für das Aktivieren und Deaktivieren, sollte vielleicht noch der Hinweis kommen, dass der HAP Service neu startet und man einen Browser Refresh durchführen sollte.

Nach dem Deaktivieren und dem Refresh erhalte ich:
![Bild3](https://user-images.githubusercontent.com/64675966/103358891-06e3e000-4ab7-11eb-9ed1-593a882027c3.jpg)
Der letzte Satz endet ohne Punkt und zb sollte z.B. geschrieben sein.

Ich habe mal auf weiter geklickt:
![Bild4](https://user-images.githubusercontent.com/64675966/103358974-35fa5180-4ab7-11eb-819e-2fb64ae3218f.jpg)
Der Anfang ist nicht übersetzt. Habe auch hier auf weiter geklickt, der Dialog läuft sich Tod. Nach Refresh musste ich dann die Veröffentlichung bestätigen, damit die vorhandenen Instanzen nicht rot sind.
