### ISSUE TITLE
Garagentor Zustände 

### ISSUE THREAD

**Issue by fighterzg6** [thkl/hap-homematic#26]
also irgend wie ist da noch ein Würmchen drin.
wenn ich die CCU3 oder den hap-homematic neu starte erkennt er nicht ob das tor auf oder zu ist.
bzw steht dann dort wird geöffnet und nix passiert!

**Comment by thkl** [comment]
Ok Tor schau ich mir an. Ggf muss ich beim Launch einfach alle Werte hart aus der ccu abfragen.

**Comment by thkl** [comment]
Ggf hilft das hier weiter :


https://github.com/thkl/hap-homematic/issues/45
