### ISSUE TITLE
Instanzen bleiben grau (HmIP-PS und HmIP-PSM)

### ISSUE THREAD

**Issue by RealWinny** [thkl/hap-homematic#260]
Hallo, ich habe mir heute HAP-Homematic installiert und erstmal voller Optimismus alle meine Räume angelegt und einige Homematic-Geräte veröffentlicht. Das sollten so an die 15 Räume und vielleicht 20-30 Geräte sein. Irgendwann hat sich dann die CCU3 aufgehängt und auf der HAP-Benutzeroberfläche war kein einziger Raum bzw. keine Bridge und kein einziges Gerät mehr da. Klasse. :-( Geholfen hat nur ein vollständiges De- und wieder Installieren von HAP-Homematik.

Wir kommen gleich zum eigentlichen Problem. Aber vorher noch ein paar Randinformationen. Vielleicht helfen die weiter. Bei meinen zwei Schaltdosen (HmIP-PS) taucht seit dem Crash die Servicemeldung "Konfigurationsdaten stehen zur Übertragung an" auf. Ich habe alles mögliche probiert. Konfigurationen geändert, Schaltbefehle gesendet, usw. Aber die einzige Chance war die Teile abzulernen und neu in die CCU einzubinden. Könnte der Fehler darin bestehen, dass ich in HAP-Homematic beim ersten Schuss vielleicht nicht den Kanal 3, sondern den Kanal 1 (Taster) ausgewählt hatte? 

Also weiter mit dem nächsten Versuch. Ich habe nun zunächst drei Räume/Bridges und 4 Geräte angelegt, zwei Temperatursensoren, eine Schaltdose (HmIP-PS) und eine zwischenzeitlich neu hinzugekommene Schalt- und Messdose (HmIP-PSM). Die Temperatursensoren funktionieren einwandfrei. Die beiden Dosen werden in der Weboberfläche jedoch in der Spalte Instanz beide grau dargestellt und tauchen in der Home-App am iPhone nicht auf. Was bedeutet die graue Darstellung und was kann ich tun? 

![Instanz grau](https://user-images.githubusercontent.com/28679778/100272781-00b09000-2f5c-11eb-9a2f-ed8b81d75642.PNG)

Hier beispielhaft die Konfig der Messdose:

![Beispiel PSM](https://user-images.githubusercontent.com/28679778/100272931-3e151d80-2f5c-11eb-9425-22a0457278d9.PNG)

**Comment by thkl** [comment]
Links im Menü gibt es eine Option HomeKit Instanzen. Dort bei Einstellungen mal bitte prüfen ob das Häkchen bei Veröffentlichen mit Geräten gesetzt ist.

**Comment by RealWinny** [comment]
> Links im Menü gibt es eine Option HomeKit Instanzen. Dort bei Einstellungen mal bitte prüfen ob das Häkchen bei Veröffentlichen mit Geräten gesetzt ist.

Nein, war es nicht. Jetzt sind die Geräte in der Instanzenspalte grün. Schaut gut aus, danke! Ich werde nun weiter testen. Thanks!
