### ISSUE TITLE
Garagentorsteuerung meldet weder offen noch zu

### ISSUE THREAD

**Issue by Schazo** [thkl/hap-homematic#261]
Moin,

habe über "Besondere Geräte" nun versucht meine Hörmann Promatic 3 per HmIP-PCBS mithilfe von zwei HMIP-SWDO in Homekit einzubinden. Funktioniert so weit auch ganz gut, Tor lässt sich öffnen und schließen.

Allerdings wird der Zustand des öffnens und schließens in Homekit nicht beendet.

Dort steht immer "Wird geöffnet..." bzw. "Wird geschlossen..."

Die Sensoren registrieren wenn man in der CCu3 direkt guckt, dass das Tor offen oder zu ist.

Anbei mal ein Auszug meiner Konfiguration.

![Torsteuerung](https://user-images.githubusercontent.com/71873517/100331103-0d6ecb80-2fd0-11eb-9f34-d14f846b9d4f.jpg)

Kann mir da jemand weiter helfen?

Gruß

**Comment by thkl** [comment]
Probier mal testweise den Offen Sensor rauszuwerfen

**Comment by Schazo** [comment]
Klappt tatsächlich, mit einer kleinen Einschränkung.

Wenn das Tor geschlossen ist, zeigt er mir offen an und umgekehrt.

Habe den Schaltzustand von true auf false gesetzt, jedoch keine Besserung :(

**Comment by thkl** [comment]
und die Adressen der Sensoren tauschen hilft auch nicht ? Also den ehemaligen Offen Sensor als Geschlossen Sensor eintragen ?

**Comment by Schazo** [comment]
Leider nein..

**Comment by thkl** [comment]
Ahhh ich sehe gerade das sind ja HmIP Geräte die liefern nicht true / false als STATE sondern 1/0

Also mal bitte testen Status des Schließen Sensors auf 1 statt true

**Comment by Schazo** [comment]
Super, das hat geklappt! Vielen Dank! :)
