### ISSUE TITLE
Hilfe bei Doorbell Service

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#263]
Hallo, 
kann mir hier vielleicht jemand Helfen?

Habe einen HomeKit Virtuellen Schalter angelegt als Homematic Doorbell Accessory .

Wenn ich diesen in der CCU auslöse dann funktioniert das auch und ich bekomme direkt eine Push in der Home App.

Ich kann die Doorbell in Home aber nicht in eine Szene oder Automation auswählen?
Würde diesen gerne nutzen um mir eine Kamera Anzeigen zu lassen oder per Airplay einen Klingelton ab zu spielen.
Vielleicht habt ihr ja einen Tipp?

EDIT1:
>Ich habe in der CCU nun einen zweiten Virtuellen Taster angelegt "Klingel Hilfstaster"
>Eine Automation in HomeKit reagiert darauf, wenn dieser "Klingel Hilfstaster" auslöst und Spielt dann einen AirPlay Ton ab.

Test:
>Nun müsste in der CCU ein Programm aufgesetzt werden, das bei auslösen des "Klingel Hilfstaster", der Virtuelle Taster "Klingel" ausgelöst wird und die Push sendet.

Noch Offen:
>Ich würde nun noch gerne das Video Bild der Briefkasten Kamera Pushen - muss ich mir dafür noch einen Fake Bewegungsmelder bauen?

Danke und Gruß 
meistermolli

**Comment by gerd2005** [comment]
Hi, Zwischenfrage: welche Geräte sind denn im Spiel bei deinem Vorhaben?

**Comment by meistermolli** [comment]
Hi,
Aktuell
Raspberrymatic CCU3
Hue Smart Button
Sonos one
Eufy 2k - die kann auch ein Bild bei Bewegung pushen. 

Leider öffnet ein Druck auf die pushmeldung des Homematic doorbel Service die Einstellungen des „HomeKit“ Gerätes und nicht den Raum.

**Comment by JensBonse** [comment]
Wenn du die Briefkastenkamera und die Klingel in den gleichen Raum packst, macht HomeKit das mit dem Bild in der Push automatisch. Zumindest war das meines Wissens nach so früher mal.

**Comment by meistermolli** [comment]
Hi @JensBonse,

ich habe einen Raum "Haustür" im Homekit.

Geräte:
HKSV Kamera - Eufy 2k

Homekit Doorbell Service so gelöst:
> Hue Smart Button löst aus:
> Homematic Virtueller Taster "Klingel Hilfstaster" kurz aktiv
> 2. Homematic Homematic Virtueller Taster "Klingel" als Homekit Doorbell Service in Hap Homematic eingebunden
             + (Programm -  Wenn "Klingel Hilfstaster" auslöst, dann löst "Klingel" aus)

So kommt direkt die Push Benachrichtigung + Klingeln auf Airplay Gerät möglich.
Drücke ich auf die Push Nachricht, komme ich in die Homekit Einstellungen des Homekit Doorbell Service, leider nicht in den Raum Haustür, in dem die Kamera ist.

Ich habe es noch nicht hin bekommen. Und weis nicht, wie ich einen Fake Bewegungsmelder für diese Aktion auswählen kann.

Gruß meistermolli

**Comment by JensBonse** [comment]
Ich denke mal bei der Apple Home App kann man da nichts weiter konfigurieren.
Und das spielt sich alles in HomeKit ab, von daher kann man da auch in HAP nichts ändern.

Ist denn der Doorbell Service also die Klingel im gleichen Raum Haustüre?

**Comment by meistermolli** [comment]
![90CE51C6-243B-4A85-A202-9976172186D3](https://user-images.githubusercontent.com/55836556/100751150-44d1e380-33e7-11eb-8c62-7eb8f8bb269d.jpeg)

Ja genau. Kann sein, dass man es nicht in HAP lösen kann. Aber vielleicht hat ja jemand anderes einen Tipp. So baut man sich dann eine HomeKit Video Türklingel für 40€ selber nach ;). In meinem Fall mit dem Vordach ist es auch nicht schlimm, dass die Kamera keine Outdoor Kamera ist. Die kommt ohnehin versiegelt und eingebaut in den Briefkasten. 

Gruß

**Comment by meistermolli** [comment]
![Uploading 3F874E5D-B387-4441-B4AA-AD5B9BA95662.jpeg…]()

**Comment by meistermolli** [comment]
![Uploading 46E0A57F-A3CC-4FC2-9E58-6B9B0FBDF95A.jpeg…]()

**Comment by meistermolli** [comment]
![8854B70A-AF37-4792-A1EB-98148F5D992B](https://user-images.githubusercontent.com/55836556/100752150-8616c300-33e8-11eb-8633-b8edaf0734a1.jpeg)
![B0360C8E-8C98-4FA2-951B-31358F1E2EDA](https://user-images.githubusercontent.com/55836556/100752158-8911b380-33e8-11eb-83ee-17dd38825ac7.jpeg)

So läuft das ab... drückt man auf die Push, kommt man in die Geräte Einstellung

**Comment by JensBonse** [comment]
Also ich nutze auch den DoorBell Service, aber nicht über HAP, sondern über HomeBridge und habe da dann auch die Kamera eingebunden. Der DoorBell Service von HAP kann das mit der Kamera nicht. Denke das wird Thomas auch nicht implementieren, da es viel zu viele Kameras etc gibt. Da macht HomeBridge dann eher Sinn.
Kurz gesagt, ich habe keine Ahnung ob man das für deine Zwecke irgendwie elegant lösen kann.

**Comment by meistermolli** [comment]
Danke @JensBonse hast du da mal einen Querverweis wie du das dort gelöst hast? gerne auch per PN ..

@thkl, denkst du dass man das in HAP implementieren könnte?
Falls das zu viele Umstände macht, würde ich das mal in Homebridge versuchen umzusetzen.

Ansonsten bevorzuge ich aber HAP, da viel einfacher intuitiver und verständlicher!

Gruß meistemolli

**Comment by thkl** [comment]
Es gibt einen VideoDoorBell .. die setzt aber ffmpeg auf der CCU voraus.
Auf meiner Test RM (Pi4) läuft das auch

![image](https://user-images.githubusercontent.com/884355/100794132-736ab100-341d-11eb-87bc-1e335657ba71.png)

Das möchte ich aber hier keinesfalls supporten, da ich sonst nichts anderes mehr mache.
Die RTSP Url ist die gleiche wie in der HomeBridge Version und das Static Image auch.

**Comment by meistermolli** [comment]
Vielen Dank, das versuche ich mal. Die eufy können auch rtsp. Dann versuche ich es mal über diesen Weg. Muss aber ggf. die Kamera dann einmal in ffmpeg und einmal als HomeKit Secure Video anlegen (da ich die Personen Erkennung noch nutzen möchte) vielen Dank für deinen tip!

**Comment by roe1974** [comment]
@JensBonse .... wie hast du das gelöst mit Türklingel/Cam/Push etc.... könntest Du hier Deinen Lösungsansatz kurz beschreiben ;-)
DANKE, lg Richard

**Comment by JensBonse** [comment]
@roe1974 Also ich habe die Klingel von DoorBird. Da gibt es für HomeBridge ein eigenes PlugIn zu.
Aber mit HAP sollte es ja auch gehen. Hast du die RTSP URL und die Still Image URL?
Ich hab zusätzlich noch einen HM Sensor, der mir in HomeMatic anzeigt, dass es geklingelt hat.
Also wenn du auch ein HomeMatic Gerät hast, was das drücken der Klingel sofort erkennt, dann solltest du doch alles zusammen haben.
Woran scheitert es denn bei dir?

**Comment by roe1974** [comment]
Ich habe einen "Video-Doorbell" mit dem homebridge videodoorbell Plug-in laufen.
Geht eigentlich perfekt, nur wollte ich jetzt den HomePod dazu aktivierren.....geht nicht.
Und ja.... erkenne das klinglen auch mit einen HM Sensor....
Ich habe RTSP Stream, Standbild und HM Sensor der Klingeln erkennt..... wie sollte ich das anders umsetzten ?
lg RIchard

**Comment by JensBonse** [comment]
@roe1974 Also die HomePods sind bei mir eigentlich automatisch dazu gekommen. Da musste ich nichts extra einstellen. Sobald du von HomeKit die Push bekommst, dass es geklingelt hat, sollten die HomePods auch ding dong machen.
Das gibt es in HomeKit eine Einstellung in den HomePods zu, dass auch Klingeln sollen. Ganz unten über 'HomePod neu starten' habe ich einen Schalter 'Auf HomePod klingeln'.

**Comment by roe1974** [comment]
@JensBonse  ... So einen Schalter habe ich nicht beim HomePod Mini .. ganz unten ist "Gerät entfernen" ... und darüber sind Infos zu Hersteller, SN, Modell, WLAN und Version (14.4 seit gestern)

**Comment by JensBonse** [comment]
@roe1974 Also ich habe zwei von den großen HomePods als Stereo. Hab die auch gerade mal auf 14.4 geupdated. Waren noch auf 14.3. Schalter ist immer noch da...
Denke da hat dein HomeKit entweder die Klingel nicht richtig 'drin' oder den HomePod mini.
Versuch mal die Klingel aus HomeKit zu entfernen und neu zu verbinden.

**Comment by gerd2005** [comment]
Ich habe auch einen HomePod mini. Bei mir sieht das aber auch anders aus als bei @JensBonse.

![5FDB0AF8-7F7E-49DC-96D1-E4DCDE1CE916](https://user-images.githubusercontent.com/72799068/105968677-acbf4600-6087-11eb-9d6c-d6428132ce49.png)

**Comment by JensBonse** [comment]
Bei Stereo Paar klingeln beide. Da habe ich auch keine Option gefunden, das nur auf einem von den beiden klingeln zu lassen.

**Comment by gerd2005** [comment]
Ok, war ja nur eine Idee. Hat denn den iOS auch die aktuellste Version installiert?

**Comment by roe1974** [comment]
@gerd2005 ... sieht so aus wie bei mir ... bei Dir ist auch kein Schalter für das klingeln ... oder ?
Bei mir ist alles auf iOS 14.4

**Comment by meistermolli** [comment]
Also ich habe bevor ich das Update gemacht haben geschaut.

Habe einen Doorbell Service und mit dem Klingelt auch der Homepod.

Aber diesen Schalter habe ich nicht!

Weder in Version 14.3 gehabt und nach update auf 14.4 auch nicht vorhanden?
