### ISSUE TITLE
Version 0.0.56 findet keine neuen Geräte oder Programme

### ISSUE THREAD

**Issue by Icke-NOH** [thkl/hap-homematic#264]
Moin habe die aktuelle RaspberryMatic 3.53.34.20201121 mit HAP 0.0.56 am laufen und heute zwei Steckdosen HMIP-PS hinzugefügt und auch Programm erstellt aber HAP findet weder die dosen noch das Programm. Neustart des HAP service und der CCU3 hat keine Veränderung gebracht, jemand noch eine Idee?

**Comment by thkl** [comment]
WebUi Menü Internes / Cache neu laden ....
