### ISSUE TITLE
Neu angemeldete Steckdosen werden nicht in HAP angezeigt

### ISSUE THREAD

**Issue by DominikMie** [thkl/hap-homematic#265]
Hallo!

Dieses Problem ist bestimmt schon mal aufgetreten, aber ich habe kein passendes Thema gefunden: 

Nachdem die Ersteinrichtung von HAP reibungslos geklappt hat, habe ich heute zwei neue HMIP-Steckdosen an der CCU3 angelernt. Alle Kanäle sind beschriftet und vorhandenen Räumen und Gewerken zugeordnet. Dennoch werden beide Steckdosen nicht in HAP als neue Geräte gefunden. 

Ich habe inzwischen die zugehörige Bridge deaktiviert und neu aktiviert, das HAP-Plugin mehrfach neu gestartet und sogar die komplette CCU3 neu gestartet. Ohne Erfolg. 

Hat jemand einen Tipp?

Vielen Dank im Voraus!

**Comment by roe1974** [comment]
doch 😊 .... Thema #264 (bereits closed)

WebUi Menü Internes / Cache neu laden ....

**Comment by DominikMie** [comment]
Super! Vielen herzlichen Dank!!
