### ISSUE TITLE
Hersteller, Seriennummer, Modell und Firmware

### ISSUE THREAD

**Issue by Jemeins** [thkl/hap-homematic#266]
Moin,
vorab noch mal vielen Dank für die super Arbeit!
Ich würde es noch besser finden, wenn bei den Geräten die Informationen zu Hersteller, Seriennummer, Modell und Firmware mit den Homematic Geräten übereinstimmt.

**Beispiel:**
Hersteller: eQ-3
Seriennummer: OEQ*******
Modell: HM-LC-BI1PBU-FM
Firmware: 2.11

Mit freundlichen Grüßen

**Comment by thkl** [comment]
Was machen ich kombinierten Geräten ? Ich würde es einfach mal so lassen wie es ist
