### ISSUE TITLE
Unterstützung HM-SwI-3-FM

### ISSUE THREAD

**Issue by rolfsg** [thkl/hap-homematic#267]
Hallo, allererst Mal herzlichen Dank, dieses Plugin ist eine echt tolle Sache, habe die CCU heute von Homebridge rübergezügelt da mit HAP alles viel verständlicher editierter ist.

Leider kann ich diesen Schaltsensor bei den Geräten nicht finden. Der sehr ähnliche HM-ScI-3-FM ist vorhanden.

Freundliche Grüsse, Rolf
[HM-SwI-3-FM.json.zip](https://github.com/thkl/hap-homematic/files/5612549/HM-SwI-3-FM.json.zip)

**Comment by thkl** [comment]
Hmm, das Gerät hat n Kanäle vom Typ SWITCH_INTERFACE und diese liefern einen PRESS Event.
Was macht dieser Sensor ? Wenn extern der angeschlossene Taster gedrückt wird, dann löst der Event aus ?

Ich könnte das in die normalen Key Geräte hinzufügen

**Comment by rolfsg** [comment]
Ja, genau, in meinem Fall ist ein Eingang an den Klingeltaster angeschlossen und löst einen Event aus wenn der Taster gedrückt wird.

**Comment by thkl** [comment]
ok sollte im nächsten release dann funktionieren

**Comment by rolfsg** [comment]
Genial ! Herzlichen Dank
