### ISSUE TITLE
Keymatic verriegelt bei UnlockModus=Open nicht mehr

### ISSUE THREAD

**Issue by jcarax** [thkl/hap-homematic#268]
Hallo,

ich habe festgestellt, dass sich bei dem HomeMaticKeyMaticAccessory und eingestelltem UnlockModus = Open die Tür nicht mehr verriegeln lässt. Ich hatte Folgendes bei UnlockModus = Open erwartet:

1) Tür verriegelt: Drücken auf die Keymatic in Homekit -> entriegeln und öffnen
2) Tür nicht verriegelt: Drücken auf die Keymatic in Homekit -> verriegeln

Tatsächlich wird in Fall 2) bei mir anstatt von verriegeln die Aktion "öffnen" ausgeführt.

Im UnlockModus = Unlock wird in Fall 1) entriegelt, aber nicht geöffnet, was ich erwartet habe. Fall 2) funktioniert wie oben erwartet.

Mache ich etwas falsch?

Viele Grüße und Danke
Ingmar

PS: Homematic CCU3 Firmware 3.53.34, HAP-homematic 0.0.56

**Comment by garysn** [comment]
Du machst nichts falsch, seit meinem Update auf V0.56 habe ich exakt das gleiche Verhalten.

Weiterhin wird nach einem Stromausfall und anschließendem Neustart der CCU3 meine Haustür jetzt automatisch aufgeschlossen und geöffnet. Das ist nicht wirklich gut, wenn ich mal in Urlaub bin und der Strom ausfällt.

**Comment by jcarax** [comment]
Hallo Gerhard,

Danke! Nach einem Stromausfall wird die Tür bei mir nicht geöffnet. 

Ich hatte das Problem allerdings im Zusammenhang mit Programmen, die durch die CCU ja nach jedem Neustart immer ausgeführt werden. Mir hat da ein kleiner [Workaround]( https://smart-wohnen.org/homematic-ausfuehren-von-programmen-bei-einem-neustart-der-ccu-unterbinden/) geholfen.

Viele Grüße
Ingmar

**Comment by thkl** [comment]
Ich kann das jetzt mangels KeyMatic nicht zu 100% nachvollziehen.
Zumindest der Application Flow für das Characteristic.LockTargetState.SECURED Commando (also schließen) hat sich nicht geändert. Hier wird ein STATE = 1 gesendet.

**Comment by garysn** [comment]
> Hallo Gerhard,
> 
> Danke! Nach einem Stromausfall wird die Tür bei mir nicht geöffnet.
> 
> Ich hatte das Problem allerdings im Zusammenhang mit Programmen, die durch die CCU ja nach jedem Neustart immer ausgeführt werden. Mir hat da ein kleiner [Workaround](https://smart-wohnen.org/homematic-ausfuehren-von-programmen-bei-einem-neustart-der-ccu-unterbinden/) geholfen.
> 
> Viele Grüße
> Ingmar

Hallo Ingmar,
vielen Dank für den Tipp mit dem Workaround. Das werde ich die Tage gleich mal ausprobieren ...

Liebe Grüße
Gerhard

**Comment by garysn** [comment]
> Ich kann das jetzt mangels KeyMatic nicht zu 100% nachvollziehen.
> Zumindest der Application Flow für das Characteristic.LockTargetState.SECURED Commando (also schließen) hat sich nicht geändert. Hier wird ein STATE = 1 gesendet.

Hallo Thomas,
ich habe noch mal alles gelöscht und neu aufgesetzt, leider mit dem gleichen Ergebnis.

Kann ich Dir irgendwie weitere Infos zukommen lassen, die Dir helfen könnten das Problem zu lösen?
LOG Dateien, Debug-Ausgaben, .., ggf. Zugriff per TeamViewer auf meinen PC, ...

**Comment by thkl** [comment]
die Keymatic Klasse ist nicht sehr gesprächig, auch wenn das DebugLog an ist.
Wenn müsste ich sie erst mal mit genügend Log Ausgabe versehen

**Comment by thkl** [comment]
so ich habe der Klasse hier https://github.com/thkl/hap-homematic/blob/master/lib/services/HomeMaticKeyMaticAccessory.js mal mehr logging Ausgaben spendiert. Du könntest das File manuell auf die CCU kopieren es müsste nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/ kopiert werden. Und dann ein Restart mit Aktivierung des DebugLogs ...

Dann einmal die Funktion ausführen , Log Download und Debug wieder ausschalten . Das geht alles über die WebUI unter dem Internes Menü

**Comment by garysn** [comment]
> so ich habe der Klasse hier https://github.com/thkl/hap-homematic/blob/master/lib/services/HomeMaticKeyMaticAccessory.js mal mehr logging Ausgaben spendiert. Du könntest das File manuell auf die CCU kopieren es müsste nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/ kopiert werden. Und dann ein Restart mit Aktivierung des DebugLogs ...
> 
> Dann einmal die Funktion ausführen , Log Download und Debug wieder ausschalten . Das geht alles über die WebUI unter dem Internes Menü

Super, ich probiere das gleich mal aus :-)

**Comment by garysn** [comment]
> so ich habe der Klasse hier https://github.com/thkl/hap-homematic/blob/master/lib/services/HomeMaticKeyMaticAccessory.js mal mehr logging Ausgaben spendiert. Du könntest das File manuell auf die CCU kopieren es müsste nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/ kopiert werden. Und dann ein Restart mit Aktivierung des DebugLogs ...
> 
> Dann einmal die Funktion ausführen , Log Download und Debug wieder ausschalten . Das geht alles über die WebUI unter dem Internes Menü



> > so ich habe der Klasse hier https://github.com/thkl/hap-homematic/blob/master/lib/services/HomeMaticKeyMaticAccessory.js mal mehr logging Ausgaben spendiert. Du könntest das File manuell auf die CCU kopieren es müsste nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/ kopiert werden. Und dann ein Restart mit Aktivierung des DebugLogs ...
> > Dann einmal die Funktion ausführen , Log Download und Debug wieder ausschalten . Das geht alles über die WebUI unter dem Internes Menü
> 
> Super, ich probiere das gleich mal aus :-)

Und hier die Resultate:

Die neue Datei an die genannte Stelle kopiert und die Rechte auf 0644 gesetzt.

1. hap-homeatic im Debug-Mode neugestartet
2. Per Siri gesagt: "Haustür schließen"
3. Passende Logdatei dazu: "haustuer schliessen.txt"
[haustuer schließen.txt](https://github.com/thkl/hap-homematic/files/5653977/haustuer.schliessen.txt)
4. Resultat: Siri meckert: "Es tut mir leid, ich konnte Deine Haustür nicht abschließen" UND die Haustür wird GEÖFFNET.

5. Debug ausgeschaltet

6. hap-homeatic im Debug-Mode neugestartet
7. Per Siri gesagt: "Haustür öffnen"
8. Passende Logdatei dazu: "haustuer oeffnen.txt"
[haustuer oeffnen.txt](https://github.com/thkl/hap-homematic/files/5654031/haustuer.oeffnen.txt)
9. Resultat: Siri sagt: "Deine Hausgang-Tür ist aufgeschlossen.

**Comment by thkl** [comment]
Also das haustuer schliessen erzeugt im Log :

```
[Mon Dec 07 2020 17:36:30 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticKeyMaticAccessory] hk set lockTargetState value is 1
[Mon Dec 07 2020 17:36:30 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticKeyMaticAccessory] unlock command
[Mon Dec 07 2020 17:36:30 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticKeyMaticAccessory] unlock mode is open send open command to ccu
[Mon Dec 07 2020 17:36:30 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticKeyMaticAccessory] buildAddress OPEN
[Mon Dec 07 2020 17:36:30 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticKeyMaticAccessory] seems to be a single datapoint
```

Haustür Öffnen
```
[HomeMaticKeyMaticAccessory] OEQ0351419 hk set lockTargetState value is 0
[Mon Dec 07 2020 17:39:13 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticKeyMaticAccessory] lock command received send state 1 to ccu
[Mon Dec 07 2020 17:39:13 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticKeyMaticAccessory] buildAddress STATE
[Mon Dec 07 2020 17:39:13 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticKeyMaticAccessory] seems to be a single datapoint
[Mon Dec 07 2020 17:39:13 GMT+0100 (CET)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject('BidCos-xxx:1.STATE');if (o){o.State(1);}
```

Schaut aus als wären die Kommandos vertauscht

**Comment by garysn** [comment]
Ja, genau so verhält sich das Ganze auch.

Kann ich das in Homekit ändern oder wo kommt die Vertauschung her?

**Comment by thkl** [comment]
Nope ich ändere das in dem Classfile. Aber wieso geht das beim normal Mode ..

**Comment by garysn** [comment]
Soll ich noch mal eine Log File im normal Mode machen ?

**Comment by thkl** [comment]
Habs in dem File https://github.com/thkl/hap-homematic/blob/master/lib/services/HomeMaticKeyMaticAccessory.js getauscht
Könnte ich vielleicht dann aus Internal / Hilfe das Devicefile für dieses Gerät haben, dann kann ich nen Unittest für die Klasse bauen. Wie das geht steht dort

**Comment by garysn** [comment]
Die gute Nachricht: 
Das Öffnen klappt jetzt auf Zuruf einwandfrei !!! Super, vielen Dank !!!!!

Die nicht so gute Nachricht: 
Wenn sich die Tür im aufgeschlossenen Zustand befindet und ich sage zu Siri "Haustür schließen" dann kommt die Fehlermeldung: "Es tut mir leid, ich konnte Deine Haustür nicht abschließen"

Hier mal die zugehörige Log-Datei:
[haustuer schliessen.txt](https://github.com/thkl/hap-homematic/files/5654218/haustuer.schliessen.txt)

**Comment by thkl** [comment]
Wie schaut das in der HomeApp aus .. ist da der Zustand richtig ? Und lässt sich die KM da schließen

**Comment by garysn** [comment]
In der Home App wird die Haustür als "Entsperrt" dargestellt, was ja richtig ist und wenn ich auf die Schaltfläche drücke, piepst die KM zweimal und sonst passiert nichts.

Das entspricht exakt dem Verhalten das auftritt, wenn ich den Vorgang über Siri anwerfe.

**Comment by thkl** [comment]
Nachtrag ich sehe gerade im Log in dem Pfad liegen noch die alten KeyMatic Classfiles. Auch wenn die mit einem suffix umbenannt sind, ist das ne doofe idee weil die auch geladen werden da der Anfang auf ein RegEx matcht.

**Comment by garysn** [comment]
Habe jetzt auch noch mal die beiden Tasten an der KM direkt gedrückt. Wenn ich über die "Abschließen" Taste die Haustür verschließe, dann wird sie in der Home App als "Gesperrt" angezeigt, wenn ich sie über die "Aufschließen" Taste aufschließe, dann wird sie in der Home App als "Entsperrt" dargestellt.

Die Statusanzeige scheint also zu funktionieren.

**Comment by garysn** [comment]
> Nachtrag ich sehe gerade im Log in dem Pfad liegen noch die alten KeyMatic Classfiles. Auch wenn die mit einem suffix umbenannt sind, ist das ne doofe idee weil die auch geladen werden da der Anfang auf ein RegEx matcht.

Okay, ich schmeiß sie mal weg und teste dann nochmal ...

**Comment by thkl** [comment]
Ja, ich vermute mal es liegt daran, das das Gerät sich wie ein Dimmer verhält.
Es wird ein Kommando gesendete und dann kommt erstmal der aktuelle Status von der CCU zurück.
Der ist natürlich noch auf dem alten Stand weil der Motor noch nicht fertig ist. Das werte ich aber schon aus und Sende es an HomeKit zurück.

**Comment by thkl** [comment]
Könnte ich mal bitte ein Logfile für einen kompletten Cycle haben also einmal öffnen und einmal schließen .. gerne auch mit den Tasten von dem Ding. Ich müsste mal wissen was für Events da so kommen. Und bitte so lange warten, bis das Ding komplett geöffnet und geschlossen hat. 
Log kann auch per Mail kommen, Adresse steht im Classfile ganz oben

**Comment by garysn** [comment]
> Könnte ich mal bitte ein Logfile für einen kompletten Cycle haben also einmal öffnen und einmal schließen .. gerne auch mit den Tasten von dem Ding. Ich müsste mal wissen was für Events da so kommen. Und bitte so lange warten, bis das Ding komplett geöffnet und geschlossen hat.
> Log kann auch per Mail kommen, Adresse steht im Classfile ganz oben

Das Löschen der alten Dateien hat keine Verbesserung gebracht. Ich mach Dir jetzt mal ein LOG File für einen komplette Cycle.

Dabei werde ich folgende Schritte durchführen:

1. Haustür in Zustand "nicht verschlossen" versetzen
2. hap-homeatic im Debug-Mode neugestarten
3. An KM die Taste "Verschließen" drücken
4. Warten bis sich nichts mehr bewegt
5. An KM die Taste "Aufschließen" drücken
6. Warten bis sich nichts mehr bewegt
7. LOG Datei sichern und per Mail versenden

**Comment by ChrWi** [comment]
@thkl die Änderung ist in einem aktuellen Build enthalten?

**Comment by thkl** [comment]
Der letzte Commit ist 9Mo her.  Ich sag mal ja :)

Ach und Danke fürs Aufräumen.
