### ISSUE TITLE
HmIP-FSI16 Tastereingang als Bewegungssensor

### ISSUE THREAD

**Issue by Jemeins** [thkl/hap-homematic#269]
Hallo,
besteht die Möglichkeit von dem HmIP-FSI16 den Kanal 1 (Tastereingang) als Bewegungssensor in HomeKit zu integrieren?
Mit freundlichen Grüßen

**Comment by thkl** [comment]
Das ist ein MULTI_MODE_INPUT_TRANSMITTER der liefert PRESS_SHORT und PRESS_LONG Events .. den kann man maximal als Tastenevents wie die anderen KEY Channels einrichten. Aber als IR Sensor ???

**Comment by Jemeins** [comment]
In den CCU Einstellung ist er bei mir als Schalter eingerichtet, und quasi der Input von meinen Bewegungsmeldern.
Das liefert den Vorteil, das ich das Licht ums Haus zusätzlich über Homematic steuern kann.

**Comment by thkl** [comment]
Und warum benutzt du nicht den Aktor Kanal zum Schalten ?

**Comment by Jemeins** [comment]
Der Aktor Kanal wird ja zum schalten genutzt.
Nur eine HomeKit Integration des Inputs als Bewegungsmelder wäre schön, damit man auf Bewegungen in HomeKit reagieren kann.
Beispiel:
Bewegung im Garten -> shortcut in HomeKit der zufällig für eine zufällige Zeit das Licht im Flur einschaltet (als Anwesenheitssimulation)

**Comment by thkl** [comment]
ok

**Comment by gerd2005** [comment]
@Jemeins ich möchte demnächst 2, 3 von den FSI16 verbauen. Ich verstehe noch nicht den UseCase hinter deiner Idee mit dem Bewegungsmeldern. Was genau machst du damit? Vielleicht ist das ja auch etwas für mich :-)

**Comment by Jemeins** [comment]
@gerd2005 ich nutze den FSI16 als Bewegungsmelder Steuerung.

Als Taster Eingang nutze ich die geschalteten 230 von dem Bewegungsmelder (In der CCU als Schalter konfiguriert). An dem Schaltkontakt sind dann die Lampen für die Eingangsbeleuchtung angeschlossen. Das bedeutet immer wenn eine Bewegung erkannt wird, schaltet der Autor und die Lampen gehen an. 

Nur für diese Anwendung wäre der HmIP-FSI16 nicht nötig, jedoch bestand der Wunsch, die Eingangsbeleuchtung per HomeKit permanent einschalten zu können, damit der Besuch sofort den erleuchteten Eingang sieht. 

Die Permanente Einschaltung habe ich über einen Virtuellen Kanal realisiert, mit der Verknüpfungsregel "or".
Ch.: 3 -> Taster Eingang
Ch.: 4 -> HomeKit Switch

Aktuell habe ich zusätzlich NodeRed laufen, damit ich den Status vom Taster Eingang als Bewegungsmelder in HomeKit darstellen kann.
Mit dem HomeKit Bewegungsmelder kann man beispielsweise eine Anwesenheitssimulation in HomeKit Realisieren.

Anbei noch ein Screenshot meiner Homematic Einstellungen und der Anwesenheitssimulation.

![Bedingung](https://user-images.githubusercontent.com/44979117/101656685-459bf280-3a43-11eb-8503-bc16ad4a0178.jpg)
![Kurzbefehl 1](https://user-images.githubusercontent.com/44979117/101656690-4765b600-3a43-11eb-969c-6dc7088e369e.jpg)
<img width="1280" alt="HomeMatic" src="https://user-images.githubusercontent.com/44979117/101656693-47fe4c80-3a43-11eb-8353-dd553669ca89.png">
![Kurzbefehl 2](https://user-images.githubusercontent.com/44979117/101656696-4896e300-3a43-11eb-971f-f174dc87402d.jpg)

**Comment by Jemeins** [comment]
Moin,
ich wollte mal höflich nachfragen wann man den Bewegungsmelder nutzen kann. 
Mit freundlichen Grüßen

**Comment by thkl** [comment]
mit dem nächsten Versionsupdate auf 0.57 wann das kommt, weiss ich noch nicht.
