### ISSUE TITLE
Virtuelle Taster RCV-50 optional als Switch service

### ISSUE THREAD

**Issue by comtel2000** [thkl/hap-homematic#27]
Ist es möglich virtuelle HM/HmIP Taster als KeyAccessory oder Switch Service konfigurierbar zu machen?
Ziel ist, das ich aus Homekit die virtuellen Taster auch bedienen kann (lang,kurzer Tastendruck)

**Comment by thkl** [comment]
Also Quasi anderesrum ein Switch im HomeKit löst einen HM Virtuellen Taster aus ?

**Comment by comtel2000** [comment]
Genau das

**Comment by comtel2000** [comment]
Bei der Einrichtung eine Auswahl des Service Key- oder SwitchAccessory wäre praktisch

**Comment by thkl** [comment]
![Bildschirmfoto 2020-04-30 um 20 26 05](https://user-images.githubusercontent.com/884355/80745894-4a014400-8b21-11ea-89f1-9030f82f03eb.png)


Ok das wird für KEY Channels und VIRTUAL_KEY Channels funktionieren.
Damit können dann alle Tasten von Geräten gedrückt werden.

In HomeKit ist es ein Switch der nach 500ms wieder von ON auf OFF geht

**Comment by comtel2000** [comment]
Perfekt. Ich würde gern unterstützen, aber muss mich in die Materie noch einlesen

**Comment by thkl** [comment]
Ideen, Bugs etc sind schon sehr viel wert. ;) ... es fehlen sicher auch noch einige HM Geräte, die ich selber nicht zum testen habe

**Comment by comtel2000** [comment]
Da habe ich einige und kann gerne Testen. Die Motivation bei mir ist aber auch selbst dazuzulernen, auch wenn mir NodeJS nicht sonderlich liegt.. :)

**Comment by thkl** [comment]
fixed here, will be published in npm 0.0.33
