### ISSUE TITLE
Unterstützung HM-LC-DW-WM Funk-Controller für Dual-White-LEDs

### ISSUE THREAD

**Issue by DrTob** [thkl/hap-homematic#270]
Der Sensor wird in der Geräteauswahl nicht angezeigt, ich nehme an weil er bisher nicht integriert ist.
[HM-LC-DW-WM.zip](https://github.com/thkl/hap-homematic/files/5646779/HM-LC-DW-WM.zip)

**Comment by thkl** [comment]
Moin, 
wie verhält sich das Gerät. Laut Doku: Kanal 1 DUAL_WHITE_BRIGHTNESS schaut aus wie ein normaler Dimmer ?
Kanal 2 DUAL_WHITE_COLOR aber irgendwie auch ?

**Comment by DrTob** [comment]
HI!
der erste Kanal ist die Helligkeit, der Zweite die Farbe  (0.0 = warmweiß bis 1.0 = kaltweiß)

**Comment by thkl** [comment]
ich hab nix zum Testen aber in der Theorie wird es so funktionieren ;o)

**Comment by DrTob** [comment]
v

**Comment by DrTob** [comment]
Danke, kann ich das irgendwie testen?

PS: hatte zwar extra vorher gesucht, trotzdem gerade gemerkt dass es die Anforderung schonmal gab: #228

**Comment by thkl** [comment]
Das file https://github.com/thkl/hap-homematic/blob/master/lib/services/HomeMaticDualWhiteDimmerAccessory.js könnte manuell nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/ geschoben werden.
Restart des Hap daemon und dann geht es ... es muss Kanal 1 ausgewählt werden. Kanal 2 wird automatisch mit benutzt

**Comment by DrTob** [comment]
Hi!
Funktioniert, aber Warm/Kaltweiß ist vertauscht. Hab's kurz gedreht:
  let r = (parseFloat(1.0 - x) * 360) + 140
...
 let x = 1.0 - (parseFloat(value) - 140) / 360

dann passt es.

DANKE!

**Comment by thkl** [comment]
ok die Characteristic geht von 140 - 500 .. und der HM Wert von 0-1 daher hab ich erst mal nur das 1:1 umgesetzt.
Aber gut ich dreh das auch mal
