### ISSUE TITLE
Neues Besonderes Gerät

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#271]
Ich hätte da Mal eine Idee für "Besondere Geräte". Es macht durchaus Sinn, einen Fensterdrehgriffkontakt (HmIP-SRH) und einen Fensterkontakt (HmIP-SWDO...) zu verbauen. Der Drehgriffkontakt ist für einen selbst wichtig, um den Status (Offen, Gekippt, Geschlossen) des Fensters zu erhalten. Zweiter ist für die Sicherheit, wenn das Fenster aufgebrochen wird, in diesem Fall würde der Fenstergriff ja nicht betätigt.
Jetzt hat man jedoch zwei Sensoren, die man über "Besondere Geräte" zu einem machen könnte. Hierbei ist dann die Einbauposition des Fensterkontakt noch wichtig. Erkennt dieser ein gekipptes Fenster auch also offen (Kontakt im oberen Bereich des Fenster verbaut) oder eben nur wenn auch offen. Es gibt somit zwei Szenarien für gekippt. Die Logig müsste dann so ausehen:

HmIP-SRH_______HmIP-SWDO___Ergebnis
geschlossen_____geschlossen____geschlossen
geschlossen_____offen__________ALARM
gekippt_________geschlossen____gekippt (bzw. gekippt aber geschlossen)
gekippt_________offen__________gekippt
offen___________geschlossen____offen aber geschlossen
offen___________offen__________offen

**Comment by thkl** [comment]
Kann man das nicht in der CCU abbilden. Ein Programm was auf den Magnetkontakt reagiert und wenn dieser Offen ist aber der Fensterdrehgriif weder gekippt noch offen ist wird eine Variable gesetzt.
Und diese Variable triggert dann HomeMaticVariableAlarmAccessory

**Comment by detLAN** [comment]
Ja/Nein. Natürlich kann man dies für den Alarm abbilden. Aber man kann damit dann immer noch nicht erkennen, ob z.B. ein gekipptes Fenster wirklich gekippt ist, oder einfach nur angedrückt, aber vergessen wurden den Griff auch zu schließen.

**Comment by thkl** [comment]
Achsoo

**Comment by thkl** [comment]
Ich habe mir jetzt folgende Matrix ausgedacht:
```
let matrix = [
      {result: 0, rotary: 0, window: false},
      {result: -1, rotary: 0, window: true},
      {result: 10, rotary: 1, window: false},
      {result: 25, rotary: 1, window: true},
      {result: 10, rotary: 2, window: false},
      {result: 100, rotary: 2, window: true}
    ]
```
result entspricht dem Öffnungsgrad des Fensters .. -1 wird im Nachhinein noch als 100% ausgegeben - aber mit einem Setzen des Tampered Status

**Comment by detLAN** [comment]
Perfekt 🤗, ich bin gespannt wie es sein wird.

**Comment by detLAN** [comment]
Hallo Thomas,

beim Einrichten ist mir folgendes Aufgefallen:
![Bild1](https://user-images.githubusercontent.com/64675966/103349224-9203ac80-4a9c-11eb-99da-dd83b521a805.jpg)
Bei der Heizung handelt es sich um die Heizungsgruppe aus der CCU, welche hier eigentlich nichts zu suchen hat.

Wenn ich Fenster und Fenstergriff jeweils als Window definiert habe, erscheinen beide und das definierte Gerät als Kachel und funktionieren soweit. Ein kleiner Schönheitsfehler besteht jedoch direkt nach dem Einrichten, da wird das definierte Gerät immer als offen dargestellt, obwohl die anderen beiden geschlossen sind. Nach dem Bedienen des Fensters pendelt es sich jedoch korrekt ein.

Eigentlich hatten wir uns ja darauf verständigt das Fenster als ContactSensor und nicht als Window zu definieren, da sonst in der Eve App ein Rollladen mit entsprechenden Meldungen erscheint. Das gleiche für den Fenstergriff, der als RotarySensor und nicht als RotaryWindow definiert sein sollte. In der Home App gibt es dann zwar keine Kachel direkt sondern erst unter den Fenstersensoren. Mit anderen Worten es sollte im definierten Gerät immer die Sensoren genommen werden, damit es in beiden Apps funktioniert.

Beste Grüße 
Detlef

**Comment by thkl** [comment]
Moin,

das Problem ist, das es bei "normalen" Fenstersensoren in HomeKit nur den Zustand offen oder geschlossen gibt.
Hier kann ich die "gekippt" Stellung nicht abbilden.

**Comment by detLAN** [comment]
Deine Matrix funktioniert ja soweit, es muss jedoch einmal vorher das Fenster richtig geöffnet werden. Aber wenn es nur mit rotary geht, dann denke ich ist es eine unbrauchbare Lösung und wir sollten auf dieses Besondere Gerät verzichten.

**Comment by detLAN** [comment]
Ich habe mich nie für reine HomeKit Geräte interessiert. Nachdem ich nun die eve App immer mehr nutze habe ich mir auch mal angesehen was für Geräte die anbieten. Dabei ist mir das Eve Window Guard aufgefallen. Dies erkennt ebenfalls ein gekipptes Fenster, mit anderen Worten die eve App müsste dies eigentlich auch visualisieren können. Vielleicht könnte dies dann auch für den HmIP-SRH genutzt werden?

**Comment by thkl** [comment]
Ja, das Problem mit eve ist; Elgato benutzt einige custom Characteristics und Daten um ihre eigenen Geräte zu supporten, wenn Homekit sowas nicht anbietet. Leider ist das nicht so leicht, rauszufinden was wie wo zu HomeKit geschickt werden muss, damit EVE es erkennt.

**Comment by blackbasket** [comment]
@detLAN besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)

**Comment by detLAN** [comment]
Aktuell keine Probleme
