### ISSUE TITLE
Support of more then 80 devices

### ISSUE THREAD

**Issue by StefanPotsdam** [thkl/hap-homematic#272]
I use more then 80 devises (93 devices) in my Homematic system and would like to use them from Homekit via hap-homematic as well

How to get it solved

thanks a lot in advance and best regards
Stefan

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Device related data**
If you want to add a new device or add a feature to a new device, please login to your hap-homematic WebUI; Select Internal/Help and create the device description file as described in the dialog you will get. Please attach the file to your request.

**Comment by JensBonse** [comment]
There is no issue with using that amount of devices.
As HAP suggests to use one instance per HomeMatic room.
And I assume that you do not have more than 100 HomeMatic devices in one single room ;)

**Comment by StefanPotsdam** [comment]
Thanks a lot Jens
100 per instance should be enough:-)
After restart now it works
