### ISSUE TITLE
Refresh delay?

### ISSUE THREAD

**Issue by MartiMan79** [thkl/hap-homematic#273]
Hi, I’m coming from a homebridge-openHAB system but I like the simplicity of this system.
One thing though, is there a possibility to set a status delay of a couple of seconds?
Each time I change a setting, the homematic ccu throws the old state back into homekit before the new is accepted so the values toggle new-old-new all the time within a timeframe of 3 seconds. The boost switch even seems to get into a loop, unable to deactivate.
My apologies if this is a noob question with a simple solution but didn’t find it...
Thanks in advance.

**Comment by thkl** [comment]
Which device/service .. depending on your question it looks like you are talking about the thermostat.

**Comment by MartiMan79** [comment]
Thanks for your fast answer, yes correct, a HmIP-WTH-2 Thermostat with humidity sensor.
My apologies not being more clear from the start. 
I just started experimenting with it and this wondered me as it was the first thing I put in and tested. In openHAB I put a delay on the receive channel for control items so that’s why I asked.

**Comment by thkl** [comment]
i've recently changed the behaviour for the thermostat to fix https://github.com/thkl/hap-homematic/issues/224 looks like this may also fix your issue

**Comment by MartiMan79** [comment]
Thanks, it behaves quite weird actually not just feedback issues. The loop seems also to be happening with the mode selector Auto-Heat-Off while it doesn’t change state in ccu3 it does fluctuate in homekit.

**Comment by thkl** [comment]
No but with that change i will also ignore all events from your ccu for about 2 seconds after u've sent a command.
So, i think this will stop the 'flickering'.

**Comment by MartiMan79** [comment]
Super!

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/101291377-8f4cc900-3808-11eb-85c1-e31272ca4f42.gif)
