### ISSUE TITLE
Can´t install hap-homematic after deleting it

### ISSUE THREAD

**Issue by Marfinho** [thkl/hap-homematic#274]
Hi folks,

I tried to switch from hap-homematic to homebridge and homematic plugin, but I´m not satisfied and wanted to switch back.

But I´m not able to install the add-on. Error 102:
"Ein unerwarteter Fehler ist während der Addon-Installation aufgetreten. Bei der hochgeladenen Datei handelt es sich entweder nicht um ein Addon-Archiv, ist defekt oder ist für eine andere Hardware vorgesehen. Bitte versuchen Sie es erneut oder kontaktieren Sie den Autor des Addons."

I really don´t get it, why this doesn´t work any more.

Any ideas what I did wrong? CCU is Raspberrymatic, also tried to update to newest version (3.53.34.20201121) but same behaviour.

Thank you in advance.

**Comment by thkl** [comment]
have u tried the latest installer ? https://github.com/thkl/hap-homematic/releases/download/0.0.14/hap-homematic-0.0.14.tar.gz
