### ISSUE TITLE
Keine Antwort bei CCU Meldung Gerätekommunikation gestört

### ISSUE THREAD

**Issue by Jemeins** [thkl/hap-homematic#275]
Moin,
ich habe testweise mal einen meiner Rollläden von der Spannung getrennt (HM-LC-BI1PBU-FM).
Der Rollladen ließ sich in HomeKit noch normal bedienen und ich bekam nicht die Meldung "keine Antwort" in HomeKit.
Müsste HomeKit nicht "keine Antwort" liefern, sobald die CCU Gerätekommunikation gestört meldet?
Mit freundlichen Grüßen

**Comment by thkl** [comment]
Ich prüfe den Status der Geräte in der CCU nicht. Daher wird der nicht nach HomeKit geleitet.

**Comment by Jemeins** [comment]
Das wäre denke ich noch eine wünschenswerte Funktion, denn sonst stimmt ja quasi der Status in HomeKit nicht.

**Comment by thkl** [comment]
Das ist leider nicht so einfach. 
Ich kann hinter einer Bridge nicht einem einzelnen Gerät den NoResponse Status verpassen. Um genauer zu sein. Ich kann diesen NoResponse Status nur dann erzeugen, wenn ich wirklich nicht auf Statusanfragen aus HomeKit reagiere.

**Comment by thkl** [comment]
Achso einige Geräte haben Fault Characteristics aber halt nicht alle. Daher lassen wir das lieber mal.

**Comment by Jemeins** [comment]
"NO_RESPONSE" müsste ja bei allen Geräten Funktionieren.
Also ist es nicht möglich wie bei „RedMatic HomeKit“ den Status für einzelne Geräte hinter einer Bridge zu prüfen?

**Comment by thkl** [comment]
No Response wird erzeugt indem man einfach nicht auf Anfragen von HomeKit antwortet. Da ich aber bei einer HomeKit Statusabfrage die CCU nach dem Zustand des Gerätes frage, und dort ggf den zuletzt bekannten Zustand bekomme, antworte ich auch auf so eine Anfrage immer. 

Ich müsste also vor jeder Anfrage von HomeKit in der CCU nach dem Status des Gerätes fragen. Ob dieses als gestört in der CCU vorliegt und dann einfach nicht antworten. Das würde schon gehen, aber irgendwie alle Anfragen insgesamt verlangsamen. 

Ich überlege mir das mal.

**Comment by Jemeins** [comment]
Wenn ich den Rollladen Lokal am Taster bediene wird in HomeKit ja öffnen / schließen angezeigt.
Ist es vielleicht auf eine ähnliche Art möglich, das die CCU bei gestörter Gerätekommunikation an HomeKit meldet? 
So würde man vielleicht die Anfragen nicht verlangsamen.

**Comment by JensBonse** [comment]
@thkl Hallo Thomas,
warum fragst du nicht in regelmäßigen Abständen die CCU ab, mit welchen Geräten es Kommunikationschwierigkeiten gibt?
Das könntest du dann Cachen und müsstet nicht bei jeder Aktion vorher prüfen. Es wird dann zwar nicht immer alles 100% übereinstimmen, aber in den meisten Fällen schon stimmen.
Verschickt die CCU einen Event, wenn es eine neue Störungmeldung gibt?

**Comment by thkl** [comment]
Ja die BidCos Schnittstelle schickt zumindest Events für Kommunikationsstörungen. 

Die müsste ich aber auch alle cachen ... 

Na mal sehen

**Comment by thkl** [comment]
Ok schaut so aus, als ob sich das recht einfach machen lässt.

Es gibt für gebridgte Accessories ein reachability Flag das kann ich updaten wenn ich einen Event für UNREACH auf dem Channel 0 bekomme.

**Comment by Jemeins** [comment]
Moin,
danke für deine Mühe!
Das heißt ich kann es im nächsten Update testen?
Wenn ja, wann rechnest du damit?
Mit freundlichen Grüßen

**Comment by Jemeins** [comment]
Ich habe es mal mit der .57 probiert, da wird noch nicht die Meldung "keine Antwort" in HomeKit gezeigt.
Sollte es schon Funktionieren?
Mit freundlichen Grüßen

**Comment by Jemeins** [comment]
Ich habe es in der .60 getestet, leider ist die Funktion noch nicht mit drin.
Wenn du Sie noch integrierst wäre ich sehr Dankbar @thkl!
Mit freundlichen Grüßen
