### ISSUE TITLE
Installationsassistent unterschlägt eine Instanz

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#280]
![Bild1](https://user-images.githubusercontent.com/64675966/102199470-f5e67c80-3ec3-11eb-9d11-e7179f67a5e0.jpg)
Ich habe mal wieder von ganz vorne angefangen - vorher alles schön sauber aus der CCU3 gelöscht.
Meine fünf Räume werden perfekt erkannt. Rot markiert ein kleiner Schönheitsfehler 😉

![Bild2](https://user-images.githubusercontent.com/64675966/102199745-42ca5300-3ec4-11eb-8fc2-61a954f17d34.jpg)
Dieser Aufforderung bin ich nachgekommen und habe alle Instanzen (von oben nach unten) in HomeKit eingerichtet.

Als nächstes sind die einzelnen Räume mit den jeweiligen Geräten abgefragt worden. Die Reihen folge sah wie folgt aus:

> 1. Außenanlage
> 2. Dachgeschoss
> 3. Untergeschoss
> 4. Garagenanlage
> 5. Außenanlage

Wer findet den Fehler 🤯? Genau, Position 1 und 5 sind identisch und das Erdgeschoss fehlt 🥲.

Btw. bei Fenstern mit vielen Geräten auf kleinem Display, wird das Fenster unten abgeschnitten. Hier muss man die Browserfunktion für verkleinern bemühen um an die unteren Einträge und Schaltflächen zu kommen.

![Bild3](https://user-images.githubusercontent.com/64675966/102207554-904bbd80-3ece-11eb-8ba1-65716abdde96.jpg)
Schöne wäre, wenn ich jetzt irgendwie den Assistenten noch mal bemühen könnte, um nicht alle Geräte im Erdgeschoss von Hand nachpflegen zu müssen.

**Comment by gerd2005** [comment]
Hallo,

sieht für mich so aus, dass der Cache der CCU noch nicht aktualisiert worden ist. Hast du vor dem Assistenten noch etwas an den Räumen o.ä. in der CCU angepasst?

**Comment by detLAN** [comment]
Moin,

nein, habe das PlugIn auf der CCU3 installiert, deren automatischen Neustart abgewartet und dann den Installationsassistenten abgearbeitet. Keine anderen Aktivitäten dazwischen.

**Comment by thkl** [comment]
hmm, ich hab da mal im CCU Simulator nachgebaut:

![image](https://user-images.githubusercontent.com/884355/102720049-224e2e80-42f2-11eb-9805-366c3a62ce77.png)

![image](https://user-images.githubusercontent.com/884355/102720075-43af1a80-42f2-11eb-9057-b5ade9d95eaa.png)

**Comment by detLAN** [comment]
Und zu welchem Ergebnis kommt Deine Simulation? Wird dabei auch ein "Raum" bei der Geräte abfrage unterschlagen, bzw. einer doppelt abgefragt

**Comment by thkl** [comment]
Alle Räume sind da und ja die Ports sind nach der Reihenfolge der Räume : 

![image](https://user-images.githubusercontent.com/884355/102721692-bcb36f80-42fc-11eb-9bc8-0509769d3687.png)

**Comment by detLAN** [comment]
Die Räume sind bei mir auch da, nur im nächsten Schritt, wie pro Raum die ganzen Geräte abgefragt werden, da wird bei mir wie geschrieben das Erdgeschoss unterschlagen und dafür die Außenanlage doppelt abgefragt.
Die Geräte für Erdgeschoss musste ich dann manuell nach nachtragen.

**Comment by thkl** [comment]
Nope alles da

![image](https://user-images.githubusercontent.com/884355/102721962-4879cb80-42fe-11eb-829b-41ac7464f5e3.png)

**Comment by detLAN** [comment]
Ein Bild sagt mehr als tausend Worte, [hier ein kleines Video](https://www.detlan.de/screen_recording.mp4)
Einen kleinen Schnitt habe ich gemacht, als ich die Home App in den Vordergrund geholt habe. Geht ja nicht jeden was an, mit wem ich mein Home teile 😉

**Comment by thkl** [comment]
Ich sehe den Fehler nicht ? Da ist doch am Ende nichts doppelt oder fehlt ? Es sind am Anfang 6 Instanzen und am Ende des Videos ?

**Comment by detLAN** [comment]
Bei 3:10 wird mit die Aussenanlage für die Geräte Auswahl angeboten und bei 3:55 kommt diese erneut. Dazwischen kommen alle anderen Räume mit ihren Geräten bis auf Erdgeschoss! Was letztendlich dazu führt, dass im Erdgeschoss keines der 32 Geräte veröffentlicht werden.

**Comment by thkl** [comment]
Ahhhh ich sehe es ... ok ich konnte das im Safari nachvollziehen im Chrome funktioniert es, da ich den immer zum Testen benutze ist mit das nicht aufgefallen.

**Comment by detLAN** [comment]
Hast Du auch gleich das Problem mit dem nicht Scrollen mit beseitigt?

**Comment by blackbasket** [comment]
@detLAN besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)

**Comment by detLAN** [comment]
Aktuell keine Probleme
