### ISSUE TITLE
Es werden in der Version 0.0.56 keine Geräte angezeigt.

### ISSUE THREAD

**Issue by markoox** [thkl/hap-homematic#284]
Hallo zusammen,

ich habe mir eine CCU 3 gekauft, hier die Aktuelle Firmware 3.53.34.20201121  installiert, dann alle meine Geräte eingerichtet IP Schalter UP, Rollo Schalter UP IP und Thermostate. Dann HAP-HomeMatic Version 0.0.56 installiert und geöffnet. Dann eine Instanz angelegt und versucht Geräte einzubinden. Doch mir wird kein Gerät angezeigt.

Was mache ich falsch? Wird außer dem HAP Plugin noch ein weiteres Plugin benötigt?

Schon mal besten Dank für eine Info.

Gruß

Marko Ochs

**Comment by dkrizic** [comment]
Vermutlich hast Du vergessen "Publish Services" bei den Instanzen zu aktivieren.

Tipp: Vorher die Instanzen in die entsprechenden Räume legen, dann sind die Geräte der Instanz auch gleich im richtigen Raum.

**Comment by markoox** [comment]
Hey, danke für die schnelle  Antwort,

aber es geht nicht darum das ich die Geräte nicht in HomeKit sehe sondern schon in der Instanz HAM, dort kann ich keine Geräte finden, die ich der Instanz zuordnen kann. Virtuelle Adapter der CCU 3 sehe ich sonst keine Schalter, Steckdosen Adapter usw.

**Comment by dkrizic** [comment]
Geh mal links auf "Internals" und "Refresh CCU Cache". Oder check mal die Firewall....

**Comment by thkl** [comment]
Wenn die Geräte nach dem Start des HAP Dämons zur CCU hinzugefügt wurden, dann weiß der nix davon. Dann hilft tatsächlich einmal die beschriebene Vorgehensweise von @dkrizic ... Die Firewallsettings werden erst interessant wenn die Instanzen zu HomeKit hinzugefügt werden sollen.

**Comment by thkl** [comment]
Erklärung siehe https://github.com/thkl/hap-homematic/issues/285#issuecomment-748464751

**Comment by markoox** [comment]
Hallo zusammen, danke für die vielen Infos. Ich werde es am Montag mal probieren und dann euch eine Rückinfo geben. Ich denke das ist die Firewall, denn ich habe bei der Einrichtung der CCU 3 auf ganz Sicher gestellt. Da die CCU3 von einem Bekannten ist, kann ich hier erst am Montag nach schauen.

Euch noch einen schönen Sonntag.

Gruß

Marko Ochs

**Comment by markoox** [comment]
Hallo zusammen,

es lag an den Firewall Einstellungen. Nach dem ich diese nicht mehre.

 so restriktiv eingestellt hatte, konnte ich alles Geräte in der HAP sehen.

Schon mal besten Dank für eure Hilfe.

Gruß

Marko
