### ISSUE TITLE
Neuer Schaltaktor wird nicht angezeigt.

### ISSUE THREAD

**Issue by derBremser** [thkl/hap-homematic#285]
Hallo, ich habe einen neuen Schaltaktor (Licht) installiert und in die CCU3 eingebunden. Leider taucht es danach nicht in der HAP Homematic auf? Was kann ich tun? Danke im Voraus.

**Comment by derBremser** [comment]
Hat sich erledigt habe es gefunden. Cache....

**Comment by thkl** [comment]
Ich erneuere zwar den Cache wenn ich von der Schnittstelle den Event für newDevice bekomme, aber an der Stelle hat das Gerät noch den alten Namen (Gerätetyp + Seriennummer) wie er aus der Schnittstelle nach dem Anmelden kommt. Der neue Name wird erst später beim Bearbeiten im Posteingang der CCU vergeben. Daher ist das Gerät schon da, aber halt weder im richtigen Raum noch mit dem richtigen Namen.

Leider sendet Rega keinen Event, wenn ein Gerät umbenannt oder in einen Raum verschoben wurde.
