### ISSUE TITLE
HM Sec SCO DataPoint

### ISSUE THREAD

**Issue by Luftloch80** [thkl/hap-homematic#287]
Ich habe eine HM Sec Sco neu an der CCU angelernt. 
wenn ich im Garage Accessory den Kontakt auswähle zeigt er mir unter DataPoint keine Einträge. 
ein baugleicher Kontakt wird ohne Probleme angezeigt. 

Habe Version 0014 drauf. 

Danke

**Comment by thkl** [comment]
Wurde unter Internes der Cache aktualisiert ?

**Comment by ChrWi** [comment]
@Luftloch80 ist das Thema noch aktuell?
