### ISSUE TITLE
Status von HmIP-BROLL

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#290]
Ich bin in der Eve App über folgendes gestolpert:

![IMG_0192](https://user-images.githubusercontent.com/64675966/102929555-1ce01800-449b-11eb-9a92-b55a1d565dea.jpg)

Hier habe ich ein Dejavu, da ich diesem Problem schon einmal begegnet bin. Ich vermute, dass hier einfach der falsche Kanal 4 für den Status abgefragt wird. Mit dem Kanal 3 für den Status dürfte es zu keinen Problemen kommen.
Im gezeigten Bild wird nur die Position vom Rollladen Terrasse richtig dargestellt. Die Werte in weiss geben den aktuellen Status des Rollladen wieder. Die Werte in grau neben dem Schieberegler die Position des Rollladen. Natürlich sollten diese Werte im Idealfall identisch sein, sind sie aber nicht, da nur Kanal 3 beide Werte korrekt übergibt. In der Home App fällt dies nicht auf, da dort die Position nicht zur visuellen Darstellung gebraucht wird.

Edit, hab ich vergessen beizufügen: 
[HmIP-BROLL.json.txt](https://github.com/thkl/hap-homematic/files/5732258/HmIP-BROLL.json.txt)

**Comment by thkl** [comment]
Der graue Wert (in Verbindung mit dem Schieberegler) ist der Sollwert. Der Wert neben dem Label der Ist wert.
Im Normalfall sollten diese bei stehendem Rollo gleich sein, da hast Du Recht. das CCU Device unterscheidet leider nicht zwischen Soll/Ist sondern hat nur einen LEVEL Wert.

Ich mache das vom "Working" Datanpunkt abhängig. Dieser ist true wenn das Rollo sich bewergt und wird auf false gesetzt wenn das Rollo stehen bleibt. Solange Working True ist setze ich den Ist Datenpunkt in HomeKit mit den Werten die ich für Level Events bekomme. Wenn der DP auf False gesetzt wird, setze ich sowohl Soll als auch Ist. Das kommt aus der Annahme, das das Rollo jetzt den gewünschten Stand erreicht hat. Hier liegt dann wohl das Problem mit Eve ...

ich muss da noch mal etwas rumexperimentieren.

**Comment by thkl** [comment]
Mir würde einmal ein DebugLog helfen wo das Rollo betätigt wird. Also einmal per CCU Oberfläche auf fahren und dann wieder auf einen anderen Stand zu fahren .. damit ich sehe, welche Datenpunkt wie gesetzt werden.

**Comment by detLAN** [comment]
Anbei die entsprechenden Logs aus CCU und HAP
[Log CCU.txt](https://github.com/thkl/hap-homematic/files/5735899/Log.CCU.txt)
[Log HAP.txt](https://github.com/thkl/hap-homematic/files/5735900/Log.HAP.txt)

Anfänglich hatte ich Kanal 4 für Programme genutzt. Konnte mir damals nicht erklären warum einiges funktionierte anderes nicht. Bis ich dann auf Kanal 3 gekommen bin, wo meine Abfragen dann immer funktionierten.

**Comment by thkl** [comment]
kann das sein:

16:06:15 von 0 auf 50% - läuft bis 16:06:25
16:06:35 von 50 auf 100% - läuft bis 16:06:45

16:06:48 von 100 auf 0% läuft bis 16:07:06


Schaut so aus, als kann ich den ACTIVITY_STATE auf Channel 3 benutzen ... Laut Doku kennt der "UNKNOWN", "UP", "DOWN", "STABLE" .. das heist kann bei UP und DOWN auf Channel 3 die Current Position in HomeKit auf das reportete Level setzen und wenn der DP auf STABLE switcht die Target Position nachziehen ...

**Comment by detLAN** [comment]
Wie geschrieben, mit Kanal 3 habe ich es auch hinbekommen. Als ich die Behanghöhe über Kanal 4 abgefragt hab, hat es nicht geklappt, erst mit Kanal 3.

**Comment by thkl** [comment]
Kanal 3 hat nur ReadOnly Datenpunkte schaut so aus, als ob Kanal 4 der ist, dem man auf dem LEVEL Datenpunkt den Soll Zustand sendet und Kanal 3 liefert dann die Events über das aktuelle Level wenn sich das Rollo bewegt

**Comment by thkl** [comment]
mir ist beim ausprobieren noch etwas aufgefallen. Eve updated den Slider für die Target Position nicht. Trotz das HomeKit einen neuen Wert gesetzt hat. Erst wenn man die Detailansicht für das Rollo verlässt und wieder aufruft wird er aktualisiert.
Dabei fragt Eve nicht mal mehr einen neuen Target Wert aktiv vom Gerät ab, sondern nimmt das letzte bekannte.

Das ist auf der einen Seite verständlich, denn die App geht davon aus, das sie ja selber den Wert ändert (User schiebt den Slider). Das funktioniert halt nur so lange, wie kein 2. User das HomeKit Gerät bedient, oder es direkt am Gerät bedient wird während die Detailansicht offen ist.

**Comment by gitalexa** [comment]
Hallo, sehe ich richtig, dass ihr mit der Home-App die Höhe in % der Jalousien steuern könnt? Ich hab den Datenpunkt 4 hinzugefügt und kann damit nur runter und anschließend wieder hochfahren....
Gibt es irgendwo eine Anleitung für die Steuerung mit dem Auto % Werten?

**Comment by detLAN** [comment]
Diese Frage gehört hier eigentlich nicht her, sondern in die [Discussions](https://github.com/thkl/hap-homematic/discussions), aber ich will sie Dir gern beantworten. Zum Ansteuern einer Position, musst Du diese in einer Szene definieren und anschließend mit einer Automation aktivieren.

**Comment by gitalexa** [comment]
@detLAN : Vielen Dank und frohe Weihnachten!

**Comment by Stefan774** [comment]
Hallo zusammen, bin auch gerade am Umstieg von Hombridge auf den Hap und auch bei mir ist das Verhalten der BROLL 1:1 wie in der Homebridge Version. Ich habe das  in der Homebridge Version für mich mal gekittet siehe hier https://github.com/thkl/homebridge-homematic/issues/181#issuecomment-385145296 wie und wo man das jetzt bei der Hap Version macht weiß ich nicht. Es ist aber wie beschrieben dass der Aktor nur auf Kanal 4 den richtigen Wert liefert wenn man den BROLL über den physischen Taster bedient. Problem an den Fix den ich bis heute in der Homebridge Version benutze ist aber, dass ich es nicht hinbekommen habe den „Wird geöffnet“ „Wird geschlossen“ Status anzuzeigen. Deshalb ging wahrscheinlich auch der Unit Test in die Hose. Für mich ist aber eine Korrekte Anzeige des aktuell Stands in % wichtiger.

**Comment by Stefan774** [comment]
@thkl ich mir ist gerade was aufgefallen warum es nicht klappt bzw. eigentlich Homematic hier was falsch macht aus meiner Sicht. Wenn man die BROLL Aktoren über den physischen Wippschalter betätigt dann liefern diese während des Fahrens die richtigen Werte jedoch haben die meisten das so konfiguriert, dass die Rollos bei einem Antippen der Wippe entweder ganz zu bzw. ganz auf  fahren. Anhalten kann man das dann indem man an der Wippe in die gegengesetzt Richtung tippt. So und hier kommt der Fehler der Broll setzt dann bei Anhalten des Aktors den Wert entweder Auf/100 oder Zu/0 im Kanal 4. 

Im Code müsste man jetzt den Set und Geter des BROLLs jeweils auf Get=3.LEVEL und SET=4.LEVEL setzen. Aber ich steig leider nicht durch welche Stelle die richtige ist. Könntest du mir/uns ggf. noch nen Tipp geben wie man das einbauen könnte?

**Comment by thkl** [comment]
Ich mache sowas schon:  Hier https://github.com/thkl/hap-homematic/blob/0c29999a6e25552b83c26279f177ae865ed9c33c/lib/services/HomeMaticBlindIPAccessory.js#L53 wird geschaut ob es den Datenpunkt clevel gibt (der ist hier https://github.com/thkl/hap-homematic/blob/0c29999a6e25552b83c26279f177ae865ed9c33c/lib/services/HomeMaticBlindIPAccessory.js#L347 auf Channel 3 Level definiert) .. wenn ja, wird hier https://github.com/thkl/hap-homematic/blob/0c29999a6e25552b83c26279f177ae865ed9c33c/lib/services/HomeMaticBlindIPAccessory.js#L165 auf dessen Events reagiert andernfalls auf Channel 4 Level.

**Comment by Stefan774** [comment]
Hmm verflixt leider funktioniert es aber nicht wenn man das mit der Wippe wie beschrieben bedient. Ggf. ein Timing Problem? Ich werd nicht schlau draus. Ggf. müsste man den 'clevel' Wert immer erst dann abfragen wenn die "Fahrt" beendet ist?

**Comment by thkl** [comment]
Naja ich frage die Datenpunkte ja nicht ab, sondern die Schnittstelle sendet Events wenn sich ein Wert für einen Datenpunkt ändert. Darauf reagiere ich. 

Wie ist denn jetzt das Verhalten ? .. Wenn man den Aktor per Tasten bedient, stimmt das Level in HomeKit nicht ?

**Comment by Stefan774** [comment]
Nein das Level ist dann immer entweder Offen oder geschlossen. Nur wenn man unter Level den Datenpunkt 3 einträgt stimmt die Anzeige jedoch kann man dann den Aktor nicht mehr bedienen

**Comment by thkl** [comment]
Würde es ggf helfen den Channel 3 noch mal konkret abzufragen, wenn die Fahrt beendet ist (es gibt dann einen PROCESS event)

**Comment by Stefan774** [comment]
Ich denke ja bzw. kann ich es testen wenn ich weiß wo ich die Anpassung machen soll

**Comment by thkl** [comment]
Das passiert schon hier : https://github.com/thkl/hap-homematic/blob/0c29999a6e25552b83c26279f177ae865ed9c33c/lib/services/HomeMaticBlindIPAccessory.js#L193

aber ich frage hier : https://github.com/thkl/hap-homematic/blob/0c29999a6e25552b83c26279f177ae865ed9c33c/lib/services/HomeMaticBlindIPAccessory.js#L198 den 4:Level ab ... es müsste einfach aus 'level' ein 'clevel' gemacht werden.

**Comment by Stefan774** [comment]
Das ist jetzt schon sehr nahe dran an der Lösung. Jetzt passt der Status im HomeKit egal ob man per Wippe oder App 'fährt'. Aber es gibt anscheinend noch einen anderen Trigger wenn man die HomeApp erneut öffnet dann 'schnapp' er sich wieder den Wert aus dem 'level' anstelle vom clevel und der Wert stimmt dann nicht mehr (ist wieder geöffnet/geschlossen)

**Comment by thkl** [comment]
Das wäre dann hier ebenso : https://github.com/thkl/hap-homematic/blob/0c29999a6e25552b83c26279f177ae865ed9c33c/lib/services/HomeMaticBlindIPAccessory.js#L65 level zu clevel

**Comment by Stefan774** [comment]
Nach der Änderung in Zeile 65 passiert folgendes:
HAP wird neugestartet App ist offen -> Es wird korrekt angezeigt
HomeApp wird geschlossen und neu geöffnet -> Er zeigt den Status "Schließen" und der bleibt (als würde der Rollo fahren)

**Comment by thkl** [comment]
Moment mal, also wird in Channel 3 der Ist Wert und in Channel 4 der Sollwert gespeichert ?
Dann müsste ich die Klasse generell mal etwas umbauen.

**Comment by Stefan774** [comment]
Also es scheint mir so. Ich benutze ja auch die PocketControl App und die Zeigt immer als Ist Wert den Channel 3 Wert an. Der Schieberegler zeigt den Sollwert Channel 4 an. 
![IMG_4592](https://user-images.githubusercontent.com/3195880/113438077-25c07e00-93e8-11eb-99cb-96c4011b92b8.jpg)

**Comment by thkl** [comment]
Problem bei HomeKit ist folgendes : es gibt einen Soll und einen Ist Wert.
Solange die sich unterscheiden zeigt HK die Anzeige Öffnen/Schließen an ... Wenn Ist=Soll geht HK davon aus das sich das Rollo nicht mehr bewegt und zeigt den % Wert oder Offen/Geschlossen an....

Wenn wir jetzt für den Soll Wert das Level aus Channel 4 und für den Ist Wert das Level aus Channel 3 nehmen und beide beim Ende der Fahrt nicht gleich sind, dann wird HK das Rollo dann nicht als "in Ruhe" anzeigen.

**Comment by Stefan774** [comment]
Ja verstehe tricky könnte man den Soll und Ist-Wert nach einer Fahrt nicht einfach gleichsetzen? Den Unterschied erkennt HK ja erst anscheinend wenn man die HomeApp schließt und neu öffnet. Wo passier im Code denn der Soll/Ist Vergleich?

**Comment by thkl** [comment]
Ja könnte man, aber wenn die Home App gestartet wird, bzw HomeKit den Ist Status erneut abfragt (das passiert zb wenn man den Raum verlässt und wieder aufruft) dann würden sich die Werte ja wieder unterscheiden.

In meinem Code dafür passiert kein Vergleich, das ist ein HomeKit Feature. Ich muss mich nicht um die Darstellung von Öffnen/Schließen/Offen/Geschlossen kümmern, ich liefere nur Soll und Ist Werte.

Ich könnte natürlich die Getter von Soll und Ist immer mit den Werten aus Channel 3 setzen. Und nur den Setter für TargetPosition auf Channel 4 setzen.

**Comment by Stefan774** [comment]
Das mit den Getter von Soll und Ist wäre noch einen Test Wert. Man müsste halt dann mal testen ob er den Sollwert dann auch noch anfährt. Könnte man den Level 4 Wert ggf. nicht einfach setzen und das auch in den CCU Wert zurückschreiben? Das verhalten ist echt ärgerlich ich glaub immer mehr, dass das ein Bug in der CCU selbst ist, das Verhalten macht doch eigentlich gar keinen Sinn... grr 😠

**Comment by thkl** [comment]
naja vielleicht doch ...so ein Thermostat hat ja auch Soll und Ist ...

**Comment by Stefan774** [comment]
Ja beim Thermostat is es mir verständlich auch bei den Jalousien aber wenn Soll != Ist sollte das Ding aus meiner Sicht den Sollzustand anfahren. Eine längere Differenz zwischen Ist unf Soll würde doch eigentlich auf einen Fehler hindeuten wie Jalousien blockiert oder ähnliches.. aber vielleicht sehe ich das auch falsch. Ich will nur im HK die korrekte Anzeige vom Ist wert, weil ansonsten die Szenen ned funktionieren 😉 ich hoffe ich kann irgendwie unterstützen, dass wir das ggf doch noch irgendwie abgebildet bekommen. Übrigens phantastisch Arbeit das mit dem hap-homematic vielen Dank dafür

**Comment by Stefan774** [comment]
Ja das löst das Problem. Vielen vielen Dank!!

Jetzt wird immer der richtige Wert angezeigt. Das einzige was jetzt noch ein wenig auffällig ist, ist dass wenn man die Jalousie in der HomeApp auf einen bestimmten Wert stellen z.B. 50%  dann rennt das so schnell Los, dass man den Wert eigentlich nicht wirklich 100%ig einstellen kann. Hier wäre ein kurze Delay von Vorteil bis man den %Wert in der App ausgewählt hat. Aber das sind Nuance die Meisten werden das eh über Szenen einstellen.

**Comment by thkl** [comment]
ok ich kann ein Delay einbauen welches immer gelöscht wird, wenn man einen neuen Wert einträgt

**Comment by Stefan774** [comment]
Genau das was ich gesucht habe 1500 finde ich recht angenehm 👍

**Comment by thkl** [comment]
1,5 sek .. ok

**Comment by Stefan774** [comment]
Also ich hab das ganze jetzt seit fast einer Woche im Einsatz und alles funktioniert jetzt wunderbar bei meinen 15 BROLLS 
-Close- ?

**Comment by thkl** [comment]
Ok :)

**Comment by candlestorm** [comment]
wie sieht denn nun die aktuelle fehlerfreie Version aus?
Ich habe hier leider nach Neuinstallation der Homebridge das gleiche Thema...
