### ISSUE TITLE
Rauchmelder als Sirene

### ISSUE THREAD

**Issue by burningbuell** [thkl/hap-homematic#291]
Hallo Zusammen,

kennt jemand eine Möglichkeit die Rauchmelder als Sirene in HomeKit einzusetzen?
Z.B.: Wenn niemand zu Hause ist und ein Fenstr geöffnet wird soll der Alarm ausgelöst werden. 

Viele Grüße

**Comment by dibadodo** [comment]
Das kommt auf deine Rauchmelder an. Bei manchen geht das, bei anderen nicht. Da ist es aber besser in Homematic Forum eine Antwort zu suchen.
