### ISSUE TITLE
Guten Morgen / Gute Nacht Szenen funktionieren nicht mehr zuverlässig

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#293]
Hallo,

ich habe seit ein paar Tagen das Problem, dass meine o.g. Szenen nicht mehr zuverlässig funktionieren. Maßgeblich steuere ich darüber unsere 14 Jalousien (HMIP-FROLL). Einige bleiben ganz random unten bzw. oben. Erst wenn ich den Befehl ein zweites Mal ausführe, funktioniert es auch mit den restlichen Jalousien.

Geändert habe ich, soweit ich weiss, nur die Software der CCU3 (Update auf V 3.55.5)

Hat jemand eine Idee woran das liegen kann?

Beste Grüße und schöne Weihnachtsfeiertage an Euch alle :-)

**Comment by thkl** [comment]
Ggf hängt das mit hier dran:

https://github.com/thkl/hap-homematic/issues/290

Die Status Rückmeldungen vom Rollo werden nicht richtig in HomeKit gesendet. Dadurch könnte es sein, das einige Rollos den falschen Zustand haben (zb. zu obwohl eigentlich offen)

Zum Test vor dem Start der Szene mal aktiv alle Rollo Detail Screen aufrufen und refreshen.  Dann holt sich HomeKit den aktuellen Status. 

.... nur so eine Idee.

**Comment by gerd2005** [comment]
Ja, stimmt. Es werden fast alle Rollos als geschlossen angezeigt, obwohl sie gerade offen sind...
![Uploading EF136C49-5BDB-44A9-A947-6C051632093B.png…]()

**Comment by gerd2005** [comment]
Beim Aktivieren der "Guten-Morgen-Szene habe ich mir mal das CCU3-Protokoll angeschaut.
![Unbenannt](https://user-images.githubusercontent.com/72799068/103266391-c5b4d880-49af-11eb-9c9a-07d0dde1cca7.PNG)

Es handelt sich dabei um unser Rollo im Gäste-WC. Dieses ist heute morgen unten geblieben.
Ich habe die Szene um 8 Uhr aktiviert. In dem Screenshot ist zu erkennen, dass der Befehl zum Hochfahren auch an der CCU ankommt, es passiert jedoch nichts. Zwei Minuten später habe ich den Befehl erneut ausgeführt. Hierbei ist das Rollo dann hochgefahren.

Hat jemand eine Idee woran das liegen könnte? Oder hat das tatsächlich mit dem #290 zu tun?

Lieben Gruß.

**Comment by ChrWi** [comment]
@gerd2005 ist das Thema noch aktuell oder mit der Lösung aus #290 geklärt.
