### ISSUE TITLE
Sonos Speaker hinzufügen

### ISSUE THREAD

**Issue by gitalexa** [thkl/hap-homematic#295]
Hallo,

ich habe meine Sonos-Speaker über Homegear als Geräte in der ccu3 und kann sie so ansteuern. In der Liste der Geräte für Homekit erscheinen sie aber nicht. 

Gibt es eine Möglichkeit, auch die Homegear-Geräte aufzunehmen?

**Comment by thkl** [comment]
Wie erscheinen denn die HomeGear Geräte in der CCU ?

**Comment by gitalexa** [comment]
![image](https://user-images.githubusercontent.com/4302427/103141301-e3094e80-46f2-11eb-8c9e-2699a30d9c74.png)

So wie die anderen Homematic-Geräte. Einfach in der Liste mit einem Kanal.

**Comment by thkl** [comment]
Ok, es gibt auf der WebUI des HAP Addons unter Internes eine Hilfe Option. Dort kann man ein DeviceFile für ein unbekanntes Gerät erstellen. Das brauch ich dann mal für so einen Sonos Lautsprecher.

Was kann die HM denn mit dem Sonos alles anstellen ?

**Comment by gitalexa** [comment]
[Sonos Play_3.json.zip](https://github.com/thkl/hap-homematic/files/5742356/Sonos.Play_3.json.zip)

Anbei das Device-File. Ich kann gern noch andere schicken - evtl. haben andere Speaker andere Werte?

Die HM kann mit den Sonos eigentlich alles anstellen, was auch über die Sonos-App geht:
- Play
- Stop
- Laut
- Leise
- Playlisten auswählen
- Verbinden von Speakern zu Räumen
- ....... 

hier sind alle Datenpunkte: http://kb.easy-smarthome.de/EASY_Sonos_Datenpunkte

**Comment by thkl** [comment]
Hmm ok , nur wie soll das in HomeKit abgebildet werden ?  Es gibt ein Speaker Accessory. Da könnte ich die Lautstärke drauf abbilden. Mehr kann das Accessory in HomeKit aber nicht.

**Comment by roe1974** [comment]
das wäre schon mehr als das homebridge plugin für sonos ... dort haben sie das accessory "speaker" nicht hinbekommen ... dort ist es ein schalter (mute on/off)

**Comment by gitalexa** [comment]
Richtig Gedanken darüber habe ich mir noch nicht gemacht, da ich heute erst hap-homematic installiert habe. Aktuell habe ich Programme für Sonos auf der HM angelegt und die ins HomeKit geholt... Ich weiß nicht, welche Grenzen es in Homekit gibt...

**Comment by thkl** [comment]
Play Pause:

![image](https://user-images.githubusercontent.com/884355/103142165-34b7d600-46ff-11eb-8364-e6d45de073f5.jpeg)

![image](https://user-images.githubusercontent.com/884355/103142167-3c777a80-46ff-11eb-87a0-7aa1a59da4ed.jpeg)


Controls erfordern etwas mehr Research 🧐😬
![image](https://user-images.githubusercontent.com/884355/103142164-2d90c800-46ff-11eb-8660-7cb7ef23761b.png)

**Comment by gitalexa** [comment]
Wenn ich was beitragen kann: Logfiles, Remotezugriff oder so - sag einfach Bescheid...

**Comment by thkl** [comment]
Das Problem ist eher erstmal in Richtung HomeKit

**Comment by roe1974** [comment]
ah schade .... wollte gerade testen ... aber homegear wird
1) nicht unter RM supported bzw. funktioniert dort nicht
2) nicht mehr weiterentwickelt (Siehe: https://forum.easy-smarthome.de/t/homegear-addon-erledigt/634)

**Comment by ChrWi** [comment]
@roe1974 ich mach das das Issue mal zu
