### ISSUE TITLE
Änderung / Umbenennen von Geräten 

### ISSUE THREAD

**Issue by spamverdacht98** [thkl/hap-homematic#297]
Hallo, 

ich habe gestern zwei Steckdosen (eine Homematic IP und eine Homematic mit Messfunktion) getauscht. Aus der IP für das Soundsystem im Wohnzimmer wurde ein Heizlüfter im Bad und andersrum. 

Wenn ich die Geräte neu im HAP hinzufügen möchte, werden die Geräte aber nach wie vor mit den „alten“ Namen anzeigt. Trotz mehrfachem Neustart der Ccu werden die Gerätenamen im HAP nicht geändert bzw. neu ausgelesen. 

Hat jemand eine Idee?

Vielen Dank im Voraus und schöne Feiertage.

**Comment by thkl** [comment]
Ja, das ist so, ich bekomme vom Logiksystem RegaHss keinerlei Infos über das Umbenennen von Geräten. Da die Namen aber auch manuell geändert werden können kann ich auch keine Vorher/Nachher Betrachtung machen. Wenn Geräte in der CCU umbenannt worden müssen diese manuell auf der HaP Oberfläche ebenso geändert werden.

**Comment by spamverdacht98** [comment]
Hallo,

 

vielen Dank für die schnelle Antwort.

 

Ich habe keine Möglichkeit gefunden, die Geräte ich der Übersicht der neuen Geräte umzubenennen. Erst wenn ich die Geräte hinzugefügt habe, lassen ich sich umbenennen.

 


Auch das Ablernen der Geräte brachte auch keine dauerhafte Namesändeung.

 

Wo bzw. wie kann ich eine dauerhafte Änderung der Namen durchfüheren?

 

Die IP Steckdose macht zumdem das Problem, dass sie sich nicht mehr mit Heizlüfter Ein/Aus steuern lässt. Ich bekomme die Nachfrage "Möchten Sie den Strom ändern" Benenne ich sie erneut um in z.B. Heizdecke funktioniert es fehlerfrei.

 

Vielen Dank im Voraus.

 

Peter

 

 

 

Gesendet: Samstag, 26. Dezember 2020 um 15:03 Uhr
Von: "Thomas Kluge" <notifications@github.com>
An: "thkl/hap-homematic" <hap-homematic@noreply.github.com>
Cc: "spamverdacht98" <spamverdacht98@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [thkl/hap-homematic] Änderung / Umbenennen von Geräten (#297)


 

Ja, das ist so, ich bekomme vom Logiksystem RegaHss keinerlei Infos über das Umbenennen von Geräten. Da die Namen aber auch manuell geändert werden können kann ich auch keine Vorher/Nachher Betrachtung machen. Wenn Geräte in der CCU umbenannt worden müssen diese manuell auf der HaP Oberfläche ebenso geändert werden.

**Comment by thkl** [comment]
Man kann Geräte nachträglich über das WebUI des HAP-Homematic Plugins ändern. Das geht dort in der Geräteliste mit dem jeweiligen Bearbeiten Buttons:

![image](https://user-images.githubusercontent.com/884355/103168716-da6d6100-4835-11eb-9797-5cb3c4aa471d.png)

Wenn das Gerät einmal in Hap-Homematic aufgenommen ist, hat eine Änderung des Namens in der CCU keine Auswirkung mehr auf den Namen in HomeKit. Wie oben beschrieben, bekomme ich a) keine Info aus der CCU das dort ein Name geändert wurde und b ) kann man ja die Namen manuell für HomeKit ändern und ich würde diese Änderung bei einer Änderung in der CCU wieder überschreiben.
