### ISSUE TITLE
Komplettabsturz bei Anlegen/Bearbeiten einer Instanz

### ISSUE THREAD

**Issue by RealWinny** [thkl/hap-homematic#298]
Hallo, ich habe folgendes Problem mit HAP-Homematic auf meiner CCU3 (derzeit aktuellste FW):

Wenn ich eine neue Instanz (unter Homekit Instanzen / Instanzen bearbeiten) manuell anlege oder eine existierende Instanz umbenenne, stürzt die komplette CCU in ca. 80% aller Fälle ab und ist erst nach vielleicht 15 Minuten und ein oder mehreren Neustarts wieder bedienbar. Schaue ich mir den HAP-Homematic-Log an, sieht man darin nur Einträge seit dem letzten Neustart und damit nicht den eigentlichen Crash.

Was könnte man tun, um den Fehler zu finden?

Gruß
Tobias

**Comment by thkl** [comment]
In /etc/config/addons/hap-homematic müssten in dem Falle .crash Files liegen.

**Comment by RealWinny** [comment]
> 
> 
> In /etc/config/addons/hap-homematic müssten in dem Falle .crash Files liegen.

Mmh, da liegt kein einziges Crash-File drin, siehe Screenshot unten.

Und jetzt? Kann es an der CCU selbst liegen? Finde ich da irgendwelche Crash-Logs, die nach einem Neustart noch da sind?


![grafik](https://user-images.githubusercontent.com/28679778/103167549-329f6580-482c-11eb-8957-5162cc110d54.png)

**Comment by thkl** [comment]
wenn der HAP Daemon abstürzt, dann wird das crashlog in dieses Verzeichnis geschrieben, denn das ist nach einem Reboot noch da ... /tmp oder /var/log liegen auf der CCU in einer RAM Disk und sind nach einem Neustart weg.

Es wurde eine neue Instanz angelegt bzw. eine vorhandene umbenannt und anschließend war die ganze CCU tot ?

**Comment by blackbasket** [comment]
Ich hatte das Problem mit .54 auch... allerdings bei der Anlage und später dem Löschen von Cux-Temperatursensoren (Netatmo)... ich hatte das Problem darauf geschoben... seit ich die Sensoren wieder gelöscht habe, ist das Problem bisher auch nicht mehr aufgetreten... danach habe ich dann auf .56 geupdated...

**Comment by thkl** [comment]
Ich kann das auf dem Testsystem erst mal so nicht nachvollziehen. Laut dem Screenshot oben sind nur HmIP / HM und eine Heizungsgruppe in Benutzung ...

**Comment by RealWinny** [comment]
Es passiert im Detail Folgendes:
Ich gehe in die HAP-App (Version 0.0.56) auf "Homekit Instanzen" und "Instanzen bearbeiten". Dann sind folgende Dinge hintereinander abgelaufen, sofern ich das jetzt aus der Erinnerung noch präzise hinbekomme:

1. Neue Instant angelegt: Nach dem Klicken auf "Fertigstellen" dreht sich das Warterädchen ewig, es passiert aber nichts mehr. -> **Crash** (siehe unten)
2. Nach komplettem Neustart der CCU selbiges erneut probiert. Die Instanz wurde in diesem Falle angelegt, allerdings lies sich die HAP-App anschließend nicht mehr vollständig bedienen. Beispielsweise konnte ich in das Menü "Geräte" wechseln, dort aber kein Gerät bearbeiten. Es gab keine Reaktion beim Klicken auf den "Bearbeiten"-Button. Ich habe dann versucht über das Menü "Internes" den HAP Service neu zu starten. -> **Crash** (siehe unten)
3. Erneut probiert eine Instanz anzulegen. Diesmal hat es geklappt. Eine Instanz konnte angelegt werden und ich konnte die Geräte anschließend bearbeiten. Da ich jedoch einen Tippfehler im Instanznamen hatte, habe ich kein Gerät zugeordnet, sondern zunächst wieder versucht die Instanz zu bearbeiten. -> **Crash** (siehe unten)
4. Ich habe das Ganze noch 2-3x wiederholt, immer mit demselben Ergebnis. -> **Crash**

Zum **Crash**:
Zunächst meldet das HomeMatic WebUI, dass irgendeine Komponente der Zentrale abgestürtzt sei, beispielsweise die RF-Komponente. Im selben Zuge lässt sich das WebUI nicht mehr bedienen, bzw. es öffnet sich keine Seite mehr. Nach ca. 2-3 Minuten startet die CCU neu und das dauert dann bestimmt 10 oder 15 Minuten. Dazwischen blinkt sie mal rot, mal blau, irgendwann ist sie dann aber wieder da.

Zur Info:
Ich hatte ein ähnliches Verhalten mal mit Node-Red. Das hab ich eigentlich nie richtig zum Laufen bekommen und bin deswegen zur Ankopplung an Homekit auf die HAP-App gewechselt, die von dem beschriebenen Problem abgesehen grundsätzlich läuft. Vielleicht hat aber doch die CCU irgendein Problem. Es ist halt schon sonderbar, dass zwei Apps ein ähnliches Fehlerbild liefern.

Wie könnte man denn jetzt am sinnvollsten mit der Fehlersuche weitermachen?

**Comment by RealWinny** [comment]
> 
> 
> Ich kann das auf dem Testsystem erst mal so nicht nachvollziehen. Laut dem Screenshot oben sind nur HmIP / HM und eine Heizungsgruppe in Benutzung ...

Das hier sind meine derzeit aktiven Geräte. Jetzt sollte ein neuer Raum angelegt werden ("Keller"), in den dann der "Bewegungsmelder Kellereingang" rein soll.


![grafik](https://user-images.githubusercontent.com/28679778/103168250-cb84af80-4831-11eb-9258-3cf09d4e9bf0.png)

**Comment by RealWinny** [comment]
Hier noch ein Screenshot meiner Instanzen. Der neue Raum heißt in meiner CCU "Keller". Nach den ersten zwei fehlgeschlagenen Versuchen bei der Instanzenanlage in HAP habe ich versucht einen anderen Instanznamen zu vergeben, nämlich Kellereingang, was dann tatsächlich erstmal funktioniert hat. Die Vermutung lag danach nahe, dass es irgendetwas mit der Bezeichnung "Keller" zu tun hat. Wenn ich jetzt versuche "Kellereingang" in "Keller" umzubennenen, kommt es tatsächlich auch wieder zum Crash. Allerdings passiert dies auch, wenn ich versuche in bspw. "Basement" umzubennen. Also hat es wohl mit dem Namen selbst doch nichts zu tun.

![grafik](https://user-images.githubusercontent.com/28679778/103168332-7301e200-4832-11eb-81b3-614789d0e269.png)

**Comment by thkl** [comment]
Nun, beim Umbenennen passiert erst mal grundsätzlich nichts anderes als beim Neu hinzufügen eines Gerätes.
Es wird ein Eintrag in der config.json gemacht und alle Instanzen starten neu. Das erzeugt kurzzeitig etwas Last auf dem Prozessor.
 
Was auf der CCU3 ggf passieren könnte, das node selber crasht und die CCU mit crashen lässt. Die Meldungen im WebUI der CCU, das eine Schnittstelle nicht geht, werden nur lokal vom Browser erzeugt. Der Fragt immer mal alle Schnittstellen ab und wenn da keine Antwort kommt popt dieses Meldung auf.

Was Du machen könntest ist den ssh Zugang zur CCU benutzen und hap beim Arbeiten zuschauen:

Wenn das System läuft per ssh auf die CCU zugreifen und dort hap beenden:

```
/etc/config/rc.d/hap-homematic stop
```

Dann hap im debug Modus starten

```
node /usr/local/addons/hap-homematic/node_modules/hap-homematic/index.js -D
```

(da kommt sehr viel Text in die Console aber das ist erst mal egal)


Dann den Crash verursachen und schauen was passiert

**Comment by RealWinny** [comment]
Ich habe den Dateizugriff immer mit FileZilla gemacht. Kommandos kann ich da aber nicht eingeben, richtig? Welches Tool würdest du dafür empfehlen?

**Comment by RealWinny** [comment]
Und noch eine Off-Topic-Zwischenfrage: Wird dir (@thkl) deine Arbeit hier oder überhaupt die Schaffung dieser App in irgendeiner Form vergütet?

**Comment by thkl** [comment]
ssh würde auf Windows zb mit Putty gehen. Die Vergütung besteht aus dem Spenden/Sponsor Button oben rechts auf der Seite. Die grundlegenden Funktionen sind entstanden, weil ich sie selber benötige. Der Rest eskaliert von alleine. 🤯

**Comment by RealWinny** [comment]
Ok, ich finde das auf alle Fälle klasse! Ich werde mich auf alle Fälle erkenntlich zeigen...

**Comment by RealWinny** [comment]
So, mich hab das mit Putty mal ausgeführt wie oben beschrieben. Scheinbar kommt es beim Starten im Debug-Modus auch schon zum Crash. Jedenfalls meldet Putty irgendwann "Network error: Software caused connection abort" und die CCU startet mit dem üblichen Geblinke (mal rot, mal blau, mal gelb) wieder neu. Ich hänge mal die Textdatei an, soweit ich das aus Putty ziehen konnte. Hilft das weiter um irgendeinen Fehler zu erkennen?

[Putty Log 20201227_1230.txt](https://github.com/thkl/hap-homematic/files/5744492/Putty.Log.20201227_1230.txt)

**Comment by thkl** [comment]
hmm schaut wirklich so aus, als ob die CCU3 mit dem start des HAP Daemons überlastet ist. Manchmal funktioniert es, manchmal crasht die ganze CCU wieder.
Das ist blöd .. Ich habe leider keine CCU3 zum Test. 

Die Idee, die ich jetzt hätte, wäre die Instanzen zeitlich versetzt zu starten um den workload zu senken.
Das ist leider etwas aufwändig umzusetzen.

**Comment by RealWinny** [comment]
Mmh, um dir jetzt nicht unendlich Arbeit zu bescheren, macht es vielleicht Sinn, wenn ich meine Hardware upgrade. Ich bin jetzt schon mal ganz grob durch's Netz geflogen und hab versucht mich schlau zu machen - so Richtung RaspberryMatic usw. Mir fehlt aber noch der detaillierte Überblick.
Gäbe es eine Empfehlung, mit welcher Hardware ich mein System performanter machen könnte, ohne dass ich jetzt ewig etwas neu konfigurieren muss? Prima wäre natürlich, wenn ich mein derzeitiges CCU-Backup und die HAP-Einstellung einfach übernehmen könnte.

Da in Kürze ein vorhandenes KNX-System noch mit angeschlossen werden soll und das Gesamtsystem sowieso eher größer statt kleiner wird, spiele ich ohnehin schon mit dem Gedanken, eine alternative Hardware anzuschaffen.

**Comment by thkl** [comment]
Ich denke mal, das perfomanteste was man derzeit so bauen kann ist ein Raspberry 4 mit einem HM-MOD-RPI-PCB (das ist das Sende/Empfangsmodul für den HM/HmIP Funk) + der Raspberrymatic Software. Und ja, Backup aus der CCU3 auf die RM spielen funktioniert. https://github.com/jens-maus/RaspberryMatic/wiki/Installation#umstieg-von-ccu3 

Die Hap Daten sind a) im CCU Backup enthalten (wenn gleich die eigentliche HAP Software nicht gebackupt wird) Man kann aber auch über das WebUI vom HAP ein Backup seiner Daten machen, und die später wieder einspielen. Das wäre die bessere Methode, denn beim Umstieg auf eine CCU3 wird empfohlen vor dem Backup alle Addons zu entfernen. Das Entfernen beinhaltet allerdings auch, das die Daten des HAP Addons dabei gelöscht werden.

**Comment by RealWinny** [comment]
Also irgendwie kommt mir das alles doch noch spanisch vor. So viel hab ich aktuell nicht am Laufen, dass die doch auch nicht schlechte CCU3 wegen dem Start von ein paar Instanzen komplett überfordert sein sollte. Ich wechsle jetzt erstmal auf meiner CCU3 von der EQ3-FW auf die RaspberryMatic. Das ändert zwar an der Hardware nichts, aber wer weiß...

**Comment by RealWinny** [comment]
Die Spendenkasse dürfte inzwischen übrigens geklingelt haben. Ob wir's jetzt bei mir zum Laufen kriegen oder nicht - ich finde es einfach genial, wenn sich jemand diese Mühe macht und so ein Tool schreibt und es auch noch der Allgemeinheit mit all dem Support zur Verfügung stellt. Tausend Dank!

**Comment by RealWinny** [comment]
Problem gelöst!!!

Nachdem ich die RaspberryMatic installiert hatte wurden die Probleme immer schlimmer, teils ist die CCU gar nicht mehr hochgefahren. Ich habe mehrfach die SD-Karte geflasht und auch eine neue ausprobiert. Nix half. Dann des Rätsels Lösung: Es lag am Netzteil! 
Seitdem ich ein anderes Netzteil an der CCU habe, hat sich alles wieder reibungsfrei installieren lassen und auch HAP-Homematic läuft einwandfrei. Keine Abstürze oder sonstiges. Nicht zu fassen! 

Das ganze Drama für Interessierte zum Nachlesen:
[HomeMatic-Forum](https://homematic-forum.de/forum/viewtopic.php?f=26&t=64017&p=630801#p630801)

Also, sorry für den Aufwand hier. Die gute Nachricht ist aber, dass die App in Ordnung ist und das Problem definitiv an meiner Hardware lag. Wünsche einen guten Rutsch! ;-)

**Comment by thkl** [comment]
Horray \o/
