### ISSUE TITLE
Systemvariable wird in HomeKit nicht aktualisiert

### ISSUE THREAD

**Issue by burningbuell** [thkl/hap-homematic#299]
Ich habe das Problem, dass eine in Homematic angelegte Systemvariable, welche ich über HAP-Homematic in Apple-Homekit eingebunden habe, nur aktualisiert wird, wenn ich HomeKit öffne.
Kennt jemand das Problem und evtl auch eine Lösung, wie man das im Hintergrund realisiert?

**Comment by thkl** [comment]
https://github.com/thkl/hap-homematic/wiki/variables#trigger
