### ISSUE TITLE
Multiple Instanzen

### ISSUE THREAD

**Issue by JensBonse** [thkl/hap-homematic#3]
Hi Thomas, kann man dann mehrere Instanzen laufen lassen, um die Begrenzung von 100 Geräten pro Gateway zu umgehen?

Finde es auf jeden Fall super das Projekt. Dann hat man endlich HomeKit direkt mit auf einer Maschine.

Ist HVL auch geplant direkt auf der CCU3 laufen zu lassen?

**Comment by thkl** [comment]
Das Projekt ist dafür ausgelegt mehrere Instanzen laufen zu lassen. Bei einer pro Raum und Zuordnung des Raumes zum Raum der CCU erfolgt dann sogar die Zuordnung der Geräte in HomeKit automatisch. 

CCu3 sollte funktionieren. Getestet ist es mangels Hardware nicht. Pivccu ist getestet  und RM. sollte also klappen.

**Comment by JensBonse** [comment]
Super!

Ich habe eine RM Charly auf einem Tinkerboard S.
Werde es dann auch mal testen und berichten.
Gehe aber davon aus, das es funktionieren wird.

Ist denn was für HVL geplant?

**Comment by thkl** [comment]
HVL läuft auch auf der RM (und sollte auch auf anderen CCU3s laufen)

**Comment by JensBonse** [comment]
Ich meine nicht nur das Plug-in um das Interface bekannt zu machen, sondern das gesamte HVL. Also der Server Part davon. Bisher läuft das bei mir auf einem Separaten Pi.

**Comment by thkl** [comment]
es git einen RM Installer für den Server .. das müsste alles gehen

**Comment by JensBonse** [comment]
FYI: HAP-homematic läuft auch auf einer RM Charly auf einem Tinkerboard S.

**Comment by thkl** [comment]
Nice !
