### ISSUE TITLE
Tauschen von geöffnet/geschlossen Zustand bei Markise

### ISSUE THREAD

**Issue by theMPstig** [thkl/hap-homematic#303]
Hallo,

habe hier eine Markise via CUxD angeschlossen. Homekit zeigt nun "Geöffnet" an bei eingefahrener Markise an und umgekehrt. Ggf. könnten auch die Begriffe von Geöffnet zu Ausgefahren und Geschlossen zu Eingefahren geändert werden.

Gibts da eine Möglichkeit? Danke und Grüße

**Comment by thkl** [comment]
Was für ein Gerät wird denn da durch CuxD erzeugt ?

**Comment by theMPstig** [comment]
Danke dir für die Rückmeldung! Man kann das bei der Einrichtung frei wählen, da es ja nur ein virtuelles Gerät ist. Bei mir ist es ein HM-LC-Bl1-FM |   | Funk-Rollladenaktor 1-fach, Unterputzmontage
Ich bin noch komplett neu im CCU3-Universum und habe daher keine Ahnung, ob man das irgendwie anders/besser machen kann. Ich habe diese Anleitung hier nachgemacht: https://homematic-forum.de/forum/viewtopic.php?f=37&t=21879

**Comment by thkl** [comment]
Ok also ein "normaler" CCU Rollo Aktor.
Ich müsste dem HomeKit Gerät dafür eine Funktion verpassen, das man die Werte umdrehen kann, also 0% entspricht 100% und umgedreht. Die Texte selber erzeugt IOS da kann man nichts machen.

**Comment by theMPstig** [comment]
Sicherlich nicht das größte Problem auf dieser Welt, aber für mich wäre es klasse!

**Comment by theMPstig** [comment]
Noch eine Ergänzung: Stopp wäre auch wichtig. So fährt er aktuell immer nur ganz aus oder ganz ein. Grad bei einer Markise wären manuelle Zwischenstopps aber sinnvoll.

**Comment by thkl** [comment]
Es gibt einen Stop Button, der löst auch ein Stop aus. Den Zeigt die HomeApp nur leider nicht an :) Eve macht das.

![image](https://user-images.githubusercontent.com/884355/103348305-e6595d00-4a99-11eb-801c-f8f63ec8c7e8.png)

**Comment by theMPstig** [comment]
Wär ja auch zu schön ;-)

**Comment by theMPstig** [comment]
Das "Werte umdrehen" klappt prima. Vielen Dank. Jetzt fehlt nur noch der Stop, aber das scheint ja ein Home-App-Problem zu sein...
