### ISSUE TITLE
HmIP-SMI / SMI55 / SMO - Bewegungserkennung deaktivieren

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#304]
Bei den HmIP Bewegungsmeldern kann die Bewegungserkennung deaktiviert werden. Dies ist z.B. von Vorteil, wenn der Hund allein zu Hause bleibt. Eine Integration in HomeKit wäre wünschenswert.

![Bewegung](https://user-images.githubusercontent.com/64675966/103270404-1d574200-49b8-11eb-9541-146857c58de4.jpg)

[HmIP-SMI.json.txt](https://github.com/thkl/hap-homematic/files/5750045/HmIP-SMI.json.txt)
[HmIP-SMI55.json.txt](https://github.com/thkl/hap-homematic/files/5750046/HmIP-SMI55.json.txt)
[HmIP-SMO.json.txt](https://github.com/thkl/hap-homematic/files/5750047/HmIP-SMO.json.txt)

**Comment by thkl** [comment]
Ähm das geht doch:

![image](https://user-images.githubusercontent.com/884355/103276191-2bac5a80-49c6-11eb-887d-c4bd0552f73f.jpeg)

**Comment by detLAN** [comment]
Hatte die Option "Aktiv Schalter hinzufügen" aktiviert und dann in der Home App gesucht. Aber okay, ist also wieder ein Funktion ausschließlich für Eve.

**Comment by thkl** [comment]
Ich muss mal testen wie das Home anzeigt wenn ich den Schalter nicht zum Motion Detector hinzufüge sondern einzeln erzeuge. 

Das schaut dann in Eve wieder doof aus weil es 2 Geräte sind. Aber wir haben ja den Home/Eve Button ab der nächsten Version.

**Comment by thkl** [comment]
@detLAN  ich habe gerade gesehen, ich habe die Unterscheidung bereits eingebaut :o) 

https://github.com/thkl/hap-homematic/commit/d3890f8fcbe6de956779ffb53190a82a791e6250#diff-43a561c55a34a5b061e62e418de0b734a9304bdbc6c68301e776698d5ce4460e

Der Button kommt also auch nach Home in .57
