### ISSUE TITLE
DoorBell Service ohne Video für HomePod

### ISSUE THREAD

**Issue by Phil7989** [thkl/hap-homematic#305]
Hallo zusammen,

benutzt jemand den HomePod als Klingel?
Kann ich das auch mit dem VideoDoorBellAccessory realisieren?
Einfach ein Tastendruck löst die Klingel im HomePod/HomePod mini aus?

Danke & Gruß Philipp

**Comment by gerd2005** [comment]
Das würde mich auch interessieren. 
Du hast vermutlich einen einfachen Klingelknopf an der Tür, und benötigst dann ja noch ein Gerät, welches den Tastendruck erkennt, oder?

**Comment by Phil7989** [comment]
Sorry, ich habe inzwischen den HomeMaticDoorBellAccessory gefunden. Das ist genau das war ich suche. aber so richtig ist der Service noch nicht in HomeKit integriert? 
Gibt es hier vielleicht ein Update dazu?

**Comment by Phil7989** [comment]
> Das würde mich auch interessieren.
> Du hast vermutlich einen einfachen Klingelknopf an der Tür, und benötigst dann ja noch ein Gerät, welches den Tastendruck erkennt, oder?

Man könnte ja auch einen Viertüllen Homematic Taster nehmen um das zu realisieren. oder einen normalen Homematic Taster. Oder man schließt die vorhandene Klingel an ein Homematic IO Modul an

**Comment by gerd2005** [comment]
Wie würdest du das denn über einen virtuellen Taster realisieren? Also was ich meine ist, dass du ja irgendwie noch eine Schnittstelle zwischen dem Tastendruck an der Klingel und dem betätigen des Tasters benötigst.

**Comment by Phil7989** [comment]
> Wie würdest du das denn über einen virtuellen Taster realisieren? Also was ich meine ist, dass du ja irgendwie noch eine Schnittstelle zwischen dem Tastendruck an der Klingel und dem betätigen des Tasters benötigst.

Ja das wäre doppelt gemoppelt. Ich habe tatsächlich an meiner Klingel einen Homematic 8-Bit HM-MOD-EM-8Bit und den leitet man dann einfach auf den VideoDoorBellAccessory um bzw. weiter.

**Comment by gerd2005** [comment]
Ach ok, auf der Suche bin ich ehrlich gesagt die ganze Zeit. Ich habe bislang nur den HmIP-DSD-PCB Gefunden. Mich schrecken jedoch die Batterien ab. Benötigt man bei deinem Batterien?

**Comment by Phil7989** [comment]
> Ach ok, auf der Suche bin ich ehrlich gesagt die ganze Zeit. Ich habe bislang nur den HmIP-DSD-PCB Gefunden. Mich schrecken jedoch die Batterien ab. Benötigt man bei deinem Batterien?

Ich habe bei mir ein Netzteil verbaut.

**Comment by gerd2005** [comment]
Es gibt also kein Modul, welches über die Klingelspannung funktioniert?

**Comment by thkl** [comment]
der DoorBell Service erzeugt ein DoorBell Accessory. Das wird zwar in der HomeApp als nicht unterstützt angezeigt, löst aber Push Meldungen aus, wenn es klingelt.

Der DoorBell Service kann jedem KEY Sensor zugeordnet werden. Also beliebigen Tastern, Virtuellen Tasten, Tastenschnittstellen. Ich benutze den HM-Sen-DB-PCB .. der braucht, wenn er an einer Klingelanlage hängt, die eine normale Glocke ansteuert, keine Batterien.
