### ISSUE TITLE
Seite kann nicht geladen werden

### ISSUE THREAD

**Issue by HeikoB95** [thkl/hap-homematic#308]
Seit der Aktualisierung auf die aktuellste Version kann ich die Konfigurationsseite des Plugins nicht mehr laden.
Vor dem Update habe ich auf die neuste RaspberryMatic Version geupdatet und die Seite war noch aufrufbar. Danach habe ich das Plugin aktualisiert und danach war die Seite nicht mehr aufrufbar. Die gesamte Software läuft auf einer CCU3. Der Dienst funktioniert, da ich die angelegten Instanzen mit der Apple Home App steuern kann. Wenn ich die CCU neu starte, dann erhalte ich kurz Zugriff auf die Seite, jedoch nur mithilfe eines vorher gesicherten Link und nicht mit der Schaltfläche in der Systemsteuerung der CCU.
Ich habe bereits den Cache meines Browser gelöscht und auch andere Browser ausprobiert. Mir ist aufgefallen, wenn ich Firefox verwende, dann wird mir nach Klicken der Schaltfläche in der Systemsteuerung der CCU kurz die Redirect Seite angezeigte, mit der Möglichkeit die HTTP oder HTTPS Seite des Plugins zu laden. Ich habe außerdem versucht, um diesen Fehler auszuschließen, die HTTPS Version von Raspberrymatic ein und auszuschalten, jedoch ließ sich die Plugin Seite in keiner der beiden Schaltzustände laden.

**Comment by thkl** [comment]
bitte mal in /var/log/hap-homematic.log schauen ob da Fehler auflaufen

**Comment by HeikoB95** [comment]
Ja da kommen kurz nach dem Start einige Fehlermeldungen.

root@ccu3-webui:/var/log# cat hap-homematic.log 
[Wed Dec 30 2020 11:00:16 GMT+0100 (CET)] info - [HAP Server] ---- launching ----
[Wed Dec 30 2020 11:00:16 GMT+0100 (CET)] info - [HAP Server] Welcome to HAP Homematic. Use your HomeMatic devices in HomeKit
[Wed Dec 30 2020 11:00:16 GMT+0100 (CET)] info - [HAP Server] (c) 2020 by @thkl - https://github.com/thkl/hap-homematic
[Wed Dec 30 2020 11:00:16 GMT+0100 (CET)] info - [HAP Server] using configuration at /usr/local/etc/config/addons/hap-homematic
[Wed Dec 30 2020 11:00:16 GMT+0100 (CET)] info - [HAP Server] [Server] settings loading ...
[Wed Dec 30 2020 11:00:16 GMT+0100 (CET)] info - [HAP Server] [Server] config loading completed; start building servicetable
[Wed Dec 30 2020 11:00:16 GMT+0100 (CET)] info - [HAP Server] [Server] service loading completed; publishing services
[Wed Dec 30 2020 11:00:16 GMT+0100 (CET)] info - [HAP Server] [Server] settings loading is done ; continuing init
[Wed Dec 30 2020 11:00:16 GMT+0100 (CET)] info - [HAP Server] [Server] Using config from /usr/local/etc/config/addons/hap-homematic/persist
[Wed Dec 30 2020 11:00:16 GMT+0100 (CET)] info - [HAP Server] Spawning configuration service with PID 1277
[Wed Dec 30 2020 11:00:16 GMT+0100 (CET)] info - [HAP Server] [Server] current restart count is  3
[Wed Dec 30 2020 11:00:16 GMT+0100 (CET)] info - [HAP Server] [Server] Checking rega connection
[Wed Dec 30 2020 11:00:16 GMT+0100 (CET)] info - [HAP Server] [CCU] check Rega is alive
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [Server] Rega is alive going ahead
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [Server] continueInitialization
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [CCU] loading object database for devices from /usr/local/etc/config/addons/hap-homematic/devices.json
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [CCU] object database loaded 19 objects found
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [CCU] device database loaded 19 devices found
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [CCU] loading object database for variables from /usr/local/etc/config/addons/hap-homematic/variables.json
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [CCU] object database loaded 14 objects found
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [CCU] variable database loaded 14 variables found
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [CCU] loading object database for programs from /usr/local/etc/config/addons/hap-homematic/programs.json
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [CCU] object database loaded 15 objects found
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [CCU] program database loaded 15 programs found
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [CCU] loading object database for rooms from /usr/local/etc/config/addons/hap-homematic/rooms.json
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [CCU] object database loaded 10 objects found
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [CCU] room database loaded 10 rooms found
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [CCU] disable Monitoring
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [Server] powering up bridge : HomeMatic default with id ########-####-####-####-########## , userid ##:##:##:##:##:## and pinCode  ###-##-###
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Zwischenstecker Aktor is HomeMaticSwitchAccessory
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [Server] add Zwischenstecker Aktor to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:17 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Heizprofil 1: Normal is HomeMaticSwitchAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add Heizprofil 1: Normal to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Heizprofil 2: Abwesend is HomeMaticSwitchAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add Heizprofil 2: Abwesend to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Heizprofil 3: Zuhause is HomeMaticSwitchAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add Heizprofil 3: Zuhause to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] service used for HmIP-WTH-2 000A9BE991E34E:1 is HomeMaticHumidityAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add HmIP-WTH-2 000A9BE991E34E:1 to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Heizprofil 4: Wochenende abwesend is HomeMaticSwitchAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add Heizprofil 4: Wochenende abwesend to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_default PinCode is ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] powering up bridge : HomeMatic Wohnzimmer with id ########-####-####-####-########## , userid ##:##:##:##:##:## and pinCode  ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Heizung Wohnraum INT0000001:1 is HomeMaticRadiatorThermostatAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add Heizung Wohnraum INT0000001:1 to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Hue Stehlampe Mitte - Helligkeit is HomeMaticDimmerAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add Hue Stehlampe Mitte - Helligkeit to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Hue Stehlampe Unten - Helligkeit is HomeMaticDimmerAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add Hue Stehlampe Unten - Helligkeit to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Hue Stehlampe Oben - Helligkeit is HomeMaticDimmerAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add Hue Stehlampe Oben - Helligkeit to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_Wohnzimmer PinCode is ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] powering up bridge : HomeMatic Küche with id ########-####-####-####-########## , userid ##:##:##:##:##:## and pinCode  ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_Küche PinCode is ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] powering up bridge : HomeMatic Schlafzimmer with id ########-####-####-####-########## , userid ##:##:##:##:##:## and pinCode  ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Schalt - Messaktor - Aktor is HomeMaticSwitchAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add Schalt - Messaktor - Aktor to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Hue Heiko Nachttisch - Helligkeit is HomeMaticDimmerAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add Hue Heiko Nachttisch - Helligkeit to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Hue Milena Nachttisch - Helligkeit is HomeMaticDimmerAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add Hue Milena Nachttisch - Helligkeit to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_Schlafzimmer PinCode is ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] powering up bridge : HomeMatic Büro with id c########-####-####-####-########## , userid ##:##:##:##:##:## and pinCode  ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_Büro PinCode is ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] powering up bridge : HomeMatic Badezimmer with id ########-####-####-####-########## , userid ##:##:##:##:##:## and pinCode  ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_Badezimmer PinCode is ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] powering up bridge : HomeMatic Garage with id ########-####-####-####-########## , userid ##:##:##:##:##:## and pinCode  ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_Garage PinCode is ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] powering up bridge : HomeMatic Flur with id ########-####-####-####-########## , userid ##:##:##:##:##:## and pinCode  ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Bewegungsmelder - Sensor is HomeMaticIPMotionAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add Bewegungsmelder - Sensor to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Hue Tischleuchte - Helligkeit is HomeMaticDimmerAccessory
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] add Hue Tischleuchte - Helligkeit to bridge instance ########-####-####-####-##########
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_Flur PinCode is ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] powering up bridge : HomeMatic Balkon with id ########-####-####-####-########## , userid ##:##:##:##:##:## and pinCode  ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_Balkon PinCode is ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] powering up bridge : HomeMatic Toilette with id ########-####-####-####-########## , userid ##:##:##:##:##:## and pinCode  ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_Toilette PinCode is ###-##-###
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] publishing accessories
[Wed Dec 30 2020 11:00:28 GMT+0100 (CET)] info - [HAP Server] [Server] 18 compatible devices found
[Wed Dec 30 2020 11:00:29 GMT+0100 (CET)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_default (##:##:##:##:##:##) is running on port 9877.
[Wed Dec 30 2020 11:00:29 GMT+0100 (CET)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_Wohnzimmer (##:##:##:##:##:##) is running on port 9878.
[Wed Dec 30 2020 11:00:29 GMT+0100 (CET)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_Küche (##:##:##:##:##:##) is running on port 9879.
[Wed Dec 30 2020 11:00:29 GMT+0100 (CET)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_Schlafzimmer (##:##:##:##:##:##) is running on port 9880.
[Wed Dec 30 2020 11:00:29 GMT+0100 (CET)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_Büro (##:##:##:##:##:##) is running on port 9881.
[Wed Dec 30 2020 11:00:29 GMT+0100 (CET)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_Badezimmer (##:##:##:##:##:##) is running on port 9882.
[Wed Dec 30 2020 11:00:29 GMT+0100 (CET)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_Garage (##:##:##:##:##:##) is running on port 9883.
[Wed Dec 30 2020 11:00:29 GMT+0100 (CET)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_Flur (##:##:##:##:##:##) is running on port 9884.
[Wed Dec 30 2020 11:00:29 GMT+0100 (CET)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_Balkon (##:##:##:##:##:##) is running on port 9885.
[Wed Dec 30 2020 11:00:29 GMT+0100 (CET)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_Toilette (##:##:##:##:##:##) is running on port 9886.
[Wed Dec 30 2020 11:00:29 GMT+0100 (CET)] info - [HAP Server] [RPC] server for all interfaces is listening on port 9875.
[Wed Dec 30 2020 11:00:29 GMT+0100 (CET)] info - [HAP Server] [RPC] server for all interfaces is listening on port 9876.
[Wed Dec 30 2020 11:00:32 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:0', 'CONFIG_PENDING', false ]
[Wed Dec 30 2020 11:00:32 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:0', 'DUTY_CYCLE', false ]
[Wed Dec 30 2020 11:00:32 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:0', 'LOW_BAT', false ]
[Wed Dec 30 2020 11:00:34 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:0', 'UNREACH', false ]
[Wed Dec 30 2020 11:00:34 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [
  'HAP_VirtualDevices.',
  'INT0000001:0',
  'OPERATING_VOLTAGE_STATUS',
  0
]
[Wed Dec 30 2020 11:00:35 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [
  'HAP_VirtualDevices.',
  'INT0000001:1',
  'SET_POINT_TEMPERATURE',
  22.5
]
[Wed Dec 30 2020 11:00:36 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:1', 'BOOST_TIME', 0 ]
[Wed Dec 30 2020 11:00:36 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:1', 'PARTY_MODE', false ]
[Wed Dec 30 2020 11:00:37 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:1', 'LEVEL_STATUS', 0 ]
[Wed Dec 30 2020 11:00:37 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:1', 'QUICK_VETO_TIME', 0 ]
[Wed Dec 30 2020 11:00:37 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:1', 'FROST_PROTECTION', false ]
[Wed Dec 30 2020 11:00:37 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:1', 'SET_POINT_MODE', 0 ]
[Wed Dec 30 2020 11:00:37 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:1', 'LEVEL', 0.29 ]
[Wed Dec 30 2020 11:00:37 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [
  'HAP_VirtualDevices.',
  'INT0000001:1',
  'ACTUAL_TEMPERATURE_STATUS',
  0
]
[Wed Dec 30 2020 11:00:37 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [
  'HAP_VirtualDevices.',
  'INT0000001:1',
  'SWITCH_POINT_OCCURED',
  false
]
[Wed Dec 30 2020 11:00:37 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:1', 'VALVE_STATE', 4 ]
[Wed Dec 30 2020 11:00:38 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:1', 'ACTIVE_PROFILE', 3 ]
[Wed Dec 30 2020 11:00:38 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:1', 'WINDOW_STATE', 0 ]
[Wed Dec 30 2020 11:00:38 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:1', 'ACTUAL_TEMPERATURE', 20.9 ]
[Wed Dec 30 2020 11:00:38 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:1', 'BOOST_MODE', false ]
[Wed Dec 30 2020 11:00:39 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:0', 'CONFIG_PENDING', false ]
[Wed Dec 30 2020 11:00:39 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:0', 'DUTY_CYCLE', false ]
[Wed Dec 30 2020 11:00:39 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:0', 'LOW_BAT', false ]
[Wed Dec 30 2020 11:00:39 GMT+0100 (CET)] error - [HAP Server] [RPC]  event unable to find Interface for [ 'HAP_VirtualDevices.', 'INT0000001:0', 'UNREACH', false ]
[Wed Dec 30 2020 12:00:16 GMT+0100 (CET)] info - [HAP Server] [Server] seems we are stable since 1 hour remove the restart counter
[Wed Dec 30 2020 12:00:16 GMT+0100 (CET)] info - [HAP Server] [CCU] disable Monitoring

**Comment by thkl** [comment]
und http://ccuip:9874/ geht nicht ?

**Comment by HeikoB95** [comment]
Nein leider nicht.

**Comment by thkl** [comment]
könnte ich ggf mal die config.json per Mail haben ... die liegt in  /usr/local/etc/config/addons/hap-homematic

**Comment by HeikoB95** [comment]
Klar schicke ich dir. Ich bin leider noch recht neu bei Github, kann ich dir hier eine private Nachricht schicken? Oder hast du eine Mail Adresse für mich?

**Comment by thkl** [comment]
die Mail steht in jedem Source File oben ;) https://github.com/thkl/hap-homematic/blob/master/index.js

**Comment by HeikoB95** [comment]
Oh, das war zu offensichtlich :D Die Mail ist raus

**Comment by HeikoB95** [comment]
Das deaktivieren der CCU Authentication scheint den Fehler behoben zu haben, danke dir :)

**Comment by thkl** [comment]
sehr wild .. zumal zumindest die Seite geladen werden müsste nur hinterher eine Fehlermeldung kommt. Ich muss da mal genauer nachsehen. Das ist eine CCU3 mit RM Image ?

**Comment by HeikoB95** [comment]
Ja genau
