### ISSUE TITLE
Während Konfiguration plötzlich keine Geräte mehr in HAP-Homematic

### ISSUE THREAD

**Issue by dibadodo** [thkl/hap-homematic#309]
Ich habe gestern Abend noch versucht meine Schalter, wie im anderen [Post](https://github.com/thkl/hap-homematic/discussions/307) beschrieben, im HomeKit einzulegen.
Ich hatte versucht die Programme, die an einen Schalter gebunden sind, direkt einzubinden, statt über den Schalter. Es war schon seltsam, das beim Anlegen des neuen Programms die Anzeige nicht aktualisiert wurde. Das neue Programm stand also nicht in der Liste. Ich habe es dann nochmal versucht, weil ich dachte irgendwas falsch gemacht oder nicht verklickt zu haben. Identisches verhalten - kein neues Programm in der Liste. Nach einigen hin und her und aktualisieren war es dann plötzlich da. Ok, dann noch das zweite Programm hinzugefügt. Auch hier wieder das Problem, das es nicht in der Liste aufgetaucht ist. Es half aber kein neu laden im Browser oder ähnliches. Dann habe ich den HAP Service neu gestartet und es war da. Mh, ok ....
Ich wollte dann noch was im Programm ändern, bin rein - Bearbeiten, habe das angepasst und Ok geklickt. Dann war plötzlich alles weg. Kein Programm mehr, keine Geräte alles auf 0. Weder Neustart des HAP noch kompletter Neustart des gesamten Systems haben geholfen.
Im HomeKit direkt sind die Geräte noch zu sehen. Teilweise noch verfügbar und auch ansprechbar, teilweise mit "Keine Antwort" markiert.

Es waren ca. 15 Instanzen mit >40 Geräten, 5-6 Programme und eine Variable eingerichtet.

Umgebung:
Raspberrymatic 3.55.5.20201226
ELV Charly (Raspberry 3)
Version HAP 0.0.14

Heute morgen wurde mir dann plötzlich das Update des HAP auf 0.0.57 angeboten. In der Hoffnung das dies etwas ändert, habe ich das auch durchgeführt. Hat natürlich nichts geändert.... - eigentlich logisch.

Im log ist zu sehen, das noch einige Instanzen vorhanden sind und ich Daten ein- und ausgehen.

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/76758561/103357996-d4d17e80-4ab4-11eb-9847-531e5517b18d.png">

<img width="264" alt="image" src="https://user-images.githubusercontent.com/76758561/103358234-62ad6980-4ab5-11eb-965e-7d1a4bd8f9d8.png">

<img width="277" alt="image" src="https://user-images.githubusercontent.com/76758561/103358252-6f31c200-4ab5-11eb-9749-a01ee96f9b14.png">

**Comment by dibadodo** [comment]
Hat da niemand eine Idee dazu?

**Comment by FlippiHimself** [comment]
Hi,

Hier hab ich gerade das gleiche erlebt... all meine Instanzen und Geräte sind weg und HAP zeigt mir jetzt auch keine Geräte mehr an... nicht mehr. Sobald ich die Startseite neu lade, kommt der Welcome Screen und beim nächsten Schritt sagt er mir, dass er fertig sei...

Ist sehr schade dass das jetzt so ist... ist sehr viel Arbeit die Geräte und Instanzen neu einzurichten; vorallem werden mir keine Geräte oder Räume mehr angezeigt... das macht das Ganze noch etwas schwieriger...

LG

**Comment by spaggi** [comment]
Kann ich so bestätigen, ist bei mir heute auch passiert. Ich bin noch am herumprobieren, daher ist es nicht schlimm aber wenn ich meine >40 Schalter eingerichtet hätte wäre das ziemlich bitter gewesen.

**Comment by thkl** [comment]
das ist schwer ohne Blick ins Logfile (liegt unter /var/log/hap-homematic.log) oder die config (/etc/config/addons/hap-homematic/config.json

**Comment by Sasi1977** [comment]
Hallo,

ich bin neu hier und habe auch das Tool installiert und Apple home eingerichtet. Heute Nacht waren alle Geräte und Räume weg. Voran kann es liegen ?

Muss ich unter Einstellung  einen haken für Apple Home-App kompatibel  setzen ?

Gruss

Sasi

**Comment by thkl** [comment]
Wo waren die Geräte und Räume weg ? In HomeKit  oder auf der WebUI vom Addon ?

**Comment by Sasi1977** [comment]
Hi, auf der Home app von iphone waren alle weg und neues Zuhause einrichten. Musste komplette neu machen.

**Comment by thkl** [comment]
Also auf der WebOberfläche war noch alles vorhanden, wie eingerichtet ? 

Ich stelle für HomeKit nur die Geräte zur Verfügung .. was dann damit passiert, da habe ich keinen Einfluss vom Addon her.
Zu den CCU Namen: ich muss einige Änderungen machen, da nicht alle Zeichen in HomeKit erlaubt sind.
Für gewöhnlich nehme ich den Kanalnamen des ausgewählten Kanals. Wenn der noch der Defaultname ist, dann nutze ich den vom Gerät. Der Name kann aber auf der Addon Oberfläche geändert werden und wird dann so auch zu HomeKit übertragen.

**Comment by Sasi1977** [comment]
besten Dank für die Antwort.  Ja auf der Weboberfläsche von Homekit waren die Geräte zu sehen aber nicht auf der Home app von Apple..komplett weg.

Muss ich was auf der Homekit einstellen oder haken setzen damit es bleibt ?

**Comment by thkl** [comment]
Nein, da muss nichts eingestellt werden. HomeKit wird einmal verbunden und dann bleibt es so.
Aber : Kann es sein, das Deine CCU zu dem Zeitpunkt vom Router eine neue IP bekommen hat ? 
Normalerweise werden die HomtKit Bridges, die das Addon erzeugt per mDNS in das Netzwerk rausgebrüllt, aber ich weiss nicht, wie sich HomeKit verhält, wenn sich da was ändert. Ich habe selber die CCU im Router auf eine feste IP via DHCP gestellt und noch nie das Problem gehabt das da was verschwunden ist.

**Comment by Sasi1977** [comment]
ich kann  mal auf der Fritzbox die eine feste IP zuordnen und lassen, sobald es wieder vorkommt, melde ich mich.

**Comment by robbyHuelsi** [comment]
Hallo zusammen,

ich habe ein ähnliches Verhalten vor ein paar Tagen feststellen können. Auf der CCU3 läuft RaspberryMatic mit hap-homematic. **Die CCU bekommt vom Router eine feste IP zugewiesen.** Ich habe 14 Instanzen in der Home App eingerichtet. Zwei Tage später waren alle weg (Geräte und Bridges/Instanzen).

Als mir das auffiel wollte ich auf der Weboberfläche der CCU3 nachsehen, was los ist. Diese wurde mir jedoch nicht angezeigt, weil die Seite von RaspberryMatic mehrmals in der Sekunde neugeladen wurde. Das habe ich so noch nie bei RaspberryMatic gesehen. Habe keine Ahnung, ob das im Zusammenhang steht. Also Stromstecker kurzzeitig gezogen. Weboberfläche kam wieder hoch, alles normal, doch die Geräte in Homekit blieben weg.

Ich habe jetzt zunächst die wichtigsten zwei Instanzen zur App hinzugefügt und werde es weiter beobachten. Wenn es wieder auftaucht, werde ich Log-Files liefern.

Grüße
Robert

**Comment by ChrWi** [comment]
Das klingt identisch zu #453 welches bereits auf neuere Installationen verweist.
