### ISSUE TITLE
No Devices in HomeApp

### ISSUE THREAD

**Issue by rhammeran** [thkl/hap-homematic#31]
Just installed hap-homematic / version 0.0.33
create 2 instance and added 2 devices and 1 program
added them to HomeApp

no devices will appear

in "HomeKit Instanzen / Instanzen bearbeiten" there are 2 instances, but "Veröffentliche Geräte: nein"

in "HomeKit Instanzen / Einstellungen" has no funktion

btw. "Internes / Neustart HAP Service - Sicher?" the buttons are "Covfefe/YOLO" - not in German

**Comment by thkl** [comment]
sorry i've screwed up the js for the application. 
Please update to 0.0.34 (there will be a Button to upgrade at right upper corner the WebUI).
Then the settings for Instances are back again, and you are able to enable the publishing of devices for the selected instance.

Covfefe = No
Yolo = Yes  ;-)
