### ISSUE TITLE
Home-App stürzt bei VideoDoorBellAccessory ab

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#310]
Hallo,

ich habe gestern versucht eine Kamera in meine Home-App zu bringen. Sie wird zwar im Standardraum angezeigt, wenn ich jedoch drauf klicke, stürzt die gesamte Home-App ab. Dies passiert gleichermaßen auf dem iPhone, wie auch auf dem iPad. Das Gerät habe ich unter „Besondere Geräte“ bereits entfernt.

Was kann ich tun? Den Raum bekomme ich bspw. nicht gelöscht. Die Möglichkeit wird mir in den Raumeinstellungen nicht angezeigt. Und das Gerät kann ich auch nicht mit einem langen Klick entfernen, da bereits beim Anklicken die App abstürzt.

![2B4364C9-DD2A-4414-BBF9-412FEE7732BE](https://user-images.githubusercontent.com/72799068/103363372-4280a900-4abb-11eb-8c41-99dfe0fa6a93.png)
![0F849B76-2C98-4DB2-A5F7-300BCEC1E7D8](https://user-images.githubusercontent.com/72799068/103363394-490f2080-4abb-11eb-920a-1fffccdab15a.png)
https://user-images.githubusercontent.com/72799068/103363396-49a7b700-4abb-11eb-8774-444ba7e730a9.MP4

**Comment by thkl** [comment]
Oh wow, ich hab das mal ausprobiert und siehe da, gleiches Problem.
Ich habe das Ding aber über die EVE App löschen können. Da kann man die Geräte einzeln anzeigen und löschen.

**Comment by gerd2005** [comment]
Das ist „schön“, dass du das nachstellen kannst 😜 

Die Eve-App nutze ich nicht. Bekomme ich die Kamera trotzdem irgendwie aus meiner HomeKit App? Oder bleibt mir nur die komplette Neueinrichtung des PlugIns ins?

**Comment by thkl** [comment]
Das Problem ist, das dieser Fehler wohl augenscheinlich in der HomeApp ist. Selbst wenn Du das Gerät aus HAP löschst bleibt es ja augenscheinlich in der HomeKit Datenbank.
Du wirst Dir also  mal kurzfristig Eve installieren müssen, um das damit aus der HomeKit Datenbank zu löschen.

Ich muss mal schauen warum die VideoDoorBell dieses Verhalten zeigt.

**Comment by blackbasket** [comment]
@gerd2005 besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)
