### ISSUE TITLE
Eve-History für Wandthermostat WTH-B

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#311]
Hi,

Habe meiner Oma ein WTH-B (Günstigere Version mit den Riesen Tasten)
gegönnt. Leider Füttert es nicht die Eve-History / Datenlogging. Das funktioniert bei den anderen Thermostaten super. 

Hier habe ich nur manchmal eine anzeige im Raum - z.B. -2 Grad? denke da wurde dann keine Daten übermittelt?

Device File im Anhang.
[HmIP-WTH-B.json.zip](https://github.com/thkl/hap-homematic/files/5755749/HmIP-WTH-B.json.zip)

Merci

**Comment by thkl** [comment]
Die Klasse selber macht das schon. Mal bitte nachschauen ob auf der CCU in /etc/config/addons/hap-homematic/ das passende History File gespeichert wird. Das heisst hostname_seriennummer_1.persist.json

**Comment by meistermolli** [comment]
In dem Verzeichnis sind verschiedene Angelegt.

zu dem Thermostat ist auch eine Datei Angelegt mit:
hostname_seriennummer_1_persist.json
homematic_XXXXXXXXXXXXXX_1_persist.json

für andere Geräte gibt es aber meist noch eine zusätzliche Datei:
mit dem hostname "localhost"
localhost_seriennummer_1_persist.json
und eine Datei 
hostname_seriennummer_1_pstore

Die beiden gibt es für dieses Thermostat nicht.

Braucht man ab einer Gewissen Datenmenge einen zusätzlichen USB Stick am Raspi? Wie für das CCU Logging
oder geht das alles auf die SD Karte?

**Comment by thkl** [comment]
die pstore Dateien sind bei einem Thermostat nicht nötig hier werden zb bei einem Kontakt oder Fenster der letzte Öffnungzeitpunkt abgelegt. Die persist.json ist per Text Editor lesbar da sollten die gemessenen Temperaturen drin liegen.

Manchmal dauert es etwas bis eve die Daten anfragt. Aber eigentlich nicht länger als 30 Min

**Comment by meistermolli** [comment]
Wird als einziges nicht in Eve angezeigt. Das Gerät ist ja schon 2 Monate angelernt. 

Kann ich die Datei löschen und die wird dann automatisch neu angelegt?

**Comment by thkl** [comment]
Ja, spätestens nach einem Neustart des HAP Dienst

**Comment by meistermolli** [comment]
das hat geholfen ...

Habe die entsprechende persist Datei gelöscht.

Nach einem Neustart von HAP und ccu und etwas warten erscheint jetzt auch das Log des Wth-b in der Eve App. 👍
