### ISSUE TITLE
0.0.57 Stürzt ab bei Start Lüftungsposition  #281

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#314]
Hallo,

version 0.0.57 Stürzt ab beim auslösen von #281 Lüftungsposition.

Startet anschließend nicht selber neu, ein Neustart über die CCU zeigt zwar einen Fehler aber HAP startet trotzdem neu. 

Wenn ich im Debugmodus Neustarte, und den Fehler durch Start der Lüftungsposition auslöse bekomme ich beim Download immer nur den Report von dem aktuellen Neustart und nicht den Report mit dem Absturz. Liegt dieser noch in einem Verzeichnis?

gruss meistermolli

**Comment by thkl** [comment]
ja crashlogs liegen in /etc/config/addons/hap-homematic/

**Comment by thkl** [comment]
ok in der Lüftungssteuerung war ein Tippfehler.
Das File https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/services/HomeMaticGarageDoorOpenerAccessory.js kann nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/ kopiert werden. (altes überschreiben) .. restart des Daemon und es geht

**Comment by thkl** [comment]
Kurze Frage  ? wie zuverlässig ist denn dieses HmIP-MOD-HO Gerät in HomeKit ? (Ich frage für: https://github.com/thkl/hap-homematic/issues/294#issuecomment-753378582)

**Comment by meistermolli** [comment]
Erstaunlich gut, mit ein paar kleinen Hürden:

Ich nutze es täglich über Siri.
Hier jedoch meist über das Handy, da meine Apple Watch 4 manchmal Probleme macht
(Verzögerung und Befehl ausführen dauert oft einfach zu lange und dann kommt ein fehler).

Das einzige Problem das ich hierbei habe, ist im direkten Wechsel von LTE auf unser WLAN vor unserer Haustüre.
Ich versuche den Auslöser also immer schon im LTE Bereich abzugeben oder wenn das Handy im WLAN verbunden ist.
Dann funktioniert es eigentlich fehlerfrei.

Den Button in der Home App nutze ich schon länger nicht mehr.
Da z.B. der Schieberegler ja eigentlich einen Schalter Simuliert, der aber wie ein Taster sofort wieder runter schnappt.
Man weiss nicht genau ob HomeKit nun geschaltet hat wenn man das Tor nicht sieht.
Das habe ich aber schon lange nicht mehr ausprobiert wie das aktuell abläuft und kann es morgen nochmal Probieren.

Der Status vom Tor ist aber nacht der Bewegung immer korrekt dargestellt.
Beim Verlassen der Garage habe ich z.B. einen potentialfreien Taster am Ausgang zum schließen.
HomeKit Zeigt die Änderung "geschlossen" auch direkt an. (auch offen, wenn man z.B. über die Hörmann Fernbedienung öffnet)

Ich habe das Video geschaut in #294 und lese mir mal das ganze issue durch, der Kollege hat aber kein Garagentor, sondern einen Drehtor Antrieb. (Rotamatic)

HmIP MOD HO:
Ich nutze es mit einer SupraMatic 3 (Torantrieb)

     > Kompatibel mit folgenden Hörmann-Antrieben:
     > Garagentor - SupraMatic Serie 3 E/P/HT ab Index Ci
     > Drehtor - RotaMatic/P/PL Serie 1 (ab 09/2010) und Serie 2
     > Linear/Schiebe Tor  - LineaMatic/H/P Serie 1 (ab 10/2009) und Serie 2
     > Garagentor + nochmal Zusatzmodul HCP Adapter - SupraMatic/ProMatic Serie 4
     > Drehtor mit Gelenkantrieb - VersaMatic/P
     > Industrietor - WA300 S4
     > Industrietor - WA300 RS4/WA 300 AR S4

Zu den weiteren Punkten in #294:
ich denke mit der Lüftungsstellung kann man bei einem Drehtor auch eine Kurze Öffnung zum Durchgehen von Fußgängern nutzen, statt die ganze Öffnung frei zu geben. Das ist sicher für den ein oder andern Hilfreich, da man diese Stellung zumindest im Garantentor Antrieb selber definieren kann (Wie weit das Tor hier aufgeht)

Die Integration des Hörmann "Lichtschalters" würde ich auch begrüßen. Wäre ein nice to have, da mann dann die Einschaltzeit selber beeinflussen könnte. (die regelt aktuell der Antrieb, und da geht das Licht ziemlich schnell wieder aus)

Ich schaue mir morgen mal das Verhalten in der WebUi im Vergleich zur Home App an.
Zudem vergleiche ich mit den Siri befehlen das verhalten.

Die Lüftungsfunktion hat mit deiner geänderten Datei heute nachmittag Funktioniert.

Ich habe das vorher noch nie gemacht aber habe eben die Crashfiles gefunden und ein Bisschen in der Ordnerstruktur rumgeschaut. Kann also nun auch zügiger Crashfiles und Debugfiles zur verfügung stellen falls etwas schief laufen sollte.

Vielen Dank für dein Engagement!

**Comment by meistermolli** [comment]
@thkl 

So ich habe mal die Siri befehle / Manuelles Auslösen in Home / Auslösen in CCU WebUi verglichen.
Teilweise zeigt die Home App sogar den Status schon schneller an wie die CCU WebUI!
CCU WebUI zeigt beim fahren des Tors Unbekannt an (das Zeigt Homekit Korrekter an Öffnet / Schließt)

Siri gibt folgendes Feedback:
> Hey Siri - Öffne das Garagentor ..."Das Garagentor wird geöffnet" (keine durchsage wenn das Garagentor offen ist)
> Hey Siri Schließ das Garagentor ... "Das Garagentor wird geschlossen (keine durchsage wenn das Garagentor geschlossen ist)
> Hey Siri Garagentor Lüftungsposition ein ... "Ok"

Anzeige Status:
> Geschlossen - alle aus (geschlossenes Garagentor Icon)
> wird geöffnet (öffnender Garagentor Icon)
> Offen - geöffnet (offener Garagentor Icon)
> schließt (schließender Garagentor Icon) +  Lüftungsposition wird eingeschaltet (drehender Ventilator)
> Geschlossen - alle aus (geschlossenes Garagentor Icon) (verzögert ca. 30 Sec. geht der Ventilator aus)

Lüftungsposition - Garagentor geöffnet - Lüftung ein (offener Garagentor Icon / Ventilator dreht)
Anzeige Torbewegung - Sofort Korrekt dargestellt!


Aktuelles Langsames verhalten:
Wenn das Garagentor geschlossen wird, Wird Lüftungsposition zusäzlich eingeschaltet.
Dann bleibt der Status Lüftungsposition noch eine kurze weile länger eingeschaltet.
Schaltet aber dann nach ca. 30 Sec. auch ab!
Wenn das Tor in Lüftungsposition steht und man es am "Ventilator" schließt, geht der Ventilator wieder an. 
Das Garagentor Icon geht auf Geschlossen. 30 Sec. Später geht dann auch der Ventilator aus.
Denke das liegt einfach an einer Längeren Abfragezeit des Zusätzlichen Ventilator Switch? Das Hörmann Modul an sich gibt ja direkt Bidirektional sein Verhalten als Antwort zurück.

Funktioniert für mich also Korrekt und kann auch mit der 30 sec. Verzögerung gut leben!
Feedback wenn das Tor geschlossen ist wäre schön, muss aber nicht sein.

Bei Fragen, gerne fragen! Kann auch Gene Screenshots oder Video machen.

Gruß meistermolli
