### ISSUE TITLE
HmIP-FSI16 als Bewegungssensor Rückmeldung

### ISSUE THREAD

**Issue by Jemeins** [thkl/hap-homematic#316]
Moin,

ich will mich nochmal für deine stetige Bemühung bedanken!

Es tut mir leid, im Issue #269 habe ich um eine Integration des Bewegungsmelders auf dem MULTI_MODE_INPUT_TRANSMITTER gebeten. 

Natürlich hattest du recht! Es macht kein Sinn die Bewegungserkennung auf Kanal 1 des Geräts anzubinden.
Nach etlichen probieren habe ich festgestellt das ich den Bewegungsmelder über NodeRed an den Aktor gebunden habe.

-Kanal 3 STATE true -> Bewegung
-Kanal 3 STATE false -> keine Bewegung

Besteht die Möglichkeit das du dies realisierst?

Besten Dank!

**Comment by thkl** [comment]
Hmm das geht schon, aber dann steht der Motion Detector auf einmal bei jedem HMIP Switch Channel zur Verfügung.
Das ist dann sicher sehr verwirrend.  Ggf baue ich eine Art Expert Mode ein für solche Sachen. Da muss ich mal drüber nachdenken.

**Comment by Jemeins** [comment]
Da geb ich dir recht!
Für diese spezielle Anwendung wäre so eine Funktion jedoch super!

**Comment by blackbasket** [comment]
@Jemeins ist das noch relevant? Sonst bitte das Ticket schließen. Danke :)
