### ISSUE TITLE
Nicht alle Geräte gefunden

### ISSUE THREAD

**Issue by theMPstig** [thkl/hap-homematic#318]
Hallo, nicht alle Geräte werden bei mir gefunden. Das letzte Mal war es so, dass es nach der Installation der Geräte quasi über Nacht dann bei hap homematic aufgetaucht sind. Jetzt fehlt mir aber ein Jalousieaktor seit Tagen, bzw. interessanterweise taucht nur mit den Kanälen 1-2 auf, 3, 4 und 7 fehlen aber. In der CCU3 ist alles vorhanden und funktionsfähig:
![image](https://user-images.githubusercontent.com/16834237/103474351-52420b00-4da3-11eb-9aaf-4a3f819dd982.png)
Im hap homematic ist nur das hier vorhanden:
![image](https://user-images.githubusercontent.com/16834237/103474368-6ab22580-4da3-11eb-9f07-8f908358c3a3.png)

Hat da jemand einen Tipp bzw. eine Idee?

**Comment by detLAN** [comment]
Moin,
hast Du schon mal Internes / CCU Cache aktualisieren mit anschließendem Neustart HAP Service ausprobiert?
Beste Grüße

**Comment by theMPstig** [comment]
Hallo Detlef, danke dir erneut. Genau das hat geklappt. Alle Geräte korrekt erkannt. Offen gestanden hatte ich den Punkt in den Einstellungen gar nicht gesehen, da ich da hätte runterscrollen müssen, was ich aber aufgrund der Farbwahl des Scrollbalkens (grau/dunkelblau) nicht erkannt habe, dass man da überhaupt scrollen konnte...

**Comment by thkl** [comment]
Zur Erklärung, ich bekomme zwar von der CCU gesagt, wenn ein neues Gerät hinzugefügt wurde, aber nicht wenn es in der CCU umbenannt wird. Daher dieses Verhalten. Den Cache automatisch aller X Minuten zu refreshen, halte ich allerdings auch für überflüssig
