### ISSUE TITLE
HAP crashed reproduzierbar

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#319]
Es ist relativ leicht HAP zum crashen zu bringen. Es braucht lediglich die eve App. Hier ruft man Räume / Typen / Strom auf und schon verabschiedet sich HAP. Danach muss man über das CCU-Addon einen Neustart erzwingen. Das Crash-Log hierzu sieht immer gleich aus:
[1609661340899.crash.txt](https://github.com/thkl/hap-homematic/files/5761343/1609661340899.crash.txt)

Der entsprechende Zeitabschnitt im CCU-Log:
[CCU.log.txt](https://github.com/thkl/hap-homematic/files/5761364/CCU.log.txt)

**Comment by thkl** [comment]
Das liegt am HomeMaticProgrammableSwitchAccessory der ist eigentlich noch weit vom Status fertig, und sollte eigentlich gar nicht im npm sein.

Das ist ein Schalter mit programmierbaren Schaltzeiten. Allerdings habe ich das Eve Protokoll dazu noch nicht komplett auseinandergenommen.

Ich werfe den wieder aus dem npm raus.

**Comment by detLAN** [comment]
Ich weiß nicht welchen Schalter Du damit meinst, wenn damit der HmIP-BRC2 gemeint ist, dann bitte nicht! Das ist meine Frinds of Hue Nachbau, welchen ich unbedingt brauche um nicht im Dunkeln zu stehen.
Ich brauche ja das Menü in eve nicht aufrufen.

**Comment by thkl** [comment]
du hast einem Kanal dieses Typs 'SWITCH', 'STATUS_INDICATOR', 'SWITCH_VIRTUAL_RECEIVER' den Service HomeMaticProgrammableSwitchAccessory zugewiesen. Den hätte es eigentlich noch gar nicht geben dürfen. Irgendwie packt npm das File aber mit ein. Der Unterschied zum HomeMaticSwitchAccessory ist, das dieser Typ (irgendwann) mal die Timerfunktion des originalen EVE Switches kann)

**Comment by detLAN** [comment]
Ich guck nachher mal, wo ich das brauche und ob ich es anders realisieren kann.

**Comment by thkl** [comment]
Einfach auf den HomeMaticSwitchAccessory (ohne Programmable im Text) wechseln. Der kann das gleiche ...

**Comment by detLAN** [comment]
Es waren 16 Geräte (HmIP-BSM, HmIP-FSM und HmIP-FSI16), welche ich jetzt entsprechend geändert habe. Wenn mich nicht alles täuscht, wurde der "fehlerhafte" Service jedoch beim Einrichten automatisch vergeben. Den Crash kann ich jetzt jedenfalls nicht mehr reproduzieren. 👍🏻

**Comment by thkl** [comment]
Oh ok dann wird es Zeit, das ich den Service mit einem Update rauswerfe.
