### ISSUE TITLE
HomeMatic ip geht nicht mehr 0.0.10

### ISSUE THREAD

**Issue by fighterzg6** [thkl/hap-homematic#32]
Wie der Titel schon sagt

**Comment by thkl** [comment]
0.0.10 ist das CCU Addon, welche Version zeigt das WebUI an ?

**Comment by fighterzg6** [comment]
0.0.34

Von meinem iPhone gesendet

**Comment by thkl** [comment]
Ich habe einige IP Devices welche problemlos funktionieren.
Bitte mal ins Log File schauen ob beim Schalten von IP Geräten Errors auftauchen.
Wenn nichts auffälliges ist, bitte mal HAP im Debug Modus neu starten, etwas hin und her schalten und dann das Log hier *als textdatei* anhängen.

**Comment by fighterzg6** [comment]
Hmm geht jetzt auf einmal nach Neustart der ccu! Komisch aber wenn’s läuft is gut

Von meinem iPhone gesendet

**Comment by thkl** [comment]
Ok, strange .. wie gesagt, mit dem Debug Log würde sowas auffallen, da schreib ich alles rein von den Events, die ich aus der CCU bekomme, bis zum Senden von Daten an die CCU. Damit kommt man recht fix auf Fehler. Leider ist das auch sehr sehr groß dann ;)

**Comment by thkl** [comment]
wow, vs-scode hat es mitbekommen 🐌 clapp (internal memo at myself)
