### ISSUE TITLE
Defekte Schalter und Aktoren. Vorgehensweise 

### ISSUE THREAD

**Issue by spamverdacht98** [thkl/hap-homematic#320]
Hallo,

nach und nach scheinen sich meine Lichtschalter und die alten Aktoren zu verabschieden. 
Da Sie ja bereits geschrieben haben, dass die CCU3 keine Änderung an das HAP raus gibt, wollte ich fragen ob es die Möglichkeit gibt, alte Geräte komplett aus dem HAP zu löschen. Alternativ ist es möglich die Adresse des Gerätes zu ändern? 

Es scheint, dass Aktoren mit gleichem Namen ebenfalls nicht an das HAP neu übertragen werden. 

Die Instans Esszimmer habe ich bereits zurückgesetzt. 

![neue CCU3](https://user-images.githubusercontent.com/21288582/103476215-0fd4fa00-4db4-11eb-9388-1054f6e47e5d.JPG)
![neu HAP](https://user-images.githubusercontent.com/21288582/103476240-3dba3e80-4db4-11eb-83a5-8fb0861d1857.JPG)

Wie lösen Sie dass Problem, wenn ein Aktor mal kaputt geht und Sie ihn ersetzten? 

Vielen Dank 

Peter

**Comment by detLAN** [comment]
Hallo Peter,
wenn Du auf der CCU den alten Schalter bereits gelöscht und den neuen hinzugefügt hast, dann im HAP einfach unter Internes / CCU Cache aktualisieren und anschließend Neustart HAP Service auswählen. Anschließend kannst Du das neue Gerät unter Geräte / Neu hinzufügen.
Beste Grüße 
Detlef

**Comment by spamverdacht98** [comment]
Hallo Detlef,

 

vielen Dank für die schnelle Hilfe.

 

Jetzt läuft es wieder!!

 

Peter

 
 

Gesendet: Sonntag, 03. Januar 2021 um 11:43 Uhr
Von: "Detlef" <notifications@github.com>
An: "thkl/hap-homematic" <hap-homematic@noreply.github.com>
Cc: "spamverdacht98" <spamverdacht98@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [thkl/hap-homematic] Defekte Schalter und Aktoren. Vorgehensweise (#320)


 

Hallo Peter,
wenn Du auf der CCU den alten Schalter bereits gelöscht und den neuen hinzugefügt hast, dann im HAP einfach unter Internes / CCU Cache aktualisieren und anschließend Neustart HAP Service auswählen. Anschließend kannst Du das neue Gerät unter Geräte / Neu hinzufügen.
Beste Grüße
Detlef

**Comment by thkl** [comment]
Hmm scheinbar ist die Nummer mit dem Cache Refresh doch irgendwie essentiell. Ich werde mal eine AutoRefresh beim Aufruf des WebUIs einbauen

**Comment by JensBonse** [comment]
> nach und nach scheinen sich meine Lichtschalter und die alten Aktoren zu verabschieden.
Bevor du die entsorgst, würde ich als Bastler Interesse an den defekten Aktoren anmelden ;)

**Comment by roe1974** [comment]
Ist ja meistens nur ein Kondensator der defekt ist 😉😉

**Comment by spamverdacht98** [comment]
Hallo Jens,

 

ich entsorge die nicht. Ich habe mir 4 auf Reserve bestellt und tausche die einfach hin und her. Später ersetzte ich dann C26, dann laufen die wieder.

 

Aber die schnelle Lösung ist halt kurz tauschen.

 

Peter

 
 

Gesendet: Sonntag, 03. Januar 2021 um 21:32 Uhr
Von: "JensBonse" <notifications@github.com>
An: "thkl/hap-homematic" <hap-homematic@noreply.github.com>
Cc: "spamverdacht98" <spamverdacht98@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [thkl/hap-homematic] Defekte Schalter und Aktoren. Vorgehensweise (#320)


 


nach und nach scheinen sich meine Lichtschalter und die alten Aktoren zu verabschieden.
Bevor du die entsorgst, würde ich als Bastler Interesse an den defekten Aktoren anmelden ;)

**Comment by spamverdacht98** [comment]
ja C26 verursacht meistens die Probleme.

 
 

Gesendet: Sonntag, 03. Januar 2021 um 21:42 Uhr
Von: "Richard" <notifications@github.com>
An: "thkl/hap-homematic" <hap-homematic@noreply.github.com>
Cc: "spamverdacht98" <spamverdacht98@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [thkl/hap-homematic] Defekte Schalter und Aktoren. Vorgehensweise (#320)


 

Ist ja meistens nur ein Kondensator der defekt ist 😉😉

**Comment by spamverdacht98** [comment]
Hallo, 

mir ist gerade aufgefallen, dass sich die getauschten Schalter zwar über Homekit schalten lassen, aber die Sprachsteuerung per Iphone funktioniert leider nicht mehr. 

Gibt es hierfür eine Lösung? Die getauschten Lichtschalter (Bad, Esszimmer und Küche) funktionieren nicht mehr. Z.B. Wohnziimer und Schlafzimmer hingegen schon. 

Vielen Danke im Voraus

Peter
