### ISSUE TITLE
Idee/Frage: Kann die Config auf eine andere Datei zugreifen für Eve History? Fake Kontaktsensor Variable.

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#321]
Hallo,

habe eine Idee zu den Fensterkontakten und Eve History.

**Kontakt in HAP angelegt als: HomeMaticWindowAccesory**
- Sieht schöner aus im Homekit (auch unsere 2 Flügelige Balkontür als Icon Auswählbar)
- Siri Abfrage ob Fenster offen funktioniert (mit Hinweis auf Motorisierte Fenster
- Status wird schön dargestellt mit offenem / geschlossenem Fenster als gerät

- leider keine Eve History (zum vergleichen wann die Fenster offen waren im Bezug auf Temperaturabfall)

**Kontakt in HAP angelegt als: HomeMaticContactSensorAccessory** 
- Eve History möglich

- leider wird kein Gerät im unteren reiter der Geräte angezeigt. Nur ein Kontaktsensor im "Status"
________________________________________________________________________________________________________________

Kannst du dem HomeMaticWindowAccesory sagen es soll auch eine persist anlegen oder Blockt Eve die dann weil es kein HomeMaticContactSensorAccessory ist?

Da das Gerät nicht doppelt über HAP eingebunden werden kann (wegen Homekit nicht möglich),
könnte man doch eine Variable in Homematic anlegen mit dem Status offen / geschlossen. Dieser Status wird dann in EVE History angelegt (funktioniert zumindest bei der Relativen Luftfeuchtigkeit schon mit History)

Kann man dann diese Variable und das HomeMaticWindowAccesory irgendwie Gruppieren, so dass man in HAP dann das Window + die Variable einem Gerät zuweist? Dann würde die Anzeige in Homekit passen und Eve könnte die History erstellen.

---------------------------------------------------------------------------------------------------------------------

Gruß meistermolli

**Comment by detLAN** [comment]
Das Thema gab es so ähnlich bereits. Du musst Dich für eins entscheiden. Da Dir die eve History wichtig ist, warum nutzt Du dann nicht auch die eve App, da ist dann ja egal wie die Home App es darstellt. Btw. ist von Apple so gewollt, Kontaktsensoren zusammen zu fassen.

**Comment by meistermolli** [comment]
Hallo @detLAN,

darum geht es ja aber in meiner Frage nicht... um beides nutzen zu können hatte ich eine Idee und Frage hier nach der Umsetzungsmöglichkeit.

Die wäre folgende:

**Virtuellen Taster nehmen und benennen "Fenster Status"
Programm Anlegen:
Wenn Fenster Kontakt = offen dann "Fenster Status" = true sonst "Fenster Status" = false

in HAP Homematic ein HomeMaticWindowAccesory anlegen mit dem Gerät Virtuellen Taster "Fenster Status" 
dann ähnlich wie bei dem Boost Modus der Heizungsthermostate ein weiteres gerät integrieren, das Gruppiert angezeigt wird.
Das zweite Gruppierte Gerät ist dann der Fenster Kontakt mit HomeMaticContactSensorAccessory.
Dieses zweite Gerät kann man ggf. Ausblenden lassen von HomeKit?
Die Geräteklasse HomeMaticContactSensorAccessory ist dann aber im gesamten Gerät noch enthalten und wird hoffentlich dann von Eve in die History eingetragen.**

---------------------------------------------------------------------------------------------------------------------

Mir geht es bei der HomeKit Nutzung schlicht darum meiner eigenen Familie zu Hause, aber auch der weiteren Familie (Eltern, Schwager, Bruder) zugriff auf das SmartHome zu geben. Zum Glück sind die fast alle mit Apple ausgestattet. Nicht jeder ist so gewandelt darin das SmartHome zu bedienen oder zu verstehen. Alle haben im Standard schon die HomeKit App drauf. Was bringt mir ein SmartHome, das nur ich selber nutzen kann und jeder weitere steht da wie der Ochse vorm Berg.

Ich kann dem Besuch auch sagen, bevor du es nutzen kannst lade bitte noch die
Hue App, die Nuki App, die Eve app, die Homeconnect app und die Sonos app herunter... finde dich darin zurecht.
Wenn du dich dann irgendwo in der app verläufst oder in der Datenflut ertrinkst macht der Besuch doch nie mehr die App auf.

Ich sage doch lieber: Hier ist die Einladung. 
Der rest ist mehr oder weniger selbst erklärend (wenn es um die Bedienung geht).
Du kannst dir sobald du im WLAN bist selber die Haustür auf machen oder erst deine Matschigen Schuhe von der Wanderung in der Garage ausziehen und waschen.
Der eingeladene kann keine Geräteänderungen vornehmen, ist beim Annehmen der Einladung bereits in der richtigen App auf dem Startbildschirm mit den wichtigsten Geräten. Eigentlich schlau gelöst.
(Wenn HomeKit an anderen Ecken nicht so viele Einschränkungen hätte, die ich damit umgehen kann, dass ich Persönlich auch andere Apps nutze)
Besuch muss auch nicht auf die History Zugreifen oder die Automationen Programmieren. Das mache nur ich. Also reicht es aus, dass nur ich die Eve App nutze... dennoch sollte das alles etwas strukturiert sein.

Mein Ziel bleibt: Alles in einer App. Allein schon wegen der TV / HomePod und Sonos Bedienung nutze ich im gesamten Alltag auch die Apple Home App.

**Comment by detLAN** [comment]
Okay, dass ging so aus Deinem einleitenden Post jedoch nicht hervor 😉

**Comment by thkl** [comment]
Ähm wenn ich mir das hier so durchlese, weiss ich nicht was das eigentliche Problem ist ... 🤔
Sollte ich was umbauen müssen: Kann mir mal jemand ein mangement summary geben
