### ISSUE TITLE
HmIP-SRD Regensensor unter HomeKit - Rain sensor

### ISSUE THREAD

**Issue by mxkms** [thkl/hap-homematic#322]
Hallo zusammen,

ich bin gerade dabei einen Regensensor HmIP-SRD einzurichten. Leider ist dieser nicht unter den Geräten auffindbar. Verbunden mit der RaspberryMatic ist dieser. 

Ist der Sensor überhaupt kompatibel? Kann mir jemand sagen wie ich die Geräte aktualisieren bzw. Neue Geräte angezeigt bekommen kann? 

Danke und Lg

English:

Hello everybody,

I'm currently setting up a rain sensor HmIP-SRD. Unfortunately, this cannot be found under the devices. This is connected to the RaspberryMatic.

Is the sensor compatible at all? Can someone tell me how I can update the devices or display new devices?

Thanks

**Comment by gerd2005** [comment]
Hallo,

bei so einem Fall aktualisiere ich immer einmal den CCU Cache im PlugIn. Das hilft meistens. Wenn nicht, einmal noch das PlugIn neu starten. Wenn auch das nicht hilf, einmal die komplette CCU neu starten. ... oder in deinem Fall die RaspberryMatic.

**Comment by thkl** [comment]
Der Regensensor ist aktuell noch nicht verfügbar. Es gibt in HomeKit kein passendes Gerät. 

Ich könnte ihn ggf auf einen "Anwesenheitssensor" mappen. Regen da/Regen nicht da :)

**Comment by mxkms** [comment]
Hallo,

Danke erstmal für die schnelle Antwort. Wenn das Ganze so funktionieren würde, wäre ich sehr dankbar. Der Regensensor gibt eh nur aus Regen da oder kein Regen. Also keine bestimmte Menge. Von daher wäre das echt klasse 👌🏼

Wäre natürlich auch as Lecksensor denkbar. Dann ist das mit dem Regen und Wasser in einer Beziehung. 

Des Weiteren wird bald ein Windmesser Typ  HmIP-SWO-B Folgen. Da die Frage ob dieser kompatibel ist?

Danke schon mal.

LG Max

**Comment by thkl** [comment]
Der Leak sensor erzeugt aber gleich mal ne Push Notification wenn er auslöst. Das heißt alle in diesem Home angemeldeten iOS Geräte bekommen dann eine Meldung wenn es regnet :)


Der swo-b wird teilweise unterstützt. Ich übertrage die Temperatur Feuchtigkeit und Helligkeit zu HomeKit.  Was anderes kann dir HomeApp nicht. 

Wenn man allerdings ElgatoEve als Client App benutzt, wird alles angezeigt ....

**Comment by mxkms** [comment]
Stimmt aber man könnte ja die notification in dem Fall bei dem Sensor in HomeKit aus stellen. 

Danke schon mal :)

**Comment by thkl** [comment]
Ich habe in der Doku gesehen der Sensor hat auch einen Temperaturwert. Deswegen wird das dann so aussehen:

![image](https://user-images.githubusercontent.com/884355/103918609-4b9ef500-510f-11eb-9961-b05e47569d0d.png)
