### ISSUE TITLE
Kein Homekit Button unter Systemsteuerung

### ISSUE THREAD

**Issue by Camel2k** [thkl/hap-homematic#323]
Ich habe folgendes Problem.

nach Installation des HAP Addons bekomme ich keinen Homekit Button unter der Systemsteuerung in 
der Raspberrymatic 3.55.5.20201226,
Unter Zusatzsoftware wird mir aber angezeigt das die Version 0.0.14 installiert ist.

Im hmhapinstall.log steht folgendes:
[Installer]Start installer
[Installer]Program Dir is /usr/local/addons/hap-homematic
[Installer]installing HAP-Homematic ...
[Installer]creating HomeKit Button ...

Internetverbindung hat die Raspberrymatic.

Hätte jemand rat?

Camel2k

**Comment by thkl** [comment]
funktioniert das Addon selber ? http://ipderccu:9874

**Comment by Camel2k** [comment]
Nein, leider auch nicht.

**Comment by thkl** [comment]
dann ist also /usr/local/addons/hap-homematic auch leer ?

**Comment by Camel2k** [comment]
So sieht das Verzeichnis auf der Raspberrymatic aus.

![Bild 10 01 21 um 11 52](https://user-images.githubusercontent.com/36271283/104120877-8638a580-533a-11eb-83df-d4b9dca93cb9.jpeg)

**Comment by thkl** [comment]
schau mal bitte, ob in /etc/config/rc.d eine hap-homematic Datei liegt.
Und hat die CCU einmal neu gestartet nach der Installation ?

**Comment by Camel2k** [comment]
Die CCU hat nach Installation neu gestartet.

Das befindet sich in /etc/config/rc.d 

![Bild 10 01 21 um 12 57](https://user-images.githubusercontent.com/36271283/104122138-8d17e600-5343-11eb-8e8e-056101e405e8.jpeg)

**Comment by thkl** [comment]
wurde da, aus welchen Gründen auch immer, dieses File hier nicht mit rein entpackt:

https://github.com/thkl/hap-homematic/blob/master/addon_installer/rc.d/hap-homematic

Das startet beim Start der CCU den ganzen Zauber.

**Comment by Camel2k** [comment]
sollte ich das dann mal in den Ordner per Hand kopieren?

**Comment by thkl** [comment]
ja und ausführbar machen (also chmod +x .. oder das Ausführbar Attribut via FTP setzen) ..  /usr/local/addons/hap-homematic/etc/postinstall.sh muss auch +x werden ggf ist das auch nicht passiert

**Comment by Camel2k** [comment]
und dann Neustart oder neu installieren?

**Comment by thkl** [comment]
Neustart ....  das File in rc.d ruft  /usr/local/addons/hap-homematic/etc/postinstall.sh auf und dort wird geprüft ob alles da ist und ggf installiert

**Comment by ChrWi** [comment]
@Camel2k bitte Feedback / wieder öffnen wenn noch aktuell
