### ISSUE TITLE
HomaticVariableAlarmAccessory gibt Status nicht weiter

### ISSUE THREAD

**Issue by hoja-67** [thkl/hap-homematic#326]
Ich wollte eine Variable anlegen, die den Status der Alarmanlage in der Apple Home App anzeigt. Das wollte ich über HomaticVariableAlarmAccessory lösen. Leider funktioniert es nicht so wie erwartet.

Ich habe im WebUI eine Wertevariable names "Alarm" mit den Werten "home;away;night;off;alarm" angelegt. 

<img width="1013" alt="Bildschirmfoto 2021-01-11 um 14 14 36" src="https://user-images.githubusercontent.com/77279372/104187364-f8cb8300-5417-11eb-948f-9874677e28a2.png">

Dann habe ich diese Variable in HAP-Homatic als HomaticVariableAlarmAccessory angelegt. Die oben genannten Werte habe ich in der gleichen Reihenfolge eingetragen. 

<img width="810" alt="Bildschirmfoto 2021-01-11 um 14 20 23" src="https://user-images.githubusercontent.com/77279372/104187512-2fa19900-5418-11eb-89ac-4166fee3c324.png">

Dann habe ich den Trigger aktualisiert. Die Variable "Alarm" ist auch jetzt in _hap_autotrigger_ eingetragen. 

<img width="996" alt="Bildschirmfoto 2021-01-11 um 14 20 59" src="https://user-images.githubusercontent.com/77279372/104187570-4942e080-5418-11eb-9ba8-d5210f657952.png">

Die neue Variable taucht auch in der Apple Home App auf, wird dort aber nicht aktualisiert, wenn man den Wert über die CCU ändert. 

Wenn man versucht, die Variable in der Home App zu ändern, dann wird im Icon ein Spinner und der Text "Aktivieren..." angezeigt. Der Spinner hört nicht mehr auf zu drehen. 

<img width="454" alt="Bildschirmfoto 2021-01-11 um 14 21 46" src="https://user-images.githubusercontent.com/77279372/104187608-59f35680-5418-11eb-84b0-30b2f5957d99.png">

Leider habe ich keine Idee mehr, was ich falsch mache. Hat jemand einen Idee?

**Comment by thkl** [comment]
ja, das ist ein Bug der ist mit der nächsten Version gelöst

https://github.com/thkl/hap-homematic/issues/78#issuecomment-756806161

**Comment by hoja-67** [comment]
Danke für das schnelle Feed-Back!

**Comment by hoja-67** [comment]
Das Update funktioniert übrigens gut. Vielen Dank!
