### ISSUE TITLE
Anpassung von https zurück auf http nicht möglich

### ISSUE THREAD

**Issue by Challenger-db** [thkl/hap-homematic#327]
In den Einstellungen habe ich im hap-homematic Plugin **https** aktiviert und bekomme seitdem beim Aufrufen über den Home-Kit Button aus der CCU3 heraus eine weiße Seite.
Es gibt keine Möglichkeit die Connection von **https auf http zurückzusetzen** - oder?

VG

**Comment by thkl** [comment]
die URL auf die der Button verweist ist http(s)://ipderccu:9874 in dem falle https ...

**Comment by Challenger-db** [comment]
Der Alternativ-Link funktioniert.
Der verwaiste Button-Link könnte auch andere Nutzer irritieren ;)

Danke.
