### ISSUE TITLE
Fensterkontakte - automatische Pushbenachrichtigung deaktivieren 

### ISSUE THREAD

**Issue by FabianLR** [thkl/hap-homematic#328]
Eine Frage oder Bitte:

Ich habe neulich 4 Fensterkontakte zu meinem HmIP System hinzugefügt. Nun bekomme ich auf jedem Gerät (3 Handys 3Macs und 2 iPads) bei jeder Statusänderung eine Pushbenachrichtigung...... die ich aber gar nicht benötige, im Gegenteil sie "nerven".
Leider werden die Einstellungen dazu nicht über die iCloud Synchronisiert, das bedeutet das ich die Einstellung auf jedem der 8 Geräte und für jeden Fensterkontakt deaktivieren muss.

Gibt es eine Möglichkeit das vorher zu deaktivieren, oder könnte man das im Hap-homeatic anders programmieren? Oder ist das generell so gewünscht/gewollt?

Gruß, Fabian

**Comment by thkl** [comment]
HAP-Homematic selber sendet keine Push Messages. Das macht Homekit selber. Bei Sensoren sind diese in HomeKit generell erst mal an. Diese müssen also wirklich manuell ausgeschalten werden.
