### ISSUE TITLE
Dimmer Level update nicht aktiv an Homekit durchgereicht

### ISSUE THREAD

**Issue by comtel2000** [thkl/hap-homematic#33]
Ich habe das Problem mit HmIP-BDT, das Dimmer Level Änderungen von anderen Tools (bspl. aus CCU 3 Weboberfläche) nicht in Homekit sichtbar sind, bzw. nur wenn Homekit irgendwann ein Update anfordert oder Homekit neu geöffnet wird.
Die Änderungen des Levels aus der CCU WebUI sind im HAP debug vorhanden, aber in Homekit gibts keine Aktualisierung.

```
[Fri May 01 2020 21:09:53 GMT+0200 (CEST)] debug - [HAP Server] [RPC] event for HmIP-RF.0008DA498E7xxx:4.LEVEL with value 1
[Fri May 01 2020 21:09:53 GMT+0200 (CEST)] debug - [HAP Server] [DIMMER] event Level 1
```

**Comment by thkl** [comment]
Ähm das ist Dein Pull Request gewesen. Sicher das der Datenpunkt DIMMER_VIRTUAL_RECEIVER ist ?

**Comment by thkl** [comment]
Ah ich sehe schon. Der IP Dimmer hat keinen Working Datenpunkt.
Und ich warte mit dem Senden an HomeKit bis Working = false gesendet wird.
Der Datenpunkt den man da nehmen müsste wäre sicher PROCESS

**Comment by comtel2000** [comment]
Ja, es funktioniert ja auch wenn ich alles über Homekit steuere. Das mit unterschiedlichen Tool ist mir gerade aufgefallen. Das gleiche hatte ich im homebridge plugin auch. Ich probiere mal PROCESS

**Comment by thkl** [comment]
Ist mir aufgefallen da zwar die Meldung [DIMMER] event Level %s im Log steht aber nicht [DIMMER] update brightnessCharacteristic to  %s .. die kommt nur wen self.isWorking nicht wahr ist.
Und das wird gesetzt wenn ein Working = False kommt

**Comment by comtel2000** [comment]
Ja, das isses. Hatte bei WORKING auch überlegt. Ich kann gleich einen neuen PR machen..

**Comment by thkl** [comment]
nicht nötig ;)
