### ISSUE TITLE
Wettersensor HmIP-SWO-PL

### ISSUE THREAD

**Issue by gitalexa** [thkl/hap-homematic#331]
[HmIP-SWO-PL.json.zip](https://github.com/thkl/hap-homematic/files/5813853/HmIP-SWO-PL.json.zip)

Hab mir ne Wetterstation gekauft.... Anbei das Json

**Comment by detLAN** [comment]
Guck mal [hier](https://github.com/thkl/hap-homematic/issues/37) und schließe anschließend dieses Ticket 😉

**Comment by mano87** [comment]
Die Integration klappt leider noch nicht zuverlässig mit der HomeMatic Wetterstation. Siehe auch #189 :-)

**Comment by detLAN** [comment]
> Die Integration klappt leider noch nicht zuverlässig mit der HomeMatic Wetterstation. Siehe auch #189 :-)

Dann kann dieses Ticket ja geschlossen werden, wenn es ein weiteres offenes zu diesem Thema gibt.

**Comment by roe1974** [comment]
sollte mit 0.0.58 gehen .... 
Mein HmIP-SWO-B funktioniert 😉

**Comment by mano87** [comment]
@roe1974 
Eingebunden als "HomeMaticThermometerAccessory" oder als "HomeMaticWeatherStationAccessory"? 

Für den HmIP-SWO-PR kann ich das leider nicht bestätigen. Hier wird weiterhin die Temperatur nur mit 0.0 Grad angegeben.

**Comment by roe1974** [comment]
Ja ... als "HomeMaticThermometerAccessory" ... Temp und Hum passen bei mir ....

**Comment by gitalexa** [comment]
wird hier behandelt:
https://github.com/thkl/hap-homematic/issues/37
