### ISSUE TITLE
Unterstützung für HmIPW-DRI16 / 32 sowie DRBL4 geplant?

### ISSUE THREAD

**Issue by spaggi2** [thkl/hap-homematic#337]
**Describe the solution you'd like**
Ich würde mir eine Unterstützung für HmIPW-DRI16 und HmIPW-DRI32 wünschen, in meinem Use Case als StatelessProgrammableButton. Hiermit lassen sich z.B. "dumme" Lichstschalter per Kabel in Homematic einbinden

https://www.homematic-ip.com/produkte/detail/homematic-ip-wired-eingangsmodul-32-fach.html

Des Weiteren gibt es mit dem DRBL4 einen 4-fachen Rolladenaktor. Auch hier wäre eine Unterstützung fantastisch!

https://www.homematic-inside.de/hardware/jalousie-rollladenaktor-hmip-wired-4-fach-hutschiene

Vielen Dank!

**Comment by spaggi2** [comment]
Sorry, ich bin zu blöd. Die Geräte werden unterstützt, ich musste nur meine HAP neustarten.

**Comment by thkl** [comment]
Kann sein, das diese nicht angezeigt wurden, weil sie erst neu aufgenommen wurden. Das Caching Problem wurde mit der aktuellen .58 Version beseitigt.
