### ISSUE TITLE
Nicht unterstütze Geräte HmIP-SWD / HmIP-STH

### ISSUE THREAD

**Issue by MaLi812** [thkl/hap-homematic#34]
Danke für dieses prima Addon. Das ist für mich eine echte Alternative zum Homebridge-homematic Plugin.
Was ich mir noch wünschen würde, wäre die Unterstützung des Wassersensors HmIP-SWD. Außerdem wird bei mir der Homematic IP Temperatur- und Luftfeuchtigkeitssensor HmIP-STH als Thermostat erkannt. Das ist Homebridge-homematic Plugin zunächst auch so, allerdings ist es dort durch Änderung der Config möglich, das Gerät nur zu Anzeige der Temperatur und Luftfeuchte zu zwingen : 
  "services": [
    {
      "type": "HmIP-STH:HEATING_CLIMATECONTROL_TRANSCEIVER",
      "service": "HomeMaticHomeKitThermostatWeatherServiceIP"
    }
  ]
Vielleicht ist dies im Haus-homeatic Addon ja analog machbar. 

Danke und viele Grüße
MaLi

**Comment by thkl** [comment]
Wenn ich die Doku zu dem Ding so anschaue wirkt das auf mich wie ein Thermostat ?

HEATING_CLIMATECONTROL_TRANSCEIVER hat die Datenpunkte

ACTUAL_TEMPERATURE
HUMIDITY

ok das wäre ein Temperatur Sensor, aber dazu kommen:

BOOST_MODE,CONTROL_MODE,SET_POINT_TEMPERATURE was wiederum Thermostat Datenpunkte sind.

Für den HmIP-SWD muss ich den LeakService etwas erweitern aber das ist kein Problem.

**Comment by fighterzg6** [comment]
Wäre es möglich eine Wetterstation HMIP swo b zu integrieren?

**Comment by thkl** [comment]
Welche Typenbezeichnung hat die Wetterstation (HmIP-....)

**Comment by roe1974** [comment]
Hallo Thomas

HmIP-SWO-PR (Pro)
HmIP-SWO-PL (Plus)
HmIP-SWO-B (Basic)

Basic habe ich selber und könnte ich testen.....

lg RIchard

**Comment by fighterzg6** [comment]
HmIP-SWO-B (Basic) Genau diese

**Comment by thkl** [comment]
Es wäre super, wenn die Issues nicht vermischt würden ;) sonst komme ich nicht hinterher was erledigt ist und was nicht .. deswegen der neue für die Wetterstation

**Comment by MaLi812** [comment]
> Wenn ich die Doku zu dem Ding so anschaue wirkt das auf mich wie ein Thermostat ?

Stimmt auch. Allerdings hat man beim Homebridge-homematic Plugin die Wahl, wie man es einsetzt. Entweder als als Thermostat oder als kombinierten Temperatur- und Luftfeuchtesensor (dann komplett ohne Thermostatfunktion)  Für Leute, die damit keine Heizung steuern ist das, finde ich und laut Homematic-Forum auch noch viele andere, übersichtlicher in HomeKit. Sollte nur eine Anregung sein, ich finde die Option im  Homebridge-homematic Plugin sehr gut. 

Beim Leak-Sensor wird auch beim Homebridge-homematic Plugin nur der Datenpunkt WATERLEVEL_DETECTED angezeigt. Das fände ich hier auch eine prima Sache und das würde mir auch reichen.

Das CCU-Addon läuft jetzt bei mir mir auf einem pivccu3 seit einem Tag absolut fehlerfrei, stabil  und sehr flott. Wirklich toll! Danke dafür. 

Vielleicht noch eine kleine Anregung: Beim ersten Start des Addon startet dieser wunderbare Assistent. Prima wäre, wenn man ihn später auch noch einmal starten könnte (ich hab zumindest nicht gefunden wie das auch bisher schon gehen könnte). Das hätte mir bei der Einrichtung einige Mühe erspart.

Viele Grüße
MaLi

**Comment by thkl** [comment]
Ok, den HmIP-STH auch als einfaches Thermometer ist kein Problem.

Da ich für alle Geräte ja einen Konfigurationsdialog habe, werde ich einfach eine Option einbauen, wann der LeakSensor auslösen soll bei MOISTURE_DETECTED oder WATERLEVEL_DETECTED


Und der Start Wizzard kommt nur solange nicht mindestens 1 Gerät eingerichtet ist.
Da der auch weniger Optionen für die Geräte kennt, ist er wirklich nur für die erste Einrichtung gedacht. Die nachträgliche Aufnahme von Geräten sollte ja, wenn die Instanzen für die Räume da sind, auch recht einfach gehen. GGf könne ich im "Gerät hinzufügen" Dialog noch den Raum einbauen, das man da auch filtern kann. Der normale Suchen Filter geht nach Device und Kanalname

**Comment by MaLi812** [comment]
> GGf könne ich im "Gerät hinzufügen" Dialog noch den Raum einbauen, das man da auch filtern kann. Der normale Suchen Filter geht nach Device und Kanalname

Das würde tatsächlich schon reichen. Es war auch absolut nicht als Kritik, sondern nur als Anregung gedacht. Mir wurden bei der Geräteeinrichtung (etwa 50 Geräte) 31 Auswahlseiten im Dialog angezeigt. Bis ich da alle meine Geräte gefunden hatte und jedesmal, hat es schon eine Zeit gedauert. Mit einer Filterfunktion würde das fast genauso gut, wie mit dem Assistenten gehen.

**Comment by thkl** [comment]
Ähm es gibt einen Filter direkt über der Liste:

![image](https://user-images.githubusercontent.com/884355/80865615-eeeb6080-8c8a-11ea-9262-857766ef9cc9.png)

Und die Liste ist sortierbar in dem man auf die Spaltenüberschriften klickt ;)

**Comment by MaLi812** [comment]
Die Filterfunktion hab ich erst benutzt, als ich noch fehlende Geräte am Schluss einzeln hinzufügen wollte. Da ich zum Testen ganz am Anfang nur ein Gerät eingerichtet hatte, war der Assistent weg und dann bin ich ohne zu Filtern einfach die ganze Liste durch, um auch alle meine Geräte zu erwischen. Daher mein Vorschlag, dass der Assistent möglicherweise auch noch später aufrufbar sein könnte. Einzelne Geräte gezielt einzurichten geht mit der jetzigen Version tatsächlich superfix, wenn man alle hintereinander einrichten möchte, ist der Assistent vermutlich das schnellere Werkzeug. 

Der Wassersensor HmIP-SWD ist jetzt auch schon eingebunden und in Funktion :-). Danke!!!
