### ISSUE TITLE
Kopplung per QR Code nicht funktional, per Pin Code schon

### ISSUE THREAD

**Issue by JensBonse** [thkl/hap-homematic#342]
Hab's rausgefunden!
Die Kopplung **_darf nicht_** per QR Code erfolgen, sondern unbedingt per PinCode.

_Originally posted by @akula3 in https://github.com/thkl/hap-homematic/discussions/338#discussioncomment-288939_

**Comment by thkl** [comment]
Ja ich weiß. Ich hab aber keinen Schimmer warum sich das so verhält. Zumal ich bei anderen Instanzen nix anders mache.

**Comment by JensBonse** [comment]
Das heißt es funktioniert nur bei der default Instanz nicht, bei den anderen Instanzen aber schon?

**Comment by thkl** [comment]
Jap

**Comment by JensBonse** [comment]
Naja, da schreibst du das default ja klein. Also keines d.
Ansonsten fangen alle Instanzen mit Großbuchstaben an.
Da war doch was bzgl. der Groß- und Kleinschreibung.

**Comment by thkl** [comment]
Was sein kann, ich erzeuge die default immer dynamisch solange keine Geräte da sind. Und dann ändert sich die pin jedesmal. 
Das könnte es sein.  Aber ich wollte die eh mal ausblenden.  
Ist eh nur das Sammelbecken.

**Comment by JensBonse** [comment]
OK, ich nutze die 'default' um da HomeKit gerate rein zu packen, die eher administrativer Art sind.
Muss ich das ändern, oder bleibt die funktional?

**Comment by thkl** [comment]
Die bleibt.  Wenn wird sie nur angefasst wenn sie leer ist.

**Comment by JensBonse** [comment]
TOP!
Dann kann man den Issue schließen, oder du behälst ihn als reminder ;)

**Comment by thkl** [comment]
Lass den mal offen.

**Comment by meistermolli** [comment]
Habe im Raum Default immer meine Hilfs Schalter / Variablen abgelegt.
So sind die immer schön gesammelt an einer stelle.

Zudem Habe ich noch einen Raum in Homekit angelegt der heisst STOP mit einem Hintergrundbild mit so einem Stop Männchen. Den lege ich jedem meiner Nutzer auch so an und sage Ab hier Finger weg! :-D

Hinter diesem Raum kommt bei mir dann 

STOP
Standardraum (Hue Bridge) - mit allen Hue Tastern
Default HAP
Default Homebridge
Default ioBroker

gruß meistermolli
