### ISSUE TITLE
Probleme bei der Installation [0.0.14]

### ISSUE THREAD

**Issue by It0w** [thkl/hap-homematic#345]
RaspberryMatic 3.55.5.20201226

Hallo,

ich hatte ein ähnliches Problem wie in https://github.com/thkl/hap-homematic/issues/323

nur das bei mir anscheinend die erforderlichen Dateien/Ordner vorhanden waren.

![hap](https://user-images.githubusercontent.com/13597836/105063537-2057c680-5a7c-11eb-9d82-2a1403733791.jpg)

Nach mehrmaligen erfolglosen versuchen die 0.0.14 zu installieren habe ich die 0.0.12 probiert die auf Anhieb funktionierte.

Ich hoffe die Information hilft anderen mit ähnlichen Problem.

**Comment by mikulcak** [comment]
Ich hatte mit der 0.0.14 genau das gleiche Problem, leider geht es auch mit der 0.0.12 bei mir nicht. 

Ich sehe die Ordnerstruktur wie oben beschrieben (also die node_modules in /`usr/local/addons/hap-homematic/node_modules` sind heruntergeladen, etc.), aber wenn ich in Systemsteuerung auf HomeKit klicke, bekomme ich nur "This site can’t be reached homematic-raspi refused to connect." Man sieht, dass sehr kurz eine Seite mit "HTTP-Version" und "HTTPS-Version" aufgerufen wird, dann kommt die automatische Weiterleitung, die zur Fehlermeldung führt. 

Ich benutze die letzte Version von raspberrymatic, 3.55.10.20210213.

**Comment by thkl** [comment]
was passiert bei folgendem Shell Befehl auf der RM ?

```
node /usr/local/addons/hap-homematic/node_modules/hap-homematic/index.js
```

Da sollte sich zumindest etwas logging zeigen wenn der Homekit Daemon startet.
GGf crasht er ja aber das wird angezeigt.

**Comment by mikulcak** [comment]
Da kommt die Meldung, dass die Ports schon belegt sind, also muss der daemon schon laufen. Das hat mich dann auf die rettende Idee gebracht: Einfach die Firewall des raspberrymatic öffnen - tada! Danke für die Hilfe, die Sache wäre also gelöst!
