### ISSUE TITLE
Support für HmIP-DBB als HomeMaticDoorBellAccessory

### ISSUE THREAD

**Issue by ElHanko** [thkl/hap-homematic#346]
Hallo,

Kann im Service HomeMaticDoorBellAccessory die HmIP-DBB unterstützt werden?

Ich konnte es über das Webinterface nicht auswählen, so habe ich es in der config.json einfach mal getestet, ob ich dem Gerät den Service zuordnen kann.
Hat nicht funktioniert, der Log meint dazu:

[Wed Jan 20 2021 15:51:09 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Türklingel-EG-Windfang:1 is HomeMaticDoorBellAccessory
[Wed Jan 20 2021 15:51:09 GMT+0100 (CET)] error - [HAP Server] [Server] unable to initialize Türklingel-EG-Windfang:1
[Wed Jan 20 2021 15:51:09 GMT+0100 (CET)] error - [HAP Server] [Server] requested ServiceClass HomeMaticDoorBellAccessory did not provide a service for KEY_TRANSCEIVER

Was der Service KEY_TRANSCEIVER mir sagen soll, kann ich leider nicht beantworten, da da mein Latein am Ende ist.

Gruß
Mathias

**Comment by thkl** [comment]
ok
