### ISSUE TITLE
Support for New device Praesenzmelder HmIP-SPI

### ISSUE THREAD

**Issue by Elbe122** [thkl/hap-homematic#347]
I would love to see support for the HmIP-SPI also.
[HmIP-SPI.json.zip](https://github.com/thkl/hap-homematic/files/5852423/HmIP-SPI.json.zip)

**Comment by thkl** [comment]
The channel 1 (PRESENCE_DETECTION_STATE) from an HmIP-SPI is currently supported by the HomeMaticPresenceAccessory .... so it should work well
