### ISSUE TITLE
Keine laufende HAP-Instanz mit CCU3

### ISSUE THREAD

**Issue by Feddero** [thkl/hap-homematic#348]
Hallo und vielen Dank erst einmal für dieses super Addon!
Ich habe eine CCU3 mit diversen HomematicIP-Wired Komponenten, darunter Thermostate, Eingangsmodule, Ausgangsmodule, Rolladenaktoren (auf Hutschiene) und Präsenzmelder.

Ich habe nun erfolgreich das Addon installiert, bekomme jedoch keine laufende HAP-Instanz angezeigt, wenn ich in die Konfiguration gehe.
Woran könnte das liegen?
Ich habe alle Ports offen, wenn ich meine CCU auf Werkseinstellungen zurücksetze und HAPinstalliere, funktioniert alles bestens, sobald ich dann das Backup einspiele und HAP neu installiere, der gleiche Fehler.

Könnte das an meinen Geräten liegen, werden diese nicht unterstützt?

Vielen Dank!

**Comment by thkl** [comment]
Das klingt wild .. Ggf bringt eines der Geräte das HAP Addon zum Crash ... auf der CCU unter /etc/config/addons/hap-homemeatic werden die Konfigurations und Cache Daten angelegt. Mal bitte dieses Verzeichnis zippen und hier an den Issue dran hängen. (oder mir per Mail schicken - Adresse stehe in jedem Source File hier oben drin)

**Comment by Feddero** [comment]
Kann auf die Unterordner anscheinend leider nicht zugreifen, 403-Forbidden.

**Comment by thkl** [comment]
Ok ein Backup über das HAP WebUI tut es auch. Da sind auch alle wichtigen Files drin

**Comment by Feddero** [comment]
[ccu3-webui-2021-01-22 (1).log](https://github.com/thkl/hap-homematic/files/5857661/ccu3-webui-2021-01-22.1.log)

Das HAP WebUI lässt mich keine Log-Datei schreiben komischerweise. Angehangen habe ich die Log der CCU.
Ich starte die CCU einmal neu, eventuell kann ich dann eine Log schreiben..

**Comment by thkl** [comment]
Das nützt leider nichts Wenn das UI kein Log oder Backup anlegt ist wirklich was komplett schief ... ggf müsstest du doch mal per FTP im obigen Pfad schauen und die Daten da raus kopieren. Der Pfad ist nicht per Browser erreichbar.

**Comment by Feddero** [comment]
[HAP.zip](https://github.com/thkl/hap-homematic/files/5857818/HAP.zip)
Ok habe die Dateien mit Filezilla herunterladen können. Kannst du damit etwas anfangen?

**Comment by thkl** [comment]
hmm die device.json Datei (diese ist der Cache alle Geräte) ist leer. Das sollte eigentlich nicht passieren.
Ich vermute mal das HAP einen Fehler beim Lesen der Geräte macht.Das sollte eigentlich nicht passieren. Wenn es Dir nichts ausmacht, schick mir mal bitte ein CCU Backup (th.kluge@me.com) (bitte nicht hier anhängen)
