### ISSUE TITLE
Heizung die „aus“ ist, lässt sich nicht via HomeKit wieder einschalten

### ISSUE THREAD

**Issue by tornenen** [thkl/hap-homematic#349]
Wenn ich die Heizung ausschalte, egal ob manuell oder per Automation, lässt sich diese nicht mehr via HomeKit einschalten. Ich muss dann erst wieder auf die CCU Webseite gehen. Anbei mal ein Video zur besseren Erklärung. Ich habe Heizgruppen die ich an HomeKit weitergebe. Nicht einzelne Thermostate. Die Heizung befindet sich dann im MANU Modus.

https://imgur.com/a/iiHEwgA

**Comment by roe1974** [comment]
muss an der Gruppe liegen ... bei einzelnen Thermostaten funktioniert es ...

**Comment by tornenen** [comment]
Hast du Recht. Hab es gerade getestet. 
Wie löst du das wenn du in einem Raum mehrere Thermostate hast? Habe im Wohnzimmer z.B. 3 Stück.

**Comment by thkl** [comment]
Kann mal bitte jemand checken ob folgendes funktioniert:

* Temp manuell über HomeKit wählen
* Heizung aus machen
* Heizung wieder einschalten .... 

Zum Einschalten muss ich eine Manuelle Temperatur angeben, die kann ich aber erst setzen wenn einmal eine gesetzt wurde.

**Comment by blackbasket** [comment]
Hallo Thomas,

bei mir scheitert es am wieder einschalten. Das musste ich jetzt über die EASY App machen. Da springt er bei mir immer zurück auf aus.

**Comment by tornenen** [comment]
Bei mir das gleiche wie bei @blackbasket

**Comment by roe1974** [comment]
@blackbasket @tornenen ..... mit Heizgruppe(n) oder einzel Thermostate in der CCU ?

**Comment by tornenen** [comment]
Bei mir Heizgruppen. Bei einzeln Funktioniert es.

**Comment by blackbasket** [comment]
Bei mir ist eine Gruppe... lg


Am 27.01.2021 um 16:53 schrieb Richard <notifications@github.com>:

﻿

@blackbasket<https://github.com/blackbasket> @tornenen<https://github.com/tornenen> ..... mit Heizgruppe(n) oder einzel Thermostate in der CCU ?

**Comment by roe1974** [comment]
Dachte ich mir ... liegt an den Heizgruppen .. ich habe keine, da funktioniert es.
