### ISSUE TITLE
HmIP-SRH wird nicht unterstützt

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#35]
Vielen Dank für dieses super Projekt. Auf so eine einfache Integration von Homematic in HomeKit hab ich schon lange gewartet. Das UI ist Dir wirklich sehr gut gelungen - auf das Wesentlichste beschränkt und damit sehr übersichtlich.
 
Die HmIP Fenster-/ Drehgriffkontakte werden aktuell nicht aus der CCU übernommen.

Hier noch ein kleiner Schönheitsfehler.
<img width="342" alt="Bild1" src="https://user-images.githubusercontent.com/64675966/80855305-7b246600-8c40-11ea-826a-f0637d667c9d.png">

**Comment by thkl** [comment]
Das mit dem Icon ist schon beseitigt.  
Welche Typenbezeichnung haben die Drehgriffkontakte ? HmIP-.....

**Comment by detLAN** [comment]
Sie Betreff ;) HmIP-SRH

**Comment by thkl** [comment]
Ach, geht der Kontakt ?

**Comment by detLAN** [comment]
Nein, habe aus Unwissenheit diesen issue geschlossen (bitte wieder öffnen)

> Das mit dem Icon ist schon beseitigt.
Schön wäre wenn die Einstellung gespeichert wird.

> Welche Typenbezeichnung haben die Drehgriffkontakte ? HmIP-.....
HmIP-SRH

**Comment by detLAN** [comment]
Integration hat funktioniert - Danke dafür!
Kann HomeKit zwischen geschlossen, gekippt und geöffnet unterscheiden? Aktuell wird für gekippt und geöffnet lediglich geöffnet dargestellt - sowohl in Home App als auch in Eve App. Die Darstellung ist zwar nicht falsch, bei gekippt ist das Fenster ja offen, aber eine Unterscheidung wäre schön.

**Comment by thkl** [comment]
Nein es gibt nur Kontakt offen oder Kontakt zu

![image](https://user-images.githubusercontent.com/884355/80865760-b5672500-8c8b-11ea-85ba-9b31b91c6408.png)
