### ISSUE TITLE
Probleme mit HmIP-FBL 

### ISSUE THREAD

**Issue by bount12** [thkl/hap-homematic#351]
Hallo!
Sobald ich über Homekit versuche meine Jalousien zu öffnen oder zu schließen, passieren immer durchaus kuriose Dinge. So bleib die Jalousie nicht an ihren Endpunkte stehen sondern wartet dort kurz und fährt anschließend wieder auf oder ab. So steht die Jalousie nach dem ich versucht habe sie zu öffnen oder schließen meist an einer randomisierten Position.
Hat sonst auch noch jemand diese Problem oder liegt das nur an mir?

Besten Dank für die Hilfe im Voraus!

**Comment by ChrWi** [comment]
Hallo @bount12,
da musst du schon mehr Infos liefern (log files, ...) Oder hat sich das Thema mittlerweile ergeben?
