### ISSUE TITLE
Variable Update auf alle Zustände

### ISSUE THREAD

**Issue by JensBonse** [thkl/hap-homematic#352]
Hallo Thomas,

ich habe ein eigenes Program bzgl. des Triggerns des Variablen updates.
Wollte mir aber auch mal deine automatische Generierung anschauen.
Da ist mir aufgefallen, dass du nur den ersten Wert der Variable auf Aktualisierung überprüfst.

Wenn ich z.B. eine boolean Variable Anwesenheit habe mit Anwesend = true und Abwesend = false, dann schaut dein Program nur nach : 'Anwesenheit' bei 'Anwesend' 'bei Aktualisierung auslösen'

Wenn die Variable nun aber auf den Wert Abwesend gesetzt wird, dann würde das Program ja nicht auslösen und die Variable in nicht HomeKit aktualisieren, oder?

Das könnte das Problem mit den Alarmanlagen Variablen erklären, was einige hier berichten, das es teilweise länger dauert, bis die Aktualisierung da ist.

Du müsstest also bei:
- boolean auf true und false auf aktualisierungen testen
- choice auf alle choices auf aktualisierung testen
- number auf aktualisierung zwischen min und max Wert der variable testen
- string gehen nicht in HomeKit ;)

Wird natürlich dem entsprechend länger das Program ;)

Wäre auch toll, wenn man den Namen des Programs irgendwo konfigurieren könnte.

**Comment by thkl** [comment]
Ich war bisher davon ausgegangen das "Bei Aktualisierung" auslöst wann immer die Variable beschrieben wird ... egal mit welchem Wert und auch wenn der Wert gleich dem alten Wert ist.  Und "bei Änderung" wird ausgelöst wenn der Wert sich wirklich ändert. Und das die beiden Auslösekriterien unabhängig vom Prüfwert sind.

Ist dem nicht so ? Dann erklärt das natürlich warum das Problem besteht. 
Mein Test der Alarm Variablen Funktion schaut so aus und funktioniert problemlos:

![image](https://user-images.githubusercontent.com/884355/106353630-38d1a780-62ec-11eb-8b57-1febb8732b52.png)


![image](https://user-images.githubusercontent.com/884355/106353643-4ab34a80-62ec-11eb-9373-5ed439b91119.png)

**Comment by JensBonse** [comment]
Ich bin genau vom Gegenteil ausgegangen ;)
Muss das mal genau testen, wann ein Program wirklich ausgeführt wird.

**Comment by JensBonse** [comment]
@thkl Habe es für ein Choice Feld getestet. Gehe davon aus, das es sich dann für alle gleich verhält.
Das Program reagierte nur, wenn der entsprechend ausgewählte Wert geändert/aktualisiert wurde. Wird ein anderer Wert ausgewählt, wird das Program nicht ausgeführt.
Daher wäre es toll, wenn du die Generierung des HomeMatic Programs entsprechend anpassen könntest.

**Comment by thkl** [comment]
ok das kann ich anpassen ...

**Comment by JensBonse** [comment]
Hat es leider noch nicht in die .59 geschafft. Kommt aber noch, oder?

**Comment by thkl** [comment]
Ah ja, das war schon zu weit runter geschrollt :)

Ja mach ich noch.

**Comment by thkl** [comment]
Das hier : 
![image](https://user-images.githubusercontent.com/884355/110206186-88236e80-7e7c-11eb-9040-eaf5b2dc712b.png)

![image](https://user-images.githubusercontent.com/884355/110206170-6f1abd80-7e7c-11eb-8228-f155be4693dc.png)

ergibt jetzt:

![image](https://user-images.githubusercontent.com/884355/110206141-59a59380-7e7c-11eb-8901-01301b15c731.png)

**Comment by JensBonse** [comment]
Hallo Thomas,

reicht es bei den Range nicht nur eine Bedingung zu bauen?
Ich nehme da z.B. nur 'im Wertebereich' -> 'größer oder gleich "Minimal-Wert"' -> bei Aktualisierung auslösen

**Comment by thkl** [comment]
Du meinst so : 
![image](https://user-images.githubusercontent.com/884355/110308844-ea0ce100-8000-11eb-9d9d-bcb09daa9f6d.png)

**Comment by JensBonse** [comment]
<img width="619" alt="Bildschirmfoto 2021-03-08 um 11 27 03" src="https://user-images.githubusercontent.com/15381432/110309157-4839c400-8001-11eb-8cc4-510c2d041e6e.png">
Dache so, wobei die -1 dann der Minimal-Wert der Variable ist.

**Comment by thkl** [comment]
dann würde es auch auslösen wenn es über dem Maximalwert ist .. allerdings weiss ich nicht ob man die Variable > Max setzen kann

**Comment by JensBonse** [comment]
Oh, du hast Recht. Man kann Variablen Werte außerhalb der definierten Range setzen. Das ist ja blöd...
Im Programm kannst du aber nur den Min oder Max Wert nutzen zum testen. Daher würde ich das schon so machen, wie vorgeschlagen. Wenn die Werte außerhalb des gültigen Bereiches sind muss der User dann die Variablen definition anpassen. 
Anders geht es denke ich leider nicht.

**Comment by thkl** [comment]
ok also kann ich quasi die <= Zeile einfach wegwerfen, denn bei meiner Zeile oben würde ja DutyCycle = 100 nicht auslösen

**Comment by ChrWi** [comment]
@thkl @JensBonse ist das Thema erledigt?
