### ISSUE TITLE
Temperatur wird nicht angezeigt (HMIP-WTH-2)

### ISSUE THREAD

**Issue by MarcoLanghans** [thkl/hap-homematic#353]
Hallo zusammen, 

wenn ich meinen Thermostate einbinde bekomme ich nun die Eingestellte SOLL Temperatur angezeigt und nicht die IST Temperatur. Beziehungsweise es schein ein aufrunden oder abrunden stattzufinden, da ich auch nun auch Geräte gefunden haben die z.B. 23.4 haben und angezeigt wird dann 23.5. Das Gerät ist ein HMIP-WTH-2 und ich habe keine Einstellungen gefunden dies zu ändern.

**Comment by gerd2005** [comment]
Hi, redest du jetzt von den Thermostaten an sich, oder von Apples HomeApp?

**Comment by gerd2005** [comment]
Ich gehe mal davon aus, dass du die Home-App meinst. Aber das ist m.E. so. Die aktuelle Temperatur wird jedoch nicht übertragen.

**Comment by MarcoLanghans** [comment]
Hi, ich rede von der Home App.
Habe eben nochmal geschaut dies sieht so aus in der Home App
![IMG_1950](https://user-images.githubusercontent.com/8319162/106256069-1ae84200-621b-11eb-8544-96b4b403bd8e.PNG)

und so in der CCU
![2021-01-29_10-13-41](https://user-images.githubusercontent.com/8319162/106256186-3fdcb500-621b-11eb-80d4-b1e7fe4fd1b1.png)

dies passt irgendwie nicht.

**Comment by blackbasket** [comment]
Hi, was genau passt da nicht? Ich bin blind…

**Comment by gerd2005** [comment]
Ah ich dachte, du meinst diesen Bildschirm:
![3A13A535-4E5B-4FB8-BED6-899513E31F2A](https://user-images.githubusercontent.com/72799068/106258063-a82c9600-621d-11eb-96a6-3ab34c3dc02d.jpeg)

Aber in der Ansicht die du gerade geschickt hast, wird die aktuelle Temperatur m.E. angezeigt. Die IST-Temperatur ist 23,5 und die SOLL-Temperatur ist 23. Das mit dem Runden ist die Sache von Home-Kit (Works as Designed)

**Comment by MarcoLanghans** [comment]
echt dies ist ja blöd, aber wenn es so im HomeKit ist dann kann man da nix machen :-(

**Comment by thkl** [comment]
In der Home App wird die Ist temp in dem kleinen Kreis oben angezeigt, und die Soll Temp unten auf dem Textlabel.
Bzw wird das oben in der Home App noch mal zusammengefasst.

**Comment by ChrWi** [comment]
Thema ist denke ich geklärt
