### ISSUE TITLE
Hap Homematic 0.0.58 läuft unter raspberrymatic 3.55.5.20201226 lässt aber kein Backup einspielen

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#354]
Hi,

habe eben auf die raspberrymatic Version 3.55.5.20201226 geupdatet.

Vorher natürlich Backups gemacht.

Nach dem Update ist in HAP Homematic nichts mehr drin.
Das Backup lässt sich auswählen aber es wird nicht eingespielt.

Addon neu installieren und nochmal versuchen?
Oder wird das nicht auf dieser raspberrymatic Version laufen?

Danke und Gruß

**Comment by meistermolli** [comment]
Deinstalliert + Neuinstallation über 0.0.14 und dann wurde auch das Backup wieder erkannt!

Läuft wieder

**Comment by meistermolli** [comment]
Leider zu früh gefreut. 

Keins der Geräte Antwortet.

keine Antwort!

**Comment by thkl** [comment]
irgendwelche Auffälligkeiten in /var/log/messages oder /var/log/hap-homematic.log

**Comment by meistermolli** [comment]
Nichts gesehen. Habe nochmal Raspberrymatic und HAP neu installiert.
Dann Backup eingespielt, ging leider immer noch nicht.

Habe dann mal eine Instanz aus Home gelöscht und neu hinzu gefügt. Diese Ging dann direkt mit dem Testgerät.

Also 23 Instanzen "kurz" aus Homekit Löschen und in HAP deaktivieren.
Dann neu hinzugefügt und Geräte wieder veröffentlicht, läuft jetzt wieder einwandfrei.

Habe mal das Riesen Log durchgerollt aber nirgendwo etwas gesehen, das wie ein Fehler aussieht.
Vermute hier hat Homekit irgendwas nicht durch gelassen?

Auch ein Neustart der Geräte und Steuerzentralen hatte leider nicht funktioniert.
(ich sollte wohl vor Updates mal die ganze SD Karte kopieren. Nicht das ich mal doof da stehe beim Updaten :-P)

Merci und gute nacht.

**Comment by meistermolli** [comment]
Guten morgen .. gestern leider ein Schreckmoment.

Nach Neustart der Raspberrymatic waren alle Instanzen und Geräte in HAP verschwunden.
Es kam der Begrüßungsbildschirm von der Neuinstallation.

Backup Lässt sich wieder nicht einspielen.
leider keine Crashfiles vorhanden.

Cache Löschen brachte auch nichts und ältere Backups leider auch nicht.

**Comment by meistermolli** [comment]
Guten morgen .. gestern leider ein Schreckmoment.

Nach Neustart der Raspberrymatic waren alle Instanzen und Geräte in HAP verschwunden.
Es kam der Begrüßungsbildschirm von der Neuinstallation.

Backup Lässt sich wieder nicht einspielen.
leider keine Crashfiles vorhanden.

Cache Löschen brachte auch nichts und ältere Backups leider auch nicht.

**Comment by thkl** [comment]
gibt es in /etc/config/addons/hap-homematic noch eine config.json ? Da stehen alle Einstellungen drin .. 
Wenn ja mal bitte hier anhängen ggf ist die ja kaputt ...  Die kann auch aus dem letzten Backup (das ist ein tar.gz) genommen und dort hin kopiert werden. Wenn das schief geht mal das Backup hier anhängen ggf. ist das File ja schon kaputt.

**Comment by meistermolli** [comment]
Das habe ich leider zu spät gelesen.

Habe wieder:
die raspberrymatic software drüber installiert
hap homenatic deinstalliert und wieder installiert.
Jetzt geht das Backup wieder.
Aber muss wieder die Instanzen neu hinzufügen in Homekit.

Werde dann jetzt erstmal nochmal die CCU neu Starten, und sehen was passiert.

Wenn das ganze nochmal abschmiert, dann sichere ich die config Datei von hier mal: /etc/config/addons/hap-homematic
Ansonsten könnte ich dir die Config aus dem aktuellen schicken?

**Comment by thkl** [comment]
nope ich muss ja Deinen Zustand erzeugen, wo das Backup nicht zurückzuspielen geht also brauche ich die config aus /etc/config/addons/hap-homematic für die Stelle, wo sich das Backup nicht einspielen lässt ...

**Comment by meistermolli** [comment]
Habe mit der raspberrymatic 3.55.5.20201226 noch weitere Probleme mit einem BWTH gefunden heute.
Vielleicht kam der Bug auch von der Seite? (Obwohl es die ja schon eine weile gibt)

Bin zurück auf Raspberrymatic 3.53.34.20201121.

**Comment by thkl** [comment]
ok, sollte das noch mal auftreten wäre ich an den LogFiles bzw den Daten aus obigem Config Folder interessiert. Ich habe gestern mal ein paar Versuche in einer virtuellen Maschine gemacht. Normalerweise werden im Backup der CCU die Konfig Daten mit gespeichert. Die eigentlichen ausführbaren Dateien des Plugins nehme ich vom Backup aus, weil das das CCU Backup aufblähen würde. Diese werden beim Start der CCU ggf von alleine nachinstalliert. (dauert natürlich einen Moment)

**Comment by meistermolli** [comment]
Alles klar.

**Comment by meistermolli** [comment]
3.55.10.20210213
hat nun die Geräteseitigen Probleme behoben und hier war auch kein neues einspielen von HAP mehr notwendig.
