### ISSUE TITLE
Authentifizierung greift nicht

### ISSUE THREAD

**Issue by marvingrieger** [thkl/hap-homematic#355]
Hallo,

ich habe die Einstellung _CCU-Anmeldung benutzen_ aktiviert.
Basierend auf der Beschreibung hätte ich erwartet, dass die Konfigurationsseite ohne gültige Session gar nicht aufrufbar ist.

Dies ist jedoch nicht der Fall, ich kann die Seite auch ohne Session problemlos aufrufen.

Das die Einstellung generell zieht merke ich an dem Herunterladen der Log-Files.
Dieses ist dann nur noch möglich, wenn eine gültige Session-ID im Parameter enthalten ist.
Andernfalls kommt der Hinweis _unauthorized_.

Beste Grüße

**Comment by thkl** [comment]
Ja, das kann ich so nachvollziehen. Ich schau mal, wo ich da was kaputt gemacht habe.
