### ISSUE TITLE
Heizung Temperatur Siri bleibt nicht erhalten

### ISSUE THREAD

**Issue by mike4president** [thkl/hap-homematic#356]
Hallo Thomas, nachdem ich nun mehrere Monate wieder beim AccessPoint war, kehre ich reumütig zu Raspberrymatic zurück, da mich wieder die gleichen Dinge und Einschränkungen beim AccessPoint nerven. 

Also, was habe ich gemacht...natürlich erstmal wieder HAP Homematic eingerichtet... was sonst. dabei stoße ich aber auf ein kleines Problem, was hoffentlich kein Bug ist.

Wenn ich meine Thermostate alle in HomeKit eingebunden habe (HmIP-eTRV-2) und per Siri die Temperatur ändere, springt das Thermostat nach ein paar Minuten immer wieder zurück zu der im Zeitplan vorgegeben Temperatur. Ich möchte im Grunde den Zeitplan im Thermostat nutzen, aber wenn ich schon mal zu Hause bin auch individuell die Temperatur wieder erhöhen können per Siri. Was mache ich falsch? Ich hab die Heizung sowohl in den manuellen Modus versetzt, als auch im Automatik-Modus probiert. 

Was ist eigentlich aus der Zeitplan Programmierung in der Eve App geworden? Konnte die Zeitpläne darüber nicht einstellen, bzw der Menüpunkt wird mir gar nicht angeboten. 

Muss ich die Heizgruppe oder oder das Thermostat in HAP Homematic einbinden oder macht das keinen Unterschied? 

Grüße

Mike

**Comment by mike4president** [comment]
So ist die Heizgruppe bei mir eingerichtet: 


<img width="1201" alt="Bildschirmfoto 2021-02-10 um 11 55 31" src="https://user-images.githubusercontent.com/65063329/107500842-f2573500-6b96-11eb-9856-d07c56a1d362.png">

**Comment by thkl** [comment]
Die Programmierung geht über folgenden Service : 

![image](https://user-images.githubusercontent.com/884355/107669995-9a9df400-6c92-11eb-8c08-509b670dd2b3.png)

Man muss das gewünschte Temperaturprofil auswählen in das geschrieben werden soll. Das geht aber momentan nur mit HM nicht mit HmIP Komponenten, da die Profilerstellung bei HmIP anders ist und ich keine IP Thermostate zum Testen habe ;/ Das ist jetzt nicht trivial zu bauen

**Comment by mike4president** [comment]
Klick... okay. verstanden. Ich hab nur IP Komponenten hier. 

Und hast du einen Ahnung warum, die Temperatur immer wieder auf den Zeitplan zurückspringt nach paar Minuten/Sekunden? 

Hab das jetzt so gelöst, dass ich eine Systemvariabel Anwesen ablesen nutze und die Geo basiert über Homekit schalten lasse, sprich wenn niemand zu Hause Wochenprogramm 1, wenn jemand zu Hause Wochenprogramm 2.

Wenn ich aber zwischendurch die Temperatur über Siri ändern will, hält die geänderte Temperatur nicht lange.

**Comment by mike4president** [comment]
Das mit den Eve Zeitprofilen ist auch nur Schmuck am Nachthemd. Wichtiger wäre mir die Sprachsteuerung

**Comment by thkl** [comment]
Das hängt sicher am Modus des Thermostats. Das setzen der Temperatur via HomeKit erzeugt nur einen Temperatur Setz Befehl ans Thermostat. Wenn das im Auto Modus läuft dann setzt es doch selber wieder die Temperatur zurück oder ? 
Über den Heat/Auto Schalter kann man es in den Manuellen Mode setzen und dann bleibt die Temperatur.

**Comment by mike4president** [comment]
Verstanden, der Nachteil am manuellen Modus ist dann aber, dass die Wochenprofile auf dem thermostat nicht mehr greifen oder? 

Wenn ich im Auto-Modus die Temperatur direkt am Thermostat ändere, bleibt sie trotz Auto-Modus erhalten bis zur nächsten Änderung gemäß Zeitplan. Das wäre auch das gewünschte Verhalten per Homekit.

**Comment by thkl** [comment]
Ja mehr mache ich auch nicht .. ich sende die Temperatur an den Datenpunkt SET_POINT_TEMPERATURE ... 
Was du mal testen könntest: Verhält sich das Thermostat genau so wenn man die Temperatur über das WebUI der CCU setzt.

**Comment by mike4president** [comment]
Habe ich eben probiert. Wenn ich die Temperatur über das WebUI der CCU ändere, bleibt sie trotz Auto-Modus trotzdem erhalten. Sie springt nur zurück, wenn ich sie über Homekit ändere

**Comment by thkl** [comment]
Na mal sehen ob ich rausfinde, das das WeBui da macht

**Comment by mike4president** [comment]
Das wäre bombe... Danke Dir! Wundert mich, dass die anderen hier das Problem noch nicht hatten. Ich habe übrigens das Thermostat selbst in Homekit hinterlegt und nicht die Heizgruppe. Weiß nicht, ob das relevant ist. Fand das nur von der Darstellung in Eve besser

**Comment by thkl** [comment]
Moment, es könnte sein, das die Gruppe einen Event für SET_POINT_TEMPERATURE verursacht und damit die Temperatur wieder zurückgestellt wird.  Wie lange ist der Zeitraum zwischen Setzen der Temperatur und das diese wieder zurück gesetzt wird ?

**Comment by mike4president** [comment]
Hab gerade mal die zeit gestoppt. ca 1:30 Minuten

**Comment by thkl** [comment]
Ok kannst du mal bitte das Debug Log einschalten, und das noch mal testen .. und dann schauen ob nach dem setzen der Temperatur ein SET_POINT_TEMPERATURE Event kommt ? Denn auf diesen setze ich natürlich die Temperatur auf den dort gesendeten Wert. Das wäre der Fall wenn die Temperatur am Thermostat selber oder über webUI etc geändert wird.

**Comment by mike4president** [comment]
Hab ich gemacht 19:17:19 die Temperatur per Homekit geändert. Dann springt sie wieder so 1,5 Minuten später zurück. Es taucht aber kein weiteres SET_POINT_TEMPERATURE Event auf. Also ich hab debug eingeschaltet und dann das log runtergeladen. Hab ich was falsch gemacht? 

[hap-homematic-log-2.txt](https://github.com/thkl/hap-homematic/files/5967640/hap-homematic-log-2.txt)

**Comment by thkl** [comment]
es wird HomeMaticThermostatAccessory verwendet oder ?

**Comment by mike4president** [comment]
<img width="962" alt="Bildschirmfoto 2021-02-11 um 19 34 30" src="https://user-images.githubusercontent.com/65063329/107682142-3b46e080-6ca0-11eb-9fa1-4bc081f80941.png">
<img width="962" alt="Bildschirmfoto 2021-02-11 um 19 34 50" src="https://user-images.githubusercontent.com/65063329/107682150-3d10a400-6ca0-11eb-9f2b-5b59e45bd56d.png">

**Comment by mike4president** [comment]
jep, ist das falsch? Ich hab die Wandthermostate so in HAP angelegt. Die Thermostate an der Heizung wie oben abgebildet und zusätzlich noch die Fenstersensoren

**Comment by thkl** [comment]
es geht um das Gerät 000A1BE9A2639F im Testfall oder ? 

```
[Thu Feb 11 2021 19:17:10 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticRadiatorThermostatAccessory] 000A1BE9A2639F set TargetTemperature 20 °C
```

Einige Zeilen später kommt der Event von der CCU wo die 20 Grad zurück kommen ...
Es schaut wirklich so aus, als ob nach dem Setzen der Temperatur kein weiterer Event eingeht.. 

Es gibt 2 Stellen wo ich die Temperatur zum Gerät schicke. 1x beim setzen via Homekit und einmal wenn man den Modus auf Off bzw zurück stellt. Wird der Modus aber von außen getriggert passiert nichts.

Ich hab leider keine DebugAusgabe im Eventhandler .. das müsste ich mal noch gespächiger machen. Im Log wird es hier gesetzt 

Die Temperatur wird im Thermostat wieder zurückgestellt ? Oder nur in der HomeKit Anzeige ??

**Comment by mike4president** [comment]
Also im Wohnzimmer sind die Thermostate 000A1BE9A2554B, 000A1BE9A2639F in Homekit zugeordnet. 

In der Küche ist ist in HomeKit 000A1BE9A2605E zugeordnet. 

Alle drei bilden bei mir in der CCU eine Gruppe. 

Ich habe Siri gesagt, dass es im Wohnzimmer die Temperatur auf 20 Grad absenken soll. Das tut er dann auch für die ersten beiden. 1,5 Minuten später springen sie zurück. Das gleiche verhalten habe ich aber auch im WC wo nur ein Thermostat ist und das mit der CCU Gruppe übereinstimmt. 

Die Temperatur wird tatsächlich am Heizkörper wie von Zauberhand zurückgesetzt und das wird auch an Homekit gemeldet.

**Comment by thkl** [comment]
Ok nach dem Setzen des 1. thermostats kommen für die anderen auch SET_POINT_TEMPERATURE Events.
Aber ich habe nirgendwo einen weiteren von HomeKit getriggerten Event zum Setzen der Temperatur im Log.
Daher muss ich mal sehen ob das WebUI ggf noch irgend welche andere Magie betreibt.

**Comment by mike4president** [comment]
Also irgend jemand zaubert da in jedem Fall ;-) Danke dir für deine Mühe. Wäre halt nur cool, wenn ich trotz Automatikmodus die Temperatur per Siri anpassen könnte. Der Automatikmodus mit den Wochenprogrammen ist mir recht wichtig.

**Comment by thkl** [comment]
Ok kannst du bitte noch mal den Debug einschalten und die Temperatur anschließend via WebUI für das Gerät 000A1BE9A2639F ändern.

Es gibt da einen Datenpunkt SET_POINT_MODE der kann 0-3 sein, taucht auch als Event auf. Ggf muss ich dem noch eine 1 für manuell mitgeben.

**Comment by mike4president** [comment]
Hab ich gemacht. Hab die Temperatur in diesem Testlauf per WebUI von 21 auf 23 erhöht. 

[hap-homematic-log-3.txt](https://github.com/thkl/hap-homematic/files/5967896/hap-homematic-log-3.txt)

**Comment by thkl** [comment]
ok, da passiert exakt nichts anderes ... und ich bin erst mal etwas ratlos

**Comment by mike4president** [comment]
moment.. jetzt ist er nachdem ich die Temperatur für das eine Thermostat per WebUI von 21 auf 23 ebenfalls selbstständig auf 21 zurückgesetzt... kurze Zeit später aktualisiert sich auch HomeKit... liegt es ggfs daran, dass ich nur ein Thermostat in der Gruppe versuche zu steuern?

Wenn ich im WC das gleiche per WebUI mit der Gruppe (denn da ist nur ein Heizkörper) mache (von 21 auf 23 per WebUI erhöht), bleibt die Temperatur bei 23 erhalten. Habe es mit Siri auch nochmal probiert und von 23 auf 18 gesenkt. Da springt die Temperatur dann leider auf 23 zurück...

**Comment by thkl** [comment]
;) 
war das nicht so, das man immer die Gruppe steuern soll ?

**Comment by blackbasket** [comment]
> Alle drei bilden bei mir in der CCU eine Gruppe. 
> 

Ja, man sollte die Gruppe steuern ;) Aber, wenn ich diesen Satz lese, klingt es für mich danach, dass der Heizkörper in der Küche mit in der Gruppe ist, oder?

**Comment by mike4president** [comment]
Ja, ist er... Also die Temperatursteuerung der CCU per WebUI scheint sich richtig zu verhalten, wenn man die Gruppe steuert. Heißt das, um das gewünscht Verhalten (Auto Modus an und trotzdem Homekit Temperatur ändern) zu erreichen, dass ich definitiv die Heizgruppe per HAP Homematic in Homekit einbinden muss? Probiere ich gleich mal...

**Comment by blackbasket** [comment]
Ok, es wird also nach der Änderung im Wohnzimmer keine gewollte Änderung in der Küche durchgeführt?

**Comment by mike4president** [comment]
Also, ich hab zwei Thermostate im Wohnzimmer und eines in der Küche. Da ich eine offene Küche habe, habe ich die Küche in der Heizgruppe zusammen mit den beiden Thermostaten aus dem Wohnzimmer. In HomeKit sind dem Raum Wohnzimmer die Thermostate aus dem Wohnzimmer zugeordnet und nicht das aus der Küche. Wenn ich Siri jetzt sage, ändere die Temperatur im Wohnzimmer passt er die beiden Thermostate im Wohnzimmer an. Die Küche bleibt außen vor. Die beiden Thermostate aus dem Wohnzimmer springen kurz darauf auf die davor eingestellte Temperatur zurück. Gleiches Verhalten in einem Raum mit nur einem thermostat und einem Wandthermostat in der Heizgruppe. Ich habe hier das Wandthermostat und das Heizkörperthermostat eilen in HAP Homematic hinterleget. Der Siri Befehl geht also nur zum Heizkörperthermostat. 

Wenn ich hingegen die Heizgruppe in HAP Homemeatic hinterlege funktioniert es. ich kann dann trotz eingestelltem Auto Modus die Temperatur per Siri ändern. Die Lösung ist also immer die Heizgruppe in Hap anzulegen und nie die einzelnen Komponenten, zumindest wenn man Siri nutzen will. War das allen hier bereits klar und ich habe mich nur dumm angestellt? Wenn ja, sorry... ansonsten wäre das ggfs auch das für die Doku? Kann mir. nicht vorstellen, dass ich der einzige Spezialist bin, der in diese Fall läuft.

**Comment by mike4president** [comment]
och nööööööööööööö zu früh gefreut, auch wenn ich die Heizgruppe bestehend aus Wandthermostat Fenstersensor und Heizkörperthermostat in HAP Hoemmatic als Heizung einbinde springt er wieder zurück. Was ist denn das bloß?

**Comment by thkl** [comment]
Nö das sich das Ganze so verhält hab ich auch nur aus den Logs rausbekommen. Bzw aus der Tatsache, das das WebUi das gleiche Verhalten zeigt. Da haben wir alle zusammen wieder was gelernt. 

Ich kann mir nur vorstellen, das Das Küchenthermostat durch die Änderung im Wohnzimmer nicht gesetzt wird, und nach x Minuten seine Solltemperatur an die Gruppe meldet. Damit wird diese zurückgesetzt. Warum es funktioniert, wenn man die Temperatur am Gerät setzt kann ich mir nicht erklären, ggf verhält sich die Gruppe anders beim Setzen der Temperatur durch die Schnittstelle als wenn diese durch einen RegaEvent gesetzt wird.

**Comment by thkl** [comment]
Btw: wird die Feuchtigkeit bei Deinen Thermostaten angezeigt ?

Siehe https://github.com/thkl/hap-homematic/issues/358

**Comment by mike4president** [comment]
Also folgendes Verhalten habe ich beobachtet. Wenn ich die Gruppe in HAP-Homematic als Heizkörper anlege, und die Temperatur per Siri ändere, dann bleibt sie scheinbar erhalten.... ABER... öffne ich die Home App, zack ist er wieder schlauer als ich und springt zurück.

Luftfeuchtigkeit wird angezeigt, sowohl wenn ich ich die WTH einzeln, als auch in der Gruppe in HAP übernehme.

**Comment by mike4president** [comment]
wenn ich die WTH in der Gruppe mit einbinde, dann zeigt er die Luftfeuchtigkeit als Chacteristic des Thermostats an... 

![IMG_0172](https://user-images.githubusercontent.com/65063329/107695239-997bbf80-6cb0-11eb-83e6-2398e10628fc.PNG)

Wenn ich es einzeln einbinde als zwei einzelne Geräte eine für Temp und eines mit Humidity

**Comment by mike4president** [comment]
hier nochmal ein Bild. wenn ich es einzeln einbinde

<img width="1135" alt="Bildschirmfoto 2021-02-11 um 21 32 49" src="https://user-images.githubusercontent.com/65063329/107695664-33dc0300-6cb1-11eb-9a40-bcc9f62d6900.png">

![IMG_0173](https://user-images.githubusercontent.com/65063329/107695755-50783b00-6cb1-11eb-8643-002c3933bc3f.PNG)

**Comment by mike4president** [comment]
> Also folgendes Verhalten habe ich beobachtet. Wenn ich die Gruppe in HAP-Homematic als Heizkörper anlege, und die Temperatur per Siri ändere, dann bleibt sie scheinbar erhalten.... ABER... öffne ich die Home App, zack ist er wieder schlauer als ich und springt zurück.
> 
> Luftfeuchtigkeit wird angezeigt, sowohl wenn ich ich die WTH einzeln, als auch in der Gruppe in HAP übernehme.

Also es ist definitiv so, ich habe vor einer halben Stunde per Siri in der Heizgruppe im WC die temp auf 17 Grad gesenkt. blieb bis eben erhalten. Soweit so gut... wenn ich aber jetzt nun der Home App die Heizgruppe auswähle springt er sofort zurück auf die vor einer halben Stunde noch gültigen 20 Grad. irgendwie ist hier noch ein Würmchen drin

**Comment by meistermolli** [comment]
![Bild 11 02 21 um 21 52](https://user-images.githubusercontent.com/55836556/107697714-dd23f880-6cb3-11eb-849a-c1494aab3a53.jpg)

Hi, ich probiere auch mal alles durch wenn ihr wollt...
Ihr müsst bei geraten in Heizungsgruppen schauen, das steht oben auch immer in der WebUI mit drin!


Einzelnes Heizungsthermostat
- als HomeMaticRadiatorThermostatAccessory:
Einstellung Temperatur über Home App bleibt drin über mehrere Minuten.
ABER:
Vorschlagswert, wenn ich das Thermostat dann in der Home App anklicke springt dann auf den Default Wert des Zeitplanes. (was ja für mich korrekt ist. damit ich schnell wieder auf die "alte/aktuelle" Einstellung zurück finde.




Wenn man dieses Szenario hat:
Heizungsgruppe
Wandthermostat
Heizkörper Thermostat

Kann ich das verhalten bestätigen. Egal ob man in Homekit am Thermostat oder Wandthermostat die Temperatur ändert, springt die Heizungsgruppe wieder zurück auf den zuvor eingestellten wert.

Das macht die Heizungsgruppe aber nicht!!!  wenn ich in der Webui das Thermostat oder Wandthermostat ändere.

In Webui:
Gruppe ändern - ändert Thermostat - ändert Wandthermostat
- Verzögert dann eins nach dem anderen. Und dabei springt die Temperatur in der Gruppe öfters hin und her.

Wandthermostat ändern - ändert Gruppe - aber nicht Thermostat
Thermostat ändern - ändert Gruppe - aber nicht Wandthermostat

*** wenn ich ehrlich bin habe ich das nicht bemerkt, weil ich eigentlich nie manuel in die heizungssteuerung eingreife.

Zum testen Füge ich in Hap jetzt auch mal die Gruppe hinzu.

Ich habe sowohl Heizkörper als auch Wandthermostat drin, da Homekit dann einen Mittelwert für die Raumtemperatur ermittelt. und wir einen großen Raum haben.

**Comment by mike4president** [comment]
Hab die Heizgruppe mit Kanal 1 hinterlegt

**Comment by mike4president** [comment]
Ich greife eigentlich such nicht gerne in den Automatikmodus ein, aber bei mir wohnt noch eine Fristbeule und da müssen dann mal spontan 45 Grad her

**Comment by meistermolli** [comment]
So habe die auch mit Kanal 1 hinzu gefügt.
Temperatur bleibt bei allen geräten stehen. 

So lange, bis ich Aktiv ein gerät auswähle! Dann Springt das ganze auf den Default wert der Zeitsteuerung im Wochenprogram. Was ich aber gut finde.

Wochenprogram 21°
Manuel ändern auf 25°

bleibt solange bis ich auf das Gerät klicke in Homekit. - Anzeige Springt dann auf 21° zurück
(Default / Vorbelegungswert)
Stelle ich dann 23° ein. bleiben die auch drin...

**Comment by mike4president** [comment]
Hmmm, ich weiß nicht ob ich das Verhalten gut finde. Gut ist es ja erstmal, dass es mit der Gruppe nun funktioniert. 

@thkl Ist es so gewollt; dass es dann nach Auswahl des Gerätes in der Home App ins Wochenprogramm zurückspringt? Wenn ich die Temperatur an einem Aktor der Heizgruppe ändere, würde der Wert ja auch erhalten bleiben, bis zur nächsten Änderung des Zeitplanes. Finde es komisch, dass die Homeapp das vorzieht, sobald ich das Gerät auswähle

**Comment by mike4president** [comment]
Ach ja und eines noch, wenn ich die Heizgruppe in Homematic hinterlege, wird die Luftfeuchtigkeit als Characteristic der Gruppe in HomeKit angezeigt. Gäbe es die Möglichkeit dass man in der Home App entscheiden kann, ob die Luftfeuchtigkeit als separate Kachel dargestellt werden kann?

**Comment by meistermolli** [comment]
Ich habe hier wieder was gelernt.
Werde nun in allen Räumen meine Heizungsgeräte anpassen.

Gruppensteuerung als eigenes Gerät in HAP auf - HomeMaticRadiatorThermostatAccessory
Wandthermostat in HAP auf - HomeMaticThermometerAccessory
Heizkörperthermostat in HAP auf - HomeMaticThermometerAccessory

Spart Geräte/Buttons in der Raumübersicht, alle Geräte sind in der Klima Steuerung im Status einsehbar.
Keine Fehlbedienung durch Nutzer mehr möglich.

**Comment by mike4president** [comment]
@thkl Moin Thomas, die noch offenen Fragen aus dem Post hier wären folgende. 

Ist es ein durch dein Addon beeinflussbares verhalten, dass sobald man die Heizgruppe hinterlegt hat und per Siri die Temperatur ändert, die Home-App nach öffnen der Heizgruppe sofort in die Temperatur gemäß Zeitplan zurückstellt?

meistermolli findet das gut, ich eher nicht so. Wenn ich per Siri mitbewohnerfeundlich auf tropische Temperaturen anhebe, möchte ich die ähnlich gesichert wissen, als wenn ich das Thermostat selber drehe. Da stellt sich ja auch nichts von Zauberhand zurück nur weil ich in die Nähe der Thermostats gehe. Wüsste nicht, warum Homekit da eine Ausnahme bilden sollte. Könntest du da von deiner Seite noch was einstellen oder isses wie es ist?

Festzuhalten bleibt also was meistermolli schon schreibt:

Gruppensteuerung als eigenes Gerät in HAP auf - HomeMaticRadiatorThermostatAccessory
Wandthermostat in HAP auf - HomeMaticThermometerAccessory
_(Heizkörperthermostat in HAP auf - HomeMaticThermometerAccessory) - wobei ich nicht weiß was die letztere Information für eine Mehrwert liefert, wenn man schon das Wandthermostat eingebunden hat. )_

Außerdem habe ich noch einen Vorschlag. Ich bin jetzt nicht so tief im Thema wie du und kämpfe mich so durch. Könnte man HAP Homatatic ggfs um einen geführten Modus (Easy Mode) erweitern... so dass bei der Ersteinrichtung nur die relevanten Kanäle und dazugehörigen Services angezeigt werden? Bei der Steckdose wäre das bspw nur der Kanal für Messen oder Schalten. Bei den Heizgruppen nur der 1 Kanal usw. 

Beim erweiterten modus könnte man das ja so lassen wie es ist. Könnte mir vorstellen, dass es dadurch noch transparenter für den einen oder andern wird. Grüße

**Comment by thkl** [comment]
Soweit ich weiss, gibt es keine Möglichkeit, eine Manuell geänderte Temperatur auf Automatik zurückzusetzen. Das macht das Thermostat selber, wenn es den nächsten Automatik Schritt erreicht.

Zur 2. Frage das geht eher schlecht. Ich betrachte keine Geräte sondern Kanäle. Das heisst, jede Geräteklasse weiß welche Kanaltypen sie bedienen kann. Daher kann es durchaus sein, das einige Geräte (zb der Fensterkanal eines Thermostates) nutzlose Optionen anbieten. Aber das ist halt so....
