### ISSUE TITLE
Sprachsteuerung bei getauschten Schaltern funktioniert nicht

### ISSUE THREAD

**Issue by spamverdacht98** [thkl/hap-homematic#357]
Hallo,

mir ist gerade aufgefallen, dass sich die getauschten Schalter zwar über Homekit schalten lassen, aber die Sprachsteuerung per Iphone funktioniert leider nicht mehr.

Gibt es hierfür eine Lösung? Die getauschten Lichtschalter (Bad, Esszimmer und Küche) funktionieren nicht mehr. Z.B. Wohnzimmer und Schlafzimmer hingegen schon.

Vielen Danke im Voraus

Peter

**Comment by blackbasket** [comment]
Hi,

hast du generell mal ein paar Eckdaten? Was für Schalter bzw. welche Funktechnik? Etc

LG,
Marcel

**Comment by JensBonse** [comment]
Also wenn die sich in HomeKit schalten lassen, dann ist die Verbindung von HAP-HomeMatic zu HomeKit funktional.
Somit kann es kein BUG von HAP-HomeMatic sein. Siri setzt auf HomeKit auf.
Schau mal in EVE bei den entsprechenden Geräten, ob da 'Typ & Name' gleich dem Gerätenamen unter Details ist.

**Comment by spamverdacht98** [comment]
Hallo,

es handelt sich um HM-LC-SW1PBU-FM. Alle Lichtschalter heißen Lichtschalter XXX. In der Homematik sind alle Lichtschalter den Gewerken Homekit und Licht zugeodnet.  

Hier ein Screenshot von der CCU. Der Lichtschalter Arbeitszimmer funktioniert, in Homekit auch mit Sprachsteuerung Bad und Esszimmer funtioniert die Sprachsteuerung nicht.  
![grafik](https://user-images.githubusercontent.com/21288582/107674339-27e34780-6c97-11eb-85d1-89cb37005402.png)

Übersicht der Lichtschalter 
![grafik](https://user-images.githubusercontent.com/21288582/107674618-6d077980-6c97-11eb-8919-52a89e79c48f.png)

Einstellung des Lichtschalter Arbeitszimmer
![grafik](https://user-images.githubusercontent.com/21288582/107674996-e2734a00-6c97-11eb-96f7-e7752b2b4272.png)

Einstellung des Lichtschalter Bad 
![grafik](https://user-images.githubusercontent.com/21288582/107675083-f7e87400-6c97-11eb-818d-8014d42664b4.png)

Vielen Dank im Voraus
Peter

**Comment by blackbasket** [comment]
Hmm, sieht ja eigentlich gut aus. Hast du die Aktoren beim Anlernen ersetzt? Bei HM geht das ja, wenn ich das richtig im Kopf habe. Dann würde ich ggf. mal die Schalter im Plugin entfernen und neu hinzufügen.

Oder natürlich mal in der Eve-App den Hinweis von @JensBonse testen. Ich kenne Eve nicht.

**Comment by spamverdacht98** [comment]
Ich habe die Schalter normal angelernt und dann Tauschfunktion der CCU verwendet. Die "alten" Schalter habe ich aus dem HAP entfernt. Den CCU Cache aktualisiert und den HAP Neustart durchgeführt.

**Comment by blackbasket** [comment]
Schade ;)

Was steht denn im Log?

**Comment by spamverdacht98** [comment]
wenn ich den Log Eintrag vom Wohnzimmer zu Bad vergleiche sieht es gut aus. Beide Schalter werden als "HomeMaticProgrammableSwitchAccessory" erkannt.

**Comment by blackbasket** [comment]
Hallo Peter,

kannst du die Schalter bitte noch einmal löschen, dann einen Restart des Plugins durchführen und danach den Sprachbefehl erneut absetzen? Was erscheint dann im Log? Ich vermute, dass Siri dir wieder sagt, dass sie nichts findet, oder?

BTW: Meine Schalter (sind HmIP) habe ich als "HomeMaticSwitchAccessory" konfiguriert. Aber das sollte kein Problem darstellen.

LG,
Marcel

**Comment by spamverdacht98** [comment]
Hallo Marcel,

wie Du gesagt hast Schalter gelöscht, Plugin resetet. Siri fidet immer (hab es mit dem Schalter in der Küche getest) nichts. 

Bezogen auf die Küche steht im Log
hap-homematic instance HomeMatic_Küche (12:34:56:9b:b8:25) is running on port 9879.
service used for Lichtschalter Küche:1 is HomeMaticProgrammableSwitchAccessory
add Lichtschalter Küche:1 to bridge instance d9478e2d-e576-4550-8b38-d998b580632d
Your Bridge ID HomeMatic_Küche PinCode is 501-84-940

Im Arbeitszimmer, das funktioniert sieht so aus. 
hap-homematic instance HomeMatic_Arbeitszimmer (12:34:56:e2:d7:83) is running on port 9881.
service used for Lichtschalter Arbeitszimmer is HomeMaticProgrammableSwitchAccessory
add Lichtschalter Arbeitszimmer to bridge instance d6f294ea-bd11-4edc-a3ad-0117f209ac9e
Your Bridge ID HomeMatic_Küche PinCode is 806-56-812

Das Umstellen auf HomeMaticSwitchAccessory hat den Fehler leider nicht behoben.

Danke im Voraus

**Comment by blackbasket** [comment]
Hallo Peter,

was mir auffällt, ist ":1" beim nicht funktionierenden Schalter Küche. Ob die jetzt bei dir unterschiedlich benannt sind (sieht für mich im Screenshot nicht so aus) oder der Schalter tatsächlich doppelt vorhanden ist, wie bereits weiter oben vermutet, musst du bitte einmal selbst prüfen.

Vielleicht installierst du testweise wirklich mal Eve. Lt. @JensBonse kann man es dort ja erkennen.

LG,
Marcel

**Comment by JensBonse** [comment]
Wenn die Schalter sich in HomeKit über die Apple Home APP schalten lassen, dann ist der Fehler nicht bei HAP zu suchen.
Dann wird es am 'Naming' oder am 'Wording' liegen.

**Comment by spamverdacht98** [comment]
Hi Marcel,
ich lade EVE herunter, muss mich aber erst schauen wie es funktioniert. 
Peter

**Comment by spamverdacht98** [comment]
Das Naming ist bei allen Schaltern identisch. 

Lichtschalter Bad
Lichtschalter Küche 
Lichtschalter Wohnzimmer
usw.

**Comment by spamverdacht98** [comment]
Hallo,

laut Eve sind die Lichtschalter Esszimmer, Bad und Küche Typ "Schalter", alle anderen Lichtschalter sind Typ Licht. Ich habe jetzt alle auf Typ Licht umgestellt, jetzt funktioniert es wieder.  VIELEN DANK an alle.
