### ISSUE TITLE
hap-homematic WTH-2 (either Thermostat or Humidity)

### ISSUE THREAD

**Issue by rxmart10** [thkl/hap-homematic#358]
Hi everyone,
I am on a personnel saga to automate my home as much as possible.
Recently I have installed the WTH-2 Radiator Thermostat with Humidity measurement.

However, when installed into the hap-homematic, it only allows 1 channel as a service.

Is there any other way to access the Radiator Thermostat & Humidity?

**Comment by thkl** [comment]
The HmIP-WTH-2 device contains multiple channels. Please select channel 1 (HEATING_CLIMATECONTROL_TRANSCEIVER). There is a dropdown to select a service for HEATING_CLIMATECONTROL_TRANSCEIVER. Please select here the HomeMaticRadiatorThermostatAccessory. This will create a Thermostat to control the device. Otherwise HomeMaticThermometerAccessory will only create a thermometer and this is a read only device

**Comment by rxmart10** [comment]
> The HmIP-WTH-2 device contains multiple channels. Please select channel 1 (HEATING_CLIMATECONTROL_TRANSCEIVER). There is a dropdown to select a service for HEATING_CLIMATECONTROL_TRANSCEIVER. Please select here the HomeMaticRadiatorThermostatAccessory. This will create a Thermostat to control the device. Otherwise HomeMaticThermometerAccessory will only create a thermometer and this is a read only device

Hi, Thank you for the reply.
What you have mentioned is correct.

The issue is that, I have 1 device that provides:
- Radiator Adjustment
- Temperature
- Humidity

However, as in the HAP-HOMEMATIC there is only 1 channel, I can only choose 1 of the above.

If I choose Radiator, it provides also current temperature (not humidity), but if I choose Humidity, it only provides Humidity.

**Comment by thkl** [comment]
the class will check if there is a humidity datapoint and if so it will provide this to homekit.
Maybe there is a bug for this detection method.I will check this .. but since i do not own such a device i have to build a simulation for, which will take some effort.

**Comment by meistermolli** [comment]
Maybe Same Bug on HmIP ETRV - B


![Bild 11 02 21 um 23 16](https://user-images.githubusercontent.com/55836556/107705537-2cbbf180-6cbf-11eb-81ce-4e81855e6954.jpg)

**Comment by rxmart10** [comment]
![2021-02-12 (1)](https://user-images.githubusercontent.com/78905466/107753953-16df1880-6d21-11eb-9896-2214b887bd51.png)
![2021-02-12](https://user-images.githubusercontent.com/78905466/107753959-19417280-6d21-11eb-82f9-44671db116e0.png)
![IMG_0280](https://user-images.githubusercontent.com/78905466/107754013-29595200-6d21-11eb-935f-ea09b0dff130.PNG)


As seen above, I have 3 options and if I choose Radiator Thermostat, no humidity is shown.

**Comment by thkl** [comment]
Please take a look into the settings of your thermostat. Maybe HomeKit will hide the humidity there.

**Comment by rxmart10** [comment]
Thanks for the feedback, already looked, it only shows Thermostat and the Boost button.

**Comment by rxmart10** [comment]
An additional info.
If I selec the Temperature option, it shows temperature and humidity but does not allow to set radiator temperature.

**Comment by thkl** [comment]
Ok I will take a look into this.  Other people (the issue I've linked above) are able to see the humidity for this device using the radiator service.

**Comment by Uwe-F** [comment]
Hallo,
die gleichen Probleme habe ich auch, die rxmart10 beschrieben hat. Die Raumtemperatur wird angezeit, aber nicht die Luftfeuchtigkeit. Alternativ hatte ich Redmatic benutzt, dort wurden beide Variablen erzeugt.
Die Luftfeuchtigkeit wird nur im Menuefenster angezeigt.
![Bildschirmfoto 2021-02-23 um 15 52 58](https://user-images.githubusercontent.com/79526268/108861331-65c56180-75ef-11eb-87f5-2bbc591e1411.png)

**Comment by thkl** [comment]
Das Problem liegt daran, das ich ein Thermostat erzeuge.  Dieses hat die Eigenschaften: Ist Temp/Soll Temp/Luftfeuchtigkeit ...

Dann zeigt Home das so an. 

Man kann natürlich die Luftfeuchtigkeit dort weglassen und in das Gerät einen Extra Service für Luftfeuchtigkeit einbauen. Dann sollte das als eigenes Icon auftauchen...

**Comment by Uwe-F** [comment]
In Redmatic ist es in der Gruppe (z.B. Robin) ein Sysmbol rund (Kreis) mit der Temperatur im Kreis und darunter die Luftfeuchtigkeit. Öffnet man den Kreis dann erhält man zwei Icons die einmal Temp. und das andere Luftf. anzeigt. Beide Bilder von Addon Redmatic.
![Bildschirmfoto 2021-02-23 um 16 10 01](https://user-images.githubusercontent.com/79526268/108863930-ff8e0e00-75f1-11eb-825a-89e840b2e5f0.png)
![Bildschirmfoto 2021-02-23 um 16 10 23](https://user-images.githubusercontent.com/79526268/108863935-00bf3b00-75f2-11eb-95b1-8ba942bee490.png)

**Comment by thkl** [comment]
Es wird im nächsten Update ein Häkchen im Thermostat geben was dann diese Version erzeugt :

![image](https://user-images.githubusercontent.com/884355/108865356-7677d680-75f3-11eb-9ba1-c1840f608a8d.jpeg)

![image](https://user-images.githubusercontent.com/884355/108865373-7a0b5d80-75f3-11eb-8965-a38e653ce7e8.png)

**Comment by Uwe-F** [comment]
Super, das freut mich. Eure Arbeit ist toll! Vielen Dank. Gruß

**Comment by thkl** [comment]
ok finally i added this patch to the thermostat and the programmable thermostat .. you may test this by override the classes in /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services with the changed files mentioned above

**Comment by Uwe-F** [comment]
Ich habe von Homematic den Homematic-IP-Wettersensor-pro mit der Bezeichnung HmIP-SWO-PR. In der Homematic sind diese Variablen erkennbar(siehe Bild). Wobei die oberen 4 Felder aktiv von der Wetterstation gesendet werden. (Temp., Luftf., Helligkeit, Windgeschw., Windricht., Schwankungsbreite). Die anderen Daten werden in der CCU berechnet. Aktuell wird die Temperatur mit 0°C angezeigt(Bild), obwohl diese in der CCu angezeigt wird. Luftfeuchtigkeit wird angezeigt. Sind weitere Werte möglich?
![Bildschirmfoto 2021-02-23 um 19 25 59](https://user-images.githubusercontent.com/79526268/108890365-c8c5f100-760d-11eb-9c03-e821bdf5160e.png)
![Bildschirmfoto 2021-02-23 um 19 25 37](https://user-images.githubusercontent.com/79526268/108890367-c95e8780-760d-11eb-9bca-63b6cb8f1907.png)
![IMG_1298](https://user-images.githubusercontent.com/79526268/108890371-c95e8780-760d-11eb-8c90-a37e37cff38e.jpg)

**Comment by thkl** [comment]
Das ist jetzt aber ein neues Thema .... und gehört nicht mehr zu dem Issue.
Aber: HomeKit kennt keine Wetterstationen, deswegen nur Temperatur und Feuchtigkeit.

**Comment by Multisaft7** [comment]
@thkl ich muss mal blöd nachfragen, aber wenn ich die Heizungsgruppe aus WTH-2 und eTRV-2 hinzufüge wird mir das Häkchen mit der Luftfeuchtigkeit aber nicht angezeigt?!

**Comment by thkl** [comment]
Soweit ich weiß wird bei einer Gruppe keine Feuchtigkeit von der CCU geliefert. Daher fehlt das Häkchen dann auch.

**Comment by Multisaft7** [comment]
> Es wird im nächsten Update ein Häkchen im Thermostat geben was dann diese Version erzeugt :
> 
> <img alt="image" width="1141" src="https://user-images.githubusercontent.com/884355/108865712-ca82bb00-75f3-11eb-8657-9b0d055e5ce4.png">
> 
> wird zu :
> 
> ![image](https://user-images.githubusercontent.com/884355/108865356-7677d680-75f3-11eb-9ba1-c1840f608a8d.jpeg)
> 
> ![image](https://user-images.githubusercontent.com/884355/108865373-7a0b5d80-75f3-11eb-8965-a38e653ce7e8.png)
<img width="1160" alt="Bildschirmfoto 2021-12-28 um 02 28 12" src="https://user-images.githubusercontent.com/33881175/147518007-677b0bf1-d2a3-4047-9006-5929ae5b5bc5.png">

@thkl ich hatte jetzt das hmip wth ausgewählt...aber bei mir fehlt das Häkchen :-( Mach ich was falsch?

**Comment by Multisaft7** [comment]
Gibts hier ein Update oder kann mir jemand weiterhelfen?

**Comment by robig** [comment]
State on Jan. 2024: I still only have a "HomeMaticRadiatorThermostatAccessory" available to choose, and there seems to be no such option.
