### ISSUE TITLE
Die Lüftung wird beim HMIP-MOD-HO noch nicht korrekt angezeigt

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#359]
Hallo,

an dem HMIP-MOD-HO funktioniert noch etwas nicht ganz korrekt.

1. Ausgangssituation: Tor ist geschlossen
![6BC431B0-C9D1-408D-AC86-44F4A30BDAD8](https://user-images.githubusercontent.com/72799068/107635783-03be4100-6c6c-11eb-8202-1933f44c7e56.jpeg)

2. Lüftungsfunktion wird per Siri aktiviert
![97486D02-050E-4332-AA01-01B191BF990F](https://user-images.githubusercontent.com/72799068/107635802-0f116c80-6c6c-11eb-8c36-2264f22fc1f2.jpeg)

3. Das Garagentor wird als „Offen“ angezeigt (Was ja auch eigentlich richtig ist), die Lüftung ist aber weiterhin aus.
![564B42A0-1EC7-45E2-A65D-2C4351254B6B](https://user-images.githubusercontent.com/72799068/107635917-35cfa300-6c6c-11eb-9e01-542a861a4125.jpeg)

4. Lüftungsfunktion wird per Siri deaktiviert
![DA4F8124-967C-423A-A580-8AAC838394B0](https://user-images.githubusercontent.com/72799068/107635991-48e27300-6c6c-11eb-9355-0ab046e2ac92.jpeg)

5. Das Garagentor wird als „geschlossen“ angezeigt (Was korrekt ist), die Lüftung wird aber nun als „aktiv“ angezeigt.
![2C34EF11-2E45-4011-896A-9D55C6757E13](https://user-images.githubusercontent.com/72799068/107636108-74655d80-6c6c-11eb-95ec-7508528a3df1.jpeg)

**Comment by meistermolli** [comment]
Hi,

einfach einen Moment warten, Die Lüftungsfunktion Anzeige geht nach ca 20 Sec. von alleine aus.

Gruß meistermolli

**Comment by gerd2005** [comment]
Naja das Icon soll ja aktiviert werden, wenn man die Lüftung anschaltet.

**Comment by meistermolli** [comment]
Das stimmt schon. 

Leider gibt das MOD-HO einen Status Unbekannt aus, wenn sich das Tor bewegt. Vielleicht liegt es ja daran?

**Comment by gerd2005** [comment]
Ja, mag sein. Aber in der CCU wird der Status ja auch korrekt gesetzt. Darauf greift doch das Plugin zu, oder nicht?

**Comment by meistermolli** [comment]
Ne in der ccu webui stand bei mir beim schließen immer „unbekannt“ ich denke daher werden beide Schalter dann ausgelöst.

Es funktioniert doch bei dir auch oder nicht? Nur der Ventilator dreht kurz mit wenn das Tor schließt? Und dann noch 30 sec wenn es zu ist?

der Status beim schließen ist ja leider irgendwo zwischen geschlossen / offen / lüften. Und wenn die ccu nur unbekannt weiter gibt. Dennoch zeigt HAP und HomeKit den Status des Tors noch korrekter an wie die webui. Denn HomeKit weiß ob das Tor schließt oder öffnet.

**Comment by blackbasket** [comment]
@gerd2005 besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)
