### ISSUE TITLE
Wiki Eintrag: Variablen Umlaute werden nicht abgeholt

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#360]
Hi,

bitte einen Wiki Eintrag machen, dass Variablen aus der CCU nicht abgeholt werden, wenn der Variablen Name in der CCU einen Umlaut ÄÖÜ enthält.

Das CCU Program und die CCU Variable werden trotz Umlaut beschrieben,
aber HAP kann den Wert nicht "abholen" und in Homekit eintragen,
auch wenn die Trigger neu gesetzt werden.

Wenn man dann ae ue oe verwendet, dann kann HAP den Variablen Wert wieder "abholen".
In HAP für den Gerätenamen in Homekit kann man dann wieder Umlaute verwenden!

Bsp: Heizkörper Temperatur als VarBasedThermometerAccessory

Variable in CCU - Heizkoerper Temperatur (Heizkörper - wert wird nicht abgeholt)
Variablen Name in HAP / Homekit - Heizkörper Temperatur

#204 

Gruß meistermolli

**Comment by thkl** [comment]
Ich baue derzeit auf escapte Gerätenamen um. Ich schau mir die Variablen da gleich mal mit an.

**Comment by thkl** [comment]
Sollte in .59 gehen
