### ISSUE TITLE
HmIP-SPI Illumination wird nicht mehr aktualisiert

### ISSUE THREAD

**Issue by blackflash73** [thkl/hap-homematic#362]
Ich verwende einen HmIP-SPI als Bewegungsmelder für die Flurbeleuchtung. Während Bewegung sehr zuverlässig und ohne große Latenz in HomeKit signalisiert wird, bleibt der Helligkeitswert statisch auf einem festen Wert. In der CCU3 wird hingegen der korrekte aktuelle Helligkeitswert angezeigt - nur nicht in der Home-App. 
Die Helligkeitswerte von zwei anderen HmIP-SMI werden hingegen normal aktualisiert. 

Entfernen des Device und erneutes Hinzufügen bringt leider nichts. Es wird wieder der gleiche falsche Wert angezeigt. Neustart HAP-Service: keine Änderung. Neustart CCU3 (Rpi3b+): aktueller Helligkeitswert des HmIP-SPI wird einmalig übernommen, danach nicht mehr aktualisiert.

**Comment by blackflash73** [comment]
- enabled Debug Mode 
- Enabled Illumination Checkbox in the HAP-Device Settings "HmIP-SPI Flur DG" [HomeMaticPresenceAccessory] 000C1BE9917887
- Saved Device Konfig 
- "HmIP-SPI Flur DG Illumination" showed up in Apple Home-App with static value "26,1" 

[Sat Feb 13 2021 12:45:17 GMT+0100 (CET)] debug - [HAP Server] [CCU] HmIP-RF.000C1BE9917887:1.CURRENT_ILLUMINATION return cached value 26.100000
-> This is the static value <> current value displayed in CCU3-UI

[hap-homematic.log](https://github.com/thkl/hap-homematic/files/5975715/hap-homematic.log)

**Comment by thkl** [comment]
Solange die CCU keinen Event mit einem aktualisierten Wert schickt, wird der Wert aus dem Cache genommen.

**Comment by blackflash73** [comment]
Hab’s vermutlich gefixt! (bitte nochmal prüfen!)

Mir ist aufgefallen, dass ich als Device Type nur "HomeMaticPresenceAccessory" (also ohne IP) 
zur Auswahl hatte. Nun hab ich die Datei "/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/HomeMaticPresenceAccessory.js" als "HomeMatic**IP**PresenceAccessory.js" gespeichert und darin die Zeile "illumination: 'CURRENT_ILLUMINATION'," mit "illumination: 'ILLUMINATION'," korrigiert (siehe Anhang, vgl. HomeMaticIPMotionAccessory.js) — nun wird der Wert aktualisiert. ^^

[HomeMaticIPPresenceAccessory.js.txt](https://github.com/thkl/hap-homematic/files/5976313/HomeMaticIPPresenceAccessory.js.txt)

**Comment by thkl** [comment]
ja die Klasse heisst HomeMaticPresenceAccessory weil es den Präsenzsenor nur in IP gibt. Daher habe ich da keine Unterscheidung gemacht.

Der Einzige Unterschied ist das der Wert ILLUMINATION statt CURRENT_ILLUMINATION abgefragt wird.
Die alles entscheidende Frage ist jetzt wo liegt der Unterschied zwischen beiden Werten. Die Doku ist da nichtssagend.

**Comment by blackflash73** [comment]
Richtig, das ist das einzige, was ich geändert habe.

Bei HmIP-SMI und -SPI gibt "Current_Illumination" den ungefilterten, aktuellen Helligkeitswert, und "Illumination" der gefilterte Wert:
CCU-Geräteeinstellungen Helligkeitsfilter: [X] "Die übertragene Helligkeit ist das Minimum der letzten X Werte (Messung alle 6 Minuten)", Defaultwert ist hier 8
Das heißt ILLUMINATION gibt das Helligkeits-Minimum der letzten 48 Minuten aus. Da ich das als Wert-Bedingung für meine Flur-Beleuchtung verwende, ist das genau das, was ich brauche.

Bei den SMI habe ich den ungefilterten Helligkeitswert im CCU3-Diagramm überwachen wollen - leider wurden die Werte nur sporadisch aktualisiert und daher habe ich mich auf den gefilterten Wert konzentriert. Beim SMI hast Du's ja auch so implementiert.

Daher mein Vorschlag: Vielleicht sollte man auch beim SPI besser "ILLUMINATION" statt "CURRENT_ILLUMINATION" abfragen.

**Comment by thkl** [comment]
Ok, ich ändere das mal.

**Comment by blackflash73** [comment]
Top, danke!  :o)

Auch für Deine klasse Entwicklungsarbeit an einem für mich unverzichtbaren CCU3-AddOn! 
👏👍💪
Bleib' bitte gesund! ;)
