### ISSUE TITLE
HM-CC-RT-DN Boost Modus - Bug oder Feature?

### ISSUE THREAD

**Issue by massenmensch** [thkl/hap-homematic#363]
Hallo,

erst einmal vielen Dank für dieses tolle Plugin. 

Ich habe eine Frage zum Boost Modus der Heizkörperthermostate... Wenn ich diesen in Homekit aktiviere, und dann manuell (ebenfalls in Homekit) wieder deaktiviere, springt das Thermostat immer auf "OFF", also geht in den manuellen Modus auf 4,5°C. Ist das ein Bug, oder muss das so sein, weil es anders nicht implementiert werden kann? Ich würde mich über eine Info hierzu sehr freuen.

Liebe Grüße

**Comment by thkl** [comment]
Kannst Du mal bitte vor dem Boost einmal die Temperatur manuell einstellen. Ist das dann immer noch so ?

**Comment by massenmensch** [comment]
Ja, das Verhalten tritt auch auf, wenn ich in Homekit erst eine Temperatur manuell einstelle und dann den Boost aktiviere und wieder deaktiviere in Homekit. Auch wenn ich am Thermostat vorher eine Temperatur einstelle tritt der selbe Fehler auf.

**Comment by gerd2005** [comment]
Hallo,

der HMIP-BWTH zeigt ein ähnliches Verhalten. Ich kann es morgen noch einmal genau nachstellen. 

Lieben Gruß

**Comment by blackbasket** [comment]
@massenmensch besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)

**Comment by massenmensch** [comment]
@blackbasket Benutze die Geräte aktuell nicht, kann ich also deshalb nicht genau sagen. Ich schließe aber trotzdem mal. :)
