### ISSUE TITLE
Zwei virtuelle Tasten zu einem Gerät verbinden

### ISSUE THREAD

**Issue by mano87** [thkl/hap-homematic#366]
Guten Abend,

in der CCU3 habe ich zwei virtuelle Tasten angelegt. Eine um das gesamte Außenlicht einzuschalten und eine um das gesamte Außenlicht auszuschalten. Mit der jeweiligen virtuellen Taste habe ich alle Außenlampen mit einer Direktverknüpfung in der CCU3 angelegt.

Kann ich diese beiden einzelnen Tasten zu einer HomeKit Taste (ein/aus) zusammen fügen? Vermutlich geht das so nicht, oder?

**Comment by ciddi89** [comment]
Guten Abend,

Also ich denke auch das es so nicht möglich ist. Würde es daher mit einer variabel lösen, die kann man ja als Schalter an HomeKit weiter geben mit True und false. Und dazu noch ein Programm, das wenn der Schalter in HK oder der virtuelle Taster betätigt/auf an gestellt werden dann auf True und Licht an und wenn in HK auf aus gestellt wird oder die andere virtuelle Taste gedrückt wird dann auf false und Licht aus. So würde ich es evtl. machen. LG

**Comment by thkl** [comment]
Genau das wäre die einfachste Variante. Für alle Konstrukte gibt es leider keine Rückmeldung über den aktuellen Zustand. 

Eine andere Möglichkeit wäre, alle Außenlichtaktoren in eine neue HomeKit Instanz aufzunehmen und dann in HomeKit einem Raum "Außen" hinzuzufügen. Dann kann man Siri das Licht in "Außen" anschalten lassen. Und sie gibt ggf auch den Status zurück.
