### ISSUE TITLE
Wäre es möglich eine Wetterstation HMIP swo b zu integrieren?

### ISSUE THREAD

**Issue by thkl** [thkl/hap-homematic#37]
Wäre es möglich eine Wetterstation HMIP swo b zu integrieren?

_Originally posted by @fighterzg6 in https://github.com/thkl/hap-homematic/issues/34#issuecomment-622663040_

HmIP-SWO-PR (Pro)
HmIP-SWO-PL (Plus)
HmIP-SWO-B (Basic)

**Comment by thkl** [comment]
Frage hier zu an @roe1974 welche Unit hat SUNSHINEDURATION bzw was wird da gemessen ? Die Stunden am Tag wo es hell ist ?

**Comment by roe1974** [comment]
das haben alle .... sieht so aus in der CCU:
![grafik](https://user-images.githubusercontent.com/30420568/80860589-dd915c80-8c68-11ea-8dbd-e1472d2ac7ff.png)

**Comment by thkl** [comment]
ok also Hours als Unit .. danke

**Comment by detLAN** [comment]
HmIP-SWO-PR sieht so aus:
<img width="797" alt="Bild2" src="https://user-images.githubusercontent.com/64675966/80860734-0e25c600-8c6a-11ea-8411-31b1a3080b77.png">

**Comment by thkl** [comment]
HmIP-SLO müsste schon gehen mit dem HomeMaticLightSensorAccessory
HmIP-STHO schaut aus wie ein normales Themometer oder

**Comment by detLAN** [comment]
> HmIP-SLO müsste schon gehen mit dem HomeMaticLightSensorAccessory

Ja

> HmIP-STHO schaut aus wie ein normales Themometer oder

Ja, ist ein Thermometer

**Comment by thkl** [comment]
Ok, dann nehm ich das und erweitere nur die Datenpunknamen

**Comment by thkl** [comment]
So, das sollte mit der nächsten Version funktionieren.
Wichtig ist aber: die HomeApp wird das nicht alles anzeigen. Hier gehen nur Temperatur und Feuchtigkeit. Apples HomeApp zeigt keine ihr unbekannten Characteristics an (obwohl alles geliefert wird, was benötigt wird) .. Elgatos Eve macht das aber.

**Comment by fighterzg6** [comment]
kann jetzt zwar die Wetterstation auswählen , aber er fügt sie nicht hinzu

**Comment by thkl** [comment]
ich glaub ich hab da noch nen Bug gefunden ...

**Comment by roe1974** [comment]
same here....

**Comment by thkl** [comment]
ach ;)

**Comment by roe1974** [comment]
:-P

**Comment by detLAN** [comment]
Umsetzung für HmIP-STHO und HmIP-SWO-PR erfolgreich - Danke dafür!

**Comment by thkl** [comment]
geht die Wetterstation in 0.0.36 ?

**Comment by detLAN** [comment]
Nein, habe ich ja schon korrigiert ;)

**Comment by thkl** [comment]
hmm im Simulator geht sie ;) .. naja mal sehen

**Comment by detLAN** [comment]
Habe gerade den HUP Service neu gestartet. Unter 0.0.36 wird jetzt die Wetterstation als Haus dargestellt - nur die Wetterdaten nicht

**Comment by thkl** [comment]
ja Home ist da bissel doof, dort wird bei unbekannten Characteristics einfach geschmollt und nichts angezeigt.

Ich wollte schon sagen, einmal den Service im WebUI explizit auswählen und anklicken sollte das Problem auch lösen. 

BugFix im automatischen Classfinder kommt mit dem nächsten Release (das ist ja jetzt hier nicht so kritisch)

**Comment by thkl** [comment]
Achja .. die Frage ist die Sonnenscheindauer sind das Minuten die ich von der CCU bekomme ?
Weil 42,7 h is doch bissel viel für den Tag oder

**Comment by roe1974** [comment]
ja sind Minuten ....
![grafik](https://user-images.githubusercontent.com/30420568/80867315-e4819480-8c93-11ea-81f1-7fc6ac7f0c73.png)
lg Richard

**Comment by detLAN** [comment]
Ich habe die Werte einmal gegenüber gestellt:
![Bild4](https://user-images.githubusercontent.com/64675966/80867316-e51a2b00-8c93-11ea-9524-3eebaec82fb3.png)

**Comment by thkl** [comment]
naja die Frage ist was bekomme ich bei der direkten Abfrage des Datenpunktes für einen Wert
Ich habe bei der Sonnenscheindauer schon /60 gerechnet ... na ich wühle mich mal durch die Firmware der CCU

**Comment by thkl** [comment]
OK, Sonnenscheindauer und RegenMenge ist so ein Ding. Das sind im Gerät laufende Zähler und in der CCU leben je Gerät 3 versteckte Variablen die von jede Nacht von einem Programm mit den Differenzen der letzten Berechnung neu gefüllt werden.

Ich würde die Werte daher weglassen.

**Comment by thkl** [comment]
das müsste doch auch durch sein oder ?

**Comment by roe1974** [comment]
aus meiner sicht ja ....

**Comment by thkl** [comment]
Nice !

**Comment by detLAN** [comment]
Ich muss hier einmal reinrufen. Eve schön viel Daten, wenn man sich nicht für HomeKit Kompatibilität entscheidet. Tut man dies jedoch, beschneidet es auch Eve.
Warum geht es nicht, dass man alle Daten die in der jeweiligen App möglich sind zur Verfügung stellt? Oder hab ich hier was überlesen?

**Comment by thkl** [comment]
Ja, ich verstehe die Frage. Nur wenn Du Eve als Client nutzt, dann musst Du dieses Apple Home Häkchen ja nicht setzen. Der Workaround der dann in Kraft tritt ist, das ich einem Gerät mehrere Sensoren zuordne. Das hat in Eve wiederum die Auswirkung das für ein Gerät mehrere Zeilen in der Raumansicht angezeigt werden.  Eve zeigt eine Zeile pro Sensor an und fasst das nicht in ein Gerät zusammen wie Apples Home. 

Im Falle, das der Haken nicht gesetzt ist, hänge ich alle Characteristics (also Temperatur, Feuchtigkeit, Druck, Wind etc) in einen Sensor. Damit wird in Eve nur eine Zeile in der Raumansicht gezeigt.  

Daher die zwei Wege.

**Comment by detLAN** [comment]
Morgens mal wieder verpennt, Aktentasche geschnappt und ab ins Büro. Sch... iPhone wieder mal vergessen. Macht ja nix, MacBook ist ja dabei. Ups, es gibt gar kein Eve für macOS, oder hat die App sich nur vor mir versteckt 😉

**Comment by thkl** [comment]
Wie gesagt beide Versionen bringen meines Erachtens Nachteile in der jeweiligen anderen App.

**Comment by detLAN** [comment]
Okay, man kann ja nicht immer alles bekommen 😔

**Comment by detLAN** [comment]
Eine Frage dann doch noch. Wenn man sich für Eve entscheidet, könnte dann nicht in der Home App das Icon unterdrückt werden?

**Comment by roe1974** [comment]
Denke nicht dass das geht .... beide Apps greifen ja auf die selben HomeKit Daten zu ..... und ein und dasselbe Gerät kann nur eine Characteristic haben ... 
Aber wenn du Eve benutzt, was kümmert dich das Icon in der Home App ?
Mich , als z.B. Home App User, kümmert auch nicht wie die Wetter Station in einer App aussieht die ich nicht benutze ;-)

**Comment by thkl** [comment]
Eve und Home greifen auf die selbe HomeKit Datenbank zu die Geräte die dort eingetragen sind werden in den Apps dargestellt.  Ob man die in der Home App ausblenden kann, weiß ich nicht.

**Comment by hillinator** [comment]
Hallo @thkl 

Wäre das der gleiche Fall für HmIP-SWO-PL ?

Hier wird zwar mit der Apple Home Kompatibilität ein Button mit drei Sensoren in Apple Home angelegt, leider jedoch immer mit "Gerät antwortet nicht"

`[HomeMaticWeatherStationAccessory] 123456789123456 buildAddress ACTUAL_TEMPERATURE
[HomeMaticWeatherStationAccessory] 123456789123456 seems to be a single datapoint
[HomeMaticWeatherStationAccessory] 123456789123456 getValue HmIP-RF.123456789123456:1.ACTUAL_TEMPERATURE
[CCU] ask Rega HmIP-RF.123456789123456:1.ACTUAL_TEMPERATURE
[Rega] RegaScript object o = dom.GetObject('HmIP-RF.123456789123456:1.ACTUAL_TEMPERATURE');if (o){Write(o.Value());}
[HomeMaticWeatherStationAccessory] 123456789123456 buildAddress ILLUMINATION
[HomeMaticWeatherStationAccessory] 123456789123456 seems to be a single datapoint
[HomeMaticWeatherStationAccessory] 123456789123456 getValue HmIP-RF.123456789123456:1.ILLUMINATION
[CCU] ask Rega HmIP-RF.123456789123456:1.ILLUMINATION
[Rega] RegaScript object o = dom.GetObject('HmIP-RF.123456789123456:1.ILLUMINATION');if (o){Write(o.Value());}
[HomeMaticWeatherStationAccessory] 123456789123456 buildAddress HUMIDITY
[HomeMaticWeatherStationAccessory] 123456789123456 seems to be a single datapoint
[HomeMaticWeatherStationAccessory] 123456789123456 getValue HmIP-RF.123456789123456:1.HUMIDITY
[CCU] ask Rega HmIP-RF.123456789123456:1.HUMIDITY
[Rega] RegaScript object o = dom.GetObject('HmIP-RF.123456789123456:1.HUMIDITY');if (o){Write(o.Value());}
[Rega] result is 28.800000
[CCU] event HmIP-RF.123456789123456:1.ACTUAL_TEMPERATURE will be handled by 1 registered callback
[WST] ignore log 28.8 -255 37
[Rega] result is 2349.000000
[CCU] event HmIP-RF.123456789123456:1.ILLUMINATION will be handled by 1 registered callback
[Rega] result is 37
[CCU] event HmIP-RF.123456789123456:1.HUMIDITY will be handled by 1 registered callback
[WST] ignore log 28.8 -255 37`
