### ISSUE TITLE
6-fach-Taster, Tasten in HomeKit werden nicht gedrückt

### ISSUE THREAD

**Issue by ykhnhfr** [thkl/hap-homematic#373]
Ich habe einen 6-fach-Taster und kann damit nur die Taste 5 in HomeKit verbinden. 
Wenn ich die Taste 5 Klicke, dann funktioniert alles wunderbar. Möchte ich allerdings die Taste 6 auch noch in HomeKit einbinden, kann die Taste 6 nicht geklickt werden. Taste 5 funktioniert aber top. Kennt jemand das Problem bzw. kann helfen?

**Comment by blackbasket** [comment]
Hi,

ich kann es nächste Woche ggf. testen. Gerade teste ich aber was anderes, da möchte ich keine config-Änderung vornehmen.

LG,
Marcel

**Comment by ChrWi** [comment]
Hallo, wie hast du den Schalter konfiguriert? 
ich nutze ihn normal nicht über HomeKit, habe das nur gerade erfolgreich wie folgt pro Key konfiguriert & getestet:
![E6F62146-0EAE-41C6-8F5E-15721BC758FD](https://user-images.githubusercontent.com/52505025/108762640-a4f0a580-7550-11eb-925e-468fee0566ec.jpeg)

**Comment by blackbasket** [comment]
Hi @ykhnhfr,

gibt's hier jetzt noch Testbedarf? Anders als @ChrWi hätte ich es auch nicht gemacht.

LG,
Marcel

**Comment by ykhnhfr** [comment]
Habe ihn als HomematicKeyAccessory konfiguriert. Vielleicht liegt da der Fehler?

**Comment by ykhnhfr** [comment]
Also ich habe mal probiert den Taster als HomematicPushTheButtonAccessory an HomeKit zu "exposen".
Hier wird der Taster dann als "Schalter" angezeigt. Sowohl "Press_Short" als auch "Press_Long" als auch Both probiert. Ich kann das nicht an- und ausschalten. Wenn ich den Taster Drücke, passiert im Home einfach nichts.

Wenn ich es als HomeMaticKeyAccessory expose, dann kann ich vom Taster nur die Taste 5 drücken. Aller anderen funktionieren nicht.

**Comment by thkl** [comment]
Mal zur Erklärung vielleicht hilft das:

Der Service KeyAccessory ist so gedacht, das er in HomeKit einen sog. StatelessProgrammableSwitch erzeugt.
Das ist eine einfache Taste, die für eine HomeKit Automation benutzt werden kann und auf einen Tastenevent aus der CCU hört. Das heisst eine virtuelle Taste in der CCU oder aber auch eine beliebige andere Taste können damit eine Homekit Scene / Automation auslösen.

StatelessProgrammableSwitch Geräte können nicht manuell ausgelöst werden. Sondern diese sind nur für Automationen verfügbar, die Zuordnung in Homekit schaut wie folgt aus:

![image](https://user-images.githubusercontent.com/884355/108892129-d0869500-760f-11eb-94ef-0fbd0e6ec55a.png)

Hier müsste bei Single oder Double Press die passende Szene/Automation hinterlegt werden.
Wird dann die verknüpfte CCU Taste gedrückt, führt HomeKit die Scene aus.

Der Service PushTheButton ist genau das Gegenteil. Er erzeugt einen Schalter (es gibt keine Taster als Gerät in HomeKit). Wird der Schalter gedrückt geht er kurz an und nach 500ms wieder aus. Dabei wird die verknüpfte Taste in der CCU betätigt.

Anwendungsbeispiel: Ein Taster in der CCU schaltet eine Lampe ein (direkte Verknüpfung mit Treppenlicht). Dieser kann damit auch aus HomeKit gedrückt werden.

**Comment by ykhnhfr** [comment]
![IMG_1EF8D8DAEA09-1](https://user-images.githubusercontent.com/63097862/108990643-703b3600-7697-11eb-8626-1852eed3a590.jpeg)

Hallo und danke!

Das habe ich genau so gemacht. Ich habe hier den Taster 5, als HomematicKeyAccessory in HomeKit eingebunden. Für die Taste 5 auf dem physischen Schalter habe ich die Automation "Gehen" bei einfachem Druck und "Willkommen" bei langem Druck hinterlegt.  

Für die Taste 6 wollte ich eine andere Funktion hinterlegen. Wenn ich aber die Tasten 1,2,3,4 oder 6 drücke, passiert nichts. die Taste 5 ist die einzige die funktioniert. Das ist doch seltsam. Oder habe ich noch einen Denkfehler?

**Comment by blackbasket** [comment]
Hallo @ykhnhfr,

ich habe es mir jetzt gerade auch mal angeschaut.

So, wie ich es bisher verstanden habe, verstehe ich ehrlich gesagt nicht, warum du den Taster überhaupt einbindest. Du musst dem Taster, der in der CCU ja bereits mit Direktverknüpfungen und/oder Programmen konfiguriert ist, in HomeKit die gleiche Funktion erneut zuweisen. Da würde ich schlichtweg direkt die CCU-Programme in HomeKit hinzufügen.

Oder ist es dein Ziel, dass du dem Taster in HomeKit eine Automation hinzufügst und diese dann auch über den physischen Schalter ausgeführt wird?

LG,
Marcel

**Comment by ykhnhfr** [comment]
Hallo Marcel,

genau. Letzteres ist mein Ziel, eine HomeKit-Automation über den physischen Tastendruck auszuführen. z.B. Musik einer bestimmten Playlist auf allen meinen HomePods. 

Und mit der Taste 5 klappt das auch wunderbar. Hier stellt sich z.B. die Szene Willkommen ein, die Lampen anschaltet, die Musik anmacht und bei kurzem Tastendruck kann ich mit einem Tastendruck sozusagen das ganze Haus "ausschalten". 

Warum auch immer das mit den Tasten 1-4 und 6 nicht klappen will. Dahinter bin ich noch nicht gestiegen.
Ginge es mir um reine Homematic-Themen würde ich das natürlich entsprechend auf der CCU abhandeln. 

LG
Yannick

**Comment by blackbasket** [comment]
Hallo Yannick,

ok, das kann ich nicht so schnell testen. Ich habe im Moment seltsame RM-Abstürze (direkte Aktorensteuerung geht, Programme laufen nicht; alle 2d 22h). Und ich muss dafür erst mal Automationen in HomeKit hinterlegen ;)

LG,
Marcel

**Comment by thkl** [comment]
Bitte einmal debug aktivieren (https://github.com/thkl/hap-homematic/wiki/Troubleshooting#running-in-debug-mode) und die Tasten 1-4 & 6 betätigen. Und dann das Logfile hier anhängen (zumindest den Teil wo die Tasten betätigt wurden)

**Comment by ykhnhfr** [comment]
[hap-homematic-log-2.txt](https://github.com/thkl/hap-homematic/files/6049168/hap-homematic-log-2.txt)

Bitteschön. Ich hatte jetzt nur die Taste 6 in HomeKit "Exposed". 1-4 belege ich nämlich mittlerweile intern in der CCU3. 
Also 5 und 6 habe ich in HomeKit drin. 5 funktioniert gut. 6 funktioniert gar nicht. Log anbei.

**Comment by ykhnhfr** [comment]
Hallo Thomas, gibt's hierzu neues?

**Comment by thkl** [comment]
Moin, 

die Tasten sind wie konfiguriert ? Also Taste in HomeKit und der Button in der CCU wird gedrückt, oder umgedreht, das ein HomeKit Event ausgelöst wird wenn die physische Taste gedrückt wird ?

Denn ich habe zumindest im Log keinerlei Events aus der CCU (also physische Taste wurde gedrückt) gefunden

**Comment by ykhnhfr** [comment]
Moin,

Umgekehrt. Also es soll ein Event ausgelöst werden, wenn physische Tasten gedrückt werden.

Das könnte eine Erklärung sein. Das funktioniert eben nur bei der Taste 5. Die wird physisch gedrückt, läuft auch im Home, bei allen anderen aber nicht.



Am 29.03.2021 um 15:51 schrieb Thomas Kluge ***@***.******@***.***>>:



Moin,

die Tasten sind wie konfiguriert ? Also Taste in HomeKit und der Button in der CCU wird gedrückt, oder umgedreht, das ein HomeKit Event ausgelöst wird wenn die physische Taste gedrückt wird ?

Denn ich habe zumindest im Log keinerlei Events aus der CCU (also physische Taste wurde gedrückt) gefunden

**Comment by thkl** [comment]
Ok aber da haben wir das Problem, im Log taucht kein Event für das Drücken der Taste auf. 

Kannst du mal ein Dummy Programm auf der CCU anlegen, welches auf diese Taste reagiert. Aktionen sind keine nötig einfach nur "kurzen Tastendruck" als Auslösekriterium. 

Background:
Man muss der Schnittstelle mitteilen, das man Events für Kanal X haben möchte. Das mache ich zwar, aber wer weiß. 
Wenn die Schnittstelle es der CCU (Rega) mitteilt, dann auch dem Hap.

**Comment by meistermolli** [comment]
hat hier schon einer was versucht? sonst würde ich das mal ausprobieren? habe einen 6 fach taster hier.

**Comment by ChrWi** [comment]
@meistermolli gerne, wenn es noch passt. Meinen 6er möchte ich hier nicht verbiegen

**Comment by ChrWi** [comment]
@thkl Ich habe jetzt über die "Single Key Accessory" alle 6 Taster in Funktion bekommen. 
Möglicherweise gibt es hier "nur" ein Cache-Problem? 

Nachdem ich 
1. Die angelegten Taster gelöscht,
2. (per ssh Zugriff) manuell den "IdentifierCache" der zugeordneten Instanz gelöscht,
3. HAP neu gestartet,
4. und die Taster wieder neu angelegt habe

geht nun alles wie gewünscht.

1: Musik über HomePod wird gespielt
2: Scene Filmabend wird aktiviert
3: Alle Rollos werden geschaltet
4: Alle Markisen werden geschaltet
5: Garagentor wird bedient
6: Scene Abwesenheit wird aktiviert

**Comment by frankprim** [comment]
Hi, ich habe ein ähnliches Problem wie hier beschrieben. 
Ich will einen Schalter von einem 6-fach Taster in HomeKit "programmieren". Ich habe den Schalter in HAP-HomeMatic eingebunden  <img width="1140" alt="(Screen1)" src="https://github.com/thkl/hap-homematic/assets/76394142/3dfd0712-cd58-4ccb-aff3-01ebd30290da"> . Der Taster wird mir auch in HomeKit angezeigt ![Screen2](https://github.com/thkl/hap-homematic/assets/76394142/56eb2aa9-375b-45c6-acc1-f911899f4e14). Ich habe auch eine Aktion hinterlegt ![Screen3](https://github.com/thkl/hap-homematic/assets/76394142/485a1350-c5d6-4b7e-85b4-14c3633579df) allerdings wird diese nicht ausgeführt. 

Vielleicht weiß jemand wo das Problem liegen könnte?

**Comment by timwegenerDE** [comment]
Ich hab den als MultiChannelKey drin und er funktioniert. Bei manchen Geräte musste ich seit iOS 16.X die Steuerzentrale(n) - also Homepods und AppleTVs danach neustarten, weil die das sonst erst nach ewiger Wartezeit mitbekommen haben, dass die was bei Tastendruck tun sollen.
![IMG_6170](https://github.com/thkl/hap-homematic/assets/56134910/4ca46548-629c-4649-ac0d-f1a62b16ed03)

**Comment by frankprim** [comment]
Ich habe nur diese Auswahlmöglichkeiten
<img width="1137" alt="Bildschirmfoto 2023-05-28 um 11 27 11" src="https://github.com/thkl/hap-homematic/assets/76394142/994626a6-524d-4f51-a366-2bc4797b7926">

**Comment by timwegenerDE** [comment]
Guck mal unter „Besondere Geräte“.

**Comment by ChrWi** [comment]
bzw hier nachlesen: https://github.com/thkl/hap-homematic/wiki/special-devices#multi-channel-push-button

**Comment by frankprim** [comment]
Perfekt danke jetzt hat es geklappt!
