### ISSUE TITLE
Neues Gerät HmIP-STE2-PCB

### ISSUE THREAD

**Issue by belzeb0b** [thkl/hap-homematic#375]
Hallo zusammen,

ich habe folgendes Gerät im Einsatz, welches noch nach Unterstützung bettelt: HmIP-STE2-PCB

Wäre klasse das irgendwann unterstützt zu sehen.

**Comment by belzeb0b** [comment]
{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HmIP-STE2-PCB",
      "address": "1119950877ABCD",
      "type": "HmIP-STE2-PCB",
      "channels": [
        {
          "id": 1001,
          "name": "1119950877ABCD:0",
          "intf": 0,
          "address": "1119950877ABCD:0",
          "type": "MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "1119950877ABCD:1",
          "intf": 0,
          "address": "1119950877ABCD:1",
          "type": "COND_SWITCH_TRANSMITTER_TEMPERATURE",
          "access": 255
        },
        {
          "id": 1003,
          "name": "1119950877ABCD:2",
          "intf": 0,
          "address": "1119950877ABCD:2",
          "type": "COND_SWITCH_TRANSMITTER_TEMPERATURE",
          "access": 255
        },
        {
          "id": 1004,
          "name": "1119950877ABCD:3",
          "intf": 0,
          "address": "1119950877ABCD:3",
          "type": "COND_SWITCH_TRANSMITTER_TEMPERATURE",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by thkl** [comment]
Was ist das denn ? Die Kanäle sehen komisch aus

**Comment by belzeb0b** [comment]
Hallo,

Mensch das ist aber ein schnelles Feedback!

Das ist ein Temperatursensor mit zwei Fühler. Derzeit bei ELV nur als Bausatz verfügbar seid Februar. Spannend, da bis 100 Grad Messvereich. Wollte damit unsere Saunakabine und Aussentemperatur abbilden. 

Kanal 1 und 2 sind Temperatur und Kanal 3 die errechnete Differenz aus 1 und 2.

Beste Grüße

Maik

**Comment by thkl** [comment]
Ok sowas haben wir schon als normales HM Gerät irgendwo .. das kann ich sicher recht schnell umsetzen

**Comment by belzeb0b** [comment]
Vielen Dank!

Ich suche schonmal den Affiliate Link... soviel Einsatz muss belohnt werden. 

Beste Grüße

Maik

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/108751789-f1cd7f80-7542-11eb-8b97-0d3c4dc14ddf.png)

**Comment by thkl** [comment]
Du kannst entweder warten oder dieses File https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/services/HomeMaticThermSensorAccessory.js auf die CCU nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services kopieren und den HAP Dienst danach neu starten.
Es muss dann nur ein Channel von dem Gerät eingefügt werden. Der Service nimmt automatisch alle 3 Kanäle in das Gerät auf (die heißten dann Gerätename ...T1  ... T2 und ... T3)

**Comment by belzeb0b** [comment]
Perfekt, funktioniert!

Vielen Dank

**Comment by mahrens61** [comment]
> 
Lässt sich diese Modul auch in der homebridge einbinden oder gibt es da ein anderes Modul ?

**Comment by jb-home** [comment]
Gibt es auch für Homebridge wird aber schon länger nicht mehr großartig gepflegt.
Da HAP Homematic mit auf der CCU läuft und daher bevorzugt wird.

**Comment by mahrens61** [comment]
Hast Du einen Link zu dem Homebridge Modul ?
Im Github Repo von der Homebridge ist nichts zu finden, bzw. Finde ich nichts.

**Comment by jb-home** [comment]
Steht doch schon im Post drin.
Hier nochmals: https://github.com/thkl/homebridge-homematic

**Comment by mahrens61** [comment]
Ja, das ist der Link zur Homebridge. Die ist ja installiert und läuft. In dieser Homebridge fehlt aber das Modul
Für das Gerät HmIP-STE2-PCB.

**Comment by jb-home** [comment]
Deswegen habe ich aj gesagt, das HAP-Homematic da besser ist, weil es aktueller ist und gelegentlich noch gepflegt wird.
Ich kenne das Gerät von dir jetzt nicht. Gibt es eins was sehr ähnlich ist? Dann könntest du einfach das entsprechende File Kopieren und den identifier entsprechend anpassen.

**Comment by jb-home** [comment]
Ach, das ist der Temperatur Differenz Sensor.
Da könntest du den file von dem alten Nicht IP nehmen  und da ggf. einfach die ID des IPs eintragen. Dann HAP Neustarten.
Kenne die Datenpunkte jetzt nicht, könnte aber klappen.

**Comment by mahrens61** [comment]
Das probiere ich mal. Danke für den Tipp.Von meinem iPhone gesendetAm 31.12.2022 um 16:49 schrieb jb-home ***@***.***>:﻿
Ach, das ist der Temperatur Differenz Sensor.
Da könntest du den file von dem alten Nicht IP nehmen  und da ggf. einfach die ID des IPs eintragen. Dann HAP Neustarten.
Kenne die Datenpunkte jetzt nicht, könnte aber klappen.

**Comment by mx-kms** [comment]
> Du kannst entweder warten oder dieses File https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/services/HomeMaticThermSensorAccessory.js auf die CCU nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services kopieren und den HAP Dienst danach neu starten. Es muss dann nur ein Channel von dem Gerät eingefügt werden. Der Service nimmt automatisch alle 3 Kanäle in das Gerät auf (die heißten dann Gerätename ...T1 ... T2 und ... T3)

Besteht irgendwie die Möglichkeit die Kanäle auch einzeln Anzulegen? 

Danke schonmal für eine Antwort

LG Max

**Comment by MNieddu91** [comment]
> Du kannst entweder warten oder dieses File https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/services/HomeMaticThermSensorAccessory.js auf die CCU nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services kopieren und den HAP Dienst danach neu starten. Es muss dann nur ein Channel von dem Gerät eingefügt werden. Der Service nimmt automatisch alle 3 Kanäle in das Gerät auf (die heißten dann Gerätename ...T1 ... T2 und ... T3)

Hallo, 

ich nutze selbes Gerät, aber leider taucht es bei mir unter den Geräten in HAP nicht auf. Ich gehe davon aus die Neuerung sollte aber mittlerweile im Release sein oder muss ich das File noch manuell kopieren? 

Viele Grüße 
Marco
