### ISSUE TITLE
Neues Gerät HmIP-HDM1

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#376]
Guten Tag,

ich habe mir ein Erfal Sonnenschutzrollo gekauft (https://www.erfal.de/produkte/smarthome/homematic-ip). Dieses Rollo ist zwar erst einmal nur mit dem Homematic AccessPoint kompatibel, Andreas von verdrahtet.info hat allerdings ein Video in dem er zeigt, wie man dieses Rollo auch in die CCU3 bekommt (https://youtu.be/re0Ffeq8mU8).

Nun möchte ich natürlich dieses Rollo auch in Apples Home-App bekommen.
@thkl Ist es möglich dieses Rollo kompatibel mit deinem PlugIn zu bekommen?

![08D566D8-4867-4E8D-ABD2-9A95223599C1](https://user-images.githubusercontent.com/72799068/108757144-c0a47d80-7549-11eb-99a3-04dc93353a3e.png)

**Comment by thkl** [comment]
Kann ich mal das Devicefile dazu haben, das geht übers WEB UI vom HAP und dort Internes / HIlfe

**Comment by gerd2005** [comment]
Das ist ja eine coole Funktion.
Hier, bitte schön:

{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HmIP-HDM1",
      "address": "6296991234ABCD",
      "type": "HmIP-HDM1",
      "channels": [
        {
          "id": 1001,
          "name": "6296991234ABCD:0",
          "intf": 0,
          "address": "6296991234ABCD:0",
          "type": "MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "6296991234ABCD:1",
          "intf": 0,
          "address": "6296991234ABCD:1",
          "type": "SHADING_RECEIVER",
          "access": 255
        },
        {
          "id": 1003,
          "name": "6296991234ABCD:2",
          "intf": 0,
          "address": "6296991234ABCD:2",
          "type": "SHADING_WEEK_PROFILE",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by gerd2005** [comment]
Wichtig wäre vermutlich noch, dass die Werte hier umgedreht sind. Bei meinen HMIP-FROLL ist das Rollo bei 100% oben, bei 0% unten. Bei dem HmIP-HDM1 ist es genau umgekehrt.

**Comment by thkl** [comment]
Ok das reicht noch nicht ganz an Infos. Bitte auf dem CCU WebUI einmal unter Programme / Script testen: das hier laufen lassen:

```
string sDeviceId = 'XXXXX';
string sDpId;
string sChannelId;
object oDevice = dom.GetObject(sDeviceId);
boolean df;
if(oDevice){
 if(df) {df = false;} else { Write(',');}
 Write('{');Write('"id": ' # sDeviceId # ',');
 Write('"name": "' # oDevice.Name().UriEncode() # '",');
 Write('"address": "' # oDevice.Address() # '",');
 Write('"type": "' # oDevice.HssType() # '",');
 Write('"channels": [');
 boolean bcf = true;
 foreach(sChannelId, oDevice.Channels().EnumIDs()){
   object oChannel = dom.GetObject(sChannelId);
   if(bcf) {bcf = false;} else {Write(',');}
   Write('{');Write('"id": ' # sChannelId # ',');
   Write('"name": "' # oChannel.Name().UriEncode() # '",');
   Write('"intf": ' # oDevice.Interface() # ','); 
   Write('"address": "' # oChannel.Address() # '",');
   Write('"type": "' # oChannel.HssType() # '",');
   Write('"access": ' # oChannel.UserAccessRights(iulOtherThanAdmin) # '');
   Write(',');
   Write('"dp":[');
   boolean dcf = true;
   foreach(sDpId,oChannel.DPs().EnumIDs()){
     object oDP = dom.GetObject(sDpId);if(dcf) {dcf = false;} else {Write(',');}Write('{');Write('"id": ' # sDpId # ',');
     Write('"name": "' # oDP.Name() # '"');Write('}');
   }
   Write(']');
   Write('}');}
   Write(']}');
}
```

Wobei in der ersten Zeile bei string sDeviceId = 'XXXXX';  die XXXXX gegen den aktuellen Gerätenamen ersetzt werden müssen.

Das erzeugt ein Ähnliches JSON nur mit den Datenpunkten pro Kanal dazu.

**Comment by gerd2005** [comment]
So korrekt?

,{"id": Innenrollo - Gäste WC,"name": "Innenrollo%20%2D%20G%E4ste%20WC","address": "000044826900EB","type": "HmIP-HDM1","channels": [{"id": 7936,"name": "Innenrollo%20%2D%20G%E4ste%20WC%3A0","intf": 1011,"address": "000044826900EB:0","type": "MAINTENANCE","access": 255,"dp":[{"id": 7937,"name": "HmIP-RF.000044826900EB:0.CONFIG_PENDING"},{"id": 7941,"name": "HmIP-RF.000044826900EB:0.DUTY_CYCLE"},{"id": 7942,"name": "HmIP-RF.000044826900EB:0.ERROR_CODE"},{"id": 7944,"name": "HmIP-RF.000044826900EB:0.LOW_BAT"},{"id": 7948,"name": "HmIP-RF.000044826900EB:0.OPERATING_VOLTAGE"},{"id": 7949,"name": "HmIP-RF.000044826900EB:0.OPERATING_VOLTAGE_STATUS"},{"id": 7950,"name": "HmIP-RF.000044826900EB:0.RSSI_DEVICE"},{"id": 7951,"name": "HmIP-RF.000044826900EB:0.RSSI_PEER"},{"id": 7952,"name": "HmIP-RF.000044826900EB:0.UNREACH"},{"id": 7956,"name": "HmIP-RF.000044826900EB:0.UPDATE_PENDING"}]},{"id": 7960,"name": "HmIP%2DHDM1%20000044826900EB%3A1","intf": 1011,"address": "000044826900EB:1","type": "SHADING_RECEIVER","access": 255,"dp":[{"id": 7961,"name": "HmIP-RF.000044826900EB:1.ACTIVITY_STATE"},{"id": 7962,"name": "HmIP-RF.000044826900EB:1.LEVEL"},{"id": 7963,"name": "HmIP-RF.000044826900EB:1.LEVEL_2"},{"id": 7964,"name": "HmIP-RF.000044826900EB:1.LEVEL_2_STATUS"},{"id": 7965,"name": "HmIP-RF.000044826900EB:1.LEVEL_STATUS"},{"id": 7966,"name": "HmIP-RF.000044826900EB:1.PROCESS"},{"id": 7967,"name": "HmIP-RF.000044826900EB:1.SECTION"},{"id": 7968,"name": "HmIP-RF.000044826900EB:1.SECTION_STATUS"},{"id": 7969,"name": "HmIP-RF.000044826900EB:1.SHADING_SPEED"},{"id": 7970,"name": "HmIP-RF.000044826900EB:1.STOP"}]},{"id": 7971,"name": "HmIP%2DHDM1%20000044826900EB%3A2","intf": 1011,"address": "000044826900EB:2","type": "SHADING_WEEK_PROFILE","access": 255,"dp":[{"id": 7972,"name": "HmIP-RF.000044826900EB:2.COMBINED_PARAMETER"},{"id": 7973,"name": "HmIP-RF.000044826900EB:2.WEEK_PROGRAM_CHANNEL_LOCKS"},{"id": 7974,"name": "HmIP-RF.000044826900EB:2.WEEK_PROGRAM_TARGET_CHANNEL_LOCK"},{"id": 7975,"name": "HmIP-RF.000044826900EB:2.WEEK_PROGRAM_TARGET_CHANNEL_LOCKS"}]}]}

**Comment by thkl** [comment]
👍 schaut von den Datenpunkten genau wie die anderen HMiP Rollos aus. Ich muss das nur hinzufügen und eine Option für diese Umkehr bauen.  Das sollte aber kein großes Thema werden.

**Comment by gerd2005** [comment]
Hervorragend, danke!

**Comment by thkl** [comment]
so ich hab die Klasse angepasst. Es gibt schon die Option für Reverse in den Settings, so das das nicht viel Arbeit war

**Comment by gerd2005** [comment]
Kannst du schon einschätzen, was du die nächste Version veröffentlichst?

**Comment by thkl** [comment]
irgendwann Richtung WE, denke ich mal
