### ISSUE TITLE
Variablen aktualisieren nicht per Trigger

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/hap-homematic#377]
Bei mir aktualisieren Variablen nicht per Trigger, woran kann das liegen ?

**Comment by thkl** [comment]
bitte mal in den Issues hier schauen, das Thema hatten wir schon öfters

**Comment by iuliusmaximilian** [comment]
@thkl Ich bin ratlos, ich weiss natürlich wie das mit den Trigger funktioniert habe ich ja ewig über die Homebridge im Einsatz, aber meine Variablen funktionieren dort nicht mehr und hier mit hap auch nicht. Ich habe zwei kleine Testprogramme geschrieben die den Wert einer Variablen Boolean true/false setzen und den Trigger auslösen. Ich starte die Programme im CCU3 UI, aber das Event kommt nicht im Home an ?! Welches Thema meinst du ?

**Comment by thkl** [comment]
bitte mal übers WebUI den HAP im Debug starten. Dann die Variable ändern und dann im Log schauen ob der Trigger Event ausgelöst wird und die Variablen aktualisiert werden. Das schreibt er ins LOG .. also einen RPC Event für die zugeordnete Taste und dann Rega Events das die Variablen geladen werden.

**Comment by iuliusmaximilian** [comment]
<img width="1680" alt="3" src="https://user-images.githubusercontent.com/28545473/108969089-e2a11b80-7681-11eb-9424-e2b05284e125.png">
<img width="1680" alt="4" src="https://user-images.githubusercontent.com/28545473/108969102-e5037580-7681-11eb-97f8-0c775f495bbd.png">
<img width="1680" alt="2" src="https://user-images.githubusercontent.com/28545473/108969109-e634a280-7681-11eb-8bfa-c03a264347fb.png">
<img width="1680" alt="1" src="https://user-images.githubusercontent.com/28545473/108969112-e6cd3900-7681-11eb-8abd-54c9353cd5bf.png">

**Comment by iuliusmaximilian** [comment]
Anbei das Log, ich habe abwechselnd beide Programm 2x2 AN/AUS/AN/AUS gestartet über das UI der CCU3.
[hap-homematic-log (1).txt](https://github.com/thkl/hap-homematic/files/6034438/hap-homematic-log.1.txt)

**Comment by iuliusmaximilian** [comment]
Habe es nochmal mit Timestamp geprüft, es passiert gar nichts im Log, kein Eintrag beim ändern der Variablen...

**Comment by thkl** [comment]
Ja es kommt auch kein Event an. 
Laut log wird nur einmal gefragt das könnte von HomeKit selber kommen.

**Comment by thkl** [comment]
Ach bitte mal versuchen eine BidCos virtuelle Taste als Trigger zu benutzen. Also nicht die vom HMIP

**Comment by iuliusmaximilian** [comment]
Habe den BidCos-RF.BidCoS-RF:9.PRESS_SHORT konfiguriert und um 11:09-11:10 AN/AUS/HOME-GEÖFFNET/AN/AUS/AN/AUS, Log hat nur...

```
[Wed Feb 24 2021 11:09:57 GMT+0100 (CET)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject(ID_SYSTEM_VARIABLES).Get('Mitteilungen');if (o){Write(o.State());}
[Wed Feb 24 2021 11:09:57 GMT+0100 (CET)] debug - [HAP Server] [Rega] result is false
[Wed Feb 24 2021 11:09:57 GMT+0100 (CET)] debug - [HAP Server] [CCU] Mitteilungen return variable value false
[Wed Feb 24 2021 11:09:57 GMT+0100 (CET)] debug - [HAP Server] [CCU] var Update Event Mitteilungen will be handled by 3 registered callback
```

<img width="1533" alt="2" src="https://user-images.githubusercontent.com/28545473/108985423-539bff80-7691-11eb-8e81-bb9cc3066c6b.png">
<img width="1536" alt="1" src="https://user-images.githubusercontent.com/28545473/108985432-55fe5980-7691-11eb-82ed-aef50a73a70b.png">

**Comment by iuliusmaximilian** [comment]
@thkl ich habe noch weiter versucht experimentiert um es einzugrenzen, aber komme nicht wirklich weiter, die Events kommen nicht im log an, verstehe es nicht ... kannst du mehr debug einbauen ?

**Comment by thkl** [comment]
ich hab noch mal das Log angeschaut. Es fehlen auch die RPC Inits auf die Hardware Schnittstellen in der CCU.
Was sind denn da noch für Geräte eingerichtet ?

**Comment by iuliusmaximilian** [comment]
Habe nur nen CUx 2.5 installiert sonst nichts, letzte Firmware ist auch drauf 3.55.10. Habe auch die Hombridge auf dem Rasp. mal ausgemacht aber das ändert auch nichts. Vielleicht speziell ist noch ein RS485 und RF-LAN Adapter

**Comment by thkl** [comment]
Nope, daran liegt es nicht. 
Ich abonniere die Events für die  jeweiligen Schnittstellen in der CCU nur, wenn mindestens ein Gerät für diese Schnittstelle benutzt wird.

Der Variablen Trigger zählt nicht dazu. Auf die Idee, das jemand nur die Variablen benutzt, bin ich noch nicht gekommen.

Das ist die Erklärung, das keine der Schnittstellenevents ankommen. Wenn also jetzt eine virtuelle HM Taste benutzt wird, sollte mindestens ein HM Gerät mit hinzugefügt werden. Dann gehts.

**Comment by iuliusmaximilian** [comment]
Löst es auch nicht, ich habe mal einen PDT hinzugefügt, dessen Events kommen an, aber es gibt einen error:

Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] ---- launching ----
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] Welcome to HAP Homematic. Use your HomeMatic devices in HomeKit
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] (c) 2021 by @thkl - https://github.com/thkl/hap-homematic
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] Logging into /tmp/hap-homematic.log
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] using configuration at /usr/local/etc/config/addons/hap-homematic
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] Using CCU at 127.0.0.1
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] [Server] settings loading ...
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] [Server] config loading completed; start building servicetable
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] [Server] service loading completed; publishing services
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] [Server] settings loading is done ; continuing init
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] [Server] Using config from /usr/local/etc/config/addons/hap-homematic/persist
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] Spawning configuration service with PID 971
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] [Server] current restart count is  1
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] [Server] Checking rega connection
[Wed Feb 24 2021 21:37:16 GMT+0100 (CET)] info - [HAP Server] [CCU] check Rega is alive
[Wed Feb 24 2021 21:37:26 GMT+0100 (CET)] warn - [HAP Server] [Server] Rega is out of home .. try again in 10 seconds
[Wed Feb 24 2021 21:37:26 GMT+0100 (CET)] info - [HAP Server] [Server] Checking rega connection
[Wed Feb 24 2021 21:37:26 GMT+0100 (CET)] info - [HAP Server] [CCU] check Rega is alive
[Wed Feb 24 2021 21:37:36 GMT+0100 (CET)] warn - [HAP Server] [Server] Rega is out of home .. try again in 10 seconds
[Wed Feb 24 2021 21:37:36 GMT+0100 (CET)] info - [HAP Server] [Server] Checking rega connection
[Wed Feb 24 2021 21:37:36 GMT+0100 (CET)] info - [HAP Server] [CCU] check Rega is alive
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [Server] Rega is alive going ahead
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [Server] continueInitialization
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] loading databases from /usr/local/etc/config/addons/hap-homematic
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] loading object database for devices from /usr/local/etc/config/addons/hap-homematic/devices.json
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] object database loaded 136 objects found
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] device database loaded 136 devices found
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] loading object database for variables from /usr/local/etc/config/addons/hap-homematic/variables.json
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] object database loaded 104 objects found
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] variable database loaded 104 variables found
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] loading object database for programs from /usr/local/etc/config/addons/hap-homematic/programs.json
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] object database loaded 161 objects found
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] program database loaded 161 programs found
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] loading object database for rooms from /usr/local/etc/config/addons/hap-homematic/rooms.json
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] object database loaded 1 objects found
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] room database loaded 1 rooms found
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] disable Monitoring
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] interface BidCos-RF seems not to be in use
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] interface VirtualDevices seems not to be in use
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] interface HmIP-RF seems not to be in use
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] interface CUxD seems not to be in use
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [CCU] interface BidCos-Wired seems not to be in use
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [Server] powering up bridge : HomeMatic default with id b6589fc6-ab0d-4c82-8f12-099d1c2d40ab , userid 12:34:56:30:e1:32 and pinCode  669-94-327
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_default PinCode is 669-94-327
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [Server] publishing accessories
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [Server] 125 compatible devices found
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_default (12:34:56:30:e1:32) is running on port 9877.
[Wed Feb 24 2021 21:37:37 GMT+0100 (CET)] info - [HAP Server] [RPC] server for all interfaces is listening on port 9875.
[Wed Feb 24 2021 21:40:45 GMT+0100 (CET)] info - [HAP Server] [Server] reloading all appliances
[Wed Feb 24 2021 21:40:45 GMT+0100 (CET)] info - [HAP Server] [Server] shutting down Homekit bridge HomeMatic default
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [Server] config loading completed; start building servicetable
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [Server] service loading completed; publishing services
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] loading databases from /usr/local/etc/config/addons/hap-homematic
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] loading object database for devices from /usr/local/etc/config/addons/hap-homematic/devices.json
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] object database loaded 136 objects found
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] device database loaded 136 devices found
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] loading object database for variables from /usr/local/etc/config/addons/hap-homematic/variables.json
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] object database loaded 104 objects found
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] variable database loaded 104 variables found
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] loading object database for programs from /usr/local/etc/config/addons/hap-homematic/programs.json
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] object database loaded 160 objects found
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] program database loaded 160 programs found
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] loading object database for rooms from /usr/local/etc/config/addons/hap-homematic/rooms.json
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] object database loaded 1 objects found
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] room database loaded 1 rooms found
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] interface BidCos-RF seems not to be in use
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] interface VirtualDevices seems not to be in use
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] interface CUxD seems not to be in use
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [CCU] interface BidCos-Wired seems not to be in use
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [Server] powering up bridge : HomeMatic default with id b6589fc6-ab0d-4c82-8f12-099d1c2d40ab , userid 12:34:56:30:e1:32 and pinCode  412-11-821
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [Server] service used for HmIP-PDT 000DD8A98BE1B9:3 is HomeMaticDimmerAccessory
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [Server] add HmIP-PDT 000DD8A98BE1B9:3 to bridge instance b6589fc6-ab0d-4c82-8f12-099d1c2d40ab
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_default PinCode is 412-11-821
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [Server] publishing accessories
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [Server] 125 compatible devices found
[Wed Feb 24 2021 21:40:46 GMT+0100 (CET)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_default (12:34:56:30:e1:32) is running on port 9877.
[Wed Feb 24 2021 21:41:06 GMT+0100 (CET)] error - [HAP Server] [RPC] Error while sending command reportValueUsage to interface HmIP-RF. Error : Error: XML-RPC fault
[Wed Feb 24 2021 21:42:43 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00089BE9A1715D:0.CONFIG_PENDING with value false
[Wed Feb 24 2021 21:42:43 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00089BE9A1715D:0.CONFIG_PENDING
[Wed Feb 24 2021 21:42:43 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00089BE9A1715D:0.UNREACH with value false
[Wed Feb 24 2021 21:42:43 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00089BE9A1715D:0.UNREACH
[Wed Feb 24 2021 21:42:43 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00089BE9A1715D:0.RSSI_DEVICE with value -87
[Wed Feb 24 2021 21:42:43 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00089BE9A1715D:0.RSSI_DEVICE
[Wed Feb 24 2021 21:42:57 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00089BE9A1715D:0.CONFIG_PENDING with value false
[Wed Feb 24 2021 21:42:57 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00089BE9A1715D:0.CONFIG_PENDING
[Wed Feb 24 2021 21:42:57 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00089BE9A1715D:0.UNREACH with value false
[Wed Feb 24 2021 21:42:57 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00089BE9A1715D:0.UNREACH
[Wed Feb 24 2021 21:42:57 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00089BE9A1715D:0.RSSI_DEVICE with value -93
[Wed Feb 24 2021 21:42:57 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00089BE9A1715D:0.RSSI_DEVICE
[Wed Feb 24 2021 21:43:10 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00089BE9A1715D:0.CONFIG_PENDING with value false
[Wed Feb 24 2021 21:43:10 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00089BE9A1715D:0.CONFIG_PENDING
[Wed Feb 24 2021 21:43:10 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00089BE9A1715D:0.UNREACH with value false
[Wed Feb 24 2021 21:43:10 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00089BE9A1715D:0.UNREACH
[Wed Feb 24 2021 21:43:10 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00089BE9A1715D:0.RSSI_DEVICE with value -92
[Wed Feb 24 2021 21:43:10 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00089BE9A1715D:0.RSSI_DEVICE

**Comment by thkl** [comment]
Das ist ein IP Gerät hast Du den Trigger wieder auf eine IP Taste umgestellt ?

**Comment by iuliusmaximilian** [comment]
Zusätzlich auch einen Lc-Dim1T bringt aber auch nichts ?

**Comment by iuliusmaximilian** [comment]
Habe neu gestartet, jetzt habe ich die Events! Aber der Rückgabewert ist immer True obwohl ich zweimal die Variable auf false gesteppt habe ?

[Wed Feb 24 2021 23:04:52 GMT+0100 (CET)] info - [HAP Server] [Server] 125 compatible devices found
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for BidCos-RF.KEQ0971102:2.BOOT with value true
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [CCU] event BidCos-RF.KEQ0971102:2.BOOT
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for BidCos-RF.KEQ0971102:2.ENERGY_COUNTER with value 9.3
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [CCU] event BidCos-RF.KEQ0971102:2.ENERGY_COUNTER
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for BidCos-RF.KEQ0971102:2.POWER with value 0.59
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [CCU] event BidCos-RF.KEQ0971102:2.POWER
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for BidCos-RF.KEQ0971102:2.CURRENT with value 7
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [CCU] event BidCos-RF.KEQ0971102:2.CURRENT
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for BidCos-RF.KEQ0971102:2.VOLTAGE with value 235.7
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [CCU] event BidCos-RF.KEQ0971102:2.VOLTAGE
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for BidCos-RF.KEQ0971102:2.FREQUENCY with value 49.94
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [CCU] event BidCos-RF.KEQ0971102:2.FREQUENCY
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for BidCos-RF.BidCoS-RF:9.PRESS_SHORT with value true
[Wed Feb 24 2021 23:05:17 GMT+0100 (CET)] debug - [HAP Server] [CCU] event BidCos-RF.BidCoS-RF:9.PRESS_SHORT
[Wed Feb 24 2021 23:05:18 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.000A970994F37B:0.CONFIG_PENDING with value false
[Wed Feb 24 2021 23:05:18 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.000A970994F37B:0.CONFIG_PENDING
[Wed Feb 24 2021 23:05:18 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.000A970994F37B:0.UNREACH with value false
[Wed Feb 24 2021 23:05:18 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.000A970994F37B:0.UNREACH
[Wed Feb 24 2021 23:05:18 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.000A970994F37B:0.RSSI_DEVICE with value -97
[Wed Feb 24 2021 23:05:18 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.000A970994F37B:0.RSSI_DEVICE
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:0.CONFIG_PENDING with value false
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:0.CONFIG_PENDING
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:0.RSSI_DEVICE with value -94
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:0.RSSI_DEVICE
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:0.DUTY_CYCLE with value false
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:0.DUTY_CYCLE
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:0.UNREACH with value false
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:0.UNREACH
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:2.SECTION_STATUS with value 0
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:2.SECTION_STATUS
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:2.STATE with value false
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:2.STATE
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:2.SECTION with value 0
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:2.SECTION
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:2.PROCESS with value 0
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:2.PROCESS
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:3.SECTION_STATUS with value 0
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:3.SECTION_STATUS
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:3.STATE with value false
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:3.STATE
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:3.SECTION with value 0
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:3.SECTION
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:3.PROCESS with value 0
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:3.PROCESS
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:4.SECTION_STATUS with value 0
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:4.SECTION_STATUS
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:4.STATE with value false
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:4.STATE
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:4.SECTION with value 0
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:4.SECTION
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:4.PROCESS with value 0
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:4.PROCESS
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:5.SECTION_STATUS with value 0
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:5.SECTION_STATUS
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:5.STATE with value false
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:5.STATE
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:5.SECTION with value 0
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:5.SECTION
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:5.PROCESS with value 0
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:5.PROCESS
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00045A499D2E44:6.WEEK_PROGRAM_CHANNEL_LOCKS with value 0
[Wed Feb 24 2021 23:05:23 GMT+0100 (CET)] debug - [HAP Server] [CCU] event HmIP-RF.00045A499D2E44:6.WEEK_PROGRAM_CHANNEL_LOCKS
[Wed Feb 24 2021 23:05:26 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for BidCos-RF.BidCoS-RF:9.PRESS_SHORT with value true
[Wed Feb 24 2021 23:05:26 GMT+0100 (CET)] debug - [HAP Server] [CCU] event BidCos-RF.BidCoS-RF:9.PRESS_SHORT
[Wed Feb 24 2021 23:05:36 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for BidCos-RF.BidCoS-RF:9.PRESS_SHORT with value true
[Wed Feb 24 2021 23:05:36 GMT+0100 (CET)] debug - [HAP Server] [CCU] event BidCos-RF.BidCoS-RF:9.PRESS_SHORT
[Wed Feb 24 2021 23:05:41 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for BidCos-RF.BidCoS-RF:9.PRESS_SHORT with value true
[Wed Feb 24 2021 23:05:41 GMT+0100 (CET)] debug - [HAP Server] [CCU] event BidCos-RF.BidCoS-RF:9.PRESS_SHORT

**Comment by iuliusmaximilian** [comment]
@thkl Event kommt jetzt an, aber offene Home wird trotzdem nicht aktualisiert?

**Comment by iuliusmaximilian** [comment]
@thkl Mit IP geht es jetzt!

**Comment by iuliusmaximilian** [comment]
Vielen vielen Dank! Vielleicht kannst du noch die Doku aktualisieren, wenn man es weiß ist es ja einfach.
