### ISSUE TITLE
Heizung ändert Temperatur trotz „Fenster auf“

### ISSUE THREAD

**Issue by blackbasket** [thkl/hap-homematic#378]
Hallo zusammen,

ich weiß nicht, ob meine gestrige Beobachtung mit #356 (finde in der App gerade keine Möglichkeit zur Verlinkung) zusammenhängt.

Ich hatte in einer Heizgruppe ein Fenster offen. Entsprechend war die Temperatur auf 6° gesetzt. Dann habe ich die Gruppe im Raum über den Status (oberer Bereich) geöffnet. In dem Moment konnte ich noch sehen, wie von 6° auf 22° gestellt wurde. Die HmIP-eTRV haben dann auch "Fenster auf" und 22° angezeigt.

Der Fehler kann m. E. in dem Fall nur aus den HomeKit-Komponenten kommen, da man bei offenen Fenstern ja am Radiator oder in der CCU machen kann, was man will. Das interessiert die Steuerung ja absolut nicht, solange ich über ein Programm nicht die Lüge "Fenster zu" verbreite.

LG,
Marcel

**Comment by thkl** [comment]
Hmm evtl. könnte es aus einer Änderung des Control Modes kommen. 
Also wenn ein Event dazu führt, das von Auto auf Manuell gestellt wird. Das sollte aber nur beim Ändern des HeatingCooling Modes in HomeKit passieren. 

Bitte mal testen, ob dieses Verhalten reproduzierbar auftritt wenn:

Thermostat im Automatik Mode
Fenster wird geöffnet
Home aufmachen und Thermostat aufrufen ...


Dann sollte, wenn die Temperatur wieder auf 22 Grad geändert wird der Modus im Thermostat auf Manuell wechseln.

**Comment by blackbasket** [comment]
Hallo Thomas,

werde ich testen. Meine Radiatoren waren gestern auf jeden Fall auf manuell. Da ich - im Gegensatz zu den meisten - den Auto-Modus bei Abwesenheit und den Manu-Modus bei Anwesenheit nutze.

LG,
Marcel

**Comment by thkl** [comment]
Also ich hab es gerade mal im Manuellen Mode probiert. Da tritt das nicht auf.  

* Manuell 22 Grad via HomeKit
* Warten bis der Heizungsregler das hat. 
* Fenster auf
* Temp geht auf 12 Grad am Heizungsregler 

* Home App wieder auf : Temp steht auf 12 Grad bleibt auch 

* Fenster zu

* Temp springt auf 22 am Regler 

* Home App auf.  Temp geht da auch auf 22.

**Comment by blackbasket** [comment]
Hast du die Home App nur geöffnet oder auch das Thermostat aufgerufen?

**Comment by thkl** [comment]
Ich habe jedes Mal Home gekillt und das Thermostat mit ForceTouch aufgerufen. Das die Detailview mit dem großen Temperaturselektor angezeigt wird. 

Eben eben noch mal im Auto Mode probiert. Da verhält es sich erst mal genau so wie es soll. Die Temp bleibt auf 12 Grad stehen. 

🤔

**Comment by blackbasket** [comment]
Ok :) werd's möglichst nachher komplett testen... vllt liegt's ja am Status-Icon...

**Comment by thkl** [comment]
Wenn das reproduzierbar auftritt bitte mal das Debuglog anschalten. Der Thermostat Service ist sehr gesprächig warum was wie berechnet und gesetzt wird.  Das würde mit helfen.

**Comment by blackbasket** [comment]
Bin noch unterwegs, aber muss ich das Addon neu starten, nachdem ich Debug einschalte?

**Comment by thkl** [comment]
nope

**Comment by blackbasket** [comment]
Guten Morgen,

anbei die Logs. Ich kann es nur im Manu-Mode reproduzieren. Logs gibt es trotzdem für beide.

LG,
Marcel
[auto-mode.txt](https://github.com/thkl/hap-homematic/files/6041190/auto-mode.txt)
[manu-mode.txt](https://github.com/thkl/hap-homematic/files/6041191/manu-mode.txt)

**Comment by thkl** [comment]
OK das einzige Mal wo die Temperatur gesetzt wird ist durch einen Befehl aus Homekit, der den "TargetHeatingCoolingState" setzt. Im Manu Log um 08:24:22 wird der Status auf Heizen gesetzt. Es wird dann die letzte gesetzte Temperatur ermittelt (das waren 22 Grad) und das ans Thermostat geschickt.

Ich sehe aber das Problem: Als zuletzt gesetzte Temperatur merke ich mir nur die Temperatur die aus HomeKit als Soll kommt. Also quasi die letzte Einstellung.  Es kommt vorher ein Event aus der CCU welcher die Soll Temperatur auf 6 Grad setzt. Ich werde den mal nutzen um die dort gesendete Temperatur auch zwischenzuspeichern.

Ob damit was anderes kaputt geht wird sich zeigen 😎

**Comment by blackbasket** [comment]
Hallo Thomas,

klingt gut ;)

LG,
Marcel

**Comment by thkl** [comment]
siehe Nachtrag oben. So einfach ist es nicht.

**Comment by thkl** [comment]
Es gibt aber im Channel 1 einen Datenpunkt Window State. Den könnte ich quasi als inhibit für HomeKit nutzen.
Wenn der gesetzt ist, gehen keine Events aus HomeKit an die CCU ? ...

**Comment by blackbasket** [comment]
Verdammt ;) also für mich ist das auch wirklich kein dringendes Problem... ich verwende HomeKit weiterhin nur zur Sprachsteuerung, alles andere mache ich über die EASY App... mir ist es halt nur aufgefallen... deshalb wollte ich es melden...

**Comment by blackbasket** [comment]
Das klingt für mich richtig... die CCU interessiert ja auch keine Eingabe, solange ein TFK offen ist...

**Comment by blackbasket** [comment]
ich bekomme das gerade nicht mehr reproduziert, daher closed
