### ISSUE TITLE
Gerät bearbeiten = Anzeige in Favoriten

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#38]
Wenn man ein Gerät bearbeitet und dann wieder speichert, wird automatisch der Schalter gesetzt, dass dieses Gerät in den Favoriten angezeigt werden soll - obwohl dies zuvor garnicht ausgewählt war.

**Comment by roe1974** [comment]
ich glaub im standard wandert bei HK jedes neue/bearbeitete gerät auch zu den favoriten ... weiß nicht ob Thomas das mitgeben kann (favorit ja/nein)
lg Richard

**Comment by thkl** [comment]
Nein ich kann da nichts machen. Das Gerät kommt  mit der gleichen UUID wieder zu HomeKit ggf natürlich mit geänderten Parametern. 
Interessant wäre es zu wissen, ob nach einem Hap restart auch alle Geräte wieder in den Favoriten sind (Spoiler bei mir nicht)

**Comment by roe1974** [comment]
it‘s a feature 😉😉😜😜

**Comment by thkl** [comment]
Ah, bei einigen Geräten beschwert sich Home beim Speichern das angeblich ungültige Zeichen drin wären, vielleicht liegt es daran. Ich habe einen Aktor der heisst blabla On/Off .. .wenn ich das On/Off im Namen (direkt in der HomeApp) lösche, dann speichert er das Flag

**Comment by roe1974** [comment]
kenne das zB von den cams (homebridge-ffmpeg) ... da musste ich 3x das flag setzten damit HK es sich "merkt" .... komisch

**Comment by thkl** [comment]
Möchte jemand bei Apple nen Bug auf machen ? Bitte hier entlang : bugreport.apple.com ;-)

**Comment by detLAN** [comment]
Also ich glaube da noch nicht an einen Apple Bug.
Habe mir diverse Geräte in der Home App genommen und den Namen geändert - keine Änderung bei Favoriten.
Jetzt hab ich mir die gleichen Geräte in HAP rausgesucht und dort den Namen geändert - hier werden die Geräte dann in Favoriten angezeigt.

Ein Neustart des HAP Service ändert nichts an den Geräten bzw. Räumen.

**Comment by thkl** [comment]
ich kann aber keinerlei Flags für die Favoriten oder sowas mit nach HomeKit liefern ..

**Comment by detLAN** [comment]
Schade, dann kann m.E. dieser issue aber geschlossen werden.

**Comment by thkl** [comment]
Ich werde das mal etwas beobachten, ggf liegt es ja wirklich am Namen, den ich versende.

**Comment by detLAN** [comment]
Jetzt muss hier doch noch mal einen Hinweis loswerden. Kann es sein, dass das Problem am _ liegt (HomeMatic_)? Wenn ich den Namen einer Bridge ändere, das HomeMatic_ jedoch belasse, bekomme ich eine Fehler bezüglich eines unerlaubten Zeichens. Nehme ich - anstatt _ funktioniert die Umbenennung.

**Comment by thkl** [comment]
Jep, das könnte das Problem sein. Ich schau mal, ob ich die Bridge HAP seitig umbenennen kann, ohne das irgendwas im Client kaputt geht.  Dürfte aber eigentlich nicht, denn HomeKit identifiziert alles anhand UUIDs.

**Comment by thkl** [comment]
In Zukunft werden die Instanzen HomeMatic .... heissen also mit Leerzeichen statt _ .
Allerdings habe ich festgestellt, das sich HomeKit nicht um eine Änderung der Seriennummer/Namen des Gerätes kümmert, solange die ID gleich geblieben ist. Die möchte ich jetzt nicht ändern, denn sonst verliert das Gerät seinen Raum (und damit alle an der Instanz hängenden Geräte auch)

Also müsste man bei Speicherprobleme manuell den Namen ändern ...
Bei neu angelegten Instanzen sollte das dann nicht mehr auftauchen.

**Comment by detLAN** [comment]
Wie werden die vorhandenen Instanzen auf der HAP editiert? HomeMatic_ ist ja fest vorgegeben, dies kann nicht bearbeitet werden.

**Comment by thkl** [comment]
hier wird einfach HomeMatic_ gegen HomeMatic[Leerzeichen] ersetzt.
Allerdings kümmert das HomeKit nicht .. da bleibt der Name ... siehe oben, der vorhandene Namen muss manuell geändert werden, wenn diese "ich kann nicht speichern" Meldung kommt.
Für zukünftig neue Bridges sollte das nicht mehr passieren

**Comment by detLAN** [comment]
Okay, prima. In der Home App hab ich dass dann schon mal erledigt ☺️

**Comment by detLAN** [comment]
Nach dem ich mit v37 komplett neu gestartet war, hab ich es mit dem Ändern noch einmal getestet. Weiterhin werden HomeMatic Geräte in Favoriten angezeigt obwohl diese vorher dort nicht waren. Da vermutet wurde, dass es sich um ein HomeKit Bug handelt, hab ich Hue Geräte in der Hue App geändert, genauso auch Eve Geräte. Hier tritt das Problem nicht auf.
Also hab ich nach weiteren möglichen Uhrsachen gesucht und bin evtl. bei der Seriennummer fündig geworden. HomeMatic Geräte sind mit dem Namen der CCU gefolgt von _ und der HomeMatic Seriennummer eingepflegt. Die Hue Geräte besten aus Blöcken von zwei Ziffern getrennt durch ein Doppelpunkt. Die Eve Geräte, welche ja explizit für HomeKit entwickelt wurde, haben eine Seriennummer aus Buchstaben und Zahlen.
Vielleicht stört hier ja weiterhin der _ bei HomeMatic Geräten. Warum nicht einfach nur die Seriennummer nehmen?

**Comment by roe1974** [comment]
Aber wenn du den Schalter einmalig deaktivierst, sind die Geräte aus den Favortien draussen ... oder ? .. ist zumindest bei mir so .... 
Und zur Info .. alle meine Hombridge Geräte (TV, Http Motion, Nest..) wurden beim initialen hinzufügen auch alle zu den Favoriten hinzugefügt....aber einmal deaktiviert ... sind sie dort dann weg....
Oder wann springen Sie bei dir in die Favoriten zurück ? ... wenn du In HAP was am Gerät änderst oder in HomeKit ?

lg Richard

**Comment by detLAN** [comment]
Hi Richard,
genauso wie Du es beschreibst verhält es sich. Und gemeint ist wenn ich nachträglich im HAP etwas ändere, dann wandert das Gerät erneut in die Favoriten. Bei Hue ist dies nicht so.
Beste Grüße
Detlef

**Comment by detLAN** [comment]
Ergänzung: Das Gerät wandert nich nur ich die Favoriten, es wandert auch im Raum an das Ende der Liste. Bei Hue und Eve passiert dies nicht, wenn man in deren entsprechenden Haus App etwas am Gerät ändert.

**Comment by roe1974** [comment]
die frage ist wie oft man im HAP an einem Gerät etwas ändern muss ;)
Aber bei Homebridge ist das bei mir auch so ... neues gerät bzw. bestehendes gerät ändern (dabei fliegt es ja raus und kommt neu rein) und der schalter favoriten ist auf „ein“ und das gerät
ist das letzte im raum ....

**Comment by detLAN** [comment]
Das stimmt schon, dass das nicht so häufig vorkommen wird. Aber wenn das Gerät beim ändern dann in HomeKit gelöscht und wieder neu eingesetzt wird, dann erklärt dies natürlich das dann richtige Verhalten.
