### ISSUE TITLE
Support for HM-ES-TX-WM

### ISSUE THREAD

**Issue by KlausBueker** [thkl/hap-homematic#382]
Hallo,

der HM-ES-TX-WM wird noch nicht unterstützt? Ich betreibe ihn mit dem IEC Powermeter.

[HM-ES-TX-WM.zip](https://github.com/thkl/hap-homematic/files/6049759/HM-ES-TX-WM.zip)

VG
Klaus

**Comment by thkl** [comment]
Doch doch, er wird unterstützt. Channel 1 taucht als HomeMaticPowerMeterAccessory auf:

Allerdings kann nur Eve etwas damit anfangen. Es gibt kein solches Gerät direkt in Home

![image](https://user-images.githubusercontent.com/884355/109332305-32d4d500-785e-11eb-9bed-47f0f0dd2cde.png)

**Comment by thommyDD** [comment]
Bei mir taucht er leider nicht in der Liste auf. Woran könnte das liegen.

vG
Thomas

**Comment by thkl** [comment]
Ah, das scheint eine neue Version des Gerätes zu sein. Der Kanal heisst jetzt POWERMETER_IEC1 .. ich füge den hinzu, dann geht es im nächsten Release

**Comment by thommyDD** [comment]
Danke für deine schnelle Rückmeldung! Dann freue ich mich auf das nächste Release. BTW: vielen Dank für deine tolle Arbeit hier 🙂
