### ISSUE TITLE
HmIP-SWO-PL wird nicht erkannt

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/hap-homematic#386]
Meine HmIP-SWO-PL wird nicht erkannt, in Homebridge hatte das problemlos funktioniert. Wird die noch nicht unterstützt oder ist da was kaputt?

![3ED3324E-2B2E-40BF-A7C9-01907DF1C452](https://user-images.githubusercontent.com/28545473/109425679-bb33b100-79e9-11eb-9a05-ebc711d5babe.jpeg)
![74CCDEBD-57ED-41CF-8D2E-5FEFE89312C9](https://user-images.githubusercontent.com/28545473/109425686-bf5fce80-79e9-11eb-939c-b41c06e4746e.jpeg)

**Comment by thkl** [comment]
Damit das in der Home App funktioniert muss in den Settings von HAP die Option "Apple Home kompatibel" eingestellt werden.

Dann werden einige Geräte etwas modifiziert sodas sie in Home funktionieren.
Es geht dann zwar die Eve History verloren, aber wenn man Home nutzt wird die eh nicht angezeigt.

**Comment by iuliusmaximilian** [comment]
Klasse, ich habe jetzt wirklich alle 191 Geräte von Homebridge rüber migriert - MEGA!

**Comment by thkl** [comment]
Backup nicht vergessen 😁
Obwohl das ist auch im CCU Backup drin.
