### ISSUE TITLE
Neues Gerät HmIP-SCTH230

### ISSUE THREAD

**Issue by timwegenerDE** [thkl/hap-homematic#387]
Halli hallo,

ich hätte da eine neue Spielerei: Ein CO2-Sensor.
Kann man damit in der Home- / Eve-App überhaupt was anfangen?

{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HmIP-SCTH230",
      "address": "5499157171ABCD",
      "type": "HmIP-SCTH230",
      "channels": [
        {
          "id": 1001,
          "name": "5499157171ABCD:0",
          "intf": 0,
          "address": "5499157171ABCD:0",
          "type": "MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "5499157171ABCD:1",
          "intf": 0,
          "address": "5499157171ABCD:1",
          "type": "CARBON_DIOXIDE_RECEIVER",
          "access": 255
        },
        {
          "id": 1003,
          "name": "5499157171ABCD:2",
          "intf": 0,
          "address": "5499157171ABCD:2",
          "type": "COND_SWITCH_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1004,
          "name": "5499157171ABCD:3",
          "intf": 0,
          "address": "5499157171ABCD:3",
          "type": "COND_SWITCH_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1005,
          "name": "5499157171ABCD:4",
          "intf": 0,
          "address": "5499157171ABCD:4",
          "type": "CLIMATE_TRANSCEIVER",
          "access": 255
        },
        {
          "id": 1006,
          "name": "5499157171ABCD:5",
          "intf": 0,
          "address": "5499157171ABCD:5",
          "type": "COND_SWITCH_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1007,
          "name": "5499157171ABCD:6",
          "intf": 0,
          "address": "5499157171ABCD:6",
          "type": "COND_SWITCH_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1008,
          "name": "5499157171ABCD:7",
          "intf": 0,
          "address": "5499157171ABCD:7",
          "type": "SWITCH_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1009,
          "name": "5499157171ABCD:8",
          "intf": 0,
          "address": "5499157171ABCD:8",
          "type": "SWITCH_VIRTUAL_RECEIVER",
          "access": 255
        },
        {
          "id": 1010,
          "name": "5499157171ABCD:9",
          "intf": 0,
          "address": "5499157171ABCD:9",
          "type": "SWITCH_VIRTUAL_RECEIVER",
          "access": 255
        },
        {
          "id": 1011,
          "name": "5499157171ABCD:10",
          "intf": 0,
          "address": "5499157171ABCD:10",
          "type": "SWITCH_VIRTUAL_RECEIVER",
          "access": 255
        },
        {
          "id": 1012,
          "name": "5499157171ABCD:11",
          "intf": 0,
          "address": "5499157171ABCD:11",
          "type": "DIMMER_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1013,
          "name": "5499157171ABCD:12",
          "intf": 0,
          "address": "5499157171ABCD:12",
          "type": "DIMMER_VIRTUAL_RECEIVER",
          "access": 255
        },
        {
          "id": 1014,
          "name": "5499157171ABCD:13",
          "intf": 0,
          "address": "5499157171ABCD:13",
          "type": "DIMMER_VIRTUAL_RECEIVER",
          "access": 255
        },
        {
          "id": 1015,
          "name": "5499157171ABCD:14",
          "intf": 0,
          "address": "5499157171ABCD:14",
          "type": "DIMMER_VIRTUAL_RECEIVER",
          "access": 255
        },
        {
          "id": 1016,
          "name": "5499157171ABCD:15",
          "intf": 0,
          "address": "5499157171ABCD:15",
          "type": "DIMMER_WEEK_PROFILE",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by timwegenerDE** [comment]
Und hier noch die Datenpunkte. Interessant ist m.E. nur Kanal 1; Temperatur und Luftfeuchtigkeit erkennt hap-homematic schon und auch der Umweg über eine Variable für den Co2-Wert funktioniert:

HmIP-RF.002D1D898AD298:0.CONFIG_PENDING
HmIP-RF.002D1D898AD298:0.DUTY_CYCLE
HmIP-RF.002D1D898AD298:0.ERROR_CODE
HmIP-RF.002D1D898AD298:0.OPERATING_VOLTAGE
HmIP-RF.002D1D898AD298:0.OPERATING_VOLTAGE_STATUS
HmIP-RF.002D1D898AD298:0.RSSI_DEVICE
HmIP-RF.002D1D898AD298:0.RSSI_PEER
HmIP-RF.002D1D898AD298:0.UNREACH
HmIP-RF.002D1D898AD298:0.UPDATE_PENDING
**HmIP-RF.002D1D898AD298:1.CONCENTRATION
HmIP-RF.002D1D898AD298:1.CONCENTRATION_STATUS**
HmIP-RF.002D1D898AD298:4.ACTUAL_TEMPERATURE
HmIP-RF.002D1D898AD298:4.ACTUAL_TEMPERATURE_STATUS
HmIP-RF.002D1D898AD298:4.HUMIDITY
HmIP-RF.002D1D898AD298:4.HUMIDITY_STATUS
HmIP-RF.002D1D898AD298:7.PROCESS
HmIP-RF.002D1D898AD298:7.SECTION
HmIP-RF.002D1D898AD298:7.SECTION_STATUS
HmIP-RF.002D1D898AD298:7.STATE
HmIP-RF.002D1D898AD298:8.COMBINED_PARAMETER
HmIP-RF.002D1D898AD298:8.ON_TIME
HmIP-RF.002D1D898AD298:8.PROCESS
HmIP-RF.002D1D898AD298:8.SECTION
HmIP-RF.002D1D898AD298:8.SECTION_STATUS
HmIP-RF.002D1D898AD298:8.STATE
HmIP-RF.002D1D898AD298:9.COMBINED_PARAMETER
HmIP-RF.002D1D898AD298:9.ON_TIME
HmIP-RF.002D1D898AD298:9.PROCESS
HmIP-RF.002D1D898AD298:9.SECTION
HmIP-RF.002D1D898AD298:9.SECTION_STATUS
HmIP-RF.002D1D898AD298:9.STATE
HmIP-RF.002D1D898AD298:10.COMBINED_PARAMETER
HmIP-RF.002D1D898AD298:10.ON_TIME
HmIP-RF.002D1D898AD298:10.PROCESS
HmIP-RF.002D1D898AD298:10.SECTION
HmIP-RF.002D1D898AD298:10.SECTION_STATUS
HmIP-RF.002D1D898AD298:10.STATE
HmIP-RF.002D1D898AD298:11.ACTIVITY_STATE
HmIP-RF.002D1D898AD298:11.LEVEL
HmIP-RF.002D1D898AD298:11.LEVEL_STATUS
HmIP-RF.002D1D898AD298:11.PROCESS
HmIP-RF.002D1D898AD298:11.SECTION
HmIP-RF.002D1D898AD298:11.SECTION_STATUS
HmIP-RF.002D1D898AD298:12.ACTIVITY_STATE
HmIP-RF.002D1D898AD298:12.COMBINED_PARAMETER
HmIP-RF.002D1D898AD298:12.LEVEL
HmIP-RF.002D1D898AD298:12.LEVEL_STATUS
HmIP-RF.002D1D898AD298:12.ON_TIME
HmIP-RF.002D1D898AD298:12.PROCESS
HmIP-RF.002D1D898AD298:12.RAMP_TIME
HmIP-RF.002D1D898AD298:12.SECTION
HmIP-RF.002D1D898AD298:12.SECTION_STATUS
HmIP-RF.002D1D898AD298:13.ACTIVITY_STATE
HmIP-RF.002D1D898AD298:13.COMBINED_PARAMETER
HmIP-RF.002D1D898AD298:13.LEVEL
HmIP-RF.002D1D898AD298:13.LEVEL_STATUS
HmIP-RF.002D1D898AD298:13.ON_TIME
HmIP-RF.002D1D898AD298:13.PROCESS
HmIP-RF.002D1D898AD298:13.RAMP_TIME
HmIP-RF.002D1D898AD298:13.SECTION
HmIP-RF.002D1D898AD298:13.SECTION_STATUS
HmIP-RF.002D1D898AD298:14.ACTIVITY_STATE
HmIP-RF.002D1D898AD298:14.COMBINED_PARAMETER
HmIP-RF.002D1D898AD298:14.LEVEL
HmIP-RF.002D1D898AD298:14.LEVEL_STATUS
HmIP-RF.002D1D898AD298:14.ON_TIME
HmIP-RF.002D1D898AD298:14.PROCESS
HmIP-RF.002D1D898AD298:14.RAMP_TIME
HmIP-RF.002D1D898AD298:14.SECTION
HmIP-RF.002D1D898AD298:14.SECTION_STATUS
HmIP-RF.002D1D898AD298:15.COMBINED_PARAMETER
HmIP-RF.002D1D898AD298:15.WEEK_PROGRAM_CHANNEL_LOCKS
HmIP-RF.002D1D898AD298:15.WEEK_PROGRAM_TARGET_CHANNEL_LOCK
HmIP-RF.002D1D898AD298:15.WEEK_PROGRAM_TARGET_CHANNEL_LOCKS

**Comment by thkl** [comment]
der CO2 Wert kann in Eve dargestellt werden:

![image](https://user-images.githubusercontent.com/884355/109703929-55385c80-7b96-11eb-9673-6665165ac871.png)

**Comment by timwegenerDE** [comment]
Hab's auch gerade gesehen, als ich den Umweg über die Variable beim Temperatur-Sensor gefunden habe. In der Home-App zeigt er mir zumindest die Luftqualität "sehr gut" mit an. Das ist ja schonmal was :)

**Comment by thkl** [comment]
HmIP-RF.:1.CONCENTRATION ist der CO2 ppm Wert ?

**Comment by timwegenerDE** [comment]
Genau:
<img width="1052" alt="Bildschirmfoto 2021-03-02 um 20 37 02" src="https://user-images.githubusercontent.com/56134910/109704661-28d11000-7b97-11eb-9b8d-d2bfc0b965a7.png">

**Comment by thkl** [comment]
ok das bekomme ich hin

**Comment by timwegenerDE** [comment]
Ich glaube der Rest geht schon:
<img width="1115" alt="Bildschirmfoto 2021-03-02 um 20 42 11" src="https://user-images.githubusercontent.com/56134910/109705205-ccbabb80-7b97-11eb-9870-5c3db177518a.png">

**Comment by thkl** [comment]
Die nehmen aber auch einen stolzen Preis für das Gerät ... ;)

**Comment by timwegenerDE** [comment]
Ach hör doch auf... Schon nicht feierlich...! 💸 🤣

**Comment by thkl** [comment]
genau eigentlich könnten die mir jedes neue Gerät unaufgefordert zuschicken ;)

**Comment by timwegenerDE** [comment]
Damit kann ich zwar nicht dienen, aber sobald du den in hap eingebaut hast, bekommst du nochmal 'nen Kaffee von mir gesponsored 😄 Hat aber keine Eile, hab ja einen Workaround... 🤪

**Comment by thkl** [comment]
Das ist kein großes Problem ich kann, so wie ich das sehe zu 95% das normale Thermometer kopieren

**Comment by thkl** [comment]
Werte sind randomly aus dem CCU Simulator ... aber so würde das Ding dann aussehen ...

![IMG_0026](https://user-images.githubusercontent.com/884355/109846698-bde31000-7c4e-11eb-9a0d-7dc1ff17ccfd.PNG)

![IMG_0025](https://user-images.githubusercontent.com/884355/109846714-c0de0080-7c4e-11eb-88d3-47fb4d56518b.PNG)

**Comment by timwegenerDE** [comment]
Das sieht doch sehr gut aus 👍 
Sagst du Bescheid sobald ich testen kann / darf / soll? :)

**Comment by thkl** [comment]
Das File hier

https://github.com/thkl/hap-homematic/blob/master/lib/services/HomeMaticIPCO2Accessory.js

muss nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/  (da liegen die ganzen Servicefiles)

Dann hap restart und das Gerät sollte auswählbar sein.

**Comment by timwegenerDE** [comment]
Funktioniert wunderbar; Der versprochene Kaffee ist auf dem Weg ;)

Danke dir und bis zum nächsten mal 😄
