### ISSUE TITLE
HmIP-WTH-2 und HmIP-STHD, Luftfeuchte fehlt

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#39]
Die Geräte HmIP-WTH-2 und HmIP-STHD stellen auch die Luftfeuchtigkeit zur Verfügung. Diese wird leider nicht übergeben.

**Comment by thkl** [comment]
Die brachte ich aber.  Ist zufällig in den Gerätesettings das ignore humidity flag gesetzt ?

**Comment by detLAN** [comment]
HmIP-STHD funktioniert, falscher Service war aktiviert. Allerdings müsste es eine Kombination beider Services sein, da man so nur Einstellen oder nur Darstellen zur Verfügung hat.
<img width="568" alt="Bild5" src="https://user-images.githubusercontent.com/64675966/80872187-a050bd00-8cb0-11ea-9449-dec86f7391a4.png">

Beim HmIP-WTH-2 fehlt der Service.
<img width="559" alt="Bild6" src="https://user-images.githubusercontent.com/64675966/80872311-616f3700-8cb1-11ea-829e-86c6ca089c86.png">

**Comment by thkl** [comment]
Ah ich verstehe die Feuchtigkeitsangabe fehlt beim Thermostat ? Ok
HmIP-WTH-2 mach ich

**Comment by detLAN** [comment]
Wichtig wäre jedoch auch, dass beide Services zusammengefasst werden. Ansonsten muss man entscheiden ob man das Geräte bedienen möchte, ohne Luftfeuchte. Oder aber man bekommt nur Temperatur und Luftfeuchte angezeigt. Auf der CCU hat man alles in einer Geräteansicht.
<img width="699" alt="Bild7" src="https://user-images.githubusercontent.com/64675966/80878172-d5164180-8cbb-11ea-9f0d-866d7c2f4c62.png">

Dies gilt natürlich für HmIP-WTH-2 und HmIP-STHD.

**Comment by thkl** [comment]
Ich werde die Feuchtigkeitsangabe einfach dem Thermostat hinzufügen. Dann passt es wieder

**Comment by detLAN** [comment]
Perfekt!

**Comment by detLAN** [comment]
Erledigt, die Feuchtigkeit wird mit v38 übermittelt. Wird in Eve dargestellt, Home App unterstützt dies offensichtlich nicht.

**Comment by thkl** [comment]
Ich hab schon mal bissel rumprobiert man könnte versuchen die Feuchtigkeit als 2. Sensor in das Gerät aufzunehmen und nicht als Characteristic zum Thermostat...

Das könnte dann auch Home anzeigen. 

Deswegen lass ich das hier erst mal noch offen. 

So habe ich die Wetterstation Home Kompatibel gemacht.  Man kann die so einstellen, das zumindest Temperatur Feuchtigkeit und Helligkeit in  Home angezeigt werden. 

Das geht über mehrere Sensoren in einem Gerät.

**Comment by detLAN** [comment]
Ich hätte da dann doch noch eine Anmerkung:
<img width="279" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81228876-25104380-8fef-11ea-860b-853a4c6ad1df.png">
Wenn ich auf die Ein- / Ausschaltfläche (orang ausgefüllter Kreis) betätige passiert nichts - wenn der Heizkörper im Automatik Modus steht. Stelle ich in der CCU auf manuell, kann ich mittels des orangen Knopfs entsprechend schalten. Dies ist in der Home App genauso wie in der Eve App, bei beiden fehlt die Möglichkeit zwischen manuell und automatisch zu wechseln.

Wenn man die Boost Schaltfläche mit integriert hat, fehlt zwischen Gerätenamen und "Boost Mode" ein Leerzeichen.

**Comment by roe1974** [comment]
verstehe ich nicht ganz ... die Luftfeuchtigkeit wird doch eh im Gerät angezeigt ?
...und der Boost Schalter kann in HK umbennant werden....

**Comment by thkl** [comment]
OK, derzeit schalte ich die Heizung auf 4,5 Grad bei Off.  Da muss noch ein ManuMode Command vorneweg.

**Comment by detLAN** [comment]
> Beim HM Thermostat wird die Luftfeuchtigkeit angezeigt ...und der Boost Schalter kann in HK umbennant werden....

Du hast in HAP unter Service HomeMaticThermometerAccessory gewählt. Damit kannst Du dass Gerät dann nicht bedienen. Nimmst Du statt dessen HomeMaticRadiatorThermometerAccessory, kann das Gerät bedient werden. Und dort fehlt die Luftfeuchte in der Home App.
Das ich den Boost Schalter umbenennen kann ist mir bewusst. Es ging mir hier nur um den Automatismus wenn man "Add a boost mode switch" gewählt hat. Hier könnte das Leerzeichen doch gleich mit gegeben werden.

**Comment by detLAN** [comment]
> OK, derzeit schalte ich die Heizung auf 4,5 Grad bei Off. Da muss noch ein ManuMode Command vorneweg.

Das würde funktionieren, nur sollte beim On schalten dann wieder der ursprüngliche Zustand wieder hergestellt werden - kann ja sein, dass jemand gar nicht auf Automatik stehen hatte.

**Comment by roe1974** [comment]
aso ... klar (leerzeichen)
und nein ... ich verwende "HomeMaticThermostatAccessory" ... das ist bedienbar (ist ein HM-TC-IT-WM-W-EU)
lg Richard

**Comment by thkl** [comment]
> Das würde funktionieren, nur sollte beim On schalten dann wieder der ursprüngliche Zustand wieder hergestellt werden - kann ja sein, dass jemand gar nicht auf Automatik stehen hatte.

Natürlich :) ich muss mir ja eh schon die Temperatur vor Off merken, um sie bei On wieder einzustellen.
