### ISSUE TITLE
Valve / Faucet Service erweitern

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#390]
Hallo,

Was meinst du wie hoch der Aufwand für so etwas wäre?

kannst du die in der neuen 59 enthaltenen Valve / Fauchet / etc...     Services bitte auch anlegen für:

Variablen;
Geräte:
- virtuelle Taster;
Besondere Geräte:
MultiChannelPuschButtonService;

Aktuell kann man diese ja für z.B. den Relais Ausgang eines PCBS auswählen.
Da ich aber die Programme in der Homematic CCU habe, übergebe ich das an Homekit über Variablen und Virtuelle Taster.

So auch meinen Wasserspender / Wasserhahn. wäre nice, wenn der auch als Wasserhahn angezeigt würde.
(Den habe ich aktuell über MultiChannelPuschButtonService eingebunden für verschiedene Füllstände)

Zudem kommt jetzt im Frühjahr eine Bewässerung, da werde ich denke ich auch **nicht** die Relaisplatine selber einbinden, sondern eher virtuelle Taster und Variablen ... 
Da ich auch z.B: auf das wetter / regen und meinen Mähroboter reagieren muss bei der Bewässerung, kann ich das nicht in Homekit Abbilden und das Ventil selber einbinden.

Zudem wie in dem Issue #383 beschrieben. Gibt es 3 Arten von Ventilen:

NC Normaly Closed
NO Normaly opened
und welche die in beiden Lagen Stabil sind. (Hier werden 2 Relais benötigt)
(also wäre ein Invertieren der Schaltung schon sinnvoll)

Danke und Gruß meistermolli.

**Comment by thkl** [comment]
U lost me at Faucet ...


Also ich kann ja sowas nur für Aktoren machen, die einen Switch State haben also ein oder aus. 

Und das sollte doch so drin sein ?

**Comment by meistermolli** [comment]
Ja dem aktor konnte ich das zuordnen.


Also kannst du einer variablen,
die ja auch wie ein Schalter agiert das nicht aneignen?

Man kann auch kein Gerät erzeugen, das die Variable als Kanal nimmt?

Mist ... 😅

**Comment by thkl** [comment]
Eine Bool Variable als Faucet würde gehen.

**Comment by meistermolli** [comment]
Das würde mich ja schon weiter bringen. Im Prinzip wäre die bool Variable ja sehr wandelbar.

Da sie viele Services annehmen kann wenn du die noch erweitern kannst? Ich überlege gerade als was ich die noch brauchen könnte. 

Die kann ja im Prinzip alles sein

switch

Socket

Faucet
Valve
Irrigation
Leak sensor

Fan
Air Purifyer
Air Humidifyer

Was gibt es sonst noch?

in der variablebinarysensoraccesory
Sind ja auch mehrere hinterlegt.

Beim variableaccesory kann man in HomeKit dann Lightbulb / Fan / Outlet auswählen. 




Mir geht es darum die Geräte, die ich nur einmal einbinden kann mehrmals in HomeKit zu bekommen. Das mache ich über Variablen. So kann man jeder variablen einen Siri Befehl geben, ohne alles als Automation an zu legen.

Die sehen in HomeKit aber irgendwann unübersichtlich aus, da sie alle als Switch dargestellt sind.

**Comment by thkl** [comment]
Es müsste also quasi einen VariableBinarySwitch geben .. der dann wie ein "normaler" Switch konfigurierbar ist ...

**Comment by meistermolli** [comment]
Das wäre ja dann perfekt.

**Comment by meistermolli** [comment]
Kann ich die Datei schon irgendwo hinein kopieren und es für dich testen?

**Comment by thkl** [comment]
das file https://github.com/thkl/hap-homematic/blob/master/lib/services/HomeMaticVariableBinarySwitchAccessory.js muss nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services + Daemon Restart

**Comment by meistermolli** [comment]
Hallo,
leider eben erst dazu gekommen.

Habe die Datei mit 

wget https://github.com/thkl/hap-homematic/blob/master/lib/services/HomeMaticVariableBinarySwitchAccessory.js 

Heruntergeladen. Diese wurde auch angelegt und hat die Daten.

Anschließend Neustart, jedoch läuft HAP Homematic nicht mehr.

**Comment by thkl** [comment]
Ich vermute mal du hast die HTML Github Seite geladen .. das Raw File liegt hier : https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/services/HomeMaticVariableBinarySwitchAccessory.js

Ansonsten : 

https://github.com/thkl/hap-homematic/wiki/Troubleshooting#running-the-daemon-from-the-commandline

**Comment by meistermolli** [comment]
ja hatte die falsche Datei genommen.

Valve - Water Faucet: funktioniert
Valve - Irrigation: funktioniert
Valve - Shower Head: funktioniert

Valve - Generic - Steht Dauerhaft Starten, setzt aber die Variable in der CCU nicht um und Lässt HAP Abstürzen / Neustarten

Die ICONs zeigen alle den Faucet. bei Geräten kann man hier bei den anderen Typen auch andere ICONs sehen.

**Comment by thkl** [comment]
Wenns Crash bitte mal in /usr/local/etc/config/addons/hap-homematic schauen ob es ein aktuelles .crash file gibt

**Comment by meistermolli** [comment]
kein crashfile da.

debug zeigt das hier:
[Fri Mar 12 2021 16:35:38 GMT+0100 (CET)] debug - [HAP Server] [CCU] _BIN_Switch_generic return variable value false
[Fri Mar 12 2021 16:35:38 GMT+0100 (CET)] debug - [HAP Server] [CCU] var Update Event _BIN_Switch_generic will be handled by 1 registered callback
[Fri Mar 12 2021 16:35:38 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticVariableBinarySwitchAccessory] _BIN_Switch_generic Update isOn/isActive to 0
[Fri Mar 12 2021 16:35:38 GMT+0100 (CET)] debug - [HAP Server] [Rega] result is false
Fri Mar 12 2021 16:35:40 GMT+0100 (CET)] debug - [HAP Server] [CCU] _BIN_Switch_generic return variable value false
[Fri Mar 12 2021 16:35:40 GMT+0100 (CET)] debug - [HAP Server] [CCU] var Update Event _BIN_Switch_generic will be handled by 1 registered callback
[Fri Mar 12 2021 16:35:40 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticVariableBinarySwitchAccessory] _BIN_Switch_generic Update isOn/isActive to 0
[Fri Mar 12 2021 16:35:40 GMT+0100 (CET)] debug - [HAP Server] [Rega] result is false

**Comment by meistermolli** [comment]
@thkl also habe das noch ein paar mal probiert. bei generic steht dauerhaft Starten. aber wird nicht eingeschaltet.

Kann ich dir sonst noch Infos zukommen lassen?

Weisst du warum die alle den Wasserhahn als Icon anzeigen? Wenn man die als Gerät einbindet, dann kommen unterschiedliche Icons.
