### ISSUE TITLE
Automatisches hap-Backup

### ISSUE THREAD

**Issue by timwegenerDE** [thkl/hap-homematic#391]
**Kein Backup, kein Mitleid**

Für den Fall das die CCU mal ganz stirbt, habe ich mir CUxD als Addon installiert. Auf einen angeschlossenen USB-Stick legt er jetzt von ganz selbst (ohne weitere Config) regelmäßig ein Backup ab. Das finde ich tatsächlich sehr praktisch und haben ist besser als brauchen.

Wäre das für hap vllt. analog denkbar?
<img width="640" alt="Bildschirmfoto 2021-03-03 um 20 09 51" src="https://user-images.githubusercontent.com/56134910/109858792-8d09d780-7c5c-11eb-9fca-0a9a6a19967b.png">

**Comment by thkl** [comment]
Das normale CCU Backup enthält /usr/local/etc/config/addons... und damit natürlich die hap Datenbank.
Die Core Files werden auf einer CCU gebackupt (ist leider so weil das addon Verzeichnis mit im Backup ist) auf einer RaspberryMatic schließe ich es durch das File .nobackup aus ...

Ein Rückspielen des Backups würde a) die Daten wieder zurückspielen und b) den Installer, der nach einem Reboot (was nach einem Backup passiert) den ganzen hap Kram wieder installiert.

**Comment by blackbasket** [comment]
Hallo @timwegenerDE ,

in dem SBK ist doch alles incl. HAP drin.

LG,
Marcel

**Comment by timwegenerDE** [comment]
Ja noch viel besser! Dann kann ich ja wieder beruhigt schlafen 😴😃👍

**Comment by meistermolli** [comment]
@timwegenerDE .. hast du mal nen link zu einer Anleitung wie man sich das einrichten kann? Merci

**Comment by timwegenerDE** [comment]
ich weiss nicht ob das nur mit Raspberrymatic geht:

https://github.com/jens-maus/RaspberryMatic/wiki/Administration#backup--restore

**Comment by thkl** [comment]
Ich hab mir mal was gebaut, was das Backup tgl.  macht und 10 Versionen rollierend auf DropBox wirft. Müsste ich mal ein Addon draus machen. 😆

**Comment by meistermolli** [comment]
Das mit dem Raspberrymatic wusste ich garnicht .. .dann muss ich mal schleunigst einen USB Stick anstecken... Danke

thkl: kann man statt dropbox auch iCloud nehmen? Dann wäre ich sofort beim backup Addon dabei ;-)

**Comment by timwegenerDE** [comment]
Gern :) 
Auch nur durch Zufall gefunden.

Wenn das mit iCloud mal so einfach wäre 🤣 
Aber wir haben uns für Apple entschieden und müssen jetzt mit einem eher geschlossenen System leben...

**Comment by thkl** [comment]
iCloud wird wohl nicht gehen. Das lebt zu sehr im goldenen Käfig.
