### ISSUE TITLE
RM-Abstürze nach hap-homematic-Konfiguration

### ISSUE THREAD

**Issue by blackbasket** [thkl/hap-homematic#394]
Hallo Thomas,

ich habe ein oder zwei Probleme. Ich beschreibe erst einmal alles in diesem Issue. Falls das 2. Verhalten ebenfalls vom Addon kommt, können wir das ja später splitten.

Seit .58 (bzw. dem Wechsel vom eq3-Image auf RM am 13/02) stelle ich reproduzierbar fest, dass die RM ca. 1-2h nach Konfigurationen über das Addon keine RM-Programme mehr ausführt. Jegliche Steuerung per DV oder direkt zum Aktor funktioniert (auch mittels Siri).
Nachdem mir dies gestern klar geworden ist, habe ich das Addon neu installiert. Kurze Zeit später war das Verhalten leider wieder reproduziert.

Schritte Neuinstallation:
- Bridges aus der Home-App entfernt
- Addon deinstalliert
- RM neu gestartet
- leeren Ordner hap-homematic gelöscht
- RM neu gestartet
- Addon installiert
- RM neu gestartet
- hap-homematic neu konfiguriert (es kam auch der first run-wizard)

Hast du hierzu eine Idee?
Ich hatte da gestern kein debug an und könnte aktuell höchstens mit RM-syslogs dienen.

Das zweite Problem habe ich bisher auf CCU-FW-Updates geschoben (deshalb gibt es dazu auch Beiträge im Homematic-Forum), aber langsam kommen mir da Zweifel. Dass die CCU/RM alle 7d abstürzt, erinnert doch sehr stark an #111 Eine fehlende Steuerzentrale kann es allerdings nicht mehr sein.
Vor der Deinstallation habe ich mittels SCP nochmal über das Filesystem geschaut und da ist mir aufgefallen, dass der Zeitpunkt, den ich bisher einem CCU-FW-Update zugeschrieben habe, genau in den Zeitraum passt, in dem ich von .56 auf .57 geupdated hatte. 

LG,
Marcel

**Comment by thkl** [comment]
Hmm ich habe 2 RM Installationen laufen und die sind stabil.  Einmal einen Pi3 als Entwicklersystem und einen Pi4 als Production. 

Die beschriebenen Fehler klingen wild da ja die CCU bei der Bedienung über HomeKit mit eingebunden ist und den Befehl über Rega bekommt und zur Schnittstelle weitergibt. 

Programme laufen auf ähnlichem Wege.

**Comment by blackbasket** [comment]
Fehler 1 ist leider absolut reproduzierbar. Wenn ich am WE Zeit habe, versuche ich das Verhalten einmal während laufendem Debug zu generieren. Wobei ich das Debug ja dann mehrere Stunden laufen lassen muss und es dann sicherlich massig Text wird.

Was mir sonst noch dazu aufgefallen ist, ich aber bisher als normal angesehen habe: Wenn alles neu gestartet ist, habe ich über 400 MB freien Speicher. Wenn es dann zum Fehler kommt, sind es nur noch >300 MB. Das war auch gestern nach der Neuinstallation so, wo die CCU nur ca. 1,5h lief, bis alles stand. Das war dann halt verhältnismäßig schnell.

Im PRTG-Graphen sieht man auch einen kleinen Peak gegen 19:25. Da hat der WatchDog hap-homematic neu gestartet. Das hilft dann aber auch nicht mehr.

![image](https://user-images.githubusercontent.com/64146687/110093268-cfd1c980-7d9a-11eb-901f-8e0848c31a38.png)

**Comment by blackbasket** [comment]
Hier noch ergänzend die SNMP-Daten von RAM und CPU des letzten "Wochenabsturzes" von gestern Morgen... sonst langweilt sich die CPU konsequent...

![image](https://user-images.githubusercontent.com/64146687/110094164-d14fc180-7d9b-11eb-9311-8814dbe6441b.png)

![image](https://user-images.githubusercontent.com/64146687/110094204-db71c000-7d9b-11eb-84a9-fac62f245538.png)

**Comment by thkl** [comment]
Ich glaub dir das ja :) nur kann ich es nicht nachvollziehen. 

Man könnte die Config vom Hap so umbiegen das er von einem anderen System auf die CCU zugreift. Um wirklich sicher zu gehen.

**Comment by blackbasket** [comment]
> Ich glaub dir das ja :)

Habe ich auch nicht bezweifelt ;) Aber vermutlich würde ich es mir selbst nicht glauben, wenn ich es nicht erlebt hätte^^

> Man könnte die Config vom Hap so umbiegen das er von einem anderen System auf die CCU zugreift. Um wirklich sicher zu gehen.

Wie genau würde das funktionieren?

**Comment by meistermolli** [comment]
Ich habe auf dem System im Moment auch nur raspberrymatic und Hap Addon am laufen. Freier Speicher auf einem Raspberry Pi 3b+ sind 300mb. Vor meinem letzten Absturz waren es nur noch 40-60 mb freier Speicher. Vielleicht fährt ja etwas den RAM voll und dann kommt es zu dem Absturz (oder dem Fehler beim Update??)

Prozessor zeigt bei mir immer unknown an.

**Comment by thkl** [comment]
Die Prozessinfos bekommt ich direkt aus dem OS Module von node. Was da raus fällt wird angezeigt.

Die ext. Installation habe ich mal eingebaut, damit es auch in einem Docker Container laufen könnte:

https://github.com/thkl/hap-homematic/wiki/Installation#running-hap-outside-the-ccu

**Comment by blackbasket** [comment]
Ok, dafür muss ich mich erst mal mit Docker auseinandersetzen. Da habe ich noch nicht mit gearbeitet. Aber soll ja wohl auch mit Hyper-V möglich sein, wenn ich das richtig im Kopf habe.

**Comment by thkl** [comment]
muss ja nicht unbedingt in einem docker container laufen .. geht ja auch auf einem 2'th oder 3'th PI ;)

**Comment by blackbasket** [comment]
Die habe ich bisher nicht im Angebot. Der Server steht zumindest hier ;)

**Comment by blackbasket** [comment]
Ok, auf den ersten Blick scheine ich zu blöd zum Bedienen von Docker zu sein... ich werde erst mal das Debug testen und sonst ggf. eine vollständige Linux-VM aufsetzen... sollte doch auch funktionieren, oder? da verstehe ich zumindest, was ich mache... auch ohne GUI ;)

**Comment by thkl** [comment]
also  mein Integration Test System läuft in dieser Form gegen einen CCU Simulator auf einem Raspberry ... will sagen, ja ;)

**Comment by blackbasket** [comment]
Hallo Thomas,

um mal kurz ein Update zu geben. Letztes WE war ich aufgrund von Exchange etwas ausgelastet ;)

Diese Nacht kam der "erwartete" Freeze nach 7d. Ich habe dann heute Morgen nach einem Reboot den RM Snapshot 3.57.4 installiert und etwas später meine Testdevices wieder aus HAP entfernt. Ca. 1h später hatte die CCU für ca. 10 min keine Lust mehr, hat sich aber von selbst gefangen.

Ich beobachte das jetzt noch. Sobald der Issue wieder auftritt, werde ich dann auf Ubuntu umstellen. Vorbereitet habe ich die VM heute endlich.

LG,
Marcel

**Comment by blackbasket** [comment]
Ok, auf Port 9874 (erscheint mir auch logischer) geht's dann doch ;)

**Comment by thkl** [comment]
Das Ganze sollte problemlos auch außerhalb der CCU laufen: siehe die letzten beiden Punkte hier : https://github.com/thkl/hap-homematic/wiki/installation#debmatic .

POrt 9874 ist der Config Webserver, Port 9875 ist der RPC Server für die Events aus der CCU.

**Comment by blackbasket** [comment]
Jepp, habe ich mir dann auch gedacht... kann ich das Wiki selbst ändern? Da steht nämlich 9875 für WebUI ;)

**Comment by thkl** [comment]
opsi

**Comment by blackbasket** [comment]
Hallo zusammen,

die CCU läuft nun auch nach 7d 3h noch. Aber das Plugin hat nach fast exakt 7d verabschiedet.

![image](https://user-images.githubusercontent.com/64146687/112147744-57159e80-8bdd-11eb-8cb3-e0fd95c3dc8a.png)
[1616491799796.crash.txt](https://github.com/thkl/hap-homematic/files/6189675/1616491799796.crash.txt)

Ein erneuter Start des Plugins auf Ubuntu hat natürlich geholfen.

LG,
Marcel

**Comment by thkl** [comment]
Channel closed tritt auf wenn der config Server (also das UI) mit dem Dämon reden will und der aber den interprozess Kanal geschlossen hat.  Das kann ich abfangen ist aber keinesfalls ein Problem das irgendwas auf dem Host so unter Last legt, das der stirbt.

**Comment by blackbasket** [comment]
Schade ;) aber ich lasse die RM aktuell auch weiter auf den Snapshot laufen. Ich will sehen, ob die wieder unter 260 MB freiem Speicher einfriert (oder heute im Laufe des 8. Tages)... alles seltsam -.-

**Comment by blackbasket** [comment]
Die RM hat eben leider auch wieder die Grätsche gemacht. Frage an euch: Sollte ich zunächst mal die HW tauschen oder neu aufsetzen? Ich hätte noch andere CCUs, die ich einfach mal kreuztauschen könnte...

**Comment by blackbasket** [comment]
Hab die HW getauscht... war erst mal die schnellere Variante... sonst habe ich Ostern zum kompletten Neuaufbau...

**Comment by blackbasket** [comment]
Andere Hardware, gleicher Fehler... hap läuft immer noch auf Ubuntu... ich denke, wir können das hier erst mal schließen...
