### ISSUE TITLE
Homekit Zuhause neu eingerichtet, Reset der Instanzen nicht möglich

### ISSUE THREAD

**Issue by tornenen** [thkl/hap-homematic#398]
Hallo,

ich habe in HomeKit mein Zuhause gelöscht um es neu einzurichten. Jetzt kann ich die Bridges nicht mehr hinzufügen, weil sie nicht auftauchen. Dann dachte ich mir, machste ein RESET der instanzen.. Jedoch läuft sich das tot. Was kann ich noch machen?

Neustart CCU/Hap habe ich mehrmals gemacht.
<img width="756" alt="Bildschirmfoto 2021-03-14 um 20 02 56" src="https://user-images.githubusercontent.com/76594569/111080798-5d7e8900-8500-11eb-9850-3dd868c85a01.png">

**Comment by mano87** [comment]
@tornenen Hast Du die Bridges auch in der Home App gelöscht?

**Comment by thkl** [comment]
Jede HomeKit Instanz kann genau einmal mit HomeKit verbunden werden. Daher kommt es zu og. Fehler.

Wenn sich die Instanzen nicht in HomeKit verbinden lassen, kannst Du auch den großen Hammer nehmen und im Ordner /usr/local/etc/config/addons/hap-homematic den Unterordner persistent löschen. Hier werden die zwischen HomeKit und den HAP Instanzen ausgehandelten Keys gespeichert. Wenn es keine dazu gibt, meldet Hap die Instanz als "verfügbar" zu HomeKit und sie sollte sich wieder verbinden lassen.

(Nach dem Löschen einmal den Daemon via WebUI neu starten)

**Comment by tornenen** [comment]
@mano87 Ja, ich habe ja das ganze Haus gelöscht.
@thkl Danke, das hat funktioniert.
