### ISSUE TITLE
HmIP-FCI1 shows low battery but has full voltage

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/hap-homematic#399]
**Problem**
Have newly configured a HmIP-FCI1 as contact sensor and it shows low battery warning in Home but the ccu-historian do not track any power issue or low battery warning in these channels. Also, via CCU3 I set the low battery warning for the device to 0.0

**Reproduce**
Always the same behaviour.

**Version**
0.0.58

![1](https://user-images.githubusercontent.com/28545473/111178676-adfef080-85ab-11eb-94a0-76f988a6dedd.jpeg)
![2](https://user-images.githubusercontent.com/28545473/111178683-afc8b400-85ab-11eb-9ce2-d32581494c21.png)
![3](https://user-images.githubusercontent.com/28545473/111178685-afc8b400-85ab-11eb-9b64-9e6d7b1ab955.png)

**Comment by thkl** [comment]
There is currently no Voltage parameter for MULTI_MODE_INPUT_TRANSMITTER. So detecting under voltage will always result in such a warning. I will set the warning level for this device to 2.4 V for the next update.

**Comment by blackbasket** [comment]
@iuliusmaximilian besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)

**Comment by ChrWi** [comment]
Siehe oben
