### ISSUE TITLE
Missing device HmIP-MOD-OC8

### ISSUE THREAD

**Issue by mach1009** [thkl/hap-homematic#4]
Hallo Thomas,

ich bin über den Sprinkler Fehler [https://github.com/thkl/homebridge-homematic/issues/576](url)
auf dein neues Projekt aufmerksam geworden. Super Idee und sicher etwas flexibler als homebride.

Ich wollte gleich mit den Sprinklern starten und meine neu angeschaffte HM IP Empfangsplatine einbinden. Leider wird diese scheinbar noch nicht unterstützt.

**Comment by thkl** [comment]
Moin, 
hier brauche ich etwas Hilfe. Das Gerät hat 41 Kanäle
1-8 : KEY_TRANSCEIVER , 
9,13,17,21,25 ... SWITCH_TRANSMITTER und 
10-12,14-16,18-20 ... SWITCH_VIRTUAL_RECEIVER

KEY_TRANSCEIVER  kein Ding das sind Tasten die auf Short / Long Press reagieren
SWITCH_TRANSMITTER ?? ist das ein normaler Ein/Aus Switch ?
SWITCH_VIRTUAL_RECEIVER schaut in der Doku auch aus wie ein Switch ... 

was wird denn da benutzt ?

**Comment by mach1009** [comment]
Hi,
ich habe das Teil nur gekauft, weil die Funkeinheit bei der IP Variante um Welten besser ist als bei der Ur-HM Version. War selbst überumpelt von der Einstellung.

SWITCH_TRANSMITTER dienen nur der Status-Anzeige des jeweiligen Ausgangs. Nur 0 / 1.
Die wirklich schaltbaren Kanäle sind SWITCH_VIRTUAL_RECEIVER 10-12,14-16,18-20...
10-12 ist ein und der selbe Ausgang.
Prinzipiell sehe ich es so, dass man jeden Kanal von SWITCH_TRANSMITTER nutzen kann. Ich nutze jeweils nur den ersten. Per Direktverknüpfung können, wie bekannt, die Zeiten mitgegeben werden.

So sieht die Hilfe in der CCU aus. Das ist pro SWITCH_TRANSMITTER konfigurierbar. Deshalb wahrscheinlich die drei Kanäle.
![grafik](https://user-images.githubusercontent.com/25270782/79019896-a05d1180-7b77-11ea-913b-2990f15103a6.png)

**Comment by thkl** [comment]
OK dann setze ich SWITCH_VIRTUAL_RECEIVER einfach mit in die Liste der Kanaltypen für Switch und dann geht der ganze Spass

**Comment by mach1009** [comment]
Kann ich jetzt irgendwie updaten?

Grüße
Matthias

**Comment by thkl** [comment]
Das WebUI müsste 0.0.19 und einen Update Button anzeigen

**Comment by mach1009** [comment]
Tatsächlich. Da muss ich wohl blind gewesen sein. Update hat geklappt und ein Ventil testhalber ein und aus - geht 👍🏻
Probiere in ruhiger Stunde nochmal mehrere durch. 
Vielen Dank und schöne Ostertage
