### ISSUE TITLE
Harmony Integration möglich?

### ISSUE THREAD

**Issue by LevelOne2k** [thkl/hap-homematic#40]
Hallo @thkl super Plugin, läuft sehr gut. Wäre es möglich die Harmony in Hap-Homematic fest zu intrigieren?

**Comment by thkl** [comment]
Nein, das sprengt den Rahmen des AddOns. Dann würde ich ja wieder eine Homebridge bauen, und das ist nicht Sinn und Zweck des AddOns

**Comment by LevelOne2k** [comment]
Auch nicht als extra Plugin für die Hap-Homematic das es getrennt davon läuft also nur wenn es zusätzlich installiert wird.

**Comment by thkl** [comment]
Nope .. das eskaliert dann in weiter Plugins ...

**Comment by LevelOne2k** [comment]
Nur auf Harmony begrenzen

**Comment by TheRealTremes** [comment]
@thkl könntest Du Dich evtl. doch dazu bewegen? Das wäre echt der Hammer. Ich, also Du, würde es dann auch wirklich auf die Harmony als Zusatz zur HAP begrenzen.

**Comment by nubbel7404** [comment]
Ja @thkl ich würde mich auch sehr über die Harmony Integration in HAP freuen. Auch kann ich meinen Vorrednern nur zustimmen ex exklusiv bei der Harmony zu belassen.

**Comment by AdlerCentauri** [comment]
Es wäre wirklich sehr nice mit der Harmony in HAP @thkl . Auch das es exklusiv bleibt finde ich gut. Es wäre echt mega von Dir!

**Comment by theo-69** [comment]
Bitte nicht die HAP zu weit aufblähen!!! Ich brauche es nicht und möchte auch nicht das eine PlugInn unnötig aufgebläht wird!!!

**Comment by thkl** [comment]
Siehe Antwort in dem neuen Issue.  Die Harmony ist out of scope bei diesem Projekt.
