### ISSUE TITLE
Integration of homebridge-alexa

### ISSUE THREAD

**Issue by marcelgross90** [thkl/hap-homematic#400]
It would be a great benefit for some users which do use both Apple-Devices and Amazon Echos if you could also integrate Alexa into your plugin.

There is already a npm package which enhance the homebridge plugin with the features for Amazon Echo.
https://www.npmjs.com/package/homebridge-alexa

So maybe there is a chance to integrate it here as well.

**Comment by thkl** [comment]
This will not work, cause this package will only work in an homebridge environment.

**Comment by marcelgross90** [comment]
Ah ok, thanks, for the info. To be honest, I saw your other project right after I opened this issue which is based on homebridge.

So let me close the issue.
