### ISSUE TITLE
HAP Instanzen können nicht zurück gesetzt werden

### ISSUE THREAD

**Issue by hillinator** [thkl/hap-homematic#401]
Hallo zusammen,
ich habe RaspberryMatic in Docker laufen, haben alle ports weitergeleitet und kann jetzt die Instanzen nicht mehr zurücksetzen. Im Log steht nur folgendes immer wieder und auf der Website verbleibt nur der Ladebalken.

```
 debug - [HAP Server] [RPC] event for HmIP-RF.00179A4989A8C7:0.CONFIG_PENDING with value false
 debug - [HAP Server] [CCU] event HmIP-RF.00179A4989A8C7:0.CONFIG_PENDING
 debug - [HAP Server] [RPC] event for HmIP-RF.00179A4989A8C7:0.UNREACH with value false
 debug - [HAP Server] [CCU] event HmIP-RF.00179A4989A8C7:0.UNREACH
 debug - [HAP Server] [RPC] event for HmIP-RF.00179A4989A8C7:0.IP_ADDRESS with value 192.168.X.X
 debug - [HAP Server] [CCU] event HmIP-RF.00179A4989A8C7:0.IP_ADDRESS
```

Die Home App wurde zurückgesetzt und daher müssen die Instanzen auch zurück gesetzt werden ,damit diese ja wieder neu als Bridge hinzugefügt werden können.

![image](https://user-images.githubusercontent.com/60514784/112049506-01df7b80-8b50-11eb-91a1-7abd8a07d2af.png)

Hat jemand Ideen, wie ich das Problemchen lösen kann?
Vielen Dank!

**Comment by thkl** [comment]
https://github.com/thkl/hap-homematic/issues/398#issuecomment-800085279

**Comment by hillinator** [comment]
Ups sorry, nicht gefunden. Vielen Dank!
