### ISSUE TITLE
HomeKit-Link in CCU-WebUI funktioniert nicht mit HTTPS!

### ISSUE THREAD

**Issue by cR0kE** [thkl/hap-homematic#402]
Hallo,

ich habe in der WebUI der HAP-Homematic die Option "HTTS benutzen" aktiviert.
In Folge dessen funktioniert jedoch der Button in der CCU-WebUI zu HomeKit nicht mehr, da dieser weiterhin auf die normale http://[ccu-ip]:9874 verlinkt.
Geht man händisch zur https://[ccu-ip]:9874 funktioniert die Oberfläche wie gewollt!

Gruß
cRoKe

**Comment by thkl** [comment]
Ja die automatische Umleitung ist bissel tricky. Ich kann auf der Umleitungsseite leider nicht erkennen ob http oder https.  Deswegen wird erst das eine, dann das andere probiert. 

Vielleicht fällt mir was besseres ein.

**Comment by blackbasket** [comment]
@cR0kE besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)

**Comment by cR0kE** [comment]
**Closed**
