### ISSUE TITLE
Nach dem Löschen des Addons ist der Menüpunkt immer noch im WebUI

### ISSUE THREAD

**Issue by HerrKuscho** [thkl/hap-homematic#403]
Hi, Ich benutze die 3.57.4 RaspMatic SW und habe die hap-homematic auch installiert gehabt.
Nach dem Löschen über "Zusatzsoftware" ist der Menüpunkt Homekit aber immer noch vorhanden. 
Homekit ist auch nicht mehr erreichbar (404 Not found). 

Also habe ich nochmal neu installiert und jetzt ist der Adapter nicht erreichbar bzw. die Configuration nicht erreichbar.
Was kann ich machen ?

**Comment by gerd2005** [comment]
Hallo, ich hatte mal ein ähnliches Verhalten, allerdings in der „normalen“ CCU. Hier hilft einfach abwarten, bis die Buttons verschwunden sind. Ich weiss nicht, woran es liegt. Vielleicht am Browser-Cache? Keine Ahnung...

**Comment by HerrKuscho** [comment]
Ja aber wie gesagt, nach der erneuten Installation habe ich keinen Zugriff mehr auf die Configurations-Seite ;(

**Comment by blackbasket** [comment]
Immer noch nicht? Nach der Installation dauert das einen Moment, da Daten nachgeladen werden. Ggf. noch einen Reboot nachschieben.

**Comment by HerrKuscho** [comment]
Neustart habe ich natürlich nach jeder Änderung gemacht. Leider kein Erfolg. 
![Fehler](https://user-images.githubusercontent.com/74314854/112141140-38aba500-8bd5-11eb-8021-c9cf1cb5a82a.JPG)

Neustart des Adapter zeigt dies an

**Comment by blackbasket** [comment]
Ok, vielleicht eine blöde Frage: Hat der Zugriff über CloudMatic bisher funktioniert?

**Comment by HerrKuscho** [comment]
Ich habe daheim in lokalen Netzwerk genau das selbe Problem !      Ich denke per CloudMatic funktioniert das eh nicht, oder ?

Aber ein Neustart des HAP  sollte doch auch so klappen. Wollte die Fehlermeldung nur damit darstellen.

**Comment by thkl** [comment]
Also der Button braucht etwas bis er verschwindet. Genau wie bei der Reinstallation. Hier wird im Prinzip nur die Konfiguration für das Addon auf die CCU geladen und nach einem Neustart (nach der Installation) wird der Rest via Inet geladen.

**Comment by HerrKuscho** [comment]
Danke ! Werde später zuhause nochmal testen.

p.s. Super Projekt von dir ! Will es nicht missen !

**Comment by thkl** [comment]
Ansonsten steht in /var/log/ das log sowohl für die Installation als auch das Daemon Runtime Log

**Comment by HerrKuscho** [comment]
Habe meine Homematic komplett neu gemacht und jetzt läuft alles wieder. Danke für dein Projekt hier !
