### ISSUE TITLE
HomeMaticDoorBellAccessory nicht unterstützt

### ISSUE THREAD

**Issue by comtel2000** [thkl/hap-homematic#41]
Bin nicht sicher ob das in Eve oder Homekit Sinn macht, statt eines normalen Schalters den HomeMaticDoorBellAccessory zu nutzen. In Homekit wird der aktuell als nicht unterstütztes Gerät angezeigt. Getestet mit HM-PBI-4-FM

**Comment by roe1974** [comment]
das würde mich auch interessieren .... verwende allerdings einen HM-SCI-3-FM der parallel zu türklingel hängt um diese zu erkennen.

**Comment by thkl** [comment]
DoorBell ist so ein Ding, Es gibt diesen Service im HomeKit Simulator aber er taucht nicht in HomeKit auf wenn ich dort ein Gerät damit anlege.

Ich denke ich werf den wieder raus.
