### ISSUE TITLE
KeyMatic HmIP-DLD

### ISSUE THREAD

**Issue by HookHM** [thkl/hap-homematic#413]
Moin @thkl , ist die neue KeyMatic HmIP-DLD schon in HAP intrigiertet? Falls nein, würde ich gerne die Datenpunkte zur integration bereitstellen.

**Comment by thkl** [comment]
Nope davon weiß ich noch nichts.

**Comment by HookHM** [comment]
Wurde vor ca. 2 oder 3 Wochen vorgestellt und seit gestern habe ich meine im Einsatz. Ich stelle später über HAP die Datenpunkte bereit.

https://de.elv.com/homematic-ip-smart-home-tuerschlossantrieb-hmip-dld-154952?fs=1585351846

**Comment by thkl** [comment]
Ok 👍

**Comment by dkrizic** [comment]
Ist die HMIP-Version anders als die alte HM-Version oder gleiche Physik und eben "nur" HMIP?

**Comment by thkl** [comment]
Laut Doku hat das Lock einen current und einen target state. 
Damit ist es im Handling etwas anders.

**Comment by gerd2005** [comment]
> Nope davon weiß ich noch nichts.
Das erklärt, dass ich auf die eröffnete Diskussion noch keine Reaktion erhalten habe ;-) Ich hatte die gleiche Frage mal in den Diskussionen hoch geworfen.
https://github.com/thkl/hap-homematic/discussions/410

**Comment by thkl** [comment]
Ja bei den Diskussionen bekomme ich keine Mail :)

**Comment by HookHM** [comment]
Hmm @thkl , wenn ich in HAP bei der Hilfe die Seriennummer eingebe und dann auf Download drücke, ist die neue Seite weiß und oben links steht nur "Unauthorized" was kann das sein?

**Comment by thkl** [comment]
Hmm CCU Authentifizierung ist in den Settings an. Und das ich dort nicht die SID mitschicke ist ein Bug.

**Comment by HookHM** [comment]
```{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HmIP-DLD",
      "address": "7316163726ABCD",
      "type": "HmIP-DLD",
      "channels": [
        {
          "id": 1001,
          "name": "7316163726ABCD:0",
          "intf": 0,
          "address": "7316163726ABCD:0",
          "type": "MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "7316163726ABCD:1",
          "intf": 0,
          "address": "7316163726ABCD:1",
          "type": "DOOR_LOCK_STATE_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1003,
          "name": "7316163726ABCD:2",
          "intf": 0,
          "address": "7316163726ABCD:2",
          "type": "ACCESS_RECEIVER",
          "access": 255
        },
        {
          "id": 1004,
          "name": "7316163726ABCD:3",
          "intf": 0,
          "address": "7316163726ABCD:3",
          "type": "ACCESS_RECEIVER",
          "access": 255
        },
        {
          "id": 1005,
          "name": "7316163726ABCD:4",
          "intf": 0,
          "address": "7316163726ABCD:4",
          "type": "ACCESS_RECEIVER",
          "access": 255
        },
        {
          "id": 1006,
          "name": "7316163726ABCD:5",
          "intf": 0,
          "address": "7316163726ABCD:5",
          "type": "ACCESS_RECEIVER",
          "access": 255
        },
        {
          "id": 1007,
          "name": "7316163726ABCD:6",
          "intf": 0,
          "address": "7316163726ABCD:6",
          "type": "ACCESS_RECEIVER",
          "access": 255
        },
        {
          "id": 1008,
          "name": "7316163726ABCD:7",
          "intf": 0,
          "address": "7316163726ABCD:7",
          "type": "ACCESS_RECEIVER",
          "access": 255
        },
        {
          "id": 1009,
          "name": "7316163726ABCD:8",
          "intf": 0,
          "address": "7316163726ABCD:8",
          "type": "ACCESS_RECEIVER",
          "access": 255
        },
        {
          "id": 1010,
          "name": "7316163726ABCD:9",
          "intf": 0,
          "address": "7316163726ABCD:9",
          "type": "ACCESS_RECEIVER",
          "access": 255
        },
        {
          "id": 1011,
          "name": "7316163726ABCD:10",
          "intf": 0,
          "address": "7316163726ABCD:10",
          "type": "SWITCH_WEEK_PROFILE",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by HookHM** [comment]
@thkl kann man Kanal 2 bis 9 auch mit einbinden? Die sind dafür da die Benutzerberechtigung ein bzw. auszuschalten. Wenn ein Handsender z.B an Kanal 2 angelernt ist, man die Benutzerberechtigung dann ausschalten, kann man mit dem Handsender nicht mehr die KeyMatic bedienen. In der WebUI sind das einfach 2 Taster „Aus“ und „Ein“

![72F36FA5-FA41-412F-978F-A7936BC3D639](https://user-images.githubusercontent.com/55434236/114741013-a9645e00-9d4a-11eb-980b-4896ab2ad75f.jpeg)

**Comment by thkl** [comment]
die Kanäle kommen als ACCESS_RECEIVER daher .. ich könnte die alle in einen Ein/Aus Schalter Mappen .. das wird dann aber ein eigenes Device

**Comment by HookHM** [comment]
@thkl Klar, voll in Ordnung als eigenes Gerät dann kann man ja locker sagen "Hey Siri, Benutzer 2 Sperren" usw.

**Comment by thkl** [comment]
Eher Siri, schalte Benutzer 2 aus ... 😂

**Comment by HookHM** [comment]
Oder so 😅

**Comment by thkl** [comment]
>  Kannst Du sagen wann ca. das Ding in HAP drin ist?

It is done, when its done

**Comment by meistermolli** [comment]
Ich schließe mich mit Interesse an, würde meine Hm Keymatic dann austauschen, da sie häufiger funkt Probleme hat.

Kannst du den Unterschied erklären, was bei der DLD anders funktioniert oder welche Auswirkungen das auf Homekit hätte?

Die verschiedenen Benutzer finde ich schonmal nice!

**Comment by thkl** [comment]
Die Klasse zum testen ist oben in dem Commit verlinkt.  Das File aus lib/services muss auf die CCU kopiert werden nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services + ein hap reboot

**Comment by HookHM** [comment]
@thkl Du meinst diese Datei laden? lib/services/HomeMaticKeyMaticIPAccessory.js wie kann ich die dort laden?

**Comment by thkl** [comment]
hier entlang : https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/services/HomeMaticKeyMaticIPAccessory.js

**Comment by HookHM** [comment]
@thkl habe die Datei auf die RaspberryMatic in den entsprechenden Ordner geschmissen, Hap restart und die neue KeyMatic ist in HAP sichtbar und habe sie einer Instanz hinzugefügt. In der Home App steht allerdings "Keine Antwort"

![A8ADAA57-E5B5-43A4-92B4-0F2FB2769BC6_1_201_a](https://user-images.githubusercontent.com/55434236/115034875-44d10c80-9ecc-11eb-8694-da1f81c8259d.jpeg)

![DE61B2A7-2901-4BD7-8B0A-B71C165716DC_1_201_a](https://user-images.githubusercontent.com/55434236/115034885-469ad000-9ecc-11eb-9ba2-0cca94d480ca.jpeg)

**Comment by thkl** [comment]
hmm was sagt das Logfile ? (kann man im WebUI vom HAP unter Internes laden) ... Crash da ggf was ?

**Comment by HookHM** [comment]
Sind da persönliche Daten oder Seriennummern drin? Sonst würde ich es Dir mal gerne per Mail zukommen lassen

**Comment by thkl** [comment]
Ja da stehen Seriennummern der Geräte drin ... Mailadresse steht im header von jedem File hier ...

**Comment by HookHM** [comment]
Die Mail ist raus. Komischerweise steht jetzt beim "Bürofenster:1" auch "Keine Antwort" eben funktionierte es noch, siehst Du ja oben am Screenshot.

**Comment by thkl** [comment]
Klingt nach einem Crash des Daemons .. in /usr/local/etc/config/addons/hap-homematic/ könnten .crash files dazu liegen

**Comment by HookHM** [comment]
Die Datei gibt es bei mir nicht

<img width="874" alt="Bildschirmfoto 2021-04-16 um 16 09 23" src="https://user-images.githubusercontent.com/55434236/115036835-2409b680-9ece-11eb-9e00-1661031758b5.png">

**Comment by thkl** [comment]
ok .. ich bau mir da mal so ein Gerät im Simulator und dann schauen wir mal

**Comment by thkl** [comment]
So der Simulator funktioniert. Aber das Verhalten basiert auf Annahmen aus der Doku.
Ich hab das Class File mal aktualisiert. Es wird jetzt mehr ins Log geschrieben.

Bitte mal das Debug einschalten (https://github.com/thkl/hap-homematic/wiki/Troubleshooting#running-in-debug-mode).
Dann einmal die HomeApp aufrufen und die View aktualisieren (Raum verlassen und Raum wieder betreten) ...

Ach und es würde mir auch helfen wenn die HMIP KeymAtic mal via Weboberfläche in jeden Status gebracht wird. also Lock .. Unlock ... Open ..  bitte mit 30 sek. Abstand damit ich das im Log nachvollziehen kann ... 

Ich vermute mal es verhält sich anders als ich mir das aus der Doku zusammenreime ...

**Comment by HookHM** [comment]
Mache ich gleich wenn ich wieder da bin. Die Push kam auf jeden Fall rein als ich die eben abgeschlossen habe
![image](https://user-images.githubusercontent.com/55434236/115045335-b6ae5380-9ed6-11eb-93e6-d81f05d06c41.jpeg)

Muss ich das file was ich eben manuell auf die RasperryMatic geschoben habe auch aktualisieren? "HomeMaticKeyMaticIPAccessory.js"

**Comment by thkl** [comment]
> Muss ich das file was ich eben manuell auf die RasperryMatic geschoben habe auch aktualisieren? "HomeMaticKeyMaticIPAccessory.js"

JA

**Comment by HookHM** [comment]
So, kann ich den selben Link nehmen für die aktualisierte Datei? https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/services/HomeMaticKeyMaticIPAccessory.js

**Comment by thkl** [comment]
ja

**Comment by HookHM** [comment]
So, ist am laufen. Habe die Datei ausgetauscht und dann HAP restart mit gesetztem Debug haken. Danach zeigte mit das Schloss in Home "Entsperrt" an, was es auch war. Habe dann in der WebUI alles durchgespielt der Status hat sich dabei in der Home App nicht geändert. Ist das ganze jetzt in der Log Datei drin? Dann lasse ich sie Dir wieder zukommen.

**Comment by thkl** [comment]
ja ich habe einen Fallback für den CurrentState eingebaut .. der liefert im Zweifel erst mal Unlocked zurück damit hängt der nicht mehr auf "No Response" Funktioniert das Schalten des Schlosses aus HomeKit ?

**Comment by HookHM** [comment]
Ja, um ca. 19:23 habe ich das Schloss per Home App gesperrt. Um 19:24 über Home App entsperrt. Springt dann auch auf "Gesperrt" bzw. "Entsperrt". 

Um 19:25 über die WebUI gesperrt, kein Status "Gesperrt" in der Home App, nur der Statuskreis in der Kachel dreht sich nach dem Sperren. 

Um 19:26 über WebUI entsperrt, auch hier kein Status in der Home App bzw. dann hört der Statuskreis auf bzw. ist dann weg. 

Um 19:27 über WebUI geöffnet.

Log Datei kommt jetzt.

**Comment by thkl** [comment]
Also Schalten geht . Anzeige ist noch falsch ? ..

**Comment by HookHM** [comment]
Ja, wenn ich über WebUI oder sonstiges die KeyMatic steuere, dann steht das in der HomeApp nicht, bleibt also immer auf "Entsperrt".

**Comment by thkl** [comment]
Ok ich sehe was schief läuft ... der Target Datenpunkt liefert beim Lesen keine Daten zurück. Sagt ja eigentlich auch die Doku:

![image](https://user-images.githubusercontent.com/884355/115062735-f4b57280-9eea-11eb-9f72-5125707fa737.png)

ich werde also für den TargetState immer den aktuellen Zustand nutzen.

**Comment by HookHM** [comment]
Ja das ist wieder super von eQ-3. Wenn die KeyMatic läuft, dann ist der Status in der WebUI "Status unbekannt". Bei der Alten KeyMaitc gab es keinen Staus, auch keinen unbekannten als die Lief. Wenn zu dann zu, wenn auf dann auf, zwischendrin kein Status.

So sieht das aus wenn man die entriegelt oder verriegelt
<img width="365" alt="Bildschirmfoto 2021-04-16 um 19 44 18" src="https://user-images.githubusercontent.com/55434236/115063706-32ff6180-9eec-11eb-9ffe-7e0d8e418a9c.png">

**Comment by thkl** [comment]
habs mal angepasst

**Comment by HookHM** [comment]
Jetzt funktioniert alles in allen Richtungen. Danke!

**Comment by thkl** [comment]
\o/

**Comment by HookHM** [comment]
@thkl die Ein/Aus Schalter für die Benutzerberechtigung sind da noch nicht bei oder?

**Comment by thkl** [comment]
nope da fehlt mir noch bissel die Idee das hübsch umzusetzen ...

**Comment by HookHM** [comment]
Es gibt doch diese "Fernseher" Schalter, wo in einem Picker die verschiedenen Eingänge drin sind, weißt du was ich meine? Ich finde leider keinen Screenshot davon.

**Comment by HookHM** [comment]
Das hier meinte ich
![image](https://user-images.githubusercontent.com/55434236/115113241-a1463180-9f89-11eb-9ba6-b8603df04fd1.jpeg)

**Comment by thkl** [comment]
Man kann die Kanäle alle zu einem Gerät zusammenfügen:

![image](https://user-images.githubusercontent.com/884355/115113814-6a254f80-9f8c-11eb-9e44-70fbbaa09767.png)

Schaut aber auch irgendwie doof aus .... aber so wird's wohl werden

**Comment by HookHM** [comment]
Ich finds ok

**Comment by HookHM** [comment]
@thkl gäbe es eine Lösung für dieses Problem:

Die KeyMatic ist in den HAP-Einstellungen so eingestellt, dass sie beim entriegeln nur entriegelt und nicht öffnen. Jetzt bräuchte ich für eine Szene auch öffnen. Wie könnte man das lösen?

**Comment by thkl** [comment]
CCU Programm was die KM öffnet und das als Schalter einbinden.

**Comment by HookHM** [comment]
Stimmt, aber dann wäre wieder ein Programm dazwischen und reagiert nicht immer so schnell.

Als ich noch RedMatic mit Homekit nutzte, hatte ich das so gelöst:
https://github.com/rdmtc/RedMatic/wiki/Open-Workaround-für-HM-Sec-Key

Da hatte ich dann einen extra Schalter "Haustüre öffnen" den ich dann in die Szene eingebunden habe, hat immer Problemlos und auch ohne Delay geklappt. Der Schalter ging auf "on" und dann sofort wieder auf "off" war also nur dafür da die KeyMatic zu öffnen.

Wäre sowas in der Art mit HAP auch möglich?

![IMG_7784](https://user-images.githubusercontent.com/55434236/115116486-fe49e380-9f99-11eb-9a67-da2c7e6d704b.jpeg)


<img width="687" alt="Bildschirmfoto 2021-04-17 um 16 27 20" src="https://user-images.githubusercontent.com/55434236/115116456-d5c1e980-9f99-11eb-88bd-e46c5b39e595.png">

**Comment by thkl** [comment]
Man könnte einen eigenen "optionalen" Schalter hinzufügen:

![image](https://user-images.githubusercontent.com/884355/115116571-744e4a80-9f9a-11eb-9d32-e007aac26b2f.png)

**Comment by HookHM** [comment]
Oder so. Kann man auch nur DEN dann in eine Szene hinzufügen?

**Comment by thkl** [comment]
Natürlich : 
![image](https://user-images.githubusercontent.com/884355/115116607-b7a8b900-9f9a-11eb-8e0e-d5ca0c97853d.png)

**Comment by HookHM** [comment]
Ja dann super. Wäre mega wenn Du das optional noch mit zur Verfügung stellst.

**Comment by thkl** [comment]
Es gibt 2 Datenpunkte in diesen Channels : 

![image](https://user-images.githubusercontent.com/884355/115139102-62b78200-a030-11eb-9880-3a8e71b6bbaf.png)

Kannst Du bitte einmal den Debug Modus starten .. die Berechtigung für einen Channel im WebUI der CCU ändern und mir dann das Log zukommen lassen.

So wie die Doku ausschaut wird auf  ACCESS_AUTHORIZATION geschrieben und der Ist Wert aus STATE gelesen.

**Comment by meistermolli** [comment]
Finde das hast du bei der alten keymatic gut gelöst. Da kann man in HAP auswählen ob die Tür geöffnet oder nur aufgesperrt werden soll. Und dann über ein Programm den anderen Befehl. Habe im Standard Haustür öffnen, da man diese Funktion öfters nutzt. In der morgen Routine habe ich dann das Programm mit dem nur aufsperren Befehl.

**Comment by thkl** [comment]
Da ist hier genau so, nur die Anfrage war ja ob man zusätzlich noch einen Öffnen Button einbauen kann.

**Comment by HookHM** [comment]
Log ist raus. Um ca. 13:00:10 habe ich auf Kanal 3 die Berechtigung eingeschaltet. Um 13:00:55 habe ich sie an Kanal 3 wieder ausgeschaltet.

**Comment by thkl** [comment]
Ok wie vermutet, steht in State die IST Einstellung für die Berechtigungen.

**Comment by thkl** [comment]
So, das File https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/services/HomeMaticKeyMaticIPAccessAccessory.js muss nach /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services. (gibts noch nicht dort)

HAP Restart.
Dann einfach einen bliebigen Channel vom Typ ACCESS_RECEIVER auswählen .. es werden dann immer alle 8 Channels als 8 Switche in dem Gerät dargestellt. 

Ich habe keine Ahnung ob das funktioniert, im Simulator tut es das, aber der macht auch das was ich ihm sage und nicht was die DLD tut ;)

**Comment by HookHM** [comment]
Es funktioniert, in allen Richtungen. Aber sage ich zu Siri "Schalte Benutzer zwei aus) usw. aus dann sagt die "Das Gerät Fernseher aus reagiert nicht"

PS: Du hast ne Mail bekommen.

**Comment by thkl** [comment]
Hmm Siri kann ich an der Stelle nicht beeinflussen ...

**Comment by HookHM** [comment]
Nun funktioniert alles. Danke dafür! Jetzt fehlt nur noch der Button zum öffnen 🙂

**Comment by meistermolli** [comment]
Falls du den Button anlegen kannst @thkl, ist dann trotzdem noch die Auswahlmöglichkeit der verschiedenen Möglichkeiten? Die einen wollen mit dem Button aufsperren und die anderen mit dem Button die Türe öffnen. Und Siri wird ja auch verschieden reagieren. (Bei mir ist Haustür öffnen „auf machen“ - das kapiert Siri aber von alleine an den Zuständen des Haustür Schloss.

Der zusätzliche Schalter heißt Haustür Aufschließen (schließt nur auf ohne öffnen) 

somit kann Siri die drei Befehle.

Haustür Abschließen
Haustür öffnen
Haustür Aufschließen

**Comment by thkl** [comment]
Ja, der Button ist dann optional und verändert auch nicht das eingestellte Verhalten.

**Comment by HookHM** [comment]
Der Öffner Button funktioniert. Jetzt sind wir durch mit dem DLD. THX!

**Comment by beckentosch** [comment]
Ist das jetzt drin oder müsste ich das noch händisch Einpflegen?

**Comment by HookHM** [comment]
@beckentosch ,

In der aktuellen Version ist es noch nicht drin das Update dafür ist noch nicht da. 

Du kannst Dir aber die fertige Datei laden und zwar diese beiden:

Für HmIP-DLD: https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/services/HomeMaticKeyMaticIPAccessory.js

Und für HMIP-DLD für die Benutzerberechtigung, ist aber kein muss wenn Du die Benutzerberechtigung nicht über HomeKit steuern möchtest:
https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/services/HomeMaticKeyMaticIPAccessAccessory.js

Dann kopierst Du beide (oder eben nur die erste) nach:
`/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services`

HAP Neustarten und dann kannst Du die KeyMatic in der HAP UI hinzufügen.

**Comment by HookHM** [comment]
Hallo @thkl ,

Ich habe mir eine Szene mit diesen Geräten erstellt
HmIP-DLD (Öffner Button)
Sirene HM-Sec-Sir-WM (Zuhause)
Schaltaktor HM-LC-Sw1-Ba-PCB (Einschaltzeit 3sek.)

So hatte ich es auch in RedMatic gehabt und hat immer bestens funktioniert. Jetzt habe ich das so auch mit HAP gemacht, und wunderte mich die Tage, warum es nicht wirklich funktioniert. Es wurde immer nur der Schaltaktor aktiviert, die Sirene und die KeyMatic nicht. Gerade habe ich durch Zufall beim aktivieren der Szene gesehen, dass die Sirene und die KeyMatic in eine Gerätekommunikation gestört laufen wenn die Szene aktiviert wird.

Ich habe dann mal die Sirene aus der Szene entfernt, aber auch hier läuft dann eine Gerätekommunikation gestört Meldung ein, aber mit der KeyMatic und dem Schaltaktor. Dann habe ich die KeyMatic mal aus der Szene entfernt und die Sirene wieder hinzugefügt, und hier funktioniert dann alles bestens.

Funktioniert:
![A77BB254-0E07-4C03-810C-E567AC226492_1_201_a](https://user-images.githubusercontent.com/55434236/115691455-5dbf3f00-a35e-11eb-81aa-15cc8319eb0b.jpeg)

Funktioniert nicht:
![7B83FBB3-F455-447A-A94E-40EE7350160A_1_201_a](https://user-images.githubusercontent.com/55434236/115691511-6c0d5b00-a35e-11eb-80dc-aad44875ab34.jpeg)


Auch wenn ich in der Szene statt den Öffner Button die KeyMatic nehme zum entriegeln, kommt die Gerätekommunikation gestört Meldung.

**Comment by HookHM** [comment]
Hallo @thkl ,

hast Du hier eine Idee warum das in die Gerätekommunikation gestört Meldung läuft wenn die KeyMatic mit dabei ist?
