### ISSUE TITLE
Fenster "Gerät bearbeiten" kann nicht nach unten gescrollt werden um auf "Fertigstellen" zu klicken

### ISSUE THREAD

**Issue by AdlerCentauri** [thkl/hap-homematic#414]
Hallo @thkl ,

ich wollte gerade mal bei den besonderen Geräten ein "HomeMaticSPVideoDoorBellAccessory" hinzufügen. Nachdem ich den Service ausgewählt habe, und dann bei "Addresse der Türklingel" die Türklingel in der Liste ausgewählt habe, ist es nicht mehr möglich, dass Fenster weiter nach unten zu scrollen damit man auf Fertigstellen klicken kann. Ich konnte das immer reproduzieren.

https://user-images.githubusercontent.com/37038767/114771412-ce69c880-9d6c-11eb-8b0e-a236d409734f.mov

**Comment by ChrWi** [comment]
Identisch mit #168 
@thkl ggf mit dem neuen Framework zu optimieren
