### ISSUE TITLE
Philips Hue mit HAP steuern

### ISSUE THREAD

**Issue by Ace-li-k** [thkl/hap-homematic#417]
Hello,

I have coupled the Hue Bridge with the CCU3.
I can control these lamps via Homematic.
Unfortunately, this is not possible via the HAP add-on.
HomeKit says no answer. Instance has been created, released, and port released in the firewall.

Greetings and thanks
_________
Hallo,

ich habe die Hue Bridge mit der CCU3 gekoppelt.
Über Homematic kann ich diese Lampen steuern.
Über das HAP Addon ist dies leider nicht möglich.
In HomeKit wird gesagt, keine Antwort. Instanz ist angelegt, Freigegeben, und Port in Firewall freigegeben.

Gruß und dank

**Comment by thkl** [comment]
I've found the root cause of this issue (some config is missing) .. I will fix this

**Comment by Ace-li-k** [comment]
Hello,

can i fix the problem somehow? or what can i do best?

**Comment by thkl** [comment]
It should work with the commit above.

**Comment by Ace-li-k** [comment]
Okay, then I need help on how to proceed

**Comment by thkl** [comment]
grab this file https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/services/HomeMaticRGBAccessory.js , upload it to your ccu at the path /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services  and restart HAP

**Comment by Ace-li-k** [comment]
Great, it works . Perfect . Thanks 

Have a nice Weekend
