### ISSUE TITLE
Wetterstation HB-UNI-SEN-WEA 

### ISSUE THREAD

**Issue by Ace-li-k** [thkl/hap-homematic#418]
Hallo,

ich habe diese Wetterstation HB-UNI-SEN-WEA gebaut und in HomeKit eingerichtet.
Für HomeKit ist leider aktuell nur Feuchte und Temperatur möglich. Wird da in Zukunft noch dran gearbeitet, dass evtl LUX und UV oder Luftdruck noch angezeigt wird ?

Danke 

______________

Hello,

I built this HB-UNI-SEN-WEA weather station and set it up in HomeKit.
Unfortunately, only humidity and temperature are currently possible for HomeKit. Is there still work to be done in the future to ensure that LUX and UV or air pressure are still displayed?

thanks

**Comment by thkl** [comment]
Can you please create a device file (https://github.com/thkl/hap-homematic/wiki/internals#support) for your weather station so I am able to check the channel type ...

**Comment by Ace-li-k** [comment]
[HB-UNI-Sen-WEA.json.zip](https://github.com/thkl/hap-homematic/files/6328727/HB-UNI-Sen-WEA.json.zip)
Moin,

ich hoffe ich habe das so richtig gemacht. Funktioniert das?

**Comment by Ace-li-k** [comment]
Morning,

I hope I really did it. Does that work?

**Comment by thkl** [comment]
I will take a 👀 into it later on

**Comment by Ace-li-k** [comment]
Have you been able to look already? 😬

**Comment by thkl** [comment]
Oh sorry for my late response. When using this with Apple Home (and u have selected the Apple Home App compatibility mode in settings) the class will generate a temperature, a humidity sensor and a light sensor . Air Pressure is only supported via eve. (The eve app supports special weather stations). Unfortunately there is no pressure sensor available in HomeKit.

**Comment by Ace-li-k** [comment]
Absolutely no problem. Where do you choose this mode?

**Comment by Ace-li-k** [comment]
Where exactly can I find that? There's nothing of it in the addon. At the moment, I only see temperature and humidity.

**Comment by Ace-li-k** [comment]
I've looked again, unfortunately I still can't find anything. Would you have a tip for me?

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/117536698-e267b980-affc-11eb-8cc9-d35f1f28a347.png)

**Comment by Ace-li-k** [comment]
That's how it looks 

![image](https://user-images.githubusercontent.com/54929252/117933007-65d92180-b301-11eb-912d-11398da145a8.jpeg)

**Comment by thkl** [comment]
Yes and when you select Apple Home compatibility it should work

**Comment by Ace-li-k** [comment]
When I check the box, press Save, and look again, the checkmark is gone. He doesn't stay

**Comment by thkl** [comment]
Hmpf, I will check this

**Comment by Ace-li-k** [comment]
Great 👍. Looks good like that. Thank you
