### ISSUE TITLE
Integration Carriersense - ähnlich Duty Cycle

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#419]
In der CCU / Raspberrymatic wird nun der Carriersense auf der Startseite angezeigt.
Kannst du diesen Ähnlich dem Duty Cycle integrieren?

Aktuell habe ich ihn mir als Variable angelegt und in anschließend über die variablen eingebunden.
Macht das einen Unterschied zur Einbindung des Duty Cycle, den man als gerät anlegt?

Ggf kann ja das Dutycycle gerät auch um den Wert Carrier Sense erweitert werden?

Danke und Gruß 
meistermolli

**Comment by thkl** [comment]
Ich lese den DC direkt aus dem Interface ... ich muss erst mal schauen, wo der CS her kommt ..

**Comment by meistermolli** [comment]
Kommt wie der Duty Cycle aus dem rpi Rf mod

**Comment by thkl** [comment]
ich hab nur den DC hier 

![image](https://user-images.githubusercontent.com/884355/115069401-cbe5ab00-9ef3-11eb-8ddf-bc2395964426.png)

Das Testsystem läuft auf einem Pi3 mit einem HB-RF-USB-TK

**Comment by thkl** [comment]
Ok ich hab mir das Script mal angeschaut, was das auf der CCU macht. Das funktioniert nur bestimmten Funkmodulen. Daher ist das etwas speziell. Ich würde meinen, die Version über die Variable sollte passen
