### ISSUE TITLE
Fensterkontakte funktionieren nicht

### ISSUE THREAD

**Issue by Andreas-Lau** [thkl/hap-homematic#420]
Ich habe verdrahtete Fensterkontakte an einem Homematic HmIPW-DRI32 aufgeschaltet. Die Öffnung der Fenster wird in der Web-GUI der CCU3 korrekt angezeigt. Wenn ich den Kontakt in HAP-Homematic als "HomeMaticContactSensorAccessory" einrichte, wird eine Änderung des Kontakt-Status **nicht** dargestellt. Richte ich wiederum den Kontakt als "HomeMaticWindowAccessory" ein, erfolgt die Darstellung des Kontakt-Status und dessen Änderungen korrekt.

**Comment by thkl** [comment]
Dieses Device kommt als MULTI_MODE_INPUT_TRANSMITTER daher. Ich hatte, warum auch immer, den Datenpunk MOTION als Erkennung des Zustandes im Kontakt eingetragen. Aber den gibt es nicht. Ich hab es auf STATE geändert.
Damit sollte es funktionieren

**Comment by Andreas-Lau** [comment]
Funktioniert, vielen Dank!

Von: Thomas Kluge ***@***.***>
Gesendet: Mittwoch, 19. Mai 2021 18:12
An: thkl/hap-homematic ***@***.***>
Cc: Andreas-Lau ***@***.***>; Author ***@***.***>
Betreff: Re: [thkl/hap-homematic] Fensterkontakte funktionieren nicht (#420)


Dieses Device kommt als MULTI_MODE_INPUT_TRANSMITTER daher. Ich hatte, warum auch immer, den Datenpunk MOTION als Erkennung des Zustandes im Kontakt eingetragen. Aber den gibt es nicht. Ich hab es auf STATE geändert.
Damit sollte es funktionieren

-
