### ISSUE TITLE
Besonderes Gerät Garagentoröffner eingerichtet und das komplette Plugin ist tot

### ISSUE THREAD

**Issue by Marfinho** [thkl/hap-homematic#421]
Erst einmal vielen Dank für das tolle Plugin! :)

Ich habe das besondere Gerät Garagentoröffner eingerichtet. Taster ist der WCG und als Sensor hab ich einen SWDO. Habe versucht alles einzurichten, ging leider nicht. Das schließen ging nicht. 
Habe dann hier in den Issues das Thema gefunden und mit dem "onTime" Befehl gearbeitet. Habe dann gespeichert und Zack, HAP ist leer. Alles weg gewesen. Neustart des ganzen Rapses ohne Erfolg. Dann hab ich das Plugin neu installiert, dachte das würde vllt helfen. Leider nein.
Die ganzen Geräte stehen noch in HomeKit als nicht erreichbar. Wenn ich jetzt bei der Neuinstallation Geräte hinzu füge, tauchen diese auch nicht in HomeKit auf.

Muss ich irgendwelche Dateien noch von Hand löschen um "clean" wieder von vorne starten zu können? :)

**Comment by thkl** [comment]
bitte mal schauen ob auf der ccu unter /usr/local/etc/config/addons/hap-homematic Crash Files liegen.
Die enden auf .crash .. Wenn eins mit aktuellem Datum bitte mal hier abwerfen .. dann sehe ich was schief gegangen ist.

**Comment by thkl** [comment]
Ach und im gleichen Verzeichnis ist eine config.json .. in der kann man ggf das Garagentor wieder rauswerfen.
Ggf liegen da auch hap-autobackup... Files. Das sind Backups die automatisch vor einem Versionsupdate gemacht werden.
Dort könnte man auch eine alte config.json wieder raus fischen.

**Comment by Marfinho** [comment]
<img width="578" alt="Bildschirmfoto 2021-04-20 um 16 09 37" src="https://user-images.githubusercontent.com/48154350/115410354-d99c7880-a1f2-11eb-91cb-2ec7f9809109.png">
Ist komplett leer. Oder bin ich zu blöd? Ist definitiv nicht auszuschließen :D

**Comment by thkl** [comment]
/usr/local/etc/config/**addons**/hap-homematic

**Comment by Marfinho** [comment]
Also eigene Blödheit, war zu erwarten.
Keine Crash-File, kein Autobackup. 
Wie bekomme ich denn die "alten" Devices raus aus HK? Die stehen jetzt alle auf "keine Antwort". Und die Geräte, die ich jetzt neu hinzugefügt habe, tauchen bei HK nicht auf.

**Comment by thkl** [comment]
mail mir mal die config.json aus dem Pfad ... ich editier den Garagenöffner da mal raus

**Comment by CaneTLOTW** [comment]
Ist mir heute auch passiert. Oberfläche war noch erreichbar, aber keine Devices und Instanzen mehr gelistet. Ich konnte mir dann eine Sicherung ziehen. Habe das Garagentor aus der Config entfernt und dann als SIcherung eingespielt. Danach ging zum Glück wieder alles.

Wie kann ich aber nun eine funktionierende Garagentorsteuerung integrieren?

Der Aktor ist bei mir ein über CUxD angebuntener Tasmota (hängt direkt am Taster für die Torsteuerung).
Der Sensor für den geschlossenen Zustand ist ein HMIP-SWDO.

Einzelnd als Schalter und SChließkontakt laufen beide super.
![grafik](https://user-images.githubusercontent.com/35076818/116794073-c3cc6480-aaca-11eb-9077-02ff1ac3658f.png)
![grafik](https://user-images.githubusercontent.com/35076818/116794086-cfb82680-aaca-11eb-8af1-8b12300adeff.png)

**Comment by thkl** [comment]
Hast du zufällig noch die kaputte config irgendwie und kannst den Teil des Garagentors mal hier posten. Dann kann ich a) sehen was schief gelaufen ist und den Crash zukünftig verhindern und b) schauen was du konfigurieren musst damit es funktioniert.

**Comment by CaneTLOTW** [comment]
Ich habe die config.json direkt im Archiv geändert und dieses so gespeichert :/

**Comment by CaneTLOTW** [comment]
Einen Tip zur Konfiguration, dann teste ich gerne und berichte hier mit/ohne Fehler zurück!

**Comment by ChrWi** [comment]
@CaneTLOTW Mögliche Konfigurationen findest du im Wiki!
