### ISSUE TITLE
Ports in Firewall auch anpassen wenn CCU-Firewall auf "Relaxed" steht?

### ISSUE THREAD

**Issue by HookHM** [thkl/hap-homematic#422]
Hallo @thkl , 

müssen die Ports für HAP in der CCU-Firewall auch angegeben werden wenn die CCU-Firewall auf "Relaxed" steht? Also so:
<img width="503" alt="Bildschirmfoto 2021-04-18 um 14 15 01" src="https://user-images.githubusercontent.com/55434236/115145177-8985b080-a050-11eb-8535-e3faa66b74ca.png">

**Comment by thkl** [comment]
Kann ich nicht genau sagen. Ein geblockter Port würde sich dahingehend äußern, das HomeKit zwar die jeweilige Instanz sieht, sich aber nicht damit verbinden kann.
