### ISSUE TITLE
Ein paar Dinge die mir aufgefallen sind

### ISSUE THREAD

**Issue by HookHM** [thkl/hap-homematic#423]
Hallo @thkl ,

da ich HAP nun produktiv nutze, sind mir ein paar Dinge aufgefallen ...

In der Home App lässt sich ein "Fensterkontakt Sensor" prozentual Steuern, soll das so sein?

https://user-images.githubusercontent.com/55434236/115158857-94603580-a090-11eb-8a91-d4c253bc2f06.mp4

Bei dem Gerät "Fenstergriffsensor HmIP-SRH" gibt es als Status "Geschlossen", "Offen", und "Gekippt" gibt es das in HomeKit auch? Denn auch hier kann ich diesen im Moment prozentual wie beim Fensterkontakt Sensor Steuern.

Bei dem Gerät "HmIP-PCBS" möchte ich, das es nach 0,5 Sekunden wieder ausgeschaltet wird, geht das?

Die Heizung steht immer im manuellen Modus. Wenn diese "Aus" ist, und ich sie per Siri einschalte, dann wird sie in den Auto Modus geschaltet.

https://user-images.githubusercontent.com/55434236/115158802-5236f400-a090-11eb-8a35-3d640510500a.mov

Ich habe es auch mal mit "Stelle die Heizung auf ..." statt "schalte" versucht, das Ergebnis bleibt gleich.

**Comment by thkl** [comment]
Danke für die Infos. 

Die meisten Sachen wurden schon in div. geschlossenen Tickets hier besprochen. 

Die Sirene verhält sich so wie gedacht. Die Funktion "Aus" verhindert auch jegliche manuellen Alarme. 

Zur Heizung gibt es noch ein offenes Ticket. 

Wenn der Fensterkontakt als Fenster benutzt wird gibt es Controls dafür, da HomeKit den dann als Mototfenster darstellt. 
Als normaler Kontakt hat er das natürlich nicht.  

Die Einschaltzeit müsste mit 0.5 gehen.

**Comment by HookHM** [comment]
Hallo @thkl ,

wenn das mit der Heizung gefixt wird, wäre super.

Nun ist mir ein komisches verhalten aufgefallen, wenn ich die Fenstersensoren umstelle von "HomeMaticWindowAccessory" auf "HomeMaticContactSensorAccessory" das dann der Kontakt in der Home App komplett verschwindet inkl. einem ganz anderem Gerät "HmIP-PCBS" sie kommen auch nicht wieder, egal wie lange ich warte.

https://user-images.githubusercontent.com/55434236/115229611-8acbe180-a113-11eb-8075-8b0d08b6d761.mp4

Wenn ich die Einschaltzeit einstelle, wird diese wieder zurück auf 0 gesetzt. Es ist egal ob ich 0.5 oder 1 eingebe. Das Gerät bleibt auch dauerhaft eingeschaltet.

https://user-images.githubusercontent.com/55434236/115229700-a505bf80-a113-11eb-97c5-a440cd7a2727.mp4

PS: Könnte man dem Gerät "HmIP-PCBS" hier die Option "HomeMaticDoorAccessory" geben? Denn die Schaltplatine schaltet hier tatsächlich eine Türe (Elektrischer Türschliesser)

**Comment by thkl** [comment]
Also ich habe das mit der Einschaltzeit mal mit einem HM-LC-Sw2-FM ausprobiert. Damit funktioniert das perfekt. Nach der eingegebenen Zeit in sek schaltet der Aktor aus und wenige Augen blicke Später erkennt HomeKit das und setzt den Status korrekt wieder auf "aus".

Daher welcher Aktor Typ ist das bei dem es nicht funktioniert ?

**Comment by HookHM** [comment]
Auch dieser HmIP-PCBS

**Comment by thkl** [comment]
Ok der sollte auf Channel 3 die ON_TIME aber unterstützen.

![image](https://user-images.githubusercontent.com/884355/115259512-413ebf00-a132-11eb-956c-838f27896331.png)

**Comment by HookHM** [comment]
Ich habe es gerade mal mit einen Zwischenstecker HMIP-PSM getestet wo vorher noch nie eine Einschaltzeit in HAP konfiguriert wurde. Ich habe eine 1 angegeben und der Stecker wurde nach 1 sek. wieder ausgeschaltet und auch in der HAP Ansicht "Gerät bearbeiten" stand bei der Einschaltzeit die 1 drin. Dann habe ich mal 0.5 eingegeben und das funktionierte nicht und in der HAP Ansicht "Gerät bearbeiten" stand bei der Einschaltzeit wieder eine 0 drin. Dann habe ich wieder eine 1 eingegeben und hier ist dann wieder alles ok. Beim HmIP-PCBS geht es jetzt auch. Dann "zickt" es wohl erstmal rum, wenn man 0.5 eingegeben hat,

**Comment by thkl** [comment]
Ja, ich weiss auch warum 
![image](https://user-images.githubusercontent.com/884355/115260266-e5286a80-a132-11eb-9468-5acf65ddf28b.png)

**Comment by HookHM** [comment]
Alles klar 0.0

**Comment by HookHM** [comment]
Kannst du das Verhalten mit dem Fensterkontakt bei dir nachstellen? https://github.com/thkl/hap-homematic/issues/423#issuecomment-822397959

**Comment by blackbasket** [comment]
Also ich kann es nachstellen... 

ich habe die 25% beim Griffsensor zwar schon immer gesehen, aber erst jetzt raffe ich, warum HomeKit so tut, als wenn es das Fenster beim Tippen auf die Kachel zu schließen versucht...

**Comment by HookHM** [comment]
Ich meinte eher die Sache warum das Fenster aus der Home App verschwindet wenn ich den Type ändere.

**Comment by blackbasket** [comment]
Achso... das ist by Design, meine ich... wenn's nur noch ein Contact ist, erscheint er nur noch im Status (oben)...

**Comment by thkl** [comment]
Ja , aber ich kann ein halb geöffnetes Fenster nicht anders darstellen.
Wenn ich die TargetState Characteristics (die ist mandatory) auf ReadOnly setze, dann geht dieses Gerät in HomeKit auf "No Response" ... das ist auch doof ...

**Comment by HookHM** [comment]
Ach so, ich Sprach jetzt nicht von dem Drehgriffsensor. Okay, das Gerät verschwindet dann nach oben also ein normaler Fenster Sensor HM-Sec-Sco. Habe nicht drauf geachtet bzw. es nicht gesehen das der Status dann oben angezeigt wird und nicht mehr als gerät. Ist also dann klar kein Bug.

**Comment by Draexl** [comment]
Hi, ist es möglich wenn das Gerät auf "contactsensoraccessory" eingestellt ist das Symbol in Homekit zu ändern? Aktuell wird es im Status als "Kontakt" dargestellt.

**Comment by ChrWi** [comment]
Ich mach das Issue gemäß "habe es gefunden" zu.
