### ISSUE TITLE
Innensirene HM-Sec-Sir-WM falsches Verhalten bei "Alarm aus" und "intern scharf"

### ISSUE THREAD

**Issue by HookHM** [thkl/hap-homematic#424]
Hallo @thkl ,

die Sirene HM-Sec-Sir-WM hat in der Home App ein falsches Verhalten. Das Verhalten für "Alle Sensoren (extern scharf)" ist korrekt. Mit "Außensensoren scharf (intern scharf)" und "Alarm Aus" scheint es jedoch nicht korrekt zu sein.

- "Aus"= "Alarm Aus"
- "Zuhause"= "Außensensoren scharf (intern scharf)" 
- "Abwesend"= "Alle Sensoren (extern scharf)
![IMG_7796](https://user-images.githubusercontent.com/55434236/115161837-1d329d80-a0a0-11eb-97a2-84569ffb4046.PNG)

Im Moment ist es so:
- "Aus"= "Alarm blockiert"
- "Zuhause"= "Alarm Aus"
- "Abwesend"= "Alle Sensoren (extern scharf)
- "Nacht"= "Außensensoren scharf (intern scharf)"
![IMG_7794](https://user-images.githubusercontent.com/55434236/115161832-11df7200-a0a0-11eb-8595-6406afece632.PNG)

![IMG_7795](https://user-images.githubusercontent.com/55434236/115161847-2d4a7d00-a0a0-11eb-9e6e-ffc1f35d3385.jpeg)

Während ich das gerade hier so nachstelle, merke ich, dass man von "falsch" garnicht so richtig sprechen kann. Ich merke, dass Du mit "Zuhause" "Aus" meinst und mit "Aus" "Alarm blockieren" meinst. Allerdings ist es jetzt auch so, dass die Pushnachrichten von der Home App auch "falsch" dargestellt werden.

Steuerung Sirene 2 (Sirene 2 ist nicht die die in HAP drin ist):

Zuhause - Außensensoren scharf (intern scharf):
![IMG_7799](https://user-images.githubusercontent.com/55434236/115162005-2c661b00-a0a1-11eb-8b1b-c0db0e6a7b3d.jpeg)

Abwesend - Alle Sensoren scharf (extern scharf)
![IMG_7800](https://user-images.githubusercontent.com/55434236/115162080-a9919000-a0a1-11eb-8d3e-e2607585a60b.jpeg)

Aus - Alarm aus
![IMG_7801](https://user-images.githubusercontent.com/55434236/115162113-e067a600-a0a1-11eb-9bc0-9b3c982081f5.jpeg)

Steuerung Sirene:
Aus - Alarm blockiert
![IMG_7802](https://user-images.githubusercontent.com/55434236/115162203-7d2a4380-a0a2-11eb-8054-e52c0b86bb7e.jpeg)

Oder ist das ganze überhaupt nicht falsch und der wo ich HomeKit vorher drüber laufen lassen habe hat es falsch implementiert?

**Comment by thkl** [comment]
Die Sirene verhält sich so wie gedacht. Die Funktion "Aus" verhindert auch jegliche manuellen Alarme.
