### ISSUE TITLE
keine Variablen mehr anwählbar

### ISSUE THREAD

**Issue by rolfsg** [thkl/hap-homematic#425]
Hallo, 

Seit kurzem ist meine Variable (Anwesenheit) verschwunden. Beim Auswählen des Variablen Registers und hinzufügen mit "Neu" wird nur eine leere Liste angezeigt. Die Geräte funktionieren nach wie vor einwandfrei, auch Programme könnte ich hinzufügen wenn ich den wollte. Nur eben keine Variablen.

Neustart CCU3 und HAP haben nichts gebracht. Gemäss Logfile  geht bei den Variablen auch was schief:

Fri Apr 23 2021 10:39:40 GMT+0200 (CEST)] error - [HAP Server] [CCU] Error while parsing json SyntaxError: Unexpected token ; in JSON at position 3025 - (str is {"variables":[{"id": 2749,"name": "@HomeNotification","dpInfo": "for @Home App","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 2024,"name": "Abwesenheitsererkennung","dpInfo": "autom. Status An- oder Abwesend von Homekit","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""}

Hat jemand einen Tipp wie ich wieder Zugriff auf die Variabeln erhalte ?

Herzliche Dank
Rolf

**Comment by thkl** [comment]
Die aktuelle Version urlencodet noch keine Variablennamen/Beschreibungen. 

Ggf hat eine Variable bei dir ein " oder ähnliches Sonderzeichen in Name/Beschreibung. Das macht das JSON kaputt. 

Ich fix das mal.

**Comment by rolfsg** [comment]
@thkl, Leider ist das Problem mit der neuen Version 0.61 nicht gelöst, es sind noch immer keine Variablen anwählbar.

**Comment by thkl** [comment]
Bitte mal folgendes Script über das WebUI der CCU / Programme / Script Testen ausführen, und das Ergebnis hier anhängen.
```
!variables
string varid;boolean df = true;Write('{"variables":[');foreach(varid, dom.GetObject(ID_SYSTEM_VARIABLES).EnumIDs()){object ovar = dom.GetObject(varid);if(df) {df = false;} else { Write(',');}Write('{')Write('"id": ' # varid # ',');
Write('"name": "');
WriteXML(ovar.Name().UriEncode());Write('",');Write('"dpInfo": "');
WriteXML(ovar.DPInfo().UriEncode());Write('",');Write('"unerasable": "' # ovar.Unerasable() # '",');
Write('"valuetype": ' # ovar.ValueType() # ',');Write('"subtype": ' # ovar.ValueSubType() # ',');
Write('"minvalue": "' # ovar.ValueMin() # '",');Write('"maxvalue": "' # ovar.ValueMax() # '",');
Write('"valuelist": "' # ovar.ValueList() # '",');Write('"unit": "');
WriteXML(ovar.ValueUnit());Write('"');Write('}');} Write(']}');
```

Das ist das Script was die Variablen aus der CCU ließt .. das scheint in Deinem Fall nicht zu funktionieren.

**Comment by rolfsg** [comment]
Hier die Ausgabe des Skipts:

{"variables":[{"id": 2024,"name": "Abwesenheitsererkennung","dpInfo": "autom%2E%20Status%20An%2D%20oder%20Abwesend%20von%20Homekit","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 40,"name": "Alarmmeldungen","dpInfo": "Anzahl%20Alarmmeldungen","unerasable": "true","valuetype": 16,"subtype": 0,"minvalue": "0","maxvalue": "65000","valuelist": "","unit": ""},{"id": 950,"name": "Anwesenheit%20%2Dalt","dpInfo": "nicht%20benutzt","unerasable": "true","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 40351,"name": "Beschattung%20Modus","dpInfo": "","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 29175,"name": "Bew%E4sserung%20Betriebsmodus","dpInfo": "","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 5904,"name": "CO2","dpInfo": "Netatmo%20CO2%20Wert%20Wohnraum","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "10000","valuelist": "","unit": "PPM"},{"id": 23260,"name": "CO2%5FBZ","dpInfo": "Netatmo%20CO2%20Wert%20B%FCro","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "10000","valuelist": "","unit": "PPM"},{"id": 1367,"name": "CO2%5FHZ","dpInfo": "Co2%20Hobbyzimmer","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "65000","valuelist": "","unit": ""},{"id": 6396,"name": "CO2%5FSZ","dpInfo": "Netatmo%20C02%20Schlafzimmer","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "10000","valuelist": "","unit": "ppm"},{"id": 25638,"name": "D%E4mmerungserkennung","dpInfo": "setzt%20autom%2E%20Status%20hell%20oder%20dunkel","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 16846,"name": "Entfeuchter%20Betriebsmodus","dpInfo": "Automatik%20oder%20Aus","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 38725,"name": "Feiertag%2DDaten","dpInfo": "Berechnete%20Jahrestage%20der%20Feier%2D%20und%20Ereignistage","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 38726,"name": "Feiertag%2DEigene","dpInfo": "Eigene%20Feier%2D%20und%20Ereignistage","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 38723,"name": "Feiertag%2DHeute","dpInfo": "Ist%20ein%20Feiertag%3F","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 2709,"name": "Feiertag%2DHeute%2DName","dpInfo": "Feiertagname","unerasable": "false","valuetype": 16,"subtype": 29,"minvalue": "","maxvalue": "","valuelist": "-;Neujahrstag;Karfreitag;Ostermontag;Auffahrt;Pfingstmontag;Bundesfeier;Allerheiligen;Altjahr";Weihnachtstag;Stefanstag","unit": ""},{"id": 38724,"name": "Feiertag%2DMorgen","dpInfo": "Ist%20ein%20Feiertag%3F","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 2710,"name": "Feiertag%2DMorgen%2DName","dpInfo": "Feiertagname","unerasable": "false","valuetype": 16,"subtype": 29,"minvalue": "","maxvalue": "","valuelist": "-;Neujahrstag;Karfreitag;Ostermontag;Auffahrt;Pfingstmontag;Bundesfeier;Allerheiligen;Altjahr";Weihnachtstag;Stefanstag","unit": ""},{"id": 10286,"name": "Ferien%2DModus","dpInfo": "manuel%20aktiviert","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 19961,"name": "Frostschutz%20Ger%E4teraum%20Betriebsmodus","dpInfo": "Status%20f%FCr%20Frostschutz%20Heizung","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 2749,"name": "HomeNotification","dpInfo": "for%20Home%20App","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 52755,"name": "HV%20%3A%20Bodenspot%20alle","dpInfo": "zusammengefasst","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 52429,"name": "HV%20%3A%20Fenster%20EG%20alle","dpInfo": "zusammengefasst","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 52566,"name": "HV%20%3A%20Fenster%20OG%20alle","dpInfo": "zusammenfassen","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 52209,"name": "HV%20%3A%20Fenster%20UG%20alle","dpInfo": "zusammengefasst","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 2867,"name": "HV%20%3A%20Ladeger%E4te","dpInfo": "alle%20Ladeger%E4t%20zusammengefasst","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 52388,"name": "HV%20%3A%20T%FCren%20Terrasse%20alle","dpInfo": "zusammengefasst","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 52618,"name": "HV%20%3A%20Wassermelder%20UG%20alle","dpInfo": "zusammengafasst","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 3221,"name": "HV%20%3A%20Wassermelder%20WG%20alle","dpInfo": "zusammengefasst","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 1538,"name": "HV%20%3A%20Wettersymbol","dpInfo": "Symbolauswahl%20f%FCr%20Neo","unerasable": "false","valuetype": 16,"subtype": 29,"minvalue": "","maxvalue": "","valuelist": "dry;rain;snow;storm","unit": ""},{"id": 1354,"name": "Jalousie%2DModus","dpInfo": "","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 10930,"name": "Katzenzaun%20Betriebsmodus","dpInfo": "Statusbit%3A%20Zeitautom%2E%20oder%20aus","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 45939,"name": "LBW","dpInfo": "letzter%20Bewegungsmelder","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 9072,"name": "Licht%20Sitzplatz%20Betriebsmodus","dpInfo": "Statusbit%3A%20Auto%20%2F%20Aus","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 56200,"name": "Luftbefeuchtern%20Modus","dpInfo": "Aus%2FAuto","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 5905,"name": "Luftdruck","dpInfo": "Netatmo%20Luftdruck","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "2000","valuelist": "","unit": "mb"},{"id": 48785,"name": "Minuten%5Fvor%5FSA","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "-1000","maxvalue": "1000","valuelist": "","unit": ""},{"id": 48786,"name": "Minuten%5Fvor%5FSU","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "-1000","maxvalue": "1000","valuelist": "","unit": ""},{"id": 30593,"name": "M%E4hroboter%20Betriebsmodus","dpInfo": "push%20","unerasable": "false","valuetype": 16,"subtype": 29,"minvalue": "","maxvalue": "","valuelist": "auto;home;eod;man","unit": ""},{"id": 56648,"name": "M%E4hroboter%2DBattery","dpInfo": "","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 56703,"name": "M%E4hroboter%2DFehlermeldung","dpInfo": "","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 56704,"name": "M%E4hroboter%2DLastSync","dpInfo": "","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 56649,"name": "M%E4hroboter%2DLaufzeit","dpInfo": "","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 57262,"name": "M%E4hroboter%2DMesser%2DBetriebsstunden","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "65000","valuelist": "","unit": ""},{"id": 58583,"name": "M%E4hroboter%2DMesser%2DProzent","dpInfo": "","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "0","maxvalue": "100","valuelist": "","unit": ""},{"id": 3999,"name": "M%E4hroboter%2DMinimal%5FAus","dpInfo": "Mininalbetrieb%20oder%20Aus","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 56650,"name": "M%E4hroboter%2DModus","dpInfo": "","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "Auto;Manu;Demo","unit": ""},{"id": 57165,"name": "M%E4hroboter%2DModus%2Dtext","dpInfo": "","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 56651,"name": "M%E4hroboter%2DM%E4htag","dpInfo": "","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "heute; morgen;übermorgen","unit": ""},{"id": 56702,"name": "M%E4hroboter%2DM%E4hzeit","dpInfo": "","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 58036,"name": "M%E4hroboter%2DNormal%5FAus","dpInfo": "Normalbetrieb%20oder%20aus","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 56805,"name": "M%E4hroboter%2DState","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "65000","valuelist": "","unit": ""},{"id": 56700,"name": "M%E4hroboter%2DStatus","dpInfo": "","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 57523,"name": "M%E4hroboter%2DStatus%2DZeit","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "65000","valuelist": "","unit": ""},{"id": 56701,"name": "M%E4hroboter%2DTimer%2DStatus","dpInfo": "","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 3952,"name": "M%E4hzyklen","dpInfo": "M%E4hzyklen%20pro%20Woche","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "30","valuelist": "","unit": ""},{"id": 38200,"name": "Pool%20Betriebsmodus","dpInfo": "EIN%2FAUS","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 11661,"name": "Pool%20Modus","dpInfo": "Zeit%2C%20Heiz%20oder%20K%FChlbetrieb","unerasable": "false","valuetype": 16,"subtype": 29,"minvalue": "","maxvalue": "","valuelist": "Zeitautomatik;Heizen bei Umwälzung;Kühlen bei Umwälzung;Aufheizen auf;Abkühlen auf","unit": ""},{"id": 7485,"name": "random%5Ftp","dpInfo": "Zufallszahl%20f%FCr%20Abwesenheitssimulation%20%2D%20gegl%E4tte","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "-2","maxvalue": "2","valuelist": "","unit": ""},{"id": 7484,"name": "random%5Fzahl","dpInfo": "Zufallszahl%20f%FCr%20Abwesenheitssimulation","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "-2","maxvalue": "2","valuelist": "","unit": ""},{"id": 60956,"name": "Rasen%20N%E4sse","dpInfo": "Hilfsvariable%20","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 5910,"name": "Regen%5Faktuell","dpInfo": "Netatmo%20Regensensor","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1000","valuelist": "","unit": "mm"},{"id": 5908,"name": "Regenmenge%5F1d","dpInfo": "Netatmo%20Regensensor","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1000","valuelist": "","unit": "mm"},{"id": 5909,"name": "Regenmenge%5F30min","dpInfo": "Netatmo%20Regensensor","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1000","valuelist": "","unit": "mm"},{"id": 41,"name": "Servicemeldungen","dpInfo": "Anzahl%20Servicemeldungen","unerasable": "true","valuetype": 16,"subtype": 0,"minvalue": "0","maxvalue": "65000","valuelist": "","unit": ""},{"id": 5906,"name": "Sonometer","dpInfo": "Netatmo%20Lautst%E4rke","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "200","valuelist": "","unit": "dB"},{"id": 2424,"name": "svEnergyCounter%5F3130%5F00089A4996735C%3A5","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 3528,"name": "svEnergyCounter%5F3511%5F00089A49967369%3A5","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 4156,"name": "svEnergyCounter%5F4143%5F00101BE9935E05%3A6","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 4250,"name": "svEnergyCounter%5F4233%5F001015699EAC5C%3A6","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 63676,"name": "svEnergyCounter%5F63659%5F001015699EAB5F%3A6","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 64111,"name": "svEnergyCounter%5F64095%5FMEQ1342283%3A2","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 2425,"name": "svEnergyCounterOldVal%5F3130","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 3527,"name": "svEnergyCounterOldVal%5F3511","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 4155,"name": "svEnergyCounterOldVal%5F4143","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 4251,"name": "svEnergyCounterOldVal%5F4233","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 63675,"name": "svEnergyCounterOldVal%5F63659","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 64110,"name": "svEnergyCounterOldVal%5F64095","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 40584,"name": "svHmIPSunshineCounter%5F40570%5F0017D709AE2D51%3A1","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 40583,"name": "svHmIPSunshineCounterOldVal%5F40570","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 40586,"name": "svHmIPSunshineCounterToday%5F40570","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 40585,"name": "svHmIPSunshineCounterYesterday%5F40570","dpInfo": "","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "0","maxvalue": "1.700000000000001e+308","valuelist": "","unit": ""},{"id": 5907,"name": "SyncTime","dpInfo": "","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 2731,"name": "Urlaub%2DHeute","dpInfo": "Urlaubstag%3F","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 2732,"name": "Urlaub%2DMorgen","dpInfo": "Urlaubstag%3F","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 2733,"name": "Urlaub%2DTage%2Dbis","dpInfo": "Tage%20bis%20zum%20Urlaub","unerasable": "false","valuetype": 4,"subtype": 0,"minvalue": "-1","maxvalue": "1000","valuelist": "","unit": ""},{"id": 2734,"name": "Urlaubstage","dpInfo": "Urlaubstage%20im%20Jahr","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 41115,"name": "Wochentag","dpInfo": "Tagname%20von%20Script%20bef%FCllt","unerasable": "false","valuetype": 20,"subtype": 11,"minvalue": "","maxvalue": "","valuelist": "","unit": ""},{"id": 51137,"name": "Zutrittsmodus%20Garage","dpInfo": "","unerasable": "false","valuetype": 2,"subtype": 2,"minvalue": "","maxvalue": "","valuelist": "","unit": ""}]}




> Am 23.05.2021 um 10:20 schrieb Thomas Kluge ***@***.*** ***@***.***>>:
> 
> !variables
> string varid;boolean df = true;Write('{"variables":[');foreach(varid, dom.GetObject(ID_SYSTEM_VARIABLES).EnumIDs()){object ovar = dom.GetObject(varid);if(df) {df = false;} else { Write(',');}Write('{')Write('"id": ' # varid # ',');
> Write('"name": "');
> WriteXML(ovar.Name().UriEncode());Write('",');Write('"dpInfo": "');
> WriteXML(ovar.DPInfo().UriEncode());Write('",');Write('"unerasable": "' # ovar.Unerasable() # '",');
> Write('"valuetype": ' # ovar.ValueType() # ',');Write('"subtype": ' # ovar.ValueSubType() # ',');
> Write('"minvalue": "' # ovar.ValueMin() # '",');Write('"maxvalue": "' # ovar.ValueMax() # '",');
> Write('"valuelist": "' # ovar.ValueList() # '",');Write('"unit": "');
> WriteXML(ovar.ValueUnit());Write('"');Write('}');} Write(']}');

**Comment by thkl** [comment]
Ha, "Feiertag Heute Namen" hat " im Text der Warteliste. Damit geht das JSON kaputt.
Die Warteliste encode ich natürlich nicht. Das hole ich noch nach, dann funktioniert das

**Comment by thkl** [comment]
So Du kannst, wenn Du möchtest, das folgende File auf der CCU tauschen:

https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/HomeMaticCCU.js

das liegt in /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib 

anschließend 2x (dazwischen 30sek warten) Restart des HAP Daemons. (1. Restart aktualisiert das getauschte File .. der 2. lädt dann die encodieren Wartelisten richtig) .... Damit sollte es funktionieren

**Comment by rolfsg** [comment]
Habe die Datei ausgetauscht und nun erscheinen die Variablen wieder :-) Bleibt dies beim nächsten Versionsupdate so oder muss die Datei dann wieder manuell geladen werden ?

Herzlichen Dank und weiterhin erholsame Pfingsttage!

> Am 23.05.2021 um 10:37 schrieb Thomas Kluge ***@***.***>:
> 
> https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/HomeMaticCCU.js <https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/HomeMaticCCU.js>

**Comment by thkl** [comment]
Nein, das nächste Update enthält diese Änderungen natürlich mit.
