### ISSUE TITLE
Probleme mit HmIP-BROLL

### ISSUE THREAD

**Issue by wkettler1985** [thkl/hap-homematic#426]
Hallo zusammen,

ich beobachte folgendes Phänomen an all meinen HmIP-BROLL Aktoren.
Setze ich einen Rollladen auf XX % via Homekit oder auch in der CCU3 WebUI funktioniert alles wie es soll.

Schließe ich einen Rollladen per Schalter und unterbreche die Fahrt ebenfalls per Schalter, zeigt mir die WebUI die Behanghöhe entsprechend korrekt an, in Homekit sehe ich ihn aber als komplett geschlossen.
Das ganze passiert auch in die andere Richtung.

Ich nutze eine CCU3 mit der aktuellsten Firmaware und ebenso hap-homematic in der aktuellsten Firmware.

Viele Grüße
W.Kettler

**Comment by thkl** [comment]
Wird die Höhe beim Refresh des HomeKit Gerätes (zb in der HomeApp den Raum einmal wechseln) aktualisiert ?

**Comment by wkettler1985** [comment]
Nein, auch ein Neustarten des Services oder ein Leeren des Caches verändert nichts.
Hier nochmal verdeutlicht in 3 Screenshots. 

![IMG_0133](https://user-images.githubusercontent.com/83218907/116080670-a5650400-a699-11eb-849d-73d49eb7998c.PNG)
![IMG_0134](https://user-images.githubusercontent.com/83218907/116080664-a4cc6d80-a699-11eb-8058-7747ea630e56.PNG)
![26-04-_2021_13-59-02](https://user-images.githubusercontent.com/83218907/116080808-c9284a00-a699-11eb-8776-20e2cbf5695d.jpg)

**Comment by ChrWi** [comment]
Bei mir habe ich das Verhalten (Webui: 15%, Homekit: geschlossen) bewusst eingestellt: 4. Eintrag in „Gerät bearbeiten“: -> Setze HomeKit auf geschlossen, wenn das Rollo unter diesem Wert ist

**Comment by wkettler1985** [comment]
Das heißt wenn der Wert >15 ist wird bei dir im HomeKit der entsprechende Wert angezeigt?
Wohlgemerkt bei Betätigung via Schalter, nicht via CCU/HomeKit

**Comment by ChrWi** [comment]
Ok, jetzt habe ich den Anwendungsfall verstanden und kann ihn reproduzieren:
Neben der o.g. Einstellung, dass kleiner 15% als geschlossen gemeldet wird habe ich ein Programm, welches bei hoher Sonneneinstrahlung auf 40% runterfährt. Vor einer Manipulation per Schalter zeigt mir HomeKit 40% pro Fenster an. Wenn ich den einen Rollladen minimal per Schalter hochfahre, steht nur noch „Geöffnet“ da, minimal per Schalter runter liefert. „geschlossen“. Die Werte laut CCU sind dagegen 50% und 30%. Merkwürdig.

**Comment by ChrWi** [comment]
Nutze einen WRC6 als Schalter

**Comment by wkettler1985** [comment]
Ok, dann sind unsere Beobachtungen identisch.

**Comment by Stefan774** [comment]
Siehe #290

**Comment by wkettler1985** [comment]
Wie sieht die Lösung aus? Kann ich nicht herauslesen.
Ich habe die neuste Version installiert und bin auf Kanal 4.

**Comment by Stefan774** [comment]
Das ist höchstwahrscheinlich noch nicht im aktuellen Release sonder nur hier auf GIT.
Daher müsstest du das selbst austauschen konkret geht es um die File:
https://github.com/thkl/hap-homematic/blob/2760eb3b6a34ef15c81d91678f31a43d66b7179f/lib/services/HomeMaticBlindIPAccessory.js

Die HomeMaticBlindIPAccessory.js beinhaltet den Fix.

Um diese einzuspielen musst du dich per SSH mit deiner CCU verbinden und die Datei im CCU Verzeichnis /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/ mit der im GIT ersetzten. Danach den HAP Service Neustarten und dann funktioniert es.

**Comment by wkettler1985** [comment]
Bin jetzt erst dazu gekommen, das Script zu ersetzen. Kann bestätigen: Problem gelöst!
Vielen Dank! :)

**Comment by ChrWi** [comment]
@wkettler1985 ich schließe mal das Ticket

**Comment by WeisserWolf611** [comment]
@Stefan774 Ich habe die Datei auf meiner CCU ersetzt, spannende Sache wenn man es das erste Mal macht... ich habe die Datei überschrieben und nun läuft HAP gar nicht mehr an. Neustart schlägt fehl und CCU3 Neustart hat nichts gebracht. Was mache ich denn nun!? :(
