### ISSUE TITLE
Siri meint "Oh oh, hier stimmt was nicht" Geräte werden aber trotzdem geschaltet

### ISSUE THREAD

**Issue by HookHM** [thkl/hap-homematic#427]
Hallo @thkl ,

wenn man Siri sagt sie soll das Licht ein- oder ausschalten, dann sagt sie das was nicht stimmt, es wird aber trotzdem korrekt ausgeschaltet. Auch wenn man sie fragt ob die Fenster verschlossen sind, sagt sie "oh oh" ... Wenn ich nach der Temperatur im Raum XY frage, funktioniert es.

Ich habe es mit offiziellen HomeKit Geräten getestet, da kommt das das richtige Feedback "OK, das Licht ist eingeschaltet" usw.

<img width="375" alt="Bildschirmfoto 2021-04-29 um 14 30 21" src="https://user-images.githubusercontent.com/55434236/116551085-d478b100-a8f7-11eb-9031-8c4f95b03543.png">

**Comment by HookHM** [comment]
Ich merke gerade, dass dieser "Fehler" nur auf macOS passiert. Auf allen anderen Geräten kommt das korrekte Feedback.

**Comment by thkl** [comment]
https://bugreport.apple.com

Viel Erfolg 😆

**Comment by thkl** [comment]
Ich habe auf dem Mac das gleiche Phänomen. Hier die Frage : Ist das Licht aus (Mac):

```
[Thu Apr 29 2021 18:25:05 GMT+0200 (CEST)] [HAP Server] [HomeMaticDimmerAccessory] DEC819af840b get isOn
[Thu Apr 29 2021 18:25:05 GMT+0200 (CEST)] [HAP Server] [HomeMaticDimmerAccessory] DEC819af840b buildAddress LEVEL
...

[Thu Apr 29 2021 18:25:05 GMT+0200 (CEST)] [HAP Server] [Rega] result is 0.000000
...
[Thu Apr 29 2021 18:25:05 GMT+0200 (CEST)] [HAP Server] [HomeMaticDimmerAccessory] DEC819af840b event Level 0
[Thu Apr 29 2021 18:25:05 GMT+0200 (CEST)] [HAP Server] [HomeMaticDimmerAccessory] DEC819af840b isON Result false
```

Es wird die Characteristic isOn abgefragt. Ich prüfe das Level des Dimmers und liefere ein false zurück weil 0

Siri läuft auf dem Mac in einen einen Fehler.


iPhone gleiche Frage:

```
[Thu Apr 29 2021 18:28:47 GMT+0200 (CEST)] [HAP Server] [HomeMaticDimmerAccessory] DEC819af840b get isOn
[Thu Apr 29 2021 18:28:47 GMT+0200 (CEST)] [HAP Server] [HomeMaticDimmerAccessory] DEC819af840b buildAddress LEVEL
...

[Thu Apr 29 2021 18:28:47 GMT+0200 (CEST)] [HAP Server] [Rega] result is 0.000000
...
[Thu Apr 29 2021 18:28:47 GMT+0200 (CEST)] [HAP Server] [HomeMaticDimmerAccessory] DEC819af840b event Level 0
[Thu Apr 29 2021 18:28:47 GMT+0200 (CEST)] [HAP Server] [HomeMaticDimmerAccessory] DEC819af840b isON Result false
```

![image](https://user-images.githubusercontent.com/884355/116585711-f3d40600-a918-11eb-8418-66e375b4414e.png)


Es kommt exakt die gleiche Anfrage an HomeKit und ich liefere exakt die gleichen Daten.

**Comment by HookHM** [comment]
Jepp, bei mir auf dem iPad, iPhone und HomePod geht es auch fehlerfrei. Auf dem Mac redet sie auch deutsch und englisch z.B. "Ok, the Licht is on" Dabei spricht sie Licht als "LICKT" aus.

**Comment by blackbasket** [comment]
Hallo zusammen,

der Fehler "muss" bei Apple liegen. Ich erhalte die "Oh, oh"-Rückmeldung teilweise bei der Ausführung von Kurzbefehlen (nur Werte in Health-App eintragen) mittels HomePod mini.

Da hängt HAP gar nicht mit drin.

LG,
Marcel

**Comment by ChrWi** [comment]
Ist auch bei mir ein macOS Problem und kein Thema bei iOS, iPadOS und HomePod.
