### ISSUE TITLE
HAP-Homematic Config Seite nach Raspberrymatic Update nicht mehr nutzbar

### ISSUE THREAD

**Issue by SvReHome** [thkl/hap-homematic#428]
Hallo thkl, erstmal tausend Dank für das tolle Plugin. Habe es problemlos eingerichtet.
Jetzt bekomme ich nach Raspberrymatic Firmwareupgrade auf Version 3.57.5.20210424 nur noch eine rudimentäre Version der Configseite angezeigt. Hier ist nichts mehr klickbar.
Was mache ich falsch?
![Bildschirmfoto 2021-04-30 um 16 03 24](https://user-images.githubusercontent.com/83460682/116713307-f2681380-a9d4-11eb-8b86-05b48e028cab.jpg)

**Comment by blackbasket** [comment]
Hi @SvReHome ,

hast du den Browser-Cache schon geleert?

LG,
Marcel

**Comment by thkl** [comment]
oh wow. 
Schaut aus, als ob das CSS fehlt.
Was du *nicht* machen solltest ist das Addon entfernen und neu aufspielen, denn beim Entfernen wird die Config mit gelöscht.

Du könntest die CSS Files aus https://github.com/thkl/hap-homematic/tree/master/lib/configurationsrv/html/css manuell auf die CCU kopieren .. die liegen in /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/configurationsrv/html/css


Ich schau mal, ob ich das Problem auf dem Testsystem nachstellen kann. Ich müsste dann eine neue Version des Addons bauen, die die Files zurückkopiert.

**Comment by thkl** [comment]
Nachtrag : Es fehlt offensichtlich dieses File https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/configurationsrv/html/css/style.css .. ich hab das mal gelöscht, dann schaut meine Testumgebung ähnlich aus ....

**Comment by thkl** [comment]
ok, was auch geht ist auf der CCU das file /usr/local/addons/hap-homematic/node_modules/hap-homematic/index.js löschen und die CCU neu starten. Beim Neustart prüft der launcher, ob genau dieses File vorhanden ist. Wenn nicht, installiert er alle Files neu drüber. Die Config bleibt erhalten, die liegt wo anders.

Nach dem Neustart der CCU dauert es dann etwas bis das UI wieder verfügbar ist.

**Comment by SvReHome** [comment]
Vielen vielen Dank thkl für den superschnellen Support ... ich habe nur Deinen letzten Vorschlag (löschen der index.js und reboot) ausprobiert und L A O L A es hat auch bei mir funktioniert ... nun kann ich weitere Geräte dazufügen .... Dankeschön

**Comment by thkl** [comment]
Perfekt. 
Ich werde mal das Addon erweitern das es genau dieses File killt ... bei einer Neuinstallation über eine bestehende Installation ...
