### ISSUE TITLE
HmIP-PSM, keine Daten

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#43]
Da wäre noch ein Gerät, vermutlich ähnlich wie bei der Wetterstation. Unterstützung der Home App vermutlich nein dafür aber Eve App. Aktuell kann dies Gerät nur schalten, gibt aber seine anderen Daten nicht preis.

HmIP Zwischenstecker Schalten/Messen (HmIP-PSM)
<img width="708" alt="Bild" src="https://user-images.githubusercontent.com/64675966/80911214-4fcf7300-8d35-11ea-8ec8-3a5f9d8d721c.png">

**Comment by thkl** [comment]
der sollte aber gehen :

![image](https://user-images.githubusercontent.com/884355/80911670-19472780-8d38-11ea-90c0-c9af0f6fa9ed.png)

Da bitte den Messwert Channel nutzen, der Switch wird automatisch hinzugefügt.

![image](https://user-images.githubusercontent.com/884355/80911687-3bd94080-8d38-11ea-9255-2e6a02c81eb1.png)

**Comment by thkl** [comment]
Der Switch Hat irgendwie in Eve ein Problem, er wird beim Aufruf der Ansicht richtig angezeigt, beim Ändern des Zustandes auch aber kurze Zeit später vergisst er in Eve seinen Status.
Obwohl es beim Switch nur On ja/nein gibt

**Comment by detLAN** [comment]
hm ... bei mir sieht es so aus:
<img width="469" alt="Bild" src="https://user-images.githubusercontent.com/64675966/80911880-65469c00-8d39-11ea-8da2-fc6a65f312e0.png">

**Comment by thkl** [comment]
Das ist der SWITCH Channel, der will dann natürlich alle möglichen Services für Switch anbieten.
Es muss ENERGIE_METER_TRANSMITTER ausgewählt werden. Das ist Channel Nummer 6

**Comment by detLAN** [comment]
haha, ja klar - Danke für den Support!

**Comment by detLAN** [comment]
Wenn man es richtig macht dann klappt es auch!

Dafür hab ich noch ein kleines Problem mit dem automatischem Anhängsel /on/off) an den Namen:
<img width="434" alt="Bild" src="https://user-images.githubusercontent.com/64675966/80912097-f10cf800-8d3a-11ea-828f-047afa47c02f.png">

**Comment by thkl** [comment]
ja das habe ich schon geändert .. ;o)
