### ISSUE TITLE
Icons austauschbar??

### ISSUE THREAD

**Issue by jgrabitzky** [thkl/hap-homematic#432]
Hallo,

erst mal ein Riesen Dank für eure fantastische Arbeit. Grade wenn wie bei uns Zuhause alle Apple Nutzer sind vereinfacht es die Bedienung schon sehr weil keine zusätzliche App benötigt wird.

Ich habe aber zwei Fragen die mir aufgefallen sind.  Hierbei handelt es sich um die Anzeige der Heizung . Im ganzen Haus ist FBH vorhanden. Diese wird mit 3 HM-TC-IT-WM-W-EU und einem HmIP-WTH-2 Thermostaten die mit einem HM-MOD-Re-8 und einem HM-LC-Sw4-Ba-PCB gesteuert.
Diese funktioniert auch sehr gut und zuverlässig in HomeKit.

Mir ist aber aufgefallen, das sobald die Soll Temperatur erreicht ist beim HmIP-WTH-2 die Anzeige von Orange auf grün wechselt. Bei den anderen 3 Thermostaten bleibt die Temperaturanzeige Orange. 

Zudem habe ich andere Räume die nur über den FBH Stellantrieb gesteuert werden. Hier hätte ich gern anstelle des Schalter symbol ein Heizungs symbol. Besteht die Möglichkeit eigene Icons einzupflegen?

Vielen Dank

**Comment by blackbasket** [comment]
Guten Morgen @jgrabitzky ,

ich lasse mich gerne korrigieren, bin aber recht sicher, dass dies nicht möglich, weil von Apple vorgegeben, ist.

LG,
Marcel

**Comment by jgrabitzky** [comment]
Ach so, ich war der Meinung die Icons waren in HAP-Homematic.

**Comment by thkl** [comment]
Nein, die Icons erzeugt die HomeApp. Da liefere ich nichts aus Hap.

**Comment by jgrabitzky** [comment]
Vielen Dank für die Mühe, dann weiss ich Bescheid.
