### ISSUE TITLE
Siri und HMIP-DLD

### ISSUE THREAD

**Issue by hoteloskar** [thkl/hap-homematic#433]
Wenn das iPhone gesperrt ist, verweigert Siri die Bedienung des DLD. Das ist sicherheitstechnisch bestimmt sinnvoll, doch ich würde den DLD auch gerne dann bedienen, wenn ich nicht dazu in der Lage bin das iPhone zu entsperren.
Gibt es da eine Einstellungsmöglichkeit speziell für den DLD?
Andere Geräte lassen sich bei gesperrtem iPhone bedienen.
Gruss, Hans

**Comment by blackbasket** [comment]
Hallo @hoteloskar ,

nicht, solange Home weiß, dass es sich um ein Schloss oder einen Alarmschalter handelt ;)

LG,
Marcel

**Comment by hoteloskar** [comment]
Hallo Marcel,
Danke für die schnelle Antwort.
Wie kann man dieses dann Home verheimlichen? In dem neuen .js File?

**Comment by blackbasket** [comment]
Hallo Hans,

das kann ich dir leider nicht sagen. Ich habe kein Schloss hier und die Alarmschalter nicht in Home. Aber die Idee führt mE in die richtige Richtung. Vielleicht kann Thomas dazu was sagen.

LG,
Marcel

**Comment by JensBonse** [comment]
Bau doch ein HomeMatic Program oder eine Variable die du dann an HomeKit übergibst als Schalter.
Das Program oder die Variable steuern dann das Schloss auf HomeMatic Seite. So bekommt HomeKit nicht mit, dass es sich um das Schloss handelt welches da gesteuert wird.

**Comment by hoteloskar** [comment]
Gute Idee, vielen Dank.

**Comment by thkl** [comment]
Wie schon erwähnt, liegt das an HomeKit und den Security Settings dort. Ich kann das nicht beeinflussen. 

Aber die Tür nicht auf Zuruf ohne Authentifizierung zu öffnen halte ich für eine gute Idee. 

Aber zum Beispiel weigert sich Siri im CarPlay jegliche HomeKit Infos zu liefern solange das iPhone nicht entsperrt ist. Gleichzeitig erklärt sie mir aber das es keine Gute Idee ist das Telefon während der Fahrt zu entsperren.  Was ne dumme Nuss !

**Comment by blackbasket** [comment]
Das ist definitiv dumm^^ aber nun ja, das eigentliche Security Setting für Schlösser und Alarmschalter ist sicherlich richtig!

**Comment by thkl** [comment]
Eben, aber das muss jeder selber entscheiden.

**Comment by JensBonse** [comment]
Natürlich ist es richtig, dass so sensible HomeKit Geräte nur bedient werden können, wenn das iOS Gerät auch entsperrt ist.
Hier ging es aber darum einen Workaround zu finden, ohne das Thomas jetzt etwas umschreiben muss, womit wir alle dann leben müssten.

Das mit CarPlay ist natürlich so eine Sache. Denke aber, dass es aus Sicht der Sicherheit schon seine Berechtigung hat.
Wenn z.B. das iPhone als Schlüssel für das Auto genutzt wird (wie bei BMW), dann setzt isch der Findige dann erst ins Auto und sagt Siri dann die Tür zu öffnen. Keine Ahnung ob das mit dem Keyless bei BMW so funktioniert, versuche nur gerade irgendwelche Angriffsvektoren mir auszudenken um gewisse Sicherheitsmechanismen zu umgehen.

**Comment by blackbasket** [comment]
Ne, CarPlay scheint da einfach dumm zu sein... ich kann über "normales" Siri, wie ich es ohne CarPlay einsetze - ja auch alles andere ohne Entsperrung aus dem Auto steuern... und das Handy weiß trotzdem, dass ich in einem Auto sitze...

**Comment by thkl** [comment]
Das hat mit dem DigitalKey nix zu tun. Mein i3 hat keinen und CarPlay verweigert sich auch schon bei Frage nach der Raumtemperatur. 

Naja egal das Thema hier scheint ja durch einen Workaround gelöst zu sein.

**Comment by HookHM** [comment]
@hoteloskar, du kannst in der CCU auch eine direkte Verknüpfung zwischen einer virtuellen Taste (HmIP-RCV-50) und der KeyMatic DLD erstellen und die virtuelle Taste dann in HAP einbinden. Dann kannst du die KeyMatic auch öffnen ohne das das iPhone entsperrt sein muss.

**Comment by ChrWi** [comment]
Workaround beschrieben (Programm auf Schalter) => Thema geschlossen
