### ISSUE TITLE
Sporadische Aussetzer bei Zugriff auf Homematic außerhalb WiFi / Heimnetz

### ISSUE THREAD

**Issue by ChrWi** [thkl/hap-homematic#434]
Hallo,
ich habe eine CCU3 auf eine Raspberry am laufen, welche auch Homebridge installiert hat (also 2 IP Adressen). Neben den Geräten, welche über hap-homematic angebunden sind, gibt es weitere Geräte, die über Homebridge kommen, sowie auch die Ikea Bridge. Beim Betrieb im heimischen Netz läuft alles einwandfrei - bin extrem zufrieden.
Wenn ich im LTE Netz bin habe ich das Problem, das - nur - die Homematic Geräte sporadisch reagieren - während andere Geräte keinerlei Probleme machen. Das Verhalten ist unabhängig davon, ob ich Home oder Eve nutze. Allerdings scheint der Zustand der Geräte (Garage auf) schon irgendwie übermittelt zu werden.
Mich stört das "sporadisch", weil ich es nicht eingegrenzt bekomme.
Hat jemand Erfahrungen hiermit?

**Comment by blackbasket** [comment]
Hallo @ChrWi ,

kannst du die sporadische Funktion genauer erläutern?

Bei mir ist es fast immer so, dass Siri eine 2. Aufforderung braucht, um zB eine Steckdose einzuschalten, sobald ich nicht im Home-WLAN bin - egal ob fremdes WLAN oder WWAN.

LG,
Marcel

**Comment by ChrWi** [comment]
Hallo Marcel,
der Status der HmIP Geräte wird nicht sauber dargestellt: 
- überall ein oranges Ausrufezeichen
- PSM/BSM erkennt den (letzten?) Zustand korrekt
- BROLL und SWDO zeigen „keine Antwort“, wobei der geschlossene Zustand richtig ist
- 
das wechselt dann gerne hin und her. Ein Drücken hat nach meiner Wahrnehmung nur bedingt Einfluss.
Cache Problem ? Aber im WiFi läuft alles flüssig!

![BEB8CB61-2FD6-4340-922C-5FC63FC0E908](https://user-images.githubusercontent.com/52505025/117550740-3943b200-b042-11eb-9e03-8c0bef847c52.jpeg)
![36C87E83-9FDB-414E-82A8-FA2EF67E1D50](https://user-images.githubusercontent.com/52505025/117550742-3a74df00-b042-11eb-91c1-01b8f607740c.jpeg)

](url)

**Comment by blackbasket** [comment]
Guten Morgen @ChrWi ,

bleibt die fehlerhafte Anzeige auch nach Aktualisierung (Raumwechsel) bestehen? Sieht für mich sehr ähnlich meinem Verhalten aus.

Off-topic: Dein AVR ist nicht zufällig von Denon? Ich bin bisher zu blöd, über die Home-App mehr als die Anzeige des Lautsprechers zu integrieren :/

LG,
Marcel

**Comment by ChrWi** [comment]
Guten Morgen Marcel,

nach Aktualisierung / Raumwechsel bleibt die fehlerhafte Anzeige bestehen. Auch beim Wechsel von Eve zurück nach Home.

Ich habe den Marantz 1510 und nutze aufgrund der Mehrfunktionen das Homebridge Plugin „Denon Heos"

Grüße
Christian

**Comment by blackbasket** [comment]
Hallo Christian,

da es nur die HAP-Geräte sind, wenn ich es richtig verstanden habe, vermute ich, deine Steuerzentrale(n) sind verbunden?

Danke :) dann muss ich mir das wohl mal ansehen ;)

LG,
Marcel

**Comment by ChrWi** [comment]
Ich habe 6 HAP Brücken, eine Homebridge Brücke (für Fritzbox + Marantz), die Ikea Bridge und den LG TV ans Homekit angebunden. 

Unabhängig von den Icons sehe ich in den Einstellungen, dass die HAP Brücken im LTE Netz „nicht antworten“. Gerade war nach 4 Minuten wieder alles OK.

Muss ich ggf. am Router irgendwelche Portfreigaben / Weiterleitungen einstellen?

**Comment by blackbasket** [comment]
Hallo Christian,

nein, bitte auf keinen Fall Ports auf der FB freigeben! Outbound ist alles offen und inbound brauchst du nichts. Die Kommunikation läuft über iCloud.

Meine Frage zielte aber tatsächlich auf die Zentrale und nicht auf die Bridges. Was nutzt du als Zentrale für HomeKit?

LG,
Marcel

**Comment by ChrWi** [comment]
Alles klar, verstanden!
Als Zentrale fungiert ein iPad mit 14.5.1., welches die AppleID meiner Frau eingestellt hat (inkl. Schlüsselbund).
Was ich noch getestet habe: auch auf dem iPhone meiner Frau tauchen die sporadischen Probleme bei LTE auf. Damit würde ich potentielle Einflüsse einiger Einschränkungen (u.a. kein Schlüsselbund) bedingt durch die Corporate IT bei meinem iPhone ausschließen.

**Comment by blackbasket** [comment]
Guten Morgen Christian,

alles, was mit so einfällt, haben wir ausgeschlossen.

Da das Verhalten nur mit HAP auftritt, sind meine Ideen gerade zu Ende. Daher kann es dann ja nicht vom iPad bzw. der anderen AppleID kommen.

LG,
Marcel

**Comment by JensBonse** [comment]
Hallo Christian,

bei den iPads als Steuerzentrale kommt es meiner Erfahrung nach leider immer wieder zu solchen Problemen.
Da die iPads beim WLAN z.B. nach einiger Zeit einen Energiesparmodus aktivieren.

Versuch das iPad mal 'aktiv' zu halten (in dem du darauf surfst oder sonst was machst) und dein iPhone vom WLAN trennst, um nur LTE zu nutzen. Tritt das Verhalten dann immer noch auf?

VG
Jens

**Comment by ChrWi** [comment]
Hallo @JensBonse,
das ist ein sehr guter Gedanke. Und: Ein erster Test war erfolgreich: Offenes iPad, Safari - direktes Ansprechen der Geräte über LTE. 
Ist bekannt, ob die anderen Optionen bzgl. Zentrale (HomePad, AppleTV) ein „Always On“ bieten?
Grüße 
Christian

**Comment by JensBonse** [comment]
Ich habe meine Apple TV per Kabel im Netzwerk.
Ich vermute, dass alles was WLAN nutzt ggf. unter diese Energiesparthemen fällt.
Es gab auch schon Andere, die ähnliche Probleme hatten. Bei einigen lag es an einem Switch, der die Broadcasts filterte etc.

Meine besten Erfahrung habe ich mit Apple TV direkt per Kabel. Das AppleTV sollte dann auch Aktiv in HomeKit sein. Also nicht im StandBy. Falls es dann immer noch zu Problemen kommt, würde ich alles mal an einen unmanaged Switch packen, der absolut nichts kann außer Geräte zu verbinden, um jegliches Netzwerk gefiltert zu unterbinden.

**Comment by blackbasket** [comment]
Hallo @JensBonse ,

wie lange dauert bei dir denn die Aktualisierung der einzelnen Geräte, wenn die Home-App länger nicht offen war?

Bei mir waren es gerade ca 10 sec. Leider ist aber gerade auch einer der HPm aktiv.

Das kann man doch auch leider nicht bestimmen, oder?

LG,
Marcel

**Comment by JensBonse** [comment]
Das initiale Laden der Zustände geht innerhalb von Sekunden (wenn die Home APP komplett geschlossen war).
Das Ändern der Zustände geht dann eigentlich innerhalb von einer Sekunde. Dazu muss die Home APP aber vorher auch komplett geschlossen worden sein.
Da @thkl eine alte Version des HAP Protokolls benutzen muss (welches noch mit Node 8 funktioniert).

Auf dem Apple TV kann man es einstellen, ob es eine Steuerzentrale sein soll oder nicht. Das kann man bei den HomePods leider nicht :(
Da müsste man entweder im Netzwerk filtern, damit die HomePods für HomeKit als nicht erreichbar erscheinen, oder die HomePods an eine andere Apple ID binden, die nicht für HomeKit genutzt wird.
HomePods sind aber alle mal besser als ein iPad als Steuerzentrale.

**Comment by ChrWi** [comment]
Managed switch ist ein guter Punkt: ich haben den PI hinter einem Netgear switch, der über Powerline mit der Fritzbox verbunden ist, während die Ikea Bridge (LAN) und die iPad Zentrale (Wifi) direkt an der Fritzbox hängen. ABER: sowohl Homebridge als auch HmIP läuft hinter dem Switch => kein klares Muster zu erkennen.
Vielleicht setze ich später mal den PI direkt an die Fritzbox und probiere es nochmals
@blackbasket bei aktivem iPad ist die Update Zeit bei mir auch kleiner 1s

**Comment by thkl** [comment]
Vielleicht kann mal jemand mit einer CCU3 via ssh 

node --version 

auf der CCU ausführen und schauen, ob inzwischen die Version erhöht wurde.

**Comment by blackbasket** [comment]
@JensBonse 
Ja, bin voll bei dir, dass HPm besser als iPad sind. Das Verhalten war bei mir auch schon so, als ich nur das ATV (natürlich per Ethernet) hatte.

@ChrWi 
Hmm... ist bei mir aber auch nur nach längerer Inaktivität so... Einfaches (richtiges) schließen gibt bei mir die selben Zeiten...

**Comment by JensBonse** [comment]
@thkl Also bei meiner RaspberryMatic zeigt er mir die Node Version 12.22.1 an.
Habe RaspberryMatic 3.57.5.20210424 am laufen.

**Comment by thkl** [comment]
Ne RM ist recht aktuell .. es geht um die Hardware CCU3 .. nur wegen dem Kistl bin ich ja noch auf der alten hapnodejs

**Comment by ChrWi** [comment]
@JensBonse ich denke das @thkl die Original CCU meinte. Ich habe bei mir bereits eine 14.1.0 laufen

**Comment by blackbasket** [comment]
Hallo Thomas,

ich habe noch eine CCU3 auf 3.55.10 laufen. Da wird Version 8.11.x (schon wieder vergessen^^) verwendet.

LG,
Marcel

**Comment by thkl** [comment]
jo das ist das Problem ich brauche für die aktuelle Version des hapnodejs (das ist quasi der Kernel für HomeKit) mindestens node Version 10

**Comment by ChrWi** [comment]
Hast du @thkl oder sonst jemand sofern bekannt das bei eq3 angefragt?

**Comment by blackbasket** [comment]
Hallo Christian,

ich habe bisher leider nie eine brauchbare Rückmeldung von eq3 erhalten. Von daher habe ich die Kommunikation mit denen, ehrlich gesagt, aufgegeben :/

LG,
Marcel

**Comment by thkl** [comment]
Ich hatte mal vor einigen Jahren Kontakt zu EQ3, war sogar mal in Leer eingeladen... aber das ist leider im Sande verlaufen ...
Aktuelle Bemühungen Demo Material zu bekommen, verlaufen derzeit nicht so prickelnd ... 

Schade ...

**Comment by blackbasket** [comment]
Hallo Thomas,

ist vermutlich eine blöde Frage: Wäre es nicht - mit wenig Aufwand - möglich, zwei Pakete zu nutzen? Einmal mit v8 und einmal mit v10+?

Oder muss dafür im Code umgebaut werden?

LG,
Marcel

**Comment by thkl** [comment]
ich müsste 2 Versionen pflegen da die Versionsnummer des module in der package.json des hap-homematic Moduls festgelegt wird.. 

Aber du könntest das hap-nodejs bei dir auf der RM testweise auf die aktuelle Version heben:

```
cd /usr/local/addons/hap-homematic/
npm install hap-nodejs@latest
```


Ich habe das auf dem Testsystem mal ausprobiert. Es startet und Crash nicht ;)

**Comment by blackbasket** [comment]
Ok, das ist natürlich mies :/

**Comment by thkl** [comment]
Ich könnte natürlich auch das ganze Paketsystem umstellen und die package.json über das CCU Addon für das jeweilige Zielsystem generieren.

Ich werde mal die aktuelle hap-nodejs Version eine Weile testen und dann darüber nachdenken

**Comment by blackbasket** [comment]
Mach dir da bitte nicht viel Arbeit mit... deshalb ja auch die blöde Frage ;) du machst hier schon echt mehr als genug für uns :)

**Comment by thkl** [comment]
ich denke mal die geringste Arbeit macht das Upgrade des Moduls im PostInstaller ... 

... das Testsystem läuft beim mir auf der aktuellen hap-nodejs Version .. schauen wir mal

**Comment by blackbasket** [comment]
Ich habe heute für den Denon-AVR mal Homebridge installiert (Danke @ChrWi )... die Aktualisierung dauert bei mir genau so lange wie bei den über HAP angebundenen Devices...

**Comment by ChrWi** [comment]
Ich vermute, auf meinem pivccu kann ich hap-nodejs nicht aktualisieren, korrekt?
Denke ich muss mich mal mir RM näher beschäftigen

**Comment by thkl** [comment]
Wie beschrieben: node --version auf der "CCU" gibt Auskunft über die Version.
Alles >=10.17.0 kann aktualisiert werden.

**Comment by ChrWi** [comment]
#node --version
v8.11.4
# npm install hap-nodejs@latest
Unhandled rejection Error: EROFS: read-only file system, mkdir '/root/.npm'963e

da steige ich vom Wissen aus

**Comment by thkl** [comment]
Ok also "nur" Version 8.11 .. da geht das eh nicht da die neueren Versionen von hap-nodejs Funktionen benutzen, die erst ab 10.17 hinzugekommen sind.

Die Fehlermeldung kommt, da das FileSystem der CCU ReadOnly ist.
Außer der Teil /usr/local ... deswegen vorher der Wechsel dahin mit  cd /usr/local/addons/hap-homematic/

Aber das funktioniert ja wegen der node Version eh nicht.
Ich schau mal, ob ich ein Update der Node Version für die CCU3 in ein AddOn Packen kann... das müsste gehen 🤔

**Comment by blackbasket** [comment]
Hallo Thomas,

mir ist das Ticket hier eben nochmal in den Sinn gekommen. Da es weiterhin so ist, dass ich aus dem WWAN ca. 8-10 Sekunden warten muss, bis die App die Daten hat und die Sprachsteuerung beim ersten Versuch gegen die Wand läuft. (Was vermutlich auch am Verbindungsaufbau liegt, da ich die App so fast nie verwende.) Auf der RM 3.57... läuft bei mir aktuell 12.22.1. Ich wollte jetzt mal schauen, was denn aktuell ist, ohne direkt ein Update zu machen. Aber ich erhalte mit npm view hap-nodejs versions ganz andere Versionierungen.

Kannst du sagen, was aktuell ist?

LG,
Marcel

**Comment by thkl** [comment]
Ich hab bei mir hap-nodejs auf 0.9.4 aktualisiert. Normal ist 0.5.7 im hap-homematic ....
Aber es hilft auch nichts. Ich habe exakt das gleiche Problem wenn ich im Auto Siri nach der Temperatur frage, überlegt sie kurz, sagt mir dann das die Geräte nicht reagieren. Wenn ich danach noch mal frage, kommt sie sofort mit der Antwort rüber ...

**Comment by blackbasket** [comment]
achso, ok... schade ;) bei Temperaturen ist ja nicht schlimm, aber man muss sich bewusst sein, dass Schaltbefehle idR tatsächlich trotzdem ausgeführt werden...

**Comment by ChrWi** [comment]
Kann ich hier irgendwo unterstützen? @thkl Ein Addon fürs Node upgrade würde ich testen

**Comment by ChrWi** [comment]
Habe heute vom iPad auf einen HomePod mini als Steuerzentrale gewechselt. Sieht soweit gut aus: alle Geräte werden im LTE Netz innerhalb von 4-6s aktualisiert

**Comment by ChrWi** [comment]
Von meiner Seite schließe ich das Thema - nach dem Umstieg auf den HomePad mini bin ich total zufrieden - das Garagentor lässt sich sowohl über CarPlay als auch per HeySiri / Apple Watch auf dem Fahrrad problemlos öffnen.
