### ISSUE TITLE
Neues Gerät: HmIP-BSL

### ISSUE THREAD

**Issue by pinogrigio** [thkl/hap-homematic#438]
Der HmIP-BSL ist ein 2 Kanal-Schaltaktor mit eingebautem LED-Licht.

Das Gerät ist als HomeMaticDimmerAccessory nutzbar und man kann via Homekit das Licht im Schalter Ein und Aus schalten.

Was fehlt ist die Möglichkeit die Lichtfarbe für den Kanal einzustellen - wenn also in Homematic der Kanal auf Aus gestellt ist, kann man diesen via Homekit nicht einschalten.

[Attachment.zip](https://github.com/thkl/hap-homematic/files/6470751/Attachment.zip)

**Comment by thkl** [comment]
Könnte ich mal einen Screenshot vom CCU WebUi haben wo man sieht wie die Farben eingestellt werden ?

**Comment by pinogrigio** [comment]
Sehr gerne!

Hier zu sehen, wie man über das Homematic Frontend die Werte einstellen kann.
<img width="1029" alt="Bildschirmfoto 2021-05-20 um 07 58 29" src="https://user-images.githubusercontent.com/84119880/118927089-90e6f500-b941-11eb-8c40-d6fc770ed94e.png">

Was vielleicht noch weiterhilft - ein Programm, welches die Lichtfarbe steuert...
<img width="1221" alt="Bildschirmfoto 2021-05-20 um 07 59 29" src="https://user-images.githubusercontent.com/84119880/118927279-d5729080-b941-11eb-8f3a-96044a109364.png">

Hier die Einstellungsmöglichkeiten, welche Homematic anbietet:
<img width="383" alt="Bildschirmfoto 2021-05-20 um 07 59 49" src="https://user-images.githubusercontent.com/84119880/118927346-ecb17e00-b941-11eb-9961-2396f21f81af.png">

Hier das Dropdown-Menü, welches die möglichen Farben anzeigt - Bemerkenswert: Auf dem 2. Screenshot wird wohl die Farbe Rot mit dem Parameter C=4 angesteuert. Im Dropdown ist Rot an 4. Stelle...
<img width="87" alt="Bildschirmfoto 2021-05-20 um 07 59 57" src="https://user-images.githubusercontent.com/84119880/118927499-297d7500-b942-11eb-9b01-eddaf9fa5b9c.png">

Hoffe das hilft! Vielen herzlichen Dank!

**Comment by thkl** [comment]
Ah, man kann also nur 7 feste Farben verwenden ?

**Comment by pinogrigio** [comment]
Ja, man hat nur diese Farbauswahlmöglichkeiten.

**Comment by thkl** [comment]
Hmm das wird dann etwas kompliziert umzusetzen.
Denn HomeKit kennt kein Gerät was sowas macht bzw hat keine Characteristic wo ich eine Liste an Werten erzeuge aus der der User dann einen auswählen kann

**Comment by thkl** [comment]
Man könnte pro Farbe einen Schalter hinzufügen, aber dann schaut das Gerät halt so aus :
![Uploading IMG_27B8408E5FBC-1.jpeg…]()

**Comment by thkl** [comment]
Hmm keine Rückmeldung?

**Comment by pinogrigio** [comment]
Sorry für die späte Rückmeldung! Finde ich dennoch super, um eine Automatisierung zu realisieren!!!

**Comment by thkl** [comment]
Ich werde wohl einfach einen RGB Lightbulb im HomeKit erzeugen und die Farben aus in einem bestimmten Bereich festlegen. Also alles zwischen hell und dunkelrot wird rot .. Das geht recht einfach da der HUE Kreis 360 Grad ist und man da einfach Abschnitte festlegen kann.

Aber : Was passiert bei "Farbe Aus" ? Ist der Schalter dann weiß oder aus ... 
Ich vermute mal das das Licht dann aus ist .. aber das ist es ja auch bei Dimmer = 0 ?

**Comment by pinogrigio** [comment]
Richtig vermutet! Es gibt letztlich 3 Parameter die das Licht steuern. Status: Ein/Aus, Farbe und Dimmer. So bald einer der Parameter 0 ist, brennt kein Licht.

Testszenarien:
Ein, Farbe=Aus, Dimmer=0% --> Licht Aus
Ein, Farbe=Weiß, Dimmer=0% --> Licht Aus
Ein, Farbe=Aus, Dimmer>0% --> Licht Aus
Ein, Farbe ungleich Aus, Dimmer >0% --> Licht An

**Comment by thkl** [comment]
Aber der Ein/Aus wird doch aus dem Dimmer abgeleitet ? Ich hab nur einen Level und einen Color Datenpunkt. 

Naja es sollte mit den Änderungen aus dem obigen Commit gehen.

**Comment by pinogrigio** [comment]
Ja, sehe ich ähnlich. Werde es gerne testen wenn es so weit ist und Rückmeldung geben - vielen lieben Dank!

**Comment by thkl** [comment]
Es würde reichen dieses File https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/services/HomeMaticDimmerAccessory.js auf der CCU zu tauschen und den HAP Daemon zu starten.
Das File liegt auf der CCU hier : /usr/local/addons/hap-homematic/node_modules/hap_homematic/lib/services

**Comment by pinogrigio** [comment]
Ich konnte es endlich ausgiebig testen. Die Lichtsteuerung funktioniert über die Eve-App wie geplant.
Mir ist aufgefallen, dass die Reaktionszeit beim ersten Befehl sehr lange dauert - ab der 2. Veränderung ist die Reaktion deutlich schneller. 

Vielen Dank!!!

**Comment by thkl** [comment]
Dieses Verhalten kenne ich auch aus anderen Geräten. 

Wenn ich im Auto Siri frage wie warm es zu Hause ist, dann erklärt sie mir beim ersten Versuch immer das die Geräte nicht reagieren. Eine erneute Frage nach der Temperatur sofort danach führt zu einer sofortigen Antwort mit der Temperatur.

Ich habe aber noch nicht nach einer Ursache gesucht ... ich weiß noch nicht mal ob das Problem beim Addon ist, oder ob HomeKit selber so lange braucht bis der Befehl zur Bridge geschickt wurde.
