### ISSUE TITLE
HMIP-DLD über HomeKit einbinden

### ISSUE THREAD

**Issue by fabi2108** [thkl/hap-homematic#439]
I want to realize the following:

Integrate the Homematic door lock HMIP-DLD into Apple Home using the HomeKit additional software. Then operate the door lock using short commands and NFC tags.

what works so far:
- Room / instance / bridge is created.
- 3 of 4 devices are displayed for integration
- Unfortunately the key device (door lock) is missing

Can you help me and "release" the door lock or tell me what to do?

Unfortunately I am not a programmer, so please explain as easily as possible ;-)

thanks

**Comment by fabi2108** [comment]
ich bin wirklich neu auf diesem Gebiet, deshalb habe ich festgestellt, das auch deutsch geht ;-)
______________________________________

Ich möchte folgendes realisieren:

Homematic Türschloss HMIP-DLD über die Zusatzsoftware HomeKit in Apple Home integireren. Anschließend über Kurzbefehle und NFC Tags das Türschloss bedienen. 

was bisher klappt:
- Raum/Instanz/Bridge wird erzeugt. 
- 3 von 4 Geräten werden zum integieren anzeigt
- das entscheidene Gerät (Türschloss) fehlt leider

Können Sie mir helfen und das Türschloss "freigeben" bzw. sagen was ich zu tun habe?

Ich bin leider kein Programmierer, deshalb bitte möglichst leicht erklären ;-)

Danke

**Comment by blackbasket** [comment]
Hallo @fabi2108 ,

über das WebUI der CCU funktioniert alles?

Hast du den HAP-Cache über Einstellungen schon mal aktualisiert?

LG,
Marcel

**Comment by thkl** [comment]
HMIP-DLD ist noch nicht im aktuellen Release 0.0.60 ....so stay tuned ...

**Comment by thkl** [comment]
0.0.61 ist raus
