### ISSUE TITLE
Dimmer Channel mit RampTime support

### ISSUE THREAD

**Issue by comtel2000** [thkl/hap-homematic#44]
Um das Dimmen via HAP etwas angenehmer zu gestalten wäre ein extra Parameter "ramp time" sehr schön. Es müsste geprüft werden, ob:

der Channel diesen data point enthält: 
`<datapoint name="HmIP-RF.0008DA498XXXX:4.RAMP_TIME" type="RAMP_TIME" ise_id="13519" value="" valuetype="4" valueunit="s" timestamp="0" operations="2"/>`

und beim Einrichten des HomeMaticDimmerAccessory ein zusätzlicher Parameter gesetzt werden:
Entweder die RampTime als Float Textfeld in Sekunden (0.1 - 10 sec.) oder als default boolean
```
  static configurationItems () {
    return {
      'useRampTime': {
        type: 'checkbox',
        default: false,
        label: 'Use Ramp Time 500 ms',
        hint: 'uses a dimmer ramp time to slowly set the new level'
      }
    }
  }
```

**Comment by comtel2000** [comment]
ich bin am probieren und für Tipps / Hinweise sehr dankbar..
Unterstützen alle Homematic Dimmer Channel RAMP_TIME?

**Comment by thkl** [comment]
soweit ich weiß ja ..  der älteste HM Dimmer, den ich habe, unterstützt das ...

**Comment by thkl** [comment]
ggf müsste man die Ramp Time selber noch angeben .... also ein 2. Config Item mit 500ms default.

**Comment by thkl** [comment]
So müsste das gehen ...
Da die ganzen Config Felder noch keinerlei Plausibilitätsprüfung haben könnte man das ggf noch in der DimmerKlasse prüfen und ggf. korrigieren

**Comment by thkl** [comment]
Die HomeMaticCCU Klasse hat eine Methode namens hazDatapoint(name) .. die liefert ein Promise zurück und damit kann man prüfen, ob ein Datenpunkt mit der Adresse in der CCU vorhanden ist.

in dem Falle in der Dimmer Klasse zb 

```
if (await this._ccu.hazDatapoint(this.buildAddress('RAMP_TIME'))) {
  Datenpunkt ist vorhanden und kann benutzt werden
}
```

**Comment by thkl** [comment]
ich hab nur HMW-LC-Dim1L-DR gefunden, ohne RampTime

**Comment by comtel2000** [comment]
Ok, dann setze ich mich heute mal dran.
Ich habe sonst keine einfache Variante in der CCU gefunden das so via HAP umzusetzen.
Ist denke ich ein nettes Feature, wenn mit 0.0.3x schon eine so stabile Software rausgekommen ist  und alle meine Geräte supported werden 👍🙂

**Comment by thkl** [comment]
siehe obiger Commit, bis auf den Check ob der RAMP_TIME vorhanden ist geht das schon :o)

**Comment by comtel2000** [comment]
24/7 bugfixing 👍 
Ich muss mir mal was deutlich komplexeres suchen, um mal wieder ein PR machen zu können ;)
HmIP-BDT Test in progress..

**Comment by thkl** [comment]
Oder vorher die Idee nicht verraten ;o)
Aber danke für die Idee mit der RampTime das ist wesentlich angenehmer....

**Comment by comtel2000** [comment]
ja, oder das :)
HmIP-BDT (DIMMER_VIRTUAL_RECEIVER) funktioniert auch und da deaktivierbar, kann das Ticket geschlossen werden.
