### ISSUE TITLE
CCU3 sagt neue Version 0.0.15, Downloadbar aber nur 0.0.14?

### ISSUE THREAD

**Issue by tornenen** [thkl/hap-homematic#440]
Meine CCU meldet eine neue Version. Wenn ich auf herunterladen gehe wird mir aber nur 0.0.14 angeboten. Ist das ein Bug bei mir? Weiß nicht seit wann es ist. Habe sicherlich 1-2 Monate nicht mehr geschaut ob Aktualisierungen verfügbar sind.
<img width="791" alt="Bildschirmfoto 2021-05-22 um 21 43 08" src="https://user-images.githubusercontent.com/76594569/119239063-c01a8380-bb46-11eb-8450-13e60f21b801.png">

**Comment by thkl** [comment]
Moin ja, das Version File ist falsch.  0.0.14 ist weiter aktuell. 

Das CCU Addon ist auch nur der Installer.  Über die WebUi Seite von HAP wird das eigentliche Addon aktualisiert. Da sind wir bei Version 0.0.61.

**Comment by thkl** [comment]
ist korrigiert
