### ISSUE TITLE
Mehrere Zuhause funktionieren nicht

### ISSUE THREAD

**Issue by D6419** [thkl/hap-homematic#441]
Zuhause A mit ATV als Steuerzentrale und CCU3, Zuhause B mit Homepod mini als Steuerzentrale und ebenfalls CCU3. Wenn ich ein Gerät in HAP von A anpasse (z.B. Anzeige Jalousie revers darstellen)  verschwinden bei der nachfolgenden aktualisierung in Homekit alle Geräte (Netatmo Welcome) und die HAP Bridges in Zuhause B. 
Nach dem erneuten anlegen der Bridge in B werden die Geräte zwar angezeigt aber nicht mehr aktualisiert. 
Die Netatmo muss ich erst zurücksetzen und anschliessend komplett neu installieren !?
Wie kann ich verhindern das eine HAP Inatsllation in Zuhause A diejenige in einem anderen Zuhause B+x mit komplett eigener und unabhängiger Installation zerschiesst?

**Comment by thkl** [comment]
Ich vermute mal das hat mit HAP nichts zu tun. 

HomeKit selbst funktioniert nach dem Prinzip, das ein Gerät (in dem Falle HAP als Bridge für mehrere Geräte) seine Daten dem Apple HomeKit Framework zur Verfügung stellt. Dabei weiß das Gerät (also HAP) nicht in welchem Raum oder gar in welchem Home es vom Nutzer eingeordnet wird.  HAP liefert einfach nur die Statusdaten bzw empfängt Änderungsbefehle.  Um Gruppierung/Darstellung/Automatisierungen kümmert sich HomeKit.
