### ISSUE TITLE
Homematic nicht aufrufbar

### ISSUE THREAD

**Issue by demji1985** [thkl/hap-homematic#442]
Hi,

nachdem ich jetzt fast 1 Monat lang Homekit in Verbindung mit HAP-Homematic genutzt und getestet habe, komme ich plötzlich nicht mehr auf die Oberfläche.

Wenn ich über RaspberryMatic auf den Button "Homekit" klicke, öffnet sich ein neuer Tab:

We will redirect you to the HAP-HomeMatic Configuration
if this will not work please user the link for :

HTTPS Version
HTTP Version

__________________________

Problem daran ist, es passiert nichts. Egal, ob ich den HTTP oder HTTPS Link probiere. Nach ca. 30-60 sek sagt er dann "Konnte nicht geöffnet werden".

Hat irgendwer eine Idee? Ich würde ungern alles neu installieren und neu konfigurieren müssen..

**Comment by blackbasket** [comment]
Hi @demji1985 ,

hast du den Service schon mal neu gestartet?

`/etc/config/rc.d/hap-homematic restart `

LG,
Marcel

**Comment by demji1985** [comment]
Hallo @blackbasket Habe sowohl die RaspberryMatic neugestartet wie auch den Dienst - beides hilft nicht...

**Comment by blackbasket** [comment]
Hmm, sind deine Firewall-Settings noch korrekt? Nutzt du HTTP oder HTTPS?

**Comment by demji1985** [comment]
Firewall überprüft, alles beim Alten.
HTTP - hab es aber auch mit HTTPS getestet - macht keinen Unterschied..

**Comment by blackbasket** [comment]
Ok, ich wollte nur sicherstellen, dass es kein TLS-Problem gibt...

Kannst du mal schauen, ob die config und alles im Filesystem noch vorhanden ist?

**Comment by demji1985** [comment]
Wie mache ich das? Hab die CU noch nicht lange. Vermutlich über SSH?

Doch, die Home-App ist scheinbar noch verbunden, wenn auch mit nicht völlig richtigen Werten. Rolladen, der auf 40% geöffnet ist, steht dort als "geschlossen"...

**Comment by blackbasket** [comment]
Ja, per SSH oder CUXD... da kannst du das FS auch browsen... da die App aber läuft, dürfte es wohl eher nicht das Problem sein...

Hast du den Browser-Cache schon mal geleert?

Mit den 40% ist eine Config-Geschichte... von daher würde ich das erst einmal vernachlässigen, wenn die generelle Funktion gegeben ist...

**Comment by demji1985** [comment]
Da ich es mit zwei unterschiedlichen Browsern versucht habe, gehe ich davon aus, dass es daran nicht liegt - einer der Browser arbeitet ohne Cache.

**Comment by blackbasket** [comment]
Ok... als nächstes würde ich testen, ob der UI-Port noch läuft... unter Windows mit 
`netstat -ao | findstr 9874`

Ob Linux das auch versteht, weiß ich ad hoc nicht ;)

**Comment by demji1985** [comment]
Aber auf dem RaspberryMatic selbst dann, oder?
Oder muss ich die Seite "öffnen" und danach suchen? ;)

**Comment by blackbasket** [comment]
Direkt auf der RM mittels SSH

**Comment by demji1985** [comment]
Hmm.... bekomme nichtmal SSH Zugriff aktuell. *seufz*

**Comment by blackbasket** [comment]
SSH auf der RM ist aktiviert?

Greifst du per Name oder per IP zu? Könnte ein DNS-Problem sein...

**Comment by demji1985** [comment]
ssh root@192.168.178.39
Connection timed out

DNS problem ist es nicht, arbeite eigentlich nur per IP ohne hostname..

**Comment by blackbasket** [comment]
Ne, UPnP sehe ich da nicht im Zusammenhang...

Da du aber auf beide Ports nicht connecten kannst: Hast du auf deinem System (nicht die RM!) eine Firewall, die outbound Ports blockiert?

Sonst gehen wir gerade die Ideen aus...

**Comment by demji1985** [comment]
Neue Erkenntnis: Via Handy öffnet sich der Tab(!) Da geht es...

**Comment by blackbasket** [comment]
Na, das untermauert ja meine Theorie von geblockten outbound Ports...

**Comment by demji1985** [comment]
Wo ist da der Sinn? Laptop ist wie das Handy im selben Netzwerk - der Zugriff ist doch quasi der selbe, nur versch. Geräte.

Könnte mir maximal vorstellen, dass der Laptop vielleicht blockiert ist durch Nmap scanning (was aber schon Tage her ist)
Und wenn ja, wo würde ich sowas wieder freigeben auf der HM?

**Comment by blackbasket** [comment]
Gar nicht auf der RM... für mich klingt es so, dass auf deinem System ausgehende Ports durch eine Firewall blockiert werden... deshalb geht's vom Handy auch problemlos...

Windows-Firewall prüfen... auf Linux zB iptables...

Oder hast du zufällig einen neuen Virenscanner installiert?

**Comment by demji1985** [comment]
Ahhhh. Da bringst du mich auf etwas....

Hab mit iptables mal rumgespielt, aber da ich das System so selten nutze, kaum noch daran gedacht. Danke für den Hinweis , das wird es sein! =)

**Comment by blackbasket** [comment]
:)

**Comment by demji1985** [comment]
Danke, geht wieder ;-)
