### ISSUE TITLE
Variable vom Typ Werteliste

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#446]
Ich habe mit den Variablen schon ein wenig gespielt, bekomme jedoch die gewünschte Funktionalität nicht abgebildet.

![Variable](https://user-images.githubusercontent.com/64675966/120486436-548dad00-c3b5-11eb-997a-18f6b165f432.jpg)

Ich möchte in HomeKit einfach nur angezeigt bekommen, welchen Wert die abgebildete Variable hat. Vermutlich sind die Werte (Texte) zu lang, diese könnten ich jedoch auch kürzer fassen.

Wie muss ich vorgehen?

**Comment by thkl** [comment]
Ich fürchte das geht so nicht.
Es gibt kein HomeKit Gerät was irgendwie Text anzeigt. Oder dem ich eine Liste an Zuständen mitgeben kann und dann wird durch Änderungen von Werten der passend referenzierte Text angezeigt.


Aktuell ist das was geht implementiert. Sollte Apple mit neuen Gerätetypen  in HomeKit daherkommen wird das vielleicht mal was. Aber ich vermute sowas wie eine Statusanzeige wird es nie geben.

**Comment by detLAN** [comment]
Hallo Thomas,

danke für die schnelle Antwort. Dann erstelle ich mir eine zweite Variable vom Wert Zahl lass die parallel zur eigentlichen Variablen laufen. Dann kann ich ja VariableAlarmAccessory nutzen.

Danke für Deine tolle Arbeit!
