### ISSUE TITLE
Problem: Einbindung HmIP Wetterstation Plus (HmIP-SWO-PL) - keine Temperatur

### ISSUE THREAD

**Issue by Schorsinator** [thkl/hap-homematic#447]
Hallo zusammen,

nachdem das Gerät auf der CCU3 wunderbar läuft, habe ich versucht meine HmIP Wetterstation Plus ins Hap einzubinden.
Als erstes habe ich den Service WeatherStation ausgewählt. Bei dieser Auswahl ist im Homekit aber gar nichts angekommen, es wurde lediglich angezeigt, dass es sich hier um ein inkompatibles Gerät handelt.

Dann habe ich den Service auf Thermometer geändert. Nun wird die Luftfeuchtigkeit korrekt angezeigt, leider bleibt die Temperaturausgabe immer bei 0,0!? 

Hat jemand ähnliche Probleme und hat ggf. ein Workaround dafür gefunden?
Bin über jede Hilfe dankbar!

![file](https://user-images.githubusercontent.com/71267045/120920580-c3258000-c6bf-11eb-9797-75e8086df57b.jpeg)

**Comment by thkl** [comment]
https://github.com/thkl/hap-homematic/issues/418#issuecomment-829490943

**Comment by Schorsinator** [comment]
Hallo thkl, 
vielen Dank für die Verlinkung. Leider hat die dort genannte Einstellung kein Erfolg gebracht.

VG

**Comment by thkl** [comment]
Die Wetterstation dürfte aber mit der Änderung nicht mehr auf unsupported stehen.

**Comment by Schorsinator** [comment]
Das wars, super vielen vielen Dank!

Ich hatte den Service noch auf Thermometer belassen.

**Comment by thkl** [comment]
Perfekt 🤩
