### ISSUE TITLE
HMIP-PSM Messwerte in Eve App unvollständig

### ISSUE THREAD

**Issue by tornenen** [thkl/hap-homematic#449]
Moin,

ich habe eine HMIP-PSM an meinem Whirlpool. Den Messwert Kanal habe ich als HomeMaticIPPowerMeterSwitchAccessory in HomeKit übergeben. Der Verbrauch (wenn einer anliegt) wird auch angezeigt. Aber der Gesamtverbrauch und die Gesamtkosten werden nicht angezeigt. 

Anbei ein Screenshot:
![image](https://user-images.githubusercontent.com/76594569/122380215-eece2300-cf67-11eb-8b7e-45b07d657bcc.png)

Ist das einfach so, oder kann man da was machen?

**Comment by JensBonse** [comment]
Das liegt an EVE.
Man kann bei Even die Kosten pro KWh etc. nur eintragen, wenn man von EVE eine Steckdose hat die das kann.
Da EVE ohne den €/KWh Wert nichts errechnen kann, zeigen die 0€ an.
Ist also kein Fehler von HAP-HomeMatic.

**Comment by tornenen** [comment]
Schade :(. Von den Eve Steckdosen habe ich nämlich schon 2 Stück mit dem Whirlpool durchgehauen.

Danke für die Info!
