### ISSUE TITLE
Besondere Geräte, wie funktioniert das?

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#45]
Meine Garagenanlage ich so aufgebaut:
<img width="523" alt="Bild1" src="https://user-images.githubusercontent.com/64675966/80916519-7901fa80-8d59-11ea-9f52-7f955240eaff.png">
Da ich nur einen Impuls brauch, steuere ich die Aktoren (grün) mit einem entsprechend konfigurierten virtuellen Taster an.
Im HAP hab ich jetzt einige Möglichkeiten durchgespielt, bekomme jedoch nur "Gerät wird nicht unterstützt". Was mache ich falsch?

**Comment by thkl** [comment]
In Adresse des Schließen Sensors muss die komplette Datenpunktadresse des Sensors der anzeigt das das Tor zu ist also dem HMIP SAM -> HmIP.12345ABCDE:1.MOTION 

Status Schließen muss true oder false rein je nachdem was der Sensor im geschlossenen Zustand meldet

Wenn kein eigener Offen Sensor (zb Optischer Sensor) vorhanden ist dann das leer lassen

Öffnen Aktor wäre die Adresse des Datenpunktes des Aktors der das Tor auf macht, wenn das eine virtuelle Taste ist dann zb BidCos-RF.BidCoS-RF:1.PRESS_SHORT für die erste Virtuelle Taste der Zentrale ... oder 

Nachricht ist ein JSON welches definiert was bei on (also Aktor wird von HK angesteuert)  oder off Aktor wird wieder aus geschalten gesendet wird

Das ganze noch für den Schließen Aktor ...

**Comment by detLAN** [comment]
Prima, danke für den Support! Gerät wird bereits dargestellt und funktioniert halbwegs. Ich bin kein Programmieren und muss nur auf die richtige Spur gebracht werden.

Hier noch ein kleiner Bug:
<img width="405" alt="Bild" src="https://user-images.githubusercontent.com/64675966/80924219-fba1ae80-8d87-11ea-8913-3076fc1e73e4.png">
Wenn man im Bereich "Besondere Geräte" ein Gerät bearbeitet und speichert, wird anschließend die Ansicht "Geräte" dargestellt. Die Pfadangabe bleibt jedoch auf "Besondere Geräte".

**Comment by thkl** [comment]
> Wenn man im Bereich "Besondere Geräte" ein Gerät bearbeitet und speichert, wird anschließend die Ansicht "Geräte" dargestellt. Die Pfadangabe bleibt jedoch auf "Besondere Geräte".

Jap, irgendwo biegt das JavaScript da falsch ab :) Das fix ich noch

**Comment by detLAN** [comment]
Eigentlich funktioniert das Garagentor, nur müsst ich die Verzögerung deaktivieren können. Wie geschrieben, wird der Impuls bereits durch meine Direktverknüpfung gegeben. Wenn jetzt noch ein Impuls kommt stoppt die Fahrt. Die 0 kann nicht gespeichert werden, diese wird zur default 5, Garagentor fährt an und im gleichen Augenblick stoppt es wieder.
<img width="334" alt="Bild" src="https://user-images.githubusercontent.com/64675966/80926555-580cca00-8d98-11ea-980b-a686a55a90ca.png">

Mit meiner Einfahrt und dem HmIP-SCI hab ich noch Probleme. Wenn ich es ähnlich wie oben Aufbau funktioniert es nicht. Kann es sein, dass der HmIP-SCI hier nicht unterstützt wird?
HmIP-RF.12345EDCBA:1.STATE   (HmIP-SCI)
CLOSE/OPEN
HmIP-RF.ABCDE12345:1.PRESS_SHORT  (HmIP-RCV)

**Comment by thkl** [comment]
Also ich muss noch was nachrüsten, das bei Key Aktoren kein Ausschaltsignal kommt. 
Egal welche Zeit eingestellt ist wird aktuell immer das Ausschaltsignal gesendet was den Key wieder triggert. 

Die 2. Sache mit versteh ich nicht ganz, was für Sensoren sind am Tor und was für Aktoren am Antrieb ?

**Comment by detLAN** [comment]
Bei der Rotamatic kann man den Status für offen / geschlossen direkt an der Steuereinheit abgreifen. Dies geht am einfachsten mit einem HmIP-SCI. Da die Rotamatic bei zweiflügligen Toren auch nur ein Flügel öffnen kann, hab ich zur Ansteuerung ein HmIP-PCBS2 verbaut. Der erste Kanal ist für die zweiflüglige und der zweite Kanal für die einflüglige Öffnung zuständig. Da auch hier nur ein Impuls gebraucht wird, hab ich auch hier wieder mit einem virtuellem HmIP Systemtaster und Direktverknüpfung gearbeitet. Für die HomeKit Integration möchte ich nur die zweiflüglige Variante nutzen.

**Comment by thkl** [comment]
Ok dann ist es sicher das gleiche Problem das einfach 2x der Taster ausgelöst wird.  

Ich denk mir mal was aus dafür ....

**Comment by thkl** [comment]
Ach und ab 37 gibt es unter Internes einen Punkt Support ... da kam man mit der Seriennummer eines Gerätes ein anonymisiertes Profil erstellen. Das bräuchte ich dann auch man für den Simulator hier. Das File heißt dann wie der Gerätetyp.

**Comment by detLAN** [comment]
Wie gewünscht anbei: [HmIP-SCI.json.txt](https://github.com/thkl/hap-homematic/files/4573079/HmIP-SCI.json.txt)

**Comment by thkl** [comment]
Ach verdammt das war eigentlich für den issue mit der Heizung gemeint 😂

**Comment by detLAN** [comment]
Kein Problem, siehe entsprechendes issue

**Comment by thkl** [comment]
so, ich habe das fürs nächste Release so umgebaut, das die Messages an die Aktoren optional sind. Das heisst wenn keine zwar eine On message aber keine Off da ist wird nur die On gesendet und nach dem delay keine Off. Das heisst KEY Datenpunkte werden damit nur einmal ausgelöst

**Comment by thkl** [comment]
0.0.38 kann jetzt KEY Devices nutzen dazu muss die Öffnen oder Schließen Nachricht so aussehen :

`{'on':true}`

Wenn der Off Wert fehlt wird kein Off Kommando gesendet

**Comment by detLAN** [comment]
> Wenn man im Bereich "Besondere Geräte" ein Gerät bearbeitet und speichert, wird anschließend die Ansicht "Geräte" dargestellt. Die Pfadangabe bleibt jedoch auf "Besondere Geräte".

Das Problem ist soweit behoben, jedoch wird der Seiteninhalt nicht aktualisiert. Fügt man z.B. ein  "Besonderes Geräte" hinzu, wird dies im ersten Moment nicht angezeigt.

Meine Garagenanlage will leider noch nicht so wie sie soll:
<img width="482" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81226363-060fb280-8feb-11ea-9d97-1ff32ee14e10.png">
Das Feld "Nachricht Schließen Aktor" darf nicht leer sein, so dass ich {"off":} eingesetzt habe. Verzögerungen möchte ich eigentlich keine, kann ich aber nicht auf 0 setzen.
Das Tor wird immer als offen angezeigt, auch wenn es geschlossen ist. Beim schließen wird angezeigt, dass das Tor schließt springt dann nach einem Moment wieder auf offen, obwohl das Tor weiterhin mit dem Schließen beschäftigt ist. Wenn ich während der Fahrt die Schaltfläche erneut betätige, kommt das Teil durcheinander. Es denkt das Tor fährt in die entgegengesetzte Richtung, dabei bleibt es einfach stehen. Erst bei erneutem betätigen der Schaltfläche geht die Fahrt entsprechend los.
Dies ist bei beiden Toranlagen gleich, also mit HmIP-SAM bzw.  HmIP-SCI und einem PCBS.

**Comment by thkl** [comment]
wirf mal bitte den Öffnen Sensor raus .. wenn dann müssen das 2 getrennte Sensoren sein
Frage ist wie schließ und öffnet man das Tor in der HomeMatic ?

**Comment by thkl** [comment]
äjm der Sensor liefert doch nicht closed oder open sondern true oder false ?

**Comment by detLAN** [comment]
Die Geräte Dokumentation spricht hier beim HmIP-SCI eindeutig von CLOSED und OPEN.
<img width="772" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81340642-759ba580-90b0-11ea-946e-5fd9399d934e.png">

**Comment by thkl** [comment]
Ja, aber das ist ein Enum eines Integers der kann nur Zahlen ..also 0 = close 1 = open

**Comment by detLAN** [comment]
Hallo Thomas, entschuldige, bitte siehe es mir nach, ich bin kein Programmierer. Habe jetzt auf 0 und 1 umgestellt. Allerdings zeigt er jetzt immer Schließen... bzw. Wird geöffnet... an, Geschlossen bzw. Geöffnet kennt er nicht.

**Comment by thkl** [comment]
Kein Ding .. deswegen erklär ich's ja ;)

Das andere Garagentor funktioniert, nur das hier mit dem SCI nicht ? .. 
Strange ... schau ich mir morgen mal an. Kann sein, das ich Target und Current Position umdrehen muss. Derzeit ist es so, das bei einem Event des Sensors dessen Wert mit den Settings verglichen wird. Wenn er matcht dann wird der Target State auf Closed gesetzt. Dann wird 1 sek gewartet, der Sensor neu befragt und der Current State gesetzt.

Du kannst ja mal den Debug Modus einschalten und nach einmal Tor auf Tor Zu das Log runterladen. Da siehst Du die Meldungen des Sensors und wie sie in HomeKit Zustände umgesetzt werden. Der Tor Service schreibt ins Log mit [SPGDS] am Anfang,

**Comment by detLAN** [comment]
Datei anbei. Da steht soviel drin, dass sagt mir leider gar nix. SPGDS gibt es 69 mal und ERROR kommt 27 mal vor.
[hap-homematic-log.txt](https://github.com/thkl/hap-homematic/files/4595887/hap-homematic-log.txt)

**Comment by thkl** [comment]
Ok eine Sache ist mir aufgefallen, das Gerät "Einfahrrt" wird augenscheinlich 2x versucht hinzuzufügen. Ich würde mir das gern genauer ansehen, um rauszufinden, wie das passiert ist.
Kannst Du bitte mal über die Backup Funktion ein Backup erzeugen. Und mir entweder das ganze oder auch nur die config.json daraus per Mail schicken. ( th.kluge@me.com )
Danke

**Comment by detLAN** [comment]
Garagentor (HmIP-SAM) und Einfahrt (HmIP-SCI) funktionieren jetzt bei mir.

Bleibt nur noch im die Aktualisierung der Seite "Besondere Geräte" nach Änderung bzw. Hinzufügen eines Gerätes.

**Comment by thkl** [comment]
Aktuell sollte aber nach dem Speichern die Seite auf den besonderen Geräten verbleiben ... 
Aktualisierung der Liste kommt noch

**Comment by detLAN** [comment]
Was ich gerade gesehen habe
![IMG_0907](https://user-images.githubusercontent.com/64675966/81551136-9fd7b680-9381-11ea-9dd2-c2b0b552bc9e.png)
Einfahrt ist offen und Garagentor geschlossen. Sollten die zwei letzten Schalter unten nicht genau andersherum sein? Funktionieren tut es, und wenn ich dann in den entsprechenden Dialog gehe, steht dort auch geöffnet/geschlossen.

**Comment by thkl** [comment]
Das sind die Tasten für Öffnen und Schließen oder ?

Ok wenn das Key Datenpunkte für die Aktoren sind kommt natürlich von denen keine Meldung das die aus sind.  Ich bau mal noch eine Funktion ein, welche die Dinger zurücksetzt.

**Comment by detLAN** [comment]
Unter der Home App funktionieren die Taster korrekt, einmal drauf tippen wird geöffnet, noch mal drauf tippen wird gestoppt oder falls öffnen bereits beendet wird geschlossen. Das zeigen die Tore auch schön an
![IMG_E88A740C3A36-1](https://user-images.githubusercontent.com/64675966/81552302-90596d00-9383-11ea-87d4-0a7db00cfa47.jpeg)
Unter der Home App funktionierte es soweit. In der Eve App wird ein Schalter angezeigt, der bei 0 geöffnet ist und bei 1 geschlossen - was etwas verwirrend ist.

**Comment by thkl** [comment]
Ja die HomeApp fasst alle Sensoren zu einer Kachel zusammen. Eve nicht deswegen kann Eve auch in der Wetterstation alles zeigen. 

Naja das bekommen wir auch noch hin.

**Comment by detLAN** [comment]
Für die Einfahrt gibt es noch eine Besonderheit in der Home App. Wenn offen und man dann den Taster betätigt wird angezeigt dass geschlossen wird, kurz darauf erscheint offen inkl. Meldung und wenn dann wirklich geschlossen ist wird dies auch wieder korrekt angezeigt. Da ist also ein Zwischenschritt drin, der da nicht reingehört

**Comment by detLAN** [comment]
Hier die Konfiguration für die Einfahrt (HmIP-SCI)
<img width="492" alt="Bild1" src="https://user-images.githubusercontent.com/64675966/81554484-2ba01180-9387-11ea-8ae6-b12a5c497d88.png">

Und hier die Konfiguration für das Garagentor (HmIP-SAM)
<img width="488" alt="Bild2" src="https://user-images.githubusercontent.com/64675966/81554498-3064c580-9387-11ea-885c-eacb6418b21b.png">

**Comment by thkl** [comment]
evtl mal die Zeit für Sensor Neuabfrage ändern .. also mindestens so groß machen wie das Tor läuft ... beim One Sensor Mode ist schwer vorherzusagen wann das Tor fertig ist

**Comment by thkl** [comment]
Also ich habe jetzt mal eine Garage gebaut mit den gleichen Geräten wie bei Dir:

![image](https://user-images.githubusercontent.com/884355/81594823-ccabbe00-93c1-11ea-8d18-4fe54394efe0.png)

Es verhält sich so : 
Ich tippe in Eve (Detailansicht) auf "Geöffnet" ... der Status wechselt auf "Öffnend" .. wenn der Beschleunigungsmelder eine Lageänderung erkennt geht der Status auf "Auf" ...

Ich tippe in Even auf "Geschlossen"  der Status wechsselt auf "Schließend" und bei Lageänderung dann geht der Status auf "Zu" .... 

Eigentlich so wie es sein soll oder ? .... Wenn ich den Lagesensor manuell ändere wechseln sowohl Zustand und auch Schalter auf die der jeweiligen Position zugeordnete Variante

**Comment by detLAN** [comment]
Hier mal im Video
[RPReplay_Final1589220740.MP4.zip](https://github.com/thkl/hap-homematic/files/4611534/RPReplay_Final1589220740.MP4.zip)

**Comment by thkl** [comment]
ich würde mal die Zeit Sensor Neuabfrage so weit hoch drehen, das sie länger ist, als das das Tor zum Schließen braucht. Dann kommt diese Abfrage nicht vor dem Event, den der Sensor eh liefert, wenn er seinen Zustand ändert.

**Comment by detLAN** [comment]
okay, werde ich morgen mal draußen messen. Die verdrehten Schalter unter Eve sind damit aber noch nicht behoben.

**Comment by thkl** [comment]
ähm das kann ich nicht beeinflussen ich kann nur an HomeKit senden CLOSED, OPENING, OPEN, CLOSING ... und wenn das in Home Passt und in Eve nicht ¯\_(ツ)_/¯

**Comment by detLAN** [comment]
Okay, dann schließe ich hier

**Comment by detLAN** [comment]
Nur zur Info, mit 14 Sekunden für die Einfahrt und 22 Sekunden für die Garage unter "Zeit Sensor Neuabfrage" fehlt jetzt wie vermutet der ungewollte Zwischenschritt 🤝🏻

**Comment by thkl** [comment]
Also zusammengefasst funktioniert die Garage jetzt wie gewollt ? Dann kann ich die gesammelte Erkenntnis mal in einen Hilfetext dafür gießen.

**Comment by detLAN** [comment]
Ja, jetzt funktioniert es wirklich prima - vielen Dank für Deine Mühe.
Einzig die umgekehrte Darstellung in Eve, aber damit kann man ja leben, zumal es in der Detailansicht ja korrekt beschriftet ist.
