### ISSUE TITLE
Nach Update keine Einstellung des Addons möglich

### ISSUE THREAD

**Issue by Mastergerdi** [thkl/hap-homematic#450]
Moin zusammen,
nach dem Update auf Version 0.0.62 sind alle meine Einstellungen verschwunden. Es ist auch nicht möglich neue Instanzen zu Erstellen. Das Startwizard zeigt nach dem klicken auf Fertigteilen keine Reaktion mehr und das Bild bleibt dunkel überblendet. 
Ein Löschen des kompletten Addons und Neuinstallieren sowie Einspielen eines Backups zeigt auch keine Änderung des Verhaltens.

Zum System:
Raspberry Pi 4 mit 8GB mit piVCCU3 in der aktuellen Version

**Comment by thkl** [comment]
was sagt denn das Log File

**Comment by Mastergerdi** [comment]
Ein Log File lässt sich leider aus dem Webinterface nicht herunterladen. Der Browser bleibt mit Ladebalken stehen. Leider ist auch kein File unter /var/log von dem Addon vorzufinden.

**Comment by thkl** [comment]
kann ich mal das Backup per Mail haben. Mailadresse steht in jedem Source File Header (bspw https://github.com/thkl/hap-homematic/blob/master/lib/Server.js)

**Comment by thkl** [comment]
Das ist das gleiche Problem wie in #452 und sollte in .63 erledigt sein

**Comment by ChrWi** [comment]
@Mastergerdi kann das Issue geschlossen werden?

**Comment by Mastergerdi** [comment]
@ChrWi  ja kann geschlossen werden.
