### ISSUE TITLE
Name ändert sich von alleine wieder auf „Default“

### ISSUE THREAD

**Issue by Draexl** [thkl/hap-homematic#451]
Erstmal dickes Lob, funktioniert super :-)

Ich habe eine Heizungssteuerunggruppe von der CCU in das Plugin eingebunden. Man kann in Homekit dann nochmals die einzelnen Namen innerhalb Des Gerätes verändern. Also Luftfeuchtigkeit, Temperatur oder ähnlich. Der Name der Temperaturanzeige bleibt stabil wenn man diesen ändert. Der Name der "Luftfeuchtigkeit" ändert sich nach gewisser Zeit bzw. nach einen Neustart wieder automatisch zum Defaultnamen. Ich hoffe man kann dies auf dem Screenshot erkennen. Hat sonst noch jemand das Problem?

![image](https://user-images.githubusercontent.com/86128006/122794510-9d51cb00-d2bc-11eb-9652-e3d74eaf2302.jpeg)

**Comment by beckentosch** [comment]
Ich habe ein ähnliches Problem. Bei mir wird die Gruppe der Heigzungssteuerung die eingebunden ist immer als Favorit gesetzt. Wenn ich Favoriten abwähle erscheint es nach einem Neustart wieder

**Comment by Draexl** [comment]
> Ich habe ein ähnliches Problem. Bei mir wird die Gruppe der Heigzungssteuerung die eingebunden ist immer als Favorit gesetzt. Wenn ich Favoriten abwähle erscheint es nach einem Neustart wieder

Das Problem habe ich auch...

**Comment by blackbasket** [comment]
Ist doppelt zu #533 ich mache das hier mal zu... das Problem ist identisch, wenn auch nicht mit dem  gleichen Heizungssensor... Namen werden immer resetted
