### ISSUE TITLE
HomeKit findet keine Geräte/Räume

### ISSUE THREAD

**Issue by Wheymisterio** [thkl/hap-homematic#452]
Ich habe heute auf meine die CCU3 das RaspberryMatic ( 3.57.5.20210525 ) installiert danach habe ich  die Version 14 von Hap-homematic über die Zusatzprogramme installiert.
Ich habe die Ports Freigegeben ( 9874; 9875; 9876; 9877; ...)
Ich kann die HAP-HomeMatic UI öffnen es werden mir aber keine Geräte angezeigt.

![UI](https://user-images.githubusercontent.com/23435719/122817638-730e0680-d2d8-11eb-8e0c-d5598d6b6dc7.PNG)
![UI2](https://user-images.githubusercontent.com/23435719/122817644-74d7ca00-d2d8-11eb-874f-c7e4f1b8aecb.PNG)
![instanz](https://user-images.githubusercontent.com/23435719/122817652-773a2400-d2d8-11eb-99ed-5c55d1830fcc.png)

mehrere Versuche über die UI einen Log herunterzuladen sind gescheitert.
ich habe 3 Räume in dene Rolläden und Lichtschalter sind.
hat jemand vielleicht eine schnelle Hilfe.

**Comment by blackbasket** [comment]
Hast du den CCU Cache über Internes schon mal geleert?

**Comment by Wheymisterio** [comment]
meinst du den cache des Browsers? den habe ich schon mehrmals gelöscht

**Comment by blackbasket** [comment]
Nein, wenn du links auf **Internes** klickst, **CCU Cache aktualisieren** auswählen...

**Comment by Wheymisterio** [comment]
das habe ich auch schon mehrmals gemacht

**Comment by TWIX99b** [comment]
Habe genau das gleiche Problem
HAP-Homematic mehrfach Cache geleert und auch schon ein Downgrade auf Version 12 durchgeführt mit dem selben Ergebnis

**Comment by Wheymisterio** [comment]
das mit dem Downgrade auf 12 habe ich auch versucht

**Comment by blackbasket** [comment]
Die Installer-Version wird's kaum sein... wenn, muss die 0.0.61 über CLI getestet werden...

**Comment by Wheymisterio** [comment]
das heißt ich muss die version 0.0.62 auf 0.0.61 ändern.
wie mach ich das ?

**Comment by blackbasket** [comment]
Ich vermute, dass es einen Schalter für den Befehl **npm install hap-homematic** gibt... muss ich aber selbst suchen...

**Comment by Wheymisterio** [comment]
wie führe ich das aus über ssh

**Comment by blackbasket** [comment]
Genau...

**Comment by Wheymisterio** [comment]
![putty](https://user-images.githubusercontent.com/23435719/122824057-6a213300-d2e0-11eb-8005-95a8d08761a2.png)

ich bin einfach unfähig habe ein wenig Linux/Ubuntu erfahrunf aber bekomme das nicht hin

**Comment by blackbasket** [comment]
Auch nicht mit sudo, wie es in der drittletzten Zeile steht?

Also **sudo npm ...**

**Comment by Wheymisterio** [comment]
nein hab ich getestet unbd apt, apt-get

**Comment by blackbasket** [comment]
Hmm, dann bin ich grad raus...

**Comment by Wheymisterio** [comment]
Oke aber danke erstmal für deine Hilfe, dann warte ich mal auf weiter antworten

**Comment by thkl** [comment]
apt gibt's auf der CCU nicht.  Und npm funktioniert nicht so einfach weil das default Cache Verzeichnis, in dem Falle /root, nicht beschreibbar ist. 


Was sagt denn das Log via WebUi von Hap (unter internes zu finden)

**Comment by Wheymisterio** [comment]
4 min versucht er was zu laden und dann sieht es so aus 
![Log](https://user-images.githubusercontent.com/23435719/122870845-7c29c280-d32e-11eb-8c76-b03ba8112127.png)

**Comment by Wheymisterio** [comment]
ein Backup kann ich über das WebUI von Hap erstellen. aber ein logfile ist nicht möglich

**Comment by thkl** [comment]
Ok könnte das Gleiche wie hier sein: https://github.com/thkl/hap-homematic/issues/450

Ich schau mir das nachher mal genauer an.

**Comment by Wheymisterio** [comment]
oke vielen dank wenn du etwas benötigst schreib kurz

**Comment by Wheymisterio** [comment]
falls es noch hilft Bei mir war es die erstinstallation von Homekit  hatte es noch nie drauf gehabt wie bei #450

**Comment by thkl** [comment]
ok, hab das  Problem gefunden.
Quick Fix : 

in  /usr/local/etc/config/addons/hap-homematic ein file namens evdps.json mit dem Inhalt 

```
[]
```

anlegen.


Der Check auf dieses File kommt nicht aus dem Promise zurück wenn das File nicht existiert.

Deswegen tritt der Fehler ab dieser Version bei noch nicht konfiguriertem AddIn auf

**Comment by Wheymisterio** [comment]
ich kann über putty nur die datei anlegen aber die [] werden nicht unterstützt

**Comment by thkl** [comment]
Alternativ das File https://raw.githubusercontent.com/thkl/hap-homematic/master/lib/HomeMaticCCU.js austauschen.
Auf der CCU liegt das in /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib ...

**Comment by TWIX99b** [comment]
Austauschen der Datei hat bei mir funktioniert DANKE!

**Comment by thkl** [comment]
0.0.63 ist auf dem Weg. Die Version fixt diesen Bug

**Comment by Wheymisterio** [comment]
so sry das ich so spät erst schreibe habe es mit dem austauschen der datei hinbekommen und es hat direkt alles funktioniert.
viel dank

**Comment by arndtk** [comment]
Hallo zusammen,

ich muss mich hier mal einklinken, denn das Problem besteht (zumindest bei mir) weiterhin. Schritt 1 wird übersprungen.
Version 0.0.63 ist installiert.

Was kann ich tun?

Grüße und Danke!
Arndt
