### ISSUE TITLE
Zeitversatz für Alarmanlage HomaticVariableAlarmAccessory

### ISSUE THREAD

**Issue by timwegenerDE** [thkl/hap-homematic#454]
Hallo Thomas,

ich hab mir wie in #78 eine Alarmanlage zusammengestöpselt. Funktioniert super :)

Wenn ich jetzt beim rausgehen Siri anbrülle, sie soll doch bitte die Alarmanlage anmachen, muss ich mich sehr beeilen und die Haustür zuschlagen. Hier wäre es super, wenn Sie erst nach ein paar Sekunden scharf stellt. Gibt es da bereits etwas?

P.S.: Nur durch deine Arbeit an diesem Plugin setze ich Homematic bei mir ein. Ich glaube eQ-3 verdankt dir eine menge Kunden! Und wenn die sich schon nicht bedanken, muss die Community das tun: Also wiederholt ein großes Lob und vielen Dank für deine tolle Arbeit! 👍

**Comment by thkl** [comment]
danke für die 🌷 .. und ja man könnte eine Verzögerung einbauen.
Aber warum schreist Du nicht Siri auf dem Phone an, wenn Du draussen bist ?

**Comment by JensBonse** [comment]
Oder einfach eine zweite Variable, die zeitverzögert dann den richtigen Alarm aktiviert?

**Comment by timwegenerDE** [comment]
@thkl weil an der Haustür noch der Homepod steht und der sich dafür anbietet und man ja auch mal die Hände voll hat und das Handy nicht rausholen kann / will.

@JensBonse hatte ich auch überlegt. Es wäre halt recht viel Aufwand, da ich ja eine zweite Variable die ganze Zeit synchron halten müsste. Bringt ja auch eine gewisse Fehleranfälligkeit mit. Und da ich dachte, dass das bestimmt auch nicht schlecht für andere wäre...

Wir können ja mal schauen, wie die Resonanz hier so ist. Wenn ich der einzige mit dem Wunsch bin, ziehe ich gerne zurück :)

**Comment by thkl** [comment]
eine Zeitverzögerung sind ein paar Zeilen Code .. das ist nicht so das Problem

**Comment by thkl** [comment]
bitteschön ....

**Comment by timwegenerDE** [comment]
Wie immer eine Freude! 🚀 😄
