### ISSUE TITLE
HmIP-BSL - Keine Antwort

### ISSUE THREAD

**Issue by oenskat83** [thkl/hap-homematic#457]
Ich habe im Flur einen HmIP-BSL, mit dem ich das Licht im HWR schalten kann. Also der "Schalter" ist dem HWR zugeordnet. Die beiden leuchtenden Tasten wiederum sind dem Flur zugeordnet und dienen als Nachtlicht. Diese sind mit einem Bewegungsmelder gekoppelt.
Seit neuestem werden im HomeKit sämtliche Geräte angezeigt als "Kein Antwort". Schiebe ich die beiden leuchtenden Tasten in einen anderen Raum, habe ich dort das gleiche und die anderen Geräte im Flur funktionieren wieder. Also egal wo ich die beiden Tasten hin schiebe, danach antwortet der ganze Raum nicht mehr.

Was kann ich tun?

**Comment by thkl** [comment]
Schaut aus als ob eine Instanz crasht. 
Sieht man da ggf was im LogFile ?

**Comment by oenskat83** [comment]
Es scheint eher an dem HmIP-BSL zu liegen. Die Instanzen habe ich alle schon neu gemacht. Habe das komplette HAP-Homematic gelöscht und neu aufgesetzt.
Nun ist es auch so, dass die Lichter bei Bewegung auch nicht mehr direkt an gehen. Irgendwas ist mit dem Teil nicht in Ordnung. Ich werde den die Tage mal auf Werkseinstellungen zurück setzen und dann noch mal schauen. Melde mich dann noch mal.

**Comment by thkl** [comment]
Hm ich sende nach einem HomeKit Request die aufbereiteten Daten zur CCU und wenn von dort ein Ergebnis kommt schicke ich die Rückmeldung zu HomeKit. Wenn jetzt von der CCU nichts oder ein Fehler kommt, dann unterbleibt die Rückmeldung an HomeKit und das Gerät geht auf "keine Antwort"

Die Ansteuerung der LEDs aus der CCU WebUI geht ?

**Comment by oenskat83** [comment]
Also ich habe nun den Schalter einmal komplett zurück gesetzt und überall raus gelöscht. Danach wieder wie neu eingerichtet. Leider gleiches Problem.
Die Ansteuerung in der RaspberryMatic läuft einwandfrei. Im Log kann ich persönlich nichts erkennen.

Firmware RaspberryMatic: 3.59.6.20210703
Firmware HAP-Homematic: 0.0.63

**Comment by thkl** [comment]
Ich habe leider keines dieser Schalter zum Test. Aber du könntest den hap Dämon auf der RM von der Commandline (ssh Login) starten und dem bei der Arbeit zuschauen.  Da fällt ggf eine Exception auf.  

https://github.com/thkl/hap-homematic/wiki/Troubleshooting#running-the-daemon-from-the-commandline

**Comment by oenskat83** [comment]
Ich habe nun mal von Dimmer auf Fan umgestellt und dann funktioniert es. Wieder zurück und Problem ist wieder da.
Ich teste das mal mit dem hap Dämon bei Gelegenheit.

**Comment by thkl** [comment]
Wie was ? Dimmer auf Fan ???

**Comment by oenskat83** [comment]
Im HAP kann ich das Gerät bearbeiten und kann in diesem Fall sagen, dass es im HomeKit als Ventilator (Fan) oder als Dimmer (Licht) angezeigt wird.

**Comment by ChrWi** [comment]
@oenskat83 am besten schickst du @thkl die relevanten Infos gemäß [Anleitung](https://github.com/thkl/hap-homematic/wiki/internals#support)

**Comment by blackbasket** [comment]
@oenskat83 besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)

**Comment by oenskat83** [comment]
Problem besteht noch. Ich habe aber aktuell keine Zeit mich darum zu kümmern.
Als „Fan“ funktioniert alles. Stelle ich es aber im HAP auf „Dimmer“ um, ist der ganze Raum plötzlich nicht mehr erreichbar.

**Comment by jhk3** [comment]
Evtl. hilft die Device Beschreibung [HmIP-BSL.json.txt](https://github.com/thkl/hap-homematic/files/11247626/HmIP-BSL.json.txt)
