### ISSUE TITLE
Falscher Change Log beim Überspringen einer Version

### ISSUE THREAD

**Issue by robbyHuelsi** [thkl/hap-homematic#458]
**Please describe your problem**
Als ich von 0.0.61 auf 0.0.63 updaten wollte, wurde mir der Change Log von 0.0.62 angezeigt (siehe Bild). Ist das so gewollt?

![IMG_0622](https://user-images.githubusercontent.com/10974639/125616612-b3c86f51-cc71-47d7-acc7-92c4e6ec6c74.jpeg)

**What happends**
Change Log der nachfolgenden, aber nicht der neusten Version wurde angezeigt. Hier: 0.0.62

**What should be happend**
Meines Erachtens wäre es sinnvoller den neusten Change Log anzuzeigen. Hier: 0.0.63
Oder vielleicht sogar die Logs von allen neueren Versionen? Hier: 0.0.62 + 0.0.63

**Steps to reproduce this issue**
Warte mit der Installation der nächsten Version und installiere erst die übernächste 😉

**Comment by thkl** [comment]
Das Wird aus dem File hier geparst .. https://github.com/thkl/hap-homematic/blob/master/CHANGELOG.md scheinbar geht da manchmal was schief

**Comment by ChrWi** [comment]
Ich denke, dass Issue ist geklärt
