### ISSUE TITLE
Das Gerät xx reagiert nicht.

### ISSUE THREAD

**Issue by hoteloskar** [thkl/hap-homematic#459]
Sehr häufig (nicht immer) bekomme ich von Siri die Antwort auf eine Schaltanweisung: „bin dran“ und kurze Zeit später „ Das Gerät xx reagiert nicht“ . Daraufhin wiederhole ich die gleiche Schaltanweisung und diese wird dann prompt ausgeführt.
Ist das normal?

**Comment by blackbasket** [comment]
Hi @hoteloskar ,

wenn du das von unterwegs machst und die App vorher länger nicht verwendet hast, leider ja. Aber Achtung, Schaltbefehle werden meistens ausgeführt!

LG,
Marcel

**Comment by hoteloskar** [comment]
Hi Marcel,
Danke für die schnelle Antwort.
Von unterwegs habe ich bisher noch nicht geschaltet, da kein Bedarf. Es passiert nur im Haus, wie soeben gerade wieder.
Mit App meinst du da die Home-App? 
Gruss, Hans

**Comment by blackbasket** [comment]
Hallo Hans,

ja, ich spreche von der Home-App. Im LAN konnte ich das Problem bisher nicht feststellen.

Schaltest du ein Gerät oder eine Szene?

LG,
Marcel

**Comment by hoteloskar** [comment]
Ich schalte ein Gerät. Mit der Home-App direkt gibt es auch keine Probleme. Nur die Befehle mit Siri funktionieren häufig erst beim zweiten Mal.

**Comment by blackbasket** [comment]
Hallo Hans,

über welches Device sprichst du Siri an? Falls Handy, ist WLAN im gleichen Netz verbunden?

Was nutzt du als Home-Zentrale?

LG,
Marcel

**Comment by hoteloskar** [comment]
Ich spreche Siri übers Handy an, im gleichen WLAN wie die homematic. Als Home-Zentrale nutze ich ein iPad.

**Comment by JensBonse** [comment]
iPad als Zentrale macht immer Probleme, das es in einen Energiesparmodus wechselt nach einiger Zeit.

Wenn du das iPad vorher mal aufweckst und dann den Siri Befehl per iPhone abgibst, sollte es sofort funktionieren.

Am besten ein Apple TV als Zentrale nutzen. Das dann falls möglich auch per LAN anschließen.

**Comment by blackbasket** [comment]
Danke @JensBonse ;)

**Comment by hoteloskar** [comment]
Da werde ich mal Siri ausschließlich übers iPad benutzen, dann müsste es ja sofort funktionieren. Vielen Dank für den Tip.
