### ISSUE TITLE
Bug: HomeMaticRadiatorThermostatAccessory

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#46]
Moin Thomas,
nach dem Version 0.0.37 veröffentlicht wurde gab es erst einmal keine Problem. Ich hab mir dann gedacht noch mal neu anzufangen, da die nicht erlaubten Zeichen in Namen gefixt wurden. Also alles auf Null, sowohl HAP auf der CCU deinstalliert und HomeKit zurückgesetzt.
Nach Neuinstallation alle Instanzen, Räume und Geräte neu hinzugefügt. Jetzt viel auf, dass in Räumen welche Heizkörper / Thermostate hatten, alle Geräte keine Antwort bekamen. Auf dem HAP für einen Raum die entsprechenden Geräte gelöscht. Und schon wurde der Status der restlichen Geräte wieder übermittelt. Wenn ich jetzt wieder die Heizkörper / Thermostate für diesen Raum hinzufüge beginnt dass gleiche Spiel, alle Geräte des Raums auf rot.
Beste Grüße aus dem Norden
Detlef

**Comment by thkl** [comment]
Bitte einmal das Log Downloaden (unter internes) und schauen ob’s errors gibt.  Und wenn ja mal das File hier anhängen.

**Comment by detLAN** [comment]
Wie gewünscht anbei: [hap-homematic-log.txt](https://github.com/thkl/hap-homematic/files/4573009/hap-homematic-log.txt)

**Comment by detLAN** [comment]
[HmIP-eTRV-2.json.txt](https://github.com/thkl/hap-homematic/files/4573181/HmIP-eTRV-2.json.txt)
[HmIP-WTH-2.json.txt](https://github.com/thkl/hap-homematic/files/4573182/HmIP-WTH-2.json.txt)
[HmIP-SRH.json.txt](https://github.com/thkl/hap-homematic/files/4573183/HmIP-SRH.json.txt)

**Comment by thkl** [comment]
Ok ich hab da einen Bug im HomeMaticRadiatorThermostatAccessory gefunden. Das sollte mit dem nächsten Update dann gehen.

**Comment by detLAN** [comment]
Ja Fehler mit v38 behoben.
