### ISSUE TITLE
MaticKeyMaticIP HmIP-DLD: Incorrect status when using unlock/lock and open door in combination

### ISSUE THREAD

**Issue by thkl** [thkl/hap-homematic#460]
### Discussed in https://github.com/thkl/hap-homematic/discussions/456

<div type='discussions-op-text'>

<sup>Originally posted by **Stiefelhagen** July 11, 2021</sup>
Hi

The new MaticKeyMaticIP HmIP-DLD is working fine. I can lock und unlock the door, and I can open it.
I configured unlock mode as unlock and checked the "add switch for opening".
There is one caveat:
When the door is locked and I open the door with the opening switch the command is properly executed, but the unlock switch remains in position locked instead of switching to unlocked. So this is a wrong status. For locking I have first to switch to unlock and than to lock back. This is a workaround. 

Do I need to configure something more to live without the workaround, or does this need some code change?

Best regards

Wilhelm</div>

**Comment by thkl** [comment]
@Stiefelhagen i will track this issue here. 

How long does the HmIP-DLD usually take to unlock and open the door. I will try to issue a state query after this time, so the state in HomeKit should be correct after that query.

**Comment by Stiefelhagen** [comment]
Hi Thomas

I have tested all combinations. For my Keymatic opening/closing/locking/unlocking is finishing after approximately 6 seconds.
Does not make too much difference which action I trigger. Perhaps 10 seconds is a good value to satisfy also other users with longer action time.

Best regards 

Wilhelm

**Comment by blackbasket** [comment]
@Stiefelhagen besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)

**Comment by Stiefelhagen** [comment]
I checked agiain all combinations. Seems to work correctly.
I will close the issue.

Best regards

Wilhelm

**Comment by Stiefelhagen** [comment]
Hallo Thomas

Es scheint jetzt korrekt zu funktionieren.
Ich bekomme den Bug allerdings nicht geschlossen.

Grüße

Wilhelm
