### ISSUE TITLE
Status: Keine Antwort 

### ISSUE THREAD

**Issue by Jemeins** [thkl/hap-homematic#461]
Moin,
ist es noch geplant die Verbesserung aus #275 einzubinden? 
Über eine Rückmeldung wäre ich dankbar!
Mit freundlichen Grüßen

**Comment by thkl** [comment]
Ich aktualisiere zwar das reachability Flag des Gerätes aber die drunterliegende Bibliothek hap-nodejs reicht das nicht zu HomeKit weiter. Dieses Flag wird auch offiziell nicht mehr von hap-nodejs unterstützt.

Ich fürchte da kann ich nicht viel machen
