### ISSUE TITLE
Installation does not seem to work on CCU3

### ISSUE THREAD

**Issue by robiwlan** [thkl/hap-homematic#467]
Running the installation on CCU3 with latest firmware. Installation seem to progress, CCU3 starts new, so far so good.
No new Icon available in system settings, in additional software, entry for installed version of Homekit available, buttons show up: Neustart, if pressed message comes up "Neustart fehlgeschlagen: Failure Success", Einstellen opens a new window but cannot display the config page ... no connection to server.
Ports are free, no further limitations in CCU3 setup.
Even older versions of Homekit show same problem.

Any idea where the issue sits, or to fix this?
Thx.

**Comment by 4EverChaos** [comment]
Made the same experience yesterday

**Comment by Lederhaut** [comment]
I have the same problem (Original Homematic IP CCU3), the /var/log/hmhapinstall.log says: 
[Installer]Check existency of the daemon
[Installer]Looks like the daemon is not here so start installer
[Installer]Running on node version:
v8.11.4
[Installer]NPM is :
5.6.0
[Installer]Program Dir is /usr/local/addons/hap-homematic
[Installer]installing HAP-Homematic ...
[Installer]creating HomeKit Button ...
[Installer]Adding .nobackup to addon dir ...
[Installer]we are done ...

**Comment by JensBonse** [comment]
Does your CCU has access to internet? That is needed for the installation as additional components are being downloaded after initial install finished.

**Comment by robiwlan** [comment]
Sure, permanent internet connection.

**Comment by JensBonse** [comment]
And the HomeKit button is still not working?

**Comment by robiwlan** [comment]
The Homekit Button does not show up, under additional software it indicates that HomeKit version 0.0.14 is installed.

**Comment by JensBonse** [comment]
What does the /var/log/hmhapinstall.log say?
You need to ssh into your CCU for that.

**Comment by robiwlan** [comment]
hmhapinstall.log says:

[Installer]NPM is :
5.6.0
[Installer]Program Dir is /usr/local/addons/hap-homematic
[Installer]installing HAP-Homematic ...
[Installer]creating HomeKit Button ...
[Installer]Adding .nobackup to addon dir ...
[Installer]we are done ...
[Installer]Check existency of the daemon
[Installer]Looks like the daemon is not here so start installer
[Installer]Running on node version:
v8.11.4

**Comment by blackbasket** [comment]
@robiwlan is this issue still existing? If not, close the ticket, please.

**Comment by robiwlan** [comment]
No solution received so far, maybe a unique problem with my setup.

**Comment by blackbasket** [comment]
#323 is not working for you?

**Comment by robiwlan** [comment]
unfortunately not, have copied the hap-homematic file into rc.d (was not there), the /addons/hap-homematic folder is empty, have removed and re-installed version 0.0.14, still same issue config page not available, etc.

**Comment by blackbasket** [comment]
> ja und ausführbar machen (also chmod +x .. oder das Ausführbar Attribut via FTP setzen) ..  /usr/local/addons/hap-homematic/etc/postinstall.sh muss auch +x werden ggf ist das auch nicht passiert

You did this, too? Especially the postinstall.sh

**Comment by blackbasket** [comment]
please copy the file https://github.com/thkl/hap-homematic/addon_installer/etc/postinstall.sh to /usr/local/addons/hap-homematic/etc/postinstall.sh and make sure that postinstall.sh as well as .../rc.d/hap-homematic are executable... (chmod +x)

**Comment by robiwlan** [comment]
Link leads to "Not Found"

**Comment by robiwlan** [comment]
got it, wrong link

**Comment by robiwlan** [comment]
both files are in the respective directory and executable, but still not working. the hap-homematic folder does only have the etc/postinstall.sh ... no more files are within the dir.

**Comment by blackbasket** [comment]
ok, and you have rebooted the system?

What happens if you start the service using ssh? `/etc/config/rc.d/hap-homematic start`

**Comment by robiwlan** [comment]
yes have rebooted several times.
Nothing happens when executing hap-homematic start

<img width="816" alt="image" src="https://user-images.githubusercontent.com/34417458/194038877-c6a3457b-976a-4ca2-97eb-275779d6f984.png">

**Comment by blackbasket** [comment]
my ideas are ending for the moment... @thkl do you have more ideas?

**Comment by thkl** [comment]
First please check if the daemon is running by ps -A command.
There should be a process called node with an argument like /usr/local/addons/hap-homematic/node-modules/hap-homematic/index.js

if the process is running please check your firewall .. to access the webUI you should have access to the port 9874 and for internals hap needs access to port 9875 ...

if not please check if the needed files are there:

please take a look into /usr/local/addons .. there should be a folder called hap-homematic .. if yes .. cc into it ..
there should be a package.json and a folder called node_modules .. if yes please try inside the /usr/local/addons/hap-homematic folder the following command:

node ./node-modules/hap-homematic/index.js

maybe there are some error messages which will be helpful ...

if the files are missing you can manually install them by running npm i hap-homematic inside /usr/local/addons/hap-homematic

**Comment by robiwlan** [comment]
as mentioned files are not there ... npm does show an error...

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/34417458/194062352-d42d06e6-9aef-4016-9a6e-e82acb471a98.png">

**Comment by thkl** [comment]
ok if your installation is missing complete please try to install the daemon by running npm i hap-homematic inside /usr/local/addons/hap-homematic

Please make sure you are sitting in the correct folder

**Comment by thkl** [comment]
sorry, without the "inside" ..  the inside belongs to the mentioned folder ... but the line break made it confusing

**Comment by thkl** [comment]
btw: the log shows npm i (which is the install command for a package) is not able to reach the node package registry ... are u sure your ccu has a valid internet connection ?

**Comment by robiwlan** [comment]
However it came into it, but there was a typo in my router IP gateway configuration, ... seems to work now.
Many thanks for your support!

**Comment by thkl** [comment]
👍

**Comment by robiwlan** [comment]
Issue has been resolved.
