### ISSUE TITLE
HmIP-MOD-HO (Homematic IP Modul für Hörmann-Antriebe )

### ISSUE THREAD

**Issue by docrossi** [thkl/hap-homematic#47]
wird es eine Unterstützung für HmIP-MOD-HO (Homematic IP Modul für Hörmann-Antriebe ) geben ??

**Comment by thkl** [comment]
Ja wenn ich ein paar Infos bekomme. Bitte mal die Internes/Support Funktion (ab v37) auf der Config Seite aufrufen, und entsprechend das Diagfile für das Gerät erzeugen und hier anhängen. Wie das geht steht dort.

**Comment by docrossi** [comment]
[HmIP-MOD-HO.txt](https://github.com/thkl/hap-homematic/files/4576478/HmIP-MOD-HO.txt)

**Comment by thkl** [comment]
Ich habe mal nachgeschaut, den Channeltyp DOOR_RECEIVER unterstütze ich mit HomeMaticGarageDoorOpenerAccessory ... das sollte schon gehen ... 

Wird der Kanal 1 des Gerätes nicht zur Auswahl für ein neues Device angeboten ?

**Comment by docrossi** [comment]
![IMG_53A7F042C3A9-1](https://user-images.githubusercontent.com/64773359/81036167-56c5c500-8e9e-11ea-872a-24e0da1772bf.JPG)

**Comment by thkl** [comment]
Nein, ich mein auf der Hap-Homematic Website

**Comment by docrossi** [comment]
<img width="1605" alt="Bildschirmfoto 2020-05-09 um 07 29 53" src="https://user-images.githubusercontent.com/64773359/81465023-12506700-91c7-11ea-8607-11e1e3182a9a.png">


wie genau werden die Datenpunkte eingetragen ??


<img width="1150" alt="Bildschirmfoto 2020-05-09 um 07 32 04" src="https://user-images.githubusercontent.com/64773359/81465040-390e9d80-91c7-11ea-8fff-0c81097c3c1b.png">

**Comment by thkl** [comment]
Ah ne das ist der Garagentoröffner aus diversen Geräten. Der Hörman kann über die normalen Geräte eingerichtet werden

**Comment by docrossi** [comment]
ja Steuerung funktioniert nicht es wird als Service HomeMaticGarageDoorOpenerAccessory angelegt im HomeKit kommt ... wird geöffnet aber es passiert nichts

**Comment by thkl** [comment]
Ok, da ich das Ding nicht habe: bitte mal über Internes das Debug einschalten. Einmal den Öffner über HomeKit betätigen und dann das Log Downloaden. Debug kann dann wieder aus (sonst wird weiter viel Log erzeugt). 

Den  Teil des Log, welcher die Zeit der Betätigung zeigt, bräuchte ich dann hier mal.  

Ggf sende ich ja einfach falsche Werte an die Homematic.

**Comment by docrossi** [comment]
[Uploading hap-homematic-log.txt…]()

**Comment by thkl** [comment]
Das mit dem Log ist bissel schief gegangen ... 
Ist das erledigt oder nur aus versehen zu ?

**Comment by docrossi** [comment]
[hap-homematic-log-2.txt](https://github.com/thkl/hap-homematic/files/4602909/hap-homematic-log-2.txt)


es passiert nichts ..

**Comment by docrossi** [comment]
[hap-homematic-log-3.txt](https://github.com/thkl/hap-homematic/files/4602912/hap-homematic-log-3.txt)

**Comment by thkl** [comment]
Es steht 2x DOOR_COMMAND 3 im Log was, wenn ich die Doku richtig lese, Schließen bedeutet.
Das Schließen Command kam auch so aus HomeKit ... und nix passierte ?

Ich werde mal die CCU Firmware durchwühlen, was die bei den Tasten in deren WebUI so machen

**Comment by docrossi** [comment]
so habe ich es auch aus der Doku verstanden .. --- anderes Projekt : bei IP Symcon kann ich gezielt ansteuern siehe Bild 
<img width="569" alt="Bildschirmfoto 2020-05-09 um 09 35 30" src="https://user-images.githubusercontent.com/64773359/81467365-7af40f80-91d8-11ea-8adf-915863403673.png">

**Comment by thkl** [comment]
Das ist der DOOR_STATE der liefert die Rückmeldung über den gegenwärtigen Zustand. Na ich schau mal

**Comment by thkl** [comment]
Also das WebUI der CCU macht folgendes beim Betätigen

Close : DOOR_RECEIVER.DOOR_COMMAND - 3
Open: DOOR_RECEIVER.DOOR_COMMAND - 1

Im Service setze ich DOOR_COMMAND auf 1 beim Öffnen Befehl und DOOR_COMMAND 3 beim Schließen ...


Anzeige:
======

DOOR_RECEIVER.DOOR_STATE = 0 -> Geschlossen
DOOR_RECEIVER.DOOR_STATE = 1 -> Offen
DOOR_RECEIVER.DOOR_STATE = 2 -> Lüften

In dem Service setze ich bei DOOR_STATE 0 Homekit auf geschlossen und bei allen anderen auf Offen


Eigentlich sollte das genau so funktionieren

**Comment by thkl** [comment]
Nachtrag: Ich tausche mal noch das Timing beim Setzen des Current und Target Zustandes, das hat augenscheinlich Einfluß auf die Darstellung im HomeKit.

**Comment by docrossi** [comment]
gibt es was neues

**Comment by docrossi** [comment]
leider funktioniert es noch nicht in der 0.40 Version Ich konnte zwar das Garagentor öffnen aber schließen ging nicht und die Rückmeldung kam nicht.

**Comment by thkl** [comment]
wenn das Tor aus der CCU Oberfläche bedient wird, aktualisiert es sich in Homekit dann ?

**Comment by docrossi** [comment]
Status unverändert.

**Comment by allesistmoeglichoderauchnicht** [comment]
leider ändert sich der Status nicht, wenn man in der CCU Oberfläche öffnet oder schließt. Es bleibt unverändert auf "wird geöffnet". Habe 2 Tore und bei beiden ist das der Fall. Kann ich ein Log schicken? wenn ja welches?

**Comment by thkl** [comment]
Ja ich hab gestern noch was an dem Service gemacht. Mir ist nach dem Erstellen des UnitTests aufgefallen, das die Statusrückmeldungen an HomeKit falsch waren. Das ist schon im Source korrigiert und kommt dann mit 0.0.41
