### ISSUE TITLE
Kontaktsensor als Wassermelder

### ISSUE THREAD

**Issue by timwegenerDE** [thkl/hap-homematic#473]
Hallo Thomas,

ich mal wieder mit einer kleinen Anfrage, ohne jede Dringlichkeit ;)

Ich würde gerne einen Kontaktsensor HmIP-FCI1 als Wassersensor bekanntmachen. Ich habe da nämlich das Eve Waterguard-Verlängerungskabel dran gebastelt. Direkt über die Geräte scheint dies nicht zu gehen, da er mir HomeMaticVariableBinarySensorAccessory nicht zur Auswahl gibt. Ich mache das jetzt mit dem Zwischenschritt über eine Variable (was man sich dann einfach nur sparen könnte).

Vielen Dank und viele Grüße
Tim

**Comment by timwegenerDE** [comment]
...
allerdings stelle ich gerade fest, dass der Lecksensor über die Variable nicht auslöst. Im Log steht 

`[Sat Aug 21 2021 20:53:06 GMT+0200 (CEST)] debug - [HAP Server] [CCU] Küche Leck Sensor return variable value 
[Sat Aug 21 2021 20:53:06 GMT+0200 (CEST)] debug - [HAP Server] [CCU] var Update Event Küche Leck Sensor will be handled by 3 registered callback
[Sat Aug 21 2021 20:53:06 GMT+0200 (CEST)] debug - [HAP Server] [Variable] update state false
[Sat Aug 21 2021 20:53:06 GMT+0200 (CEST)] debug - [HAP Server] [HomeMaticVariableBinarySensorAccessory] Küche Leck Sensor skipp update Leak Detected cause the value stayed the same 0 (force is false)
[Sat Aug 21 2021 20:53:06 GMT+0200 (CEST)] debug - [HAP Server] [Variable] update state false
[Sat Aug 21 2021 20:53:06 GMT+0200 (CEST)] debug - [HAP Server] [HomeMaticVariableBinarySensorAccessory] Küche Leck Sensor skipp update Leak Detected cause the value stayed the same 0 (force is false)
[Sat Aug 21 2021 20:53:06 GMT+0200 (CEST)] debug - [HAP Server] [Variable] update state false
[Sat Aug 21 2021 20:53:06 GMT+0200 (CEST)] debug - [HAP Server] [HomeMaticVariableBinarySensorAccessory] Küche Leck Sensor skipp update Leak Detected cause the value stayed the same 0 (force is false)`

Die Variable ist ganz normal als Logikwert erstellt mit "ist wahr" / "ist falsch".
Variable Neuerstellen / Triggerprogramm aktualisieren haben nicht geholfen.

**Comment by JensBonse** [comment]
Also laut LOG hat die Variable keinen anderen Wert als 'ist falsch' / false / 0 angenommen.
Ggf. stimmt da etwas an der Trigger Logik bei dir nicht.

**Comment by timwegenerDE** [comment]
Hab ich mehrfach geprüft; Die Variable setzt korrekt, kommt aber nicht im HAP an.

Ich hab den Sensor jetzt woanders eingesetzt. Mein Bedarf wäre damit hinfällig.

**Comment by timwegenerDE** [comment]
Nachtrag: Grund war ein Umlaut im Variablennamen.
