### ISSUE TITLE
Mehr als 50 Geräte

### ISSUE THREAD

**Issue by LEB01** [thkl/hap-homematic#476]
Hallo Zusammen,

nach kleinen Schwierigkeiten läuft meine Installation nunmehr tadellos. Leider ist es mir aber nicht möglich mehr als 50 Geräte einzurichten. Gibt es hier eine Beschränkung und wenn ja, wie lässt sich diese Grenze erhöhen.

Vielen Dank vorab und viele Grüße 

LEB01

**Comment by ChrWi** [comment]
@LEB01 bitte stelle die Frage zu den Lamellen in einem neuen Beitrag, da @thkl da ggf weitere Infos zum Gerät benötigt. Da dein ursprüngliches Problem / Cache / gelöst ist, schließe ich dieses Thema
