### ISSUE TITLE
HomeKit aktualisiert ständig

### ISSUE THREAD

**Issue by markusholt** [thkl/hap-homematic#477]
Mit der Aktualisierung der HAP-HM auf die Version 0.63 lief zu Beginn alles bestens. Mittlerweile muss ich bei jedem Start der HomeKit-App ca. 20s auf die Aktualisierung warten. An der Konfiguration habe ich nichts geändert.
Was kann ich tun, um wieder schnellere Reaktionszeiten zu bekommen?

**Comment by JensBonse** [comment]
Im WLAN auch? Oder nur unterwegs?
Welchen HUB von Apple nutzt du? iPad, HomePod oder Apple TV?

**Comment by markusholt** [comment]
Ich nutze ein IPad.
Die Aktualisierungsverzögerung taucht im WLAN auf.

Viele Grüße 
Markus Holthaus
- mobil gesendet -

**Comment by JensBonse** [comment]
Hat sich an deinem WLAN etwas geändert? Irgendwo ein Firmware upgrade gemacht oder ähnliches?

Generell sind iPads leider nicht so gut als Hub geeignet. Problem ist hier das Energiemanagement. Da geht das WLAN des iPad nach einiger Zeit in den Energiesparmodus. Dadurch ist der Hub dann nicht sofort erreichbar und das iPad muss erst aufwachen, um dann die Anfrage an HomeKit zu beantworten.

Die besten Erfahrungen habe ich mit Apple TV als Hub gemacht. Da man das Apple TV per Kabel direkt mit dem Netzwerk verbinden kann.

**Comment by markusholt** [comment]
..ah, ok, danke.

Es hat nur mit dem IPad bis vor 3 Wochen problemlos funktioniert.

Keine Änderungen im WLAN.
Bin ein wenig ratlos…

Viele Grüße 
Markus Holthaus
- mobil gesendet -

**Comment by JensBonse** [comment]
Zum testen das iPad einfach mal aufwecken und dann erst im Handy HomeKit öffnen.
Dann sollte es innerhalb von 1-2 Sekunden aktualisieren.

**Comment by markusholt** [comment]
…ok, ich probiere es aus.

Danke Jens.

Viele Grüße 
Markus Holthaus

- mobil gesendet -

**Comment by JensBonse** [comment]
Erledigt?
Falls ja, dann bitte schließen.

**Comment by markusholt** [comment]
Jens,
leider habe ich das Problem immer noch und bisher leider keine Lösung gefunden.

Viele Grüße 
Markus Holthaus
- mobil gesendet -

**Comment by JensBonse** [comment]
Verstehe ich das also richtig, dass in der Home APP an den Geräten permanent 'Aktualisieren' steht, aber es passiert dann einfach nichts?
Wie lange hast du schonmal gewartet, um zu sehen ob doch noch was passiert?

Hast du eine originale CCU3 oder einen Eigenbau?

Hattest du ggf. ein neues Gerät zur CCU hinzugefügt und das dann auch in HomeKit integriert? Also zu dem Zeitpunkt etwa wo es aufhörte zu funktionieren.

**Comment by JensBonse** [comment]
Hattest du das denn probiert:

> Zum testen das iPad einfach mal aufwecken und dann erst im Handy HomeKit öffnen.
Dann sollte es innerhalb von 1-2 Sekunden aktualisieren.

**Comment by markusholt** [comment]
…ja, habe es gerade auch noch einmal probiert. Aber leider ohne Erfolg:-(


Viele Grüße 
Markus Holthaus
- mobil gesendet -

**Comment by ChrWi** [comment]
Das klingt alles sehr merkwürdig. Bei mir läuft die .63 total stabil. Das muss eine andere Ursache haben.

**Comment by blackbasket** [comment]
@markusholt besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)
