### ISSUE TITLE
HAP in Raspberrymatic -> virtuellen Maschine auf einer Synology Temperatur als besonderes Gerät

### ISSUE THREAD

**Issue by mike4president** [thkl/hap-homematic#478]
Moin, wenn ich die CCU Temp als besonderes Gerät einrichten möchte, werden nur 0.00 Grad übertragen. Liegt das an meinerr Konstellation Raspberrymatic in einer virtuellen Maschine auf meiner Synology?

**Comment by JensBonse** [comment]
Wird in der CCU in der Variablen denn ein Wert angezeigt?
Ich vermute, dass deine Annahme bzgl. VM schon richtig ist und da erst gar keine Temperatur ankommt.

**Comment by mike4president** [comment]
Kann ich leider nicht mehr schauen. Ich habe wieder den AccessPoint im Einsatz und setzte aktuell auf dieses Plugin: 

https://github.com/marcsowen/homebridge-homematicip#readme

Anfrage ist damit erledigt.
