### ISSUE TITLE
Helligkeitswerte der Bewegungsmelder ... keine Lux Werte

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#48]
Hallo Thomas

Die Lichtwerte der Bewegungsmelder (z.B.: HM-Sen-MDIR-O-2, HM-Sen-MDIR-WM55) werden ja in der CCU in Werten zwischen 0-255 angezeigt. Dieser Wert wird 1:1 übernommen und als Lux in HK angezeigt. Das sind aber keine Lux :-)
Könnte man das umrechnen (wenn auch ganz richtig nicht geht ... ) ?
![IMG_6339](https://user-images.githubusercontent.com/30420568/80949994-5ae9d800-8df5-11ea-8cba-5b6f2094de97.PNG)
lg Richard

**Comment by roe1974** [comment]
PS: Hätte das hier noch gefunden:
![Screenshot 2017-11-04 17 15 25](https://user-images.githubusercontent.com/30420568/80950170-a69c8180-8df5-11ea-9c5e-656245301c21.png)

plus diese Formel dazu .....:

Input from 0-19

	0.01*((0.2/0.01)^1/20)^x

Input from 20-86

	1/((1/0.2)^1/67)^87*((1/0.2)^1/67)^x

Input from 87-255:

	0.0009*((10000/3)^1/100)^x

**Comment by thkl** [comment]
WTF ....

Ok ich schau mal wie ich das umrechnen kann.

**Comment by roe1974** [comment]
da die lichtwerte, gerade gesehen (siehe unten), im geschlossenenn Raum sowieso nie 500 übersteigen kann man das so lassen wie es ist .... einzig für die outdoor Varianten (zB HM-Sen-MDIR-O-2) wäre das ein Thema ... wenn im Aussenbreich angebracht .... vielleicht als option zum anklicken (umrechnung ja/nein) .... 
hier noch die werte:
![grafik](https://user-images.githubusercontent.com/30420568/80958876-0864e780-8e06-11ea-81d7-7e194f877238.png)
lg Richard
