### ISSUE TITLE
Neue Geräte hinzufügen klappt nicht

### ISSUE THREAD

**Issue by ManiCEO** [thkl/hap-homematic#481]
### Discussed in https://github.com/thkl/hap-homematic/discussions/480

<div type='discussions-op-text'>

<sup>Originally posted by **manfredbognar** September 11, 2021</sup>
Hallo,

zunächst meine Konfiguration:
CCU3 mit RasperryMatic  3.59.6.20210807
HAP-HomeMatic 0.0.64
HomeMatic HM-PBI-4-FM Funktaster 4-fach
10 HAP-Instanzen mit insgesamt 18 Geräten

Ich nutze HAP-Homematic jetzt seit ca **10 Monaten ohne Probleme** in einem Testbetrieb. Über einen Tastendruck am Funktaster, als "HomeMaticKeyAccessory" in HAP-HM/Homekit eingebunden, löse ich dann eine Szene aus.
 
Nun wollte ich komplett umstellen und **weiter Funktaster hinzufügen**. Das klappt aber nicht. 
Die Taster werden in der Homekit App angezeigt, aber **bei betätigen des Funktasters triggern sie nicht**. Das kann man schon sehr gut optisch erkennen. Wenn sie triggern, verändert sich das Icon für eine Sekunde. 

Ich hab die Funktaster natürlich auf Funktion geprüft, sie gelöscht und wieder eingebunden, andere Funktaster eingebunden, zu anderen Instanzen hinzugefügt und so weiter. FW/Ports geprüft. Die Instanzen und Geräte sind in der Homekit App erreichbar. 
Alle bei der Erstinstallation hinzugefügten Taster funktionieren nach wie vor **einwandfrei.**

Das **Log** für einen **funktionierenden Taster** sieht so aus:
[HAP Server] [CCU] event BidCos-RF.IEQ0042733:3.PRESS_SHORT
[HAP Server] [CCU] event BidCos-RF.IEQ0042733:3.PRESS_SHORT will be handled by 1 registered callback
[HAP Server] PRESS_SHORT Event send 0
[HAP Server] [HomeMaticKeyAccessory] IEQ0042733 updating Programmable Switch Event to 0 (true)
[HAP Server] [RPC] event for BidCos-RF.IEQ0042733:3.INSTALL_TEST with value true
[HAP Server] [CCU] event BidCos-RF.IEQ0042733:3.INSTALL_TEST
[HAP Server] [RPC] event for BidCos-RF.BidCoS-RF:3.PRESS_LONG with value true
[HAP Server] [CCU] event BidCos-RF.BidCoS-RF:3.PRESS_LONG

Das **Log** für einen **NICHT funktionierenden** sieht so aus:
[HAP Server] [RPC] event for BidCos-RF.IEQ0042902:1.INSTALL_TEST with value true
[HAP Server] [CCU] event BidCos-RF.IEQ0042902:1.INSTALL_TEST
 
Ich bin da etwas ratlos. Hat **bitte** jemand noch eine Idee?
**Danke** & LG Mani
</div>

**Comment by ChrWi** [comment]
Hallo @mani-bog, ggf. ist dies identisch mit #373 => bei mir haben die Tasten getriggert, nachdem ich zwischen Löschen und Neuanlage den Cache manuell gelöscht habe (Verzeichnis /etc/config/addons/hap-homematic/persist, IdentifierCache.xxxxx.json, z.B. per FTP) und den HAP Service neu gestartet habe (dann werden die Dateien wieder angelegt).

**Comment by blackbasket** [comment]
@ManiCEO besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)
