### ISSUE TITLE
HomeMaticSPTwoSensorWindowAccessory zeigt falschen Status

### ISSUE THREAD

**Issue by DrTob** [thkl/hap-homematic#490]
Ich habe ein HomeMaticSPTwoSensorWindowAccessory erstellt. Hängt an einem HmIP-SRH + HHmIP-SWDO-I. Wenn ich das Fenster bediene funktioniert das auch (-> komplett geschlossen = geschlossen. Geschlossenes Fenster mit Griff auf offen oder gekippt zeigt 10%. Gekippt = 25% offen = geöffnet). Jedoch wechselt der Zustand nach einiger Zeit auf "geöffnet", obwohl beide Sensoren nach wie vor geschlossen melden. Gestern hat das Gerät zwischendurch auch mal wieder "geschlossen" gemeldet, meist meldet er jedoch offen. Woran kann das liegen?

**Comment by blackbasket** [comment]
@DrTob besteht das Problem noch? Sonst bitte das Ticket schließen. Danke :)

**Comment by ChrWi** [comment]
Ich mache das hier mangels Feedback zu
