### ISSUE TITLE
Siri gibt komische Antwort wenn ich nach der aktuellen Temperatur in einem Raum Frage. Und einige Geräte "reagieren" nicht.

### ISSUE THREAD

**Issue by HookHM** [thkl/hap-homematic#495]
Hallo @thkl ,

ich habe u.a. meine Heizthermostate aus der "Gruppe" in HomeKit hinzugefügt:
![IMG_8962](https://user-images.githubusercontent.com/55434236/137633703-f741cfc0-7934-477b-852f-2bf56458c004.jpeg)

Wenn ich Siri nun Frage, wie warm ist aktuell im Raum XY ist, dann erhalte ich diese Antwort:
![IMG_8963](https://user-images.githubusercontent.com/55434236/137633897-cc76aca1-4285-4172-b09b-3d733abebdec.jpeg)

![IMG_8964](https://user-images.githubusercontent.com/55434236/137633899-dac843ee-6006-4f35-a69d-d7fa4e7f88c4.jpeg)

In anderen Räumen sieht die Antwort so aus:
![IMG_8965](https://user-images.githubusercontent.com/55434236/137634024-003875d1-b38d-4733-80c2-9fe70edcc190.jpeg)

![IMG_8966](https://user-images.githubusercontent.com/55434236/137634027-787876a2-0a9c-483c-b51c-7dc64bcc2e43.jpeg)

![IMG_8967](https://user-images.githubusercontent.com/55434236/137634028-49695c42-1f13-409a-9db7-9a2641b11c15.jpeg)

Wenn ich Siri nach der Luftfeuchtigkeit Frage, dann funktioniert das. Und hier wird ja das gleiche Gerät abgefragt:
![IMG_8970](https://user-images.githubusercontent.com/55434236/137634391-9457961d-a0ad-4679-b4eb-c654321337b3.jpeg)

Hast Du da eine Idee, oder Einfluss drauf? Oder Frage ich die Olle einfach nur falsch?

Manchmal kann ich die Heizungsgeräte (auch nur diese Geräte) nicht steuern, also nur per Siri nicht steuern, in der Home App geht es, und es kommt auch keine Fehlermeldung
![IMG_8968](https://user-images.githubusercontent.com/55434236/137634126-6d478370-ed7e-40d3-bac6-cd4349e71f2c.jpeg)

Wenn ich einen Neustart von HAP mache, dann geht es wieder für ein paar Minunten:
![IMG_8969](https://user-images.githubusercontent.com/55434236/137634229-1e495200-0517-4f3e-aa0d-d153e7f99ae6.jpeg)

**Comment by blackbasket** [comment]
Existiert das Problem noch, @HookHM ?

**Comment by HookHM** [comment]
Ja natürlich. Aber ich weiß immer noch nicht welche Config bzw. wo? Wo in "Geräteliste -> Bearbeiten" ? in der CCU WebUI oder in der HAP-WebUI?

**Comment by ChrWi** [comment]
Existiert das Problem noch, @HookHM ?

**Comment by ChrWi** [comment]
Da kein Input mehr…
