### ISSUE TITLE
Feuermelder können nicht hinzugefügt werden 

### ISSUE THREAD

**Issue by Milo-PRT** [thkl/hap-homematic#5]
Hallo Thomas
die Feuermelder (HmIP-SWSD), welche in der CCU3 (pivCCU3 3.51.6-39) angelernt sind, können im HAP nicht hinzugefügt werden, da sie erscheinen leider bei der Geräteauswahl nicht. 
Habe ich was falsch gemacht oder ist dies ein "Käfer"?
Beste Grüsse

**Comment by thkl** [comment]
Ich schau mal wenn die nicht unterstützt werden, weil der Kanaltyp keinen Service findet werden sie nicht angezeigt.  Ich muss mal in der Doku schauen wie der Kanaltyp heißt.

**Comment by thkl** [comment]
Ok ich hab einen Nebensatz hier überlesen. Raumelder angelernt. Die aktuelle Version braucht noch 2 Neustarts des HAP Services damit neu angelernte Geräte automatisch in der Geräteliste auftauchen. Das wird in einem der nächsten Updates gefixt. Dann regagiere ich auch auf einen NewDevices Call der CCU und lese die Liste der Geräte neu ein.

Also über das WebUI des HAP Plugins dieses Neustarten ... kurz warten, dann noch mal neu starten und dann sollte es gehen. Denn unterstützt werden diese Rauchmelder schon.

Hintergrund 2x Reboot: Beim Boot wird erst ein mal die gecachte Geräteliste verwendet und wenn das Ding hochgefahren ist lese ich erst eine neue Version und schreib die ins config Verzeichnis ....

**Comment by Milo-PRT** [comment]
Danke für Deine schnelle Rückmeldung. Leider sind die Rauchmelder trotz dem Doppelneustart, wie auch nach einer Neuinstallation des gesamten WEBUI in den Gerätenlisten nicht ersichtlich. Meine RM's waren in der CCU nicht neu angelernt, sondern schon vorhanden - oder meinst du das neu anlernen im WEBUI?

hab dir mal mein LOG angefügt.
[hap-homematic-log-3.txt](https://github.com/thkl/hap-homematic/files/4476156/hap-homematic-log-3.txt)

beste Grüsse

**Comment by thkl** [comment]
ok ich schau mir das mal an ...

**Comment by thkl** [comment]
ok ich hab den bug gefunden ... ein Update auf 0.0.21 sollte das Problem beheben

**Comment by Milo-PRT** [comment]
ok, mit der 0.0.21 werden sie angezeigt. Danke für Deine Unterstützung

TOP!!

Grüsse

**Comment by Milo-PRT** [comment]
Hallo Thomas

Wollte heute das weitere Einbinden der Rauchmelder an die Hand nehmen. Sie sind zwar im Reiter Geräte ersichtlich, jedoch kommt nach dem klick auf „auswählen“ das bekannte Auswahlfeld nicht.
Das Einzuge was sich ändert ist, dass das inaktive „Fertigstellen“ nun aktiv markiert wird.

Beste Grüsse 

Beat

**Comment by thkl** [comment]
bitte mal auf die browserconsole wechseln und dort schauen ob Javascript Fehler auftauchen ... 
zb in Chrome geht das mit rechtsklick auf die seite > untersuchen > reiter console .. da wird a) angezeigt welcher fehler wo auftaucht und b) in den usermessages welche daten zwischen browser und server hin und her fließen

**Comment by Milo-PRT** [comment]
DevTools failed to parse SourceMap: http://IP:9874/js/coreui.bundle.min.js.map
DevTools failed to parse SourceMap: http://IP:9874/js/bootstrap.min.js.map
DevTools failed to parse SourceMap: http://IP:9874/css/style.css.map
DevTools failed to parse SourceMap: http://IP:9874/css/free.min.css.map


{"devices":[{"device":"00155A49970AC6","name":"Eingangstüre","type":"HmIP-SWDM","channels":[{"id":1415,"address":"00155A49970AC6:1","name":"Eingang","type":"SHUTTER_CONTACT"}]},{"device":"00155A4996FE54","name":"Garagentor","type":"HmIP-SWDM","channels":[{"id":1453,"address":"00155A4996FE54:1","name":"Garagentor","type":"SHUTTER_CONTACT"}]},{"device":"BidCoS-RF","name":"HM-RCV-50 BidCoS-RF","type":"HM-RCV-50","channels":[{"id":1014,"address":"BidCoS-RF:1","name":"HM-RCV-50 BidCoS-RF:1","type":"VIRTUAL_KEY"},{"id":1018,"address":"BidCoS-RF:2","name":"HM-RCV-50 BidCoS-RF:2","type":"VIRTUAL_KEY"},{"id":1022,"address":"BidCoS-RF:3","name":"HM-RCV-50 BidCoS-RF:3","type":"VIRTUAL_KEY"},{"id":1026,"address":"BidCoS-RF:4","name":"HM-RCV-50 BidCoS-RF:4","type":"VIRTUAL_KEY"},{"id":1030,"address":"BidCoS-RF:5","name":"HM-RCV-50 BidCoS-RF:5","type":"VIRTUAL_KEY"},{"id":1034,"address":"BidCoS-RF:6","name":"HM-RCV-50 BidCoS-RF:6","type":"VIRTUAL_KEY"},{"id":1038,"address":"BidCoS-RF:7","name":"HM-RCV-50 BidCoS-RF:7","type":"VIRTUAL_KEY"},{"id":1042,"address":"BidCoS-RF:8","name":"HM-RCV-50 BidCoS-RF:8","type":"VIRTUAL_KEY"},{"id":1046,"address":"BidCoS-RF:9","name":"HM-RCV-50 BidCoS-RF:9","type":"VIRTUAL_KEY"},{"id":1050,"address":"BidCoS-RF:10","name":"HM-RCV-50 BidCoS-RF:10","type":"VIRTUAL_KEY"},{"id":1054,"address":"BidCoS-RF:11","name":"HM-RCV-50 BidCoS-RF:11","type":"VIRTUAL_KEY"},{"id":1058,"address":"BidCoS-RF:12","name":"HM-RCV-50 BidCoS-RF:12","type":"VIRTUAL_KEY"},{"id":1062,"address":"BidCoS-RF:13","name":"HM-RCV-50 BidCoS-RF:13","type":"VIRTUAL_KEY"},{"id":1066,"address":"BidCoS-RF:14","name":"HM-RCV-50 BidCoS-RF:14","type":"VIRTUAL_KEY"},{"id":1070,"address":"BidCoS-RF:15","name":"HM-RCV-50 BidCoS-RF:15","type":"VIRTUAL_KEY"},{"id":1074,"address":"BidCoS-RF:16","name":"HM-RCV-50 BidCoS-RF:16","type":"VIRTUAL_KEY"},{"id":1078,"address":"BidCoS-RF:17","name":"HM-RCV-50 BidCoS-RF:17","type":"VIRTUAL_KEY"},{"id":1082,"address":"BidCoS-RF:18","name":"HM-RCV-50 BidCoS-RF:18","type":"VIRTUAL_KEY"},{"id":1086,"address":"BidCoS-RF:19","name":"HM-RCV-50 BidCoS-RF:19","type":"VIRTUAL_KEY"},{"id":1090,"address":"BidCoS-RF:20","name":"HM-RCV-50 BidCoS-RF:20","type":"VIRTUAL_KEY"},{"id":1094,"address":"BidCoS-RF:21","name":"HM-RCV-50 BidCoS-RF:21","type":"VIRTUAL_KEY"},{"id":1098,"address":"BidCoS-RF:22","name":"HM-RCV-50 BidCoS-RF:22","type":"VIRTUAL_KEY"},{"id":1102,"address":"BidCoS-RF:23","name":"HM-RCV-50 BidCoS-RF:23","type":"VIRTUAL_KEY"},{"id":1106,"address":"BidCoS-RF:24","name":"HM-RCV-50 BidCoS-RF:24","type":"VIRTUAL_KEY"},{"id":1110,"address":"BidCoS-RF:25","name":"HM-RCV-50 BidCoS-RF:25","type":"VIRTUAL_KEY"},{"id":1114,"address":"BidCoS-RF:26","name":"HM-RCV-50 BidCoS-RF:26","type":"VIRTUAL_KEY"},{"id":1118,"address":"BidCoS-RF:27","name":"HM-RCV-50 BidCoS-RF:27","type":"VIRTUAL_KEY"},{"id":1122,"address":"BidCoS-RF:28","name":"HM-RCV-50 BidCoS-RF:28","type":"VIRTUAL_KEY"},{"id":1126,"address":"BidCoS-RF:29","name":"HM-RCV-50 BidCoS-RF:29","type":"VIRTUAL_KEY"},{"id":1130,"address":"BidCoS-RF:30","name":"HM-RCV-50 BidCoS-RF:30","type":"VIRTUAL_KEY"},{"id":1134,"address":"BidCoS-RF:31","name":"HM-RCV-50 BidCoS-RF:31","type":"VIRTUAL_KEY"},{"id":1138,"address":"BidCoS-RF:32","name":"HM-RCV-50 BidCoS-RF:32","type":"VIRTUAL_KEY"},{"id":1142,"address":"BidCoS-RF:33","name":"HM-RCV-50 BidCoS-RF:33","type":"VIRTUAL_KEY"},{"id":1146,"address":"BidCoS-RF:34","name":"HM-RCV-50 BidCoS-RF:34","type":"VIRTUAL_KEY"},{"id":1150,"address":"BidCoS-RF:35","name":"HM-RCV-50 BidCoS-RF:35","type":"VIRTUAL_KEY"},{"id":1154,"address":"BidCoS-RF:36","name":"HM-RCV-50 BidCoS-RF:36","type":"VIRTUAL_KEY"},{"id":1158,"address":"BidCoS-RF:37","name":"HM-RCV-50 BidCoS-RF:37","type":"VIRTUAL_KEY"},{"id":1162,"address":"BidCoS-RF:38","name":"HM-RCV-50 BidCoS-RF:38","type":"VIRTUAL_KEY"},{"id":1166,"address":"BidCoS-RF:39","name":"HM-RCV-50 BidCoS-RF:39","type":"VIRTUAL_KEY"},{"id":1170,"address":"BidCoS-RF:40","name":"HM-RCV-50 BidCoS-RF:40","type":"VIRTUAL_KEY"},{"id":1174,"address":"BidCoS-RF:41","name":"HM-RCV-50 BidCoS-RF:41","type":"VIRTUAL_KEY"},{"id":1178,"address":"BidCoS-RF:42","name":"HM-RCV-50 BidCoS-RF:42","type":"VIRTUAL_KEY"},{"id":1182,"address":"BidCoS-RF:43","name":"HM-RCV-50 BidCoS-RF:43","type":"VIRTUAL_KEY"},{"id":1186,"address":"BidCoS-RF:44","name":"HM-RCV-50 BidCoS-RF:44","type":"VIRTUAL_KEY"},{"id":1190,"address":"BidCoS-RF:45","name":"HM-RCV-50 BidCoS-RF:45","type":"VIRTUAL_KEY"},{"id":1194,"address":"BidCoS-RF:46","name":"HM-RCV-50 BidCoS-RF:46","type":"VIRTUAL_KEY"},{"id":1198,"address":"BidCoS-RF:47","name":"HM-RCV-50 BidCoS-RF:47","type":"VIRTUAL_KEY"},{"id":1202,"address":"BidCoS-RF:48","name":"HM-RCV-50 BidCoS-RF:48","type":"VIRTUAL_KEY"},{"id":1206,"address":"BidCoS-RF:49","name":"HM-RCV-50 BidCoS-RF:49","type":"VIRTUAL_KEY"},{"id":1210,"address":"BidCoS-RF:50","name":"HM-RCV-50 BidCoS-RF:50","type":"VIRTUAL_KEY"}]},{"device":"61A7DA498FA6EF","name":"HmIP-RCV-50 61A7DA498FA6EF","type":"HmIP-RCV-50","channels":[{"id":1239,"address":"61A7DA498FA6EF:1","name":"HmIP-RCV-50 61A7DA498FA6EF:1","type":"KEY_TRANSCEIVER"},{"id":1242,"address":"61A7DA498FA6EF:2","name":"HmIP-RCV-50 61A7DA498FA6EF:2","type":"KEY_TRANSCEIVER"},{"id":1245,"address":"61A7DA498FA6EF:3","name":"HmIP-RCV-50 61A7DA498FA6EF:3","type":"KEY_TRANSCEIVER"},{"id":1248,"address":"61A7DA498FA6EF:4","name":"HmIP-RCV-50 61A7DA498FA6EF:4","type":"KEY_TRANSCEIVER"},{"id":1251,"address":"61A7DA498FA6EF:5","name":"HmIP-RCV-50 61A7DA498FA6EF:5","type":"KEY_TRANSCEIVER"},{"id":1254,"address":"61A7DA498FA6EF:6","name":"HmIP-RCV-50 61A7DA498FA6EF:6","type":"KEY_TRANSCEIVER"},{"id":1257,"address":"61A7DA498FA6EF:7","name":"HmIP-RCV-50 61A7DA498FA6EF:7","type":"KEY_TRANSCEIVER"},{"id":1260,"address":"61A7DA498FA6EF:8","name":"HmIP-RCV-50 61A7DA498FA6EF:8","type":"KEY_TRANSCEIVER"},{"id":1263,"address":"61A7DA498FA6EF:9","name":"HmIP-RCV-50 61A7DA498FA6EF:9","type":"KEY_TRANSCEIVER"},{"id":1266,"address":"61A7DA498FA6EF:10","name":"HmIP-RCV-50 61A7DA498FA6EF:10","type":"KEY_TRANSCEIVER"},{"id":1269,"address":"61A7DA498FA6EF:11","name":"HmIP-RCV-50 61A7DA498FA6EF:11","type":"KEY_TRANSCEIVER"},{"id":1272,"address":"61A7DA498FA6EF:12","name":"HmIP-RCV-50 61A7DA498FA6EF:12","type":"KEY_TRANSCEIVER"},{"id":1275,"address":"61A7DA498FA6EF:13","name":"HmIP-RCV-50 61A7DA498FA6EF:13","type":"KEY_TRANSCEIVER"},{"id":1278,"address":"61A7DA498FA6EF:14","name":"HmIP-RCV-50 61A7DA498FA6EF:14","type":"KEY_TRANSCEIVER"},{"id":1281,"address":"61A7DA498FA6EF:15","name":"HmIP-RCV-50 61A7DA498FA6EF:15","type":"KEY_TRANSCEIVER"},{"id":1284,"address":"61A7DA498FA6EF:16","name":"HmIP-RCV-50 61A7DA498FA6EF:16","type":"KEY_TRANSCEIVER"},{"id":1287,"address":"61A7DA498FA6EF:17","name":"HmIP-RCV-50 61A7DA498FA6EF:17","type":"KEY_TRANSCEIVER"},{"id":1290,"address":"61A7DA498FA6EF:18","name":"HmIP-RCV-50 61A7DA498FA6EF:18","type":"KEY_TRANSCEIVER"},{"id":1293,"address":"61A7DA498FA6EF:19","name":"HmIP-RCV-50 61A7DA498FA6EF:19","type":"KEY_TRANSCEIVER"},{"id":1296,"address":"61A7DA498FA6EF:20","name":"HmIP-RCV-50 61A7DA498FA6EF:20","type":"KEY_TRANSCEIVER"},{"id":1299,"address":"61A7DA498FA6EF:21","name":"HmIP-RCV-50 61A7DA498FA6EF:21","type":"KEY_TRANSCEIVER"},{"id":1302,"address":"61A7DA498FA6EF:22","name":"HmIP-RCV-50 61A7DA498FA6EF:22","type":"KEY_TRANSCEIVER"},{"id":1305,"address":"61A7DA498FA6EF:23","name":"HmIP-RCV-50 61A7DA498FA6EF:23","type":"KEY_TRANSCEIVER"},{"id":1308,"address":"61A7DA498FA6EF:24","name":"HmIP-RCV-50 61A7DA498FA6EF:24","type":"KEY_TRANSCEIVER"},{"id":1311,"address":"61A7DA498FA6EF:25","name":"HmIP-RCV-50 61A7DA498FA6EF:25","type":"KEY_TRANSCEIVER"},{"id":1314,"address":"61A7DA498FA6EF:26","name":"HmIP-RCV-50 61A7DA498FA6EF:26","type":"KEY_TRANSCEIVER"},{"id":1317,"address":"61A7DA498FA6EF:27","name":"HmIP-RCV-50 61A7DA498FA6EF:27","type":"KEY_TRANSCEIVER"},{"id":1320,"address":"61A7DA498FA6EF:28","name":"HmIP-RCV-50 61A7DA498FA6EF:28","type":"KEY_TRANSCEIVER"},{"id":1323,"address":"61A7DA498FA6EF:29","name":"HmIP-RCV-50 61A7DA498FA6EF:29","type":"KEY_TRANSCEIVER"},{"id":1326,"address":"61A7DA498FA6EF:30","name":"HmIP-RCV-50 61A7DA498FA6EF:30","type":"KEY_TRANSCEIVER"},{"id":1329,"address":"61A7DA498FA6EF:31","name":"HmIP-RCV-50 61A7DA498FA6EF:31","type":"KEY_TRANSCEIVER"},{"id":1332,"address":"61A7DA498FA6EF:32","name":"HmIP-RCV-50 61A7DA498FA6EF:32","type":"KEY_TRANSCEIVER"},{"id":1335,"address":"61A7DA498FA6EF:33","name":"HmIP-RCV-50 61A7DA498FA6EF:33","type":"KEY_TRANSCEIVER"},{"id":1338,"address":"61A7DA498FA6EF:34","name":"HmIP-RCV-50 61A7DA498FA6EF:34","type":"KEY_TRANSCEIVER"},{"id":1341,"address":"61A7DA498FA6EF:35","name":"HmIP-RCV-50 61A7DA498FA6EF:35","type":"KEY_TRANSCEIVER"},{"id":1344,"address":"61A7DA498FA6EF:36","name":"HmIP-RCV-50 61A7DA498FA6EF:36","type":"KEY_TRANSCEIVER"},{"id":1347,"address":"61A7DA498FA6EF:37","name":"HmIP-RCV-50 61A7DA498FA6EF:37","type":"KEY_TRANSCEIVER"},{"id":1350,"address":"61A7DA498FA6EF:38","name":"HmIP-RCV-50 61A7DA498FA6EF:38","type":"KEY_TRANSCEIVER"},{"id":1353,"address":"61A7DA498FA6EF:39","name":"HmIP-RCV-50 61A7DA498FA6EF:39","type":"KEY_TRANSCEIVER"},{"id":1356,"address":"61A7DA498FA6EF:40","name":"HmIP-RCV-50 61A7DA498FA6EF:40","type":"KEY_TRANSCEIVER"},{"id":1359,"address":"61A7DA498FA6EF:41","name":"HmIP-RCV-50 61A7DA498FA6EF:41","type":"KEY_TRANSCEIVER"},{"id":1362,"address":"61A7DA498FA6EF:42","name":"HmIP-RCV-50 61A7DA498FA6EF:42","type":"KEY_TRANSCEIVER"},{"id":1365,"address":"61A7DA498FA6EF:43","name":"HmIP-RCV-50 61A7DA498FA6EF:43","type":"KEY_TRANSCEIVER"},{"id":1368,"address":"61A7DA498FA6EF:44","name":"HmIP-RCV-50 61A7DA498FA6EF:44","type":"KEY_TRANSCEIVER"},{"id":1371,"address":"61A7DA498FA6EF:45","name":"HmIP-RCV-50 61A7DA498FA6EF:45","type":"KEY_TRANSCEIVER"},{"id":1374,"address":"61A7DA498FA6EF:46","name":"HmIP-RCV-50 61A7DA498FA6EF:46","type":"KEY_TRANSCEIVER"},{"id":1377,"address":"61A7DA498FA6EF:47","name":"HmIP-RCV-50 61A7DA498FA6EF:47","type":"KEY_TRANSCEIVER"},{"id":1380,"address":"61A7DA498FA6EF:48","name":"HmIP-RCV-50 61A7DA498FA6EF:48","type":"KEY_TRANSCEIVER"},{"id":1383,"address":"61A7DA498FA6EF:49","name":"HmIP-RCV-50 61A7DA498FA6EF:49","type":"KEY_TRANSCEIVER"},{"id":1386,"address":"61A7DA498FA6EF:50","name":"HmIP-RCV-50 61A7DA498FA6EF:50","type":"KEY_TRANSCEIVER"}]},{"device":"000A5A49A24F39","name":"Rauchmelder Eltern","type":"HmIP-SWSD","channels":[{"id":1511,"address":"000A5A49A24F39:1","name":"Rauchmelder Eltern","type":"SMOKE_DETECTOR"}]},{"device":"000A5A49A24E36","name":"Rauchmelder Loris","type":"HmIP-SWSD","channels":[{"id":1569,"address":"000A5A49A24E36:1","name":"Rauchmelder Loris","type":"SMOKE_DETECTOR"}]},{"device":"000A5A49A05CE0","name":"Rauchmelder OG","type":"HmIP-SWSD","channels":[{"id":1598,"address":"000A5A49A05CE0:1","name":"Rauchmelder OG","type":"SMOKE_DETECTOR"}]},{"device":"000A5A49A24E44","name":"Rauchmelder Sina","type":"HmIP-SWSD","channels":[{"id":1540,"address":"000A5A49A24E44:1","name":"Rauchmelder Sina","type":"SMOKE_DETECTOR"}]},{"device":"000A5A49A05411","name":"Rauchmelder Stube","type":"HmIP-SWSD","channels":[{"id":1482,"address":"000A5A49A05411:1","name":"Rauchmelder Stube","type":"SMOKE_DETECTOR"}]}]}


API Request {"method":"system"} 

Result {"cpu":[{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":13130600,"nice":1800,"sys":13650900,"idle":808698800,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":14982400,"nice":1100,"sys":13245400,"idle":823551200,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":14082700,"nice":3500,"sys":12907800,"idle":824809700,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":13504700,"nice":300,"sys":12623800,"idle":825874300,"irq":0}}],"mem":33751040,"uptime":85694,"hapuptime":85279.24,"version":"0.0.21","update":"0.0.21","debug":"false"}
network.js:10 API Request {"method":"system"} 

Result {"cpu":[{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":13135700,"nice":1800,"sys":13654700,"idle":808984800,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":14987200,"nice":1100,"sys":13250400,"idle":823841400,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":14089600,"nice":3500,"sys":12912700,"idle":825099600,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":13508800,"nice":300,"sys":12627500,"idle":826166400,"irq":0}}],"mem":43876352,"uptime":85725,"hapuptime":85309.487,"version":"0.0.21","update":"0.0.21","debug":"false"}
network.js:10 API Request {"method":"system"} 

Result {"cpu":[{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":13139100,"nice":1800,"sys":13659500,"idle":809278800,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":14993800,"nice":1100,"sys":13255200,"idle":824138200,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":14095200,"nice":3500,"sys":12917800,"idle":825397200,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":13512200,"nice":300,"sys":12631100,"idle":826467900,"irq":0}}],"mem":43868160,"uptime":85756,"hapuptime":85340.514,"version":"0.0.21","update":"0.0.21","debug":"false"}
network.js:10 API Request {"method":"system"} 

Result {"cpu":[{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":13143500,"nice":1800,"sys":13666000,"idle":809572100,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":15000100,"nice":1100,"sys":13261600,"idle":824436700,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":14100800,"nice":3500,"sys":12923100,"idle":825696600,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":13517400,"nice":300,"sys":12636800,"idle":826767800,"irq":0}}],"mem":44642304,"uptime":85787,"hapuptime":85371.763,"version":"0.0.21","update":"0.0.21","debug":"false“}

API Request {"method":"system"} 

Result {"cpu":[{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":13143500,"nice":1800,"sys":13666000,"idle":809572100,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":15000100,"nice":1100,"sys":13261600,"idle":824436700,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":14100800,"nice":3500,"sys":12923100,"idle":825696600,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":13517400,"nice":300,"sys":12636800,"idle":826767800,"irq":0}}],"mem":44642304,"uptime":85787,"hapuptime":85371.763,"version":"0.0.21","update":"0.0.21","debug":"false"}
j

query.min.js:3049 POST http://192.168.1.44:9874/api/ net::ERR_EMPTY_RESPONSE
send @ jquery.min.js:3049
ajax @ jquery.min.js:2944
(anonymous) @ network.js:4
makeApiRequest @ network.js:3
buildDeviceSettings @ wizzards.js:211
buildNewDeviceStep2 @ wizzards.js:373
(anonymous) @ wizzards.js:430
(anonymous) @ ui.js:55
dispatch @ jquery.min.js:1627
q.handle @ jquery.min.js:1589
wizzards.js:376 Uncaught (in promise) {readyState: 0, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
buildNewDeviceStep2 @ wizzards.js:376
async function (async)
buildNewDeviceStep2 @ wizzards.js:373
(anonymous) @ wizzards.js:430
(anonymous) @ ui.js:55
dispatch @ jquery.min.js:1627
q.handle @ jquery.min.js:1589
5XHR failed loading: POST "<URL>".
jquery.min.js:3049 POST http://192.168.1.44:9874/api/ net::ERR_EMPTY_RESPONSE
send @ jquery.min.js:3049
ajax @ jquery.min.js:2944
(anonymous) @ network.js:4
makeApiRequest @ network.js:3
buildDeviceSettings @ wizzards.js:211
buildNewDeviceStep2 @ wizzards.js:373
(anonymous) @ wizzards.js:430
(anonymous) @ ui.js:55
dispatch @ jquery.min.js:1627
q.handle @ jquery.min.js:1589
wizzards.js:376 Uncaught (in promise) {readyState: 0, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
buildNewDeviceStep2 @ wizzards.js:376
async function (async)
buildNewDeviceStep2 @ wizzards.js:373
(anonymous) @ wizzards.js:430
(anonymous) @ ui.js:55
dispatch @ jquery.min.js:1627
q.handle @ jquery.min.js:1589
jquery.min.js:3049 POST http://192.168.1.44:9874/api/ net::ERR_EMPTY_RESPONSE
send @ jquery.min.js:3049
ajax @ jquery.min.js:2944
(anonymous) @ network.js:4
makeApiRequest @ network.js:3
buildDeviceSettings @ wizzards.js:211
buildNewDeviceStep2 @ wizzards.js:373
(anonymous) @ wizzards.js:430
(anonymous) @ ui.js:55
dispatch @ jquery.min.js:1627
q.handle @ jquery.min.js:1589
wizzards.js:376 Uncaught (in promise) {readyState: 0, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
buildNewDeviceStep2 @ wizzards.js:376
async function (async)
buildNewDeviceStep2 @ wizzards.js:373
(anonymous) @ wizzards.js:430
(anonymous) @ ui.js:55
dispatch @ jquery.min.js:1627
q.handle @ jquery.min.js:1589
jquery.min.js:3049 POST http://192.168.1.44:9874/api/ net::ERR_EMPTY_RESPONSE
send @ jquery.min.js:3049
ajax @ jquery.min.js:2944
(anonymous) @ network.js:4
makeApiRequest @ network.js:3
buildDeviceSettings @ wizzards.js:211
buildNewDeviceStep2 @ wizzards.js:373
(anonymous) @ wizzards.js:430
(anonymous) @ ui.js:55
dispatch @ jquery.min.js:1627
q.handle @ jquery.min.js:1589
wizzards.js:376 Uncaught (in promise) {readyState: 0, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
buildNewDeviceStep2 @ wizzards.js:376
async function (async)
buildNewDeviceStep2 @ wizzards.js:373
(anonymous) @ wizzards.js:430
(anonymous) @ ui.js:55
dispatch @ jquery.min.js:1627
q.handle @ jquery.min.js:1589
jquery.min.js:3049 POST http://192.168.1.44:9874/api/ net::ERR_EMPTY_RESPONSE
send @ jquery.min.js:3049
ajax @ jquery.min.js:2944
(anonymous) @ network.js:4
makeApiRequest @ network.js:3
buildDeviceSettings @ wizzards.js:211
buildNewDeviceStep2 @ wizzards.js:373
(anonymous) @ wizzards.js:430
(anonymous) @ ui.js:55
dispatch @ jquery.min.js:1627
q.handle @ jquery.min.js:1589
wizzards.js:376 Uncaught (in promise) {readyState: 0, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
buildNewDeviceStep2 @ wizzards.js:376
async function (async)
buildNewDeviceStep2 @ wizzards.js:373
(anonymous) @ wizzards.js:430
(anonymous) @ ui.js:55
dispatch @ jquery.min.js:1627
q.handle @ jquery.min.js:1589
network.js:10 API Request {"method":"system"} 

Result {"cpu":[{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":13147300,"nice":1800,"sys":13671000,"idle":809859300,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":15008900,"nice":1100,"sys":13267500,"idle":824725300,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":14106900,"nice":3500,"sys":12927900,"idle":825988200,"irq":0}},{"model":"ARMv7 Processor rev 4 (v7l)","speed":1400,"times":{"user":13525100,"nice":300,"sys":12640400,"idle":827058600,"irq":0}}],"mem":44503040,"uptime":85817,"hapuptime":85402.213,"version":"0.0.21","update":"0.0.21","debug":"false"}

**Comment by thkl** [comment]
OK schaut so aus, als ob bei der Abfrage der möglichen Services vom neuen Rauchmelder keine richtige Antwort vom Plugin kommt. Daher mal bitte ins Serverlog schauen, ob da irgenwelche Fehler geworfen werden .. bzw welcher Rauchmelder ist schon da und welcher sollte hinzugefügt werden ?

**Comment by Milo-PRT** [comment]
Guten Morgen Thomas

Hier das Log der CCU.

Es hätten alle Rauchmelder eingebunden werden sollen, welche alle schon vorhanden waren. Es wurden keine neu angelernt.

Beste Grüsse

Beat

**Comment by Milo-PRT** [comment]
[messages.txt](https://github.com/thkl/hap-homematic/files/4485362/messages.txt)

**Comment by thkl** [comment]
hmm das ist das CCU Log. Das bringt nix. Bitte mal auf 0.0.22 updaten. Dort hat das WebUI jetzt auch mehr Consolen Logging bekommen. Dann noch mal versuchen die Rauchmelder hinzuzufügen.
Und wenn das nicht geht brauch ich mal das Console Log . Aber nur die User Messages ...
![Bildschirmfoto 2020-04-16 um 20 16 19](https://user-images.githubusercontent.com/884355/79491741-33d28e80-801f-11ea-8e57-f8de962690c3.png)


Und wenns geht hier als Textfile damit das nicht so viel wird ;)

**Comment by Milo-PRT** [comment]
Guten Morgen

Das Update hat leider nicht den gewünschten Effekt gebracht.

Hier nun das Log:

Beste Grüsse

Beat

**Comment by Milo-PRT** [comment]
[HAP-LOG.log](https://github.com/thkl/hap-homematic/files/4490954/HAP-LOG.log)

**Comment by Milo-PRT** [comment]
...zudem ist mir aufgefallen, dass die HomeMatic_default-Instanz im Homekit nicht erscheint und auch keine Geräte angezeigt werden.... (habe mal einen virtuellen Schalter in diese Instanz eingebunden)

**Comment by thkl** [comment]
Die default Instanz ist eigentlich nur Deko die wird nicht automatisch mit Geräten ausgerollt damit die Geräte erscheinen muss in den Veröffentlichungseinstellungen das Häkchen bei default gemacht werden. 

Diese Instanz dient als Auffang für Geräte die irgend wo hin müssen wenn man eine Rauminstanz löscht. 

Ich merke ne Doku ist wichtig und fehlt 🙀... Rest schau ich mir an ob ich da was rausfinde

**Comment by thkl** [comment]
Ok soweit ich das aus dem Log lese bekommt die WebUI keine Antwort auf die Abfrage welche Services für den Smoke_Detector Kanal verfügbar sind.  Ich werde mal einen Simulator mit hinzufügen, dann kann ich das mit Deinen Daten ausprobieren und schauen wo das Problem liegt.

**Comment by Milo-PRT** [comment]
Perfekt

Gruss

**Comment by thkl** [comment]
so ... 0.0.23 sollte das Problem lösen. Ich hatte einen Bug im Configuration Server.

**Comment by Milo-PRT** [comment]
Perfekt - mit 0.0.23 sind alle Rauchmelder in HomeKit einbandbar und erscheinen auch. Danke für diesen Support!!

**Comment by thkl** [comment]
Prima ;)
