### ISSUE TITLE
HmIP-ASIR-2 als Schalter?

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#50]
Die Alarmsirene (HmIP-ASIR-2) wird als Schalter hinzugefügt. Ergibt nicht wirklich Sinn, zumal nichts passiert wenn man den Schalter betätigt.
[HmIP-ASIR-2.json.txt](https://github.com/thkl/hap-homematic/files/4577300/HmIP-ASIR-2.json.txt)

**Comment by thkl** [comment]
Oh ok, also aus der Doku zu dem Ding werde ich nicht richtig schlau. Was kann man denn im WebUI der CCU da betätigen. Bzw in welchem Channel, das schaut aus, als können dan mehrere Zonen ausgelöst werden ...

**Comment by detLAN** [comment]
Der Schalter ist nicht wirklich spannend, da öffnet sich ein Dialog mittels welchem man die Sirene testen kann - z.B. um heraus zu finden welchen akustischen Alarm man nutzen möchte.
<img width="712" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81070933-420c2000-8ee4-11ea-8d3e-a80d5fac1990.png">

**Comment by thkl** [comment]
Ja ok, aber was soll denn jetzt nach HomeKit ?

**Comment by roe1974** [comment]
Bedienung ist verdeckt ... was ist da dahinter ? EIN/AUS ?

**Comment by detLAN** [comment]
Ich denke es ist ausreichend, wenn das Teil nur signalisiert ob gerade einen Alarm ausgegeben wird oder eben nicht. Ansonsten finde ich das Teil eh nicht spannend. Nur da es integriert ist, sollte dann aktuell etwas mit dem Schalter passieren, oder aber dieser weggelassen werden.
<img width="712" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81071821-851ac300-8ee5-11ea-92a0-7aabe8f0fa29.png">

**Comment by thkl** [comment]
Naja die Integration kommt "von hinten" durch den Channeltyp KEY_TRANSCEIVER .. dieser hat normal PRESS_LONG und PRESS_SHORT .. aus irgend einem Grund hat HmIP-ASIR auch einen KEY_TRANSCEIVER Channel aber mit völlig anderen Datenpunkten.  Ausblenden von Geräten habe ich bisher nicht vorgesehen. Wird aber wohl nötig sein.

**Comment by detLAN** [comment]
So ergibt es wenig Sinn, zumal Schalter, Licht oder Lüfter ist das Teil nun wirklich nicht.
<img width="102" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81072496-826c9d80-8ee6-11ea-9529-8f8f494819e8.png">

**Comment by thkl** [comment]
Ja, hap-homematic erwartet bei KEY_TRANSCEIVER obige beschriebene Datenpunkte und würde daraus einen Switch machen, und beim Betätigen den Kurz Drücken oder Lang Drücken Datenpunkte auslösen.

Ich bau mal einen Filter für solche Sachen rein ... dann wird die Alarmsirene nicht mehr auswählbar sein.

**Comment by roe1974** [comment]
es gibt doch auch "Taster" in HK ... könnte man der Sirene einen Taster zuordnen ? ... um sie dann in HK auslösen zu können ?

**Comment by thkl** [comment]
Nooooin, es geht, soweit ich das verstanden habe, nicht um die Auslösung der Sirene. Sondern um die Tatsache, das sie da ist und als Gerät für Homekit erzeugbar ist. Aber ohne Funktion

**Comment by roe1974** [comment]
ok ... dann habe ich es falsch verstanden ... es geht also um die "richtige" Darstellung in HK ?

**Comment by roe1974** [comment]
der button sieht zumindest so aus......
![grafik](https://user-images.githubusercontent.com/30420568/81073332-c44a1380-8ee7-11ea-8674-2e6c29ce71f7.png)

**Comment by detLAN** [comment]
Genau, ein Gerät was einen Schalter ohne Funktion mitbringt macht keinen Sinn. Würde wie geschrieben das Teil signalisieren können ob die Sirene ausgelöst hat wäre es etwas anderes. Aber einen Taster um Alarmtöne zu testen, ergibt keinen Mehrwert, da man dies i.d.R. einmal macht für die Einstellungen und dann nicht mehr.

**Comment by thkl** [comment]
Deswegen aus der Geräteliste filtern und fertig ...

**Comment by thkl** [comment]
Ne noch nicht zu , ist ja noch nicht gemacht .. ich nehme das hier ja auch als ToDO Liste

**Comment by detLAN** [comment]
Sorry - das mit dem Schließen muss ich noch üben - ist mir jetzt auch klar, dass es Deine Abarbeitungsliste ist.
