### ISSUE TITLE
Variable als Binary Sensor ändert Status nicht

### ISSUE THREAD

**Issue by timwegenerDE** [thkl/hap-homematic#501]
Hallihallo,

ich hätte gerne eine bool Variable (wahr / falsch) als Kontaktsensor eingerichtet. Leider ist dieser - unabhängig vom Wert - immer geöffnet. Trigger / Hilfsprogramm habe ich aktualisiert.

Kann das mal jemand bei dich testen, ob das ein Einzelschicksal ist?

Vielen Dank 😊 
Tim

**Comment by benno666** [comment]
Hey Tim,

ich hatte ein ganz ähnliches Problem: benutzt du vielleicht eine Systemvariable, die Umlaute oder Sonderzeichen enthält?

Gruß,
benno666

**Comment by timwegenerDE** [comment]
Genau das! 😂 Umbenannt, geht… 

Danke dir!

**Comment by ChrWi** [comment]
Meine Systemvariable hat keine Sonderzeichen, aber ich habe auch dieses "Problem". Wobei ich feststelle, dass sich teilweise asynchrones Verhalten ergibt, also false = geöffnet / true = geschlossen. Ich hatte erst einen Bug vermutet, bis ich diesen Beitrag gefunden habe.

**Comment by ChrWi** [comment]
Ergänzung: bei Verwendung von „Occupancy“ wird die boolesche Variable korrekt ausgewertet.

**Comment by ChrWi** [comment]
Denke ich hab‘s - es ist asynchron zu den anderen Typen. Der Blick in den Sourcecode zeigt auch warum (this.reverse = true). Muss das morgen mal ausprobieren.

**Comment by ChrWi** [comment]
Nach dem Ändern auf "this.reverse = false" in Zeile 58 von HomeMaticVariableBinarySensorAccessory.js 
habe ich das gewünschte Verhalten. Ggf. kann @thkl bei Gelegenheit erklären, warum nur dieser subtype das reverse gesetzt hatte.

**Comment by ChrWi** [comment]
Ist geklärt
