### ISSUE TITLE
Doorbell funktioniert nicht

### ISSUE THREAD

**Issue by thomaskoerfer** [thkl/hap-homematic#504]
Hi - ich würde gerne eine Doorbell zum Laufen bringen - jedoch ohne Video. Die Doorbell, die ich in den normalen Geräten auswählen kann wird aber in HomeKit nicht richtig erkannt - und viel wichtiger - erzeugt kein „Klingelereignis“ in HomeKit, welches ich für den HomePod benötigen würde.
Ist es tatsächlich fehlerhaft oder bin ich der Schuldige? 
ich sehe, dass das vor einigen Jahre schonmal Thema war - hoffe aber natürlich, dass es in der Zwischenzeit anders ist :)

**Comment by ChrWi** [comment]
Siehe #617
