### ISSUE TITLE
Ikea Steckdose kann nicht über Homekit geschaltet werden

### ISSUE THREAD

**Issue by s-eckey** [thkl/hap-homematic#509]
**Please describe your problem**
Ikea Steckdose, angelernt über die HUE Bridge.
HUE Bridge ist normal mit der CCU3 gekoppelt (verbundene Ikea-Lampen an HUE Bridge funktionieren auch über HAP Homekit)
Steckdose wird in CCU als VIR-LG-ONOFF HU-On/Off plug:1 gelistet
Steckdose ist über CCU sowie über HUE App steuerbar

**What happends**
Steckdose ist nicht über Homekit steuerbar. Ein- und ausschalten wird in der App dargestellt, aber es funktioniert nichts

**What should be happend**
Steckdose sollte über die Schaltung in Homekit geschaltet werden

**Steps to reproduce this issue**
HUE mit CCU koppeln
Steckdose von Ikea (Version 2.0.024) mit HUE koppeln
Steckdose in HAP nach Homekit deployen
Service: HomeMaticSwitchAccessory
Subtyp: Outlet
Einschaltzeit: 0

Schalten in CCU und HUE App funktionieren
Schalten in Homekit funktionieren nicht.

Debug-Log:

[Mon Dec 06 2021 15:15:23 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticSwitchAccessory] HU-On/Off plug [Switch] set switch false
[Mon Dec 06 2021 15:15:23 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticSwitchAccessory] HU-On/Off plug set value false
[Mon Dec 06 2021 15:15:23 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticSwitchAccessory] HU-On/Off plug buildAddress STATE
[Mon Dec 06 2021 15:15:23 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticSwitchAccessory] HU-On/Off plug seems to be a single datapoint
[Mon Dec 06 2021 15:15:23 GMT+0100 (CET)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject('VirtualDevices.HU-On/Off plug:1.STATE');if (o){o.State(0);}
[Mon Dec 06 2021 15:15:23 GMT+0100 (CET)] debug - [HAP Server] [Rega] result is 
[Mon Dec 06 2021 15:16:06 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticSwitchAccessory] HU-On/Off plug [Switch] set switch true
[Mon Dec 06 2021 15:16:06 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticSwitchAccessory] HU-On/Off plug set value true
[Mon Dec 06 2021 15:16:06 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticSwitchAccessory] HU-On/Off plug buildAddress STATE
[Mon Dec 06 2021 15:16:06 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticSwitchAccessory] HU-On/Off plug seems to be a single datapoint
[Mon Dec 06 2021 15:16:06 GMT+0100 (CET)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject('VirtualDevices.HU-On/Off plug:1.STATE');if (o){o.State(1);}
[Mon Dec 06 2021 15:16:06 GMT+0100 (CET)] debug - [HAP Server] [Rega] result is

**Comment by IST24** [comment]
Hallo, dass kann ich bestätigen, sogar etwas schlimmer: wenn ich IKEA dimmbare GU10 über HUE Bridge in HomeKit einbinde, dann raucht AddOn ab und sieht keine Geräte mehr, als ob AddIn ausgesperrt wird.

MIt dem AddOn funktioniert aber alles in HomeKit AddOn, leider ist von Entwickler abgekündigt
https://github.com/j-a-n/homematic-addon-hue

Danke

**Comment by ChrWi** [comment]
Analog #536
