### ISSUE TITLE
Aktuelle HAP-NodeJS Version

### ISSUE THREAD

**Issue by JensBonse** [thkl/hap-homematic#51]
Hallo Thomas,

laut deinem package.json verwendest du fix HAP-NodeJS 0.5.7.
Seit HAP-NodeJS 0.5.6 braucht HAP-NodeJS selber Node >=10.17.0
Somit sollte die Standard CCU3 mit Node 8 nicht funktional sein. Solltest also auch auf Node 10 wechseln können.
Wäre es dann möglich, HAP-NodeJS auf die neuste Version (aktuell 0.7.0) zu heben? Da wurde einiges an der Performance geschraubt.

**Comment by thkl** [comment]
Ja, aber der Teil von HapNodeJs der Node10 braucht wird von mir nicht angesprochen. 

Ich schau mal ob ich auf die aktuelle Version Updater kann. Nach dem Drama mit Homebridge 1.0 bin ich mit Versionssprüngen bei depending Modulen vorsichtig :)

**Comment by roe1974** [comment]
wüsste nicht was da noch performanter gehen sollte ... die geräte in HK reagieren so schnell wie. ich nie ! ;-)

**Comment by JensBonse** [comment]
Performance Verbesserungen siehe hier unter Improvements von Version 0.7.0:
https://github.com/homebridge/HAP-NodeJS/releases

**Comment by thkl** [comment]
Wie gesagt, ich würde ungern die CCU3 und passende Virtualisierungen abhängen.

**Comment by thkl** [comment]
Ich habe mal auf einer Testinstallation (piVCCU3) hap-nodejs auf 0.7 gehoben:

```
/etc/config/rc.d/hap-homematic stop
cd /usr/local/addons/hap-homematic
npm i --cache /tmp/hap-homematic-cache hap-nodejs@latest
/etc/config/rc.d/hap-homematic start
```
Dort läuft NodeJS auf 8.11.4

Das lief durch .. scheint auch zu funktionieren. Aber ich habe keine Geräte da dran, das ich das testen könnte.

Wenn jemand mutig genug ist ;)

**Comment by roe1974** [comment]
was wäre der vorteil ... rennt ja schon perfekt !!!

**Comment by thkl** [comment]
ich sehe derzeit noch keinen ... außer das man halt nicht auf alten Versionen festhängt ...

**Comment by roe1974** [comment]
wenn ich das teste ... komme ich wieder zurück ?
PS: npm gibt es auch schon 6.14.5 :-P

**Comment by thkl** [comment]
`npm i --cache /tmp/hap-homematic-cache hap-nodejs@0.5.7`

geht wieder zurück auf eine "alte" Version

**Comment by roe1974** [comment]
ok ..... mal sehen ob ich mich traue in meiner produktiv umgebung :-)

**Comment by JensBonse** [comment]
Bei mir läuft die 0.7.2 HAP-nodejs bisher problemlos mit einer RM.

**Comment by thkl** [comment]
ich hab mal testweise auf 0.7.3 aktualisiert (npm ci) und laufe in dieses Problem:

```
Error: Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20)
    at new Cipheriv (internal/crypto/cipher.js:217:22)
    at Object.createCipheriv (crypto.js:109:10)
    at Object.chacha20_poly1305_encryptAndSeal (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/util/hapCrypto.js:79:35)
    at HAPServer._this._handlePairVerifyStepOne (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/HAPServer.js:486:39)
    at HAPServer._this._handlePairVerify (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/HAPServer.js:450:23)
    at IncomingMessage.<anonymous> (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/HAPServer.js:227:39)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1125:12)
```

**Comment by roe1974** [comment]
welche RM version ? (node version) ? 😜😜

**Comment by thkl** [comment]
v10.15.3 auf RM 3.47.15.20190831 der Herr ;)

**Comment by roe1974** [comment]
Node 12.16.1 auf der aktuellen RM :)

**Comment by thkl** [comment]
Kein Grund zum Updaten, die schöne Uptime ...
