### ISSUE TITLE
Schalter für eine Variable der drei Zustände anzeigen kann

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#510]
Hallo,

Ich habe in der CCU einen virtuellen Taster angelegt. Dieser springt immer in den Ausgangszustand zurück.Eigentlich ja auch logisch, weil es ein Taster ist und kein Schalter.

Kann mir jemand sagen, wie ich es hinbekomme, dass der Schalter eingeschaltet bleibt?
Vielen Dank.

https://user-images.githubusercontent.com/72799068/145013281-2b541685-c071-4e97-8e50-e49510cbcf55.MP4

**Comment by gerd2005** [comment]
Ha :-) Ich habe es heraus gefunden. Mann muss eine Systemvariable in der CCU angelegt werden. Diese muss dann im PlugIn unter „Variablen“ als „VariableAccessory“ angelegt werden.

**Comment by gerd2005** [comment]
Gibt es einen Schalter für eine Variable der drei Zustände anzeigen kann?

**Comment by ChrWi** [comment]
Du meinst eine Variable mit Werteliste? Was ist das Ziel? Drei Zustände steuern: könnte über PushTheButton funktionieren (short, long, double click). Drei Zustände anzeigen: fällt mir keine Möglichkeit ein.

**Comment by gerd2005** [comment]
Genau, ich habe eine Werteliste mit drei Werten:
![F7FF8356-33C8-44E2-8888-10B523A1E78F](https://user-images.githubusercontent.com/72799068/145635256-b96fc4eb-6448-43a8-a16d-aa88fe7e9096.jpeg)

Diese Werte möchte ich in der Home App mit einem Schalter verändern können.

**Comment by ChrWi** [comment]
Ich kenne dafür keine Lösung innerhalb der Home App, sondern nur eine über ein Hardware-Schalter, der dann für Kurzklick/Langklick/Doppelklick jeweils einen Variablenwert setzt

**Comment by timwegenerDE** [comment]
Die Alarmanlage kann das doch oder? Wenn ich das oben richtig lese geht es eh in die Richtung An- / Abwesenheit. Hat halt nur den Nachteil, dass es für Homekit ein sicherheitsrelevantes Gerät ist und beim „scharf schalten“ eine Bestätigung will.
