### ISSUE TITLE
HmIP-WTH-2 can only be configured as Thermostat assessory OR Thermometer/Humidity but NOT together

### ISSUE THREAD

**Issue by ajscheid** [thkl/hap-homematic#512]
See subject;
I have just configured a WTH-2 an pass it on to home via HAP-homeatic to the home app.
I can either set it up as HomeMaticRadioatorThermostatAccessory OR as HomeMaticThermometerAccessory (or HumidityAccessory) but I can't manage to get humidity displayed in home app without loosing possibility to control the thermostat.
I have set the WTH-2 up as master which controls the HmIP-eTRV-2. With this setup I would need the possibility to pass on the hunmidity to home app for display purposes only.

Here a screenshot:
![Capture](https://user-images.githubusercontent.com/94199452/146459924-1427b0f1-d01d-4355-bffd-aca4220869aa.JPG)

Would it be possible to include the humidityAccessory data to the ThemorstatAccessory so the humidity gets displayed in home app and control of the thermostat is possible at the same time?

**Comment by Matzushub** [comment]
Usually you would create a Heating Group and connect the Control Channel of that group via HAP to HomeKit. See if that works.

Regardless of that, you can add multiple channels via HAP as devices to HomeKit. That is what so am doing with my HP thermostat. I guess IP devices also have a channel for controlling and one channel for climate data?

**Comment by ajscheid** [comment]
Hi,

Yes, IP devices have got separate channels as can be seen in the screenshot. But I can't create another instance and add the same device selecting the other channel.
When I try the IP device is greyed out and says "already used".
![image](https://user-images.githubusercontent.com/94199452/146982137-99762acf-4e19-44bb-ac55-26eb2a5e52da.jpeg)

**Comment by ajscheid** [comment]
To add some information; the eTRV-2 and WTH-2 have direct device connection. eTRV-2 is therefore controlled by WTH-2.
When I look through the channels of WTH-2 I can't see a separate channel for condition humidity.
Possibly that is the reason I can't add another channel.

**Comment by Matzushub** [comment]
You don’t have to use a different instance. You want to add multiple devices to one instance like: instance = physical room.

Which channels does your HMIP-WTH-2 offer?
In the Screenshot you provided I see only one.

did you create a heating group or created a separate direct device connection. A heating group would appear as a separate device and you should then use it for controlling the whole group.

**Comment by ajscheid** [comment]
Thanks for coming back; clearly I need to put more brain into this.
WTH-2 has the following channels:
![image](https://user-images.githubusercontent.com/94199452/146984039-28c15dc0-374d-41e5-a6ce-19c0bcfcacde.jpeg)

WTH-2 and heating thermostat are connected via direct device connection:
![image](https://user-images.githubusercontent.com/94199452/146984145-ede70400-de2b-463c-9b51-42cd79016df9.jpeg)

As per Homematic manual 3 direct device connections need to be created to have full control from WTH-2

So you say if I create a heating group with the 2 devices I should be able to overcome this issue without loosing ability to control from WTH-2?

**Comment by Matzushub** [comment]
Try my approach and delete all manual direct connections. Create a heating group and add the devices there. Then try to add the heating group to hap as the channel to control all the other devices. Humidity may already work as a sub-data in the device. If not add the wall thermostat only for the purpose of transmitting the humidity.

**Comment by ajscheid** [comment]
I now have created heating groups and was able to configure so humidity is also isolated in home app.
Thank you for pointing me in the right direction!
I will close this one.

**Comment by Matzushub** [comment]
Before you close it. Check if your group also has the humidity as an additional data point and check if it is correct. In case it is you can get rid of the wall thermostat as an additional device.
