### ISSUE TITLE
Add Support for HmIP-DLS

### ISSUE THREAD

**Issue by Niwa1980** [thkl/hap-homematic#515]
[HmIP-DLS.zip](https://github.com/thkl/hap-homematic/files/7775823/HmIP-DLS.zip)

**Comment by ChrWi** [comment]
Daran hätte ich auch Interesse!

**Comment by tornenen** [comment]
Wäre auch in meinem interesse.
Wird das Plugin noch weiterentwickelt?

**Comment by ChrWi** [comment]
Same as #629. I keep the newer one.
