### ISSUE TITLE
hap-homematic in Docker

### ISSUE THREAD

**Issue by timwegenerDE** [thkl/hap-homematic#516]
Hallo zusammen,

ich habe meine Raspberrymatic jetzt in einem Docker-Container laufen:
https://github.com/jens-maus/RaspberryMatic/wiki/Installation-Docker-OCI

Das funktioniert auch mit dem hap-homematic Plugin super, wenn ich das Netzwerk des Containers auf „host“ stelle. 
Im bridged Mode werden die Geräte nicht an Homekit raus gegeben (hier wird wohl der entsprechende Dienst / Port blockiert). Leider kommt sich der Container mit Homebridge und Deconz in die Quere, wenn das Netzwerk auf „host“ steht.

Hat jemand eine lauffähige Konfiguration im Docker Container beim Netzwerk im bridged Mode?

**Comment by timwegenerDE** [comment]
Ich habe jetzt zumindest das Problem im bridged Mode (halbwegs) verstanden. Die Geräte werden via mDNS rausgegeben. Das muss wohl in jedem Fall der Host machen. Die Lösungsansätze sind eher frickelig, wie der hier: https://www.devwithimagination.com/2020/02/02/running-homebridge-on-docker-without-host-network-mode/

**Comment by andreasrueb** [comment]
Ich bin mir nicht ganz sicher ob wir das gleiche Problem haben, aber ich kommentiere mal hier falls jemand auch über dieses Issue stolpert.

Wenn man den Container über die [deploy.sh](https://github.com/jens-maus/RaspberryMatic/wiki/Installation-Docker-OCI#using-deploysh-script) startet werden die nötigen Ports standardmäßig nicht freigegeben. Man kann sich aber ganz leicht Abhilfe schaffen.
Man editiert folgende Zeile in der deploy.sh und fügt die nötigen Ports für das Plugin hinzu (Ich habe es hier mal schon getan):

`
# Other ports to open
: "${CCU_PORTS_TO_OPEN:="2001 2010 8181 9292 9874 9875 9876 9877"}"
`

**Comment by timwegenerDE** [comment]
@andreasrueb Du beschreibst zwar ein anderes Problem, aber aus dem Kontext klingt das so als würde das ja bei dir grundsätzlich laufen.

Heisst das, du hast raspberrymatic im bridged mode inkl. hap-homematic am laufen und deine Home App kommt an die Geräte?

**Comment by timwegenerDE** [comment]
Ich habe jetzt noch versucht über den avahi docker container mDNS vom bridged Netzwerk nach eth0 zu „brücken“:

https://github.com/flungo-docker/avahi#reflect-mdns-broadcasts-between-networks

Danach sehe ich die hap Instanz auch in homekit, kann sie aber nicht hinzufügen. Ich vermute, dass hier der Rückweg bis in den Raspberrymatic Container nicht funktioniert.

Da der Raspberrymatic Container es scheinbar auch nicht gerne hat, im host mode zu laufen, s. hier: https://github.com/jens-maus/RaspberryMatic/issues/1676 gebe ich aber noch nicht ganz auf…

**Comment by timwegenerDE** [comment]
Hostmode in Raspberrymatic wird nicht unterstützt: https://github.com/jens-maus/RaspberryMatic/issues/1676#issuecomment-1146585535

Und im Bridged Mode bekomme ich es nicht hin.

Also Stand jetzt: Am besten nicht auf Docker setzen.
