### ISSUE TITLE
Support für HmIP-SWSD Rauchmelder

### ISSUE THREAD

**Issue by leonardbld** [thkl/hap-homematic#517]
Moin, wäre es mögich den HmIP-SWSD Rauchmelder zu unterstützen ? 
Hätte diesen gerne in HomeKit.
Grüße Leo :D

**Comment by leonardbld** [comment]
Mein Fehler, hat funktioniert

**Comment by bgirr** [comment]
Gibt es denn Rauchmelder als Typ zur Auswahl? Habe ich in keiner Liste gefunden. 
Ich habe die Gira-Rauchmelder via Eingangsmodul und Kabel in Homematic Wired integriert und möchte diese gerne auch in HomeKit sichtbar machen.

**Comment by timwegenerDE** [comment]
Über den Umweg einer Variable geht das.
![51B279CF-5542-4EB5-BB99-EBE32207AC3F](https://user-images.githubusercontent.com/56134910/186241099-65ac1988-66e0-47e4-8309-9edd012e755d.jpeg)

**Comment by bgirr** [comment]
Super, vielen Dank für die schnelle Info - teste ich gleich mal!
