### ISSUE TITLE
HmIPW-DRBL4 Jalousien fahren nach 100% wieder ein Stück herunter

### ISSUE THREAD

**Issue by cmdux** [thkl/hap-homematic#518]
Ich setze HAP-Homematic auf meiner Raspberrymatic CCU (ELV Charly) ein, um meine HmIPW-Jalousienaktoren mit Homekit steuern zu können.

Ich habe alle Jalousien in HAP-Homematic eingebunden und sehe diese auch in Homekit. Öffnen und Schließen funktioniert soweit, allerdings fahren die Jalousien manchmal (nicht immer, aber oft) beim Öffnen wieder ein Stück herunter, nachdem sie eigentlich schon fertig nach oben gefahren sind. In Homekit wird dann z.B. 97% geöffnet angezeigt. In der Home-App kann ich dann die Jalousie mit dem Slider nach oben fahren. Dies muss man manchmal 2-3 Mal wiederholen, bis die Jalousie dann wirklich komplett nach oben gefahren wird. Dann wird sie auch als "offen" in Home angezeigt.

Beim Herunterfahren habe ich manchmal das Phänomen, dass die Jalousie zwar unten ist, die Lamellen aber in der falschen Richtung stehen (wie beim öffnen). 

Ich habe schon verschiedene Sachen ausprobiert, aber ich bekomme es nicht in den Griff. Ich könnte mir vorstellen, dass es etwas mit der Lamellenposition zu tun hat. Ich habe mal irgendwo gelesen, dass beim Befehl immer beide Werte für die Behanghöhe und die Lamellenposition übergeben werden müssen (also beim Öffnen z.B. 100% und 100%). Kann es sein, dass HAP-Homematic dies nicht macht?

Ich wäre sehr dankbar für Tips und Erfahrungswerte.

**Comment by maroony** [comment]
Das Problem habe ich leider auch. Teilweise geht das Rollo wieder ein Stück auf (2 %), nachdem es eigentlich schon ganz zu gewesen ist, teilweise geht das Rollo wieder ein Stück zu (2 %), nachdem es eigentlich schon ganz offen gewesen ist. Ich habe keine Idee woran das liegen könnte.
