### ISSUE TITLE
Program Entfernen

### ISSUE THREAD

**Issue by JensBonse** [thkl/hap-homematic#52]
Hallo Thomas,

ich habe bei Programmen eine kleine Namenskonvention.
Ich habe das Program mit dem Namen 'P: Anwesenheit' mal testweise der default Instanz hingefügt.
Jetzt wollte ich es wieder entfernen, doch es verschwindet nicht. Und in der Spalte 'Name in der CCU' steht nur 'P' ich vermute, dass du da einen Split oder ähnliches auf ':' machst.

**Comment by JensBonse** [comment]
In der JavaScript Konsole sehe ich nichts das Fehlschlägt.
Im Log habe ich beim Überfliegen auch nichts gesehen... Ich schau mal genauer.
Neustart von HAP hat auch nichts gebracht. Auch als ich das Program dann entsprechend umbenannt habe. Holt HAP sich immer den aktuellen Namen des Programs aus der CCU?

**Comment by thkl** [comment]
Oh jeh, genau intern setze ich die Programmnamen auf das CCU Namensschema der Datenpunkte um: Program:Name.0 ;) .. "Program" ist quasi das Interface und das erkennt der Rega Manager wieder  ... das jemand : in den Namen macht, damit hätte ich rechnen sollen ;(

Ich schau mal das ich das : irgendwie beim einlesen Escape ...  Hap holt sich beim Neustart die Sachen neu, aber arbeitet vorher mit einem Cache um den Start zu beschleunigen, daher 2 Neustarts wenn es sofort geändert werden muss.

**Comment by thkl** [comment]
müsste in 0.38 erledigt sein

**Comment by JensBonse** [comment]
Ja, ist erledigt. HM Program Name wurde richtig erkannt. Danach konnte ich es dann wieder löschen.
Danke!

**Comment by JensBonse** [comment]
Wenn ich ein Program nach HomeKit hole, dann bekommt es nur den Namen 'Schalter'.
Ist dann sehr schwer die Programme zu unterscheiden ;)

Das gleich scheint bei Steckdosen mit Messwertekanal zu passieren. Die wurde mir auch nur als Schalter übergeben...

**Comment by thkl** [comment]
Bei den Messsteckdosen muss der Messkanal ausgewählt werden, der holt sich dann den Schalter mit. Wird nur der Schalter ausgewählt, dann ist es nur der Schaltkanal ....

**Comment by JensBonse** [comment]
Hmmm... habe die Programme gelöscht und erneut hinzugefügt. Jetzt sind die mit richtigem Namen rüber gekommen...
Den Messwertekanal hatte ich natürlich ausgewählt... Komisch...
Setzt dur irgendwo als Deafult erst mal den Namen 'Schalter' und überschreibst den dann im Code im dem Namen aus HomeMatic?

**Comment by thkl** [comment]
nein. ich gebe immer den Namen mit der in der Config ausgewählt wurde. Entweder der Channelname, oder der Gerätename (wenn der Channel den default Namen hat) oder halt den Namen den man manuell editiert hat.
