### ISSUE TITLE
Schaltplatine "HmIP-PCBS" 2x in einer Instanz mit 2 verschiedenen Namen hinzufügen

### ISSUE THREAD

**Issue by HookHM** [thkl/hap-homematic#521]
Hallo @thkl ,

wäre es möglich, die Schaltplatine "HmIP-PCBS" beim Hinzufügen einer Instanz so zu konfigurieren das man diese in der selben Instanz mit 2x als Gerät mit Unterschiedlichen Namen anlegt?

Sinn der Sache ist: Ich steuere damit einen Motoren-Türschließer für eine Zimmertüre und es gibt keinen direkt Befehl für z.B. "Türe schließen" oder "Türe öffnen" es ist nur ein Impuls der den Motor zur fahren bringt

Drücken --> Impuls = je nach Position öffnet oder schließt die Türe. Nochmals drücken (während der Fahrt) stoppt die Türe.

Nun würde ich es mit Siri jedoch gerne etwas eleganter haben und sagen können (wenn Türe geschlossen) "Türe öffnen" normaler Imupls wird gegeben und Türe öffnet sich. "Türe schließen" (wenn Türe geöffnet" normaler Imupls wird gegeben und Türe schließt sich.  Ich habe das schon per Szene versucht, klappt aber eher schlecht als recht. 

Ich hoffe Du kannst mir folgen ^^ Also eigentlich muss ich nur die Möglichkeit haben das Gerät beim anlegen in ein und der selben Instanz 2x mit unterschiedlichem HomeKit Gerätenamen "Türe öffnen" und "Türe schließen" anlegen zu können. 

Natürlich nur, wenn das nicht den Aufwand übersteigt.

Danke schon mal.

**Comment by thkl** [comment]
Nein, das geht nicht.  Grund ist:jedes Gerät in HomeKit hat eine uuid. Diese muss pro Instanz eindeutig sein.  Diese uuid leitet sich aus der Adresse des CCU Gerätes ab. Damit würde ein und der selbe Kanal in der gleichen Instanz die gleiche uuid erzeugen. Und das ist in HomeKit nicht möglich. 

Da musst du irgendwie etwas anders drumrum bauen.

**Comment by HookHM** [comment]
Hallo @thkl , ich habe das Gerät einer weiteren Instanz hinzugefügt, dann in der Home App in dem anderen Raum das Gerät umbenannt „Türe öffnen“ und dieses Gerät dann ins Wohnzimmer verschoben, jetzt habe ich das Gerät 2x im Wohnzimmer.
