### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Manuel1607** [thkl/hap-homematic#524]
Hallo ich nutze aktuell die 0.0.14. 
Wenn ich aber hier manches gelesen habe, gibt es schon 0.0.63 ? Wo kann ich die herunter laden? Wenn ich drauf gehe, wird mit immer als aktuelle die 0.0.14 angezeigt, die ab schon von 2020 ist ?

**Comment by JensBonse** [comment]
0.0.14 ist der HomeMatic installer. Der ist Aktuell.
Die 0.0.63 ist die Version von HAP-HomeMatic. Die siehst du wenn du die HAP öffnest. steht oben rechts.

**Comment by Manuel1607** [comment]
AH ok.... das erklärt einiges... super danke
