### ISSUE TITLE
hap homematic startet sehr oft neu

### ISSUE THREAD

**Issue by psdl** [thkl/hap-homematic#53]
Meine hap-homematic Instanz startet sich von selbst immer wieder neu. Ich kann leider nichts in den LOG Files sehen, da diese nach einem Neustart immer wieder zurückgesetzt werden.

Ich habe die Logs der hap-homematic und der raspberrymatic angehängt.
[hap-homematic-log.txt](https://github.com/thkl/hap-homematic/files/4585298/hap-homematic-log.txt)
[0.0.0.0-2020-05-06.log](https://github.com/thkl/hap-homematic/files/4585299/0.0.0.0-2020-05-06.log)

**Comment by thkl** [comment]
liegt zufällig in /usr/local/etc/config/hap-homematic/ ein File mit der Endung .crash 

Das sind die Crashlogs die vor dem beenden gespeichert werden. Der Neustart wird vom Monitoring Service gemacht.  Da sollte auch ein Alarm in der CCU auftauchen.

**Comment by psdl** [comment]
Ich habe eben einmal nachgeschaut. Das Verzeichnis ist leider leer.

**Comment by psdl** [comment]
Ich deinstallieren die Software und lösche die Verzeichnisse nochmal und lege alles neu an. Erst einmal ohne Geräte und beobachte das Verhalten dann.

**Comment by thkl** [comment]
oops der richtige Pfad für die config ist auch : /usr/local/etc/config/addons/hap-homematic/ ...

**Comment by psdl** [comment]
Danke für deine Hilfe. Den Pfad hatte ich selbst gefunden, allerdings lagen dort keine Crash Logs. Ich habe die komplette CCU noch einmal aufgesetzt und nicht meine Config aus der Debmatic auf die Raspberrymatic übertragen. der Fehler ist verschwunden !
Was für eine Arbeit :)
