### ISSUE TITLE
Unterstützung von Secure Video

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#532]
Hallo,

ich bin über einige Meldungen im Internet gestolpert, dass Homebridge in der neuen Version 1.4 Apples Secure Video unterstützt. Nicht zertifizierte Kameras können somit ins Apple Universum eingebunden werden.

Wäre so ein Feature auch mit diesem Plugin möglich?

Viele Grüße

**Comment by JensBonse** [comment]
Für HomeMatic gibt es direkt keine Kameras. Man kann zwar über CUxD sich Kameras einbinden, aber dann kann man die über eine HomeBridge direkt ohne Umweg ins HomeKit bringen.
Glaube nicht, dass es generell Sinn ergeben würde.
