### ISSUE TITLE
HmIP-eTRV Boost

### ISSUE THREAD

**Issue by blackbasket** [thkl/hap-homematic#533]
Hallo Thomas,

ich dachte, wir hätten das Thema schon mal gehabt. Allerdings finde ich gerade kein Ticket dazu.

Seit Beginn ist es bei mir so, dass sich das "Gerät" Heizung Boost Mode immer wieder umbenennt.

Soll heißen:
- Es existiert das Gerät "Heizung" und das Gerät "HeizungBoost Mode". Letzteres lässt sich über Siri nicht bedienen - mit Ausnahme des HomePods im entsprechende Raum.
- Jetzt benenne ich das Gerät in der HomeApp zu "Heizung Boost" um.
- Nach einem HAP-Neustart ist alles wieder weg :(

LG,
Marcel

**Comment by blackbasket** [comment]
Hallo @thkl ,

ich habe die Lösung, aber bin zu blöd, um in GitHub einen PR zu erstellen. (In allen Anleitungen, die ich finde, stehen Optionen, die ich nie sehe)

In der HomeMaticRadiatorThermostatAccessory.js müssen zwei Zeilen geändert werden.

Zeile 189
```let boostService = this.addService(new Service.Switch(this._name + ' Boost', 'Boost Mode'))```

Zeile 198 auskommentieren (sonst wird der ManuMode nicht wiederhergestellt)
```await self.setValueForDataPointNameWithSettingsKey('SetControlMode', null, 0)```

LG,
Marcel

**Comment by blackbasket** [comment]
Hallo Thomas,

die o.g. Lösung hatte bis jetzt (iOS 16) gut funktioniert. In iOS 16 heißt der Boost Switch nun aber immer "Heizung" (also gleich dem Name des Radiators). Wenn man den Wert "Heizung" in der Home-App über das X löscht, wird dahinter der korrekte Name in grau angezeigt.

Ich habe mehrere Versionen der Zeile 189 getestet, aber leider alle erfolglos. Der Name ist immer "Heizung".
`let boostService = this.addService(new Service.Switch(this._name + '-Boost', 'Boost Mode'))`
`let boostService = this.addService(new Service.Switch(this._name + 'Boost', 'Boost Mode'))` ("Originalzeile")
`let boostService = this.addService(new Service.Switch('Heizung Boost', 'Boost Mode'))`

Mir ist schon am ersten Tag nach dem Update aufgefallen, dass plötzlich einige Werte (auch aus Homebridge-Addons) verstellt waren. Dort kann ich das Problem aber zumindest nicht mehr reproduzieren.

Hast du eine Idee für mich?

LG,
Marcel

**Comment by blackbasket** [comment]
Ich hab's jetzt erst mal mittels CCU-Programm gelöst, damit der Name nach reboot bestehen bleibt... es wäre ggf. trotzdem gut, wenn wir das gefixt bekommen, @thkl 

Sonst mach das Ticket ruhig zu und jeder kann nachlesen, dass es mittels Programm zu lösen ist ;)

LG,
Marcel

**Comment by thkl** [comment]
Das Problem scheint in HomeKit zu liegen. Ich habe jetzt mal mit dem original Apple HomeKit Simulator ein Thermostat anzulegen und einen Schalter als "linked Service" dazu .. (genau so wird das via Hap erzeugt) .. In HomeKit bekommen die beiden Geräte dann auch den gleichen Namen, egal wie ich sie im Simulator benannt habe ... ich sehe gerade keine Möglichkeit das zu fixen
