### ISSUE TITLE
Module not starting anymore after Raspberrymatic FW Update

### ISSUE THREAD

**Issue by demji1985** [thkl/hap-homematic#535]
Hello,

i just did a firmware update from raspberrymatic. Since then the module is not working anymore. Cannot restart it, cannot reinstall. It appears like it just does not work anymore - does it have issues with any update here?

Regards,

**Comment by Matten-Matten** [comment]
Hallo, hier das selbe. Neuste raspberrymatic software auf RPI3.

Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
Version 3.61.7.20220226 (rpi3)

**Comment by Matten-Matten** [comment]
```
Mar 21 19:29:18 ccu3 user.err monit[1267]: 'HapHomeMatic' service restarted 1 times within 1 cycles(s) - exec
Mar 21 19:29:18 ccu3 user.info monit[1267]: 'HapHomeMatic' exec: '/bin/triggerAlarm.tcl Hap-HomeMatic restarted WatchDog-Alarm'
Mar 21 19:29:18 ccu3 user.err monit[1267]: 'HapHomeMatic' process is not running
Mar 21 19:29:18 ccu3 user.info monit[1267]: 'HapHomeMatic' trying to restart
Mar 21 19:29:18 ccu3 user.info monit[1267]: 'HapHomeMatic' restart: '/etc/config/rc.d/hap-homematic restart'
Mar 21 19:29:20 ccu3 user.info homematic: stopped hap-homematic
Mar 21 19:29:30 ccu3 user.info homematic: start hap-homematic
Mar 21 19:29:36 ccu3 kern.crit kernel: [  477.428838] EXT4-fs error (device mmcblk0p3): ext4_lookup:1706: inode #652834: comm node: iget: checksum invalid
Mar 21 19:29:36 ccu3 kern.crit kernel: [  477.432470] EXT4-fs error (device mmcblk0p3): ext4_lookup:1706: inode #652834: comm node: iget: checksum invalid
Mar 21 19:29:36 ccu3 kern.crit kernel: [  477.597008] EXT4-fs error (device mmcblk0p3): ext4_lookup:1706: inode #652834: comm node: iget: checksum invalid
Mar 21 19:29:36 ccu3 kern.crit kernel: [  477.762393] EXT4-fs error (device mmcblk0p3): ext4_lookup:1706: inode #652834: comm node: iget: checksum invalid
Mar 21 19:29:36 ccu3 kern.crit kernel: [  477.927586] EXT4-fs error (device mmcblk0p3): ext4_lookup:1706: inode #652834: comm node: iget: checksum invalid
Mar 21 19:29:36 ccu3 kern.crit kernel: [  478.092317] EXT4-fs error (device mmcblk0p3): ext4_lookup:1706: inode #652834: comm node: iget: checksum invalid
Mar 21 19:29:37 ccu3 kern.crit kernel: [  478.257229] EXT4-fs error (device mmcblk0p3): ext4_lookup:1706: inode #652834: comm node: iget: checksum invalid
Mar 21 19:29:48 ccu3 user.err monit[1267]: 'HapHomeMatic' process is not running
Mar 21 19:29:48 ccu3 user.info monit[1267]: 'HapHomeMatic' trying to restart
Mar 21 19:29:48 ccu3 user.info monit[1267]: 'HapHomeMatic' restart: '/etc/config/rc.d/hap-homematic restart'
Mar 21 19:29:50 ccu3 user.info homematic: stopped hap-homematic
Mar 21 19:30:00 ccu3 user.info homematic: start hap-homematic
```

**Comment by AlexBruns** [comment]
Hallo, habe auch mit der Vorgängerversion 3.61.7.20220115 häufiger Crashes (alle paar Tage):

Mar 22 00:06:24 raspberrymatic user.warn monit[1354]: 'HapHomeMatic' process is not running
...
Mar 22 00:06:42 raspberrymatic user.warn monit[1354]: 'HapHomeMatic' process is not running
...
Mar 22 00:07:00 raspberrymatic user.warn monit[1354]: 'HapHomeMatic' process is not running
Mar 22 00:07:18 raspberrymatic user.warn monit[1354]: 'HapHomeMatic' process is not running
Mar 22 00:07:36 raspberrymatic user.err monit[1354]: 'HapHomeMatic' process is not running
Mar 22 00:07:36 raspberrymatic user.info monit[1354]: 'HapHomeMatic' trying to restart
Mar 22 00:07:36 raspberrymatic user.info monit[1354]: 'HapHomeMatic' restart: '/etc/config/rc.d/hap-homematic restart'
...
Mar 22 00:08:06 raspberrymatic user.err monit[1354]: 'HapHomeMatic' service restarted 1 times within 1 cycles(s) - exec
Mar 22 00:08:06 raspberrymatic user.info monit[1354]: 'HapHomeMatic' exec: '/bin/triggerAlarm.tcl Hap-HomeMatic restarted WatchDog-Alarm'
Mar 22 00:08:06 raspberrymatic user.info monit[1354]: 'HapHomeMatic' process is running with pid 14007
Mar 22 00:08:06 raspberrymatic user.info monit[1354]: 'HapHomeMatic' process is running after previous restart timeout (manually recovered?)

Es lief früher definitv stabiler.

**Comment by demji1985** [comment]
Bei mir geht es wieder .... die SD Karte war defekt und hat kurz drauf nen Abflug gemacht. Jetzt neue SD Karte - Backup eingespielt - alles geht wieder inkl. HomeKit
