### ISSUE TITLE
Unterstützung für HM-LC-RGBW-WM

### ISSUE THREAD

**Issue by hillinator** [thkl/hap-homematic#537]
Hallo Thomas,
wäre es möglich folgendes Homematic Modul mit einzubinden, damit man die Farben und Helligkeit steuern kann?

.json Inhalt anbei:

<pre>{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HM-LC-RGBW-WM",
      "address": "3529122215ABCD",
      "type": "HM-LC-RGBW-WM",
      "channels": [
        {
          "id": 1001,
          "name": "3529122215ABCD:1",
          "intf": 0,
          "address": "3529122215ABCD:1",
          "type": "DIMMER",
          "access": 255
        },
        {
          "id": 1002,
          "name": "3529122215ABCD:2",
          "intf": 0,
          "address": "3529122215ABCD:2",
          "type": "RGBW_COLOR",
          "access": 255
        },
        {
          "id": 1003,
          "name": "3529122215ABCD:3",
          "intf": 0,
          "address": "3529122215ABCD:3",
          "type": "RGBW_AUTOMATIC",
          "access": 255
        }
      ]
    }
  ]
}
</code></pre>

danke und Gruß

**Comment by 011V32** [comment]
Hallo,

bei mir funktioniert das Modul HM-LC-RGBW-WM mit Kanal 2 "RGBW_COLOR".
Was funktioniert bei dir nicht?

MFG

**Comment by 011V32** [comment]
Hallo,

falls es jemanden hilft: wie im [homebridge homematic](https://github.com/thkl/homebridge-homematic#hm-lc-rgbw-wm) erwähnt funktioniert bei mir Kanal 2.

**Comment by hillinator** [comment]
Hi @011V32 , Danke für die Info. Dein erster Post ist iwie untergegangen, sry. Ich konnte es jetzt auch erfolgreich einbinden.
