### ISSUE TITLE
Homkit verbindungsprobleme

### ISSUE THREAD

**Issue by YanneckBecker** [thkl/hap-homematic#543]
Homkit  trennt immer wieder die verbindung zu homatic dann werden auf der hap seite keine Geräte mehr angezegt

**Comment by ChrWi** [comment]
Was ist Deine Hardware für HomeKit?

**Comment by YanneckBecker** [comment]
benutze eine CCU3 ein paar homatic ip schaltaktoren das problem ist hab es jetzt 4 mal neu instaliert. jedesmal läuft es ein paar tage dann stürtzt es immer wieder alle paar stunden/minuten nach neustart ab bis es garnicht mehr geht und ich auch nicht mehr auf die Web oberfläche komme

**Comment by ChrWi** [comment]
Ich meinte HomeKit 
-> nutzt Du hierfür iPad, HomePad, AppleTV?
Was ist denn jetzt das primäre Problem:
- HomeKit zeigt keine Geräte mehr an (und die CCU läuft noch) 
ODER
- die CCU stürzt regelmäßig ab
ODER
- HomeKit Add-on stürzt regelmäßig ab
???

**Comment by YanneckBecker** [comment]
Zentrale für homkit ist ein apple tv angezeigt wird mir immer das keine verbindung zum gerät hergestellt werden kann

**Comment by ChrWi** [comment]
Was sagen die Firewall Einstellungen der CCU?

**Comment by jb-home** [comment]
Kannst du wenn was abschmiert mal in die LOGs schauen?
Damit wir ggf. sehen können was klemmt.
HAP-HomeMatic ist generell stabil. Nur wenn es defekte Geräte gibt, kann sich das auf HAP auswirken.
Welche Addons sind auf der CCU noch installiert?

> Zentrale für homkit ist ein apple tv angezeigt wird mir immer das keine verbindung zum gerät hergestellt werden kann
Wo wird dir das angezeigt?

**Comment by ChrWi** [comment]
@YanneckBecker noch Bedarf? Dann stelle bitte die Informationen bereit.
