### ISSUE TITLE
"light" switch in home kit does not keep "on" state when used with "special device" "http call"

### ISSUE THREAD

**Issue by Girgitt** [thkl/hap-homematic#549]
(Thank you very much for such a useful project)

**Please describe your problem**
_Which_ Homematic actor/sensor you want to control ?_
I want to control a third party device using http call via Node-Red running on CCU3.

_Which settings y've choosen for this actor/sensor in hap-homematic ?_
I added "special device" http according to https://github.com/thkl/hap-homematic/wiki/special-devices#http-call

**What happens**
Device appears in Home Kit just fine (e.g. as "light bulb" if such type is chosen) and action is triggered when tapped on it however after a ~second device in Home Kit returns to the initial state (e.g. off).  

The problem is I don't know what value/json should the http call return to modify the state of the actor. 
I tried returning True, 1, ON and also JSON {"on":true, "off":false} but the result is always the same: after a second device's state in Home Kit returns to "off".

**What should be happend**
If "special device" of the http call type supports changing the state of Home Kit device it is mapped to the documentation should mention this and provide example of the value the http call should return. Or if changing state is not possible, documentation should mention such limitation. 

Since hap-homematic does a GET call on the endpoint configured in http call I assume there is no separate call for getting current state (e.g. GET) and to issue an action (e.g. POST). 

**Steps to reproduce this issue**
I will add interaction steps in debug mode if needed but please, if possible, explain first if http "special device" supports changing permanently the state of the mapped Home Kit device - because if not then this issue should be a feature request (apart from remark on documentation of the http call "special device" being too brief).

**Comment by ChrWi** [comment]
Hi, you are right, there is documentation missing. I struggled today with a POST request that include a Bearer token (part of the header information when sending the request via curl). No idea where / how to put this into the setup.
Maybe @thkl or @sailor79 can give some hints / answers to above request.

**Comment by thkl** [comment]
Currently the http service will not react on the result of the call. The isOn Request from HomeKit will be served always with "false". So that is the reason why your light icon will turn off after HomeKit sends the next query. 

The http service was designed as "a Push to action".

For implementing a valid state getter there has to be a second url for requesting the current state of the device and maybe parsing logic to get a valid state from the http request.

**Comment by ChrWi** [comment]
Thanks Thomas, I defined my use case per CCU virtual device + script.

**Comment by Girgitt** [comment]
Thank you for all the answers. I ended up using node-red for home kit integration.
