### ISSUE TITLE
Disable Monitoring

### ISSUE THREAD

**Issue by thkl** [thkl/hap-homematic#55]
Disable monitoring after 5 restarts in about 1 hour

Disable monitoring via webui

**Comment by roe1974** [comment]
Hallo Thomas
Unter Einstellungen kann ja jetzt das Monitorung enabled/disabled werden.
Wenn man es enabled bleibt aber das Häkchen nicht .. damit weiss man nicht ob Monitoring aktiv ist oder nicht ....
lg Richard

**Comment by thkl** [comment]
Ja, weil der ganze Prozess derzeit neu starten muss 🤪 mach ich vielleicht später noch on the fly.

**Comment by roe1974** [comment]
ok :-) ... du meinst der monit process startet neu .... (monit reload) .... weil du die config dort hinlegst/wegnimmst .... aber was hat das mit dem "icon-häkchen" zu tun ? ... wenn config da = häkchen on, wenn config nicht da= häckchen off :-P

**Comment by thkl** [comment]
Nein ich sage dem Hauptprozess nur das er beim nächsten Start keine Neue erzeugen bzw. die alte entfernen soll.

**Comment by roe1974** [comment]
ok ... aber dann brauchst du jedesmal ein "monit reload" ... damit monit das mitbekommt .....
und das häkchen kann man nicht abhängig machen ob config da oder nicht ?

**Comment by thkl** [comment]
Mehr noch es wir ja nur das Flag vom Config Prozess gesetzt welches dem Hauptprozess bei seinem Start sagt was er tun soll. 

Der Config Prozess ändert derzeit am Monitoring nichts. Das muss ich noch erweitern.

**Comment by roe1974** [comment]
😜😜

**Comment by roe1974** [comment]
👍👍
