### ISSUE TITLE
Vier Geräte steuern das selbe Ziel

### ISSUE THREAD

**Issue by RealWinny** [thkl/hap-homematic#550]
Hallo,
ich habe in meiner CCU über CUXD einen virtuellen Dimmer-Aktor angelegt, der die Lamellenverstellung meiner Jalousien regelt. Die Höhe der Jalousie wird mit einem ganz normalen Jalousieaktor eingestellt (ist hier nicht von Bedeutung), nur eben die Lamellenausrichtung wird separat über genannte Dimmer-Aktoren eingestellt. 0% heißt geschlossen, 100% genau anders herum geklappt geschlossen und 50% entspräche einer waagrecht eingestellten Lamelle. 
Passt und funktioniert alles soweit mit einem Gerät.

Jetzt habe ich vier Kanäle angelegt. Jeder steuert eine eigene Jalousie. Die vier Kanäle bzw. Geräte sind in HAP-Homematic eingebunden und tauchen in der Home-App auf. Hier die Ansicht in HAP-Homematic. Die 4 Kanäle des CUXD-Gerätes sind als 4 Geräte in HAP-Homematic eingebunden:
![Durchsicht](https://user-images.githubusercontent.com/28679778/176750702-434c99c4-8d99-4060-9bf6-159ebeaba261.JPG)

Das Problem ist nun, dass immer wenn ich über die Home-App eines der Geräte bediene, immer das erste Gerät sich bewegt. Sprich, wenn ich z.B. "Durchsicht Zimmer Max" auf 50% stelle, stellt sich "Durchsicht Mitte links" auf 50%. Analog bei den anderen Geräten. Alles mündet auf "Durchsicht Mitte links". Innerhalb der CUU (z.B. via Bedienung über das WEB-Interface) funktionieren alle individuell ohne Probleme.
Auch andere virtuelle CUXD-Geräte mit mehreren Kanälen funktionieren problemlos über die HAP-Homematic-App und können einzeln angesteuert werden. Nur hier in diesem Fall funktioniert es nicht. Woran kann das liegen?

Hier die Log-Datei:
[hap-homematic-log.txt](https://github.com/thkl/hap-homematic/files/9022363/hap-homematic-log.txt)

**Comment by jb-home** [comment]
Bau die Geräte in der CCU mal auf CUxD Dimmer (CUX400000...) um.
Momentan werden die als HomeMaticRGBAccessory Geräte an HomeKit übergeben.
Nach der Umstellung, sollten die Geräte in HAP dann als HomeMaticDimmerAccessory verfügbar sein.
Damit sollte es dann funktionieren.

**Comment by RealWinny** [comment]
Hat geklappt! :-)
Danke für den Tipp!
