### ISSUE TITLE
HAP Homematic zeig nichts mehr an

### ISSUE THREAD

**Issue by Sebbo1712** [thkl/hap-homematic#554]
Hallo zusammen,

Ich hoffe hier kann mir jemand helfen. 
Ich habe auf meiner CCU3 das addon HAP-Homematic installiert was auch ne ganze zeitlange ohne porbleme lief.
Jetzt in Letzter zeit wurde mir immer öfter Geräte als nicht verfügbar angezeigt. Also ich an den PC über die WebUI das Addon gestartet und siehe da es ist nichts mehr da. Das Addon startet immer bei Schritt 2 der Neueinrichtung, wenn ich dann auf weiter und danach auf Fertigstellen klicke verschwindet zwar das fenster aber es passiert überhaupt nichts mehr und das Addon lässt sich nicht mehr bedienen, auch nach 2-3 Stunden Wartezeit passiert nichts.
Neuinstallation hat auch nichts gebracht. 
ein altes Backup habe ich auch aufgespielt hier wurde mir das einmal kurz alles wieder angezeigt und dann verschwindest wieder alles und das Addon hängt sich auf. 

Updates und so weiter sind alle gemacht und aktuell.

**Comment by blackbasket** [comment]
Hey @Sebbo1712 ,

hast du schon mal die SD-Karte ausgetauscht? Sonst lies auch mal die geschlossenen Tickets. Ich meine, dass wir sowas schon mal hatten.

LG,
Marcel

**Comment by Sebbo1712** [comment]
Hallo Marcel,

Welche SD-Karte meinst du? 
Die CCU3 hat meines Wissens nach keine SD Karte.

**Comment by blackbasket** [comment]
Die microSD, die sich in dem Raspi in deinem CCU3-Gehäuse befindet ;)

**Comment by mrt1976** [comment]
bei mir das gleiche Problem. Hat aber nichts mit der SD Karte zu tun.

**Comment by blackbasket** [comment]
Welche CCU/RM-Version? nur hap ist leer? Und startet auch immer wieder bei Schritt 2?

**Comment by mrt1976** [comment]
manchmal ist hap leer. nach hap neustart wird nichts gefunden. irgendwann werden dann alle 101 Geräte gefunden, jedoch auf dem iphone sind alle geräte ohne funktion ( keine Antwort )

**Comment by blackbasket** [comment]
Was hast du für HomeKit-Zentralen?

**Comment by thkl** [comment]
Hallo @Sebbo1712 ,

kurze Frage, sind die Geräte in HomeKit vorhanden und lassen diese sich bedienen oder sind die auch dort weg ? 
Wenn nicht, kann ich mal das Backup haben. eMail wäre ok.

Beste Grüße
Thomas

**Comment by ChrWi** [comment]
@Sebbo1712 noch aktuell? Ansonsten Bitte schließen

**Comment by Sebbo1712** [comment]
Closed
