### ISSUE TITLE
HmIP-FCI1 unter besondere Geräte Anzeigen lassen

### ISSUE THREAD

**Issue by Tom74HH** [thkl/hap-homematic#556]
Moin,

ich würde gerne den HmIP-FCI1 unter besondere Geräte anzeigen lassen, um damit eine Video Door Bell zu erstellen. 
Auslöser wäre der Klingeltaster  der an einem HmIP-FCI1 angeschlossen ist. Hab am Eingang eine Camera wo ich dann das Bild abfangen würde.

Wäre es möglich den HmIP-FCI1 mit unter besondere Geräte anzeigen zu lassen.

Gruß Tom

**Comment by thkl** [comment]
i am late to the party, ich weiss .. Kurze Frage zu diesem Device. Laut Doku kommt es als MULTI_MODE_INPUT_TRANSMITTER daher. Es hat 3 Datenpunkte auf Channel 1 .. PRESS_LONG PRESS_SHORT und STATE.
Sehe ich das richtig, dass man das Ding konfigurieren kann das es einmal als "Ein Aus" Gerät agiert und einmal als normaler Taster ?

**Comment by Tom74HH** [comment]
Moin, jepp so ist es. Ich hab den als Taster für die Klingel konfiguriert.

**Comment by thkl** [comment]
Dann könnte man das recht einfach durch Erweiterung dieser Datei https://github.com/thkl/hap-homematic/blob/master/lib/services/HomeMaticKeyAccessory.js versuchen.

Es müsste hier nur der neue ChannelType hinzugefügt werden:

Zeile 76 - 78 müssen von 
```
static channelTypes() {
    return ['KEY', 'VIRTUAL_KEY', 'KEY_TRANSCEIVER', 'MULTI_MODE_INPUT_TRANSMITTER', 'SWITCH_INTERFACE']
  }
```

zu 

```
static channelTypes() {
    return ['KEY', 'VIRTUAL_KEY', 'KEY_TRANSCEIVER', 'MULTI_MODE_INPUT_TRANSMITTER', 'SWITCH_INTERFACE', 'MULTI_MODE_INPUT_TRANSMITTER']
  }
```

Dann sollte das Gerät erkannt werden

**Comment by Tom74HH** [comment]
Moin, Änderung gemacht, taucht aber leider nicht unter besondere Geräte auf.

**Comment by thkl** [comment]
Ne das Ding wird dann als normale Gerät (Taste) erkannt ... und kann so hinzugefügt werden .. oder hab ich da was falsch verstanden ?

**Comment by Tom74HH** [comment]
Da wird der ja angezeigt und verarbeite, da hab ich denn auch als normale Klingel eingerichtet. Unter "besondere Geräte" wollte ich den eigentlich Nutzen als Video Türklingel.  Hab da aber erstmal ein Virtuellen Taster erstellt der beim Klingeln ausgelöst wird. Mit der Video Türklingel bin ich aber noch am test. Dachte nur das man da den Taster auch direkt anzeigen lassen kann, da einige Wandtaster da ja angezeigt werden.

**Comment by thkl** [comment]
Oh jetzt sehe ich das erst. Du willst die VideoDoorBell erweitern .. dann ist es Zeile 129 im File https://github.com/thkl/hap-homematic/blob/master/lib/services/HomeMaticSPVideoDoorBellAccessory.js

```
        options: {filterChannels: ['KEY', 'VIRTUAL_KEY','MULTI_MODE_INPUT_TRANSMITTER']}
```

**Comment by Tom74HH** [comment]
Super Danke.... Wird da nun angezeigt :-)
