### ISSUE TITLE
HAP-Homematic stürzt immer wieder ab

### ISSUE THREAD

**Issue by sjbufton** [thkl/hap-homematic#557]
**Please describe your problem**
Die Steuerung via HomeKit funktioniert immer wieder nicht, weil der HAP-Homematic-Addon abgestürzt ist.

**What happens**
HAP-Homematic produziert ein .crash-File mit folgendem Inhalt (immer gleich):
```
Error: accept EMFILE
    at _errnoException (util.js:992:11)
    at TCP.onconnection (net.js:1541:24)
```

[Siehe 1660446379376.crash.txt](https://github.com/thkl/hap-homematic/files/9335621/1660446379376.crash.txt)

**What should happen**
HAP-Homematic soll nicht abstürzen ;-)

**Steps to reproduce this issue**
Unbekannt. Es passiert immer wieder mal.

**Umgebung**
CCU3 mit Firmware 3.65.6
Keine anderen Addons installiert.

**Comment by MNieddu91** [comment]
Ich reihe mich hier mal ein, gleiches Problem und Verhalten, jedoch führt bei mir ein anderer Error zum Absturz des Addons. 

`TypeError: Cannot set properties of undefined (setting 'lockEvents')
    at /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/HomeMaticKeyMaticIPAccessory.js:176:30
    at /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/HomeMaticCCU.js:832:9
    at Array.map (<anonymous>)
    at HomeMaticCCU.fireEvent (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/HomeMaticCCU.js:831:14)
    at /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/HomeMaticCCU.js:532:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

Mit jedem Absturz (wenige Sekunden nach manuellem Neustart von HAP-Homematic wird das Addon wieder beendet mit dieser Fehlermeldung. 
CCU3 bereits mehrmals neu gestartet. HAP-Homematic neu installiert und aus Backup wiederhergestellt schaffte Abhilfe für etwa eine Stunde. Seitdem wieder das gleiche Problem.

**Comment by ChrWi** [comment]
Auf welcher Hardware & Version läuft eure HomeKit Umgebung?

**Comment by sjbufton** [comment]
> Auf welcher Hardware & Version läuft eure HomeKit Umgebung?

HomeMatic IP CCU3, jetzt 3.65.11, damals 3.65.6. HAP-Homematic ist seit längerem nicht mehr abgestürzt.
