### ISSUE TITLE
Kosmetik: der gewählte Menüpunkt behält nicht die Farbe ... vielleicht bessere Orientierung wenn doch ?!?!

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#56]
Hallo Thomas

Aktuell bleibt der gewählte Menüpunkt links ja nicht in blau markiert. Könnte man das ändern zur besseren Orientierung wo man gerade steht ? Ich habe ein paar Screenshots gebastelt:
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/30420568/81261570-99250880-903c-11ea-9fcf-aa2201c30aee.png">
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/30420568/81261580-9de9bc80-903c-11ea-9fd3-4d28e4a118dd.png">

Die gewählten Punkte bleiben links blau .... geht das ?

lg Richard

**Comment by thkl** [comment]
Echt jetzt ?

**Comment by roe1974** [comment]
okeeeeeee ..... dann mach ich ihn wieder zu 😜😜😜😜😜
