### ISSUE TITLE
HmIP-BSM status wird nicht angezeigt im HomeKit

### ISSUE THREAD

**Issue by mcoreix** [thkl/hap-homematic#562]
**Please describe your problem**
HmIP-BSM status wird nicht richtig angezeigt und ist auch nicht mehr bedienbar --> HomeMaticSwitchAccessory

**What happends**
Wenn der Aktor (Licht) manuell betätigt wird, kann diese über Apple HomeKit nicht mehr ausgeschaltet werden. Es ist auch nicht mehr bedienbar. 
Wenn der Aktor (Licht) über HomeKit betätigt wird, kann dieser wiederum auch nicht mehr manuell abgeschaltet werden

**What should be happend**
Beide Funktionen sollten Funktionieren. Also wenn es über HomeKit eingeschaltet worden ist, sollte es auch über den manuellen Schlalter ausgeschaltet werden können und umgekehrt auch 

**Steps to reproduce this issue**
Licht manuell einschalte und über HomeKit es versuchen abzuschalten

**Comment by timwegenerDE** [comment]
Kann ich nicht bestätigen. Aktuellste Raspberrymatic + hap-homematic Version. Mehrere BSM ohne Probleme.

**Comment by mcoreix** [comment]
muss man was bestimmtes in der ccu konfigurieren?

**Comment by timwegenerDE** [comment]
Eigentlich nicht. Hast du den richtigen Kanal in hap genommen? Ist der Duty Cycle der CCU vielleicht recht voll?

**Comment by mcoreix** [comment]
> Eigentlich nicht. Hast du den richtigen Kanal in hap genommen? Ist der Duty Cycle der CCU vielleicht recht voll?
Danke es war leider der falsche Kanal
