### ISSUE TITLE
Kompatibilität mit iOS 16

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#563]
Guten Tag,

am Anfang der kommenden Woche veröffentlicht Apple iOS 16. Mit dieser Version soll der komplette Unterbau von Homekit angepasst worden sein. Wurde das Plugin schon mit iOS 16 getestet? Oder ist das nicht notwendig?

Viele Grüße
Christoph

**Comment by dkrizic** [comment]
Ich habe die Betas bzw. RCs auf dem iPhone und iPad laufen. Aktuell läuft alles soweit so gut.

**Comment by gerd2005** [comment]
Ok, danke für den Hinweis.
