### ISSUE TITLE
Nach restart werden daten nicht automatisch geladen

### ISSUE THREAD

**Issue by marwi234** [thkl/hap-homematic#567]
Neuerdings merkwürdiges aber reproduzierbares Verhalten nach HAP restart oder CCU restart. 

Setting: 
Raspberrymatic 3.65.8.20220831, 
HAP-Homematic Version 0.0.63

Durchgeführte Schritte:
-HAP restart
Verhalten: Nach restart sind keine Geräte oder Instanzen mehr vorhanden. Der Willkommendialog wird angezeigt.

Abhilfe: Wilkommensmeldung schließen (X), "Homekit Instanzen" -> "Einstellungen" wählen, Bei "Veröffentlichungseinstellungen" auf "Fertigstellen" drücken. Danach sind alle Geräte und Instanzen wieder da. 

Ab 13:41:0x waren alle Geräte wieder da. 

debug-log als gist:

https://gist.github.com/marwi234/2514b670829c31f31aac8ad086518b81#file-hap-homematic-log-txt

**Comment by karwak** [comment]
Habe seit einigen Monaten bereits das selbe Phänomen.
- Nach dem Neustart der CCU ist die Konfiguration des HAP-Services stets erst mal leer und das Willkommens-Popup erscheint.

Sofern ich den HAP Service nach ein paar Minuten neu starte erscheinen die Geräte wieder…

Liefere gerne auch Infos zu, bräuchte jedoch Anleitung was ich dazu tun muss.

**Comment by TeaJAge** [comment]
Ich denke, dass es sich um dasselbe Problem handelt wie in #453 beschrieben. Ich glaube, es gibt noch mehrere Issues, die dieses Problem beschreiben.

Diese zwei hab ich gefunden: #453, #554 (+dieses #567)

Bei mir hilft nur eine Neuinstallation des Adapters, nach einiger Zeit, vermutlich meistens, wenn ich etwas ändere, erscheint dann wieder der Wizard und ich fange wieder von vorne an.

**Comment by blackbasket** [comment]
Hmm, ich habe das Verhalten bisher zum Glück nicht...

mir kommt aber gerade mal ein Gedanke: Müsste das beschriebene Verhalten nicht genau dann auftauchen, wenn das hap "vergessen" hat, dass es schon mal konfiguriert war? Es wird ja zunächst das Installer-Package auf der CCU installiert (0.14)... nach einem reboot fängt dann der Download des Addons an... und da gibt es doch bestimmt ein File, welches sich merkt, dass es installiert ist, oder Thomas @thkl ? Könnte es nicht sein, dass eben dieses File nicht sauber geschrieben wird? Ggf. falsche Berechtigungen oder so?

Ich möchte uns jetzt nicht auf den falschen Weg führen, nur eine Idee...

**Comment by thkl** [comment]
Also, ein Problem bei den Rechten auf das Config file sehe ich eher nicht. Das wird mit ein und dem selben User (im RM Falle sogar root) geschrieben. Das Logfile oben zeigt auch keine Fehler an. Die Instanzen werden geladen und die Geräte scheinbar auch.  

Intern sind der Teil der mit HomeKit spricht und der Konfigurationsserver zwei verschiedene Prozesse die via Interprozesskommunikation ihre Daten austauschen. Wenn die Weboberfläche geladen wird und keine Instanz bzw kein Gerät vom Daemon gesendet bekommt, geht sie davon aus, dass es eine neue Installation ist und zeigt den Wizzard an.

Die Frage ist, wenn dieser Fall auftritt, sind die Geräte in HomeKit noch da und werden sie als erreichbar angezeigt ? Das schaut zumindest nach obigem Logfile so aus. Dann wäre es entweder ein Problem zwischen Daemon und Konfiguarationsservice oder zwischen Konfigservice und WebUI.

**Comment by TeaJAge** [comment]
Also bei mir sind die Gräte auf "keine Antwort" in Homekit, wenn der Wizard angezeigt wird.

**Comment by thkl** [comment]
Aber ab dem Zeitpunkt ist es ein Dauerzustand ? Dann könnte es gut sein das der Daemon zwar startet aber aufgrund eines Fehlers im config.json File die Geräte nicht geladen werden. 

Ggf geht das File auch beim Speichern der vorherigen Änderungen kaputt. Was aber nicht der Fall des Original Posters ist, denn laut dem Log werden da Daten geladen. 

Kannst du bitte auch mal das LogFile als .TXT hier anhängen sollte der Fehler aufgetreten sein.

**Comment by TeaJAge** [comment]
Das LogFile hab ich im Ticket #453 (https://github.com/thkl/hap-homematic/issues/453#issuecomment-1257280515) hochgeladen. Ich hab da nur meine User und PIN gelöscht, weil ich nicht weiß ob man da online darauf zugreifen und steuern könnte, mit den Daten.

**Comment by marwi234** [comment]
> Die Frage ist, wenn dieser Fall auftritt, sind die Geräte in HomeKit noch da und werden sie als erreichbar angezeigt ? Das schaut zumindest nach obigem Logfile so aus. 

Nach dem Neustart sind die Geräte in Homekit noch vorhanden aber nicht erreichbar. Auch längeres Warten hilft nicht. Nach oben genannter Prozedur sind die Geräte wieder erreichbar und zwar zuverlässig. HAP Laufzeit 7 Tage ohne Probleme. 
Es scheint tatsächlich so zu sein, dass ../hap-homematic/config.json nach einem reboot nicht automatisch geladen wird.

**Comment by cR0kE** [comment]
Hallo ich habe das gleiche oder ein ähnliches Phänomen, bei mir verschwinden ab und an ebenfalls alle Geräte nach einem Neustart der CCU, meistens wenn ich die CCU update! Jedoch auch wenn einfach mal wieder die Internetverbindung abbricht oder ich wie heute den Switch, an dem der Raspi hängt, neu starte.
Ich beobachte dieses Phänomen mittlerweile auch schon einige Monate!

Bei mir hilft dann nur folgender Workaround:
- via SSH auf dem Raspi zu verbinden
- unter _/usr/local/etc/config/addons/hap-homematic_ die Datei _evdps.conf_ leeren & mit `[]` füllen
- danach dann ein Neustart von HAP-Homematic 
 
Danach sind die Geräte und Instanzen wieder vorhanden!
Die Workarounds von oben habe ich heute gleich mal getestet, funktionieren beide nicht bei mir!

System:
- Raspberry Pi 3B+
- RaspberryMatic 3.65.8.20220831
- HAP-HomeMatic Version 0.0.63
- weitere Addons:
--> JP HB Devices Version 6.0
--> Programmedrucken Version 2.5

**Comment by blackbasket** [comment]
#453 hast du weiter mitgelesen?

**Comment by marwi234** [comment]
Bach update auf RaspberryMatic 3.65.11.20221005 hatte ich zunächst einen Totalausfall von HAP-Homematic und keine Möglichkeit auf das WI zuzugreifen. 
Abhilfe: 
HAP deinstalliert
HAP neu installiert
manuell alle Geräte neu eingerichtet (ob, ein Backup auch funktioniert hätte, kann ich nicht sagen)

Nun fehlerfreier Betrieb auch nach Neustart der CCU

mfg (meine Anfrage scheint sich somit erledigt zu haben)

**Comment by blackbasket** [comment]
Dann schlage ich vor, dass wir das schließen... wir haben davon ja noch mehr offen, die sich nun ggf auch lösen...
