### ISSUE TITLE
Automationen werden nicht mehr ausgeführt

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#568]
Guten Tag,

mein heutiges Problem hat glaube ich nicht unmittelbar etwas mit diesem PlugIn zu tun, ich komme jedoch leider nicht mehr weiter und benötige Hilfe.

(Gefühlt) seit dem Update meiner Apple Geräte auf 16.0.1 funktionieren meine Automationen nicht mehr. Konkret geht es um zwei Automationen.
1. Schalte Licht zum Sonnenuntergang an (Hier wird das PlugIn angesprochen)
2. Schalte einen HomePod mini um 07:00 Uhr an (Hier ist das PlugIn nicht involviert. Dieser Befehl geht direkt von der Steuerzentrale zum HomePod).

Ich habe die Automationen neu angelegt und die Steuerzentrale gewechselt (Vom Apple TV zum HomePod).
Kurioserweise funktionierenden alle anderen Dinge aber wie gewohnt. Ich kann Szenen ausführen, ich kann Sprachbefehle absetzen und das manuelle Testen einer Automation funktioniert auch.

Ich bin absolut ratlos woran das liegen kann.

Danke und lieben Gruß.

**Comment by blackbasket** [comment]
Hallo Gerd,

da du mit Sicherheit recht hast, dass es nichts mit HAP zu tun hat: Kann bitte jemand von euch @gerd2005 @thkl aus dem Issue eine Discussion machen?

Zunächst mal ein paar Fragen:
- Wie hast du den HPm zur Steuerzentrale gemacht? Mir ist bisher kein Weg bekannt, mit dem man dies nachhaltig beeinflussen kann. HomeKit entscheidet selbst, welches Gerät die aktive Zentrale ist. Sofern das ATV per Ethernet angebunden ist, würde ich dieses auch immer bevorzugen.
- iOS 16.0.1 bezieht sich auf dein Handy? Meine HPm's sind mit 16.0 aktuell. Für's Handy gibt's aber auch schon 16.0.2
- Werden dir Probleme in der Home-App angezeigt? Ich hatte zuletzt einen HPm, der immer wieder ins falsche WLAN connected hat.
- Wie testest du die Automation manuell?
- Es sind HomeKit-Automationen und keine Kurzbefehle?

LG,
Marcel

**Comment by gerd2005** [comment]
Hallo,

wie man dieses Issue in eine Diskussion bringt weiß ich leider nicht. 

Zu 1.: vorher war ein Apple TV (WLAN) die Steuerzentrale. Dies kann man in den Einstellungen unter HomeKit aktiv beeinflussen. Bei den HPm gebe ich dir recht. Die machen das selber.

zu 2.: entschuldige bitte, ich meinte auch 16.0.2 (iPhone). Auf den HPm & APT ist erst 16.0 verfügbar. 

Zu 3.: Nein, keine Meldungen 

zu 4.: hierfür gibt es einen Button in jeder automation. 
![B472A0B2-7337-4FF7-B982-71236C9F8DAC](https://user-images.githubusercontent.com/72799068/193459339-8ebd9567-4ff1-40aa-9913-b27636216ba1.jpeg)

zu 5.: Kurzbefehle habe ich keine. 

Vg

**Comment by blackbasket** [comment]
Zu 1: Ok, jetzt verstanden... du hast auf dem ATV die Option deaktiviert ;)

Zu 4: hast du andere Automationen, die vom Sonnenauf-/untergang abhängig sind?

**Comment by blackbasket** [comment]
> Zu 1.: Exakt
> 
> Zu 4.: nein, habe ich nicht. 
> 
> 
> 
> Ich bin im übrigen auf diesen Artikel gestoßen. 
> 
> 
> 
> Generell: funktionieren bei euch alle Automationen?

Ich glaube, du hast den Link vergessen ;)

**Comment by gerd2005** [comment]
Ja, stimmt. 

https://piunikaweb.com/2022/09/30/homekit-automations-not-working-or-broken-after-ios-16-update/

**Comment by blackbasket** [comment]
Ok... basierend auf dem Link schlage ich vor, den Issue hier zu schließen... das scheint ja definitiv von HomeKit zu kommen und sich aktuell nur durch "einmal alles neu" lösen zu lassen...

Stimmst du mir zu?

**Comment by gerd2005** [comment]
Achso, sorry. Vielen Dank für deine Unterstützung!!
