### ISSUE TITLE
autoupdate

### ISSUE THREAD

**Issue by blackbasket** [thkl/hap-homematic#57]
eine kurze Info: Ich habe gerade manuell von 0.0.31 auf 0.0.38 geupdated... die Tage ist kein autoupdate passiert...

**Comment by thkl** [comment]
Es gibt kein Autoupdate 🙃

**Comment by blackbasket** [comment]
ok, dann hatte ich dich zuletzt falsch verstanden ;)

**Comment by thkl** [comment]
Jup,scheinbar. Das mit dem AutoUpdate hatte ich auch erstmal nicht vor.
