### ISSUE TITLE
iOS 16.1 ... kompatibel ?

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#572]
Am kommenden Montag ist ja Release Date für iOS/iPadOS 16.1.
Hier sollen sich ja ein paar Dinge ändern in Homekit.
Hat vielleicht schon jemand mit einer Beta Version von iOS 16.1 testen können ob das hap-homematic Add-On dann noch funktioniert ?
lg Richard

**Comment by dkrizic** [comment]
Hi,

zwischen iOS 16.0 und iOS 16.1 gibt es meines Wissens keinen Unterschied bezüglich HomeKit. Das iOS 16.1 bzw. das iPadOS 16.1 kommt man Montag primär wegen der neuen iPads und ein paar (anderen) Features, die nachgereicht werden (z.B. Family Photo Sharing). Ich habe hier ein zwei iPads mit jetzt iPadOS 16.1 RC und da funktioniert alles.

**Comment by roe1974** [comment]
ok ... danke für die info 😉
ich hätte gelesen dass hier irgendwas umgestellt wird ... aber warten wir montag ab 😊
lg richard

**Comment by roe1974** [comment]
Irgendetwas neues kommt aber ......
https://www.ifun.de/apple-home-das-grosse-homekit-update-kommt-mit-16-1-195119/
lg Richard

**Comment by dkrizic** [comment]
Ja, Thread und Matter, aber das sollte erstmal keine Auswirkungen auf bestehende Installationen und das HAP haben.

**Comment by roe1974** [comment]
D.h. soll man diese "Konvertierung" durchführen oder nicht wenn Sie heute Abend angeboten wird ?

**Comment by gerd2005** [comment]
@roe1974  ich mache es mittlerweile immer so, dass ich neue Updates erst nach 1, oder 2 Wochen installiere um zu sehen ob Störungen auftreten. Diese werden ja dann bspw. hier oder in anderen Foren behandelt. Oft ist ja dann schon eine X.X.1 draußen. 
lieben Gruß

**Comment by dkrizic** [comment]
Mach und sag Bescheid, ob noch alles geht :-)

Es geht wohl um die interne Datenbank, sollte auch keine Auswirkungen haben.

**Comment by roe1974** [comment]
Hahhahahhaha ... ich will nicht der erste sein 🙈😜

**Comment by roe1974** [comment]
16.1 installiert ... nichts passiert ... alles grün :-)
Es kam keine Aufforderung zu irgendeiner Konvertierung ;-)

**Comment by Igster-85551** [comment]
Vorsicht - bei mir hat das Update auf 16.1 alles zerschossen. Die angelegten Instanzen kann ich in Home einfügen, allerdings werden zugeteilte Geräte nicht angezeigt. HAP-Homeatic funktioniert unter iOS 16.1 und macOS 13 NICHT !

**Comment by blackbasket** [comment]
> Vorsicht - bei mir hat das Update auf 16.1 alles zerschossen. Die angelegten Instanzen kann ich in Home einfügen, allerdings werden zugeteilte Geräte nicht angezeigt. HAP-Homeatic funktioniert unter iOS 16.1 und macOS 13 NICHT !  

Diese Aussage kannst du so nicht treffen, nur weil du vielleicht Probleme hast! Offensichtlich gibt es sonst keine Ausfälle.

Bist du in Home nach einem Update gefragt worden?

**Comment by Igster-85551** [comment]
> > Vorsicht - bei mir hat das Update auf 16.1 alles zerschossen. Die angelegten Instanzen kann ich in Home einfügen, allerdings werden zugeteilte Geräte nicht angezeigt. HAP-Homeatic funktioniert unter iOS 16.1 und macOS 13 NICHT !
> 
> Diese Aussage kannst du so nicht treffen, nur weil du vielleicht Probleme hast! Offensichtlich gibt es sonst keine Ausfälle.
> 
> Bist du in Home nach einem Update gefragt worden?

Nein - in Home bin ich nicht nach einem Update gefragt worden. Muss berichtigen, bei mir ist das Problem eine zweite Person für Home einzuladen. Dabei geht die Konfiguration in Home kaputt. In HAP-HomeMatic funktioniert bei mir das Zurücksetzen einer Instanz nicht. Ich muss alle Instanzen löschen und alles neu aufsetzen. 

Generell funktioniert HAP-HomeMatic mit iOS 16.1 und macOS 13.

**Comment by blackbasket** [comment]
Gut, falls das andere Verhalten mit hap zu tun hat, bitte ein neues Ticket aufmachen... Ich denke, hier können wir schließen...
