### ISSUE TITLE
Wrong Message according Battery Status

### ISSUE THREAD

**Issue by seprim** [thkl/hap-homematic#573]
Hello
I‘ve installed a HMIP Opening Sensor for one of my doors.
Unfortunately the battery status of this door is wrong inside the Home App, and i cannot correct this.
Is there a possibility to deactivate this message inside HAP or the Home App?
BR
Sebastian

**Comment by ChrWi** [comment]
Can you please check against #77 #122 #350 ?

**Comment by ChrWi** [comment]
Closed as duplicate / no more feedback
