### ISSUE TITLE
Homekit Thermostat HmIP-eTRV-E-S Ansicht in der Eve-App falsch

### ISSUE THREAD

**Issue by hardl1** [thkl/hap-homematic#574]
Hallo,

vor 1 Moche habe ich mir testweise ein Heizungsthermostat HmIP-eTRV Evo zugelegt.
In der RaspberryMatic auf der VM Qnap und in der @Home-App sieht alles sehr gut aus.

Die Umsetzung im HAP-Homematic Adapter ist in der Home-App weitgehend identisch mit einem Eve-Thermostat.

Ich verwende lieber die Eve-App, da dort der Ventilöffnungsgrad und Statistiken ablesbar sind.
Hier gibt es aber in der Eve-App Probleme:
Ausrufezeichen in Kopfzeile
Der Modus ist nicht schaltbar
Der Zeitplan ist nicht wählbar
Der Ventil-Öffnungsgrad ist nicht sichtbar
Beim Druck auf Modus erscheint ein leeres Fenster.

Habe ich etwas falsch gemacht?
Ist das ein Fehler?
Wird die Anzeige in der Eve-App nicht bearbeitet?

![866C4C14-A6DD-4DCF-B673-3DD83F8842B2](https://user-images.githubusercontent.com/38688960/198872596-8fbd7fbf-f795-43a7-aaa6-8efa7bd7df2e.png)

![480B4549-3472-44EB-A8A7-CA3F53175BEC](https://user-images.githubusercontent.com/38688960/198872632-509bf934-b1f2-4f2e-b1e7-3520647b20ce.png)

Gruß hardl

**Comment by timwegenerDE** [comment]
Ist vielleicht nur ein Workaround, aber hast du mal versucht den in eine HmIP-Heizgruppe zu packen und via hap rauszugeben?

**Comment by hardl1** [comment]
Einen Versuch war es wert, aber leider keine Änderung.

Leider scheint es in der Eve-App weitere Probleme zu geben. 
Das Energiemeter in der Steckdose wird als Schalter dargestellt.
Das Garagentor wird statt offen oder geschlossen mit 0 oder I dargestellt
