### ISSUE TITLE
HAP-HomeMatic wird nicht gestartet

### ISSUE THREAD

**Issue by jb-home** [thkl/hap-homematic#576]
Ich hab die CCU3 aus Wartungsgründen heruntergefahren.
Beim wieder hochfahren, war HAP-HomaMatic nicht automatisch gestartet worden.
Habe es dann per SSH neugestartet.
Problem war, dass der PID file noch existierte.

Habe den service temporär in soweit angepasst, dass er vorher einen stop macht, wie beim service restart.

Man könnte den PID file auch in den tmp Ordner packen, damit der nach jedem Reboot definitiv weg ist.

**Comment by thkl** [comment]
Das PID File liegt in /var/run .. wo alle anderen PIDs auch liegen .. das /var liegt auf einem tmpfs .. Ggf ist hap auch direkt nach dem Start gecrasht. Dann sollte sich in /usr/local/config/addons/hap-homematic ein .crash file finden ...

**Comment by jb-home** [comment]
Einen .crash Datei konnte ich nicht finden. Zum Glück rebooted man ja nicht so oft ;)
Passt schon. Danke!
