### ISSUE TITLE
Ports werden blockiert

### ISSUE THREAD

**Issue by Wheymisterio** [thkl/hap-homematic#578]
![hap-homematic](https://user-images.githubusercontent.com/23435719/200649552-fcc92594-49ed-46c9-814c-9e32769bf58e.jpg)

das sind meine Instanzen.

![firewall](https://user-images.githubusercontent.com/23435719/200649788-00670602-87ca-43f9-9981-fc0b6b452b34.jpg)

und das sind die freigegebenen Port.

Neuinstallation und neu Einrichtung haben nichts gebracht.

**Comment by timwegenerDE** [comment]
Wenn die Firewall Richtlinie auf Ports offen steht müssen die unten eigentlich nicht nochmal eingetragen werden. In meiner Config hab ich die Richtlinie auf Ports blockiert und unten die einzelnen Ports dann freigegeben. Aber ob das einen Unterschied macht? 🤷🏻‍♂️

**Comment by Wheymisterio** [comment]
leider keine Änderung egal wie ich die Firewall einrichte.
ich kann Instanzen neu anlegen und sehe alle Geräte der CCU3
aber bekomme die Verbindung zu Homekit nicht (Bild scannen oder pin code eingeben beides findet die Bridge nicht)

**Comment by Wheymisterio** [comment]
hier mal mein log
[hap-homematic.log](https://github.com/thkl/hap-homematic/files/9964624/hap-homematic.log)

**Comment by jb-home** [comment]
Ist die CCU/HAP denn im gleichen Netzwerk wie deine Apple Geräte?
Falls ja, welche Netzwerk Switche hängen denn auf dem Weg zwischen CCU/HAP und iPhone/iPad?

**Comment by Wheymisterio** [comment]
Also zwischen ccu und FRITZ!Box steht ein fritz repeater der als mash eingerichtet ist also gleicher Wlan Name und key

**Comment by jb-home** [comment]
Kannst du den Repeater testweise mal umgehen/weglassen und dann ein Pairing der Bridge versuchen?

**Comment by kampfschlonz** [comment]
Hast Du die Bridges unter "Einstellungen" veröffentlicht?

**Comment by blackbasket** [comment]
Kannst du mal bitte den output von `netstat -tulpn` posten?

**Comment by Wheymisterio** [comment]
[netstat-ccu3.txt](https://github.com/thkl/hap-homematic/files/10010647/netstat-ccu3.txt)

**Comment by Wheymisterio** [comment]
![relaxed](https://user-images.githubusercontent.com/23435719/201870070-3baf889b-7b94-47db-813e-6b9f649869e6.jpg)

meinst du das so @blackbasket

**Comment by blackbasket** [comment]
ganz genau... ich setze ja mal voraus, dass du von extern kein Port-Mapping hast... das wäre so oder so fatal fahrlässig...

**Comment by Wheymisterio** [comment]
nein das habe ich nicht 
nach dem neustart habe ich nochmal die port ausgelesen sehen immer noch gleich aus

**Comment by blackbasket** [comment]
hmm... ganz schön blöd, dass die CCU keine Prozesse mit ausgibt... in der RM ist das zumindest brauchbar lesbar... mal andersrum... was hat du für Add-ons installiert? Du verwendet auch CloudMatic, richtig?

**Comment by Wheymisterio** [comment]
CloudMatic wird verwendet
zusätzlich HomeMatic(HomeKit) funktioniert nicht
und NeoServer

**Comment by Wheymisterio** [comment]
kann ich ein backup erstellen nur mit meinen angelernten Geräten ? ohne die anderen einstellungen zu übernehmen

**Comment by blackbasket** [comment]
> CloudMatic wird verwendet zusätzlich HomeMatic(HomeKit) funktioniert nicht und NeoServer

verwendest du neoServer?

> kann ich ein backup erstellen nur mit meinen angelernten Geräten ? ohne die anderen einstellungen zu übernehmen

nein, ich denke nicht

**Comment by Wheymisterio** [comment]
ich benutz die Fernbedienung die ich mal erstellt habe mit AIO Creation Neo dort sind aber nicht die jetzt neuen Geräte vorhanden da lizenz abgelaufen. deswegen versuche ich grad Homekit zum laufen zu bringen damit ich mich von Neo trennen kann

**Comment by blackbasket** [comment]
Ok... neo war das erste, was ich damals deinstalliert hatte...

**Comment by Wheymisterio** [comment]
ich habe jetzt meine ccu3 zurückgesetzt und homekit neu installiert.
nach Feierabend muss ein gerät anlernen und teste ob die ports weiterhin gesperrt sind.
ohne ein Gerät kann ich die Instanz nicht veröffentlichen.

**Comment by blackbasket** [comment]
ok... Idee: Kannst du nicht einfach einen HmIP-VirtualKey verwenden? aber lass dich jetzt bitte nicht stressen ;)

**Comment by blackbasket** [comment]
auf welchen iOS-Ständen bist du eigentlich?

**Comment by Wheymisterio** [comment]
woher bekomme ich den HmIP-VirtualKey ?
IOS 16.1.1

**Comment by blackbasket** [comment]
HmIP-RCV-50 unter Geräte... da hast du 50 virtuelle Taster...

**Comment by Wheymisterio** [comment]
also es scheint nicht zu funktionieren ich weiß nicht woran es liegt .

[netstat-ccu3 nach reset.txt](https://github.com/thkl/hap-homematic/files/10012205/netstat-ccu3.nach.reset.txt)

**Comment by Wheymisterio** [comment]
![Screenshot 2022-11-15 123259](https://user-images.githubusercontent.com/23435719/201909588-4198bd6f-c638-4a08-815d-b8de85cdcc8a.jpg)

**Comment by blackbasket** [comment]
ich versteh's langsam auch nicht mehr... @thkl Thomas, hast du noch eine Idee?

**Comment by thkl** [comment]
Die Anzeige ob die Ports offen sind nehme ich aus den Firewall File. Es kann durchaus sein, das sich da was geändert hat und das Auslesen nicht mehr richtig funktioniert.  Das ist aber nur eine Info. Wenn die Ports freigegeben sind, müsste HomeKit mit der jeweiligen Instanz reden können. 

Ein nicht freigegebener Port äußert sich so, das HomeKit zwar die Bridge beim Einrichten sieht, aber sich nicht verbinden kann.

**Comment by Wheymisterio** [comment]
ich werd mein backup noch nicht einspielen will später erstmal mit dem reset versuchen ob ich am handy die bridge verbinden kann

**Comment by blackbasket** [comment]
Ok... aber das hattest du vorher schon mal probiert, oder? Das hatte ich zumindest immer gedacht...

**Comment by Wheymisterio** [comment]
ja das habe ich wie oben beschrieben immer probiert.
jetzt habe ich aber ein werksreset gemacht und homekit neu installiert und eine virtuelle taste angelegt und eine instanz.
aber da ich auf Arbeit bin und nur fernzugriff auf meinen PC habe konnte ich es nicht am Handy testen

**Comment by blackbasket** [comment]
Gut :)

**Comment by blackbasket** [comment]
Nein, das Problem ist ja schon lokal... andere Frage, ohne jetzt nochmal den ganzen Thread zu lesen... was nutzt du als Steuerzentrale?

**Comment by Wheymisterio** [comment]
ich habe eine CCU3 
mit RaspMatic Version 3.65.11.20221005

**Comment by blackbasket** [comment]
Danke :) aber ich meinte Apple HomeKit-Zebtrale ;)

**Comment by Wheymisterio** [comment]
mein iPad

**Comment by Wheymisterio** [comment]
@blackbasket @thkl 

iPad zurückgesetzt und jetzt kann ich die Bridge verbinden 
das ist wohl die Lösung

**Comment by blackbasket** [comment]
Danke, dann kannst du es auch schließen... iPad als Zentrale ist Mist... lieber HomePod (mini) oder am besten AppleTV per Ethernet angeschlossen ;)

**Comment by Wheymisterio** [comment]
Vielen Dank für die Hilfe einfach top Support hier 
 Ja dann muss ich mir mal eine andere Zentrale anschaffen
