### ISSUE TITLE
Einstellungen des HMIP-BWTH

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#579]
Guten Tag,

es geht um die Homematic-Thermostate BWTH.

In der CCU3 gibt es den Manuellen-Modus und einmal den Automatik-Modus. In der Home-App werden diese Punkte jedoch mit Automatisch und Heizung angezeigt. Kommen diese Bezeichnungen von Apple, oder hat das PlugIn Einfluss darauf?
Ich würde es für logischer finden, wenn es Automatisch und Manuell heißen würde.

Zudem kann man in der HomeApp noch „Aus“ auswählen. Was bewirkt diese Einstellung? In der CCU ändert sich dadurch m.E. nichts.

![B95E1503-66F2-4468-8B01-179B3503E8A6](https://user-images.githubusercontent.com/72799068/201609616-a77fa6f8-c496-499c-a67d-0a4ffb4b23dd.jpeg)
![4AA0B9C4-BDA2-469D-9A46-BBECD05A9C80](https://user-images.githubusercontent.com/72799068/201609620-80fa1efb-dd2d-41ac-9f11-94ae4ed010a1.jpeg)

Danke und lieben Gruß
gerd

**Comment by blackbasket** [comment]
Soweit ich weiß, kommt die Bezeichnung aus HomeKit. Aber guck mal ins Source File. Falls ich morgen Zeit habe, gucke ich auch mal.

**Comment by ChrWi** [comment]
Je nach Einstellung im Gerät taucht auch Kühlung auf. Ist nicht so eingängig, macht m.E. insgesamt nur in Kombination mit einem intelligenten Heiz-(Kühl)-System sind: Aus = Urlaub/Abwesend, Regelung Soll-Ist, etc.

**Comment by blackbasket** [comment]
also, ich hab's grad nochmal gecheckt... auch, wenn @ChrWi 's Antwort ja schon recht deutlich ist... das kommt mE von Apple... daher schlage ich vor, das Ticket zu schließen
