### ISSUE TITLE
Problem mit UI

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#58]
<img width="308" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81390010-0909c080-911b-11ea-8bd5-28a1819e1a4e.png">
Wenn man das Menü in der eingeklappten Variante nutzt, kann man die letzten Menüpunkte nicht sehen, geschweige denn erreichen.
Wünschenswert wäre zudem ein Punkt in den Einstellungen, dass man das Menü immer im eingeklappten Zustand nutzen möchte.

**Comment by roe1974** [comment]
hmmmmmm ... sieht bei mir so aus:
<img width="231" alt="Unbenannt" src="https://user-images.githubusercontent.com/30420568/81391134-dfea2f80-911c-11ea-9d87-10c724dd3a02.png">

**Comment by detLAN** [comment]
Mit zunehmendem Alter nutze ich bereits nicht mehr die Standardauflösung (1440 x 900) sonder lege mehr Wert auf größeren Text (1280 x 800). Ist aber egal, selbst bei Standardauflösung auf einem 13" MacBook und Safari im Vollbild gibt es bereits das Problem. Erkennt man gut an der Position des aufklappen Pfeil.

**Comment by roe1974** [comment]
ok ... habe hier 2560x1440 .... mit Zoom Faktor 150%
:-) :-P
Sehe also auch nix mehr *ggggg*

**Comment by roe1974** [comment]
habs gerade mit kleinem browser Fenster probiert ... stimmt... es fehlt der Scrollbalken :-/

**Comment by thkl** [comment]
ok ich schiebe dann demnächst das Menü etwas hoch.

![image](https://user-images.githubusercontent.com/884355/81416253-c01d3080-9149-11ea-93e7-8d9b608aef55.png)

mal sehen was damit dann bricht und kaputt geht
