### ISSUE TITLE
Homekit Geräte seit dem ios 16.1.1 update keine Funktion

### ISSUE THREAD

**Issue by nucomagpernozzoli** [thkl/hap-homematic#583]
Hallo Zusammen

Seit dem neuen Update von ios 16.1.1 funktionieren die Homekit Geräte nicht mehr mit der Hap-Homematic v. 0.0.14.
Zeitweise war der Dienst über den Webbrowser nicht mehr zur Verfügung und konnte nicht gestartet werden.

Habe folglich auch versucht eine neue Instanz hinzuzufügen, da kam vom Homekit nur die Meldung: "Gerät kann nicht hinzugefügt werden. Sicherheitsüberpüfung fehlgeschlagen oder Aktion unzulässig."

Hat jemand eine Idee an was das liegen könnte?

Danke, Nucom AG, Luca

**Comment by ChrWi** [comment]
Hallo,
da musst Du etwas mehr Infos geben: was läuft bei Dir jetzt auf 16.1.1 ? Das Endgerät, die Homekit Instanz? Funktionierte es noch auf 16.0? Sonstige Änderung am Netzwerk?

mein iPod läuft bereits auf 16.2 beta, die Geräte auf 16.1.1, auf 15.7 u.w. Aktuell bin ich total zufrieden, habe seit Monaten nichts mehr am Add-on geändert

**Comment by Dom-333** [comment]
Hi,
Habe das selbe Problem, HomePod 16.1; iPads iPhones 16.1.1
Mit HomePod 16.1. lief noch alles, nachdem die iPads und iPhones auf 16.1.1 sind keine Antwort. Musste auch Homeassistant aktualisieren aber dieser und die shellys funktionieren wieder.

**Comment by blackbasket** [comment]
@thkl

**Comment by thkl** [comment]
Ich hab das Problem aktuell nicht. 
Auf 16.1.1 funktioniert alles. 
Allerdings läuft bei mir die RM (aktuelle Version) in  einer ProxMox VM auf einen Intel System. 

Ich schau mal, dass ich ggf am Wochenende mal dazu komme, einen Raspberry mit einem Testsystem aufzusetzen.

**Comment by kampfschlonz** [comment]
Welche Raspberry Version hast Du im Einsatz? 3.65.11.20221005?

**Comment by Dom-333** [comment]
Ich habe gestern Nach noch alle HomePods zurückgesetzt und alle iPads und Apple TVs neugestartet. Gefrustet dann ins Bett und heute morgen lief dann alles wieder. Hat mir zwar die falschen Stati angezeigt, bsp. diverse Rollläden halb offen&gesschlossen; dabei waren diese oben aber es ging alles wieder.

**Comment by blackbasket** [comment]
Die falschen Stati habe ich schon immer...

**Comment by nucomagpernozzoli** [comment]
Bin naechste Woche wieder beim Kunde. Werde mich mit ausfuehrlichen Infos melden.
Danke fuer die antworten.

**Comment by ChrWi** [comment]
> Welche Raspberry Version hast Du im Einsatz? 3.65.11.20221005?

Ich nutze piVCCU3 mit 3.65.11

**Comment by nucomagpernozzoli** [comment]
Also ich hab momentan die Asus Thinkerboard s.r 2.0 im einsatz, aktuelle Firmware CCU3 3.65.11.20221005, 
iPad ist auf 16.1.1. Hap Homekit auf 0.0.14.

auf dem Pad , Im Homekit antwortet kein Gerät, Alle Geräte "keine Antwort", Ein neues Gerät hinzufügen bzw. über Bridge und den QR Code in das Homekit ist nicht möglich. Fehlermeldung: Unzulässige Aktion.

**Comment by nucomagpernozzoli** [comment]
Es hat geklappt! Musste alle bestehenden Bridges löschen und neu einlesen. 

Jedoch erhalte ich nicht den richtigen Status. Das liegt aber daran, dass die Leuchten DALI sind. 

Dali mit Deuta EnoCean Flex Controller über den CUXD eingebunden. Statusmeldungen gehen bis zu 5minuten, gibt's hier schon eine bessere Lösung?

**Comment by blackbasket** [comment]
Ich hab mal eine Frage, die nur im weitesten Sinne hier hin gehört... ich hoffe, ihr nehmt's mir nicht übel...

Seit iOS 16.0 (oder 16.1 - bin unsicher) antwortet Siri mir immer "das Element Licht ist an", "das Element Kaffeemaschine ist aus" etc...

ich habe seit ewigen Zeiten nichts verändert... als das plötzlich aufgetreten ist, war dazu im Netz nichts zu finden... ich kann mich nur daran erinnern, dass es an dem Tag war, als Apple über Seed den RC angekündigt hat... also der Mittwoch vor Verfügbarkeit des Updates über OTA...

**Comment by ChrWi** [comment]
@blackbasket Du meinst „Element“? Meine 16.2 klingt vernünftig bzw. wie ich es erwarten würde. Zuvor habe ich nicht drauf geachtet

**Comment by blackbasket** [comment]
Ok... ich denke, das wäre dir auf Dauer aufgefallen ;)

**Comment by ChrWi** [comment]
Das eigentliche Problem ist geklärt wenn ich das richtige sehe.
