### ISSUE TITLE
Homekit Addon blockiert HMIPServer (filedescriptor Verbrauch steigt stetig)

### ISSUE THREAD

**Issue by DasBlackfur** [thkl/hap-homematic#584]
Ich habe eine ziemliche komplexe Homematic (RaspberryMatic) Instanz in einer VM am laufen.
Diese hängt sich etwa alle 15 Tage auf und nur ein Neustart hilft um alles wieder in gang zu bekommen.

Ich hatte nun endlich Zeit mir den Fehler genauer anzusehen und bin dabei auf den HMIPServer Prozess gestoßen der stetig weiter Sockets öffnet bis er irgendwann sein Limit erreicht.
Um genau raus zu finden was für dieses Verhalten verantwortlich ist, habe ich die CCU im abgesicherten Modus gestartet (in welchem das Problem nicht auftritt) und Stück für Stück die Zusatzsoftware wieder gestartet.

Sobald das Homekit Addon gestartet wird steigt die Filedescriptor Auslastung alle 5 Minuten um 2 an.
Parallel werden im `hmserver.log` alle 5 Minuten `io.vertx.core.impl.BlockedThreadChecker WARN  [vertx-blocked-thread-checker] Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 9829 ms, time limit is 2000 ms` Nachrichten ausgegeben.

Ich hoffe mir kann jemand weiterhelfen, falls noch irgendwelche Logs benötigt werden ich habe die CCU mal auf "Alles Loggen" eingestellt.

**Comment by blackbasket** [comment]
Das Problem hatte ich vor ewigen Zeiten schon... da muss es hier ein Ticket zu geben... ich meine, wir hatten es gefixt, aber ich habe den täglichen Restart des hap trotzdem einfach drin gelassen... tut nachts ja nicht weh...

**Comment by ChrWi** [comment]
@DasBlackfur gibt es hier noch Bedarf? Falls ja dann bitte mehr Details zu Deinem System

**Comment by DasBlackfur** [comment]
> @DasBlackfur gibt es hier noch Bedarf? Falls ja dann bitte mehr Details zu Deinem System

Scheint sich komplett erledigt zu haben.
