### ISSUE TITLE
Raspberymatic auf neue Synology umgezogen hap-homematic funktioniert nicht mehr

### ISSUE THREAD

**Issue by twister9916** [thkl/hap-homematic#587]
Hallo,
ich nutze Raspberrymatic auf einem Synology NAS in einer Virtuellen Maschine.
Nun wurde das NAS von einem DS918+ auf ein DS923+ getauscht und auch die virtuelle Maschine neu aufgesetzt.
Von der Kompletten Raspberrymatic wurde ein Backup erstellt und auf dem neuen System das komplette Backup wieder eingespielt. Die IP Adresse der Raspberrymatic ist die gleiche. MAC Adresse wohl eine neue.
Es scheint alles zu funktionieren. Nur Hap Homematic nicht mehr. 
Wenn man unter Systemsteuerung der Raspberymatik auf den „Homkit“ Button geht stürzt hap homematic quasi ab oder startet nicht. Es wird dann nur ein leeres Browserfenster angezeigt und dass Safari auf die Seite nicht zugreifen kann.
Auch unter Zusatzsoftware Homekit Einstellungen komme ich nicht mehr auf irgendetwas drauf.
Die Geräte unter Homekit antworten alle nicht, also scheint das System nicht zu laufen.

Unter Watchdog Alarm steht nur dass hap-homematic restarted wurde.

Eine Neuinstallation von hap-homematic (also einfach drüber installieren) hat nix gebracht.
Die hap-homematic Version ist die letzte 0.014
Als Raspberrymatic läuft die Version  3.65.11.20221005

Der Rest funktioniert offenbar ohne Probleme

Wer kann helfen ?

Liebe Grüße
Rüdiger

--

**Comment by jb-home** [comment]
Hat die VM auf der Raspberrymatic und HAP-Homematic läuft denn Internetzugriff?

**Comment by twister9916** [comment]
> Hat die VM auf der Raspberrymatic und HAP-Homematic läuft denn Internetzugriff?

Ja, hat sie. Auf die Seite von „meine-Homematic“ komme ich aus der Anwendung drauf. 
Ich teste jetzt alles nochmal komplett runter fahren und neu starten.

**Comment by twister9916** [comment]
Alles runter fahren, inkl. Router Neustart etc. hat leider auch nichts genützt. Noch schlimmer ist, ich habe nun das alte NAS ans Netz gehangen und die Raspberrymatic darauf wieder gestartet. Leider hier genau das gleiche. 
Es wurde aber sonst nix im Netz verändert außer dem anderen NAS.
Beim Drücken auf „Homekit“ in der Systemsteuerung von Raspberrymatic blitzt ganz kurz eine Webseite auf man kann aber nicht lesen was da steht und dann kommt Seite nicht erreichbar. 
Die Homekit Zentrale ist ein Apple TV mit TV OS 16.1

**Comment by twister9916** [comment]
Wenn man hap-homematic unter Zusatzsoftware neu starten möchte kommt dieser Fehler:

Neustart wurde mit Fehlern abgeschlossen:

Please see /var/log/addon-uninstall-error.log on the central for more details.

Wie kann ich diese Datei einsehen ?

**Comment by twister9916** [comment]
Jetzt ist es mir sogar gelungen die kurz erscheinende Seite per Screenshot aufzunehmen. 
Da steht aber nur:

We will redirect you to the HAP-HomeMatic Configuration, if this will not work please user the link for :
und dann kommen zwei Hyperlinks
HTTP Version
HTTPS Version

**Comment by twister9916** [comment]
Ich bin immer noch etwas sprachlos. Aber das Problem scheint gelöst. 
Vielleicht kann mir aber mal jemand erklären warum das so ist.

Wenn ich zuerst die IP Adresse meiner Raspberrymatic mit https anstelle http aufrufe und dann auf den homekit button gehe funktioniert alles.

**Comment by jb-home** [comment]
Schau mal, ob du in HAP unter Internes -> Einstellungen das Häkchen bei HTTPS gesetzt hast.
Soweit ich mich erinnern kann, deaktiviert das den HTTP Zugang zu HAP.

**Comment by jb-home** [comment]
Gelöst? Falls ja, dann bitte schließen.
