### ISSUE TITLE
Mehrere Instanzen erforderlich?

### ISSUE THREAD

**Issue by murksmax66** [thkl/hap-homematic#589]

**Comment by murksmax66** [comment]
Moin,
ich habe die aktuelle Version (V0.0.63) als Addon (V0.0.14) auf einer Raspimatic (20221005) installiert. Ist schon klasse, wie das mit Home läuft - ein großes Lob an die Entwickler!
Habe aber ein kleines Problem:

Wenn sich ein weiterer Benutzer mit der Bridge verbinden will, kommt keine Verbindung zustande, obwohl alle erforderlichen Ports geöffnet sind. Die Bridge wird nicht gefunden.
Lädt man den Benutzer ein, kann er das Zuhause zwar betreten, aber alle darin befindlichen Geräte antworten nicht.

Wird eine neue HomeKit Instanz angelegt, kann sich der Benutzer dann mit dieser verbinden und auch alle Geräte bedienen. Leider muss man die Geräte manuell noch einmal in die neue Instanz kopieren (Gerät bearbeiten -> zu neuer Instanz hinzufügen), um sie dort auch zu finden. Und die Raumzuordnung muss man dann auf dem Apple Device nochmals manuell durchführen.

Die gleichen Schritte sind leider nochmals bei jedem weiteren Benutzer erforderlich.

Hat ein Benutzer mehrere Geräte (iPhone und iPad) unter seiner AppleID am laufen, klappt das auch mit einer Instanz.
Verwendete iOS-Versionen: 15.7.1 und 16.1.1

Grüße von der Nordsee
Max

**Comment by jb-home** [comment]
Jede Bridge lässt sich nur mit einer Apple-ID verbinden.
Zum Teilen lädt man die anderen Benutzer dann in das Home der Apple-ID ein.
So ist es zumindest von Apple gedacht.

Ein Gerät mit mehreren Brigdes zu Verbinden und die dann jeweils einzeln mit den Apple-IDs zu verbinden macht eigentlich kaum Sinn. Da du pro Apple-ID dann auch einen eigenen HUB bräuchtest und die Geräte von extern steuern zu können.

**Comment by murksmax66** [comment]
Hi
vielen Dank für die Rückmeldung!

Das mit dem Teilen hatte ich auch versucht, indem ich meine Frau eingeladen habe. Aber auf ihrem Telefon musste dann auch noch einmal die Pin eingegeben werden. Und damit ist das Telefon dann wieder in einen Timeout gerannt :(

Ich habe jetzt drei Instanzen (default ->ich, meine Frau und meine Tochter), damit jeder steuern kann. Von außen geht nicht, da kein Apple HUB vorhanden. Das geht nur über VPN mit der WebUI. Vielleicht über VPN zu Fritz!Box? Mal probieren...

Wünsche einen geruhsamen Jahreswechsel!
Max

**Comment by jb-home** [comment]
Beim Teilen muss keine PIN eingegeben werden. Ggf. hat das Teilen dann nicht richtig funktioniert. Da schein Apple Momentan eine Baustelle zu haben.
Beim Teilen bekommt der eingeladene genau das was auch in deinem Home drin ist. Da sind keine PINs mehr nötig. Wenn du den einmal gepaired hast, kommt das auch bei allen mit denen du Teilst.

Bei VPN wird das Problem von Multicast wohl der springende Punkt sein. Das diese Pakete nicht über die VPN gehen. Das ist aber ein ganz anderes Thema dann.

**Comment by murksmax66** [comment]
Hm, ok, werde ich dann wohl nochmal probieren müssen. Werde ich meiner Frau noch einmal das Handy klauen und sie aus dem Home rauslöschen und von meinem aus einladen müssen ... 
Wird heute aber nix, muss gleich nochmal den Flaggenmast legen und den Weihnachtsstern entwirren müssen, der hat sich heute bei dem Wind total vertörnt:)

**Comment by Raab1488** [comment]
Hallo,

hat sich da eine Lösung schon aufgetan?

Ich habe das selbe Problem.
Habe meine Frau eingeladen. Sie hat ca zur hälfte der Geräte keine Antwort, andere Hälfte funktioniert einwandfrei.

**Comment by murksmax66** [comment]
Moin,
wenn es denn mal so einfach wäre ...

<img width="545" alt="Bildschirmfoto 2023-01-16 um 07 58 13 png" src="https://user-images.githubusercontent.com/111336739/212617175-6fb28662-38f1-4769-a895-68e76f296856.png">
Bei iOS 16.2 scheint Apple an der Schnitt etwas geändert zu haben wenn ich jetzt jemand einladen will, kann ich die Person nicht mehr auswählen/eingeben. Jetzt sagt Apple mir, dass ich eine Steuerzentrale wie einen ApplePod oder AppleTV benötige, um jemanden einzuladen ...
<img width="574" alt="Bildschirmfoto 2023-01-16 um 07 58 52 png" src="https://user-images.githubusercontent.com/111336739/212617352-14d9146f-19d5-4531-8b1b-ba87c5eb4de4.png">

Direkt kann ich Familienangehörige nicht mehr einladen! Damit bin ich wieder bei der Frage mit den mehreren Instanzen :(

**Comment by murksmax66** [comment]
Moin,
nach dem letzten Update von iOS auf 16.3.1 hat dich da nix geändert - auch jetzt kann man keinen andere Benutzer mehr in das Zuhause einladen. Man ist noch immer gezwungen, für jeden Benutzer eine Instanz anzulegen. Das ist leider verdammt aufwendig, da alle Geräte mehrfach erstellt werden müssen :(
