### ISSUE TITLE
Rauchmelder schlagen alarm

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#59]
Einige Rauchmelder (HM-Sec-SD-2) im Haus (2 bis 3 von 9, immer die gleichen) schlagen unkontrolliert alarm. In der Home App gibt es dazu keine Meldung. Auch die CCU schickt keine E-Mail, die eigentlich bei Rauch erkannt kommen müsste. Ich hab dann alle Rauchmelder einmal durchgepustet und einen Selbsttest durchgeführt. Nächster Tag wieder alarm im Haus. Bekomme schon ärger, dass ich "meine Technik" nicht im Griff hab. CCU neu gestartet, einen Tag später wider alarm. Da ich nichts an der CCU Konfiguration geändert hatte, hab ich die Raumelder mal aus dem HAP gelöscht - jetzt ist wieder Ruhe.

**Comment by thkl** [comment]
Löst der Rauchmelder selber aus oder denkt nur HomeKit das er ausgelöst hat ?

**Comment by detLAN** [comment]
Der Rauchmelder löst selbst aus, HomeKit und CCU geben keinen Hinweis.

**Comment by thkl** [comment]
Strange ! Zumal der Rauchmelder, außer Install_Test, keinerlei beschreibbare Datenpunkte hat.

![image](https://user-images.githubusercontent.com/884355/81397599-f47ff500-9127-11ea-8ef6-1a2012fd1439.png)

Und INSTALL_TEST beschreibe ich in keinem Fall.

**Comment by detLAN** [comment]
Wie geschrieben ich habe die jetzt erst einmal im HAP wieder gelöscht, damit der Hausfrieden wieder einkehrt. Werde die Teile aber nach ein paar Tagen testweise wieder hinzufügen. Für mich sind die eigentlich nicht wichtig, genauso wie die Alarmsirene, da ich bei Auslösung Push und E-Mail erhalte.
HomeKit ist für mich eigentlich nur interessant, da ich so Siri meine Wünsche kundtun kann. Funktioniert aber auch nur mittelprächtig. Im Auto unterwegs "Status Toranlage" bekomme ich die Richtige Antwort, aber "Toranlage schalten" meint Siri dies nicht zu können, da der Fernzugriff nicht konfiguriert sei.

**Comment by mike4president** [comment]
Das Problem hatte ich auch als ich die Feuermelder über Home Assistant in HomeKit eingebunden habe. Scheint also am Gerät zu liegen. Nur dass die Geräte da nur in HomeKit Alarm ausgelöst haben allerdings glücklicherweise nicht wirklich einen Ton von sich gaben. Ich binde meine die Tage auch mal in HAP ein und schaue was passiert

**Comment by detLAN** [comment]
Rauchmelder auf frischem System eingerichtet und heute wieder Alarm. Hab Backup (Datensicherung) ohne Rauchmelder wieder eingespielt. Aus meiner Sicht kann dies hier geschlossen werden, ich brauch die Teile genauso wenig wie die Alarmsirene in HK.

**Comment by thkl** [comment]
Aber mal zur Info:

Die Dinger lösen sporadisch aus sobald sie in HomeKit sind ?

**Comment by roe1974** [comment]
Also ich kann mir nicht vorstellen, dass der Rauchmelder durch etwas anderes als eben Rauch ausgelöst werden kann .... zumal wie Thomas oben schon geschrieben hat, das Ding nur lesende Datenpunkte hat .... sicher, dass da nicht anderwertig der "Wurm" drinnen ist ? ;-)
Sind die in einer Gruppe in der CCU ?

**Comment by thkl** [comment]
Ok ich werde auf jeden Fall noch zu 100% sicherstellen, das das Plugin nicht auf ReadOnly Datenpunkte schreibt. Weder wenn es per AccessLevel verboten ist noch per Schnittstelle. Switche halten sich derzeit schon an das Accesslevel. Allerdings sollte auch Rega das ignorieren bzw. die Schnittstelle dahinter schon gleich noch ...

**Comment by detLAN** [comment]
>Die Dinger lösen sporadisch aus sobald sie in HomeKit sind ?

Ja, wenn in HK, dann lösen die sporadisch aus - aber nicht alle.

> Also ich kann mir nicht vorstellen, dass der Rauchmelder durch etwas anderes als eben Rauch ausgelöst werden kann .... zumal wie Thomas oben schon geschrieben hat, das Ding nur lesende Datenpunkte hat .... sicher, dass da nicht anderwertig der "Wurm" drinnen ist ? ;-)

Auffällig ist, dass die Teile nur sporadisch auslösen, wenn sie in HK sind. Nehme ich sie raus sind sie wie eh und je ganz ruhig. Bekommen einmal im Jahr ihre Wartung - Staub ausblasen und Funktionstest.

> Sind die in einer Gruppe in der CCU ?

Habe zwei Gruppen in der CCU eingerichtet. Vielleicht interessant, es waren immer nur Rauchmelder der ersten Gruppe (also die Gruppe die ich als erstes in der CCU definiert habe), die sporadisch ausgelöst haben.

**Comment by mike4president** [comment]
Hallo, also ich habe meinen Feuermelde nun seit 2 tagen eingebunden und hatte noch keinen Fehlalarm.

**Comment by detLAN** [comment]
> Hallo, also ich habe meinen Feuermelde nun seit 2 tagen eingebunden und hatte noch keinen Fehlalarm.

Welche Rauchmelder setzt Du ein HM oder HmIP?

**Comment by roe1974** [comment]
und verwendet @mike4president Gruppen ?

**Comment by mike4president** [comment]
@detLAN : HmIP

@roe1974 : Nein

**Comment by detLAN** [comment]
> @detLAN : HmIP
> 
> @roe1974 : Nein, nur im Zusammenhang mit der Heizungssteuerung

Damit entspricht die Konfiguration in beiden Fällen nicht der meinen.
Bei mir sind es HM Rauchmelder (HM-Sec-SD-2) und diese in zwei Gruppen eingeteilt.

**Comment by mike4president** [comment]
Wie ist hier eigentlich der Stand. Lösen sie immer noch Alarm aus?

**Comment by detLAN** [comment]
Ich probier es zum Wohle des Hausfriedens lieber nicht mehr aus - hab die Dinger hier einfach nicht eingerichtet und gut.

**Comment by mike4president** [comment]
Ok... ich kaufe mir demnächst noch 2 weitere IP Rauchmelder und richte auch mal eine Gruppe ein. Das hilft dir mit deinen zwar nicht weiter, aber dann kann man das zumindest für die IP Teile ausschließen
