### ISSUE TITLE
Instanz nicht veröffentlichtbar

### ISSUE THREAD

**Issue by jvnvsii** [thkl/hap-homematic#590]
Hallo,

Ich kann leider keine Instanz eines bestimmten Raumes hinzufügen. Bei allen anderen Räumen hat es funktioniert, nur bei diesem nicht.
Auch wenn ich eine neue Instanz des selben Raumes erstelle, kann ich diese nicht veröffentlichen und somit die Geräte des Raumes zu HomeKit hinzufügen.

Liegt das Problem in der Konfiguration oder ist es vielleicht ein Bug?

Hier der Log noch beim Versuch es hinzuzufügen

[hap-homematic-log-wohnen-hinzufügen.txt](https://github.com/thkl/hap-homematic/files/10200307/hap-homematic-log-wohnen-hinzufugen.txt)

**Comment by jb-home** [comment]
Besteht das Problem noch?
Habe im LOG jetzt nichts gesehen, dass er die Räume 'Wohnen' oder 'wohnen neu' nicht veröffentlichen wollen würde.
