### ISSUE TITLE
iOS 16.2 Architektur Upgrade

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#592]
Hallo alle zusammen
Hat schon jemand in iOS 16.2 das Architektur Upgrade durchgeführt und kann bestätigen, dass HAP nachher noch funktioniert ?
lg Richard

**Comment by gerd2005** [comment]
Ich habe alle Geräte auf 16.2 aktualisiert. Wie kann ich dieses HomeKit-Update aktivieren?

**Comment by roe1974** [comment]
In der Home App -> rechts oben auf die "..." -> dann "Einstellungen des Zuhauses" -> dann auf "Softwareupdate" -> dort wird es ganz oben angeboten ...

**Comment by Hasenpups** [comment]
Die Thermostate funktionieren bei mir weiterhin. Die Lampen allerdings sind nicht erreichbar :(

**Comment by blackbasket** [comment]
Was sind es für Lampen bzw Aktoren, die du einsetzt?

**Comment by gecko74** [comment]
Ich habe auch das Upgrade durchgeführt und bei mir gehen die HmIP-PSM nicht mehr.
Die HmIP-STHD etc gehen weiterhin.

**Comment by Jokerx3** [comment]
Bei mir funktioniert nach dem Home-Upgrade alles wie bisher (BWTH, BROLL, PSM, BSM).

**Comment by kleenebrooker** [comment]
> Bei mir funktioniert nach dem Home-Upgrade alles wie bisher (BWTH, BROLL, PSM, BSM).

Du hast aber nicht zufällig eine Idee, woran es liegen kann, dass meine Instanzen / Bridges eingerichtet, die Geräte darin aber nicht durchgereicht werden?

**Comment by Jokerx3** [comment]
> 

Leider nein. Wollte nur die Erfahrung teilen, dass es reibungslos mit genannten Geräten funktionieren kann.

**Comment by kevbes** [comment]
> > Bei mir funktioniert nach dem Home-Upgrade alles wie bisher (BWTH, BROLL, PSM, BSM).
> 
> Du hast aber nicht zufällig eine Idee, woran es liegen kann, dass meine Instanzen / Bridges eingerichtet, die Geräte darin aber nicht durchgereicht werden?

**Comment by kleenebrooker** [comment]
> > > Bei mir funktioniert nach dem Home-Upgrade alles wie bisher (BWTH, BROLL, PSM, BSM).
> > 
> > 
> > Du hast aber nicht zufällig eine Idee, woran es liegen kann, dass meine Instanzen / Bridges eingerichtet, die Geräte darin aber nicht durchgereicht werden?
> 
> Info/Beobachtung: Bridges konnte ich einrichten, zunächst keine Geräte in Homekit mehr gesehen. Dann alles komplett neu eingerichtet (in Homekit: Bridges mit (wieder) neu angelegten Räumen), diese wieder alle leer. Aber dafür alle Geräte in Homekit vorhanden in "Standardraum"! Von dort konnte ich sie dann manuell in die leeren aber eigentlichen Räume ummelden. Hth.

oh Mann … DANKE! Das war es … ich Depp bin nicht auf die Idee gekommen, im Standardraum nachzuschauen. 🤦🏻‍♂️

**Comment by ChrWi** [comment]
> Bei mir funktioniert nach dem Home-Upgrade alles wie bisher (BWTH, BROLL, PSM, BSM).

So auch bei mir

**Comment by jb-home** [comment]
Bitte schließen.
