### ISSUE TITLE
Benachrichtigen bei Hmip Tür-/Fenstersensor

### ISSUE THREAD

**Issue by Sheldor81** [thkl/hap-homematic#60]
Hallo,

erst möchte ich mich mal für das tolle Plugin bedanken. Bin bisher sehr begeistert davon.
Aktuell nutze ich noch die Homebridge will aber nach und nach die Geräte über dieses Modul in HomeKit einbinden.

Heute ist mir aufgefallen das wenn ich mich über die HomeApp über das öffnen oder schließen einer Tür/Fenster benachrichtigen lassen möchte, bekomme ich nur einmal beim öffnen eine Benachrichtig.
Bei den Sensoren die über Homebridge eingebunden sind bekomm ich immer eine Nachricht beim öffnen und schließen, so hätte ich es auch gerne. Kann man das noch irgendwie in HAP-HomeMatic einstellen.

Gruß
Michael

**Comment by thkl** [comment]
Welche Serviceclass wird da verwendet und was für ein Homematic Gerät ?

**Comment by Sheldor81** [comment]
Es handelt sich um den Sensor HMIP-SWDO und eingebunden ist er als HomeMaticWindowAccessory.

**Comment by thkl** [comment]
Ok, kann ich nachvollziehen. Das ist ein Timing problem. CurrentState muss nach TargetState gesetzt werden. Derzeit ist es andersrum. Ich fix das.

**Comment by Sheldor81** [comment]
vielen Dank.

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/81436932-96283600-916a-11ea-9420-eda053ec5b25.jpeg)

**Comment by Sheldor81** [comment]
Genau so sollte es sein. Werde es wenn du es gefixt hast direkt mal testen

**Comment by thkl** [comment]
wird mit .39 dann gefixt

**Comment by Sheldor81** [comment]
vielen Dank

**Comment by Sheldor81** [comment]
steht es gleich schon zum updaten zur Verfügung?

**Comment by thkl** [comment]
nein, ich weiss noch nicht wann ich die Version update. Ist noch zu wenig geändert zur vorherigen ;)

**Comment by Sheldor81** [comment]
Ok, wünsche dir noch einen schönen Abend

**Comment by roe1974** [comment]
thomas .... kann das auch der grund bei der sirene sein ? ... dort kommen die status änderungen in HK sehr sporadisch ....

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/81438795-a42b8600-916d-11ea-9325-c6bbb3838d7f.png)

Yep 🤓

**Comment by Samfox2** [comment]
Fixt das vielleicht auch das Eve logging bei dem Sensor?

**Comment by Sheldor81** [comment]
Vielleicht reicht es ja dann doch für ein zeitnahes Update, wenn damit noch mehr Probleme gelöst werden können.

**Comment by thkl** [comment]
Nope, hier weiss ich nicht woran das liegt. Das Log wird geschrieben (auch in das passende File). Aber Eve behauptet keine Daten zu haben

**Comment by Samfox2** [comment]
Ah schade. Funktioniert aber bei den normalen Homematic Sensoren (und ging auch früher mal bei den iOS).

**Comment by thkl** [comment]
ja bei "normalen" Contact Sensors geht das ... da wird auch das gleiche File geschrieben.
Aber sobald man Window oder Door nimmt funktioniert zwar noch die Anzahl der Öffnungen aber die History bleibt leer.

**Comment by Samfox2** [comment]
Ich hab meine normalen Contact Sensors auf "anzeigen als Tür" eingestellt, da funktioniert das. Ist das nicht das gleiche Prinzip auch bei den IPs?

**Comment by thkl** [comment]
Ach ? Und bei den IP Sensoren gibt es keine History ? Also das ist intern wurschd ob IP oder nicht .. das ist alles das gleiche Service File

**Comment by Samfox2** [comment]
Je genau, das ist ja das merkwürdige. Kann das denn noch jemand nachvollziehen oder ist das nur bei mir?

**Comment by thkl** [comment]
Bei mir ist das so (egal ob HM oder HMIP Kontakte) sobald der Kontakt als Window definiert wird, geht die History nicht mehr. Stelle ich den auf Contact um ist sie wieder da (und auch die Events, die während der Window Darstellung "verloren gegangen" sind.

**Comment by Samfox2** [comment]
Also HM funktionieren bei mir alle mit logging, egal ob als contact/window oder door. Früher ging das auch mit den HMIPs. Nur nochmal zur Sicherheit: ich definiere die Darstellung nur in der Home App, nicht in der config. Dort ist bei window/door nichts eingetragen.

**Comment by Samfox2** [comment]
![954EF44C-934C-4D5E-91B3-89DCC1EACC68](https://user-images.githubusercontent.com/11883712/81442061-2ff3e100-9173-11ea-975a-124c96550ebd.png)

**Comment by thkl** [comment]
Ne ich rede von HomeMaticDoorAccessory vs HomeMaticContactSensorAccessory

**Comment by Samfox2** [comment]
Gut, ich nicht 😀

**Comment by thkl** [comment]
aber im HomeMaticContactSensorAccessory ist es auch egal ob ein HM oder HMIP Gerät da geht die History bei Beiden

**Comment by Samfox2** [comment]
Bei mir nicht mehr beim HMIP.

**Comment by Samfox2** [comment]
Wenn das jedoch bei dir funktioniert, dann muss es ja irgendwie an meinem Setup liegen.

**Comment by Samfox2** [comment]
Ja, nur das loggen nicht.

**Comment by Samfox2** [comment]
![37B963D1-C3FC-4DEF-B8E8-175EBAA3C716](https://user-images.githubusercontent.com/11883712/81442399-d50eb980-9173-11ea-8072-63f842aaae55.png)

**Comment by thkl** [comment]
Das hier ist mein Test Kontakt HMIP-SWDO-I

![image](https://user-images.githubusercontent.com/884355/81442729-7269ed80-9174-11ea-9005-a19639c8d30c.jpeg)

**Comment by Samfox2** [comment]
Ja, leider 😀 funktioniert es bei dir. Liegt also definitiv auf meiner Seite. Ich glaub ich schmeiße den Sensor einfach raus.

**Comment by thkl** [comment]
Wenn Du ihn löschst wird auch das History File gelöscht, maybe das ist korrupt und es geht dann wieder

**Comment by Sheldor81** [comment]
![137C612D-B464-4D42-BD14-C8201F87FA33](https://user-images.githubusercontent.com/37243683/81443166-2f5c4a00-9175-11ea-9349-348254db6d0e.jpeg)

**Comment by Sheldor81** [comment]
So sieht es bei mir über HAP aus

**Comment by thkl** [comment]
Ja, Door und Window können scheinbar keine History, da hängt das Diagramm auch an "Anzahl geöffnet" und nicht an der Position

**Comment by Sheldor81** [comment]
Und so mit Homebridge 

![65B2CCB4-8C38-4FCA-A397-0491D95A31AE](https://user-images.githubusercontent.com/37243683/81443261-67fc2380-9175-11ea-9eae-6ca969b66901.jpeg)

**Comment by thkl** [comment]
Siehe oben, das eine ist ein HomeKit Fenster, das andere ein Kontakt. Der Kontakt kann History .. das Fenster nicht

**Comment by Sheldor81** [comment]
wieder was gelernt

**Comment by thkl** [comment]
ich mach das mal hier zu, is ja kein Chat
