### ISSUE TITLE
keinen zugriff von extern

### ISSUE THREAD

**Issue by Tom251236** [thkl/hap-homematic#601]
Hallo 
ich versuche von extern auf den hap zuzugreifen doch dies funktioniert nicht. Solange ich im Wlan bin funktioniert alles sobald ich über LTE gehe geht nichts mehr

**Comment by blackbasket** [comment]
Hallo @Tom251236 ... Welche Steuerzentrale (Apple, nicht Homematic) nutzt du? Das Problem kann eigentlich nicht vom hap kommen.

LG,
Marcel

**Comment by Tom251236** [comment]
hi  Marcel

von apple habe ich nur ein iphone und über dieses und der home app wollte
ich es steuern

gruß Tom

blackbasket ***@***.***> schrieb am Mi. 11. Jan. 2023 um
14:29:

**Comment by blackbasket** [comment]
Dann ist das Verhalten, wie erwartet... du benötigst ein AppleTV (beste Wahl, wenn verkabelt) oder HomePod(mini), dass als Zentrale fungiert... dann kannst du auch Remote zugreifen...

**Comment by Tom251236** [comment]
mhh

alles klar danke für die Antwort

gruß thomas

blackbasket ***@***.***> schrieb am Mi. 11. Jan. 2023 um
14:59:

**Comment by blackbasket** [comment]
Gerne :) schließt du das Ticket bitte?

**Comment by Tom251236** [comment]
Danke
