### ISSUE TITLE
HAP Bridge lässt sich in HomeKit nicht hinzufügen

### ISSUE THREAD

**Issue by s1udge0706** [thkl/hap-homematic#602]
Ich habe mein HomeKit auf die neue iOS 16.2 Architektur hochgezogen und seither sind meine CCU3/HAP Geräte nicht mehr verfügbar.

HAP habe ich bereits neu aufgesetzt (sogar neu installiert) und eine neue Instanz erstellt.
Beim Hinzufügen als Bridge in HomeKit erfolgt allerdings ein Fehler. HomeKit sagt hier
` "Unbekannter Fehlercode: NSCocoaErrorDomain : 1560"`

Bei neuen HAP Instanzen tritt der selbe Fehler auf.

Ich weiß allerdings nicht, ob das überhaupt am HAP Service liegt, oder nicht direkt an HomeKit.

**Comment by s1udge0706** [comment]
Ich bin etwas weiter. 

Ich habe meine CCU3 komplett zurück gesetzt und die Geräte nach und nach bei angelernt. 

Geht alles super, bis man die HMIP-PSM Zwischenstecker einbinden will. Danach kommt der Fehler. 

Wird also an HomeKit liegen, dass die Messwerte (Leistung, Strom, etc.) nicht mehr mit eingebunden werden können.  

"Einfache" Sachen wie Türkontakte funktionieren. Auch nur der Schaltteil der HMIP-PSM Zwischenstecker (Kanal 3 ist das glaube ich) würde funktionieren. 
Allerdings bräuchte ich bei meiner Automation die Leistungsmesswerte (= Trigger für Waschmaschine ist fertig). 



Ich warte mal ab was zukünftige Updates bringen.

**Comment by ChrWi** [comment]
@s1udge0706 wie sieht es bei Dir mit 16.4 aus? Siehe #621

**Comment by ChrWi** [comment]
@s1udge0706 @jhk3 wie sieht es bei Euch aus? Würde hier als Duplikat zu #621 aber zumachen

**Comment by s1udge0706** [comment]
@ChrWi  ich nutze den Kanal 6 nicht mehr. Für die Leistungsmessung bin ich seit den Problemen im Januar auf Shelly PM gewechselt und mache das ganze über einen MQTT Broker.

Ich nutze lediglich noch die Türkontakte von HM IP über die HAP Bridge.

Für mich kann das Thema also geschlossen werden :)
