### ISSUE TITLE
Daten werden nicht von Homekit an Geräte übertragen

### ISSUE THREAD

**Issue by mcdjhomer** [thkl/hap-homematic#609]
Wenn ich per Homekit am Handy oder Mac die Temperatur ändere, werden die Daten zwar am Thermostat geändert, aber NICHT 
an den einzelnen Heizkörpern.

Hat bisher immer geklappt und ich hab auch nicht geändert (ausser ein update der Raspberrymatic evl.)

Kann da jmd was zu sagen?

**Comment by blackbasket** [comment]
Das klingt doch nach einem RM-Problem... wenn die Temperatur am Thermostat geändert wird, scheint die Kommunikation zwischen HomeKit und RM intakt zu sein...

**Comment by mcdjhomer** [comment]
> Das klingt doch nach einem RM-Problem... wenn die Temperatur am Thermostat geändert wird, scheint die Kommunikation zwischen HomeKit und RM intakt zu sein...

Nee Idee was es sein könnte?
