### ISSUE TITLE
Variablen Trigger

### ISSUE THREAD

**Issue by Sheldor81** [thkl/hap-homematic#61]
Wie funktioniert das mit dem Trigger um die Variablen zu aktualisieren.

**Comment by thkl** [comment]
Da ich keine Events aus der CCU über das Ändern einer Variable bekomme, gibt es einen Workaround über eine virtuelle Taste.

Ein Programm in der CCU muss eine Virtuelle Taste drücken wenn die Variable aktualisiert wurde. In der WebUI muss der Datenpunkt der Taste eingetragen werden, Beispiel:
```
BidCos-RF.BidCoS-RF:49.PRESS_SHORT
``` 
wenn Key 49 gedrückt wird. Dieser Event löst dann ein Abfragen aller Variablen in der CCU aus.

**Comment by Sheldor81** [comment]
Haben den Taster wie beschrieben eingefügt, aber leider aktualisiert sich der Wert nicht Automatisch 
![3BDD4426-DDDE-4EB0-BD77-E264772A0B01](https://user-images.githubusercontent.com/37243683/81467877-e7bcd900-91db-11ea-8b09-81e38034a6d0.jpeg)

**Comment by Sheldor81** [comment]
![CA7581A5-073D-47B8-8212-FD68FE399AD0](https://user-images.githubusercontent.com/37243683/81467904-11760000-91dc-11ea-8070-be6e334518e4.jpeg)

**Comment by Sheldor81** [comment]
Habe es, hat wohl an der groß und Kleinschreibung gelegen. Hatte alles klein, das war wohl falsch.

**Comment by thkl** [comment]
Ja da ich einen Stringvergleich machen ist das schon wichtig ;)
Ich wollte irgendwann mal eine Validierung für Datenpunkte einbauen. Die braucht es ja auch für den Garagentoröffner ...
