### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by inmarx** [thkl/hap-homematic#613]
Hallo,
Ich bin Neuling, ich versuche verzweifelt das Add-on zu installieren. Über die GUI bekomme ich es nicht hin, per ssh bekomme ich folgende Meldung:

root@ccu3-webui:/usr/local/addons/hap-homematic# npm i hap-homematic
npm WARN tar zlib: incorrect data check
npm WARN tarball tarball data for tr46@https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz (sha512-N3WMsuqV66lT30CrXNbEjx4GEwlow3v6rr4mCcv6prnfwhS01rkgyFdjPNBYd9br7LpXV1+Emh01fHnq2Gdgrw==) seems to be corrupted. Trying again.
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN tarball tarball data for tr46@https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz (sha512-N3WMsuqV66lT30CrXNbEjx4GEwlow3v6rr4mCcv6prnfwhS01rkgyFdjPNBYd9br7LpXV1+Emh01fHnq2Gdgrw==) seems to be corrupted. Trying again.
npm WARN tar zlib: incorrect data check
npm WARN tarball tarball data for googleapis@https://registry.npmjs.org/googleapis/-/googleapis-110.0.0.tgz (sha512-k6de3PGsdFEBULMiFwPYCKOBljDTDvHD3YGe/OFqe8Ot0lYQPL8QV1qjxjrPWiE/Ftf0Ar2v4DNES66jLfSO7w==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for googleapis@https://registry.npmjs.org/googleapis/-/googleapis-110.0.0.tgz (sha512-k6de3PGsdFEBULMiFwPYCKOBljDTDvHD3YGe/OFqe8Ot0lYQPL8QV1qjxjrPWiE/Ftf0Ar2v4DNES66jLfSO7w==) seems to be corrupted. Trying again.
npm notice
npm notice New major version of npm available! 8.19.2 -> 9.4.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.4.0
npm notice Run npm install -g npm@9.4.0 to update!
npm notice
npm ERR! code ENOENT
npm ERR! syscall stat
npm ERR! path /tmp/npm-cache/_cacache/content-v2/sha512/37/75/8cb2ea95eba953df40ab5cd6c48f1e06130968c37bfaaebe2609cbfaa6b9dfc214b4d6b920c857633cd05877d6ebecba57575f849a1d357c79ead86760af
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, stat '/tmp/npm-cache/_cacache/content-v2/sha512/37/75/8cb2ea95eba953df40ab5cd6c48f1e06130968c37bfaaebe2609cbfaa6b9dfc214b4d6b920c857633cd05877d6ebecba57575f849a1d357c79ead86760af'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR! /tmp/npm-cache/_logs/2023-01-26T15_03_21_639Z-debug-0.log
root@ccu3-webui:/usr/local/addons/hap-homematic#

Habt ihr eine Idee?
Danke!

**Comment by ChrWi** [comment]
Hallo @inmarx,
welche Hardware nutzt Du für die CCU?
Hast Du einen aktuellen Software Stand?
Hast Du Deine SD Karte mal auf Fehler kontrolliert?
