### ISSUE TITLE
Geräte nicht mehr erreichbar in Homekit "keine Antwort" 

### ISSUE THREAD

**Issue by wischli** [thkl/hap-homematic#615]
**Please describe your problem**
* Alle Devices sind über Nacht nicht mehr in Homekit erreichbar "Keine Antwort"
* In pocketControl funktioniert alles einwandfrei, scheint also ein Plugin Problem zu sein
* Es wurden keine Änderungen vorgenommen (z.B. Software Updates, Gerätwechsel)

Dies ist das erste Mal, dass wir ein Problem mit dem Plugin haben seit der Installation vor ca. 3 Monaten. Bisher lief alles problemlos. Ich würde gerne wissen, nach welchen bekannten Zeilen man in den Logs gucken sollte, und welche allgemeinen Lösungsvorschläge existieren.

Hier mein Setup
* CCU3 auf neustem Stand `3.67.10`, einzelne Components auf neustem Stand
* Plugin läuft direkt auf der CCU mit aktuellster Version `0.0.63`
* iOS auf neustem Stand `16.3.0` 

**What happens**
* Mehrere Restarts der Apple Geräte, CCU3 und HAP-Homeatic haben keinerlei Änderung bewirkt
* Dasselbe gilt für CCU Cache resets im Plugin

**What should be happend**
* Devices sollten ansprechbar sein

**Steps to reproduce this issue**
Soweit ich das beurteilen kann, stechen 2 Arten von Error logs heraus, siehe Logfile im Anhang. Leider kann ich nicht sagen, ob die Voltage Logs vorher schon existierten. Mir liegen keine Logs vor dem Problem vor.

```
[Mon Feb 13 2023 09:18:51 GMT+0100 (CET)] debug - [HAP Server] [RPC] CCU Response for init at HmIP-RF. with command http://127.0.0.1:9875,HAP_HmIP-RF. ...Value ("") Error : (null)
```
```
[Mon Feb 13 2023 09:21:26 GMT+0100 (CET)] debug - [HAP Server] [RPC] event for HmIP-RF.00161D89AF7BD5:0.OPERATING_VOLTAGE_STATUS with value 0
```
[hap-homematic-log_.txt](https://github.com/thkl/hap-homematic/files/10720123/hap-homematic-log_.txt)

**Comment by ChrWi** [comment]
Hallo @wischli,
iOS 16.3 gibt es noch keine 3 Monate. Auf welcher Hardware läuft Dein Apple Home?
Sind weitere Bridges / Geräte neben Hap-homematic installiert? Lese einiges an Eve im Log…
Welches HmIP Gerät gibt den o.g. Voltage-Status aus?

**Comment by wischli** [comment]
**Update**: Nachdem ich meine Homekit Basis (Apple TV 4k 1st gen) manuell aktualisiert habe von `16.3.1` auf `16.3.2` läuft wieder alles wie am Schnürchen.

Der Vollständigkeit halber hier die Antworten zu deinen Fragen:

> Hallo @wischli, iOS 16.3 gibt es noch keine 3 Monate. 

Das ist wahr. Habe damit implizit sagen wollen, dass ich seit der Initialisierung keine Probleme hatte und aktuell auf `iOS 16.3` mit meinem iPhone bin.

> Auf welcher Hardware läuft Dein Apple Home? 

Apple TV 4K 1st gen.

> Sind weitere Bridges / Geräte neben Hap-homematic installiert? 

* Homebridge mit Homebridge UniFi Protect, hatte ich aber direkt deaktiviert.

> Lese einiges an Eve im Log… 

* Habe keine Eve Geräte. Erscheinen nach dem Fix jetzt auch nicht mehr in den Logs

> Welches HmIP Gerät gibt den o.g. Voltage-Status aus?

Kann ich nicht genau sagen, muss ich meinen Elektriker mal zeigen.
