### ISSUE TITLE
Wetterstation HmIP-SWO-B wird nicht hinzugefügt

### ISSUE THREAD

**Issue by mbgong** [thkl/hap-homematic#619]
Ich möchte o. g. Gerät hinzufügen. Nach betätigen des NEU-Buttons sehe ich es auch und wähle den Temperatursensor. Ich habe im darauffolgenden Dialog keine Checkbox aktiviert, möchte also Temperatur und Luftfeuchte sehen. Ich wähle noch eine Instanz und Go.
Dann dreht sich unten der Kreis und er sagt "wird hinzugefügt". Danach erscheint das Gerät weder im Webinterface des Plugins, noch in HomeKit. Hilfe!

**Comment by roe1974** [comment]
Bei mir geht der HmIP-SWO-B ohne Probleme.
Wichtig: 1. Kanal des Geräts auswählen und "HomeMaticThermometerAccessory" als Service wählen.

**Comment by mbgong** [comment]
Genau das mache ich. Dann sagt er „Gerät wird hinzugefügt.“ Danach ist das Gerät nicht in der Liste. Bei mir laufen 64 Geräte problemlos. Testweise habe ich auch ein anderes hinzugefügt, was auch funktioniert hat. Nur die Wetterstation Basic möchte nicht.

**Comment by mbgong** [comment]
Ich habe die Wetterstation nun such testweise nochmal aus der CCU3 entfernt und zurückgesetzt. Das Problem besteht auch nach erneutem Anlernen fort.

**Comment by mbgong** [comment]
Hat niemand eine Idee? Ohne die Integration in HomeKit ist die Station nur halb so viel wert für mich.

**Comment by jhk3** [comment]
Ich habe es zum Test mal mit dem Redmatic AddOn ausprobiert. (auf einer neuere Raspberrymatic, denn das geht nicht mit der älteren CCU2. Ich nutze das sonst nicht und kenne weder NodeRed noch Redmatic). Mit Websuche habe ich gefunden, dass sich homekit auch darüber verknüpft werden kann, jedoch aus meiner Sicht weniger elegant. Also die mit Redmatic erzeugte Bridge kann ich unter iOS 16.4.1 nachdem Homkit Architektur Upgrade einbinen und ich bekomme damit auch die Wetterstation in Homekit korrekt angezeigt, jedenfalls stimmt die Temperatur, die Luftfeuchtigkeit und die Helligkeit. Anderes habe ich nicht in Homekit gesehen. Alle drei Werte stimmen mit der Anzeige in der WebUI überein.

**Comment by jhk3** [comment]
Wegen der Messparameter der HMIP-SWO-PR habe ich mal die Device Information mit dem HAP-Homematic AddON erzeugt, da ja die Helligkeit in Homekit prinzipiell abgebildet werden könnte (evtl. auch die anderen Messwerte).

[HmIP-SWO-PR.json.txt](https://github.com/thkl/hap-homematic/files/11242850/HmIP-SWO-PR.json.txt)

**Comment by blackbasket** [comment]
Zur Sicherheit mal @thkl ... weiß nicht, ob Thomas in dem Thread schon mentioned wurde...

**Comment by mbgong** [comment]
Tatsächlich existiert das Problem schon bei mir schon vor HomeKit. Die Station wird nicht einmal im Plugin selbst angelegt. Ich habe 64 Geräte laufen, es wird mit der Station kein neues angelegt. Im Protokoll taucht nichts auf dazu. Er sagt er würde es anlegen, tut es aber nicht. Ein willkürlich gewähltes anderes Gerät wird testweise sofort als 65. Gerät angelegt.

**Comment by mbgong** [comment]
Ich habe den Fehler gefunden. Fehlercode 99...
Ich hatte mal eine OpenWeather-Wetterstation in der CCU von der scheinbar noch Relikte rumgeistern. Diese wurden mir auch in HAP angezeigt. Hab die Wetterstation über die Seriennummer gesucht und zack, so gehts. Logisch, dass es geht, wenn man es richtig macht...
