### ISSUE TITLE
Steckdose HMIP-PSM und Lichtschalter HmIP-BSM

### ISSUE THREAD

**Issue by mike4president** [thkl/hap-homematic#62]
Hallo,

wenn ich von der Steckdose den Messwertkanal hinzufüge kann ich die Dose schalten. Wenn ich vom Lichtschalter den Messwertkanal hinzufüge ist der Lichtschalter nicht messbar. 

Ich möchte gerne in der Eve App sowohl die Schaltvorgänge als auch den Stromverbrauch protokollieren. Dadurch muss ich aber beim Lichtschalter HmIP-BSM sowohl den Schaltkanal als auch den Messwertkanal einzeln hinzufügen, damit ich beides in Eve sehen kann. Dadurch wird HomeKit aber unübersichtlich. 

Kann man hier das Verhalten noch ändern, dass beides in einem HomeKit Gerät und somit auch in einer Gerät in der Eve App auftaucht?

Grüße

Mike

**Comment by mike4president** [comment]
und danke für das tolle Addon. Auf so eine Lösung warte ich schon lang. Ich verstehe einfach nicht, dass eQ-3 das nicht selber auf die Beine stellen kann.

**Comment by thkl** [comment]
Kannst Du mal bitte für den Aktor, der nicht wie gewünscht funktioniert, das Debugprofile erzeugen. Das geht über die Funktion Internes / Support. Und ist dort beschrieben.
Das Profile wird anonymisiert und kann hier angehangen werden.

**Comment by mike4president** [comment]
Wow, besten Dank für die schnelle Rückmeldung. Also der Lichtschalter HmIP-BSM funktioniert schon wie gewünscht, allerdings nur wenn ich seinen Schalkanal zu HomeKit hinzufüge. Allerdings sehe ich dann in der Eve App nur wann der Lichtschalter geschaltet wurde. Um zusätzlich die Verbrauchswerte in der Eve-App anzuzeigen muss ich zuzätzlich des Messwertkanal in HomeKit als zweites gerät hinzufügen. Dann sehe ich zusätzlich die Messwerte. Besteht die Möglichkeit das in der Eve App als ein Gerät anzuzeigen? Ich habe das Problem eigentlich nur weil ich die Eve App nutzen möchte. Wenn ich vom Lichtschalter nur den Messwertkanal hinzufüge dann kann nicht wie bei der Steckdose das Licht ein oder ausschalten. Das geht nur mit dem Schaltkanal. Was wirklich toll wäre, wenn man beide Geräte in der Eve App als eines sieht und damit auch beide Informationen (Schaltvorgänge und Verbrauch) unter einem Gerät sehen würde. 

<img width="1035" alt="Bildschirmfoto 2020-05-09 um 09 31 12" src="https://user-images.githubusercontent.com/65063329/81467312-35cfdd80-91d8-11ea-995a-5732ac28fe48.png">
![IMG_0119](https://user-images.githubusercontent.com/65063329/81467354-69126c80-91d8-11ea-8443-12bdb95d05d6.png)
![IMG_0120](https://user-images.githubusercontent.com/65063329/81467357-6d3e8a00-91d8-11ea-9e8d-0b996d94ede4.png)

**Comment by mike4president** [comment]
![IMG_0120](https://user-images.githubusercontent.com/65063329/81467408-b262bc00-91d8-11ea-9749-719f50378d10.jpg)
![IMG_0119](https://user-images.githubusercontent.com/65063329/81467412-b42c7f80-91d8-11ea-8cbe-8c9fc647bd95.jpg)

**Comment by mike4president** [comment]
soll ich das Debugprofile trotzdem noch schicken?

**Comment by thkl** [comment]
Jaja fürs zusammenlegen auf ein Gerät brauch ich das :)

**Comment by mike4president** [comment]
ok, das wäre klasse! ich probiere das mal. Danke...

**Comment by mike4president** [comment]
tut mir leid, dass ich so blöd fragen muss aber was genau ist denn das Device Serial das ich zur Erstellung der Informationen benötige?

**Comment by thkl** [comment]
001234567... die steht auch in der CCU in der Geräteliste. Das ist auch die Adresse des Gerätes.  Am Ende sollte ein File HmIP-BSM.json rausfallen.

**Comment by mike4president** [comment]
{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HmIP-BSM",
      "address": "6094613587ABCD",
      "type": "HmIP-BSM",
      "channels": [
        {
          "id": 1001,
          "name": "6094613587ABCD:0",
          "intf": 0,
          "address": "6094613587ABCD:0",
          "type": "MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "6094613587ABCD:1",
          "intf": 0,
          "address": "6094613587ABCD:1",
          "type": "KEY_TRANSCEIVER",
          "access": 255
        },
        {
          "id": 1003,
          "name": "6094613587ABCD:2",
          "intf": 0,
          "address": "6094613587ABCD:2",
          "type": "KEY_TRANSCEIVER",
          "access": 255
        },
        {
          "id": 1004,
          "name": "6094613587ABCD:3",
          "intf": 0,
          "address": "6094613587ABCD:3",
          "type": "SWITCH_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1005,
          "name": "6094613587ABCD:4",
          "intf": 0,
          "address": "6094613587ABCD:4",
          "type": "SWITCH_VIRTUAL_RECEIVER",
          "access": 255
        },
        {
          "id": 1006,
          "name": "6094613587ABCD:5",
          "intf": 0,
          "address": "6094613587ABCD:5",
          "type": "SWITCH_VIRTUAL_RECEIVER",
          "access": 255
        },
        {
          "id": 1007,
          "name": "6094613587ABCD:6",
          "intf": 0,
          "address": "6094613587ABCD:6",
          "type": "SWITCH_VIRTUAL_RECEIVER",
          "access": 255
        },
        {
          "id": 1008,
          "name": "6094613587ABCD:7",
          "intf": 0,
          "address": "6094613587ABCD:7",
          "type": "ENERGIE_METER_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1009,
          "name": "6094613587ABCD:8",
          "intf": 0,
          "address": "6094613587ABCD:8",
          "type": "COND_SWITCH_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1010,
          "name": "6094613587ABCD:9",
          "intf": 0,
          "address": "6094613587ABCD:9",
          "type": "SWITCH_WEEK_PROFILE",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by mike4president** [comment]
war das richtig? :-/

**Comment by mike4president** [comment]
vielen Dank für Ihre Mühe.

**Comment by mike4president** [comment]
ich kann die json Datei hier irgendwie nicht anhängen. Daher habe ich den Text kopiert.

**Comment by mike4president** [comment]
hier nochmal das Debüt Profile für die Steckdose. Hier wäre das Zusammenlegen auf ein Gerät genauso wünschenswert, damit man in HomeKit nicht mehr beide Geräte hinzufügen muss, damit man die Informationen in der Eve App hat.

**Comment by mike4president** [comment]
{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HMIP-PSM",
      "address": "5868691143ABCD",
      "type": "HMIP-PSM",
      "channels": [
        {
          "id": 1001,
          "name": "5868691143ABCD:0",
          "intf": 0,
          "address": "5868691143ABCD:0",
          "type": "MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "5868691143ABCD:1",
          "intf": 0,
          "address": "5868691143ABCD:1",
          "type": "KEY_TRANSCEIVER",
          "access": 255
        },
        {
          "id": 1003,
          "name": "5868691143ABCD:2",
          "intf": 0,
          "address": "5868691143ABCD:2",
          "type": "SWITCH_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1004,
          "name": "5868691143ABCD:3",
          "intf": 0,
          "address": "5868691143ABCD:3",
          "type": "SWITCH_VIRTUAL_RECEIVER",
          "access": 255
        },
        {
          "id": 1005,
          "name": "5868691143ABCD:4",
          "intf": 0,
          "address": "5868691143ABCD:4",
          "type": "SWITCH_VIRTUAL_RECEIVER",
          "access": 255
        },
        {
          "id": 1006,
          "name": "5868691143ABCD:5",
          "intf": 0,
          "address": "5868691143ABCD:5",
          "type": "SWITCH_VIRTUAL_RECEIVER",
          "access": 255
        },
        {
          "id": 1007,
          "name": "5868691143ABCD:6",
          "intf": 0,
          "address": "5868691143ABCD:6",
          "type": "ENERGIE_METER_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1008,
          "name": "5868691143ABCD:7",
          "intf": 0,
          "address": "5868691143ABCD:7",
          "type": "COND_SWITCH_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1009,
          "name": "5868691143ABCD:8",
          "intf": 0,
          "address": "5868691143ABCD:8",
          "type": "SWITCH_WEEK_PROFILE",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by thkl** [comment]
So ich habe einen kleinen Fehler im BSM Profil beseitigt. Das könnte mit dem nächsten Update funktionieren ;)

**Comment by mike4president** [comment]
Echt klasse, vielen Dank. Ich mag die Eve App irgendwie, weil ich mir dadurch Cloudmatic und Pocket Control sparen kann. Geht das für die Steckdose auch, dass beides in einem Gerät zusammengefasst wird?

**Comment by thkl** [comment]
Aber oben die PSM geht doch schon in einem Gerät in Eve ?

**Comment by mike4president** [comment]
Ja, nur dass in Eve die Schaltzustände nur übermittelt werden, wenn ich die Steckdose einmal als mit dem Schaltkanal als Steckdose in HomeKit einrichte. Wenn ich zusätzlich die Steckdose als extra Kanal mit dem Messkanal in HomeKit einbinde, dann werden zwar die Stromwerte übermittel und sie lässt sich auch schalten, allerdings werden die Schaltzustände nicht protokolliert. Was ich im Grunde gerne hätte, ist dass ich nur den Messkanal einbinde in Homkit und dass dann sowohl die Schaltzustände als auch Stromwerte i einem Gerät in Eve protokolliert werden. Ginge das?
![IMG_0121](https://user-images.githubusercontent.com/65063329/81469984-864f3700-91e8-11ea-97d9-d83768fb48b9.jpg)
![IMG_0119](https://user-images.githubusercontent.com/65063329/81469986-8818fa80-91e8-11ea-99b6-2402907cec59.jpg)

**Comment by mike4president** [comment]
ich möchte halt gerne vermeiden, dass ich das selbe Gerät zweimal in Homkit einbinden muss um beide Daten zu protokollieren

**Comment by mike4president** [comment]
für den Lichtschalter meinte ich das genauso. Da würde ich auch gerne nur den Messkanal in HomeKit einbinden und dann die Schltzustände und die Stromwerte in einem Gerät protokollieren. Natürlich weiß ich nicht, ob das geht, es würde aber helfen HomeKit und die Eve App überschaubarer zu halten...

**Comment by thkl** [comment]
Ok. Laut der FakeGato Dokumentation ist es so, das eve energy kein Logging für switch Events hat. Und man kann einem Gerät mit dem FakeGato Modul nur einen logging Service hinzufügen. 
Will sagen, das geht momentan nicht. 

Es kann gut sein, das Eve selber das anders handhabt und bei denen es doch geht .. aber das von mir verwendete FakeGato Modul kann das derzeit nicht.

**Comment by mike4president** [comment]
Ah ok, besten Dank für die Mühe. Die ausgelesenen Stromwerte sind mir ohnehin wichtiger. Daher freue ich mich darauf, dass ich die Lichtschalter bald schalten kann :-)

**Comment by mike4president** [comment]
jetzt geht es mit dem Lichtschalter ;-)

**Comment by thkl** [comment]
Dann kann der issue ja geschlossen werden
