### ISSUE TITLE
HmIP Schlüsselsensor HmIP-DLS fehlt

### ISSUE THREAD

**Issue by hardl1** [thkl/hap-homematic#629]
**Device related data**
If you want to add a new device or add a feature to a new device, please login to your hap-homematic WebUI; Select Internal/Help and create the device description file as described in the dialog you will get. Please attach the file to your request.

{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HmIP-DLS",
      "address": "2297857947ABCD",
      "type": "HmIP-DLS",
      "channels": [
        {
          "id": 1001,
          "name": "2297857947ABCD:0",
          "intf": 0,
          "address": "2297857947ABCD:0",
          "type": "MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "2297857947ABCD:1",
          "intf": 0,
          "address": "2297857947ABCD:1",
          "type": "DOOR_LOCK_STATE_TRANSCEIVER",
          "access": 255
        },
        {
          "id": 1003,
          "name": "2297857947ABCD:2",
          "intf": 0,
          "address": "2297857947ABCD:2",
          "type": "ALARM_COND_SWITCH_TRANSMITTER",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by blackbasket** [comment]
@thkl :)
