### ISSUE TITLE
Session ID

### ISSUE THREAD

**Issue by JensBonse** [thkl/hap-homematic#63]
Hallo Thomas,

du übergibst dem HAP-homematic Web GUI ja die Session ID der aktuellen HM session.
Leider scheint sich HAP-homematic aber gar nicht dafür zu interessieren, ob die Session noch gültig ist. Man kann die Session ID auch ändern und reload drücken und alles geht weiter.
Kannst du die Session verifizieren und ggf. durch Aktionen in HAP-homematic 'am leben' erhalten?

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/81484609-1e7c0900-9247-11ea-9e5c-3bea9556e54a.png)

Das passiert bei mir auch, wenn ich die SessionID in der URL ändere.

**Comment by thkl** [comment]
btw: ich prüfe bei jedem Call über Rega system.GetSessionVarStr(sid) ob ich einen User mit Admin Rechten zurück bekomme ... 

ich schau noch mal, ob das den Session TimeOut zurücksetzt

**Comment by JensBonse** [comment]
Hmmm also als ich in der HAP-homematic URL einfach mal die ID verändert habe und reloaded habe, kam die ganz normale GUI. Änderungen an den Geräten habe ich nicht probiert. Aber ich hatte auch schon eine Session, die auf der CCU abgelaufen war und ich konnte Änderungen in HAP-homematic machen.
Ich schau mir das nochmal an.

**Comment by thkl** [comment]
Ja das habe ich in meinem Beispiel auch gemacht.  Den Haken in den Settings das die CCU Authentifizierung benutzt werden soll hast Du gesetzt ? Sonst wird die SessionId ignoriert.

**Comment by JensBonse** [comment]
Ah, daran kann es liegen. Checke ich dann morgen mal 😂
Dann wird sich das hier erledigt haben.
Den Session Timeout zu checken wäre trotzdem interessant.
