### ISSUE TITLE
HmIP-SWO-B als Wetterstation einbinden

### ISSUE THREAD

**Issue by frankprim** [thkl/hap-homematic#633]
Wenn ich die HmIP-SWO-B als "HomeMaticWeatherStationAccessory" einbinden will bekommt HomeKit keine Verbindung zum Gerät. Binde ich das Gerät als "HomeMaticThermometerAccessory" ein funktioniert die Verbindung und bekomme Temperatur und Luftfeuchtigkeit angezeigt.

Ich weiß jetzt nicht ob mir mehr Infos zur Verfügung stehen würden wenn ich das Gerät als "HomeMaticWeatherStationAccessory" eingebunden bekommen würde oder nicht. Vielleicht weiß das ja jemand. :)

**Comment by Menuchim** [comment]
Hi,
ich habe die gleiche Frage.
Ich würde auch gern eine Wetterstation einbinden, habe jedoch die HmIP-SWO-PR.
Allerdings bekomme ich keinen Temperaturwert übermittelt, wenn ich es als "HomeMaticThermometerAccessory" einbinde.
Cool wäre, wenn es wirklich als "HomeMaticWeatherStationAccessory" eingebunden werden könnte, da ich so auch Windrichtung, Windgeschwindigkeit und ggf. Helligkeit bekommen könnte. Helligkeit jedoch bitte nicht in LUX, da das nicht die Einheit ist, die die Wetterstation erzeugt.
Danke.
Gruß.

**Comment by ChrWi** [comment]
Schaut bitte mal unter #37 nach -> Apple Home bietet das Gros der Wetterdaten nicht an
