### ISSUE TITLE
BROLL Anzeige in Homekit 

### ISSUE THREAD

**Issue by benskyy** [thkl/hap-homematic#634]
Als Homematic Neuling und zwei linken Händen im Bereich Programmierung/etc., hab ich es geschafft, meine CCU3 samt HAP einzurichten. Es funktioniert hervorragend. 

Aktuell nutze ich nur die Rolladenaktoren. Nun eine Frage zur Anzeige in Homekit. 
Wenn ein Rollo geöffnet ist, wird es wie eine eingeschaltete Lampe -> Schaltfläche HELL/AN angezeigt. Ich hätte dies der Übersichtlichkeit wegen gern umgedreht oder gar ausgeschaltet.

Gibt es da irgendeine Möglichkeit? 

Danke!!

**Comment by gerd2005** [comment]
Hast du im PlugIn vlt. einen falschen Service ausgewählt?
Lad mal bitte ein paar Screenshots hoch.

**Comment by benskyy** [comment]
@gerd2005 

![IMG_9076](https://github.com/thkl/hap-homematic/assets/135142311/7caac652-fa22-42b4-a9a5-f39266b426e4)

**Comment by gerd2005** [comment]
Achso, du meinst wenn das Rollo oben/ geöffnet ist, soll die Schaltflächen so dargestellt werden wie bspw. der Lightstrip?

**Comment by benskyy** [comment]
@gerd2005 Ja genau. Umgekehrt wäre übersichtlicher. 

Gibts dafür eine Lösung?

**Comment by gerd2005** [comment]
Nein, das wird nicht funktionieren denke ich.

**Comment by AlexF090** [comment]
Ich bin mir nicht sicher ob du diese Funktion meinst und ob diese den gewünschten Effekt hat. 

<img width="1681" alt="Bildschirmfoto 2023-10-25 um 11 19 08" src="https://github.com/thkl/hap-homematic/assets/100590496/fadb155e-3ea5-4cd0-87d9-4748251c7581">

Ich habe daran bei mir nichts geändert und habe mich damit zufrieden gegeben. Rolladen sind in den USA nicht so sehr vertreten, aus diesem Grund wird hier eine "Jalousie" benutzt.

"Hey Siri schließe die Rollade xyz auf 20%" und ich habe nur noch die einzelnen Löcher der Rollade die offen sind.

**Comment by benskyy** [comment]
Danke! Hat funktioniert!
