### ISSUE TITLE
Markisensteuerung

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#636]
Hallo zusammen,

ich möchte euch einmal fragen, wie ihr eure Markisen oder generell Beschattungen ins Homekit bringt.

Ich habe aktuell das Problem, dass wenn ich Siri sage "schließe /öffne alle Rollos", bewegt sich auch die Markise, weil die (logischerweise) auch als Rollo erkannt wird.

Habt ihr eine Idee und Tipps, wie ich das unterbinden kann?

Zur Info: Für alle Rollos und die Markise habe ich einen HMIP-FROLL im Einsatz. Vielleicht muss ich auch für die Markise ein andere Gerät nutzen?

Danke und lieben Gruß
gerd

**Comment by ChrWi** [comment]
Hallo Gerd,
ich nutze ausschließlich die BROLLs für 14x Rollläden und 3 Markisen. Dein „Problem“ kenne ich auch, wobei Siri hier nur im Ausnahmefall zur Anwendung kommt -> primär Zeitsteuerung (Rollladen) und Wetterdaten (Markisen), sekundär per manuellem Schalter durch Frau & Kinder
Wenn  jemand einen Trick für Siri hat -  gerne!

**Comment by Jokerx3** [comment]
Hallo, 
ich habe mir in HomeKit 2 Szenen mit dem Wortlaut „alle Rollläden hoch“ und „alle Rollläden runter“ angelegt. In die Szenen habe ich alle Rollläden reingepackt mit Ausnahme der Markise. Beim Sprachkommando über Siri wird dann die Szene getriggert - funktioniert bei mir tadellos.
Viele Grüße

**Comment by gerd2005** [comment]
Hallo @Jokerx3 ,

grds. ein OKer Workaround, jedoch hat Homekit ja diese Befehle bereits im Bauch.
Naja mal sehen... m.E. müsste es halt eine Gerätekategorie "Markise" o.ä. geben. In Amerika haben die anscheinend keine Markise, genauso wenig wie Rasenroboter oder so...

Viele Grüße
gerd
