### ISSUE TITLE
HAP-homematic GUI Link

### ISSUE THREAD

**Issue by JensBonse** [thkl/hap-homematic#64]
Hallo Thomas,

wenn ich aus der CCU auf HomeKit klicke, öffnet der Browser eine neues Tab auf /addons/hap-homematic/index.html?sid=@ABC@ was mich dann an http://<URL der CCU>:9874?sid=@ABC@ weiterleitet.

Wäre es möglich, die Weiterleitung irgendwie zu konfigurieren?
Da ich einen Reverse Proxy verwende, wäre es super, wenn ich die Weiterleitung von /addons/hap-homematic/index.html?sid=@ABC@ z.B. auf https://<andere URL>?sid=@ABC@ konfigurieren könnte. Damit ich auch von Außen auf HomeKit komme, wenn ich den HomeKit Knopf drücke.

Ich kann natürlich im Reverse Proxy einiges basteln, damit das funktioniert. Anders fände ich es natürlich schöner.

**Comment by thkl** [comment]
Das Script auf der AddonSeite weiss natürlich noch nichts vom HAP Server und dessen Config.
Daher muss ich schon einige Stunts machen, um rauszufinden, ob ich auf http oder https umleiten muss. Diese Umleitung konfigurierbar zu machen wird gleich noch wilder.

**Comment by roe1974** [comment]
wieso kein vpn tunnel ?

**Comment by thkl** [comment]
Das ist die falsche Frage ;)

**Comment by roe1974** [comment]
naja so oft konfiguriert man doch nicht herum in der ccu/hap von unterwegs .... 😉😉

**Comment by thkl** [comment]
Ich könnte aber generell eine Version von hap-homematic auf http und eine auf https (http port +1) laufen lassen ...  (ich wollte nur nicht noch mehr ports auf machen)

**Comment by roe1974** [comment]
wenn man die ccu webui via https öffnet leitet er doch HAP um auf https .... über einen reverse proxy tut er das nicht ?

**Comment by JensBonse** [comment]
Er leitet dann schon auf https um. Jedoch mit dem Port hinten. Dann muss ich auf meinem Reverse Proxy den Port eben öffnen und da auch eine Weiterleitung machen. Oder ich schau mir einfach mal die index.html vom Addon an und editiere die.

VPN wird in vielen Netzwerken blockiert. Https hingegen ist immer offen. Und wenn man dann auf dem Reverse Proxy noch OTP ( one time password) verwendet, ist das auch sehr sicher.

**Comment by roe1974** [comment]
deswegen mache ich ovpn über port 443 und nicht 1194 :)

**Comment by JensBonse** [comment]
Das bringt aber auch nur bedingt was. Wenn eine richtige Firewall mit Packet Inspection eingesetzt wird, dann geht dein OpenVPN nicht. Dann könntest du natürlich immer noch stunnel einsetzten.
Was man alles installieren und konfigurieren muss. Mit dem Reverse Proxy kann ich an jeden Rechner ohne Manipulation oder Installation direkt auf meine Systeme zugreifen.

**Comment by thkl** [comment]
Da ich einen eigenen HTTP(s) Server auf dem Port aufmache wird das nicht so leicht. Ich könnte natürlich einfach alles durch ein cgi Script Tunneln und wäre dann wieder auf Port 443 ... 🤯

**Comment by JensBonse** [comment]
Nein, lass mal. Ich biege mir das schon zurecht.
Ist ja keine Anforderung die viele haben werden.
