### ISSUE TITLE
Systemvariable schaltet in der CCU nicht um

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#644]
Hallo,

in der CCU habe ich eine Systemvariable angelegt:
![image](https://github.com/thkl/hap-homematic/assets/72799068/14f01eca-62fe-431e-af73-33d0db15e99e)

Diese habe ich zu den Favoriten/der Startseite hinzugefügt um den Status zu sehen:
![image](https://github.com/thkl/hap-homematic/assets/72799068/b76cb67c-f41c-4c90-a3f2-3b9d6d400a81)

Anschließend habe ich die Variable ins Homekit gebracht um hier den Status ändern zu können:
![image](https://github.com/thkl/hap-homematic/assets/72799068/dfabc19c-e8b5-4039-9782-1d120ccad5fc)

In der Home-App wird die Variable nun auch angezeigt und ich kann sie ein- und ausschalten. Jedoch ändert sich der Status in der CCU nicht. Dieser bleibt immer auf "Manu-Modus"

PS: Ein Programm habe ich noch nicht aktiv. Ich wollte es erst hinbekommen, dass der Status in der CCU korrekt angezeigt wird. Hat jemand eine Idee was ich falsch mache?

VG
gerd

**Comment by blackbasket** [comment]
Hallo @gerd2005 ,

nach dem Motto keep it simple: Nimm mal das einfache HomematicVariableAccessory

Das funktioniert bei mir problemlos...

LG,
Marcel

**Comment by gerd2005** [comment]
Hi,

habe ich nun gemacht, und die CCU auch einmal neu gestartet. Leider ohne Erfolg.

Komisch ist auch folgendes:
Ich schalte die Variable in der Home-App ein => Der Schalter bleibt oben
Schließe ich in der App den Schalter über das "X", schaltet sich die Variable direkt wieder aus.

**Comment by ChrWi** [comment]
Hallo Gerd,
wenn ich den screenshot aus dem hap addon richtig interpretiere, hast Du keinen Trigger definiert, oder? Bin mir gerade nur nicht sicher, ob der für beide Richtungen (ccu <-> hap) benötigt wird. Sollte im Wiki stehen

**Comment by gerd2005** [comment]
@ChrWi 
Danke für dein Feedback. Ich verstehe es aber leider nicht… Was genau meinst du?
So sieht die Variable in dem Plugin aktuell aus.
![IMG_0747](https://github.com/thkl/hap-homematic/assets/72799068/1b69aa60-71b2-4f6f-a351-a307cb8862d8)

Meinst du das, was da im Hintergund ist? Teigiger => Auswählen?

**Comment by ChrWi** [comment]
Ja, siehe https://github.com/thkl/hap-homematic/wiki/variables#trigger

**Comment by gerd2005** [comment]
Hi,
ich habe nun einen virtuellen Taster als Trigger hinzugefügt und dieses Hilfsprogramm erzeugen lassen. Das hat auch soweit geklappt.
Dennoch schaltet sich meine Variable in der CCU immer noch nicht um.

Ist denn überhaupt möglich eine Variable im Homekit als Schalter hinzuzufügen und löst bei einer Änderung ein Programm in der CCU aus?

![image](https://github.com/thkl/hap-homematic/assets/72799068/3087c9c8-3080-4424-a691-9d67f0235742)
 Ich bin echt ratlos mittlerweile...

**Comment by ChrWi** [comment]
Hallo Gerd,
ich nutze das an mehreren Stellen. Ein konkretes Beispiel:

- Variable „Schulfrei“, Boolean (lange schlafen/früh aufstehen)
- Programm wie angehängt - setzt das Zeitprogramm der Rollläden außer Kraft
- im hap-homematic die Variable als Switch definiert
- das Trigger Programm aktualisiert
![IMG_0596](https://github.com/thkl/hap-homematic/assets/52505025/30a2b9ab-7258-444e-8b49-f1de7ab1fbbc)
![IMG_0597](https://github.com/thkl/hap-homematic/assets/52505025/2a6614ac-661b-4a7f-9563-782bc0b61c10)
![IMG_0598](https://github.com/thkl/hap-homematic/assets/52505025/94d594c2-a9a3-4d30-8808-2f8304e43de1)

**Comment by gerd2005** [comment]
Also ich würde sagen, dass ich das genauso habe wie du. Ich habe bei der DANN-Bedingung zur KOntrolle mal einen Lichtschalter genommen, damit ich sehen kann, ob überhaupt was in der CCU ankommt.

Programm:
![image](https://github.com/thkl/hap-homematic/assets/72799068/5e9f4f4f-d688-42dd-b6d6-4ece72dce9c8)

Switch im Plugin:
![image](https://github.com/thkl/hap-homematic/assets/72799068/216f9c6d-ea5b-4728-bc7a-5d2cca6be9b5)

hap_autotrigger:
![image](https://github.com/thkl/hap-homematic/assets/72799068/e4f38810-a140-4f20-a430-298e15872cde)


Hast du noch eine Idee?

**Comment by ChrWi** [comment]
Ich vermeide aus Gewohnheit Leerzeichen und Sonderzeichen in Variablen

**Comment by blackbasket** [comment]
Guter Hinweis @ChrWi ... das ist mir bewusst gar nicht aufgefallen... mache ich auch...

**Comment by gerd2005** [comment]
Hallo,

das Problem ist behoben. Leerzeichen und Umlaute (ä,ö, usw.) funktionieren in der CCU nicht.
Irgendwie unglaublich, dass die CCU damit nicht umgehen kann.

Danke für Eure Hilfe!!!

Viele Grüße
Gerd

**Comment by gerd2005** [comment]
Hallo,

das Problem ist behoben. Leerzeichen und Umlaute (ä,ö, usw.) funktionieren in der CCU nicht.
Irgendwie unglaublich, dass die CCU damit nicht umgehen kann.

Danke für Eure Hilfe!!!

Viele Grüße
Gerd

**Comment by blackbasket** [comment]
Ok... da ich auch in der "Ära" nach 8.3 immer noch möglichst kurze Dateinamen und nur ASCII-Zeichen verwende, ist mir das tatsächlich nicht aufgefallen ;) schön, dass es jetzt läuft :) @ChrWi gutes Auge ;)

**Comment by gerd2005** [comment]
Hallo,

ich habe doch noch eine abschließende Frage.
Besteht die Problematik mit der Benamung (Nur A-Z, keine Umlaute und Leerzeichen) nur in Verbindung mit dem PlugIn, oder ist das ein generelles Problem in der CCU?

Mit anderen Worten: Wenn ich eine SV in der CCU anlege, diese aber NICHT im PlugIn ist, kann ich diese mit Leerzeichen und Umlauten benennen?

**Comment by ChrWi** [comment]
Hallo Gerd, ich habe kurz in den Dokumentation nachgeschaut - aus offizieller Sicht ist die Antwort nein.
![IMG_0604](https://github.com/thkl/hap-homematic/assets/52505025/d1c63ef3-00fd-44af-b65d-d77aae06b2a5)
https://www.eq-3.com/Downloads/eq3/download%20bereich/hm_web_ui_doku/HM-Skript_Teil_1_Sprachbeschreibung_V2.2.pdf#page6
