### ISSUE TITLE
Version 0.0.39

### ISSUE THREAD

**Issue by renderender** [thkl/hap-homematic#65]
Hallo,

gerade habe ich auf Version 0.0.39 geupdated -> Leider sind alle einstellungen verloren gegangen. Nach neuinstallation in der Instanz kann kein Gerät mehr in die Instanz angelegt werden. Auch ein Namensänderung der Instanz geht nicht. Bei jedem Neustart aus RaspyMatic heraus startet der Einrichtungsassistent...Es sieht so aus, als würden keine Einstellungen mehr gespeichert.

Mit Version 0.0.37 hatte ich keinerlei Probleme...
Was kann ich tun?

In der firewall sind die Ports offen...

**Comment by thkl** [comment]
Oops da gab es einen Fehler im Einlesen der Config. .40 sollte das beheben.
Allerdings hat dieser Bug die config.json aus /usr/local/etc/config/addons/hap-homematic geschrottet. Ggf also das Backup einspielen

**Comment by thkl** [comment]
achja, die config.json liegt auch im CCU Backup, da dort auch das config Verzeichnis gesichert wird.
