### ISSUE TITLE
Unable to initialize HomeMaticIPMotionAccessory

### ISSUE THREAD

**Issue by akassa89** [thkl/hap-homematic#656]
Moin zusammen,
leider kann ich keine Bewegungsmelder hinzufügen. Kennt jemand das Problem?
Es passiert bei dem HmIP-SMO (also Funk) und beim kabelgebundenen HmIPW-SMI55 gleichermaßen.

[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] info - [HAP Server] [Server] powering up bridge : HomeMatic Außen with id XXXX , userid XXXX and pinCode  XXXX
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [Server] loading devices for instance XXXXX
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [Server] try find serviceclazz for 00095BE99A884D:1
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [Server] service HomeMaticIPMotionAccessory found thru address 00095BE99A884D:1
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [Server] try adding BwM to bridge b996248b-0bdc-41ae-a897-2264abcb08c3
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] info - [HAP Server] [Server] service used for BwM is HomeMaticIPMotionAccessory
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [HomeMaticIPMotionAccessory] 00095BE99A884D creating homekit accessory BwM-30_Außen / Sensor
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [HomeMaticIPMotionAccessory] 00095BE99A884D publishing services for BwM
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [HomeMaticIPMotionAccessory] 00095BE99A884D Register Datapoint MOTION for events
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [HomeMaticIPMotionAccessory] 00095BE99A884D buildAddress MOTION
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [HomeMaticIPMotionAccessory] 00095BE99A884D seems to be a single datapoint
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [HomeMaticIPMotionAccessory] 00095BE99A884D full addr is [object Object]
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [CCU] register address HmIP-RF.00095BE99A884D:1.MOTION for events
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [CCU] ask Rega HmIP-RF.00095BE99A884D:1.MOTION
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject('HmIP-RF.00095BE99A884D:1.MOTION');if (o){Write(o.Value());}
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] debug - [HAP Server] [HomeMaticIPMotionAccessory] 00095BE99A884D enable logging service  motion for BwM
[Tue Oct 24 2023 12:55:45 GMT+0200 (CEST)] error - [HAP Server] Unable to initialize BwM Error is /usr/local/addons/hap-homematic/node_modules/https-proxy-agent/dist/index.js:54

**Comment by ChrWi** [comment]
Hallo,
erste Frage: hast Du https in den Einstellungen von hap-homematic aktiviert? Siehe #653

**Comment by akassa89** [comment]
Moin @ChrWi,
nein, HTTPS ist nicht aktiviert. Bevor nun gleich rumgebasht wird, warum ich das nicht  gemacht habe: ich konnte erfolgreich Dimm-, Schalt- und Jalousie-Aktoren einbinden.

Es würde mich schon sehr wundern, wenn das dann die Lösung sein sollte, aber ich würde es anpassen. Ich melde mich morgen wieder. 

Für andere Lösungswege wäre ich trotzdem dankbar.

**Comment by akassa89** [comment]
![IMG_0079](https://github.com/thkl/hap-homematic/assets/148866909/c45c0888-ad99-4a34-b884-a14fa8502171)

es hat tatsächlich geklappt… unglaublich. Aber ehrlicherweise erst nach dem aktivieren des Kompatibilitätsmodus, da ich schon Bewegungsmelder hinzugefügt hatte.

**Comment by ChrWi** [comment]
Mit Blick auf zB #653 denke ich, dass mit der letzten großen Architekturanpassung durch iOS 16.2 „irgendwas passiert ist“, was die Home-Kompatibilität einfordert. Vielleicht kann sich @thkl hierzu äußern.
