### ISSUE TITLE
Integration HM-WDS10-TH-O

### ISSUE THREAD

**Issue by AllDamnAlarm** [thkl/hap-homematic#657]
Hallo zusammen, mir gelingt es nicht das Thermometer/Hygrometer HM-WDS10-TH-O als neues Gerät einer Instanz hinzu zufügen. Gibt es ein Log welches man überprüfen kann woran es hakt?

**Comment by AllDamnAlarm** [comment]
Kleinigkeit vergessen, das Log habe ich heruntergeladen, es geht mehr drum zu verstehen was mit nachfolgender Meldung ist.
"Error - [HAP Server] Unable to initialize DGBZ OUTS THRM:1 Error is /usr/local/addons/hap-homematic/node_modules/https-proxy-agent/dist/index.js:54
        this.proxyHeaders = opts?.headers ?? {};
                                 ^
"
Kann ich da was nachkonfigurieren ?

**Comment by roe1974** [comment]
Als welchen Gerätetyp hast Du das HM-WDS10-TH-O in HAP konfiguriert ?

**Comment by AllDamnAlarm** [comment]
Moin, Danke dür die schnelle reaktion. Ich nehme an den 'Service' da sind zwei zur Ausahl 'HomaMaticHumidityAccessory' und 'HomaMaticThermometerAccessory' beides generiert keinen Eintrag.

**Comment by roe1974** [comment]
Ich verwende diesen "HomeMaticThermometerAccessory" .. und der geht bei mir
Verwednest Du nur die Home App oder auch Eve ?

**Comment by AllDamnAlarm** [comment]
Einen Thermostat, welcher sich als "HomaMaticHumidityAccessory" meldet bekomme ich eingebunden, dieser HM-WDS10-TH-O  ist in der Auswahlliste bei 'Neues Gerät hinzufügen' als Typ 'WEATHER' gekennzeichnet. Falls es missverständlich war, es geht an der Stelle um die Definition des Gerätes in HAP. Also noch bevor ich mit Home oder EVE drauf zugreife.  Das hinzufügen zu einer Instanz schlägt fehl.

**Comment by roe1974** [comment]
Da Frage zielt ab in Richtung Einstellung in HAP: Internes->Einstellungen: "Apple-Home App kompatible" angehackt oder nicht ?

**Comment by AllDamnAlarm** [comment]
Oh tausend Dank, das war es wohl, ich habe den Haken gesetzt, die HAP Instanz wurde neu gestartet und das Gerät war sofort in der Liste der Geräte als zugeordnet.

**Comment by AllDamnAlarm** [comment]
Und um die Frage noch zu beantworten ich habe den zweiten Eintrag aus der Liste genutzt. In der' Home'-App ist es als Thermometer und mit Suffix '2' als Hygrometer zu sehen.
Die Lösung war also  => HAP: Internes->Einstellungen: "Apple-Home App kompatible"  anhaken.
Vielen Dank noch mal für die schnelle Unterstützung.
