### ISSUE TITLE
Keine Unterstützung für iOS > 16.2 - keine Einladung anderer Benutzer möglich

### ISSUE THREAD

**Issue by murksmax66** [thkl/hap-homematic#665]
Moin,
bei der Nutzung von hap-homematic mit einem Device mit aktuellem iOS (Version >16.2) ist es leider nicht mehr möglich, andere vertrauenswürdige Benutzer in das Home einzuladen. Es erscheint der schlichte Hinweis von Apple, dass man doch bitteschön einen AppleTV oder HomePod als Steuerzentrale nutzen möge um andere Benutzer einzuladen. 

Bei einem Device mit iOS < 16.2 (z. B. ein älteres iPad mini) funktioniert dies einwandfrei und es können von dem alten Gerät aus auch Benutzer mit einem neuen Gerät (> 16.2) erfolgreich eingeladen werden.

Beim Aufrufen der Einstellungen des Zuhauses (unter einem neuen iOS) und dort der Personen wird angezeigt, dass eine Steuerzentrale benötigt wird. Eine Einladung von anderen Personen ist nicht möglich.

![IMG_1545](https://github.com/thkl/hap-homematic/assets/111336739/cca3e66c-11e8-4cf4-99f3-9df78b10d9e5)

Klickt man hier auf " weitere Infos", bekommt man den Hinweis auf die erforderliche Hardware:

![IMG_1544](https://github.com/thkl/hap-homematic/assets/111336739/5173b9e5-8ca6-4c70-9126-e652fced9b53)

Leider bringt es einen nicht weiter, dass man entweder 
* ein altes Telefon/Tablet oder
* einen AppleTV >= Generation 4 oder
* einen HomePod
als Steuerzentrale einsetzen muss, um die Homematik damit zu ersetzen bzw. anzusteuern ...

Es wäre schön, wenn die Entwickler sich hier nochmals dran versuchen könnten, um die Emulation einer Steuerzentrale zu ermöglichen. Ansonsten ist das ein klasse System!

Grüße aus Ostfriesland 
Max

**Comment by roe1974** [comment]
Das hat aber nichts mit dem PlugIn hier zu tun ... seit iOS 17 gehen nurmehr HomePods und ATVs als Steuerzentrale.
Das wird von Apple so vorgegeben !

**Comment by ChrWi** [comment]
@roe1974 hat absolut recht
