### ISSUE TITLE
Sirene

### ISSUE THREAD

**Issue by daytrax** [thkl/hap-homematic#67]
hi, gibt es einen Support für die Homematic Ip Sirene ?
HmIP-ASIR-2
DIe Normale Siren Funktion würde mir schon reichen.

Day

**Comment by daytrax** [comment]
[HmIP-ASIR-2.json.txt](https://github.com/thkl/hap-homematic/files/4606389/HmIP-ASIR-2.json.txt)

**Comment by thkl** [comment]
Die war schon mal drin, aber da man keine sinnvollen Sachen damit anstellen kann, werden die Key Datenpunkte rausgefiltert. Siehe #50

**Comment by daytrax** [comment]
Schade, ich dachte ich könnte Sie als Alarmsirene unter HomeKit nutzen ; wenn Bewegung dann Sirene an.

**Comment by thkl** [comment]
ja, aber sollte das nicht die CCU steuern ?

**Comment by daytrax** [comment]
Ja, aber ich habe z.B. die Fenstersensoren nicht in der CCU. ich nutze ein Mischsystem aus HomeKit Nativ, Homematic, Hue und Xiaomi.

Ich würde halt die Sirene aus HomeKit mit dem Bewegungsmelder aus HomeKit Triggern

**Comment by thkl** [comment]
Okay. Problem ist, wie kann ich die Sirene ansteuern.
Ich vermute mal Channel 3 ALARM_SWITCH_VIRTUAL_RECEIVER da gibts nen beschreibbaren Datenpunkt: ACOUSTIC_ALARM_SELECTION mit allerlei Trötvarianten:

DISABLE_ACOUSTIC_SIGNAL
FREQUENCY_RISING
FREQUENCY_FALLING
FREQUENCY_RISING_AND_FALLING
FREQUENCY_ALTERNATING_LOW_HI
GH
FREQUENCY_ALTERNATING_LOW_MI
D_HIGH
FREQUENCY_HIGHON_OFF
FREQUENCY_HIGHON_LONGOFF
FREQUENCY_LOWON_OFF_HIGHON_
OFF
FREQUENCY_LOWON_LONGOFF_HIG
HON_LONGOFF
LOW_BATTERY
DISARMED
INTERNALLY_ARMED
EXTERNALLY_ARMED
DELAYED_INTERNALLY_ARMED
DELAYED_EXTERNALLY_ARMED
EVENT
ERROR

**Comment by detLAN** [comment]
Deine Vermutung ist richtig, es gibt drei Kanäle und der dritte wäre es.
<img width="284" alt="Bild1" src="https://user-images.githubusercontent.com/64675966/81700928-9cb7f580-9469-11ea-90be-b9bd0832a50b.png">

Auf der CCU unter Geräte sieht man dann dies für Kanal 3
<img width="599" alt="Bild2" src="https://user-images.githubusercontent.com/64675966/81700921-9b86c880-9469-11ea-8114-745ee98ace0b.png">

<img width="599" alt="Bild3" src="https://user-images.githubusercontent.com/64675966/81700917-99bd0500-9469-11ea-877c-ea4dde3c9423.png">

<img width="599" alt="Bild4" src="https://user-images.githubusercontent.com/64675966/81700910-988bd800-9469-11ea-8a97-b968901108aa.png">

<img width="599" alt="Bild5" src="https://user-images.githubusercontent.com/64675966/81700907-9590e780-9469-11ea-965d-3673cacf6792.png">

**Comment by daytrax** [comment]
Das wird der Grund sein, warum es sogst wie keine Sirenen unter HomeKit gibt !
Kenne da nur den Aqara Hub, und der erlaubt auch kaum eine Steuerung unter HomeKit

**Comment by mike4president** [comment]
Ich würde die Sirene falls möglich auch gerne in HomeKit einbindend ich teilweise noch Aqara Sensoren nutzen möchte. :-) Sie ist eigentlich das einzige Gerät, dass ich bisher nicht einbinden konnte.

![aqara-homekit-alarmanlage](https://user-images.githubusercontent.com/65063329/82235132-a098bb80-9932-11ea-93c5-433c3e15c8fa.jpg)
