### ISSUE TITLE
Home Kit will nicht richtig

### ISSUE THREAD

**Issue by B4unty** [thkl/hap-homematic#670]
Hallo zusammen,

ich habe homekit installiert und solange die debmatik. noch. nicht anmelde bereit ist. komme ich auch auf die website. und der Port lauscht. Sobald die website erreichbar. ist. Ist der. port verschwunden und Homekit auch.
Hilfe währe toll. Danke

**Comment by blackbasket** [comment]
Hallo @B4unty ... das schreit doch sehr nach Firewall...

**Comment by B4unty** [comment]
Kenn mich bei linux nicht so aus, warum sollte das so sein?

`root@debmatic:~# netstat -tulpen |grep 9874
tcp6       0      0 :::9874                 :::*                    LISTEN      0          11946      495/hap-homematic-c
root@debmatic:~# netstat -tulpen |grep 9874
root@debmatic:~# netstat -tulpen |grep 9874
root@debmatic:~# netstat -tulpen |grep 9874`

**Comment by blackbasket** [comment]
Hmm, sieht für mich danach aus, als wenn nur IPv6 auf dem Port hört... aber ich kenne DebMatic nicht... ist iptables oder so installiert?

**Comment by B4unty** [comment]
Nein nicht installiert.

**Comment by blackbasket** [comment]
Gibt's dann vllt in der Systemsteuerung Zugriff auf die FW? also, wie bei einer "normalen" CCU?

**Comment by B4unty** [comment]
Error: Service name is already in use on the network
    at Registry._onProbeComplete (/root/hap-homematic/node_modules/bonjour-hap/lib/Registry.js:108:27)
    at Prober.done (/root/hap-homematic/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/root/hap-homematic/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (node:events:517:28)
    at Socket.<anonymous> (/root/hap-homematic/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (node:events:517:28)
    at UDP.onMessage [as onmessage] (node:dgram:942:8)
~

**Comment by blackbasket** [comment]
Ein bisschen mehr Infos als ein Log wäre hilfreich... wo? Wann? ...?

**Comment by blackbasket** [comment]
Und in Code-Tags bitte ;)

**Comment by B4unty** [comment]
Ich kann nur sagen das ich das Plugin installiert habe. Danach die Configuration aus der Raspbarry Matic (HomeKit) Importiert habe. Wenn die Debmatik seine Website zur verfügung stellt das Plugin aufhört zu Arbeiten und den Log Eintrag Erzeugt. Mit code Tag war es leider nicht lesbar da kein zeilenumbrüche vorhanden waren.

**Comment by blackbasket** [comment]
Wenn du das Code-Tag dreifach eingibst, ist es multiline-fähig ;)

Also gibt es in der DebMatic kein `Einstellungen -> Systemsteuerung -> Firewall konfigurieren`?

**Comment by blackbasket** [comment]
Hast du die DebMatic auch aus einem RM-Backup wiederhergestellt? Oder wie kommst du zum HAP-Backup?

**Comment by B4unty** [comment]
Danke für die Erklärung. 
Ich habe ein Backup der Rasberymatic CCU eingespielt und auch von Home kit. FW Einstellung wie bei Raperrymatic finde ich nicht. Da der dienst aber mit einem Fehler wie im log beendet wird. Ist FW ausgeschlossen da der dienst ja nicht startet.

**Comment by blackbasket** [comment]
>> Wenn die Debmatik seine Website zur verfügung stellt das Plugin aufhört zu Arbeiten und den Log Eintrag Erzeugt

Dass der Dienst nicht startet, muss ja sachlich falsch sein. Schließlich hast du selbst geschrieben, dass er zunächst läuft. ;)

Und im Log steht ja, dass der Dienst bereits läuft und daher nicht nochmal gestartet werden kann. Deshalb auch die Frage nach den Backups. Ich habe das Gefühl, dass HAP in irgendeiner Form "doppelt installiert" ist. Eigentlich hätten die HAP-Settings ja auch schon im CCU-Backup enthalten sein müssen.

Kannst du das Plugin mal deinstallieren und danach schauen, was davon noch im Filesystem existiert?

**Comment by B4unty** [comment]
In der Anleitung und im Skript sind verschiedene Pfade da ich curl und npm nicht installiert hatte lief das skript teilweise in einen Fehler. Was zu der vermuteten doppel installation geführt hat. Danke
