### ISSUE TITLE
Schaltaktor HmIP-BSM läßt sich nicht einbinden

### ISSUE THREAD

**Issue by McMike63** [thkl/hap-homematic#680]
**Please describe your problem**
Which Homematic actor/sensor you want to control ? HmIP-BSM
Which settings y've choosen for this actor/sensor in hap-homematic ?
Service:  HomeMaticSwitchAccesory
Subtyp:  Lightbulb
Instance: HomeMatic Gaeste WC

**What happends**
Der Aktor erscheint nicht in HOME (HomeKit), obwohl der Prozess zum Hinzufügen ohne Fehlermeldung durchläuft
**What should be happend**
Der Aktor sollte
**Steps to reproduce this issue**
(while you are perfoming these steps please run hap-homematic in debug mode ( https://github.com/thkl/hap-homematic/wiki/Troubleshooting#running-in-debug-mode ) and add the log here

**Comment by ChrWi** [comment]
Hi,
Deine HAP-Instanz vom BSM ist aktiv?

**Comment by McMike63** [comment]
Guten Morgen,so ganz verstehe ich die Frage nicht.Wenn damit gemeint ist, ob die Instanz die dem betroffenen Gerät zugewiesen wird aktiv ist, dann gehe ich davon aus, dass diese Instanz aktiv ist.In der Home App wird die Instanz beim Einfügen auf jeden Fall angezeigt. Nur nach dem Einfügen des/der Geräte befinden diese sich nicht in der entsprechenden Ansicht der Home App.Vielen Dank für Deine Bemühungen.Viele GrüsseMichaelMichael SchulteAmselstrasse 2146119 OberhausenMail : ***@***.*** 29.04.2024 um 23:45 schrieb ChrWi ***@***.***>:﻿
Hi,
Deine HAP-Instanz vom BSM ist aktiv?

**Comment by ChrWi** [comment]
Hi,
ok, die Instanz ist geklärt.
Zu den anderen beiden Punkten:
Kanal 4 ausgewählt?
![IMG_0833](https://github.com/thkl/hap-homematic/assets/52505025/ecfe1ab9-112b-4590-864a-8dfcb577ece2)
Sofern Du kein Eve nutzt, aktiviere idealerweise die Apple-Homekit Kompatibilität 
![IMG_0834](https://github.com/thkl/hap-homematic/assets/52505025/d0e4028b-1de9-40ef-b0fd-f6ff5e1af0f0)
Meine 4 BSMs machen keine Probleme (Erstes Gerät ca. 2019, letztes Gerät dieses Jahr)
![IMG_0835](https://github.com/thkl/hap-homematic/assets/52505025/a8076725-bec4-464b-b8a9-5945bbed8551)

**Comment by McMike63** [comment]
﻿Hallo,sorry, dass ich mich jetzt erst melde. Ich war aber einige Wochen krank geschrieben und habe mich in der Zeit nicht wirklich um das Thema kümmern können.Mittlerweile habe ich es aber geschafft, die Geräte ins Homekit einzukippen und auch darauf über die Apple Home App darauf zuzugreifen und auch über Siri.Danke für die UnterstützungViele GrüsseMichael SchulteAmselstrasse 2146119 OberhausenMail ***@***.*** SchulteAmselstrasse 2146119 OberhausenMail : ***@***.*** 21.05.2024 um 22:39 schrieb ChrWi ***@***.***>:﻿
Hi,
ok, die Instanz ist geklärt.
Zu den anderen beiden Punkten:
Kanal 4 ausgewählt?
IMG_0833.jpeg (view on web)
Sofern Du kein Eve nutzt, aktiviere idealerweise die Apple-Homekit Kompatibilität
IMG_0834.jpeg (view on web)
