### ISSUE TITLE
unfi Protect camera and ekey fingerprint

### ISSUE THREAD

**Issue by Andruvion** [thkl/hap-homematic#681]
**Is your feature request related to a problem? Please describe.**
I try to integrate Unifi Cameras in my Home environment. Normally i use Homematic but for camera und so on unifi.
so is it possible to port https://github.com/hjdhjd/homebridge-unifi-protect to HAP-Homematic?

Further is it possible to integrate ekey devices?

**Comment by jb-home** [comment]
HAP-Homematic is a plugin for Homematic only.
It is not a platform like Homebridge.

Use Homebridge to connect Unifi Protect cameras to HomeKit.
