### ISSUE TITLE
Fehlende Übersetzung

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#69]

**Comment by detLAN** [comment]
<img width="800" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81510370-6b2c1680-9311-11ea-9cb5-67e9bc6336c7.png">
Please make sure...

**Comment by thkl** [comment]
😁

**Comment by detLAN** [comment]
oh, dass freut den Meister, dann muss ich gleich weitere Fensterschüsse hier posten.
<img width="367" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81510867-83059980-9315-11ea-911b-7cf8743a1c84.png">

<img width="769" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81510908-adefed80-9315-11ea-9091-439ce4aea75b.png">

**Comment by detLAN** [comment]
<img width="776" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81510989-5aca6a80-9316-11ea-9717-995258c7ee84.png">

<img width="774" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81510994-6158e200-9316-11ea-8e96-1d0612a1f330.png">

**Comment by detLAN** [comment]
![IMG_0906](https://user-images.githubusercontent.com/64675966/81511073-04a9f700-9317-11ea-8aea-d1ce637b2e99.png)
Ist jetzt zwar nicht Übersetzung, pack ich trotzdem hier rein, weil ich sonst nicht weiß wohin damit. Nach dem ich allen Instanzen einen Raumzugewiesen habe, Steht der Raum hinter dem Wort HomeMatic. Nur wo ich keine Änderungen vorgenommen habe, bleibt der Name vor dem Wort HomeMatic stehen. Jetzt heißt es, finde den Fehler.

**Comment by detLAN** [comment]
<img width="314" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81511395-6e2b0500-9319-11ea-9543-7552e63fa665.png">
Processor = Prozessor
Uptime = Betriebszeit

**Comment by detLAN** [comment]
Wo wir gerade drüben über die Wetterstation sprachen
<img width="747" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81511610-e0501980-931a-11ea-9f24-1f4e7bfe8e73.png">

**Comment by detLAN** [comment]
<img width="235" alt="Bild" src="https://user-images.githubusercontent.com/64675966/81511874-bb5ca600-931c-11ea-84e8-17e676343593.png">
Log herunterladen

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/81582863-d1b44180-93b0-11ea-8bf0-05f218ff413d.png)

**Comment by thkl** [comment]
oben die Meldung Processor kommt direkt aus dem node process da kann ich nichts lokalisieren

**Comment by detLAN** [comment]
Kurz noch zu Info, habe jetzt festgestellt, dass auf der CCU irgendetwas mit dem Raumnamen "Außenanlage" nicht stimmte. Hab den Raum neu benannt (wieder mit Außenanlage) und dann klappte es auch hier korrekt.


> ![IMG_0906](https://user-images.githubusercontent.com/64675966/81511073-04a9f700-9317-11ea-8aea-d1ce637b2e99.png)
> Ist jetzt zwar nicht Übersetzung, pack ich trotzdem hier rein, weil ich sonst nicht weiß wohin damit. Nach dem ich allen Instanzen einen Raum zugewiesen habe, steht der Raum hinter dem Wort HomeMatic. Nur wo ich keine Änderungen vorgenommen habe, bleibt der Name vor dem Wort HomeMatic. Jetzt heißt es, finde den Fehler.
