### ISSUE TITLE
Heizung

### ISSUE THREAD

**Issue by blackbasket** [thkl/hap-homematic#7]
Hallo,

ich habe das Addon gestern entdeckt und heute installiert. Erst einmal vielen Dank :) Funktioniert super.

Nun zu meinem Anliegen:
Ich kann keine Heizkörperthermostate (HmIP-eTRV) hinzufügen. Auch die Heizgruppe (HmIP-HEATING) zeigt nur Channel 5 an, aber lässt sich "ohne Steuerungszentrale" nicht nutzen.

LG,
Marcel

**Comment by thkl** [comment]
Kurze Frage hierzu: Die Steuerung erfolgt in der CCU über Kanal 1 dieses Gerätes oder ?

**Comment by blackbasket** [comment]
Ja, Ch1 ist der Sender... Ch2 der Empfänger am Radiator...

**Comment by thkl** [comment]
für HmIP-HEATING bräuchte ich irgendwie eine Info welcher Kanäle & Datenpunkte was machen. Da gibts leider nichts in der EQ3 Doku.

Für das Ventil ist es :

1:ACTUAL_TEMPERATURE - Aktuelle Temperatur
1:BOOST_MODE aktiviert den Boost Mode (bzw Event beim deaktivieren)
1:CONTROL_MODE akueller Modus des Ventils (Auto, Manuell, Boost)
1:SET_POINT_TEMPERATURE - Soll Temperatur

**Comment by blackbasket** [comment]
Ich würde dir gerne mehr sagen, aber im ccu-historian gibt es die Gruppe nicht. Auch nicht deaktiviert. Daher anbei die Daten aus der WebUI. Sieht für mich erst mal identisch aus. Mehr kann ich aktuell nicht bieten, aber ich suche nochmal.

![92CF656C-E643-4ADB-931B-08468BD26B21](https://user-images.githubusercontent.com/64146687/80016526-85719200-84d3-11ea-9957-c9816a7573b6.jpeg)
![4629A27A-F6C4-4A6B-8785-1D2E333A844A](https://user-images.githubusercontent.com/64146687/80016537-886c8280-84d3-11ea-97fb-0600e86476fe.jpeg)
![C682EACD-2B79-4BC1-9A76-051BCE3F0D35](https://user-images.githubusercontent.com/64146687/80016541-899daf80-84d3-11ea-833f-aed200f63edb.jpeg)
![65A571CA-D2AB-4C5A-AD0A-1F3E571A2787](https://user-images.githubusercontent.com/64146687/80016543-8a364600-84d3-11ea-8535-21f65ee00d4b.jpeg)

**Comment by thkl** [comment]
ok eins noch: der Channeltyp ... bitte mal auf der CCU im /usr/local/config/addons/hap-homematic/devices.json File nach dem Gerät schauen. Das ist ein json File aber durchaus lesbar.
Ich brauche den type des Channels 1 von so einer Gruppe ... beim HmIP-eTRV ist das HEATING_CLIMATECONTROL_TRANSCEIVER .. gff heist der bei den Gruppen auch so

**Comment by blackbasket** [comment]
Ja, ist identisch.
![533E62E6-922D-418A-B003-BD4C31ACB149](https://user-images.githubusercontent.com/64146687/80019218-77257500-84d7-11ea-85bd-3e2171e904bc.jpeg)
![DE20973C-571E-40B6-9794-891500B6A963](https://user-images.githubusercontent.com/64146687/80019226-7856a200-84d7-11ea-9391-5622b2cb23fa.jpeg)

**Comment by thkl** [comment]
ok dann funktionieren die mit dem nächsten Update vielleicht auch ;) Ich kanns mangels Geräten nicht testen ...

**Comment by blackbasket** [comment]
Danke. Das ging ja schnell :) ich werde berichten.
