### ISSUE TITLE
Backup Funktionalität

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#70]
Irgendwie vermisse ich die Wiederherstellen Funktion. Was soll ich mit einem Backup wenn ich es nicht auch wieder einspielen kann.

Zum Namen hätte ich einen Vorschlag: hap-homematic-backup-200510231234
Automatisch Datum (JahrMonatTag) und Uhrzeit dem Namen mitgeben. Ist Eindeutiger als hap-homematic-backup, hap-homematic-backup-2, hap-homematic-backup-3 ...

**Comment by thkl** [comment]
Einspielen ist derzeit auspacken und in den Config Folder per sftp kopieren.  Aber ja eine Restore Funktion wäre nützlich.  

Dazu fehlen aber noch diverse Validierungen.

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/82155552-fc513f00-9875-11ea-9c21-b795622ebda9.png)

**Comment by roe1974** [comment]
.... was heißt eigentlich covfefe ... kommt das wort nicht von trump ?

**Comment by thkl** [comment]
https://www.urbandictionary.com/define.php?term=covfefe

**Comment by roe1974** [comment]
sorry ... verstehe es trotzdem nicht ... denke du interpretierst „abbrechen“ damit

**Comment by thkl** [comment]
Korrekt

**Comment by roe1974** [comment]
warum schreibt man dann nicht „abbrechen“ ? 👍😜😜😜😜😜

**Comment by mike4president** [comment]
ich glaube das hier ist jetzt erledigt oder?

**Comment by thkl** [comment]
Ja, die Restore Funktion ist drin .. Freiwillige vor !

**Comment by detLAN** [comment]
Das könnte ich ja mal tun. Kann ich komplett löschen (auch auf CCU) und ganz neu anfangen?Frage, wieviel darf ich vorher löschen?

**Comment by thkl** [comment]
Wenn das AddOn von der CCU gelöscht wird, dann löscht sich auch das Datenverzeichnis. Bei einer Neuinstallation des Addons müsste dann der Wizzard abgebrochen werden und dann das Backup einspielen. Es wird nur die Config daraus benutzt. Die gespeicherten History Daten liegen zwar im Backup mit drin, aber werden nicht wieder ausgepackt. Da sich der Filename mit einem neuen Hostnamen vom PI ggf ändert...

Dabei fällt mir ein, ich hab den Restore mit der WebSocks Version des WebGUI noch nie getestet /o\ ...

Wenn es schief geht einfach die config.json aus dem Backup Archiv nach /usr/local/etc/addons/hap-homematic kopieren und HAP Neu Starten .. was anderes macht der Restore auch nicht

**Comment by detLAN** [comment]
Prima, Backup funktioniert so wie es soll!
Hab alle Instanzen bis auf default gelöscht. Hab anschließend alle 61 Geräte gelöscht, die default Instanz konnte ich trotzdem nicht löschen. Nach HAP Neustart dann das Backup eingespielt und alles ist wieder da, auch die Sortierung in Home bzw. eve sind beibehalten.
Werde dann die Tage dann mal auch komplett alles löschen, auch das AddOn von der CCU entfernen.

Was mir aufgefallen ist. Beim Löschen der Instanzen wird selbiges Fenster nicht aktualisiert. Hab eine Instanz gelöscht, die wird weiterhin angezeigt. Erst nach einem manuellen refresh ist sie dann auch weg.
Wenn man auf CCU Cache aktualisieren klickt passiert nichts, kein Feedback für den Nutzer.

**Comment by thkl** [comment]
ok wegen dem Löschen, baue ich mal noch einen Push vom Server zum Client ein.
Und ja ne Message für den Cache wäre schön kommt auch noch.
