### ISSUE TITLE
Homekit Automation mit Fenster-, Tür- oder Kontaktsensor

### ISSUE THREAD

**Issue by Sheldor81** [thkl/hap-homematic#71]
Mir ist aufgefallen das wenn ich eine Automation über die Statusmeldung eines Sensoren zum Beispiel durch "öffnen" des jeweiligen Sensors auslösen möchte. Das dieser dann erst geöffnet und wieder geschlossen werden miuss und dann erst beim wiederholten öffnen die Automation die beim "öffnen" Ausgelöst werden soll startet.

Die Statusmeldung in der Home App wird aber immer korrekt angezeigt und die Pushbenachrichtigungen funktionieren nach dem letzten Update auch perfekt.

Bei besondere Geräte habe ich mein Garagentor, dort werden die Aktionen über den Torstatus richtig ausgelöst.

**Comment by thkl** [comment]
What ?
Die Statusänderungen des Kontaktes sind korrekt, aber die Automationen funktionieren nicht ?

Die Automation (beim öffnen) läuft beim Öffnen los .... und dann erst wenn der Kontakt geschlossen und wieder geöffnet wird ?

Irgendwas verstehe ich nicht.

**Comment by Sheldor81** [comment]
> What ?
Die Statusänderungen des Kontaktes sind korrekt, aber die Automationen funktionieren nicht ?

genau. Push-Nachrichten funktionieren auch korrekt


Ich habe zum Beispiel eine Automation die beim öffnen eines Sensors das Licht einschalten soll.
Doch beim öffnen des Sensors passiert nichts, wird der Sensor dann geschlossen und direkt wieder geöffnet, startet die Automation.

**Comment by thkl** [comment]
Ist das Ding als Kontakt oder als Tür/Fenster eingestellt ?

**Comment by Sheldor81** [comment]
Egal der Fehler tritt bei jeder der genannten Konfigurationen auf.

**Comment by thkl** [comment]
Ok ich probier das mal aus

**Comment by thkl** [comment]
Bei mir funktionieren die Automations überhaupt nicht. Ich habe mal extra den Kontakt aus dem Original Apple HomeKit Simulator eingebunden. Der sollte sich ja 💯 konform verhalten. 

Dann ne Automation, die eine Lampe an schaltet:

![image](https://user-images.githubusercontent.com/884355/81590146-a9314500-93ba-11ea-97ef-970c2f7582b9.png)

Ich kann den Contact auf zu machen das interessiert die Lampe nicht. Die Anzeige in HomeKit für den Kontakt läuft problemlos.

**Comment by roe1974** [comment]
kann das ähnlich sein wie bei der winmatic .....
laut apple home war sie zu ... laut eve & co nicht ....
kann ja nur am kontakt sensor liegen ... oder ?

**Comment by Sheldor81** [comment]
![8608CBD5-3787-4377-8CCA-5E35192DD801](https://user-images.githubusercontent.com/37243683/81593811-43e05280-93c0-11ea-8820-c5dc5e62f25f.jpeg)

![90E57963-4717-467B-BBB5-99B165211F56](https://user-images.githubusercontent.com/37243683/81593935-725e2d80-93c0-11ea-94df-0dfd56290bee.png)


![5AD87743-1511-4136-9501-FE1BA5EA94ED](https://user-images.githubusercontent.com/37243683/81593980-84d86700-93c0-11ea-9f52-721b182d92f9.png)


Und wenn ich dann nach dem schließen die Tür direkt noch einmal öffne funktioniert es.
![B2E96A10-519F-4C2A-93A8-5BE003C5623B](https://user-images.githubusercontent.com/37243683/81593998-8b66de80-93c0-11ea-9281-fc6d4f523526.png)

**Comment by thkl** [comment]
> kann das ähnlich sein wie bei der winmatic .....

Nein, der Contact hat keinen Target und Current State .. sondern nur einen Current. Bei der Winmatic und auch bei Doors und Windows war das Problem in welcher Reihenfolge ich die Werte setze, das ist aber erledigt, deswegen kommen auch die Pushes von Home

**Comment by Sheldor81** [comment]
Hast du schon eine Idee woran es liegt?

**Comment by thkl** [comment]
Nein

**Comment by roe1974** [comment]
@Sheldor81  .... schon mal einen anderen Auslöser probiert ?
ich meine ich verwende HK automation nicht ... aber geht zum testen WENN Licht 1 "an" ... DANN Licht 2 "an" ... nur um zu sehen ob das geht ?
lg Richard

**Comment by Sheldor81** [comment]
Hallo @roe1974 ,

gerade getestet. Das funktioniert....

**Comment by roe1974** [comment]
hmmmm ... dann ist doch vielleicht irgendwas mit dem Status des Kontakt Sensors.......
Das kann sich nur Thomas ansehen ....

**Comment by Sheldor81** [comment]
Ich habe bei „Besondere Geräte“ mein Garagentor  hinterlegt und wenn ich mit dessen Status eine Automation starte funktioniert es auch.

**Comment by thkl** [comment]
Also Automationen funktionieren bei mir überhaupt nicht.  Weder Wenn Licht an dann Licht2 an noch Wenn Kontakt öffnet dann Licht an oder sowas.  ¯\_(ツ)_/¯

**Comment by Sheldor81** [comment]
Wenn Licht 1 an dann Licht 2 einschalten hat bei mir sofort funktioniert.

**Comment by detLAN** [comment]
> ¯_(ツ)_/¯

Shift + Option + 7 = \ >>> ¯\_(ツ)_/¯ damit er auch einen Arm hat.

**Comment by mike4president** [comment]
bei mir funktionieren die HomeKit Automationen auch nur sporadisch bis gar nicht.

**Comment by Sheldor81** [comment]
Wenn ich zum Beispiel eine Automation mit einem Heizkörperthermostat erstelle, wird diese auch nur sporadisch wie in der Automation vorgegeben eingestellt.

**Comment by roe1974** [comment]
also ich verwende nur "wenn der erste kommt" und "wenn der letzte geht" und schalte damit meine Variable "Anwesenheit" ... das funktioniert zu 100% ..... Automationen laufen bei mir in der CCU ;-)
Frage an @Sheldor81 und @mike4president : Habt Ihr vorher Homebridge-Homematic benutzt ? .... Wenn ja hat es dort funktioniert ?

**Comment by Sheldor81** [comment]
Hallo, ja habe ich. Damit hat es reibungslos funktioniert, ich habe auch extra noch einmal zum testen einige Geräte zurück zu Homebridge gewechselt, damit laufen die gewünschten Geräte in den Automationen problemlos.

**Comment by roe1974** [comment]
Hmmmmmmmmmm ..... Dann kann sich das nur Thomas ansehen ...

**Comment by roe1974** [comment]
@Sheldor81  .... CCU3 oder RM ?

**Comment by Sheldor81** [comment]
RM

**Comment by mike4president** [comment]
@roe1974 : Ne, Homebridge habe ich ausgelassen. Hatte vorher Home Assistant im Einsatz und da ging es auch nicht so richtig

**Comment by thkl** [comment]
Heute hat eine längst vergessene Automation zum ersten mal ausgelöst. Ich war verwundert ... :o)

**Comment by Sheldor81** [comment]
:-)

**Comment by Sheldor81** [comment]
Das wäre ja super, warum ?

**Comment by thkl** [comment]
Es gibt im Contact Sensor eine optionale Characteristic : Characteristic.StatusActive
Die habe ich bisher ignoriert, weil optional  ... Wenn ich die aber dauerhaft auf wahr setze, dann gehen die Automationen .. ist sie false, dann nicht ...

**Comment by Sheldor81** [comment]
Wäre wirklich super denn es dann funktionieren würde.

**Comment by thkl** [comment]
ich behalte das mal im Auge, ggf könnte man das ja irgendwie auch nutzen um Automationen temporär zu blocken ...

**Comment by Sheldor81** [comment]
welche Dateien müssen angepasst werden, dann könnte ich das Verhalten der Automationen nach der Anpassung mal etwas testen.

**Comment by thkl** [comment]
Siehe Commit über mir ..

**Comment by Sheldor81** [comment]
Danke! Habe die Dateien angepasst und aktuell scheint alles wie gewünscht zu funktionieren.

**Comment by thkl** [comment]
Super 👍

**Comment by thkl** [comment]
Ok ich schließe das dann mal hier
