### ISSUE TITLE
service restart ohne Zugriff

### ISSUE THREAD

**Issue by blackbasket** [thkl/hap-homematic#72]
Gibt es eine Möglichkeit, den Service neu zu starten, wenn kein Zugriff mehr auf das Addon besteht? Mal abgesehen vom CCU-reboot meine ich natürlich ;)

Seit v0.0.40 sehe ich den Zugriff auf die URL http://<ccu>/addons/hap-homematic/index.html?sid=@SID@, der dann auf http://<ccu>:9874/?sid=@SID@ redirected wird. Nur antwortet dort nichts mehr.

**Comment by roe1974** [comment]
müsste gehen via ssh mit:
/etc/config/rc.d/hap-homematic restart

**Comment by blackbasket** [comment]
hat funktioniert, danke :)

**Comment by thkl** [comment]
Auf einer RM sollte der Monitor Service das automatisch machen wenn der Prozess eine Weile nicht mehr antwortet.
