### ISSUE TITLE
Homebridge Namen

### ISSUE THREAD

**Issue by JensBonse** [thkl/hap-homematic#73]
Hallo Thomas,

Home bridge Namen dürfen anscheinend nicht alle Zeichen beinhalten.
Ich hatte zwei die hießen 'Homebridge Flur 1.OG' und 'Homebridge Flur 2.OG'. Diese wurden mir nicht angezeigt. Habe dann den Namen geändert und den Punkt aus den Namen entfernt. Tadaaa wurden sie mir in der Home App angezeigt und konnten hinzugefügt werden.
Wäre also super, wenn du da ein Replace drauf laufen lässt. Ggf. steht in der HomeKit Doku irgendwo, welche Zeichen alles nicht im Namen sein dürfen.

**Comment by thkl** [comment]
Ok.  Ich hab das schon in den Gerätenamen. Ich nehme an die Bridges haben die gleichen constraints...

**Comment by JensBonse** [comment]
Hallo Thomas,
in HomeKit kann ich das Zeichen '-' in Namen verwenden. Daher gehe ich davon aus, dass es ein gültiges Zeichen ist. Da ich einige Geräte habe, die im Namen einen - verwenden, wäre es schön wenn das gefixt wird.

**Comment by thkl** [comment]
Oh ich filtere das raus. Wenn Du möchtest kannst Du das testen:
HomeMaticAccessory.js in Zeile 76 für den Channel und 80 für das Device

```
.replace(/[.:#_()-]/g, ' ')
```
muss zu

```
.replace(/[.:#_()]/g, ' ')
```

**Comment by thkl** [comment]
ok geht mit dem - ...

**Comment by thkl** [comment]
Ist das erledigt ?

**Comment by JensBonse** [comment]
Denke schon!
