### ISSUE TITLE
Manuelle Aktualisierung des CCU Caches via WebUI

### ISSUE THREAD

**Issue by roe1974** [thkl/hap-homematic#74]
Hallo Thomas

Wie oben beschrieben tauchen neu hinzugefügte Geräte in der CCU (auch Variablen) nicht in HAP auf .... habe fast 1h gewartet ....
Nach einem reboot von HAP sind sie dann da ;-)

lg Richard

**Comment by Sheldor81** [comment]
Das ist bei mir auch so, dachte aber das es so gewollt ist.

**Comment by roe1974** [comment]
variablen ja .... geräte nein 😉😉

**Comment by thkl** [comment]
Also bei mir geht das ;o)

Ich habe testweise ein Gerät hinzugefügt. Auf dem Server passiert folgendes:

```
[Fri May 15 2020 20:49:42 GMT+0200 (CEST)] [HAP Server] [RPC] <- newDevices on HmIP-RF.. Emit this for the ccu to requery rega (null)
[Fri May 15 2020 20:49:42 GMT+0200 (CEST)] [HAP Server] [CCU] refresh device database on newDevices message from ccu
[Fri May 15 2020 20:49:42 GMT+0200 (CEST)] [HAP Server] [Rega] result is {"devices":[{"id": 1653,"name": " ...
[Fri May 15 2020 20:49:42 GMT+0200 (CEST)] [HAP Server] [Server] CCU DeviceList just changed
[Fri May 15 2020 20:49:42 GMT+0200 (CEST)] [HAP Server] [Server] 121 compatible devices found
```

Unmittelbar danach (genauer gesagt in dem Moment wenn das Gerät im Posteinang der CCU landet) ist das Gerät in der Suche vorhanden wenn man neue Geräte anlegen möchte.

ABER: Wird im Posteingang, oder später der Name des Gerätes geändert, dann bekomme ich das natürlich nicht mit. Denn Bezeichung des Geräte lebt nicht im HmIP / BidCos Interface, sondern in Rega. Daher wird auch kein Event beim Umbenennen des Gerätes in Rega ausgelöst. Ich erfahre also nix von dem neuen Namen. In der Suche ist weiterhin der default Name (Gerätetyp Seriennummer) als Name.

Was auch noch dazu kommt, wenn das Gerät in einen Raum gesetzt wird, oder ein vorhandenes Gerät den Raum wechselt, bekomme ich das auch nicht mit.
Um das Problem zu lösen, würde ich einfach eine Funktion in das WebUI bauen, die einen Reload (wie beim Restart von HAP) triggert.

**Comment by roe1974** [comment]
ok ... es liegt am umbenennen .....
Die Geräte bekommen gleich einen neuen Namen ... und dadurch finde ich sie in HAP nicht ... 😉😜

**Comment by thkl** [comment]
ja, aber ich bin noch nicht glücklich mit dieser Lösung. Noch ein Button den man drücken muss ;o( Zu blöd das Rega keine Events schickt ...

**Comment by roe1974** [comment]
könnte man nicht beim aufruf der UI einmalig automatisch ein reload machen ?

**Comment by thkl** [comment]
Dann hast Du das UI in einem 2. Browsertab und schon funktioniert es nicht mehr konsistent ;)

**Comment by roe1974** [comment]
hmmmmmm .... stimmt :(

**Comment by JensBonse** [comment]
Wie wäre es mit einem Knopf, der eingeblendet wird, sobald eine Suche kein Ergebnis liefert?
Nach dem Motto ‚auf der CCU suchen‘. Wo dann der Cache refresht wird. Dann wäre der nicht immer da...

**Comment by thkl** [comment]
Nice ! Nur was mache ich wenn die Suche zwar ein Ergebnis liefert, aber eigentlich 2 erwartet werden, weil die Suche auf einen alten Devicenamen matcht ...

**Comment by roe1974** [comment]
keep it simple ... reload knopf und gut ist es.
Man weiß ja wenn man neue geräte/variablen hinzugefügt hat 😉
