### ISSUE TITLE
Gerät hinzufügen nicht möglich

### ISSUE THREAD

**Issue by santofulminante** [thkl/hap-homematic#75]
Die Einrichtung der Instanzen auf der CCU hat funktioniert. Nur beim einfügen in die Home-App zeigt diese nach minutenlangen laden "HomeMatic EG Bad 7B3B konnte nicht hinzugefügt werden". 

Die HomeMatic default Instanz hat dagegen direkt funktioniert. Aber alle anderen leider nicht. Woran könnte das liegen?

**Comment by mike4president** [comment]
Ports in der Firewall freigegeben?

**Comment by mike4president** [comment]
für jede Instanz wird ein eigener Port benötigt

**Comment by roe1974** [comment]
Ports 9877..n ... also bei zB 5 Instanzen die Ports:

9877
9878
9880
9881
9882

... freischalten

**Comment by mike4president** [comment]
<img width="942" alt="Bildschirmfoto 2020-05-15 um 12 45 14" src="https://user-images.githubusercontent.com/65063329/82042451-2a822380-96aa-11ea-9625-a846fc1e20c2.png">
<img width="963" alt="Bildschirmfoto 2020-05-15 um 12 46 26" src="https://user-images.githubusercontent.com/65063329/82042455-2bb35080-96aa-11ea-9b40-02544703f6e5.png">

**Comment by santofulminante** [comment]
Oh man...ich bin auch nicht gerade die hellste Kerze auf der Torte. Vielen Dank. So klappt es natürlich

**Comment by thkl** [comment]
Ich schau mal ob ich einfach beim Anlegen der Instanz die Ports auf der Firewall auf machen kann.

**Comment by thkl** [comment]
Ich werde die Firewall wohl eher nicht anfassen aber anzeigen wenn Ports, die benötigt werden, nicht offen sind:

![image](https://user-images.githubusercontent.com/884355/82141032-7ad8bd00-9833-11ea-8834-b693fa7e2beb.png)

+ ein Text unten was (!!) bedeutet

**Comment by roe1974** [comment]
@thkl kannst du sie auch rot machen wenn der port fehlt ?

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/82141341-6ac1dd00-9835-11ea-915e-077c6a096130.png)
