### ISSUE TITLE
Homematic inside

### ISSUE THREAD

**Issue by mike4president** [thkl/hap-homematic#76]
Moin,

ich hab mal veranlasst, dass das Plugin hier mit aufgenommen wird. Bisher funktioniert es hervorragend. hab seid gestern alle Geräte (mit Ausnahme der Alarmsirene) eingebunden. 

https://www.homematic-inside.de/software/tag/Zusatzsoftware

Ich hab auch noch einen Vorschlag. Die Kopplung meiner Hue Geräte ist nicht so wirklich der Hit. Könnte man in diesem Plugin HomeKit Geräte als virtuelle Geräte an die CCU3 zurückmelden, also praktisch in die andere Richtung. 

Ich weiß es gibt HVL, das hat aber zumindest bei mir überhaupt nicht geklappt. Im Grunde benötige ich nur 2 Funktionen von HVL:

eine virtuelle Wetterstation und die Einbindung von Hue. Könnte man das nicht auf einfacherer Weise hier integrieren und das Aden somit noch attraktiver machen? 

Grüße

**Comment by thkl** [comment]
Eher nicht. Die CCU hat ja eine eigene Kopplung zu Hue.

Dein HVL Problem gehört eher dort hin. Das Ding fasse ich irgendwann ggf auch mal wieder an :)
