### ISSUE TITLE
Batteriestatus in HomeKit 

### ISSUE THREAD

**Issue by mike4president** [thkl/hap-homematic#77]
Hallo, auch auf die Gefahr, dass die Frage bescheuert ist, aber wäre es möglich den Batteriestatus der Homematic Gerät an HomeKit zu übergeben? Ich fände es ganz hilfreich dort zu sehen, wenn die CCU eine schwache Batterie meldet. 

![36111031-1d6a1288-1025-11e8-8821-5921a77ce1e5](https://user-images.githubusercontent.com/65063329/82233574-84941a80-9930-11ea-8f58-18815fedff6e.png)

**Comment by thkl** [comment]
ich dächte ich hätte das schon eingebaut .. ich schau mir das mal an ...
wird etwas dauern ....

**Comment by mike4president** [comment]
Besten Dank. Hab gerade nochmal alle Geräte durchgeschaut. In der Eve App werden teilweise Batteriestaus angezeigt. In der Home App leider nicht...

**Comment by thkl** [comment]
Jo hab mehrere Fehler gefunden. 

![image](https://user-images.githubusercontent.com/884355/82239678-71397d00-9939-11ea-9444-985f6ab25a56.png)


Bei HM Geräten gibt es nur LowBat deswegen da 0 oder 100% ... bei HMIP wird teilweise die Spannung bereitgestellt da rechne ich dann die % aus.

**Comment by mike4president** [comment]
Verstanden. Ich nutze ausschließlich IP Geräte. Hab meine Liste gerade mal durchgeschaut in der CCU3. Bei fast allen wird die Spannung angegeben. Ich nutze ausschließlich Lithium Batterien. Da ist sie auch etwas höher als bei Alkali Batterien. Die Energizer Lithium Batterien halten bei mir eeewig!

**Comment by thkl** [comment]
Da ich recht wenig IP Geräte besitze müsste ich dann mal bei Gelegenheit wissen, bei welchen Geräten es bei Dir nicht funktioniert und wie die default Spannung ist. Dann kann ich das nachtragen. Derzeit geht das nur beim IP Motion Control, die Dinger hab ich ;)

LowBat sollte aber gehen ...

**Comment by mike4president** [comment]
Suche ich für alle meine Geräte raus nachher

**Comment by roe1974** [comment]
ich sehe hier bei keinem einzigen kontakt sensor (alle HM) einen Batterie Status in Home ?!?!

**Comment by thkl** [comment]
ja nextes Release ... ist doch erst hier https://github.com/thkl/hap-homematic/commit/6568b468255e37f2f04105304289b13d2c6f0db0 gefixt worden ... herrjehmine

**Comment by mike4president** [comment]
ich wie gesagt auch nicht. 

hier die Spannung für die ersten Geräte. Das sind alles Geräte, bei denen ich erst kürzlich die Batterien gewechselt habe. Aber ich setze wie gesagt Energizer Lithium Batterien an, weil die doppelt so lange halten. 

<img width="1199" alt="Bildschirmfoto 2020-05-18 um 19 49 12" src="https://user-images.githubusercontent.com/65063329/82244719-f58ffe00-9941-11ea-8d47-6999e2f49536.png">
<img width="1197" alt="Bildschirmfoto 2020-05-18 um 19 50 35" src="https://user-images.githubusercontent.com/65063329/82244727-f759c180-9941-11ea-9b94-00f14f6c94df.png">
<img width="1197" alt="Bildschirmfoto 2020-05-18 um 19 51 28" src="https://user-images.githubusercontent.com/65063329/82244738-f9238500-9941-11ea-904a-afcc4f185432.png">
<img width="1197" alt="Bildschirmfoto 2020-05-18 um 19 52 11" src="https://user-images.githubusercontent.com/65063329/82244746-fc1e7580-9941-11ea-95f8-b3d1af69160c.png">
<img width="1197" alt="Bildschirmfoto 2020-05-18 um 19 56 06" src="https://user-images.githubusercontent.com/65063329/82244754-ff196600-9941-11ea-831f-5f9cfcebb3ed.png">

**Comment by roe1974** [comment]
> ja nextes Release ... ist doch erst hier https://github.com/thkl/hap-homematic/commit/6568b468255e37f2f04105304289b13d2c6f0db0 gefixt worden ... herrjehmine

okeeeeee ....  nicht gesehen 😜😜😜😜

**Comment by mike4president** [comment]
es könnte sein, dass die Spannung bei den Lithium Dingern etwas höher ist... Für folgende Geräte liefer ich das noch nach: Da sind die Alkali Batterien schon ewig drinnen und daher wäre der Wert wohl nicht korrekt.

HmIP-STHO
HmIP-SPI
HmIP-STHD
HmIP-SWDM
HmIP-SWDO-I
HmIP-SWD

**Comment by mike4president** [comment]
vielleicht können die anderen hier ja auch helfen die Werte zu vervollständigen

**Comment by thkl** [comment]
Naja ich gehe mal von 1,2V pro AAA Batterie aus .. daher 1 Batterie = 1,2V 2 = 2,4 .. etc ich müsste also nur wissen wieviele Batterien in den Dingern ist .. wenn ich > 100% Akku an Homekit liefere wird das eh auf 100 beschnitten

**Comment by mike4president** [comment]
1,2 Volt eigentlich nur bei wiederaufladbaren Batterien. 

normale Alkali AAA haben 1,5 Volt und AA auch 1,5 Volt

**Comment by thkl** [comment]
tja nun ;) irgendwas muss ich ja als 100% nehmen ....

**Comment by mike4president** [comment]
Stimmt, ich glaube ich war hier gedanklich gerade zu kompliziert unterwegs. 120 % Batterie... yeah!!!!!! oh Man(n) sorry!

Auf der Homematic IP Seite ist auch pro Gerät die Anzahl der Batterien plus Batterietyp angegeben...

**Comment by thkl** [comment]
Jep, da HomeKit maximal 100% zulässt sollte das kein Problem sein. Und die LowBat Warnung wird durch die CCU getriggert.

**Comment by mike4president** [comment]
okay, ich dachte, dass mit der Low Batterie Schwelle dann auch der Prozentwert errechnet wird. Aber Low Batterie Warnung reicht mir schon. ich muss eigentlich nicht wissen, ob die Batterie nur 90 oder 70 Prozent hat.

**Comment by mike4president** [comment]
Danke für die schnelle Rückmeldung. Schönen Abend noch

**Comment by thkl** [comment]
Jaaaaaa, dann kommt gleich wieder einer um die Ecke, der feststellt Oh hier gibts ja Voltage reading. Kann man da nicht % anzeigen ....

**Comment by mike4president** [comment]
kurze Frage vorab: Wenn die Batterieanzeige zukünftig funzt... muss ich die Geräte dann neu in HomeKit anlegen oder passiert das im Hintergrund?

**Comment by thkl** [comment]
Es muss nichts gemacht werden. Der Status für die 🔋 kommt einfach von alleine dazu.

**Comment by mike4president** [comment]
Prima! Danke 🙏

**Comment by thkl** [comment]
Eine Sache noch: Nach einem CCU reboot, kann es sein, das einige Geräte im HomeKit leere Batterien melden. Das ändert sich, sobald diese das erste mal eine Statusänderung, und damit auch ihren richtigen Batteriezustand an die CCU gesendet haben. Vorher weiß die CCU Logigschicht noch nichts von dem Ladezustand und gibt einfach 0 zurück.

**Comment by mike4president** [comment]
ok... danke für die Info

**Comment by mike4president** [comment]
Klasse!!!! Die optischen und magnetischen Kontaktsensoren, Heizkörperthermostate (wenn nicht die Heizgruppe hinterlegt wurde), Wassersensoren und Feuermelder zeigen nun den Batteriestatus an :-) Beim Präsenzemelder sieht man den Status wenn die einzelnen Geräte für Helligkeit und Bewegung aufruft (Ich hab das in HomeKit in einer Kachel). 


![IMG_0151](https://user-images.githubusercontent.com/65063329/82733083-c1d22100-9d11-11ea-8e9c-8a144f1e02b4.png)


![IMG_0153](https://user-images.githubusercontent.com/65063329/82733073-b3840500-9d11-11ea-9955-1a838dc67980.jpeg)


Bei 

HmIP-STHO
HmIP-STHD (auch nicht in den Einzelgeräten für Luftfeuchtigkeit bzw Temperatur)
HmIP-WTH-2 (auch nicht in den Einzelgeräten für Luftfeuchtigkeit bzw Temperatur)

geht es noch nicht. 

Ein guter Anfang ;-) Danke

**Comment by thkl** [comment]
was geht für STHO STHD WTH nicht ? Batterie ?

**Comment by mike4president** [comment]
genau! Da wird hinter den Einzelgeräten für für Temperatur und Luftfeuchtigkeit kein Batteriestatus übermittelt. 
![IMG_0159](https://user-images.githubusercontent.com/65063329/82733304-3bb6da00-9d13-11ea-9388-c29cb68dbf67.png)

**Comment by thkl** [comment]
stimmt, die Klasse hat kein     
```
this.addLowBatCharacteristic()
```

im init. ich trage das mal nach

**Comment by mike4president** [comment]
eine Kleinigkeit ist mir außerdem noch aufgefallen. Ich habe in Homekit meine in der CCU angelegte Heizgruppe bestehen aus Thermostat, Fensterkontakt und Wandthermostat als Heizkörperthermostat in Homekit angelegt. Das habe ich gemacht, damit in Eve dort auch die Luftfeuchtigkeit reported wird. 

![IMG_0158](https://user-images.githubusercontent.com/65063329/82733362-9819f980-9d13-11ea-85d1-9a2436bea47d.jpeg)

Dadurch wird jetzt bei den Geräten in Eve eine leere Batterie gemeldet. 



![IMG_0157](https://user-images.githubusercontent.com/65063329/82733393-bda70300-9d13-11ea-8805-bbe7038061c6.png)
![IMG_0156](https://user-images.githubusercontent.com/65063329/82733401-cd264c00-9d13-11ea-9fdb-12860073b07d.jpeg)
Wenn ich ausschließlich das Heizkörperthermostat in Homekit anlege, funktioniert alles. Liegt also an der Gruppe. Nur zur Info

**Comment by mike4president** [comment]
cool... Fehler schon gefunden... sehr schön...

**Comment by thkl** [comment]
oh ok .. ich prüfe zwar ob das Gerät einen LOW_BAT / LOWBAT Datenpunkt zurückmeldet aber scheinbar ist das bei den Gruppen komisch .... ich schau mal

**Comment by mike4president** [comment]
ok... ich fand es sinnvoller die Gruppe in HomeKit anstatt nut des Thermostats anzulegen, da dann in Eve eher das gemeldet wird, was ich zum Heizkörperthermostat benötige...

**Comment by thkl** [comment]
Also die Gruppe hat ein LowBat und der wird bei mir auch nicht als Leer angezeigt:

![image](https://user-images.githubusercontent.com/884355/82733627-58541180-9d15-11ea-8465-46a118e8585e.png)

**Comment by mike4president** [comment]
komisch.. also in meiner CCU Gruppe sind ein IP Heizkörperthermostat, ein optischer IP Fenstersensor und ein IP Wandthermostat. Daher sieht das bei mit anders aus... Bei mir wird in der Gruppe zusätzlich die Luftfeuchtigkeit angezeigt. Kann es damit zu tun haben? Die Batterie wird mir 0 Prozent angezeigt

![IMG_0160](https://user-images.githubusercontent.com/65063329/82733708-0364cb00-9d16-11ea-9539-43a32030b20d.png)

**Comment by thkl** [comment]
Ah MOMENT ! ich habe keine IP Gruppe sondern eine Heizungsgruppe mit nicht IP Geräten ... 


kannst du mal im "Script testen" auf der CCU das hier ausführen:


```
var dadr = "INT0000002";
var dpl = "LOWBAT\tLOW_BAT\tOPERATING_VOLTAGE";
string dpn;
foreach (dpn, dpl) {
  WriteLine("Check "# dpn );
  var adr = "VirtualDevices." # dadr # ":0." # dpn;
  var x = dom.GetObject(adr);
  if (x) {
   WriteLine(dpn # " is here");
   WriteLine(dpn # " level is " # x.State());
  } else {
   WriteLine(dpn # " is missing");
  }
}
```

ggf oben in dadr = "" die Nummer der Gruppe anpassen.

Bei HM Gruppen kommt diese Ausgabe:

```
Check LOWBAT
LOWBAT is here
LOWBAT level is false
Check LOW_BAT
LOW_BAT is missing
Check OPERATING_VOLTAGE
OPERATING_VOLTAGE is missing
````

**Comment by mike4president** [comment]
Check LOWBAT
LOWBAT is missing
Check LOW_BAT
LOW_BAT is here
LOW_BAT level is false
Check OPERATING_VOLTAGE
OPERATING_VOLTAGE is missing

**Comment by thkl** [comment]
okay, danke für die Info.
Ich simuliere das mal in einer Testumgebung ...

**Comment by thkl** [comment]
Kannst Du mal auf der WebOberfläche von HAP unter Interns / Hilfe für deine Heizungsgruppe das Devicefile erstellen lassen und hier anhängen. Die Seriennummer ist die gleiche wie bei dem Testscript oben.

**Comment by mike4president** [comment]
{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HmIP-HEATING",
      "address": "4762653007ABCD",
      "type": "HmIP-HEATING",
      "channels": [
        {
          "id": 1001,
          "name": "4762653007ABCD:0",
          "intf": 0,
          "address": "4762653007ABCD:0",
          "type": "MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "4762653007ABCD:1",
          "intf": 0,
          "address": "4762653007ABCD:1",
          "type": "HEATING_CLIMATECONTROL_TRANSCEIVER",
          "access": 255
        },
        {
          "id": 1003,
          "name": "4762653007ABCD:2",
          "intf": 0,
          "address": "4762653007ABCD:2",
          "type": "HEATING_CLIMATECONTROL_SWITCH_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1004,
          "name": "4762653007ABCD:3",
          "intf": 0,
          "address": "4762653007ABCD:3",
          "type": "ROTARY_HANDLE_TRANSCEIVER",
          "access": 255
        },
        {
          "id": 1005,
          "name": "4762653007ABCD:4",
          "intf": 0,
          "address": "4762653007ABCD:4",
          "type": "SWITCH_TRANSMITTER",
          "access": 255
        },
        {
          "id": 1006,
          "name": "4762653007ABCD:5",
          "intf": 0,
          "address": "4762653007ABCD:5",
          "type": "KEY_TRANSCEIVER",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by thkl** [comment]
AH ich habs raus. 

Die Gruppe triggert die Nutzung von HomeMaticRadiatorThermostatAccessory diese hat laut meiner Definition eine Batterie mit 2,4 Volt ... leider hat, siehe oben die Gruppe aber keinen Datenpunkt OPERATING_VOLTAGE ... die Abfrage erzeugt dann einen 0 und der Rest ist zu sehen

**Comment by mike4president** [comment]
ok, kann ich also nur das einzelne Heizkörperthermostat dann in Homekit hinterlegen und muss die Gruppe wieder rausschmeißen?

**Comment by thkl** [comment]
ne ich fix das in der nächsten Version.

**Comment by mike4president** [comment]
ah okay... Danke...

**Comment by thkl** [comment]
ok https://github.com/thkl/hap-homematic/commit/f9c67125d59d10d98475f138de51da8d7f725ce9  fixt das dann 

![image](https://user-images.githubusercontent.com/884355/82735345-598b3b80-9d21-11ea-9305-db94a2810b50.png)

wird dann in .43 eingehen.

**Comment by mike4president** [comment]
Sehr schön

**Comment by detLAN** [comment]
Bei meinen HmIP-SRH wird immer 100% angezeigt, obwohl einige bereits an der Grenze zu 1,0 V liegen.

{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HmIP-SRH",
      "address": "9186757108ABCD",
      "type": "HmIP-SRH",
      "channels": [
        {
          "id": 1001,
          "name": "9186757108ABCD:0",
          "intf": 0,
          "address": "9186757108ABCD:0",
          "type": "MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "9186757108ABCD:1",
          "intf": 0,
          "address": "9186757108ABCD:1",
          "type": "ROTARY_HANDLE_TRANSCEIVER",
          "access": 255
        },
        {
          "id": 1003,
          "name": "9186757108ABCD:2",
          "intf": 0,
          "address": "9186757108ABCD:2",
          "type": "ALARM_COND_SWITCH_TRANSMITTER",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by thkl** [comment]
Für den habe ich noch keine🔋 Infos hinterlegt. Daher rechnet da noch nix sondern die Anzeige ist 100% und sobald es einen LowBat Event gibt fällt sie auf 0. 

Was sind da für Batterien drin ? Bzw wie ist denn die Spannung bei 100% 🔋

**Comment by detLAN** [comment]
Nehme seit Jahren [Paradies Batterien Power Alkaline](https://www.dtgv.de/tests/test-batterien-aaa-micro-welche-ist-die-beste-batterie/) von DM.

**Comment by thkl** [comment]
Die Frage war eher LCR44 AA oder AAA bzw wieviele damit ich aus Soll und Ist die % rechnen kann 😁

**Comment by detLAN** [comment]
Es ist eine AAA.

**Comment by thkl** [comment]
ok also 1,2 V wenn man Akkus nimmt ..

**Comment by detLAN** [comment]
Das sind 1,5 V Batterien.

**Comment by detLAN** [comment]
Auch der HmIP-SWDO verwendet diese.

{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HMIP-SWDO",
      "address": "3077353483ABCD",
      "type": "HMIP-SWDO",
      "channels": [
        {
          "id": 1001,
          "name": "3077353483ABCD:0",
          "intf": 0,
          "address": "3077353483ABCD:0",
          "type": "MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "3077353483ABCD:1",
          "intf": 0,
          "address": "3077353483ABCD:1",
          "type": "SHUTTER_CONTACT",
          "access": 255
        },
        {
          "id": 1003,
          "name": "3077353483ABCD:2",
          "intf": 0,
          "address": "3077353483ABCD:2",
          "type": "ALARM_COND_SWITCH_TRANSMITTER",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by detLAN** [comment]
LR03 1,5 V Micro

**Comment by mike4president** [comment]
Thomas muss trotzdem 1,2 Volt als 100 Prozent nehmen für die Leute die Akkus verwenden. Mit deinen 1,5 Volt bist du dann halt so lange bei 100 Prozent bis die Spannung nachlässt und darunter fällt. Hab den gleichen Gedankenfehler gemacht.

**Comment by detLAN** [comment]
Die Frage wäre nur, wieviel Nutzer setzen teure Akkus ein. Rein rechnerisch lohnen Akkus einfach nicht, die kann man auch nicht ewig neu laden.

**Comment by roe1974** [comment]
also eneloop pro akkus sind voll geladen auch bei ca 1,45 Volt ...

**Comment by thkl** [comment]
Ich hab überall Akkus weil ich nicht dauernd Batterien wegwerfen möchte. Ich nehm 1,2 V (hab ja auch 2,4 bei den 2 Batterie Geräten) Ein LowBat aus der CCU triggert das LowBat in HomeKit , der Rest ist nur schön anzusehen.

**Comment by thkl** [comment]
der HMIP-SWDO als HomeMaticContactSensorAccessory sollte aber schon eine Batterieanzeige haben .... Rest kommt

**Comment by mike4president** [comment]
HMIP-SWDO hat bei mir schon eine Batterieanzeige

**Comment by detLAN** [comment]
Schon merkwürdig dass das Batteriesymbol eine hohe Ladung verspricht, im zweiten Bild sogar den Ladestand in Prozent verrät, mir aber gleichzeitig mitgeteilt wird, dass ich mein Gerät aufladen möge. Was darf ich jetzt glauben?
Es handelt sich um ein HmIP-eTRV-2 (2 x Batterie Mignon LR6 / Mignon AA). Hier ist die Spanne von 3.0 V (voll) bis 2.0 V (leer). CCU gibt bei 2.1 V eine entsprechende Meldung - was sie in diesem Fall auch tut.

Räume - Gerät:
![IMG_0924](https://user-images.githubusercontent.com/64675966/82894546-07c9f780-9f53-11ea-9ab7-a897451635be.jpg)

Einstellungen - Geräte:
![IMG_0925](https://user-images.githubusercontent.com/64675966/82894551-0b5d7e80-9f53-11ea-872f-02e59cd30135.jpg)

**Comment by thkl** [comment]
Das liegt daran das die % Angaben aus einer festen Max Volt Zahl und der aktuellen Spannung berechnet werden und der Zustand Laden/Nicht aus der CCU mit dem LowBat Datenpunkt kommen. 

Ich hätte nur die Idee, die fest eingetragenen Volt für Batterie voll flexibel konfigurierbar zu machen.

**Comment by mike4president** [comment]
Blöde Frage: Ist der Zustand Laden verpflichtend für HomeKit? Macht ja bei den Homematic Teilen wenig Sinn.

**Comment by mike4president** [comment]
Mit persönlich würde die Prozentanzeige bzw Hinweis LowBat reichen ohne eine Ladeempfehlung

**Comment by detLAN** [comment]
Vielleicht könnte die Berechnung etwas genauer passieren, wenn HAP wüsste was verbaut ist, also Batterie, Akku oder Netzgerät (HmIP-BPS). Da für jedes Gerät feststeht was für Typen gebraucht werden AA oder AAA und wieviel davon, kann HAP dann durch die Angabe des Batterietyps die Berechnung präzisieren. Vielleicht reicht im HAP Gerät-Einstellungsdialog ein DropDown-Menü mit den Vorgaben Batterie, Akku (ggf. welche Spannung - Akku a, Akku b) und Netzbetrieb. Mit den Angaben müsste für jeden Fall annähernd die richtigen Werte ermittelt werden können. Default sollte Batterie sein, da diese bei Fertiggeräten mitgeliefert werden.

**Comment by thkl** [comment]
naja, dann müsste man das aber bei allen Geräten wieder in den Einstellungsdialog bauen. Denn was ist wenn ich einige Geräte auf Akku habe und einige, weil sie neu sind or whatever, auf Batterien ... das sind schon wieder viel zu viele Konfigurationsknöpfchen.

**Comment by thkl** [comment]
> Mit persönlich würde die Prozentanzeige bzw Hinweis LowBat reichen ohne eine Ladeempfehlung
> 
> Oder brauch man das, damit man die Batterieanzeige in Eve hat?

Ich kann in HomeKit 2 Sachen setzen a) Batterie Normal oder Batterie leer  und b) optional dazu die Prozentuale Batterieladung also das was als % da steht.
Den Rest macht Eve. Die Batterie Leer/nicht Leer Info kommt auf jeden Fall vom LOWBAT des Gerätes. Diesen Datenpunkt gibt es in HmIP und HM ... zusätzlich gibt es bei den IPs noch OPERATING_VOLTAGE was die aktuelle Spannung angibt. Die % rechne ich aus der Vorgabe pro Gerät und dieser Info.

**Comment by mike4president** [comment]
HmIP-STHO Batteriestatus geht jetzt
HmIP-STHD Batterieanzeige geht jetzt
HmIP-WTH-2 Batterieanzeige geht jetzt

Ich weiß nicht ob das Thema hier offen aber Heizgruppe bestehen aus HmIP-STHD,HMIP-SWDO und HmIP-eTRV-2 melden jetzt auch einen Batteriestatus. HmIP-eTRV-2 einzeln auch
