### ISSUE TITLE
Firmware Updates

### ISSUE THREAD

**Issue by mike4president** [thkl/hap-homematic#79]
Noch eine letzte Idee: HomeKit erlaub ja inzwischen auch die Benachrichtigung über Firmware Updates. Könnte man die Servicenachrichten aus der CCU ebenfalls nutzen und an HomeKit übergeben? 

![f8cUSBA88z2qWRdqFg1w4ASRmNq-xdI5XmSyzUaQ0pI](https://user-images.githubusercontent.com/65063329/82608021-36924780-9bba-11ea-8050-be99ddc21196.jpg)

**Comment by thkl** [comment]
Soweit ich weiß, geht das nur für von Apple abgenickte Geräte. Ich habe keine passende Characteristic dafür im HomeKit Simulator gefunden.

**Comment by mike4president** [comment]
ah okay, schade... das hier hilft auch nicht weiter?

https://developer.apple.com/documentation/homekit/hmaccessory?language=objc

**Comment by mike4president** [comment]
hab nur mal gegoogelt auch wenn ich natürlich keinen blassen Schimmer davon habe

**Comment by thkl** [comment]
Das ist die Client Seite. Die Klassen brauch ich, wenn ich eine Controller App für HomeKit schreiben möchte.  

Was hier gefragt wäre, ist genau die Gegenseite.

**Comment by mike4president** [comment]
ah okay... kann man dieses Projekt eigentlich unterstützen? Bei HVL gibt es doch so eine Spendenbutton... Kann der hier nich auch hin? Ich hab wirklich noch keine einfacherer Möglichkeit gefunden Homkit einzurichten

**Comment by thkl** [comment]
Muss ich bei Gelegenheit mal noch einbauen.

**Comment by mike4president** [comment]
okay, find ich gut! Danke schon mal für deine ganze Mühe... ich hab mir wegen deines Addons überhaupt erst die CCU gekauft. :-) Hatte das Video auf verdrahtet gesehen. Da ich mir über HomeKit diese ganze Cloudmatic Geschichte sparen kann, bin ich ziemlich glücklich damit.
