### ISSUE TITLE
Update funktioniert nicht

### ISSUE THREAD

**Issue by blackbasket** [thkl/hap-homematic#8]
Hallo Thomas,

ich mal wieder. Ich habe mir die 0.0.3 heruntergeladen und zweimal versucht über Zusatzsoftware zu aktualisieren. Leider bleibt die Version 0.0.25.

PS: Nach dem Neustart der CCU muss ich den HAP Service nochmal neu starten, damit die Devices auftauchen. Oder die 4 Minuten uptime des HAP Service waren zu kurz und ich zu ungeduldig ;)

LG,
Marcel

**Comment by thkl** [comment]
Das CCU Addon installiert nur die aktuelle npm Version.  Die ist 0.0.25 :) Das Plugin selber kann sich dann eigenständig Updaten.  Die neue Addon Version ist nur für die kommende (optionale) CCU basierende Userauthentication nötig

**Comment by thkl** [comment]
Und ja das Thema mit den Geräten löst die nächste Version auch. Problem ist hier das die CCU das Plugin schon startet obwohl Rega noch nicht komplett läuft. Ab der nächsten Version warte ich auf eine gültige Antwort von Rega (das ist die CCU Logicschicht die auch die Gerätedatenbank hält) bevor das Plugin überhaupt weiter hochfährt ...

**Comment by blackbasket** [comment]
ok, dann warte ich mal, dass sich das Update lädt und teste die Heizung danach. ist ja nicht dringend ;)

**Comment by thkl** [comment]
BTW: Das Plugin zeigt auf seiner Webseite oben rechts an, wenn ein neues Update verfügbar ist ... das aktualisiert sich auch automatisch
