### ISSUE TITLE
Kleinigkeit: Besondere Geräte HomeMaticSPCCUTempAccessory

### ISSUE THREAD

**Issue by mike4president** [thkl/hap-homematic#80]
Hi, das besondere Gerät HomeMaticSPCCUTempAccessory erzeugt keine fakegato Daten. Ist nur Schmuck am Nachthemd... aber fand ich ganz nett ;-)

**Comment by thkl** [comment]
Die Daten werden schon erzeugt, aber ich habe keinen Schimmer, warum sie nicht in eve angezeigt werden.
![image](https://user-images.githubusercontent.com/884355/82608736-81608f00-9bbb-11ea-838d-ad2262d78f82.png)

**Comment by mike4president** [comment]
nicht dramatisch... war mir bloß aufgefallen, weil ich gucken wollte, wie das Temperaturverhalten meiner CCU war. Ich hab in meiner CCU3 ein Tinkerboard S eingebaut. Das Auslesen der Temperatur funktioniert trotzdem

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/82671966-fecde300-9c3f-11ea-9009-fbac384015db.png)

😁😁😁😁😁

**Comment by mike4president** [comment]
Cool 😎 👍

**Comment by thkl** [comment]
die Ursache hat mich jetzt 2h Suche gekostet ;) ... AccessoryInformation hat ein Feld Characteristic.Model .. das wird normal mit dem Typ des CCU Channels befüllt. (ist ein Textfeld) ... Variablen und der Temp Sensor haben dieses Feld einfach leer gelassen. Das fand eve halt nicht so cool ...

**Comment by mike4president** [comment]
jetzt geht es... super... ich schließe dann mal dieses Issue. Besten Dank


![IMG_0155](https://user-images.githubusercontent.com/65063329/82733194-83893180-9d12-11ea-9b39-6a54838dceb8.png)
