### ISSUE TITLE
Schönheitsfehler

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#82]
<img width="1140" alt="Bild 1" src="https://user-images.githubusercontent.com/64675966/82734136-0ca36700-9d19-11ea-9240-f2de7f5670e4.png">
<img width="293" alt="Bild 2" src="https://user-images.githubusercontent.com/64675966/82734143-1331de80-9d19-11ea-9d7d-80b0a275fd47.png">

**Comment by thkl** [comment]
🤯

aber ja

**Comment by staudy83** [comment]
Bei der heutigen Erstinstallation (Assistent) war ich beim anklicken der Räume etwas verwundert. Wenn man zwischen den beiden Seiten hin und her wechselt, sind alle Haken wieder verschwunden.

Trotzdem sind alle beim klicken auf weiter ausgewählt.

**Comment by staudy83** [comment]
Kann es sein das die Suchfunktion bei den Geräten nicht funktioniert? Wenn ich nach den Gerätenamen bzw. den Seriennummern suche bleibt alles unverändert.

**Comment by mike4president** [comment]
geht bei mir bei den bereits hinzugefügten Geräten auch nicht mehr seit gestern... die Suche, wenn ich ein neues Gerät hinzufüge geht bei mir aber noch...

**Comment by mike4president** [comment]
das muss sich Thomas wohl mal ansehen :-)

**Comment by roe1974** [comment]
Siehe #83 .... ist bereits bereinigt für die nächste Version...

**Comment by staudy83** [comment]
> geht bei mir bei den bereits hinzugefügten Geräten auch nicht mehr seit gestern... die Suche, wenn ich ein neues Gerät hinzufüge geht bei mir aber noch...

Korrekt, die Suche hinter dem Button "NEU" funktioniert.

**Comment by staudy83** [comment]
> Siehe #83 .... ist bereits bereinigt für die nächste Version...

Sorry, bin neu hier. Habe ich jetzt auch unter den "closed" gefunden.

**Comment by mike4president** [comment]
Herzlich willkommen :-)

**Comment by mike4president** [comment]
Schönheitsfehler CCU Cache aktualisieren behoben...


Die Suche funktioniert wieder

**Comment by thkl** [comment]
Ja aber der Cache macht noch keine Message an den User wenn er aktualisiert wurde deswegen würde ich das hier noch offen lassen
