### ISSUE TITLE
Problem mit der letzten Instanz

### ISSUE THREAD

**Issue by detLAN** [thkl/hap-homematic#84]
Die Instanz ist installiert, Port in CCU freigegeben, aber es gibt keine Geräte.
<img width="1264" alt="Bild 1" src="https://user-images.githubusercontent.com/64675966/82735653-84768f00-9d23-11ea-8d75-672fb8827be6.png">

Unter Geräte wird die Instanz ausgegraut.
<img width="1055" alt="Bild 2" src="https://user-images.githubusercontent.com/64675966/82735683-b8ea4b00-9d23-11ea-97f5-b575407f7b9e.png">

Mit den anderen Räumen gibt es keine Probleme. Instanz bereits gelöscht und neu eingerichtet, ohne Erfolg. Wo könnte das Problem liegen? Vielleicht dass es die letzte Instanz, der letzte Port ist?

**Comment by thkl** [comment]
Hat diese unter Instanzen / Einstellungen das Publish Häkchen. ? Das bekommt sie nicht automatisch, damit man sie ohne Geräte in HomeKit erst mal einem Raum zuordnen kann ohne das für alle Geräte machen zu müssen.

**Comment by detLAN** [comment]
Das Häkchen fehlte, läßt sich aber auch nicht dauerhaft setzen. Wenn ich wieder in Instanzen Einstellungen gucke, ist es nicht mehr gesetzt.
Noch zur Info, ich habe wieder mal ganz neu angefangen, also auch den Assistenten bekommen, dort natürlich auch die betreffende Instanz mit eingerichtet, inkl. dann auch der Geräte. Weder Instanz noch Geräte wurden übernommen.

**Comment by detLAN** [comment]
Okay, da war beim Probieren noch ein Gerät mit ausgegrauter Instanz, nach löschen des Geräts bleibt das Häkchen stehen.

**Comment by thkl** [comment]
Das Häkchen hat 2 Bedingungen:
1. Es existiert mindestes 1 Gerät in dieser Instanz UND 
2.das Häkchen wurde einmalig gesetzt

Da widerspricht zwar Deinem Kommentar oben drüber, ist aber so ;)


Der Ablauf wäre : 
Instanz anlegen -> Instanz wird ohne Geräte (Häkchen) in HomeKit aufgenommen und ein Raum zugewiesen -> Geräte hinzufügen -> Publish Häkchen setzen ... Geräte fallen in HomeKit in den Raum wo die Bridge ist. .. Häkchen bleibt und wird auch ausgegraut.

**Comment by detLAN** [comment]
Also irgendwo beim Assistenten muss der Fehler passiert sein. Für ist jetzt jedoch wieder alles prima, somit schließe ich hier.

**Comment by thkl** [comment]
Nur für meine Info: Alle Instanzen wurden per Wizzard erzeugt, und  mit Geräten befüllt ? Und die Letzte hat dieses Publish Problemchen ?

**Comment by detLAN** [comment]
Ja, mit dem Wizzard.
Was mir dabei Einfällt am Anfang der Geräte Auswahl wurden einige Geräte der Instanz zur Auswahl bereits angeboten und am Ende dann noch einmal alle Geräte dieser Instanz. Hab ich dann natürlich noch einmal ausgewählt.
