### ISSUE TITLE
Eve App Feinschliff

### ISSUE THREAD

**Issue by mike4president** [thkl/hap-homematic#85]
So, ich hab mal eben alle meine mittlerweile in der Eve App hinterlegten Geräte durchgeschaut. Folgendes ist mir aufgefallen:

bei HmIP-BSM hinterlege ich immer den Kanal in Homekit der die Stromwerte ermitteln kann. Dieser lässt sich inzwischen ja auch schalten. :-) Allerdings wird das nicht so richtig mitgeloggt in der Eve App...

![IMG_0169](https://user-images.githubusercontent.com/65063329/82736348-55631c00-9d29-11ea-8306-46e4fa119420.jpeg)
![IMG_0170](https://user-images.githubusercontent.com/65063329/82736350-5b58fd00-9d29-11ea-8288-f8db923edb9d.jpeg)

Gleiches gilt auch für HMIP-PSM (dazu hatten wir uns ja schon ausgetauscht)

Beim HmIP-eTRV-2 ist es so, dass wenn man die Gruppe der CCU hinterlegt es ganz gut aussieht... 

![IMG_0172](https://user-images.githubusercontent.com/65063329/82736368-93f8d680-9d29-11ea-9b93-c53688b2c6ad.jpeg)

hinterlegt man das einzelne IP-Thermostat ohne Gruppe wir ein Wert für Luftfeuchtigkeit angezeigt, der aber nichts mitloggt

![IMG_0171](https://user-images.githubusercontent.com/65063329/82736390-b38fff00-9d29-11ea-87a2-0c0ca0f15a2a.jpeg)

**Comment by thkl** [comment]
Der Schalter bekommt zwar eine History, ich fülle die auch, aber Eve Energy ignoriert die.

Welches Device ist das wo die Feuchte fehlt ?

**Comment by mike4president** [comment]
gilt das auch für die Verbrauchswerte "Gesamtkosten" und "geschätzte Kosten"?

Es handelt sich um das Gerät HmIP-eTRV-2 wenn man es nicht als Gruppe hinterlegt.

**Comment by thkl** [comment]
Diese Kostengeschichte erzeugt eve selber. Ich übermittle nur 2 Sachen:

ElectricPower -> Aktuelle Leistung des Gerätes
TotalConsumption -> Energiezähler des Gerätes

Die ganzen Kostensachen denkt eve sich aus ...

**Comment by thkl** [comment]
beim HmIP-eTRV-2 welcher Service wird da benutzt ? Das steht auf der WebUI. Es müsste HomeMaticRadiatorThermostatAccessory sein ? Der kann Luftfeuchte ....

**Comment by mike4president** [comment]
<img width="665" alt="Bildschirmfoto 2020-05-23 um 20 04 40" src="https://user-images.githubusercontent.com/65063329/82737406-3e282c80-9d31-11ea-91f9-18704d6b8f39.png">

ist es, trotzdem wird die Luftfeuchtigkeit nicht mitgeschrieben bei dem IP Heizkörperthermostat. Ist für mich nicht weiter dramatisch, da ich es eh im Rahmen der CCU Gruppe hinterlege und da geht es. Nur wenn ich das Thermostat als einzelnes gerät in HomeKit anlege geht es nicht.

**Comment by mike4president** [comment]
> Diese Kostengeschichte erzeugt eve selber. Ich übermittle nur 2 Sachen:
> 
> ElectricPower -> Aktuelle Leistung des Gerätes
> TotalConsumption -> Energiezähler des Gerätes
> 
> Die ganzen Kostensachen denkt eve sich aus ...

Achso, da Kosten pro kWh kann man in der Eve App nur hinterlegen, wenn man ein Eve Energy hat. Daher ist die Anzeige dann scheinbar doch eher witzlos...

**Comment by thkl** [comment]
Ja ich habe die Kostensachen auch ausgeblendet.

Das Thermostat macht mir noch Sorgen .... laut EQ3 Doku gibts einen Datenpunkt HUMIDITY in Channel 1 den nutze ich auch der ist der gleiche wie bei der Gruppe. Nur warum er da geht und beim Thermostat nicht ist jetzt die Frage.

**Comment by mike4president** [comment]
Ist es eigentlich korrekt, dass wenn ich vom HmIP-BSM anstelle des Messkanals nur den Schalkanal aus der CCU in Homekit hinterlege er das in der Eve App nur so, also ohne irgend einen Verlauf darstellt? 

![IMG_0173](https://user-images.githubusercontent.com/65063329/82737842-0969a480-9d34-11ea-9489-3ebbc72095f7.png)


Ich packe mal zum Vergleich einen Screenshot vom Eve Switch dazu... 

<img width="549" alt="Bildschirmfoto 2020-05-23 um 20 25 51" src="https://user-images.githubusercontent.com/65063329/82737858-171f2a00-9d34-11ea-8a26-3b41d0b3b0d1.png">

**Comment by mike4president** [comment]
> Ja ich habe die Kostensachen auch ausgeblendet.
> 
> Das Thermostat macht mir noch Sorgen .... laut EQ3 Doku gibts einen Datenpunkt HUMIDITY in Channel 1 den nutze ich auch der ist der gleiche wie bei der Gruppe. Nur warum er da geht und beim Thermostat nicht ist jetzt die Frage.

hmmmmm :-/

**Comment by thkl** [comment]
Ja, wenn nur der Switch Kanal ausgewählt wird, und der SubTyp auf Switch gestellt wird, dann geht auch die Einschalthistory. Denn dann lege ich das Gerät als Switch in HomeKit an und dort unterstützt Eve diese History

**Comment by mike4president** [comment]
> Ja, wenn nur der Switch Kanal ausgewählt wird, und der SubTyp auf Switch gestellt wird, dann geht auch die Einschalthistory. Denn dann lege ich das Gerät als Switch in HomeKit an und dort unterstützt Eve diese History

Der Wald vor lauter Bäumen usw. Danke... jetzt geht das ...

**Comment by thkl** [comment]
Man kann jedem Gerät leider immer nur einen Logging Service hinzufügen. Daher kann ich beim PSM entweder den Verbrauch oder die Einschaltvorgänge loggen. Ich könnte da allerdings eine Option einbauen, das man wählen kann was man speichern möchte.

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/82738794-be06c480-9d3a-11ea-88aa-ec0d457b2f72.png)


funktioniert sogar ;) Wobei die Aussage, das Eve nur eins loggen kann falsch ist. FakeGato, das Modul was ich dafür verwende, kann nur einen Loggingservice pro Gerät erstellen.

**Comment by mike4president** [comment]
Ok...prima.  jetzt mal ne blöde Frage. Warum kann ich dann z.B. für HmIP-BSM mit seinen 7 Kanälen 7 verschiedene Homekit Geräte anlegen? Werde es dann nicht einfacher es würde nur der Messkanal in Homekit HAP angeboten wegen der Übersichtlichkeit und man würde sich dort für den Loggingservice entscheiden? 

FakeGato is as it is sozusagen? Oder kann man da noch auf einer Weiterentwicklung hoffen, dass auch mehrere Logginservices pro Gerät erstellen kann. Das wäre schon ziemlich klasse...

**Comment by thkl** [comment]
Ich bin da gerade bissel durch die Issues gesurft und auf einen sehr vielversprechenden Pull Request gestoßen. Ich hab da mal was vorbereitet:

![IMG_3593](https://user-images.githubusercontent.com/884355/82739528-931f6f00-9d40-11ea-904a-f098c7cccb2c.PNG)
![IMG_3594](https://user-images.githubusercontent.com/884355/82739532-97e42300-9d40-11ea-8fd1-ba11dde566a5.PNG)
![IMG_3595](https://user-images.githubusercontent.com/884355/82739534-987cb980-9d40-11ea-8ba3-71b49b0f0187.PNG)
![IMG_3596](https://user-images.githubusercontent.com/884355/82739535-99155000-9d40-11ea-9836-bba2d944b057.PNG)

**Comment by thkl** [comment]
Ach und:

![image](https://user-images.githubusercontent.com/884355/82739587-e8f41700-9d40-11ea-8ede-a7a97dcaaf2c.png)

**Comment by mike4president** [comment]
wie klasse ist das denn... :-) :-) ich bin der Meinung du solltest eine Spendenmöglichkeit direkt in Hap Homematic integrieren. So tolle Arbeit muss belohnt werden. Könntest du mir diese Frage noch beantworten? 

"jetzt mal ne blöde Frage. Warum kann ich dann z.B. für HmIP-BSM mit seinen 7 Kanälen 7 verschiedene Homekit Geräte anlegen? Werde es dann nicht einfacher es würde nur der Messkanal in Homekit HAP angeboten wegen der Übersichtlichkeit und man würde sich dort für den Loggingservice entscheiden?" ehrlich gesagt, hat mich das am Anfang ein wenig verwirrt.

**Comment by thkl** [comment]
Also die grundlegende Funktionsweise von hap-homematic ist das es für einzelne Kanäle entsprechende Geräte in HomeKit gibt. Ich muss das so machen, damit ich flexibel bei Geräten mit multiplen Kanälen bin, die das gleiche tun. Zb wired switchen .. dann gibts halt für jeden SwitchKanal ein HomeKit Geräte. Das macht bei Wired sogar Sinn, wenn das Ding im Schaltschrank ist und Lampen in 3 Räumen steuert.

Damit hat der BSM Services für KEY_TRANSEIVER (also Tasten) SWITCH_TRANSMITTER (Schaltkanal) SWITCH_VIRTUAL_RECEIVER (virtueller Schaltkanal) und ENERGIE_METER_TRANSMITTER (Messkanal)

Deswegen taucht der so oft auf.
Wenn man den SWITCH_TRANSMITTER oder SWITCH_VIRTUAL_RECEIVER auswählt bekommt man nur den SwitchService ... beim ENERGIE_METER_TRANSMITTER den HomeMaticIPPowerMeterSwitchAccessory Service wobei der wiederum weiß das er noch Kanal 4 hinzufügen muss ...  

Also einfach das ignorieren was du nicht brauchst ...

**Comment by mike4president** [comment]
Besten Dank. Also ich fasse für nochmal zusammen: 

Offen war jetzt in Eve noch der Luchtfeuchtigkeitswert für HmIP-eTRV-2, wenn man nur das Thermostat in HomeKit hinzufügt

ggfs mehrere LoggingServices für ein Gerät in Eve (falls FakeGato das kann)

und deine tollen Screenshots bspw zu den Heizplänen :-)

**Comment by thkl** [comment]
HmIP-eTRV-2 wird schwierig, ich hab das Ding nicht .. und laut Doku müsste es passen.

Es geht derzeit nur ein Logging Service deswegen hab ich in der nächsten Version einen Auswahlschalter für das Ding ... 

Die Programmierbare Heizung wird noch etwas dauern. 
a) kennt eve nur 2 Temperaturen zwischen denen man wechseln kann. Das Thermostat der HomeMatic kann zu jedem Schaltzeitpunkt eine unterschiedliche Temperatur nutzen.  Damit wird zwar das Setzen des Wochenplans möglich, aber einen vorhandenen anzuzeigen scheitert ggf.

b) werden die Wochenpläne auch unterschiedlich zwischen HmIP und HM Geräten abgelegt. Bei IP geht das so lala zu machen .. HM ist ne Katastrophe hier muss ich direkt auf die BidCos-RF Schnittstelle schreiben weil die Daten im Master und nicht im Value Parameterset liegen.

**Comment by mike4president** [comment]
na dann hoffen wir mal, dass sich FakeGato noch weiterentwickelt. 

a)b)Bedeutet das, dass der Wochenplan bei den IP Geräten dann direkt im Thermostat abgelegt wird? Oder wirkt das dann eher wie eine HomeKit Automation.

**Comment by thkl** [comment]
hier bin ich noch unschlüssig. Entweder ich manage das mit den Temperaturen selber. Dann muss hap-homematic das Thermostat zu den jeweiligen Zeitpunkten entsprechend einstellen.
Oder der aus Eve erstelle Wochenplan wird in einen des Thermostats geschrieben. (das kann ja mindestens 3) ....  ich präferiere momentan noch die 2. Möglichkeit, denn ich wollte eigentlich so wenig wie möglich Sachen aus der CCU in mein Addon verlegen.

**Comment by detLAN** [comment]
Der HmIP-eTRV-2 hat meines Wissens für sich allein genommen gar kein Luftfeuchtigkeitssensor. Erst in Kombination mit einem HmIP-WTH-2, HmIP-STHD u.s.w. kommt die Luftfeuchte hinzu.

**Comment by mike4president** [comment]
Stimmt, insofern kann die Anzeige in Eve auch raus, wenn man nur das Heizkörperthermostat anstelle der Heizgruppe hinterlegt.

**Comment by detLAN** [comment]
Oder man nimmt gleich HmIP-WTH-2, HmIP-STHD u.s.w. Die Heizungsgruppen (VirtualDevices), können ja auch nicht klimarelevante Geräte enthalten.
<img width="1369" alt="Bild 1" src="https://user-images.githubusercontent.com/64675966/82751115-65c0d880-9db5-11ea-9992-8def128855f9.png">

**Comment by mike4president** [comment]
genau, siehe oben: https://github.com/thkl/hap-homematic/issues/85#issue-623702786

**Comment by mike4president** [comment]
HmIP-eTRV-2 einzeln zeigt in Eve noch immer Luftfeuchtigkeit an, obwohl Datenpunkt nicht vorhanden im Thermostat... zur Info

nur zur Übersicht:

Eve-Heizpläne für späteres Release noch offen

**Comment by thkl** [comment]
Stimmt das mit der Luftfeuchtigkeit ist noch offen. Da muss ich die CCU vorher fragen ob der DP existiert.


Heizungspläne ist ein größerer Part

**Comment by mike4president** [comment]
wieso geschlossen???? War hier nicht noch u.a. das mit den Heizplänen offen?

**Comment by thkl** [comment]
das ist ein eigenes Thema ;)

**Comment by mike4president** [comment]
na gut ;-)
