### ISSUE TITLE
Gerät HMW-Sen-SC-12-DR hinzufügen?!

### ISSUE THREAD

**Issue by staudy83** [thkl/hap-homematic#86]
Hallo zusammen,

ich habe heute die Zusatzsoftware installiert und habe ein Gerät welches noch nicht mit unterstützt wird. Es ist der oben genannte Schließerkontakt.

Nach der Anleitung habe ich die Seriennummer in das Feld eingegeben und den Code wie folgt abgespeichert. Ich hoffe das reicht. ;-)

An dem Gerät sind alle Fenster und Türen angeschlossen und melden zurück ob diese geschlossen oder geöffnet sind.

{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HMW-Sen-SC-12-DR",
      "address": "7348266248ABCD",
      "type": "HMW-Sen-SC-12-DR",
      "channels": [
        {
          "id": 1001,
          "name": "7348266248ABCD:1",
          "intf": 0,
          "address": "7348266248ABCD:1",
          "type": "SENSOR",
          "access": 255
        },
        {
          "id": 1002,
          "name": "7348266248ABCD:2",
          "intf": 0,
          "address": "7348266248ABCD:2",
          "type": "SENSOR",
          "access": 255
        },
        {
          "id": 1003,
          "name": "7348266248ABCD:3",
          "intf": 0,
          "address": "7348266248ABCD:3",
          "type": "SENSOR",
          "access": 255
        },
        {
          "id": 1004,
          "name": "7348266248ABCD:4",
          "intf": 0,
          "address": "7348266248ABCD:4",
          "type": "SENSOR",
          "access": 255
        },
        {
          "id": 1005,
          "name": "7348266248ABCD:5",
          "intf": 0,
          "address": "7348266248ABCD:5",
          "type": "SENSOR",
          "access": 255
        },
        {
          "id": 1006,
          "name": "7348266248ABCD:6",
          "intf": 0,
          "address": "7348266248ABCD:6",
          "type": "SENSOR",
          "access": 255
        },
        {
          "id": 1007,
          "name": "7348266248ABCD:7",
          "intf": 0,
          "address": "7348266248ABCD:7",
          "type": "SENSOR",
          "access": 255
        },
        {
          "id": 1008,
          "name": "7348266248ABCD:8",
          "intf": 0,
          "address": "7348266248ABCD:8",
          "type": "SENSOR",
          "access": 255
        },
        {
          "id": 1009,
          "name": "7348266248ABCD:9",
          "intf": 0,
          "address": "7348266248ABCD:9",
          "type": "SENSOR",
          "access": 255
        },
        {
          "id": 1010,
          "name": "7348266248ABCD:10",
          "intf": 0,
          "address": "7348266248ABCD:10",
          "type": "SENSOR",
          "access": 255
        },
        {
          "id": 1011,
          "name": "7348266248ABCD:11",
          "intf": 0,
          "address": "7348266248ABCD:11",
          "type": "SENSOR",
          "access": 255
        },
        {
          "id": 1012,
          "name": "7348266248ABCD:12",
          "intf": 0,
          "address": "7348266248ABCD:12",
          "type": "SENSOR",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by thkl** [comment]
Das Gerät ist im nächsten Update mit drin

**Comment by staudy83** [comment]
Guten Morgen und vielen Dank für die schnelle Umsetzung.

Ich hätte jetzt noch eine optische Umsetzungsbitte, da praktisch alles bestens funktioniert. Die Magnetschaltkontakte werden jetzt als Kontakte dargestellt. In deiner anderen Version über die Homebridge kann ich entsprechende Symbole auswählen. Siehe angehängte Fotos.

Mache ich einen Fehler?

![IMG_77951105C600-1](https://user-images.githubusercontent.com/65859025/83346069-bab2a080-a319-11ea-8b81-9e95717d91da.jpeg)
![IMG_69F05CE1567A-1](https://user-images.githubusercontent.com/65859025/83346088-d322bb00-a319-11ea-94e5-13e1f8a83195.jpeg)
![IMG_C34647CEF54D-1](https://user-images.githubusercontent.com/65859025/83346089-d453e800-a319-11ea-940b-d9b0f8fdc502.jpeg)

**Comment by thkl** [comment]
Nein, ich habe die aktuell nur in dir Kontaktklasse eingefügt und nicht in Window oder Door. Aber meine Wissens kann man das schon in Home ändern. In den Einstellungen des Gerätes in der Home App gibt es „anzeigen als“ . Das müsste das Problem lösen. Denn eigentlich sind es keine Türen/Fenster von der Funktion her.

**Comment by staudy83** [comment]
> Nein, ich habe die aktuell nur in dir Kontaktklasse eingefügt und nicht in Window oder Door. Aber meine Wissens kann man das schon in Home ändern. In den Einstellungen des Gerätes in der Home App gibt es „anzeigen als“ . Das müsste das Problem lösen. Denn eigentlich sind es keine Türen/Fenster von der Funktion her.

Stimmt da war mein Fehler.

Vielen dank für den Support und schöne Pfingsten.
