### ISSUE TITLE
Bewegungsmelder ohne LUX Sensor

### ISSUE THREAD

**Issue by theo-69** [thkl/hap-homematic#88]
Hallo, ich nutze den Bewegungsmelder ohne Lux Sensor. Leider wird in HomeKit immer ein Lux Wert angezeigt. Kann man den wie bei NodeRed HomeKit irgendwie abschalten.

**Comment by mike4president** [comment]
Also ich finde eigentlich ganz gut, dass der Wert mitgeliefert wird. Du kannst die beiden Sensoren in Homekit auch als separate Felder darstellen. Aber so ne Option bei der Einrichtung des Gerätes ist sicher nett...

**Comment by theo-69** [comment]
das stimmt schon aber meiner hat kein LUX Sensor und zeigt somit immer 0.0000001 Lux an ;-)

**Comment by thkl** [comment]
Ja, ich kann das ähnlich wie beim Thermometer bauen das in der Config der Helligkeitssensor abgeschaltet werden kann.

**Comment by theo-69** [comment]
Super, schon beim nächsten Update? :-)

**Comment by thkl** [comment]
![image](https://user-images.githubusercontent.com/884355/82809308-1c8f8800-9e8c-11ea-89d3-eefbdfc3afa1.gif)

**Comment by mike4president** [comment]
Ich wünschte eQ-3 würden so schnell auf Nutzerwünsche reagieren wie Thomas auf github.

**Comment by theo-69** [comment]
ich hatte ja auch extra nen Smiley dahinter gepackt.... 😂
