### ISSUE TITLE
Netatmo Co2 Wert

### ISSUE THREAD

**Issue by rost2802** [thkl/hap-homematic#89]
Hallo, ist es möglich den Co2 Wert aus einer Systemvariable in einem ThermometerAccessory mit anzeigen zu lassen? Der Wert (ppm) kommt von einer Netatmo Wetterstation.

**Comment by thkl** [comment]
Ja

**Comment by rost2802** [comment]
Super vielen Dank. Die Variable ist einem Thermostat-Kanal zugeordnet, evtl. könnte man sie direkt von da einbauen.

**Comment by thkl** [comment]
Guter Punkt ... die Frage ist, wie bekomme ich das generisch gelöst.  Ich kann nicht davon ausgehen das jede dem Thermostat zugewiesene Variable CO2 ist. Der nächste User hat da einen anderen Wert and Thermostat gehangen ....

**Comment by rost2802** [comment]
Kann man generell einem erstellten Gerät ein Service hinzufügen? Z.B. falls der Co2 Status aus einer Variable kommt (oder evtl. Baterielevel). Beim Thermostat dann den CarbonDioxideLevel, CarbonDioxideDetected und CarbonDioxidePeakLevel.

**Comment by thkl** [comment]
Nun ja prinzipiell kann ich einem Accessory (Das ist das HomeKit Gerät) diverse Services (das sind die Sensoren / Batterielevel etc) hinzufügen. Diese können dann diverse Characteristics (das ist zb Current Temperature und Target Temperature für ein Thermostat) haben. Das geht schon alles.
Ich will nur keinen Baukasten auf machen. Das wird dann echt kompliziert. 

Das Ziel dieses AddOns ist: der User durchläuft einmal den Wizzard und fertig. Alles was funktioniert liegt dann in HomeKit.


Ich muss da mal genauer drüber nachdenken ;)

**Comment by rost2802** [comment]
Das ist verständlich... gibt ja auch noch RedMatic womit man allerlei basteln kann. Grund für den Wechsel zu deiner Lösung war eben die FakeGato History Geschichte, die mir sehr gut gefällt... von der einfachen Einrichtung mal abgesehen ;)

**Comment by thkl** [comment]
Config:

![image](https://user-images.githubusercontent.com/884355/82839873-17a0f780-9ed1-11ea-8675-5deb239fdf0b.png)

wird zu:

![IMG_3608](https://user-images.githubusercontent.com/884355/82839917-37382000-9ed1-11ea-979f-77765bf7f538.jpg)


100% glücklich bin ich mit der Lösung noch nicht ... aber nun ja

**Comment by rost2802** [comment]
Nicht glücklich weil zu Speziell? Sieht doch schonmal sehr gut aus... für die mit einem Netatmo System eine tolle Sache.

**Comment by mike4president** [comment]
@rost2802 Kurze Verständnisfrage: ist die Wetterstation nicht inzwischen selbst HomeKit kompatibel?

**Comment by thkl** [comment]
nein, erst ab Hardware Revision V3 .. die älteren Modelle nicht

**Comment by mike4president** [comment]
Klick!

**Comment by thkl** [comment]
Theoretisch könnten eine Menge Hersteller das ganze wohl in Software abbilden. Ich meine, selbst ein ESP8266 kann mittlerweile ein HomeKit Device sein. Allerdings legt wohl  da immer noch die Hand drüber wenn man seine Hardware  mit HomeKit verkaufen möchte

**Comment by thkl** [comment]
> Nicht glücklich weil zu Speziell? Sieht doch schonmal sehr gut aus... für die mit einem Netatmo System eine tolle Sache.

Nein, weil ich mich schon sowas für alles mögliche implementieren sehe ;) Aber ich kipp das schon mal ins nächste Release.

**Comment by rost2802** [comment]
Ein Träumchen 👍

**Comment by rost2802** [comment]
Muss die Co2 Variable dann auch regelmäßig getriggert werden?

<img width="985" alt="Bildschirmfoto 2020-05-25 um 22 50 27" src="https://user-images.githubusercontent.com/59236127/82842522-28a23680-9eda-11ea-9791-029c89497aa6.png">

**Comment by thkl** [comment]
> Muss die Co2 Variable dann auch regelmäßig getriggert werden?

nein, da ich wegen FakeGato ohnehin das Thermostat aller 10 Minuten befragen muss, wird an der Stelle auch die Variable abgeholt.

> Und werden für Co2 auch FakeGato Daten geschrieben? 🙈
ja ;) dazu muss ich von Eve Weather auf Eve room, das heisst das Gerät muss vorher einmal aus HAP gelöscht und dann wieder aufgenommen werden. Sonst passen die Werte nicht.

**Comment by thkl** [comment]
Mit einer CO2 Variable wird das Thermometer dann so aussehen. 

![image](https://user-images.githubusercontent.com/884355/82944151-00c6d780-9f9b-11ea-8ee1-926e582ae2cf.png)

**Comment by rost2802** [comment]
Läuft perfekt 👍 
Wäre es ein großer Aufwand auch den Batteriestatus aus einer Variable optional zu lesen? Hoffe das ist nicht zu Speziell oder überhaupt sinnvoll.

**Comment by thkl** [comment]
Nope, denn der Batteriestatus kommt schon vom Thermostat, an welchem der CO2 Wert hängt

**Comment by rost2802** [comment]
Das Thermostat ist ein CUxD Gerät ohne Batterielevel, daher die frage. Oder kann man das Level auch in das CUxD Gerät direkt schreiben? Schreibe die Daten in das Thermostat per Skrip welches alles von Netatmo abruft. Die Batterie bekomm ich aber nur in eine Variable.

**Comment by thkl** [comment]
Wenn das Gerät auf Channel 0 einen Datenpunkt LOWBAT hat wird der Akkustand angezeigt. Datenpunkt false = Akku voll, Datenpunkt true = Akku leer (HM Geräte)

Wenn das Gerät auf Channel 0 einen Datenpunkt OPERATING_VOLTAGE und einen LOW_BAT hat , werden zusätzlich noch die % Werte angezeigt. Dafür benötigt es aber eine feste Einstellung was 100% sind. (im Code;nicht User editierbar)

**Comment by rost2802** [comment]
Kann es sein das Co2 Werte unter 400 in der Luftqualität einen Fehler ausgeben?

![IMG_3175](https://user-images.githubusercontent.com/59236127/83338811-1e13e280-a2c8-11ea-97b8-d799c59ea562.png)

**Comment by thkl** [comment]
Ja ... ich werde mal die 0 rausnehmen.
Und sonst alles > 300 auf Excellent setzen

**Comment by rost2802** [comment]
> Wenn das Gerät auf Channel 0 einen Datenpunkt LOWBAT hat wird der Akkustand angezeigt. Datenpunkt false = Akku voll, Datenpunkt true = Akku leer (HM Geräte)
> 
> Wenn das Gerät auf Channel 0 einen Datenpunkt OPERATING_VOLTAGE und einen LOW_BAT hat , werden zusätzlich noch die % Werte angezeigt. Dafür benötigt es aber eine feste Einstellung was 100% sind. (im Code;nicht User editierbar) (HmIP Geräte)

Das virtuelle Gerät hat leider keine Batterie Datenpunkte... konnte auch nix finden um einen in CUxD erstellten Gerät irgendwelche Batterie Datenpunkte hinzuzufügen. Deswegen schreibt das Netatmo Skript die Daten in eine SysVar.

<img width="984" alt="Bildschirmfoto 2020-06-06 um 00 04 08" src="https://user-images.githubusercontent.com/59236127/83926164-60866500-a789-11ea-8ca3-48b0c36d9d03.png">

**Comment by thkl** [comment]
Sorry aber jetzt sprengt es den Aufwand etwas oder ?

**Comment by rost2802** [comment]
Ja das hab ich befürchtet 🙈
