### ISSUE TITLE
HmIP-KRCA

### ISSUE THREAD

**Issue by mike4president** [thkl/hap-homematic#90]
Hi,

könnte man die Schlüsselbundfernbedienung HmIP-KRCA ähnlich in HomeKit integrieren wie z.B. den Hue Tab? 

Ich hätte die einzelnen Buttons der Fernbedienung gerne als ein Gerät dargestellt, so wie der Hue Tab das macht. 

Zusätzlich wäre der Batteriestatus hier auch spannend, da ich bei dem Gerät mit Abstand am Häufigsten die Batterie wechseln muss. 

<img width="246" alt="Bildschirmfoto 2020-05-25 um 12 26 26" src="https://user-images.githubusercontent.com/65063329/82804730-1b0d9200-9e83-11ea-9a14-4dedad24d7be.png">
<img width="330" alt="Bildschirmfoto 2020-05-25 um 12 29 17" src="https://user-images.githubusercontent.com/65063329/82804897-5f009700-9e83-11ea-8932-90f971193f46.png">

**Comment by thkl** [comment]
Derzeit müsste es gehen, die Tasten einzeln aufzunehmen da ich ja einzelne Kanäle betrachte und nicht das ganze Device..... die Batterie würde dann bei jedem Gerät mit erscheinen

**Comment by mike4president** [comment]
Ja, die einzelnen Tasten gehen bereits... Ich dachte nur, dass das beispielsweise auch für den Gerätetyp HmIP-RC8 interessant wäre. Sonst hat man so viele Einzelbuttons in Homekit ;-) Wenn es aber aufgrund der Kanalbetrachtung nicht geht, ist es auch kein Beinbruch

**Comment by thkl** [comment]
Ich habe die Herangehensweise über die Kanäle schon mal in einem anderen Issue beschrieben.  A) schaffe ich so recht leicht Kompatibilität zwischen Geräten die im Grunde das gleiche tun nur andere Ausführungen sind. (Innen IRD aussen Ird etc)

B) ist es einfacher für Geräte mit mehreren Aktoren diese zu trennen.  Zb wired switche die 4 Relais haben in einem Schaltschrank wohnen und in unterschiedlichen Räumen das Licht an schalten. 


Ich schau mit das mit der Batterie mal an was ist da für eine Drinn wegen der Spannung

**Comment by mike4president** [comment]
sorry, nicht gesehen... Es ist eine AAA Batterie drinnen

**Comment by thkl** [comment]
Damit ich für den Batterieservice von dem Ding einen Test schreiben kann, der die Funktion automatisch prüft, bräuchte ich mal das Device File. 

Das kann man auf dem WebUI vom HAP unter Hilfe / Support erzeugen.
Bitte mal hier anhängen.

**Comment by mike4president** [comment]
{
  "devices": [
    {
      "id": 1000,
      "intf": 0,
      "intfName": "",
      "name": "HmIP-KRCA",
      "address": "4436784678ABCD",
      "type": "HmIP-KRCA",
      "channels": [
        {
          "id": 1001,
          "name": "4436784678ABCD:0",
          "intf": 0,
          "address": "4436784678ABCD:0",
          "type": "MAINTENANCE",
          "access": 255
        },
        {
          "id": 1002,
          "name": "4436784678ABCD:1",
          "intf": 0,
          "address": "4436784678ABCD:1",
          "type": "KEY_TRANSCEIVER",
          "access": 255
        },
        {
          "id": 1003,
          "name": "4436784678ABCD:2",
          "intf": 0,
          "address": "4436784678ABCD:2",
          "type": "KEY_TRANSCEIVER",
          "access": 255
        },
        {
          "id": 1004,
          "name": "4436784678ABCD:3",
          "intf": 0,
          "address": "4436784678ABCD:3",
          "type": "KEY_TRANSCEIVER",
          "access": 255
        },
        {
          "id": 1005,
          "name": "4436784678ABCD:4",
          "intf": 0,
          "address": "4436784678ABCD:4",
          "type": "KEY_TRANSCEIVER",
          "access": 255
        },
        {
          "id": 1006,
          "name": "4436784678ABCD:5",
          "intf": 0,
          "address": "4436784678ABCD:5",
          "type": "ALARM_COND_SWITCH_TRANSMITTER",
          "access": 255
        }
      ]
    }
  ]
}

**Comment by mike4president** [comment]
besten Dank

**Comment by mike4president** [comment]
Batteriestatus wird jetzt angezeigt...
