### ISSUE TITLE
HmIP-WTH-2 in Verbindung mit Schaltaktor

### ISSUE THREAD

**Issue by rost2802** [thkl/hap-homematic#91]
Hallo, ist es möglich den Automatisch Modus im Thermostat mit einzubauen? Sonst schaltet der in Direktverbung stehende Aktor meiner IR-Heizung nicht.

**Comment by thkl** [comment]
Könnte man ähnlich wie den Boost Button machen.

**Comment by theo-69** [comment]
fände ich toll könnte ich auch gebrauchen :-)

**Comment by mike4president** [comment]
Ähm, kann mir kurz jemand erklären was genau hier gemeint ist? Welche Direktverbindung wurde hier denn aufgebaut?

**Comment by rost2802** [comment]
> Ähm, kann mir kurz jemand erklären was genau hier gemeint ist? Welche Direktverbindung wurde hier denn aufgebaut?

<img width="1784" alt="Bildschirmfoto 2020-05-25 um 13 18 02" src="https://user-images.githubusercontent.com/59236127/82808395-362fd000-9e8a-11ea-9cf1-4c8d862d72d5.png">

**Comment by mike4president** [comment]
Danke. Hatte HmIP-WTH-2 mit dem IP-Heizkörperthermostat verwechselt...

**Comment by theo-69** [comment]
Hallo, eigentlich war mein Beitrag Heizung (aus-heizung-automatik) #95 kein Duplikat, denn bei meinem Beitrag geht es ja um die Heizung Automatik Modus - Manuell Modus - Aus Modus!

**Comment by thkl** [comment]
Ja, aber die Funktion ist die gleiche.  Schalten auf Manuell wenn man die Grad ändert oder auf Auto wenn man in dem Selector Automatisch wählt. 

Ich wollte zuerst einen Button nehmen aber der Selector kann ja Aus Heizen (wäre dann Manuell) oder Auto

**Comment by theo-69** [comment]
stimmt nur bei Node-red Homekit geht Automatik - Manuell ist dann manuelle Temperatur und Aus für OFF (also 4,5 Grad)

**Comment by thkl** [comment]
Das ist exact das was ich oben beschrieben habe. Und so würde ich es auch umsetzen.

**Comment by thkl** [comment]
Im Zusammenhang mit #95 würden Thermostate das also in Zukunft so aussehen.

![image](https://user-images.githubusercontent.com/884355/83035034-3f12d400-a039-11ea-8829-f8d607c5d143.png)

Damit ändert sich ein klein wenig die Verhaltensweise, welche aber an das "normale" Verhalten der Thermostate an der CCU angepasst ist:

Off/Aus -> Thermostat geht in den Manuellen Mode und 4,5 Grad 
Auto -> Thermostat geht in den Auto Modus
Heating/Heizen -> Thermostat geht in den Manuellen Mode und setzt die zuletzt bekannte Temperatur ( die kommt entweder von der letzten Einstellung, oder aus der letzten CCU SetTemp Message)

Manuelles drehen an der Temperatur -> im AutoModus -> Auto bleibt Temp wird verstellt. Damit fällt das Thermostat zum nächsten Schalten des Programms wieder auf das Programm zurück. Im Manu Mode bleibt dieser und die Temperatur wird angepasst.

**Comment by theo-69** [comment]
> Das ist exact das was ich oben beschrieben habe. Und so würde ich es auch umsetzen.

sorry wohl etwas überlesen

**Comment by thkl** [comment]
HMIP Thermostate dauern noch, da fehlen mir mangels Gerät einige Infos

**Comment by mike4president** [comment]
Können wir da Infos beisteuern? Ich hab nur nur IP Thermostate...

**Comment by thkl** [comment]
Einmal DebugMode einschalten. Dann im WebUI der CCU ManuMode einschalten Temp ändern .. AutoMode einschalten .. Temp ändern .. Boost Einschalten .... und dann einmal Manu Mode und Off Temp einstellen. Dann Debug ausschalten und mir das Logfile hier als Datei anhängen.

Ich müsste wissen, welche Events da auf der Schnittstelle passieren

**Comment by mike4president** [comment]
Ich versuche das mal... schaffe es aber erst morgen...

**Comment by rost2802** [comment]
Debug Mode in CCU oder HAP-Homematic 🤔

**Comment by thkl** [comment]
Debug Mode auf der WebUI der Hap Oberfläche .. damit werden die Events aufgezeichnet, die die CCU sendet

**Comment by rost2802** [comment]
So... ich hoffe das passt so... ist mit einem HmIP-WTH-2.

[hap-homematic-log-3.txt](https://github.com/thkl/hap-homematic/files/4690722/hap-homematic-log-3.txt)

**Comment by roe1974** [comment]
für den HM Thermostat hast du alles was du brauchst ?
lg richard

**Comment by thkl** [comment]
@rost2802 danke erstmal .. ich muss ne bessere Idee finden es kommen einige Events mehrfach daher weiss ich nicht welches normale Statusupdates sind und was auf Änderungen im UI der CCU passiert ist.

@roe1974 : ja HM ist fertig das Zeugs habe ich selber

**Comment by rost2802** [comment]
> @rost2802 danke erstmal .. ich muss ne bessere Idee finden es kommen einige Events mehrfach daher weiss ich nicht welches normale Statusupdates sind und was auf Änderungen im UI der CCU passiert ist.

Kann sein das ich ab und an 2x gedrückt hab weil die Änderungen nicht direkt übernommen wurden. Noch ein versuch?

**Comment by thkl** [comment]
ja, gut wären definierte Zeitpunkte also zb:
Beginn AutoMode ist eingeschalten

20:30  ManuMode Button 
20:31  temp auf 20 Grad
20:32  AutoMode Button
20:33  temp auf 22 Grad
20:34  Boost Mode
20:35  Manu Mode Button

Also eine definierte Zeitabfolge die ich auch am Log dann sehe. 
Ich muss wissen welche Datenpunkte wie gesetzt werden, wenn definierte Funktionen aufgerufen werden.

**Comment by rost2802** [comment]
21:43 ManuMode Button
21:44 temp auf 20 Grad
21:45 AutoMode Button
21:46 temp auf 22 Grad
21:47 Boost Mode
21:48 Manu Mode Button

[hap-homematic-log.txt](https://github.com/thkl/hap-homematic/files/4691406/hap-homematic-log.txt)

**Comment by thkl** [comment]
Danke, damit komme ich weiter

**Comment by thkl** [comment]
in .43 sollte es für HM funktionieren und könnte auch für HmIP gehen das kann ich leider nicht testen aber anhand der Logs müsste es passen.

**Comment by rost2802** [comment]
Läuft leider noch nicht komplett bei mir mit .43 und einem HmIP-WTH-2.

Modus wird richtig gelesen bei Änderung in CCU aber nicht geändert bei Änderung in Home App.

Temperaturänderungen funktionieren nicht in beiden Richtungen.

Boost wird richtig gelesen bei Änderung in CCU, einschalten per Home funktioniert auch aber ausschalten wird wiederum nicht weiter gegeben.

**Comment by thkl** [comment]
Könnte mal bitte jemand folgende HM Scripts ausprobieren und mir sagen ob sich am Modus was ändert:

SERIENNUMMER ist die des Gerätes aus der Geräteliste der CCU

Das hier sollte den AutoMode einschalten:
```
dom.GetObject('HmIP.SERIENNUMMER.1:CONTROL_MODE').State(0);
```

Das hier sollte den Manuellen Mode einschalten:
```
dom.GetObject('HmIP.SERIENNUMMER.1:CONTROL_MODE').State(1);
```

Und wenn Boost aktiv ist, wird der dann ausgeschalten ?
Also bei AutoMode(.State(0);)  zurück auf Auto oder bei Manu (.State(1);) zurück auf Manuell ?

**Comment by rost2802** [comment]
Die beiden befehle funktionieren nicht... hab bissl hin und her probiert und damit geht es:

dom.GetObject("HmIP-RF.SERIENNUMMER:1.CONTROL_MODE").State(0);
dom.GetObject("HmIP-RF.SERIENNUMMER:1.CONTROL_MODE").State(1);

**Comment by rost2802** [comment]
Ach und Boost funktioniert nur im AutoMode und wird ausgestellt wenn man mit State(1) ManuMode aktiviert.

**Comment by thkl** [comment]
Oh ja, sorry ich hatte die Schnittstellenbezeichnung falsch.  

Aber das hilft mir für den Issue weiter.  


Ich bräuchte mal für ein paar Wochen den großen EQ3 Demokoffer mit allen Geräten 😁

**Comment by rost2802** [comment]
Läuft in .44
Vielen Dank 👌
