### ISSUE TITLE
Etwas Respekt für Inhibit ;)

### ISSUE THREAD

**Issue by JensBonse** [thkl/hap-homematic#93]
Hallo Thomas,

könntest du bei den Rollläden das Inhibit bitte noch mit abfragen?
Damit man per HomeKit nicht steuern kann, wenn Inhibit aktiv ist?

Danke!

**Comment by thkl** [comment]
ich dächte ich respektiere das schon bei allen Geräten ... aber ok ich schaue mir das an.

**Comment by thkl** [comment]
ah nein ok ich beachte "bedienbar" als Channelflag .. ok Inhibit ja ...

**Comment by thkl** [comment]
kann das weg ?

**Comment by JensBonse** [comment]
Hab es noch nicht getestet aber ich vertraue dir da.
