### ISSUE TITLE
Performance Hap

### ISSUE THREAD

**Issue by mike4president** [thkl/hap-homematic#94]
Hi, ich weiß nicht, ob ich das geträumt habe, aber war HAP im letzten Release noch performanter? 

ich hab es jetzt oft, dass wenn ich mich anmelde erstmal das hier eingeblendet wird. 

<img width="1771" alt="Bildschirmfoto 2020-05-26 um 19 01 45" src="https://user-images.githubusercontent.com/65063329/82931277-f864a180-9f86-11ea-9203-04e4145ede27.png">

Nach ein paar Sekunden fängt er sich dann. Dadurch steht auch in Homekit manchmal recht lange "Aktualisieren"...

Ich hab inzwischen 40 Homekit Geräte angelegt. Cache habe ich zurückgesetzt.

**Comment by thkl** [comment]
Naja das Hochfahren von 40 Geräten dauert ein wenig. Da ich beim Launch (und das ist auch beim Speichern von neuen Geräteeigenschaften) alle Instanzen neu hochfahre kann das schon mal ein paar Sekunden dauern. Ich muss auch an der Stelle die CCU zb nach dem Vorhandensein von Datenpunkten (zb Batterie info ja/nein)  fragen etc. Ggf kann ich das noch cachen ...

**Comment by mike4president** [comment]
ist nicht weiter dramatisch... passiert auch nicht jedes Mal. Jetzt gerade habe ich diese Ansicht seit 2,5 Minuten... and counting... kann man da im Log was sehen?

**Comment by roe1974** [comment]
Also bei mir dauert das <2sec ... und das "Aktualisieren" in Homekit ist quasi nicht sichtbar !!

**Comment by mike4president** [comment]
kann das daran liegen, dass ich ein TinkerboardS habe?

**Comment by mike4president** [comment]
also ich habe jetzt mal die CCU neu gestartet... (Ach der Neustart... die typische IT Empfehlung) und den Browsercache zurückgesetzt. Zusätzlich den Cache der CCU aktualisiert. Nach dem Neustart HAP aufgerufen... es dauert ca 10 Sekunden und dann werden die Geräte eingeblendet...

**Comment by thkl** [comment]
> ist nicht weiter dramatisch... passiert auch nicht jedes Mal. Jetzt gerade habe ich diese Ansicht seit 2,5 Minuten... and counting... kann man da im Log was sehen?

Nur im browser ggf. wenn zwar die Seite lädt aber keine Daten hat, könnte ein reload helfen. Wie gesagt die Seite kommt als leere html Hülle und wird über eine WebSocket Verbindung gefüllt.

>kann das daran liegen, dass ich ein TinkerboardS habe?
nein, bei mir läuft das auf einem popeligen RPi2

>also ich habe jetzt mal die CCU neu gestartet... (Ach der Neustart... die typische IT Empfehlung) 

alles nicht nötig wir sind ja hier nicht unter Windows. Ich schau mal das ich das etwas besser performen lassen und nicht erst auf den WebSocket warte, sondern den initialen Daten gleich lade....

**Comment by mike4president** [comment]
auf Arbeit natürlich letzteres... ;-)

**Comment by roe1974** [comment]
no no no :-P :-P :-P

**Comment by mike4president** [comment]
:-P ich hab Windows immer so empfunden :-)

![giphy](https://user-images.githubusercontent.com/65063329/82934917-9444dc00-9f8c-11ea-909e-281a1926b657.gif)

**Comment by thkl** [comment]
ok wir behalten das im Auge ;o)
