### ISSUE TITLE
Heizung (aus-heizung-automatik)

### ISSUE THREAD

**Issue by theo-69** [thkl/hap-homematic#95]
Hallo ich steige gerade von RedMatic zu deinem PlugIn um, leider stelle ich gerade fest das bei den Heizungsgruppen zwar der Boot geht aber die Auswahl (AUS - HEIZUNG - AUTOMATIK) fehlt.

![IMG_661FC736A3A2-1](https://user-images.githubusercontent.com/28484958/82997959-5f299f80-a007-11ea-86eb-6f81610821b9.jpeg)

**Comment by thkl** [comment]
Da gibt’s schon einen Issue für der ist noch offen

**Comment by theo-69** [comment]
oh sorry nicht gefunden :-(

**Comment by thkl** [comment]
Duplicate https://github.com/thkl/hap-homematic/issues/91

**Comment by theo-69** [comment]
Hallo, eigentlich war mein Beitrag Heizung (aus-heizung-automatik) #95 kein Duplikat, denn bei meinem Beitrag geht es ja um die Heizung Automatik Modus - Manuell Modus - Aus Modus!
