### ISSUE TITLE
HmIP-BBL Devices können nicht angesteuert werden

### ISSUE THREAD

**Issue by ebjogot** [thkl/hap-homematic#96]
![Snap2](https://user-images.githubusercontent.com/66059037/83115782-2f43d000-a0cb-11ea-9d7f-41b3a60911a1.jpg)
![ios_home](https://user-images.githubusercontent.com/66059037/83115787-2fdc6680-a0cb-11ea-88af-439f6755472c.jpg)
![Snap1](https://user-images.githubusercontent.com/66059037/83115789-3074fd00-a0cb-11ea-806a-b49efb8148d7.jpg)

HmIP-BBL Geräte können als "HomeMaticPushTheButtonAccessory" oder "HomeMaticKeyAccessory"eingebunden werden. 
Eine Einbindung als "HomeMaticKeyAccessory" lässt keine Ansteuerung über Homekit zu.
Eine Einbindung als "HomeMaticPushTheButtonAccessory" lässt eine Ansteuerung über Homekit zu es wird aber kein Aktion am Aktor ausgelöst.

**Comment by thkl** [comment]
Könnte ich dazu bitte mal das DeviceFile haben:
WebUi -> Internes -> Hilfe und dann steht da wie das geht. Das File hier einfach anhängen.

**Comment by thkl** [comment]
Btw: die beiden vorhandenen Services betätigen nur die interne Gerätetaste weil die halt als KEY Channel ankommt. Aber die kann ich dann ausblenden.

**Comment by ebjogot** [comment]
[HmIP-BBL.zip](https://github.com/thkl/hap-homematic/files/4694781/HmIP-BBL.zip)

Wow, das ging schnell. Anbei das DeviceFile. Musste ich leider zipen da ich kein .json anhängen kann.

Super cooles Projekt! Wenn es einen donate button gibt unterstütze ich gerne!

**Comment by mike4president** [comment]
Den gibt es :-) ganz oben ist ein Herz und daneben steht Sponsor...

**Comment by mike4president** [comment]
Hab ich auch schon draufgedrückt 🙃

**Comment by ebjogot** [comment]
Gefunden und gedrückt ;-)

**Comment by thkl** [comment]
Kurze Frage zu dem Gerät: Es gibt einen LEVEL_2 Datenpunkt. Dieser scheint das "Kippen" der Jalousie zu sein. Er geht von 0-1.01 ... Ich könnte das in HomeKit in den TiltAngle umsetzen.
Der wird aber von -90 bis +90. Wie soll ich das umrechnen ? HomeMatic 0 = -90 | 1 = 90 ???

**Comment by ebjogot** [comment]
Ja genau das ist die Lamellenposition.
In der CCU3 wird diese in 0%-100% umgesetzt. Halte ich für sinnvoll.
![F9F715B3-22D5-4BB5-856F-74ED2A9C6BE3](https://user-images.githubusercontent.com/66059037/83286986-29401300-a1e1-11ea-85cd-aaac474d2e50.png)
Also 0% = -90, 100% = 90
Gruß Björn

**Comment by roe1974** [comment]
geht das dann auch für den HM Jalousie Aktor ? (HM-LC-Ja1PBU-FM) ;-)
lg Richard

**Comment by thkl** [comment]
häng mal bitte das device file hier an

**Comment by thkl** [comment]
@ebjogot Frage wenn Du die Lamellenposition änderst, kommt da im WebUI das Working Zahnrad  analog dem Fahren der normalen Jalousie ?

**Comment by roe1974** [comment]
Anbei das Device File ... und ja, wenn ich die Lamelle verstelle kommt das "working Zahnrad" .... Sieht aber nicht wie oben aus ... ich habe noch einen "send" button ...
![grafik](https://user-images.githubusercontent.com/30420568/83298434-bb054b80-a1f4-11ea-8248-95eb44c4ff90.png)
[HM-LC-Ja1PBU-FM.txt](https://github.com/thkl/hap-homematic/files/4703921/HM-LC-Ja1PBU-FM.txt)

**Comment by ebjogot** [comment]
> @ebjogot Frage, wenn Du die Lamellenposition änderst, kommt da im WebUI das Working Zahnrad analog dem Fahren der normalen Jalousie ?

Nein ich kann einfach auf den Schieberegler klicken und schon läuft die Lamelle los.
Ein Working Zahnrad kann ich nicht entdecken.

**Comment by roe1974** [comment]
PS: prinzipiell geht der HM-LC-Ja1PBU-FM schon ... nur die Lammellen gehen nicht extra zum einstellen ... ist aber jetzt nicht ultra-notwendig ;) ... aber hast du das nicht schon mal probiert bei dem aktor mit negativem ergebnis ?
lg richard

**Comment by roe1974** [comment]
also bei meinen HM-LC-Ja1PBU-FM hat sich mit .44 nichts verändert ... hätte sollen ?
lg Richard

**Comment by thkl** [comment]
nein für den HM habe ich das noch nicht implementiert

**Comment by roe1974** [comment]
ok, war vorher auch schon (gerade getestet)
Wenn ich einen jalousie in HK schliesse .... bleibt der Staus zB auf "10% geöffnet" .... obwohl sie schon am schliessen ist.. dann verzögert um ein paar sekunden springt die anziege auf "wird geöffnet" (obwohl ich sie geschlossen habe) und bleibt so in dem zustand .... bis ich HK abschiesse und neu starte :(

**Comment by roe1974** [comment]
gerade rollback gemacht....
hier funktoniert noch alles normal:
https://github.com/thkl/hap-homematic/blob/1ba156b07f9cdb1ff6442c1b393eb576c9bca624/lib/services/HomeMaticBlindAccessory.js

ab hier ist der wurm drinnen (das inhibit update)
https://github.com/thkl/hap-homematic/blob/21f6cd6d81f2462beb6eca8df3a47ab62afb1569/lib/services/HomeMaticBlindAccessory.js

lg Richard

**Comment by roe1974** [comment]
PS: 100 pro funktioniert die version auch nicht ... hier wird nicht altualisiert wenn ich direkt am schlater die jalousie ändere :-/

**Comment by thkl** [comment]
die Inhibit Sache war schon vorher drin, ich habe die Funktionen der Klasse größtenteils aus dem homekit Projekt genommen.   Die Inhibit Steuerung hat nur eine Aktivierungsoption bekommen.

**Comment by roe1974** [comment]
hab dir mal ein video geschickt von dem verhalten ....

**Comment by ebjogot** [comment]
@thkl Vielen Dank für die schnelle Implementierung und das Update. 
Ich habe am Wochenende mal gespielt.
Grundsätzlich kann ich die Raffstoren anfahren. Leider fährt der Raffstore die Endposition an und dann jeweils ein Stück zurück. Entsprechend ist schließen und öffnen nicht möglich. 
Auch die Positionsanwahl (z.B. 80% geöffnet) ist nicht möglich. Fährt hoch (vermutlich um die Nullage zu ermitteln) und dann komplett wieder zu (bis auf das oben genannte Reststück).
Bislang also leider sehr eingeschränkt nutzbar. 

Kann ich dir Daten/Logfiles zur Verfügung um das zu fixen?

**Comment by artspe** [comment]
Danke @thkl für das klasse Projekt! Habe ein ähnliches Verhalten mit dem HMIP-BBL und der Behanghöhe sowie Lamelleneinstellung. Wenn ich über die eve App nur die Behanghöhe einstelle, fährt die Jalousie immer auf den eingestellten Wert und dann ein kleines Stück weiter. Das wird wohl die Lamellenposition sein. Stelle ich über die eve App nur den Wert für die Lamllenstellung ein, reagiert der Aktor erst gar nicht solange nicht danach auch die Behanghöhe eingestellt wird. Kann es damit zusammenhängen, dass in der CCU für den HMIP-BBL immer beide Parameter für Behanghöhe (LEVEL) und Lamellenposition (LEVEL_2) im Programm mitgegeben werden müssen? Das ist z. B. im Programm über die Kanalaktion L=100,L2=50 einzustellen. Möchte ich einen der Werte beim Anfahren einer Position ignorieren muss hier der Wert 101 mitgegeben werden.

**Comment by thkl** [comment]
Das kann gut sein. 
Ich habe solche Aktoren nicht da, daher ist das schwer zu testen. 

Also müssen immer beide Levels gesetzt werden ... zb 50% (Level) rauf und 10grad Lamellenposition (Level_2) das könnte ich entsprechend mal umbauen.

**Comment by thkl** [comment]
So, ich habe das mal geändert. Beim Betätigen der Rollos (LEVEL) setze ich die Lamellen (LEVEL_2) auf 1.01 und umgedreht ...

**Comment by artspe** [comment]
Hab ich eine Möglichkeit die Änderungen zu testen?

**Comment by artspe** [comment]
Hab die aktuelle .46 installiert und getestet und es ist noch ein Bug in der Einstellung des Aktors drin:
1. Einstellen der Behanghöhe über den Schieberegler Position auf z. B. 0% oder 100% (zu-auf)
2. Einstellen der Horizontalen Neigung auf z. B. -15%
Verhalten:
Lamellenposition bleibt unberücksichtigt und Horizontale Neigung wird auf den "alten" Wert zurückgesetzt. Ich muss ein zweites Mal mit den Tasten für die Horizontale Neigung den gewünschten Wert einstellen und erst dann fährt die Jalousie die Lamellenposition an.
Erwartetes Verhalten:
Lamellenposition wird beim ersten Einstellen der Horizontalen Neigung angefahren.

Ferner funktioniert das Anfahren von Behanghöhe in Kombination mit Lamellenposition (Horizontale Neigung) in Routinen nicht zuverlässig, wenn beide Werte in der Routine eingestellt werden. Als Beispiel:
Setzen der Position auf 0%, Horizontale Neigung auf -15%. Ich kann es noch nicht 100% Nachvollziehen, aber immer wieder kommt es vor, dass irgendeine Position angefahren wird und dabei die Horizontale Neigung ignoriert wird.

Vielleicht kannst Du Dir das nochmal ansehen. Was mir im Code noch aufgefallen ist und ggfls. für die Bestimmung der aktuellen Position der Jalousie sowie Lamellenposition relevant sein könnte. Die "richtige" Behanghöhe sowie Lamellenposition werden beim HMIP-BBL auf Kanal 3 übertragen. Kanal 4 ist der Aktorkanal und dann gibt es noch 2 virtuelle Kanäle 5 + 6.

**Comment by thkl** [comment]
Ja momentan sende ich auf dem nicht benutzten Datenpunkt ein 1,01 das heißt wenn die Höhe eingestellt wird, wird die Lamellenposition ignoriert und umgedreht. Dadurch klappt das mit den Routinen sicher nicht. 

Mangels Aktor muss ich da noch mal nachfragen: kann man die Datenpunkte einzeln setzen oder muss immer der 2. Datenpunkt mit gesetzt werden ? Denn einzeln wie vorher scheint ja nicht zu funktionieren. 

Ggf würde ich das setzen der HomeMatic Werte ein paar Millisekunden verzögern und in der Zeit auf den zweiten Wert aus HomeKit warten.

**Comment by artspe** [comment]
In der WebUI kann ich die Einstellungen einzeln für die Behanghöhe und Lamellenposition setzen. Die beiden Datenpunkte gemeinsam müssen nur in einem Programm gesetzt werden. Im Programm wird auf dem Parameter L die Behanghöhe gesetzt und auf L2 die Lamellenposition. Hier gibt es noch die beiden Besonderheiten mit Position oder Lamellenposition ignorieren (101) und "Letzter Wert" (100.5). Hab mal paar Infos und Screenshots angehängt.
![Jalousieaktor](https://user-images.githubusercontent.com/12343158/84139712-a9bc0a80-aa50-11ea-8430-24f470782fcb.JPG)
![Jalousieaktor_Programm](https://user-images.githubusercontent.com/12343158/84139727-af195500-aa50-11ea-81bf-a537787103fa.JPG)

**Comment by artspe** [comment]
Ich hab jetzt mal den Netzwerkmonitor mitlaufen lassen und denke das folgendes beim Einstellen der Werte passiert: Es werden die realen Werte Behanghöhe und Lamellenposition in Variablen gespeichert und dann immer beide Werte neu gesetzt. Egal ob nur die Behanghöhe oder Lamellenposition einzeln betätigt wird. Ausnahmen im Programm wo zusätzlich zum Wertebereich 0-100 die Werte 101 für Ignorieren sowie 100.5 für "Letzter Wert" gesetzt werden können.

Ich versuche mich in den nächsten Tagen mal mit debuggen...

**Comment by thkl** [comment]
Also ist die Idee mit den kurzen Delay und dem warten auf den 2. Wert (plus speichern der Werte für die jeweilig andere Einstellung keine dumme Idee 🙃)

**Comment by thkl** [comment]
mit obiger Änderung sollte das dann funktionieren

**Comment by artspe** [comment]
Interessant in dem Zusammenhang folgender Thread im [homematic Forum](https://homematic-forum.de/forum/viewtopic.php?f=60&t=59144). Es gibt wohl einen COMBINED_PARAMETER mit dem beide Werte gleichzeitig gesetzt werden müssen.

**Comment by thkl** [comment]
Na der combined ist das was das Programm ggf setzt. Seit dem Change oben setzte ich immer Level und Level_2 zusammen. Das wird immer auf den Wert aus HomeKit bzw. den gemerkten Wert für den anderen Parameter gestützt.  Das müsste mal getestet werden. 

Wenn das nicht tut dann mit Combined.

**Comment by thkl** [comment]
Funktioniert das mit .47 jetzt besser ?

**Comment by artspe** [comment]
Es funktioniert jetzt besser in Szenen. Wenn ich in einer Aktion Position und Horizontale Neigung einstelle, fährt die Jalousie beim Auslösen der Szene in die richtige Lage. Was noch nicht 100% funktioniert ist die manuelle Einstellung über die UI. Auch die Einstellung der Position auf 0% respektive 100% (geschlossen, offen) über den Schieberegler Position funktioniert. Hier wird automatisch die Horizontale Neigung auf -90° respektive 90° mit gesetzt.

Was noch nicht funktioniert ist die Verstellung der Lamellen, sobald nur die Pfeiltasten für die Horizontale Neigung angetippt werden. Aktion:
1. Jalousie steht auf Position 0% und Horizontale Neigung auf -90% (geschlossen)
2. Nur Einstellung der Horizontalen Neigung über Pfeiltasten auf z. B. -30° => Aktor löst nicht aus, Lamellen verbleiben in der "alten" Position, UI zeigt bei Horizontaler Neigung aber den "neuen" Wert -30° an.
3. Wenn ich jetzt nochmal die Position über den Schieberegler auf z. B. 50% ändere, fährt die Jalousie die Position an, allerdings wird die Horizontale Neigung auf 90° gesetzt.
4. Dann dritte Aktion Position auf 0% gesetzt => Jalousie fährt auf Position, allerdings werden die Lamellen auf die vorher eingestellten 30° gesetzt.

Da ist wohl noch irgendwo der Wurm drin...

Erwartetes Verhalten wäre: Lamellen werden auf den entsprechenden Wert eingestellt.

**Comment by thkl** [comment]
ok könntest du bitte mal über das WebUI / Internes das Debug Log einschalten. Dann diese Aktionen zu definierten Zeitpunkten ausführen und anschließend das Log downloaden.

Wichtig ist, das ich weiss zu welchem Zeitpunkt was gemacht wurde, was auch im Log sichtbar ist.

Die IP Blind Einträge im Log kann man mit [BLINDIP] seriennummer .... erkennen ...

**Comment by artspe** [comment]
[hap-homematic-log.txt](https://github.com/thkl/hap-homematic/files/4776833/hap-homematic-log.txt)
Folgende Aktionen. Ausgangsposition der Jalousie war geschlossen Position 0%, Horizontale Neigung -90°

1. Von Position 0% auf Position 100% (keine Einstellung der Horizontalen Neigung) => Endposition der Jalousie 100%, 90° (Position, Horizontale Neigung Lamellen)
2. Von Position 100% auf Position 0% (keine Einstellung der Horizontalen Neigung) => Endposition der Jalousie 0%, -90° (Position, Horizontale Neigung Lamellen)
3. Von Position 0% auf Horizontale Neigung -30° => keine Aktion
4. Von Position 0%, Horizontale Neigung -30° auf Position 49% => Endposition der Jalousie 49%, -18° (Position, Horizontale Neigung Lamellen)
5. Von Position 49%, Horizontale Neigung -18° auf Position 0% => Endposition der Jalousie 0%, -48° (Position, Horizontale Neigung Lamellen)

Hoffe das hilft weiter und Du kannst aus dem Log was rauslesen.

**Comment by thkl** [comment]
Danke ich kann das so im Log nachvollziehen. 
Ich habe auch schon gefunden, woran es liegen könnte.

**Comment by artspe** [comment]
Ich habe mal die aktuelle Version der HomeMaticBlindIPAccessory.js auf die CCU in das hap Verzeichnis kopiert. Ich denke, das reicht um den aktuellen Code zu testen. Die Lamellenverstellung habe ich noch nicht probiert, allerdings folgendes Verhalten beim Tap auf den Homekit Butten der Jalousie zum Öffnen bzw. Schließen. Schließen funktioniert aber beim Öffnen läuft die Jalousie mal wieder etwas unter die 100% Stellung. Hab mal das Log angehängt. Dort ist nach dem Öffnen auch die HK Position am Ende auf .925.
[hap-homematic-log.txt](https://github.com/thkl/hap-homematic/files/4842923/hap-homematic-log.txt)

**Comment by artspe** [comment]
Das Issue kann geschlossen werden.
