### ISSUE TITLE
Neustart

### ISSUE THREAD

**Issue by theo-69** [thkl/hap-homematic#97]
Dumme Frage gibt es die Möglichkeit die Instanzen oder generell HAP-Homatic neu zu starten ohne Homematic neu zu starten? Denn auch neue Geräte tauchen bei mir immer erst nach einem Neustart auf. Oder habe ich da was übersehen?

**Comment by roe1974** [comment]
CCU Cache aktualisieren ......
![grafik](https://user-images.githubusercontent.com/30420568/83331960-03764500-a299-11ea-9ab3-082fa6990845.png)

**Comment by theo-69** [comment]
ups soweit war ich wohl noch nie runtergescrollt

**Comment by thkl** [comment]
Hinzufügen neuer Geräte sollte eigentlich ein Cache Update triggern *hmm* Wenn die Geräte allerdings umbenannt und oder in Räumen verschoben werden, wird kein Event auf dem Interface von der CCU generiert und ich bekomme das nicht mit. Daher der manuelle Button.
