### ISSUE TITLE
HomeMaticSPGarageDoorAccessory - Aktor wird nicht zurückgesetzt

### ISSUE THREAD

**Issue by gorbi2001** [thkl/hap-homematic#98]
Hallo,

teste gerade die  Version 0.0.44 und habe als Aktor für das  HomeMaticSPGarageDoorAccessory einen HmIP-WGC Garagentortaster.
Dieser wird über HomeKit betätigt, aber dann nicht nach 5 Sekunden zurückgesetzt.
Sprich man muss ihn in der Raspberrymatic manuell auschalten.

Anbei ein Öffnen / Schliessen Vorgang (_mit zwischendurch manuellem abschalten des Tasters in Raspberrymatic_) aus dem hap-homematic.log

"[SPGDS] one actor mode send reset actor " taucht darin nicht auf.

Gruss
Norbert

[Mon Jun 01 2020 13:07:35 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] Garage Door Config: one sensor mode
[Mon Jun 01 2020 13:07:35 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] Sensor close  is HmIP-RF.0015599393F1CA:1.STATE
[Mon Jun 01 2020 13:07:35 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] Sensor close value is 0
[Mon Jun 01 2020 13:07:35 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] Garage Door Config: one actor mode
[Mon Jun 01 2020 13:07:36 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] Close sensor hm value is 0 set targetDoorState 1
[Mon Jun 01 2020 13:07:39 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] timer fired close sensor hm value is 0 set new current state 1
[Mon Jun 01 2020 13:08:36 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] HomeKit target message is 0 ...
[Mon Jun 01 2020 13:08:36 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] one actor mode send go message ...
[Mon Jun 01 2020 13:08:36 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] one actor mode send open ...
[Mon Jun 01 2020 13:08:36 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] send Actor Message true to HmIP-RF.00131A499B8D11:3.STATE
[Mon Jun 01 2020 13:08:38 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] Close sensor hm value is 1 set targetDoorState 0
[Mon Jun 01 2020 13:08:39 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] timer fired close sensor hm value is 1 set new current state 0
[Mon Jun 01 2020 13:09:06 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] garage door requery sensors ...
[Mon Jun 01 2020 13:09:06 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] Close sensor hm value is 1 set targetDoorState 0
[Mon Jun 01 2020 13:09:07 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] timer fired close sensor hm value is 1 set new current state 0
[Mon Jun 01 2020 13:09:36 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] HomeKit target message is 1 ...
[Mon Jun 01 2020 13:09:36 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] one actor mode send go message ...
[Mon Jun 01 2020 13:09:36 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] one actor mode send open ...
[Mon Jun 01 2020 13:09:36 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] send Actor Message true to HmIP-RF.00131A499B8D11:3.STATE
[Mon Jun 01 2020 13:09:54 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] Close sensor hm value is 0 set targetDoorState 1
[Mon Jun 01 2020 13:09:55 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] timer fired close sensor hm value is 0 set new current state 1
[Mon Jun 01 2020 13:10:06 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] garage door requery sensors ...
[Mon Jun 01 2020 13:10:06 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] Close sensor hm value is 0 set targetDoorState 1
[Mon Jun 01 2020 13:10:07 GMT+0200 (CEST)] debug - [HAP Server] [SPGDS] timer fired close sensor hm value is 0 set new current state 1

**Comment by thkl** [comment]
jib isn Bug, wie ich gerade sehe. Asl Workaround müsste es funktionieren die Nachricht für den Schließen Aktor auf den gleichen Wert wie für den Öffnen Aktor zu setzen

**Comment by rost2802** [comment]
Ich war auch schon am HmIP-WGC dran per besonderes Gerät. Hab nur das öffnen hinbekommen... schließen reagiert nicht.

<img width="1137" alt="Bildschirmfoto 2020-06-01 um 15 18 57" src="https://user-images.githubusercontent.com/59236127/83412921-3fd1ae80-a41b-11ea-8894-4920f1b539a8.png">

**Comment by thkl** [comment]
ja, der WGC Aktor ist ein wenig komisch. Aus einem anderen Projekt habe ich rausgefunden, das er am Besten funktioniert wenn man ihm vor dem Einschalten eine OnTime mit liefert. Dann funktioniert er wohl besser.

**Comment by gorbi2001** [comment]
Hi Thomas,

der workaround mit dem Schließen Aktor geht leider nicht.
Nachdem ich den Schliessen Aktors wieder entfernt habe,  incl. Neustart HAP,  wurde immer noch "two actor mode" gemeldet. Wenn man dann in Homekit auf das Garagentor klickt stirbt HAP.
Lösung: Neustart Raspi
Danach läuft wieder der "one actor mode".

Auch die Änderung der js Datei mit deinem Fix (close > open) bringt leider keine Änderung.
Aktor wird nicht zurückgesetzt.

Zu guter letzt wollte ich das Gerät neu anlegen. Also GarageDoorAccessory  gelöscht und neu erstellt.
Ergebnis fatal. HAB läuft, aber die WebUI zeigt nichts mehr an.
Alle HM Geräte sind da und bedienbar, nur nicht das GarageDoorAccessory
Alles neu gestartet, keine Änderung. Auch ein Bug wie es scheint. :(

Haste eine Idee bevor ich es plätte ?

<img width="1424" alt="Bildschirmfoto 2020-06-02 um 19 44 28" src="https://user-images.githubusercontent.com/32872296/83552084-80a7f100-a509-11ea-9eb7-4b6b1b805a29.png">

**Comment by thkl** [comment]
kannst du mal in der browser console schauen ob da irgendwelche errors auflaufen

**Comment by thkl** [comment]
ps: wenn du magst kannst du mir auch mal das backup deiner config schicken, dann schau ich mal was da schief läuft. Mailadresse steht im header von jedem .js file

**Comment by thkl** [comment]
das wäre die Config für den HmIP-WGC mit einer 2Sek onTime bevor der Aktor sich selbst wieder zurücksetzt.

![image](https://user-images.githubusercontent.com/884355/83672377-7273d680-a5d6-11ea-88c0-e437675f29d1.png)

**Comment by Sheldor81** [comment]
Bei mir funktioniert es so nicht und wenn ich die offene Garage schließe stürzt das ganze HAP ab.

**Comment by thkl** [comment]
siehe Edit oben ;)

**Comment by Sheldor81** [comment]
Öffnen funktioniert jetzt und der Autor wird auch zurück gesetzt, nur schließen lässt sie sich nicht.

**Comment by roe1974** [comment]
@gorbi2001 .... sind die rollos oben aus dem screenshot auch homematic geräte mit HAP
in homekit gebracht ?

**Comment by thkl** [comment]
aber Schließen ist doch im OneActor Mode das gleiche da wird der "Öffnen" Aktor nur wieder angeschubbst

**Comment by Sheldor81** [comment]
habe noch einmal neugestartet, jetzt funktioniert es.

**Comment by Sheldor81** [comment]
Danke

**Comment by thkl** [comment]
> habe noch einmal neugestartet, jetzt funktioniert es.

Mit dem HmIP-WGC und dem geänderten File aus dem Commit ?

**Comment by Sheldor81** [comment]
genau, werde es aber morgen noch einmal in Ruhe testen und dann bescheid geben.

**Comment by gorbi2001** [comment]
@roe1974 
Japp, alles Homematic. Die Rolloaktoren sind HM-LC-Bl1PBU-FM

**Comment by roe1974** [comment]
@gorbi2001  .... und wenn ganz geöffnet steht da „geöffnet“ ???
bei mir steht da „öffnen“ ......
ist bei mir aber der HM-LC-Ja1PBU-FM

**Comment by roe1974** [comment]
ist das iOS aktuell ?

**Comment by gorbi2001** [comment]
@roe1974 
Da muss Apple mal an der Übersetzung arbeiten.
Schalte mal die Sprache von Deinem IPhone/IPad auf Englisch.
Dann steht da Open und während dem öffnen steht opening.


![BE57BB81-376B-4DB2-8052-9F0E5DAF4262](https://user-images.githubusercontent.com/32872296/83681373-9a693700-a5e2-11ea-8187-a53c2ee52a1b.jpeg)

**Comment by roe1974** [comment]
aber oben in deinem screenshot war doch deutsch .... und „geöffnet „ bei der Küchen Rollo ?!?!

**Comment by thkl** [comment]
Herrschaften, würdet ihr bitte den Garagentor Issue hier nicht zuspammen ? Ich verliere slightly den Überblick !

**Comment by Sheldor81** [comment]
So, habe das ganze noch einmal getestet und leider läuft es doch noch nicht ganz rund.

Beim öffnen funktioniert es, da wird der Aktor zurück gesetzt. Doch beim schließen leider nicht.

<img width="550" alt="Bildschirmfoto 2020-06-05 um 14 49 39" src="https://user-images.githubusercontent.com/37243683/83878223-15923080-a73c-11ea-8f64-d4a5b485d0e6.png">

**Comment by Sheldor81** [comment]
So, ich habe das ganze noch einmal getestet. Dabei ist mir aufgefallen das es beim öffnen wie gewünscht funktioniert. Doch beim schließen wird der Aktor immer noch nicht zurück gesetzt.

<img width="656" alt="Bildschirmfoto 2020-06-05 um 14 53 51" src="https://user-images.githubusercontent.com/37243683/83878391-6570f780-a73c-11ea-9f62-2c63b453daf6.png">

**Comment by Sheldor81** [comment]
und ich habe beim auslösen der Schließvorgangs eine Push-Nachricht das die Garage geöffnet und eine das sie geschlossen wird bekommen.

**Comment by gorbi2001** [comment]
@Sheldor81 
Bei Nachricht Schließen Aktor steht nicht OnTime in Deinem Screenshot.
Für den WGC reicht es auch nur den Öffnen Aktor zu setzen = One Actor Mode

**Comment by Sheldor81** [comment]
HI, das habe ich angepasst. Aber jetzt sind alle Geräte aus HAP verschwunden steuern lassen sich aber noch alle außer die Garage

**Comment by thkl** [comment]
Das Problem hatten wir schon hier .. das ist ein "bug" im GaragenService, der wird mit kaputter config.json nicht richtig geladen und damit stirbt auch die Funktion die die Geräte für das UI bereitstellt. Mail mir mal die config.json

**Comment by Sheldor81** [comment]
im welchen Verzeichnis liegt die config.json und wie ist deine Mail Adresse

**Comment by thkl** [comment]
/usr/etc/config/addons/hap-homematic/  und mail steht im header jeder Datei hier bsp https://github.com/thkl/hap-homematic/blob/master/lib/HomeMaticAddress.js

**Comment by MattN82** [comment]
ÖHm...sorry, wenn ich das verkrame...und es könnte auch sehr gut sein, dass ich grad den Wald vor lauter Bäumen nicht sehe....aber könnte mir auch mal jemand bitte auf die Sprünge helfen?

Meine config sieht jetzt so aus wie bei sheldor weiter oben:

![screenshot](https://user-images.githubusercontent.com/66356925/87223781-0710e780-c380-11ea-801f-37a6bb9911ea.png)

Und bei mir geht NICHTS. Die Garage macht keinen Mucks, der Status wird in HomeKit immer als "geöffnet" angezeigt, völlig egal was für Permutationen von 1,0,true,false ich bei "Status/Wert Sensor" eintrage.

**Comment by thkl** [comment]
* Status des Schließen Sensors muss auf true stehen  (wenn der Sensor so angebaut ist, das er bei geschlossenem Tor auslöst)
* Wenn kein "Offen Sensor" existiert dann muss da auch kein Wert rein
* der WGC muss nur beim Öffnen Aktor stehen da er dann auch fürs Schließen benutzt wird

Dann sollte es passen.

**Comment by MattN82** [comment]
Eben genauso durchgeführt. Ergebnis: Alle Instanzen und alle Geräte weg

**Comment by thkl** [comment]
*seufz* dann ist die config.json kaputt .. mail mir die mal bitte

**Comment by MattN82** [comment]
Ich befürchte da muss ich jetzt noch eine Wissenslücke offenbaren: Meine Raspberrymatic läuft inner VM im Synology Virtual Machine Manager.

Wie....komm ich da ran?

**Comment by thkl** [comment]
per sftp auf die IP der RM .. User ist root Password das für den SSH Access auf die CCU.
Ordner ist /usr/local/etc/config/addons/hap-homematic

**Comment by thkl** [comment]
Ich hab das eben mal mit einem SWDO und einem "emulierten" WGC ausprobiert.
Das wären die Einstellungen. (Die Auswählen Buttons sind Beta nicht verunsichern lassen)

![garage_door_wgc_swdo](https://user-images.githubusercontent.com/884355/87224295-7688d600-c384-11ea-89fe-57b3354e378e.png)

**Comment by MattN82** [comment]
Bin per Forklift drauf....ging :-) 

config.json hab ich dir geschickt

**Comment by MattN82** [comment]
Neues Problem (bei dem ich mir grad nicht erklären kann wo es herkommt:

Nach erneutem einloggen per sftp via forklift ist der von dir oben genannte Ordnerlink leer. Kein Inhalt.
Er hatte aber einen Inhalt...sonst hätte ich dir ja die config.json nicht rausziehen können.

Alter was ist denn heute wieder los?? oO

**Comment by MattN82** [comment]
Ok, mit der config.json, die du mir geschickt hast, läuft das System wieder.

Allerdings wird bei der Konfiguration unter "besondere gerate" in deiner config.json die Garage in HomeKit als "nicht unterstützt" angezeigt.

Wenn ich dann deine Werte aus dem obigen Screenshot eintrage (Sensoradresse bei "Adresse Schließen Sensor" anstatt bei "Adresse offen Sensor" wie in der config.json), dann verschwinden die Geräte zwar nicht wie beim ersten Mal, werden aber alle in HomeKit als "nicht erreichbar" angezeigt.

In Kurz: Verwende ich deine config.json, geht alles aber Garage: Nicht unterstützt. Repliziere ich deine Einstellungen aus dem Screenshot: Alle Geräte in HomeKit "keine Antwort" (in der WebUI von hap-homematic sind sie aber noch da).

Heut scheint mal wieder einer dieser Tage zu sein :-D

**Comment by thkl** [comment]
ich hab das auf dem Testsystem ausprobiert. Das ist schon etwas weiter als die aktuelle npm Version.
Ich klöppel mir mal bei Gelegenheit eine virtuelle RM zusammen und schau mal was in der aktuellen Version kaputt geht.

Also erst mal keine Garage, aber die kommt schon noch ;o)

**Comment by MattN82** [comment]
Alles klar :-) Ich warte geduldig. Ich weiß ich wiederhol mich aber: Ich hab einen Heidenrespekt vor dem was du hier machst! Ich hab das Gefühl alle bisherigen "ich flansch Homematic IRGENDWIE an HomeKit dran"-Lösungen sind/waren "Knüppel". Und du baust hier ein Skalpell.

Echt...Hut ab!

**Comment by MattN82** [comment]
Verständnisfrage: Habe eben auf 0.0.48 upgedatet und das changelog nennt u.a. die Selektoren bei "Garage" als Neuerung, sowie "Bugfixes".

Besteht noch die Gefahr, dass ich mir die config zerschieße, wenn ich nochmal das obige Prozedere ausprobiere?
Also...:-)...dass sich das nicht ganz ausschließen lässt, ist mir klar. Es ist mehr die Frage ob die "Bugfixes" die Wahrscheinlichkeit reduziert haben.

**Comment by thkl** [comment]
Das Garagentor hat noch einen kleinen Fehler https://github.com/thkl/hap-homematic/issues/143 der sich aber umgehen lässt. 

Für einige scheint die Config in .48 nicht zu funktionieren, was ich aber noch nicht nachvollziehen kann. (#142)

**Comment by BenjiKingKenji** [comment]
> Ich war auch schon am HmIP-WGC dran per besonderes Gerät. Hab nur das öffnen hinbekommen... schließen reagiert nicht.
> 
> <img alt="Bildschirmfoto 2020-06-01 um 15 18 57" width="1137" src="https://user-images.githubusercontent.com/59236127/83412921-3fd1ae80-a41b-11ea-8894-4920f1b539a8.png">

Hallo Zusammen :) 
Ich habe mich hier mal durchgelesen und sehe immer den gleichen Screenshot auf dem man sieht, dass man recht viele Optionen angeben kann für den Garagentortaster.
Ich habe dies aber nicht; bzw. werden mir nur 4 Optionen angezeigt... Gibt es da irgendwelche versteckte Optionen ? Oder habe ich doch einen anderen Taster im Gebrauch als Ihr...? Unten Screenshots von meinem Gerät und die auswählbaren Optionen.
Danke im Voraus :)

<img width="1413" alt="Screenshot 2021-01-10 at 17 45 34" src="https://user-images.githubusercontent.com/4267523/104129218-2955e300-536c-11eb-9faa-195137bb76ab.png">
<img width="1227" alt="Screenshot 2021-01-10 at 17 45 50" src="https://user-images.githubusercontent.com/4267523/104129222-2e1a9700-536c-11eb-9667-b0c1c94108ed.png">
<img width="894" alt="Screenshot 2021-01-10 at 17 47 06" src="https://user-images.githubusercontent.com/4267523/104129227-31ae1e00-536c-11eb-8fdf-112fee54ac66.png">

**Comment by thkl** [comment]
Das Garagentor, welches aus diversen Sensoren und Aktoren zusammengesetzt wird, ist unter Besondere Geräte zu finden. 

Da liegt alles, was nicht direkt aus einem HM Channel erzeugt wird.

**Comment by BenjiKingKenji** [comment]
> * Status des Schließen Sensors muss auf true stehen  (wenn der Sensor so angebaut ist, das er bei geschlossenem Tor auslöst)
> * Wenn kein "Offen Sensor" existiert dann muss da auch kein Wert rein
> * der WGC muss nur beim Öffnen Aktor stehen da er dann auch fürs Schließen benutzt wird
> 
> Dann sollte es passen.

Danke habs gefunden :)

Wenn Ich den "State close sensor" auf true setze, zeigt er mir an dass das Tor offen ist und öffnet sich auch nicht bei Knopfdruck... 

LG Marco

![IMG_A359B94EF26C-1](https://user-images.githubusercontent.com/4267523/104132751-9f177a00-537f-11eb-8384-f7076154f655.jpeg)


LG

**Comment by FlippiHimself** [comment]
Guten Tag,

Ich habe mir mal die Mühe gemacht und verschiedene Einstellungen getestet, da die Einstellungen die hier vorgeschlagen werden nicht funktionieren...

**1. Garage wird als geöffnet angezeigt.**
Hier die Einstellungen im HAP-Homematic:
State close sensor auf: **true** und state open sensor auf: **true**

<img width="727" alt="Screenshot 2021-01-15 at 08 11 30" src="https://user-images.githubusercontent.com/4267523/104694462-7ee31480-570b-11eb-807e-e274433b9d34.png">

**Resultat:**
Als allererstes wird das Garagentor als geöffnet angezeigt. Wichtig hier: **Das Garagentor ist derzeitig geschlossen**.
![IMG_4113](https://user-images.githubusercontent.com/4267523/104694579-b225a380-570b-11eb-9cbb-1090c16912fb.PNG)
Nachdem man dann auf das Garagentor-Icon drückt, passiert natürlich nichts, da versucht wird die Garage zu schliessen aber schon der Fall ist:
![IMG_4114](https://user-images.githubusercontent.com/4267523/104694582-b487fd80-570b-11eb-933a-e51ca3d4c3fc.PNG)

**2. Garage wird als offen angezeigt / lässt sich aber teilweise betätigen**
Hier die Einstellungen im HAP-Homematic:
State close sensor auf: **true** und state open sensor auf: **false**

<img width="733" alt="Screenshot 2021-01-15 at 08 32 28" src="https://user-images.githubusercontent.com/4267523/104695276-c5853e80-570c-11eb-8bce-d96cb16a6fc2.png">

**Resultat:**
1. Status(Homekit) ist immer noch offen (Garage ist zu)
2. Einmal betätigen (Homekit Taster auf dem iPhone betätigen): Zeigt "closing..." an und beim nochmal betätigen zeigt Homekit "opening..." an und das Tor öffnet.
3. Garagentor offen (Satus bei Homekit auch auf "offen"): Jetzt will man das Tor schliessen
4. Einmal betätigen: Zeigt "closing..." passiert aber nichts -> erst nachdem man sofort nochmal betätigt Homekit immer noch "closing..." an, aber das Garagentor schliesst.

**3. Garage wird als offen angezeigt / lässt sich aber teilweise betätigen**
Hier die Einstellungen im HAP-Homematic:
State close sensor auf: **false** und state open sensor auf: **false**

<img width="736" alt="Screenshot 2021-01-15 at 08 40 54" src="https://user-images.githubusercontent.com/4267523/104695675-696eea00-570d-11eb-999f-5924d0645ae1.png">

**Resultat:**
1. Status (Homekit) ist immer noch offen (Garage ist zu)
2. Einmal betätigen passiert nicht (ausser: closing...) Nochmal betätigen dann auf "opening..." und Garagentor öffnet
3. Garagentor jetzt offen - Homekit zeigt auch offen
4. Einmal betätigen zum schliessen: Homekit zeigt "closing..." aber nix passiert. Nochmal betätigen schliesst das Tor dann obwohl Homekit "opening..." anzeigt -> Garagentor jetzt geschlossen aber wird wieder wie am Anfang als offen angezeigt

**4. Garage wird als offen angezeigt / lässt sich aber teilweise betätigen**
Hier die Einstellungen im HAP-Homematic:
State close sensor auf: **false** und state open sensor auf: **true**

<img width="734" alt="Screenshot 2021-01-15 at 08 46 13" src="https://user-images.githubusercontent.com/4267523/104696195-2b25fa80-570e-11eb-910c-80005530b062.png">

**Resultat:**
1. Status (Homekit) ist immer noch offen (Garage ist zu)
2. Einmal betätigen passiert nicht (ausser: closing...) Nochmal betätigen dann auf "opening..." und Garagentor öffnet
3. Garagentor jetzt offen - Homekit zeigt auch offen
4. Einmal betätigen zum schliessen: Homekit zeigt "closing..." aber nix passiert. Nochmal betätigen schliesst das Tor dann obwohl Homekit "opening..." anzeigt -> Garagentor jetzt geschlossen aber wird wieder wie am Anfang als offen angezeigt

Ich habe hier soweit alle Möglichkeiten getestet aber das Garagentor lässt sich erst schliessen/öffnen wenn man sozusagen einen Doppelklick macht (Punkt 2. in den Beispielen). Garagentor wird aber immer als offen angezeigt. 
Ich hoffe diese kleine Analyse hilft, diese Funktion nochmal unter die Lupe zu nehmen; denn es scheint doch noch nicht richtig zu funktionieren. 
PS: Kleine Überlegung: Würde es mit einem Magnetkontakt der die Offen-Stellung des Garagentores wiedergibt eventuell besser funktionieren...?

Ich würde mich freuen wenn nach diesem Problem gekuckt wird; ich bin auch weiterhin bereit weitere Tests, Logs usw. bereitzustellen, sofern es dem Projekt weiterhilft.

LG Marco

**Comment by Cellebyte** [comment]
> Hi. Bin erst seit ein paar Tagen Umsteiger von der Cloud App zur Raspberrymatic auf CCU3 und danke eurem Forum schon mal für die Hilfe. Garagentor war für mich auch ein Thema. Hatte es schon immer mit der Schaltplatine HMIP-PCBS parallel zum originalen Taster und dem Fensterkontakt HMIP-SWDO (findet optisch den Schlitten)gelöst. Diese habe ich jetzt in HAP umgesetzt und nach einigem Basteln funktioniert folgende Config. Wichtig war es, die Abfragezeit solange zu setzen, wie das Tor fährt und so wie ich es sehe, gibt der SWDO 0 und 200 raus. Teile mein Ergebnis einfach mal, falls das völliger Mumpitz ist, bitte nicht steinigen ;) Aber bei mir läuft es.... LG, Denis ![2021-10-25 18_09_17-](https://user-images.githubusercontent.com/93145335/138732338-0c379ce6-2e5a-4104-97d3-7ce40c546577.jpg)

Habe ewig gesucht und jetzt tut es auch bei mir.
Lag tatsächlich am HMIP-SWDO State.
