### ISSUE TITLE
HMIP Wired Jalousie-/Rollladenaktoren

### ISSUE THREAD

**Issue by MattN82** [thkl/hap-homematic#99]
Hallo,

ich hab mir extra einen Account gemacht um das zu posten. Warum betone ich das? Weil ich seit Jahren auf GitHub Smarthome-Softwareprojekte ausprobiere und noch nie die Notwendigkeit dafür gesehen hab...bis jetzt.Noch kein Projekt war so Arsch auf Eimer wie das hier :-) GANZ TOLL! Ich hab mich GERNE angemeldet, um beim Feedback mitmachen zu können. :-)

Ich habe mit Freuden festgestellt, dass seit einem der neusten Updates nun auch die HMIP Wired Jalousie- und Rollladenaktor angezeigt werden, samt "Untergeräten".

Habs auch gleich ausprobiert aber: Keine Reaktion in HomeKit. Hab exemplarisch einen meiner Rollläden genommen (kann es sein, dass hap-homematic Status- und Aktorkanäle zu EINEM "Gerät" zusammenfasst).
Viel zu konfigurieren gibts ja nicht, daher schließe ich Bedienfehler erstmal aus.

Resultat ist wie gesagt: Gerät wird in HomeKit angezeigt, wechselt auch seinen Status beim daraufklicken, aber der physische Rollladen macht keinen Mucks.

Die althergebrachte Bastellösung mit Iobroker und Yahka (die ich btw nur noch für die Rollladen brauch....DANKE dafür nochmal thkl!) funktioniert nach wie vor einwandfrei.

Ich wünsche dir, thkl, und uns allen dass dieses Projekt Bestand hat und sich so grandios weiterentwickelt wie es momentan den Eindruck macht!

**Comment by thkl** [comment]
Welches Gerät ist das ? Ich habe  bisher  die HmIP-BBL angefasst. Kann sein das durch gleiche Channeltypen auch andere Geräte auswählbar sind. Wenn es nicht der BBl ist bitte mal im WebUi unter Internes/Hilfe wie dort beschrieben das Devicefile erzeugen und hier anhängen.

**Comment by MattN82** [comment]
Hallo und Danke für die schnelle Antwort. Öhm...ich bin Bedienungstechnisch neu hier....beim Versuch das .json-file hier im Thread anzuhängen, kommt "we don't support that file type".

Was mach ich falsch?

**Comment by thkl** [comment]
Nix umbenennen auf .txt hilft.  
Ich werde mal noch die Download Funktion für das File anpassen das da .txt rausfällt (obwohl der Inhalt der gleiche bleibt)

**Comment by MattN82** [comment]
Alles klar :-)

Bitteschön:
[HmIPW-DRBL4.txt](https://github.com/thkl/hap-homematic/files/4722364/HmIPW-DRBL4.txt)

**Comment by thkl** [comment]
ok, schau ich mir mal an .. ich hab die Dinger nicht aber irgendwie wird das schon

**Comment by thkl** [comment]
Achja die Rollos haben ja alle diese 3 virtuellen Kanäle pro Gerät. In den Gerätesettings in der CCU können ja aus den 3 Kanälen dann via Einstellung die "realen" Werte zusammengesetzt werden. Wenn das nicht benutzt wird dann den ersten virtuellen Kanal nehmen der heisst BLIND_VIRTUAL_RECEIVER und müsste soweit ich das sehe Channel 2 sein.

**Comment by MattN82** [comment]
Ich bin nicht so ganz sicher ob ich bei diesen Kanälen/deren Zuweisungen durchsteig.

Was ich dir sagen kann ist, dass z.b. mein Schlafzimmerrollladen bei diesem Gerät auf Kanal 5 und 6 liegt (Statusmitteilungen und Autor), mir aber hap-homematic diese Kanäle 5 und 6 nicht anzeigt, sondern EINEN Eintrag mit "Rollladen Schlafzimmer". Nur die nichtzugewiesenen Kanäle (infolgedessen unbenannt) werden mir mit Kanal angezeigt.

Falls das irgendwie hilft

**Comment by thkl** [comment]
AH ich sehe gerade das kann nicht funktionieren. Ich lege den Aktor fest auf Channel 4.
Da muss ich eine kleine Anpassung für das Wired Gerät machen, aber das ist keine große Sache.

**Comment by MattN82** [comment]
Wow, das klingt schonmal gut. Ich bin gespannt, mach dir aber keinen Stress. Ich habe monatelang mit Bastellösungen gelebt, ich bin mittlerweile mit Geduld gesegnet :-)

**Comment by thkl** [comment]
Naja HomeMatic ist ja wohl literally ne Bastellösung

**Comment by MattN82** [comment]
Touché...aber flansch da noch Raspberrymatic in ner Synology VM und den Iobroker drauf und wir sind irgendwie in der Sphäre "Wow...es...funktioniert wirklich" unterwegs :-D

**Comment by mike4president** [comment]
Ganz ehrlich, wenn eQ-3 endlich mal seine Hausaufgaben machen würde, dann brächten die meisten keine Bastellösung. Die CCU hätte so viel Potenzial... Ich verstehe überhaupt nicht, wie das Unternehmen so lange seine Nutzerwünsche ignoriert und trotzdem noch erfolgreich ist. Die Hue Integration ist ein Witz. Wie kann man 2020 mit so einem UI an den Start gehen. Im Forum von Homee stand, dass man sich nicht einig geworden wäre... es gibt so viele gute Ansätze. Aus meiner Sicht gibt es bisher halt keine guten Alternativen, die so vielfältig sind. Und diese ganzen Spielzeuglösungen sind keine gute Investition in die Zukunft. Schaut euch mal dieses Video des Produktmanagers an. 

https://m.youtube.com/watch?feature=youtu.be&v=yaOXOH7VUFQ

Das ist exemplarisch für was da schief läuft. 

„Das ist nicht so einfach... und ist das bewusst... bla bla bla...“ die sollten mal bisschen mehr Zeit in ihre Softwareentwicklung stecken... oder Thomas fad machen lassen. 

Sorry musste mal raus... 🧨 hatte heute noch keinen Kaffee

**Comment by MattN82** [comment]
Ich sag nur: Hutschienen-Leistungsmessung bei HMIP wired.

Ist mir völlig unbegreiflich, warum es das nicht gibt bzw. nicht direkt in HMIP wired integriert wurde. Hutschienen-Leistungsmessung gibts für klassische Homematic seit Jahren

**Comment by mike4president** [comment]
Die neue HomeMatic IP App ist auch ein schlechter Scherz. Und für die CCU gibt es Pocket Control wovon ich kein Fan bin... 

Ich habe die schon paarmal angeschrieben aber man bekommt immer die gleiche standardisierter Antwort. HomeMatic: eine Hassliebe. Ich hab erst etwas Seelenfrieden seit ich HAP entdeckt habe... 

Ich hab eQ-3 auch gefragt, warum sie von freien Entwicklern links und rechts überholt werden. Raspberrymatic ist ja auch nur ein engagierter Entwickler: Jens Maus. 

Ich glaube nicht mehr dran, dass sie die nächsten Dekade da groß irgendwas ändern wird

**Comment by mike4president** [comment]
Aber okay, gehört nicht in diese Issue. Müssen wir ein neues für aufmachen 🙃

**Comment by thkl** [comment]
Wenn jemand die HmIPW Blinds testen möchte, wichtig sind nur die Änderungen ( https://github.com/thkl/hap-homematic/commit/38419d6cec9c1697b788c61544080ac30ab3a7fe#diff-ca37f16e4e361a391301f1dfd633f0e3) im File lib/services/HomeMaticBlindIPAccessory.js 

Der Rest des Commits oben sind automatische Tests für das Ding. Es wird für den Aktor nicht mehr Kanal 4 fest angenommen sondern wirklich der, den man ausgewählt hat.

**Comment by MattN82** [comment]
Ich würd dir gerne anbieten es zu testen...so es in meiner Macht / meinen technischen Fertigkeiten liegt.  Ich....bin zu neu hier um zu wissen "wie" :-)

**Comment by MattN82** [comment]
Falls es hilfreich ist / interessiert: Ich habe auf die 0.0.46 upgedatet und die Rollläden funktionieren jetzt. Erstaunlich gut sogar. Selbst die Richtungsanzeige (öffnet/schließt) wird korrekt erkannt, was bei meiner Iosbroker-Variante nicht der Fall war.

Das einzige was mir auffällt: Im komplett geöffneten / geschlossenen Zustand zeigt das Icon "öffnen" und "schließen" anstelle von "offen" und "geschlossen".

Das war aber auch bei Iobroker schon so, von daher kann ich nicht sagen, ob es eine Einstellungssache oder ein generischen Homekitproblem ist.

Alles in allem: TOP!!!!! DANKE!!!! :-)

**Comment by thkl** [comment]
Das ist, soweit wir das bisher ermitteln konnten ein Übersetzungsfehler in HomeKit. Wenn das Phone auf englisch steht dann wird Open und Close angezeigt

**Comment by mike4president** [comment]
> Falls es hilfreich ist / interessiert: Ich habe auf die 0.0.46 upgedatet und die Rollläden funktionieren jetzt. Erstaunlich gut sogar. Selbst die Richtungsanzeige (öffnet/schließt) wird korrekt erkannt, was bei meiner Iobroker-Variante nicht der Fall war.
> 
> Das einzige was mir auffällt: Im komplett geöffneten / geschlossenen Zustand zeigt das Icon "öffnen" und "schließen" anstelle von "offen" und "geschlossen".
> 
> Das war aber auch bei Iobroker schon so, von daher kann ich nicht sagen, ob es eine Einstellungssache oder ein generischen Homekitproblem ist.
> 
> Alles in allem: TOP!!!!! DANKE!!!! :-)

also mich interessiert es ;-) 

ist eine Fehler in iOS 13. bei macOS wird es richtig angezeigt....

https://community.hom.ee/t/roller-shutter-3-status-geoeffnet-fehlt-in-homekit/25932/20

<img width="413" alt="Bildschirmfoto 2020-06-08 um 17 15 04" src="https://user-images.githubusercontent.com/65063329/84047489-9dca3d00-a9ab-11ea-9c71-183c4d6fb8f6.png">
